"""Owner-focused return review library. Re-run after rebuilding the blog index."""
import csv
import re
import site_template as T

DATE = '2026-09-26'
HUB = '/tax-return-mistakes/'
POSTS = [
dict(slug='tax-preparer-made-mistake-business-rental-return',
title='Tax Preparer Made a Mistake? An Owner’s Next Steps',
description='Found a possible mistake on a business or rental tax return? Gather the evidence, separate filing errors from planning choices and map the correction.',
lead='If you think your tax preparer made a mistake on a business or rental return, get the filed return and supporting records, identify the exact discrepancy, and request a written explanation. The next step depends on whether the issue is an incorrect return, a payment posting problem, missing information or a reasonable tax position.',
sources=[('https://www.irs.gov/taxtopics/tc254','IRS Topic 254: choosing a tax return preparer'),('https://www.irs.gov/taxtopics/tc308','IRS Topic 308: amended returns')],
body='''<h2>Describe the difference before assigning fault</h2>
<p>“My refund is smaller” does not identify an error. “The rental ledger shows $12,000 of repairs, but the return workpaper shows $21,000 and I cannot reconcile the difference” is a reviewable question. State the tax year, entity, property, return schedule, disputed amount and source document. Ask the preparer to show the reconciliation and explain any adjustment.</p>
<p>An owner may have provided an incomplete ledger. A bookkeeper may have duplicated a transaction. A preparer may have entered a figure incorrectly. The return may also reflect a limitation or election that was not explained clearly. These are different problems. A second advisor should establish what happened before describing the return as wrong or promising a refund.</p>
<h2>Build a small evidence packet</h2>
<ul><li>The complete filed federal and state returns, including schedules and filing acknowledgments.</li><li>The source record that conflicts with the return and the version originally supplied to the preparer.</li><li>Relevant bookkeeping adjustments, depreciation schedules, basis worksheets and carryforward records.</li><li>Any IRS or state notice, including its response date and envelope.</li><li>The engagement letter and messages discussing the disputed item.</li></ul>
<p>Use a secure document portal. Preserve original files and put proposed corrections in a separate copy. Record which return version was actually filed; a draft containing the right number does not establish what the taxing authority received.</p>
<h2>Example: the same expense appears twice</h2>
<p>Suppose a practice owner sees a $4,800 software purchase in both the credit-card expense report and a bank payment category. That is a hypothetical bookkeeping warning, not proof that the filed return deducted $9,600. The accountant may already have removed the duplicate in a year-end adjustment. Request the adjusted trial balance and the expense total used on the return. If the duplicate survived, quantify the correction and identify every affected filing.</p>
<h2>Ask for a correction map</h2>
<p>A useful response lists the established facts, unresolved questions, affected years, proposed procedure, expected tax direction and who is responsible for each step. Individual amended returns, entity corrections, payment tracing and accounting-method corrections are different procedures. For partnerships, the applicable correction process can depend on the partnership’s filing regime. Do not submit an individual amendment before understanding whether an entity-level correction is required.</p>
<p>The IRS explains that taxpayers remain responsible for return accuracy even when they hire a preparer. That does not answer who should bear preparation costs or whether a preparer has contractual responsibility. Discuss fees separately from the action needed to protect a response or filing deadline. Keep notices moving while the parties resolve responsibility.</p>
<h2>When a second opinion helps</h2>
<p>Seek an independent review if the numerical explanation is still missing, several years may be affected, or the advisor cannot explain the proposed procedure. Request a defined review scope and written findings. An ordinary mistake is different from suspected unauthorized changes or misconduct; describe the evidence accurately. Start with a <a href="/business-tax-return-lookback-review/">business return lookback review</a> and use the <a href="/tax-return-mistakes/">mistake library</a> to identify the specific issue.</p>'''),
dict(slug='review-business-rental-tax-return-before-signing',
title='Review Your Business and Rental Return Before Signing',
description='A practical pre-signing tax return review for owners: check entities, rental properties, payments, asset changes and the final filing authorization.',
lead='Before signing a tax return authorization, review the complete proposed return against an owner-prepared list of entities, properties, major transactions and payments. A refund or balance-due summary cannot show whether the business and rental schedules are complete.',
sources=[('https://www.irs.gov/forms-pubs/about-form-8879','IRS: Form 8879, e-file signature authorization')],
body='''<h2>Start with a one-page change list</h2>
<p>Write down what changed during the year: a new company, ownership transfer, property purchase, property sale, refinancing, large equipment purchase, new state activity or change in rental use. Next to each event, identify the supporting document and the return schedule or workpaper where the preparer addressed it. This helps you review facts you know without pretending to recreate the entire tax calculation.</p>
<p>Ask for the complete review copy early enough to resolve questions. Confirm that the tax year, taxpayer name and entity classification are right. For an owner with several LLCs, distinguish the legal entity from the return on which its activity is reported. An LLC name alone does not establish its federal tax classification.</p>
<h2>Reconcile the business and property list</h2>
<p>Compare the businesses and rentals you actually operated or owned with the schedules in the packet. Look for an omitted property, a sold building that remains on the active asset list, or an ownership percentage that has not changed after a transfer. Confirm that the preparer received all expected K-1s and knows which documents remain preliminary.</p>
<p>For each business, compare the final bookkeeping profit to the tax workpaper and ask about significant adjustments. For each rental, compare rent totals and major expenses with the annual property statement. Differences can be appropriate; the objective is an understandable bridge. Do not assume book income must equal taxable income.</p>
<h2>Check payments separately from deductions</h2>
<p>Create a payment list with dates, amounts, tax agencies, payment types and tax years. Compare the list with the return’s payment entries. A bank debit alone does not prove that a payment belongs to the correct taxpayer or period. Keep federal and state payments separate, and distinguish an extension payment from an estimated installment. Ask about any prior-year refund intended for the current year.</p>
<h2>Example: a sale missing from the review packet</h2>
<p>Imagine a landlord sold one of four rentals in July. The draft contains four full-year rental summaries and no sale workpaper. That does not establish the correct sale treatment, but it identifies a concrete question before signing. Send the settlement statement, sale agreement and prior depreciation schedule. Ask the preparer to explain the disposition reporting and revise the packet if necessary. This hypothetical check is more useful than comparing this year’s refund with last year’s.</p>
<h2>Authorize the version you actually reviewed</h2>
<p>Form 8879 is the declaration and signature authorization used for an individual return filed through an electronic return originator. Entity filings may use different authorizations. Match the authorization to the taxpayer, period and final return version. If figures change during review, ask the preparer to confirm what updated authorization is needed before transmission.</p>
<ul><li>Resolve open questions in writing or label them for follow-up.</li><li>Verify refund account and payment instructions through the secure process.</li><li>Save the final return, authorization and filing acknowledgment together.</li><li>Agree who handles estimates, state filings and remaining notices.</li></ul>
<p>Use the <a href="/assets/owner-tax-return-review-checklist.csv">downloadable owner review checklist</a> to track questions. If a return has already been filed, move to the <a href="/business-tax-return-lookback-review/">lookback review process</a> rather than treating a draft revision as a completed correction.</p>'''),
dict(slug='business-owner-estimated-tax-payments-missing-return',
title='Estimated Tax Payments Missing From an Owner’s Return',
description='Reconcile missing estimated tax payments by taxpayer, tax year and agency before paying twice or filing an unnecessary amended return.',
lead='A missing estimated tax payment can mean the return omitted a payment, the IRS posted it to a different period or account, or the payment never completed. Reconcile the bank record, payment confirmation and tax account before deciding whether the return itself needs correction.',
sources=[('https://www.irs.gov/payments/online-account-for-individuals','IRS: individual online account and payment history'),('https://www.irs.gov/payments/direct-pay-help','IRS Direct Pay help')],
body='''<h2>Build a payment ledger by taxpayer and period</h2>
<p>Business and property owners often pay several agencies from the same bank account. Label each payment with the taxpayer, last four identifying digits in your private records, agency, amount, submission date, settlement date, payment type and tax period. Add the confirmation number and the return line where the payment was reported. Keep the full account numbers out of shared spreadsheets.</p>
<p>Separate personal federal estimates from payroll deposits, entity payments, state estimates and property taxes. A payment with “tax” in its bank description does not tell the preparer how to report it. Include any prior-year overpayment that the filed return directed toward the next year; a planned carryover and an actual filed election may differ.</p>
<h2>Compare three records</h2>
<p>First, check the bank for a completed debit, reversal or returned payment. Second, read the payment confirmation for the selected form and tax period. Third, check the applicable tax account record. The IRS individual online account provides payment history, including estimated payments. Recent transactions and processing status still need to be considered before concluding that an entry is missing.</p>
<p>Direct Pay distinguishes the year used to verify identity from the tax year selected for the payment. An owner reviewing a confirmation should inspect the actual payment details. If an amount was debited but cannot be matched, use the IRS payment support process with the confirmation available rather than assuming another payment will resolve the first one.</p>
<h2>Hypothetical example: a $9,000 difference</h2>
<p>An owner’s spreadsheet lists four $9,000 federal installments, but the return includes $27,000. The fourth bank debit might be a state payment, a payment for another year, or a federal installment omitted from the preparer’s input. Each possibility produces the same $9,000 spreadsheet difference and requires a different response. Attach all four confirmations and ask for a line-by-line reconciliation.</p>
<p>If the fourth payment is correctly posted to the intended federal year, the reviewer must determine whether the filed return and current IRS account already resolve the discrepancy or require action. If it went to the wrong period, request guidance on moving or tracing the credit. If it failed, discuss the unpaid obligation and timing consequences. The example does not establish an automatic refund or penalty waiver.</p>
<h2>Keep notice deadlines in view</h2>
<p>A payment dispute does not make a notice disappear. Record the notice date, response deadline, assessed amount and contact instructions. Give the advisor the whole notice, not a cropped balance screenshot. Request a written plan stating whether to respond, trace a payment, correct a filing or take another action. Confirm how current-year estimates will continue while the older discrepancy is investigated.</p>
<h2>Prevent the same problem next year</h2>
<ul><li>Save each confirmation immediately in a folder labeled by agency and tax year.</li><li>Reconcile the payment ledger before handing off year-end records.</li><li>Have one person own the final list sent to the preparer.</li><li>Compare that list with the review copy before signing.</li></ul>
<p>For forward-looking payment planning, see <a href="/estimated-taxes-business-owners/">estimated taxes for business owners</a>. For a filed-return question, use the <a href="/tax-return-mistakes/">owner tax-return review library</a>.</p>'''),
dict(slug='business-credit-card-payments-deducted-twice',
title='Business Credit-Card Expenses Deducted Twice',
description='Learn how imported card charges and bank payments can duplicate business expenses, what records to reconcile and how to review a filed return.',
lead='If business credit-card purchases were recorded as expenses and the later payment of the card balance was also recorded as an expense, the books may contain a duplicate deduction. Trace the original charges and the payment through the ledger before changing the tax return.',
sources=[('https://www.irs.gov/publications/p583','IRS Publication 583: business records and supporting documents')],
body='''<h2>How two bank feeds create one problem</h2>
<p>A business imports its card transactions and categorizes each purchase. It also imports the checking account transactions used to pay the card. If a payment gets assigned to “office expense” instead of reducing the card liability, the bookkeeping can count the same spending twice. Automated rules can repeat the pattern for months. A bank reconciliation can still match cash while the expense classification is wrong.</p>
<p>Start with the accounting entries rather than the tax savings. A payment of a previously recorded card balance generally clears the liability; it does not create a second purchase. A proper review also separates interest, fees, refunds, personal charges and transactions that belong in an asset account. Deductibility and timing depend on the underlying expenditure and accounting method, not simply on the bank-feed label.</p>
<h2>Reconstruct a single statement cycle</h2>
<p>Select one complete card statement and obtain the detailed card register, checking register and general ledger for the same period. Match each purchase to its invoice or receipt. Match the bank payment to the credit in the card account. Mark whether the payment reduced a liability, posted to an expense or disappeared into a transfer account that still needs reconciliation.</p>
<p>The IRS recordkeeping guidance identifies supporting documents such as invoices, receipts and card statements. Preserve those records alongside the reconciliation. A statement establishes an account transaction but may not, by itself, explain the business purpose or the appropriate expense category.</p>
<h2>A duplicate-expense example</h2>
<p>Suppose an agency records $2,400 of software charges and $600 of supplies from its card feed. It then codes the $3,000 payment from checking as another software expense. Ignoring other activity, the books show $6,000 of expense for $3,000 of purchases. The extra $3,000 is the bookkeeping difference to investigate. It is not a calculated tax liability, because the return may include year-end adjustments and other rules may affect the purchases.</p>
<p>Ask whether the preparer received the raw books or an adjusted trial balance. A correcting entry already made during tax preparation could mean the return is right while the owner’s dashboard is wrong. Reversing an expense again without checking that bridge would introduce a new error.</p>
<h2>Review the effect on a filed return</h2>
<ul><li>Identify every affected card and statement period.</li><li>Calculate duplicate entries separately from legitimate fees and purchases.</li><li>Reconcile the corrected books to the amounts actually used on the return.</li><li>Identify affected entity, owner and state filings before choosing a correction procedure.</li><li>Retain the original ledger export and a dated adjustment schedule.</li></ul>
<h2>Fix the workflow after fixing the numbers</h2>
<p>Review automatic categorization rules, make one person responsible for transfer matching and reconcile the card liability monthly. Test the next statement cycle with both feeds active. The goal is a repeatable balance reconciliation, not a rule that categorizes every card payment as a deductible purchase. Include closed cards and cards held personally but used for business in the review scope.</p>
<p>If the issue reached a filed return, begin with a <a href="/business-tax-return-lookback-review/">business return review</a>. Before the next filing, use the <a href="/blog/review-business-rental-tax-return-before-signing/">pre-signing checklist</a>.</p>'''),
dict(slug='rental-mortgage-principal-deducted-tax-return',
title='Deducting the Whole Rental Mortgage Payment: A Mistake',
description='Rental owners should separate mortgage principal, interest and escrow. Review lender statements and Schedule E before deducting the whole payment.',
lead='A rental mortgage payment is not a single deductible expense. Principal repayment does not become a rental expense merely because it leaves the bank account. Separate interest, principal, escrow funding and actual escrow disbursements before reconciling the return.',
sources=[('https://www.irs.gov/publications/p527','IRS Publication 527: rental expenses and interest')],
body='''<h2>Follow the components of the payment</h2>
<p>A property owner may see one monthly withdrawal while the lender applies it to several accounts. Principal reduces the loan balance. Interest relates to borrowing. Escrow funding sets aside money that the servicer may later use for taxes or insurance. The transfer into escrow is not itself the same event as the servicer paying a tax or insurance bill. Determine the actual payment and applicable treatment before recording an expense.</p>
<p>Mortgage interest may be deductible subject to the applicable rules, including how loan proceeds were used. The building’s eligible cost is generally recovered through depreciation rather than deductions for each principal installment. Publication 527 explains rental interest and depreciation; refinancing or mixed personal and rental use can require additional analysis.</p>
<h2>Example: cash flow and expense are different</h2>
<p>Assume twelve monthly payments of $2,000, totaling $24,000. The annual lender statement allocates $7,000 to principal, $12,000 to interest and $5,000 to escrow deposits. Entering $24,000 as mortgage interest would not match that statement. But replacing it with an automatic $17,000 expense would also skip the escrow review: deposits and actual disbursements may differ.</p>
<p>Those numbers are hypothetical. The owner should reconcile the loan balance, the interest record, and the escrow activity separately, then consider the eligibility and timing of each item. Depreciation is a separate calculation. A rental that generates cash after debt payments can have a different taxable result from that cash-flow figure.</p>
<h2>Gather the lender and property records</h2>
<ul><li>Annual mortgage statements and any Form 1098 received.</li><li>Beginning and ending loan balances, plus refinancing documents.</li><li>Escrow analyses showing deposits, disbursements, refunds and shortages.</li><li>Property-tax bills and insurance invoices matched to the servicer’s payments.</li><li>The rental ledger, tax workpaper and depreciation schedule.</li></ul>
<p>If the loan changed servicers, obtain records from both. If several properties secure one loan, ask the advisor to explain the allocation rather than assigning all interest to whichever property name appears in the bookkeeping account. Reconcile any cash-out proceeds to their use; the collateral alone does not settle every interest question.</p>
<h2>Check for a second duplication</h2>
<p>Owners sometimes deduct the full mortgage withdrawal and also deduct the tax and insurance amounts paid from escrow. Review both patterns together. Search the ledger for the servicer, tax collector and insurance company, then compare the transactions with year-end adjustments. A preparer may already have reclassified the principal and escrow amounts, so inspect the final tax workpapers before concluding the filed return is wrong.</p>
<h2>Choose the correction after the reconciliation</h2>
<p>Prepare a property-by-property schedule of reported amounts and supported amounts. Ask the reviewer to identify affected years, rental income changes and any loss carryforward effect. A correction that reduces a suspended loss may have a different current cash effect from one that changes taxable income. Keep federal and state consequences separate.</p>
<p>Use <a href="/rental-property-tax-planning/">rental property tax planning</a> for the broader cash-flow projection. If a loss balance changes, consult the <a href="/passive-loss-carryforward-correction/">passive-loss correction guide</a> as part of the review.</p>'''),
dict(slug='changing-tax-preparer-business-rental-carryforward-records',
title='Changing Tax Preparers: Owner Carryforward Checklist',
description='Transfer business basis, rental losses, depreciation and payment records when changing tax preparers so opening balances can be verified.',
lead='When changing tax preparers, transfer the schedules behind your business and rental returns along with the filed PDFs. A new preparer needs support for opening basis, unused losses, depreciation and other continuing items; last year’s refund amount cannot establish those balances.',
sources=[('https://www.irs.gov/publications/p925','IRS Publication 925: passive activity and at-risk rules'),('https://www.irs.gov/instructions/i7203','IRS Form 7203 instructions: S corporation shareholder basis')],
body='''<h2>Ask for balances with their supporting history</h2>
<p>Build an inventory by taxpayer, entity and property. For each continuing item, list the ending balance, tax year, supporting schedule, preparer and whether it has been reconciled. Ask the new advisor what historical records are needed; a single final-year worksheet may not explain an unexplained opening figure. Retain your own copies even if the firms arrange a direct transfer.</p>
<p>A complete filed return is the starting point. Request the supporting schedules available under the engagement and applicable requirements, recognizing that access to a preparer’s internal workpapers can differ from access to client records. The practical objective is documented balances and the information required to reproduce them, not a promise that every internal file must be transferred.</p>
<h2>Keep different loss buckets separate</h2>
<p>A passive-loss carryforward is not interchangeable with a basis-limited or at-risk-limited loss. Publication 925 explains passive and at-risk restrictions, while the Form 7203 instructions address S corporation shareholder stock and debt basis. Label each balance by its actual limitation and owner. Combining everything into one “prior losses” entry can make a later release or utilization analysis unreliable.</p>
<p>For rentals, preserve the property-level activity history and any relevant grouping documentation. For an S corporation, retain the shareholder’s basis schedules and the underlying contribution, distribution and loan records. For partnerships, obtain outside-basis support rather than treating the K-1 capital account as a substitute.</p>
<h2>Prepare a handoff manifest</h2>
<ul><li>Complete federal and state returns, amendments and filing acknowledgments.</li><li>Fixed-asset schedules with cost, service dates, methods, conventions and accumulated depreciation.</li><li>Loss, credit and other carryforward schedules, separated by taxpayer and jurisdiction.</li><li>Stock, debt and partnership outside-basis records where applicable.</li><li>Election statements, open notices and unresolved filing questions.</li><li>Estimated payments, refund applications and the next payment calendar.</li></ul>
<p>Mark each file as received, missing, superseded or awaiting reconciliation. Include the date and version in the filename. A corrected return should be linked to the return it replaced so a software import does not silently restore an obsolete balance.</p>
<h2>Example: the new software starts at zero</h2>
<p>A landlord changes firms and the new rental worksheet shows no beginning suspended loss. The previous year’s support shows $28,000 associated with the property. That hypothetical mismatch is a request for reconciliation, not permission to deduct $28,000 this year. The reviewer should verify the prior calculation, intervening activity and current limitations before deciding what carries forward or becomes usable.</p>
<p>Likewise, importing a figure successfully is not proof that it was right. Ask the new advisor to distinguish balances merely carried over from balances independently reconciled. That distinction helps set a sensible scope and avoids creating a false impression that onboarding included a full historical audit.</p>
<h2>Close the transfer with an opening-balance review</h2>
<p>Before filing the first return with the new firm, compare opening balances to the signed-off handoff manifest. Record unresolved differences and their effect on filing readiness. Assign responsibility for obtaining missing documents and for responding to notices. For a specific rental mismatch, use the <a href="/passive-loss-carryforward-correction/">passive-loss reconstruction guide</a>; for broader concerns, request a <a href="/business-tax-return-lookback-review/">lookback review</a>.</p>'''),
dict(slug='partnership-k1-capital-account-not-outside-basis',
title='K-1 Capital Account Is Not Partnership Outside Basis',
description='Business and rental partners should not use K-1 tax capital as outside basis. Review contributions, distributions, debt and loss-limit worksheets.',
lead='The tax-basis capital account on a partnership Schedule K-1 is not the same as a partner’s outside basis in the partnership interest. Using the capital figure as the sole basis number can distort a business or rental partner’s loss and distribution analysis.',
sources=[('https://www.irs.gov/instructions/i1065sk1','IRS Partner’s Instructions for Schedule K-1, Form 1065')],
body='''<h2>Ask which number the return is actually using</h2>
<p>The K-1’s capital section is useful information, but it does not replace an outside-basis rollforward. The IRS partner instructions explain that the partner must determine the adjusted basis of the partnership interest and that the capital account analysis cannot be used to calculate it. Partnership liabilities and partner-specific acquisition facts can make the numbers differ.</p>
<p>A reviewer should identify the beginning outside basis, current-year adjustments, ending basis and records supporting each component. If the only explanation is “we copied the ending capital account,” ask for a separate reconciliation. A negative capital account also does not, by itself, establish the amount of a deductible loss or taxable distribution.</p>
<h2>Build a partner-specific file</h2>
<p>Collect the original investment or purchase documents, prior basis schedules, all K-1s, contributions, distributions and information about partnership liabilities. Flag an interest acquired from another partner rather than through a cash contribution to the entity. Tell the advisor about ownership changes, refinancing and payments that may have been booked as loans or capital without a clear agreement.</p>
<p>Keep the partnership’s records separate from the individual partner’s history. Two owners with similar ownership percentages can have different tax histories. A worksheet copied from another partner may omit facts unique to an acquisition, transfer or prior loss limitation.</p>
<h2>Illustration: a mismatch is the beginning of the review</h2>
<p>Assume a rental partner receives a K-1 showing $20,000 of ending tax capital and separately reported liability information. The owner wants to use $20,000 as the available loss limit. That conclusion skips the outside-basis analysis. The reviewer must reconcile the partner’s actual history and relevant liability treatment before determining basis. Even a supported outside-basis figure does not resolve the other limitations.</p>
<p>This is a hypothetical record-review example, not a formula for adding every liability number to capital. Do not simply add a current-year debt figure to a capital balance that has not been reconciled. Timing, liability changes and the owner’s starting basis must be understood.</p>
<h2>Review the limitations in sequence</h2>
<p>The partner instructions explain that loss limitations can apply at multiple levels, including basis, at-risk and passive activity rules. A partner can have enough outside basis while another limitation still suspends the loss. Ask for separate schedules showing the amount allowed and the amount deferred at each applicable step; one combined carryforward obscures the reason a loss was not used.</p>
<ul><li>Which opening outside-basis figure was used, and where did it come from?</li><li>Were contributions and distributions reconciled to bank and entity records?</li><li>Were changes in liability allocations addressed?</li><li>Are prior suspended losses labeled by the limitation that created them?</li><li>Do owner and entity corrections need to be coordinated?</li></ul>
<h2>Resolve a filed-return concern with the entity advisor</h2>
<p>A discrepancy can arise in the K-1, the owner’s basis worksheet or both. Determine which document requires action and the appropriate procedure before changing the owner return. Keep replacement schedules clearly labeled so the next preparer does not reuse an obsolete balance. For the specific refinancing decision, see <a href="/blog/rental-partnership-refinance-distribution-basis/">rental partnership refinance distributions and basis</a>. For preparation handoffs, use the <a href="/blog/changing-tax-preparer-business-rental-carryforward-records/">owner carryforward checklist</a>.</p>'''),
dict(slug='sold-rental-property-still-on-depreciation-schedule',
title='Sold Rental Still on Your Depreciation Schedule?',
description='Review rental sale reporting, asset retirement and sale-year depreciation when a sold property remains active on the tax depreciation schedule.',
lead='If a sold rental still appears as an active asset, reconcile the sale documents with the depreciation and disposition schedules. A retained historical asset row is not necessarily an error, but continued depreciation after disposal or missing sale reporting needs review.',
sources=[('https://www.irs.gov/publications/p946','IRS Publication 946: depreciation and retirement from service'),('https://www.irs.gov/publications/p544','IRS Publication 544: sales and other dispositions of assets')],
body='''<h2>Distinguish a historical row from an active asset</h2>
<p>Tax software may keep a disposed asset in the report to show its history. Look for the disposition date, current-year deduction and status rather than assuming every visible row is still depreciating. The IRS depreciation guidance explains when depreciation ends and how applicable conventions affect the sale year. A sale during the year does not necessarily mean that the correct deduction is zero or a simple count of months.</p>
<p>Ask the preparer to show the property’s sale-year depreciation calculation and the disposition workpaper. Compare both with the actual closing date and transaction facts. If only the building was marked disposed, check whether separately listed improvements and components sold with it were also addressed.</p>
<h2>Assemble a sale packet before checking the result</h2>
<ul><li>Sale agreement, final settlement statement and any amendments.</li><li>Original purchase records and the land/building allocation.</li><li>All depreciation schedules, including improvements and study components.</li><li>Selling-cost support, debt payoff details and any installment terms.</li><li>Records of partial dispositions, casualty adjustments or other basis changes.</li><li>Prior loss schedules and ownership information relevant to the sale.</li></ul>
<p>Use one property identifier across the packet. A street address that changed in the software should not create two unrelated asset histories. If a cost segregation study split the property into many assets, request a cross-reference showing which assets were included in the sale and how proceeds and costs were allocated.</p>
<h2>Example: the building was sold, the renovation remained</h2>
<p>Suppose a landlord sold a duplex in August. The asset report marks the original building disposed but leaves a kitchen renovation from an earlier year active into the next year. The owner should ask whether the renovation was conveyed with the building, replaced before the sale or retained in some other way. The supporting facts determine what should happen to that row.</p>
<p>This hypothetical example does not calculate recapture or the sale-year deduction. It shows why checking only the largest building line can miss a component-level problem. The reviewer should reconcile the entire asset group and carry any correction into the following year’s opening records.</p>
<h2>Do not use the mortgage payoff as tax basis</h2>
<p>Cash received at closing, debt repaid and taxable gain are different calculations. Publication 544 explains disposition reporting and potential depreciation recapture. Request a bridge from the sale price and applicable selling costs to adjusted basis and reported gain. Show the debt payoff separately in the cash reconciliation so it does not silently replace the basis calculation.</p>
<p>Also ask about suspended losses and state treatment. A sale can interact with those items, but their result depends on the transaction and owner facts. An estimate that uses only the net check from escrow cannot answer all of those questions.</p>
<h2>If the return was already filed</h2>
<p>Identify the first incorrect year and whether the issue is a sale entry, depreciation calculation, accounting method or carryforward. The correction procedure can differ. Do not automatically delete the asset and assume the current return fixes the past. Preserve the original schedules and request a written correction sequence covering affected entity, owner and state filings.</p>
<p>For missed depreciation before the sale, start with <a href="/blog/form-3115-missed-depreciation/">the missed-depreciation correction guide</a>. For the broader review, use <a href="/real-estate-tax-planning/">real estate owner tax planning</a> and the <a href="/tax-return-mistakes/">return-mistake library</a>.</p>''')
]

EXISTING = [
('/blog/reconcile-1099-k-gross-payments-to-tax-return/','1099-K gross receipts do not match deposits','Reconcile processor totals, refunds and fees.'),
('/blog/rental-property-security-deposit-tax/','Rental security deposits reported incorrectly','Separate refundable deposits from other rent receipts.'),
('/passive-loss-carryforward-correction/','Rental passive-loss carryforward is missing','Rebuild the history and keep limitation categories separate.'),
('/corrected-k1-after-amended-1120s/','A corrected S corporation K-1 arrives after filing','Coordinate entity and owner corrections.'),
('/blog/form-3115-missed-depreciation/','Rental or business depreciation was missed','Review the correction procedure before amending.'),
('/blog/cost-segregation-report-basis-reconciliation/','A cost segregation report does not match basis','Reconcile land, improvements, assets and prior depreciation.'),
('/blog/business-s-corp-loss-debt-basis/','An S corporation loss lacks debt-basis support','Review shareholder loan facts and loss limitations.'),
('/blog/rental-property-closing-costs-basis/','Rental closing costs were classified incorrectly','Review settlement items individually.'),
('/blog/business-equipment-delivered-not-operational-year-end/','Equipment was deducted before it was ready','Check placed-in-service evidence.'),
('/blog/should-i-amend-my-return-or-wait-for-next-year/','An error was left for next year without a plan','Compare correction choices for the affected filing.')
]

def paths():
    return [HUB] + ['/blog/'+p['slug']+'/' for p in POSTS] + [p[0] for p in EXISTING]

def inject(path, links, heading):
    target = T.ROOT / path.strip('/') / 'index.html' if path != '/' else T.ROOT/'index.html'
    text = target.read_text()
    text = re.sub(r'\s*<!-- return-mistakes:start -->.*?<!-- return-mistakes:end -->\s*(?=</main>)','',text,flags=re.S)
    block = '<!-- return-mistakes:start -->'+T.related_section(links,heading)+'<!-- return-mistakes:end -->'
    target.write_text(re.sub(r'\s*</main>',lambda _: '\n'+block+'\n    </main>',text))

def main():
    for post in POSTS:
        path = '/blog/'+post['slug']+'/'
        trail = [('Home','/'),('Tax Return Mistakes',HUB),(post['title'],path)]
        body = T.page_header(h1=post['title'],subtitle='Tax return review for business owners and real estate owners.',trail=trail)
        body += T.section('What to check first',T.definition(T.esc(post['lead']))+f'<p>By AE Tax Advisors Team · Published <time datetime="{DATE}">September 26, 2026</time></p>'+post['body'])
        body += T.section('Sources and scope','<ul>'+''.join(f'<li><a href="{url}">{T.esc(label)}</a></li>' for url,label in post['sources'])+'</ul><p>Sources checked September 26, 2026. Examples are hypothetical. This educational guide does not determine whether your return is incorrect or which filing procedure applies. <a href="/editorial-policy/">Editorial policy</a>.</p>')
        body += T.related_section([(HUB,'Browse all owner tax-return mistakes'),('/assets/owner-tax-return-review-checklist.csv','Download the return-review checklist (CSV)'),('/business-tax-return-lookback-review/','Request a scoped return review')])
        schemas = [T.article_schema(title=post['title'],description=post['description'],url=T.SITE+path,published=DATE,modified=DATE,section='Tax Return Mistakes',citations=[s[0] for s in post['sources']]),T.breadcrumb_schema(trail)]
        target = T.ROOT/path.strip('/')/'index.html'; target.parent.mkdir(parents=True,exist_ok=True)
        target.write_text(T.build_page(title=post['title']+' | AE Tax',description=post['description'],path=path,body=body,schemas=schemas,published=DATE,modified=DATE))
    title='Tax Return Mistakes: Business and Rental Owner Guides'
    description='Find business and rental tax return mistakes, review preparer work and plan corrections. Explore 18 guides and download an owner review checklist.'
    trail=[('Home','/'),('Tax Return Mistakes',HUB)]
    body=T.page_header(h1=title,subtitle='Find the discrepancy. Gather the evidence. Choose the right correction.',trail=trail)
    body+=T.section('Start with the issue on your return',T.definition('A tax return review starts with a specific difference between the filed return and the supporting facts. This library helps business owners and real estate owners investigate potential mistakes in their own records or their preparer’s work, without assuming every unexpected tax result is an error.')+'<p>Eight new working guides and ten related articles cover preparation, bookkeeping, rental expenses, basis, depreciation and corrections. A missed planning opportunity, a limited deduction and an incorrect filing are different findings. Use the guide matching your situation to prepare a focused question for your advisor.</p><p>Published September 26, 2026 · AE Tax Advisors Team</p><p><a href="#before-filing">Before filing or changing preparers</a> · <a href="#business-errors">Business and payment checks</a> · <a href="#rental-errors">Rental and basis checks</a> · <a href="#more-errors">More specific errors</a> · <a href="#correction-plan">Plan the next step</a></p>')
    groups=[('before-filing','Before filing or changing preparers',[0,1,5]),('business-errors','Business expenses and tax payments',[2,3]),('rental-errors','Rental expenses, partnership basis and property sales',[4,6,7])]
    for anchor,heading,indexes in groups:
        cards=''.join(f'<li><h3><a href="/blog/{POSTS[i]["slug"]}/">{T.esc(POSTS[i]["title"])}</a></h3><p>{T.esc(POSTS[i]["description"])}</p></li>' for i in indexes)
        body+=T.section(heading,f'<div id="{anchor}"><ul>{cards}</ul></div>')
    body+=T.section('More specific return errors','<div id="more-errors"><ul>'+''.join(f'<li><h3><a href="{path}">{T.esc(label)}</a></h3><p>{T.esc(desc)}</p></li>' for path,label,desc in EXISTING)+'</ul></div>')
    body+=T.section('Make a correction plan, not a refund assumption','''<div id="correction-plan"><p>Write down the taxpayer, tax year, disputed entry, supporting record and amount. Ask the reviewer to classify the finding before proposing a filing. Not every difference requires an amended return, and an error may increase tax, reduce tax or only change a future carryforward.</p><ol><li><strong>Confirm the filed version.</strong> Compare the accepted return with the underlying records and any final bookkeeping adjustments.</li><li><strong>Identify the affected filings.</strong> Include entity, owner, state and later-year schedules where relevant.</li><li><strong>Select the procedure.</strong> Payment tracing, return corrections, partnership procedures and accounting-method changes require different analyses.</li><li><strong>Assign dates and responsibility.</strong> Preserve notice deadlines and document who prepares, reviews and submits each step.</li><li><strong>Verify the result.</strong> Save acknowledgments and update the continuing schedules so the same issue does not reappear.</li></ol><p>A complete review should produce a list of supported findings and unresolved questions. Ask for the expected tax effect, preparation cost and procedural limits before proceeding. No refund amount is promised by this library.</p></div>''')
    body+=T.section('Download the owner return-review checklist','<p>Use the blank worksheet to track issues, evidence, responsible people and resolution status. Keep identifying account numbers and sensitive tax documents in your secure records system.</p><div><a class="btn btn-primary" href="/assets/owner-tax-return-review-checklist.csv" download>Download the CSV checklist</a></div>')
    body+=T.related_section([('/business-tax-return-lookback-review/','Business tax-return lookback review'),('/business-owner-tax-planning/','Business owner tax planning'),('/real-estate-tax-planning/','Real estate owner tax planning')],'Get help reviewing an owner return')
    schemas=[T.breadcrumb_schema(trail),{'@context':'https://schema.org','@type':'CollectionPage','name':title,'description':description,'url':T.SITE+HUB,'datePublished':DATE,'dateModified':DATE,'mainEntity':{'@type':'ItemList','itemListElement':[{'@type':'ListItem','position':i+1,'url':T.SITE+p} for i,p in enumerate(paths()[1:])]}}]
    target=T.ROOT/HUB.strip('/')/'index.html';target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(T.build_page(title=title+' | AE Tax',description=description,path=HUB,body=body,schemas=schemas,published=DATE,modified=DATE,og_type='website'))
    for path in ['/','/blog/','/business-tax-return-lookback-review/','/business-owner-tax-planning/','/real-estate-tax-planning/']+[p[0] for p in EXISTING]:
        inject(path,[(HUB,'Tax-return mistakes: 18 guides for business and rental owners'),('/assets/owner-tax-return-review-checklist.csv','Download the owner return-review checklist')],'Review your return for missing or incorrect information')
    with (T.ROOT/'assets/owner-tax-return-review-checklist.csv').open('w',newline='') as file:
        writer=csv.writer(file)
        writer.writerow(['Review item','Taxpayer or property nickname','Tax year','Evidence reference','Reported amount','Supported amount','Open question','Responsible person','Status','Resolution'])
        for item in ['Complete filed return and acknowledgment','Business and rental activity inventory','Major purchases and sales','Income reconciliation and 1099-K','Credit-card charges versus payments','Rental principal interest and escrow','Refundable security deposits','Estimated payments and refund applications','Property basis and closing costs','Depreciation and disposed assets','Partnership outside basis','S corporation stock and debt basis','Loss and credit carryforwards by limitation','Corrected K-1 and owner return coordination','Federal and state differences','Notices and response deadlines','Correction procedure and filing sequence','Final return review and authorization']:
            writer.writerow([item]+['']*9)
    print('Built 8 articles, 18-guide hub, 18-row checklist and 15 discovery links')

if __name__=='__main__':main()
