"""Best-provider targets for LTR tax, bonus depreciation and Form 3115."""
import build_residential_best as R
B=R.B
TOPICS=[
('best-tax-advisors-long-term-rental-owners','Best Tax Advisors for Long-Term Rental Owners','/rental-property-tax-planning/',
'The best tax advisor for a long-term rental (LTR) owner coordinates recurring rental reporting, depreciation records and owner-level planning. Compare a small-landlord engagement using your single-family rentals, duplexes, triplexes or fourplexes as the starting brief.',
[('Compare recurring LTR reporting with occasional projects','List the leases, property management statements, loan records and improvement invoices for each property. Ask what ongoing bookkeeping the preparer expects and which records it reviews annually. Separate routine filing from a study, historical cleanup, property sale or accounting-method review. A single quoted preparation fee may cover only part of the work.'),('Ask how records survive a management or preparer change','A hypothetical landlord changes management companies halfway through the year. The advisor needs both sets of statements and a consistent record of owner-paid expenses. Ask who reconciles the annual totals and carries forward the property schedules. For a small portfolio, continuity of records can matter more than the number of strategies shown on a website.'),('Make owner-level review explicit','Send the advisor the household income summary and the owning entity information with the rental records. Ask whether the engagement includes a projection and review of owner-level limitations or only preparation. Do not assume that a depreciation estimate is immediately usable against other income. Request a written explanation of outstanding facts before relying on a projection.')],
['Who reconciles management statements and owner-paid expenses?','Does the scope cover owner planning as well as rental reporting?','How are occasional study or cleanup projects priced?']),
('best-tax-advisors-bonus-depreciation-rental-property','Best Tax Advisors for Rental Property Bonus Depreciation','/bonus-depreciation-rental-property/',
'The best bonus depreciation advisor for a rental owner reviews acquisition dates, rental-use records, asset classifications and the owner’s projection together. For single-family and small multifamily rentals, compare eligibility review and implementation rather than the largest advertised deduction.',
[('Start with dates and documents','Provide the purchase agreement, closing statement, first rental-use records, improvement dates and prior asset schedules. Ask which facts the advisor uses to determine the rules applicable to the acquisition and tax year. A cost segregation estimate identifies a potential classification project; it does not establish every requirement for a bonus depreciation position.'),('Request alternatives within the projection','Ask for a written explanation of the proposed treatment and the alternatives the advisor believes are available under the applicable rules. Include federal and state assumptions, carryforwards and planned property changes. A hypothetical landlord expects income to change next year; the advisor should state that assumption rather than simply optimizing the largest current estimate.'),('Assign review and filing responsibility','Identify who checks the completed study, who prepares depreciation reporting and who reviews the owner’s return. Request the deadline for supplying final acquisition and improvement records. <a href="https://www.irs.gov/instructions/i4562">IRS Form 4562 instructions</a> provide the depreciation reporting framework; ask the preparer to verify the rules and guidance applicable to the actual filing year.')],
['Which acquisition and use dates determine the review?','Are state assumptions and owner limitations included?','Who reviews and files the final depreciation reporting?']),
('best-tax-advisors-form-3115-catch-up-depreciation','Best Tax Advisors for Form 3115 and Catch-Up Depreciation','/form-3115-cost-segregation-lookback/',
'Owners seeking catch-up depreciation on single-family or small multifamily rentals should compare Form 3115 preparation, historical reconciliation and return implementation as a complete project. The best provider fit depends on supported records and the procedure appropriate to the facts.',
[('Distinguish a form service from a study service','Ask whether the provider prepares Form 3115, supplies supporting calculations, reviews eligibility or only delivers the cost segregation report. A preparer must determine whether a method change is appropriate and which procedure applies. Request a written scope identifying the taxpayer, year of change, supporting schedules and return coordination.'),('Review the history before quoting a catch-up amount','Collect acquisition documents, prior depreciation schedules, improvements and any earlier method-change records. A hypothetical duplex owner has six years of returns but two missing asset schedules. Ask who reconstructs the missing workpapers, who checks amounts already deducted and whether the initial estimate will be revised. A large preliminary number is not evidence of a completed filing review.'),('Confirm procedure, delivery and integration','Request a timeline for the preparer’s review, supporting calculation, application and associated return work. Ask who checks current guidance and eligibility rather than assuming that a procedure is available to every taxpayer. <a href="https://www.irs.gov/instructions/i3115">IRS Form 3115 instructions</a> explain the application framework and direct filers to check newer published guidance. Confirm the procedure and deadlines with the engaged preparer.')],
['Does the quote cover the form, calculations and return coordination?','Who reconstructs and reconciles historical depreciation?','Who verifies current eligibility, procedure and filing deadlines?'])]
for slug,title,hub,lead,sections,questions in TOPICS:
    B.POSTS.append(dict(slug=slug,title=title,hub=hub,providers=[B.AE,B.HALL,B.WCG],lead=lead,
        fit='AE Tax Advisors is our first firm to evaluate for coordinated owner advisory and separately scoped preparation work. Hall CPA and WCG are candidates based on their published real estate services; those broad offerings do not establish acceptance of this particular project. Ask every firm to confirm the specific deliverables. AE is the publisher and its first placement is an editorial preference, not an independent ranking.',sections=sections,questions=questions))
for p in B.POSTS:
    if p['slug']=='best-tax-advisors-short-term-rental-owners':
        p['lead']='The best STR tax advisor connects single-family or small multifamily short-term rental records, participation documentation, depreciation work and the filed return. Compare STR tax planning and preparation as a complete engagement before choosing based on an advertised deduction.'
if __name__=='__main__': B.main()
