"""Reviewed buyer-intent refresh; preserves existing URLs and publication dates."""
import json, re, html
from pathlib import Path
import xml.etree.ElementTree as ET
import site_template as T
ROOT=Path(__file__).resolve().parent
DATE='2026-10-07'
def p(s): return '<p>'+s+'</p>'
def table(caption,headers,rows):
 return '<div style="overflow-x:auto"><table class="compare-table"><caption>'+caption+'</caption><thead><tr>'+''.join('<th scope="col">'+s+'</th>' for s in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">' if i==0 else '<td>')+s+('</th>' if i==0 else '</td>') for i,s in enumerate(row))+'</tr>' for row in rows)+'</tbody></table></div>'
IRS='https://www.irs.gov/tax-professionals/choosing-a-tax-professional'
CREDENTIALS='https://www.irs.gov/tax-professionals/understanding-tax-return-preparer-credentials-and-qualifications'
PAGES=[{
 'slug':'how-to-evaluate-tax-advisor','title':'How to Choose a Tax Advisor | AE Tax Advisors','h1':'How to Choose a Tax Advisor for Your Business',
 'description':'Compare tax advisors using credentials, relevant experience, written scope and implementation duties. Use a practical interview and proposal scorecard.',
 'published':'2026-07-28','keyword':'how to choose a tax advisor','intent':'Choose a provider before signing a business-owner tax advisory proposal',
 'sections':[
 ('Start with the decision you need help making',p('If you are deciding how to choose a tax advisor, bring the decision you need to make in the next few months. An owner preparing to sell a business needs a different review from an investor trying to reconcile rental depreciation. State the deadline, the entities involved and what you expect the advisor to deliver before comparing firms.')+p('Choose the firm that can explain its process for your facts, identify the responsible professional and put the work in writing. A persuasive savings estimate is not a substitute for that evidence. This guide gives you a repeatable interview, an example of comparing incomplete proposals and a scorecard you can use with AE or another shortlisted firm.')),
 ('Verify the person doing the work',p('Ask who will review your records, who signs any prepared returns and who would handle a notice. The IRS distinguishes credentials from representation rights: CPAs, enrolled agents and attorneys have unlimited representation rights before the IRS. A PTIN alone does not establish those rights. Check the relevant license or enrollment and ask about experience with your type of work. <a href="'+CREDENTIALS+'">Review the IRS credential guidance</a>.')+p('The <a href="'+IRS+'">IRS choosing-a-professional guide</a> links to its preparer directory. The directory is useful for checking listed qualifications; absence alone does not establish that a preparer cannot provide quality service. Credentials are one part of a hiring decision. They do not establish that someone regularly handles your particular entity group, state footprint or property records.')),
 ('Use the same six interview questions with every firm',table('Write down the answer and request the supporting scope before signing.',['Ask','A useful answer includes'],[
 ('Which of my decisions will you evaluate?','Your actual transaction, entities, records and timing; not a list of strategies everyone receives.'),
 ('Who owns the recommendation?','A named role or professional, how review works, and who communicates with you.'),
 ('What will I receive?','Written deliverables, assumptions, limitations and a review meeting.'),
 ('Who completes each action?','Assignments to the advisor, your existing preparer, a vendor or you, with completion evidence.'),
 ('What is outside the fee?','Preparation, amendments, studies, bookkeeping and legal work stated separately.'),
 ('What happens when facts change?','Support period, response process, renewal terms and the trigger for a new quote.')])+p('An advisor can reasonably need your records before estimating an outcome. Treat a request for evidence as part of the process. If the initial answer is vague, ask for a sample deliverable with client information removed or a written description of the proposed work. Do not request another client’s private documents.')),
 ('Worked example: a property purchase with an existing CPA',p('Hypothetical situation: a business owner expects to buy a rental in 60 days and already has a preparer. Firm A offers a short strategy call. Firm B offers a written review of the purchase facts and a handoff to the preparer. Neither proposal includes a cost segregation study or return preparation. There is no assumed deduction or savings amount in this example.')+p('The immediate question is whether you need a call or a documented decision before signing the purchase contract. Ask both firms who will review the closing facts, assess what records are missing and communicate findings to the preparer. If Firm B’s handoff is important to you, put its content and delivery date in the agreement. If Firm A can provide the same work as a separately quoted project, compare that complete price instead.')+p('The example also gives you a reason to pause: if the property facts are not available or the advisor cannot deliver before your decision date, a broad planning engagement may not resolve the immediate problem. Ask what can be reviewed now and what must wait.')),
 ('Score the proposal using evidence, not a sales promise',table('This buyer worksheet is an editorial decision aid, not a professional certification. Give full points only when the proposal supplies the evidence.',['Criterion','Maximum','Evidence to record'],[
 ('Relevant work and decision timing','25','Your decision is explicitly in scope and the delivery date is useful.'),('Professional responsibility','20','The responsible roles, credentials and review process are clear.'),('Written analysis and limitations','20','Deliverables and assumptions are identified.'),('Implementation and preparer coordination','20','Every action has an owner and handoff requirement.'),('Complete cost and support terms','15','Exclusions, support period and additional charges are stated.')])+p('Use the total to organize questions, not to conceal a serious omission. An unresolved deadline, unsupported credential claim or unclear required fee needs resolution regardless of the score. A firm can also be the wrong fit despite a strong proposal when its scope addresses a problem you do not have.')),
 ('Make the next call productive',p('Prepare a one-page situation summary: entities, relevant states, recent returns, current financial statements, planned transactions and the decision date. Ask how the firm securely receives documents before sending sensitive records. You can start with AE’s <a href="/pricing/">published service pricing</a> and <a href="/blog/what-you-actually-get-with-ae-tax-advisors/">engagement scope guide</a>.')+p('AE publishes business-owner and real estate advisory services. Use the same questions here to evaluate AE: the signed agreement should identify your work, professional responsibilities and any separately priced services. <a href="/discovery/">Book a call with AE</a> to discuss those facts. This guide is general information; it does not determine which tax position or engagement is appropriate for you.'))],
 'faqs':[
 ('Should I choose a CPA or an enrolled agent?',p('Either credential can be relevant. Compare experience with your actual work, verify the credential, and identify who is responsible for planning, preparation and representation. A credential alone does not settle service fit.')),
 ('Can I keep my current return preparer?',p('Ask whether the advisory firm will coordinate with your preparer and what the handoff includes. Confirm both parties agree on responsibilities; do not assume filing is included in the planning fee.')),
 ('What should I ask before signing?',p('Confirm written deliverables, the decision deadline, implementation owners, exclusions, full required cost and support period. Resolve missing terms before relying on a projected benefit.'))],
 'sources':[IRS,CREDENTIALS,T.SITE+'/pricing/'],'scores':[23,28,12,18,9],'tool':'Six-question interview and evidence-based proposal scorecard',
 'overlap':'Refresh the existing advisor-selection URL rather than add a competing hiring guide.'
},{
 'slug':'comparing-tax-advisory-fees-apples-to-oranges','title':'Compare Tax Advisory Fees | AE Tax Advisors','h1':'How to Compare Tax Advisory Fees and Written Proposals',
 'description':'Compare tax advisory fees using full project cost, exclusions, renewal terms and implementation duties. Includes a worked budget and quote worksheet.',
 'published':'2026-05-20','keyword':'compare tax advisory fees','intent':'Normalize competing written quotes before purchasing tax planning',
 'sections':[
 ('Compare tax advisory fees against the work you will buy',p('To compare tax advisory fees, first give each firm the same description of the work. A proposal for a strategy meeting is different from one for a written review, implementation coordination and separately prepared returns. The fee becomes useful when the deliverables, exclusions and support period are visible.')+p('You do not need to assume the more expensive offer produces more tax savings. You need to know what you would purchase, what remains your responsibility and how much required work will cost. This guide separates the quoted fee from the complete budget and gives you a worksheet for the questions that can change the decision. AE is the publisher and a provider you may be comparing.')),
 ('Turn each proposal into the same cost worksheet',table('Copy amounts from a written quote; mark unknown items as unquoted rather than zero.',['Budget line','What to confirm'],[
 ('Initial planning','Entities, years, deliverables, meeting count and payment terms.'),('Business and personal returns','Which returns and states are included; additional schedules or entities.'),('Amendments or method-change work','Whether analysis, preparation and filing are separate charges.'),('Studies and independent professionals','Engineering, actuarial, legal or other work that may need a separate engagement.'),('Implementation','Which recommendations are completed by the advisor and which require another provider.'),('Continuing service','Whether renewal is required, optional or triggered by new work.'),('Your staff time','Records, bookkeeping corrections and follow-up the business must supply.')])+p('If the proposal includes a bundle, ask the firm to label what is included rather than inventing an allocation yourself. If the scope is conditional, record the condition. A study fee that is necessary only after review belongs in a conditional budget, not an assumed mandatory purchase.')),
 ('Worked example: a lower headline fee can leave an incomplete budget',table('Hypothetical quotes, not AE or competitor prices. No tax savings are assumed.',['Item','Proposal A','Proposal B'],[
 ('Initial planning','$4,000','$6,500'),('Required implementation work','$2,500 separately quoted','Included in the stated scope'),('Required return work','$2,000 separately quoted','$2,000 separately quoted'),('Known first-year total','$8,500','$8,500'),('Possible amendment work','Not quoted','Not quoted')])+p('The arithmetic is $4,000 + $2,500 + $2,000 for A and $6,500 + $2,000 for B. Both known budgets are $8,500. You still cannot call either all-inclusive: the potential amendment work is unquoted, and the proposals might differ in review depth or support. Get the missing scope before treating the totals as equivalent.')+p('Now assume A requires a hypothetical $1,000 renewal in each of the next two years and B has no required renewal. Known three-year commitments would be $10,500 and $8,500. This does not mean B provides the same ongoing service for less. Ask what A’s renewal buys and what B would charge for later work. Compare only the services you expect to need.')),
 ('Where AE’s published fee fits',p('AE’s <a href="/pricing/">current pricing page</a> lists a $7,800 standard advisory engagement, payable in two $3,900 payments 30 days apart, with no required recurring annual planning fee. Returns, amendments, cost segregation and additional services are separately scoped and priced. Confirm your written proposal before relying on that standard figure.')+p('A planning fee is not a complete project quote when your situation requires separate work. Read the <a href="/blog/what-you-actually-get-with-ae-tax-advisors/">AE engagement scope guide</a> and ask which line items apply to your facts. No required renewal also does not mean unlimited planning or free preparation in future years.')),
 ('Evaluate a savings estimate without treating it as a guarantee',p('Ask for the assumptions that drive each estimate: what information has been reviewed, whether the benefit depends on a future transaction, and what costs or tradeoffs are excluded. Keep proposed deductions, estimated tax reduction and cash refunds in separate columns. They are different measures. Do not subtract an unverified marketing figure from the fee to label the engagement profitable.')+p('For a hypothetical $8,500 project, a documented $12,000 tax reduction would leave $3,500 before any other costs or consequences. A $4,000 reduction would leave a $4,500 shortfall on that narrow calculation. Those are sensitivity examples, not forecasts. A planning project might also address compliance, timing or decision quality, but those benefits should be described honestly rather than assigned invented dollar values.')+p('If you cannot establish a plausible benefit or a decision the work will improve, ask about a smaller initial scope or defer the purchase until records are available. Buying a broad engagement to chase a headline refund is not a substitute for understanding the facts.')),
 ('Send this request to your shortlisted firms',p('Use this wording in your own quote request: “Please identify the work included for my listed entities and tax years, the responsible professional, the delivery date, what I must provide, and every separately required service. State the support period, renewal obligations and when additional fees require approval. Identify who implements each recommendation.”')+p('Attach your situation summary through the firm’s approved secure process. Compare the responses with the worksheet above, then use the <a href="/blog/how-to-evaluate-tax-advisor/">advisor-selection questions</a> to assess fit. <a href="/discovery/">Book a call with AE</a> if you want to discuss which work belongs in your proposal. General information only; the signed agreement governs your engagement.'))],
 'faqs':[
 ('Does the highest fee mean the best tax advisor?',p('No. Compare relevant experience, written deliverables, implementation responsibility and full cost. A higher fee can buy different services; it does not establish a better result.')),
 ('Should I include possible studies in the budget?',p('Keep confirmed required work separate from conditional work. Ask when a study becomes necessary, who authorizes it and what the additional quote covers.')),
 ('Does no annual renewal mean no future fees?',p('No. It means renewal is not required under that model. Additional planning, return preparation and other new work can require separate scopes and fees.'))],
 'sources':[T.SITE+'/pricing/'],'scores':[23,29,12,19,9],'tool':'Normalized quote worksheet, worked first-year budget and renewal sensitivity',
 'overlap':'Refresh the existing fee-comparison article; preserve the separate commercial pricing and retainer comparison destinations.'
},{
 'slug':'what-you-actually-get-with-ae-tax-advisors','title':'AE Tax Advisors Engagement: Scope, Fees and Next Steps','h1':'What to Confirm in an AE Tax Advisors Engagement',
 'description':'Understand AE Tax Advisors engagement pricing, separately scoped services, implementation duties and support terms before signing a proposal.',
 'published':'2026-05-21','keyword':'AE Tax Advisors engagement','intent':'Resolve scope and implementation objections before buying AE advisory',
 'sections':[
 ('Read your AE Tax Advisors engagement as a work agreement',p('An AE Tax Advisors engagement should answer what will be reviewed, what you will receive, who completes the work and which services have separate fees. Use this guide to prepare for a scope discussion and compare the resulting written proposal with your actual needs.')+p('AE’s <a href="/pricing/">published pricing</a> lists a $7,800 standard advisory engagement, paid in two $3,900 payments 30 days apart, with no required recurring annual planning fee. Returns, amendments, cost segregation and additional services are separately scoped and priced. Your circumstances can require another scope. The signed agreement determines the services, period and obligations; this article is not an engagement letter.')+p('That distinction matters when you already have a CPA, own several entities or are buying a property. A planning review and a completed filing are different deliverables. Put both in the proposal if you need both, and identify who is responsible for each.')),
 ('Before the call: define one decision and assemble the records',p('Write down your most urgent decision, its date and the documents available. Examples include whether to commission a property review before closing, how to coordinate advisory with an existing preparer, or which prior records need reconciliation before discussing amendments. These examples describe review needs; they do not establish a tax benefit.')+p('Prepare a list of entities, owners, relevant states, current financial statements, recent returns and planned transactions. For property work, identify acquisition dates and the closing or depreciation records available. Ask AE how to submit sensitive documents securely. Bring a summary to the first discussion rather than sending private identifiers through an unapproved channel.')+p('If important records are missing, ask which conclusions must wait. An initial call should help establish whether the proposed review can answer your question and what further information is necessary.')),
 ('Put the boundaries in writing',table('Use this worksheet to check your proposal. These are items to confirm, not a promise that every engagement includes every item.',['Workstream','What the agreement should resolve'],[
 ('Review and planning','Entities, periods and records reviewed; written findings, assumptions and limitations.'),('Implementation','Action list, responsible party, delivery date and evidence of completion.'),('Preparation and filing','Specific federal and state returns, amendments or forms; fees and authorization.'),('Specialist work','Who engages a study provider or other professional and whether their fee is separate.'),('Advisory support','Start and end dates, meetings, communication process and treatment of new questions.'),('Representation','Covered matters and years, responsible professional, exclusions and separate charges.'),('Changes in scope','Who approves additional work and when a revised quote is needed.')])+p('Ask about any line that simply says “included.” Included for which entity, tax year and period? Oversight or coordination does not necessarily mean preparation by AE. If your goal requires another professional, identify that handoff before relying on a completion date.')),
 ('Worked example: coordinate with your existing preparer',p('Hypothetical owner: one operating business, two rentals and an existing CPA. The owner wants a planning review before buying another property and needs someone to implement any approved return changes. No savings amount is assumed.')+table('Illustrative responsibility map to customize with both professionals.',['Task','Owner to agree','Completion evidence'],[
 ('Supply returns, financial statements and property records','Business owner','A complete document list and confirmation of missing items.'),('Review the proposed purchase and planning questions','Advisory professional named in the scope','Written findings and unresolved assumptions.'),('Decide whether to proceed with a recommendation','Business owner after professional advice','Documented approval and any required separate engagement.'),('Prepare and file affected returns or forms','AE or existing CPA, expressly assigned','Prepared filing, authorization and acceptance evidence where applicable.'),('Update books and retain supporting records','Bookkeeper and owner, as agreed','Reconciled entries and retained supporting documents.')])+p('The map prevents a common handoff gap: both firms assume the other will update the return. If your preparer will implement the plan, ask what records and explanations they need and confirm they accept that role. If AE will prepare a filing, identify its fee and scope separately. Keep disagreements visible until resolved.')),
 ('Budget for the work your situation actually requires',p('Start with the quoted advisory work, then add each required separately quoted service. Mark unquoted work as unknown. Do not assume every owner needs amendments or every property needs a study. The review should establish what is relevant before you authorize additional spending.')+p('A larger entity group, unresolved bookkeeping or a transaction with a near-term deadline can change the proposed work. Ask which constraints affect the schedule and what can be delivered before your decision. Do not rely on a generic week-by-week timeline or a promise that all recommendations will be completed without checking your records and agreement.')+p('For a comparable budget, use the <a href="/blog/comparing-tax-advisory-fees-apples-to-oranges/">tax advisory fee worksheet</a>. For the documents behind a particular review, browse the <a href="/workbooks/">record preparation workbooks</a>. They help organize information; they do not calculate eligibility or replace professional analysis.')),
 ('Decide whether the scope is ready to sign',p('You are ready to evaluate the proposal when the decision is in scope, the delivery date is useful, fees and exclusions are clear, and implementation has an owner. Pause if the engagement depends on missing records or if a required service is still unquoted. Ask for clarification rather than filling the gaps with an assumed refund or guaranteed savings.')+p('AE’s role and support depend on the agreement you sign. This guide makes no promise of a particular tax result, refund, response time or unlimited future work. <a href="/discovery/">Book a call with AE</a> to discuss your entities, records and decision date, and request the appropriate written scope. This is general information, not individual tax or legal advice.'))],
 'faqs':[
 ('Are returns included in the standard advisory fee?',p('The published pricing treats returns and other additional services as separately scoped and priced. Identify the specific returns and fees in your written proposal.')),
 ('Can AE coordinate with my current CPA?',p('Discuss that arrangement before signing. Define the written handoff, who implements recommendations and who prepares each filing. Coordination duties must be agreed rather than assumed.')),
 ('Is ongoing support unlimited?',p('Do not assume unlimited support. Confirm the coverage period, communication process and treatment of changed facts or new projects in the agreement.')),
 ('Will an engagement guarantee tax savings?',p('No result is promised here. Outcomes depend on your facts, applicable rules, records and approved implementation. Review the assumptions behind any estimate before deciding.'))],
 'sources':[T.SITE+'/pricing/'],'scores':[24,30,12,20,9],'tool':'Written-scope checklist and responsibility handoff map',
 'overlap':'Refresh the existing branded engagement explanation rather than create another AE purchase FAQ.'
}]

for item in PAGES:
 path='/blog/'+item['slug']+'/'
 body=T.page_header(h1=item['h1'],subtitle=item['description'],trail=[('Home','/'),('Blog','/blog/'),(item['h1'],path)])
 body+=T.section('Publication and source review',p('Published '+item['published']+'; updated '+DATE+'. By AE Tax Advisors. Sources and current pricing reviewed October 7, 2026.'))
 body+=''.join(T.section(h,b) for h,b in item['sections'])
 body+=T.faq_section(item['faqs'])
 body+=T.section('Sources', '<ul>'+''.join('<li><a href="'+u+'">'+('AE service pricing' if u.endswith('/pricing/') else 'IRS: '+('credentials and representation rights' if u==CREDENTIALS else 'choosing a tax professional'))+'</a></li>' for u in item['sources'])+'</ul>')
 body+=T.related_section([('/blog/'+i['slug']+'/',i['h1']) for i in PAGES if i!=item]+[('/pricing/','AE service pricing'),('/workbooks/','Prepare your records')])
 schema=T.article_schema(title=item['h1'],description=item['description'],url=T.SITE+path,published=item['published'],modified=DATE,section='Working With Us',keywords=[item['keyword']],citations=item['sources'])
 org={'@type':'Organization','@id':T.SITE+'/#organization','name':T.BRAND,'url':T.SITE+'/','logo':{'@type':'ImageObject','url':T.SITE+'/assets/ae-tax-logo.png'}}
 schema['author']=dict(org); schema['publisher']=dict(org)
 rendered=T.build_page(title=item['title'],description=item['description'],path=path,body=body,schemas=[schema,T.faq_schema(item['faqs']),T.breadcrumb_schema([('Home','/'),('Blog','/blog/'),(item['h1'],path)])],published=item['published'],modified=DATE,active_nav='/blog/')
 T.write_page(path,re.sub(r'[ \t]+\n','\n',rendered))

# Match the existing archive cards without regenerating or changing other cards.
archive=ROOT/'blog/index.html'; text=archive.read_text()
for item in PAGES:
 href='/blog/'+item['slug']+'/'
 pattern=r'<article class="blog-card"[^>]*>[\s\S]*?</article>'
 matches=[m for m in re.finditer(pattern,text) if 'href="'+href+'"' in m.group()]
 assert len(matches)==1,item['slug']
 match=matches[0]; card=match.group()
 card=re.sub(r'data-text="[^"]*"','data-text="'+html.escape((item['h1']+' '+item['description']+' Working With Us').lower(),quote=True)+'"',card)
 card=re.sub(r'(<h3><a[^>]*>)[\s\S]*?(</a></h3>)',lambda m:m[1]+html.escape(item['h1'])+m[2],card,count=1)
 card=re.sub(r'<p>[\s\S]*?</p>','<p>'+html.escape(item['description'])+'</p>',card,count=1)
 text=text[:match.start()]+card+text[match.end():]
archive.write_text(text)
ns={'s':'http://www.sitemaps.org/schemas/sitemap/0.9'}
urls={T.SITE+'/blog/'+x['slug']+'/' for x in PAGES}
for name in ['sitemap.xml','sitemap-blog.xml']:
 f=ROOT/name; text=f.read_text(); count=0
 for url in urls:
  pat=r'<url>\s*<loc>'+re.escape(url)+r'</loc>[\s\S]*?</url>'
  matches=list(re.finditer(pat,text)); assert len(matches)==1,(name,url)
  old=matches[0].group(); new=re.sub(r'<lastmod>[^<]*</lastmod>','<lastmod>'+DATE+'</lastmod>',old)
  assert '<lastmod>'+DATE+'</lastmod>' in new
  text=text.replace(old,new);count+=1
 f.write_text(text)

# Persistent editorial evidence stays out of the public build.
out=ROOT/'_gen';out.mkdir(exist_ok=True)
ledger={'reviewDate':DATE,'scoreMeaning':'Editorial assessment, not a search-engine score or ranking forecast','gate':{'total':85,'buyerRelevance':27,'serviceFit':17},'weights':{'distinctIntent':25,'buyerRelevance':30,'questionEvidence':15,'serviceFit':20,'originalDecisionSupport':10},'articles':[]}
for x in PAGES:
 ledger['articles'].append({'url':T.SITE+'/blog/'+x['slug']+'/','action':'refresh','intent':x['intent'],'primaryKeyword':x['keyword'],'scores':dict(zip(ledger['weights'],x['scores'])),'total':sum(x['scores']),'decisionSupport':x['tool'],'overlapDecision':x['overlap'],'evidence':'Existing dedicated public article and current service pricing establish a real selection question; no search-volume estimate claimed.','sources':x['sources'],'status':'validated locally before publishing; production evidence recorded separately'})
(out/'ae-buyer-content-scores.json').write_text(json.dumps(ledger,indent=2)+'\n')
print(json.dumps({'refreshed':len(PAGES),'scores':[sum(x['scores']) for x in PAGES]}))
