#!/usr/bin/env python3
"""Generate researched competitor pricing and a buyer navigation hub. No inferred fees."""
import json,re,html
from pathlib import Path
import site_template as T
DATE='2026-10-08'
E=html.escape
ROOT=Path(__file__).resolve().parent
SOURCES=json.loads((ROOT/'content/seo-campaign-20261007/competitor-sources.json').read_text())
PROFILES={x.split('|')[0]:x.split('|')[1:] for x in (ROOT/'content/seo-campaign-20261007/competitors.tsv').read_text().splitlines()}
NOTES=json.loads((ROOT/'content/competitor-comparison-notes-20261008.json').read_text())
COVERAGE={x['slug']:x for x in json.loads((ROOT/'_gen/competitor-coverage-20261008.json').read_text())['brands']}
OWNERS={s:f'/compare/{s}-pricing-vs-ae-tax/' for s in ['peter-holtz-cpa','neil-jesani-advisors','keystone-cpa','prime-path-advisory','rainwater-cpa']}
# Manually vetted official fee excerpts. Values never extracted automatically from marketing dollar amounts.
FEES={
'keystone-cpa':('https://www.keystonecpa.com/','Tax planning: $20,000 to $55,000 flat fee.','The homepage FAQ separates planning from tax return preparation. Confirm the deliverables and payment schedule for your proposal.'),
'wcg-cpas':('https://wcginc.com/tax-center/business-advisory-services/','Vail: $4,500 per year. Telluride: $4,980 per year. Aspen: custom pricing.','The business advisory page describes annual package prices paid as monthly subscriptions. Check which returns and accounting services your selected tier covers.'),
'range':('https://www.range.com/pricing','Premium: $3,950/year. Platinum: $5,950/year. Titanium: $12,500/year.','These are financial planning membership tiers. Tax planning and personal tax filing differ by tier. Do not compare the membership fee to a standalone business tax engagement without checking scope.'),
'collective':('https://www.collective.com/plans-and-pricing','Displayed monthly plans: LLC $199/month; S Corp $349/month.','The page offers monthly and yearly billing selections. Confirm the selected billing term, entity eligibility, included returns, and any onboarding charges before annualizing a displayed price.'),
'pilot':('https://pilot.com/tax','Tax preparation starts at $1,000+/year for a single-member LLC, $2,000+/year for a partnership or S corporation, and $2,450+/year for a C corporation.','Pilot’s pricing page states tax must be purchased with Pilot Bookkeeping. Include the bookkeeping fee when comparing the total engagement.'),
'heard':('https://www.joinheard.com/pricing','Annual-billing Lite plan: $129/month equivalent, billed $1,548 upfront per year.','This is a practice accounting subscription. Lite annual tax filing is advertised as a separate $750 add-on. Quarterly estimates and an annual income tax return are different deliverables.'),
'xendoo':('https://xendoo.com/xendoo-pricing/','Essential bookkeeping: $395/month on monthly billing, or $355/month on annual billing.','Essential is shown for up to $50,000 in monthly expenses and has account and integration limits. Obtain a separate statement of tax return and planning scope.'),
'anomaly-cpa':('https://www.anomalycpa.com/','The homepage advertises bookkeeping packages starting at $750/month.','This starting package amount is not a universal standalone tax strategy fee. The service mix and complexity of your business determine the relevant proposal.'),
'basis-cost-segregation':('https://basiscostseg.com/pricing','Residential study: $1,795 per property.','Confirm that the property qualifies for the advertised residential product. A study fee does not automatically include your tax returns or implementation by your return preparer.'),
'cost-seg-atlas':('https://costseg.2911tech.com/pricing','Advertised AI study price: $395.','Review the report methodology, property eligibility, human review, and return handoff. The advertised report price is not the price of a comprehensive advisory engagement.'),
'cost-seg-smart':('https://costsegsmart.com/pricing/','Studies start at $495. The pricing page lists most residential studies at $495 to $995 and commercial studies starting at $995.','Confirm the specific property price and included support. Ask how the study findings reach your tax preparer and whether any filing work is separately contracted.'),
'my-cost-segregation':('https://www.mycostsegregation.com/pricing/','Self-service starts at $497; professional review starts at $2,500.','The pricing page changes prices by property value and service path. Confirm property eligibility and the level of review rather than treating the lowest starting fee as a quote for every building.'),
'investor-friendly-cpa':('https://www.investorfriendlycpa.com/pricing-tax-planning','Listed tax planning starting fees: Intermediate $5,497+, Advanced $9,497+, Elite $16,997+.','These are planning tier starting fees, not a verified recurring annual charge. Tax preparation is priced on a separate page. Confirm scope, term, and implementation responsibility.'),
'little-fish-accounting':('https://www.littlefishaccounting.com/taxes','Tax Prep Essentials starts at $3,500/year; Tax Prep Suite starts at $7,500/year.','The tax page distinguishes annual filing support from a broader support package. Accounting subscriptions are separate products with different pricing.'),
'costseg-express':('https://www.costseg.express/','Advertised automated study price: $99.','Confirm property eligibility, review level, report deliverables, and filing assistance. An inexpensive report and a professional tax engagement are different purchases.'),
}
CATEGORY={
'realestate':('Property and owner coordination','List properties, ownership percentages, placed-in-service dates, depreciation schedules, K-1s, and planned acquisitions. Ask for entity-level and household-level scope separately. A portfolio with several partnerships creates a different workload from one directly owned rental.','Is property accounting, the owner’s return, acquisition advice, and depreciation implementation assigned to one lead?'),
'costseg':('Study scope and return handoff','Send the address, property type, acquisition or construction cost, land allocation, square footage, placed-in-service date, and existing depreciation schedule. Identify renovations and prior studies. A report-only price should be separated from site work, accounting method changes, amended returns, and representation.','Who resolves questions from my return preparer, and what happens if the report needs correction?'),
'wealth':('Planning membership versus tax engagement','Separate investment management, financial planning, tax projections, and tax return preparation. Identify account requirements and whether the quote changes with assets, household complexity, or K-1 volume. AE’s tax engagement should not be treated as a replacement for investment management.','Can I purchase the tax work independently, and who signs the returns?'),
'startup':('Startup compliance and accounting','Identify the legal entity, funding stage, monthly expense volume, state registrations, payroll, and prior filing history. Separate bookkeeping, federal and state returns, tax credits, and CFO support. A newly formed company can require a different package from a funded multi-state employer.','Which services are mandatory companions to the quoted tax package?'),
'solopreneur':('Subscription eligibility and entity scope','Describe revenue, business expenses, current entity, payroll status, and household filing needs. Compare billing terms, formation work, catch-up bookkeeping, and the number of included returns. A sole proprietor and an S corporation have different compliance responsibilities.','What changes in price and deliverables if I elect S corporation status?'),
'filing':('Return pricing and complexity','List each personal and entity return, filing state, rental activity, K-1, and amendment year. Ask whether the quoted amount is a starting price, average price, or fixed price after document review. Tax filing does not establish that a written forward-looking plan is included.','Which schedules, states, and follow-up questions trigger a separate fee?'),
'books':('Monthly accounting and year-end work','Provide monthly transactions, bank and credit card accounts, accounting software, expense volume, and the last reconciled month. Separate monthly accounting from cleanup, payroll, tax preparation, and strategic planning. Annualizing the subscription alone can understate first-year cost.','What cleanup must be completed before the recurring package starts?'),
'national':('Specialist team and project boundaries','Define the actual project: business returns, transaction diligence, state exposure, property studies, or owner planning. Request named workstreams, responsible specialists, and a fee basis for each. A broad national-firm engagement can contain services outside AE’s tax offering.','Which specialist work is essential to my situation and how is each workstream billed?'),
'legal':('Legal documents and tax work','Separate entity formation, legal advice, document drafting, bookkeeping, tax planning, and return preparation. Identify which licensed professional owns each workstream. Compare tax services within the proposal rather than treating legal scope as interchangeable with a tax engagement.','Which legal deliverables are separately contracted from tax planning and filing?'),
'resolution':('Existing tax matters and future planning','Provide the tax years, notice deadlines, balances, and procedural status through a secure channel. Separate representation and resolution work from forward-looking planning. A fee for a controversy project does not establish the cost of ongoing compliance.','Are notices, appeals, or representation included in this particular agreement?'),
'software':('Software and professional responsibility','Identify the tool’s output, any human review, and which professional takes responsibility for interpreting it. Confirm user limits, data import, support, and filing assistance. A software subscription should be compared with another tool before it is compared with a full advisory engagement.','Who verifies the assumptions before the output is used on a return?'),
}
DEFAULT=('Advisory deliverables and implementation','Bring prior returns, current financial statements, an entity chart, payroll information, state exposure, and a list of pending decisions. Separate analysis, written recommendations, implementation meetings, bookkeeping, filing, and notice support. Confirm whether the agreement is a project, recurring subscription, or annual renewal.','Who owns implementation after the recommendations are delivered?')
def p(s):return '<p>'+E(s)+'</p>'
def table(rows):return '<div style="overflow-x:auto"><table><thead><tr><th scope="col">Item</th><th scope="col">What to verify</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+E(a)+'</th><td>'+E(b)+'</td></tr>' for a,b in rows)+'</tbody></table></div>'
def build(path,title,desc,body,keywords,citations=[]):
 trail=[('Home','/'),('Compare','/compare/'),(title,path)]
 file=ROOT/path.strip('/')/'index.html'
 published=DATE
 if file.exists():
  m=re.search(r'"datePublished"\s*:\s*"([0-9-]+)',file.read_text())
  if m:published=m[1]
 schemas=[T.article_schema(title=title,description=desc,url=T.SITE+path,published=published,modified=DATE,keywords=keywords,citations=citations),T.breadcrumb_schema(trail)]
 T.write_page(path,T.build_page(title=title+' | AE Tax Advisors',description=desc,path=path,body=T.page_header(h1=E(title),subtitle=E(desc),trail=trail)+body,schemas=schemas,published=published,modified=DATE,active_nav='/compare/'))
def inject(path,body,marker):
 f=ROOT/path.strip('/')/'index.html'
 if not f.exists():raise RuntimeError('Missing incoming owner '+path)
 text=f.read_text();text=re.sub(r'<!-- '+marker+r' -->.*?<!-- /'+marker+r' -->','',text,flags=re.S)
 text=text.replace('</main>','<!-- '+marker+' -->'+body+'<!-- /'+marker+' -->\n</main>',1)
 f.write_text(text)
manifest=[]
for s in SOURCES:
 slug,name=s['slug'],s['name'];category,focus,audience,scenario,instruction,question=PROFILES[slug]
 path=OWNERS.get(slug,f'/compare/{slug}-pricing/')
 source,fee,caveat=FEES.get(slug,(s['primary_url'],'A numeric fee was not verified in the official sources reviewed.','Request a current written quote. This does not mean the firm has no public prices; it means this guide does not have a verified amount for your engagement.'))
 heading,records,handoff=CATEGORY.get(category,DEFAULT)
 body=T.section('What does '+E(name)+' cost?',p(fee)+p(caveat)+p('Source review: October 8, 2026. Fees can change. This guide is published by AE Tax Advisors, a provider you may also be evaluating; it is not an independent rating or a quote from '+name+'.')+f'<p><a href="{E(source,quote=True)}" rel="noopener">Official {E(name)} source reviewed</a></p>')
 body+=T.section('Which engagement are you pricing?',p(name+' is included in this comparison for '+focus+'.')+p('A relevant buyer profile: '+audience+'.')+p(scenario)+p(instruction))
 if slug in NOTES:body+=T.section('Provider-specific scope considerations',p(NOTES[slug]))
 body+=T.section(heading,p(records)+table([('First-year cost','Add setup, cleanup, analysis, mandatory companion services, implementation, and filing charges for the same period.'),('Ongoing cost','Confirm renewal, minimum commitment, cancellation notice, and any price changes tied to business growth.'),('Scope boundaries',question),('Responsibility',handoff)]))
 body+=T.section('A quote request tailored to this decision',p('Use this as a starting point and send sensitive documents through the provider’s secure intake process:')+'<blockquote>'+p('I am evaluating '+name+' for '+focus+'. '+scenario+' '+question+' Please separate initial analysis, implementation, recurring support, and filing. Specify the legal entities and tax years covered, exclusions, required companion services, payment dates, and renewal terms. '+handoff)+'</blockquote>')
 body+=T.section('Compare '+E(name)+' with AE Tax Advisors',p('Compare only the work both proposals actually contain. AE’s current published standard advisory fee is $7,800, paid in two $3,900 installments 30 days apart, with no required recurring annual planning fee. Returns, amendments, cost segregation, and additional services are separately scoped. Confirm the current agreement before committing.')+p('A lower filing or software price can be appropriate when that is all you need. A broader engagement can be appropriate when several professionals or workstreams must be coordinated. Neither price alone establishes quality, eligibility for a deduction, or guaranteed savings.')+'<p><a href="/pricing/">Review AE’s current fees</a> and bring both proposals to a <a href="/discovery/">consultation</a> to discuss scope and fit.</p>')
 cov=COVERAGE[slug]
 body+=T.related_section([('/compare/competitor-pricing/','Browse pricing for 100 providers'),(cov['alternative_url'].replace(T.SITE,''),name+' alternatives'),(cov['comparison_url'].replace(T.SITE,''),name+' versus AE'),('/compare/tax-advisor-buying-guide/','Tax advisor buying guide')])
 desc='Review '+name+' pricing, fee scope, billing questions, and a tailored quote checklist before comparing tax providers.'
 build(path,name+' Pricing: Fees, Scope and Quote Questions',desc,body,[name+' pricing',name+' cost',name+' fees',name+' vs AE Tax Advisors'],[source,T.SITE+'/pricing/'])
 inject(cov['alternative_url'].replace(T.SITE,''),T.section(E(name)+' pricing and fees',f'<p><a href="{path}">Review {E(name)} pricing, verified fee information, and quote questions</a> before comparing proposals.</p>'),'vendor-pricing-20261008')
 manifest.append({'slug':slug,'name':name,'path':path,'category':category,'source':source,'fee':fee,'qualification':caveat,'reviewed':DATE,'keywords':[name+' pricing',name+' cost',name+' fees']})
(ROOT/'content/vendor-pricing-20261008.json').write_text(json.dumps(manifest,indent=2)+'\n')
rows=''.join(f'<tr data-provider="{E((r["name"]+" "+r["category"]).lower(),quote=True)}"><th scope="row"><a href="{r["path"]}">{E(r["name"])} pricing</a></th><td>{E(r["category"])}</td><td>{E(r["fee"])}</td></tr>' for r in sorted(manifest,key=lambda x:x['name']))
body=T.section('Compare the same work and billing period',p('This directory covers 100 tax, accounting, cost segregation, and adjacent providers. Published fees are included only where a numeric amount was verified. When the reviewed source did not establish a price, the individual guide supplies a provider-specific quote request. Some firms offer legal, investment, or specialist services outside AE’s scope.')+p('AE Tax Advisors publishes this directory. It is a commercial comparison resource, not an independent ranking. A starting fee, monthly bookkeeping plan, annual filing package, and financial planning membership are different products.')+'<p><a href="/compare/tax-advisor-buying-guide/">Start with the buyer guide</a> or <a href="/pricing/">review AE’s pricing</a>.</p>')
body+=T.section('Find a provider','<label for="provider-search">Filter by provider name or service category</label><input id="provider-search" type="search" style="display:block;width:100%;padding:12px;margin:12px 0" placeholder="Example: Keystone, Pilot, costseg"><p id="provider-count" aria-live="polite">100 providers</p><div style="overflow-x:auto"><table><thead><tr><th scope="col">Provider</th><th scope="col">Category</th><th scope="col">Verified fee summary</th></tr></thead><tbody id="provider-rows">'+rows+'</tbody></table></div><script>document.getElementById("provider-search").addEventListener("input",function(){let n=0;document.querySelectorAll("#provider-rows tr").forEach(r=>{r.hidden=!r.dataset.provider.includes(this.value.toLowerCase().trim());if(!r.hidden)n++});document.getElementById("provider-count").textContent=n+" providers"});</script>')
build('/compare/competitor-pricing/','Tax Advisor and Cost Segregation Pricing: 100 Providers','Compare official fee information and quote checklists for 100 tax, accounting, and cost segregation providers.',body,['tax advisor pricing comparison','cost segregation pricing comparison'])
print('Generated',len(manifest),'pricing pages and directory')
