import json,re,html
from pathlib import Path
import site_template as T
ROOT=Path(__file__).resolve().parent
DATE='2026-10-07'
def p(s):return '<p>'+s+'</p>'
def table(headers,rows):return '<div style="overflow-x:auto"><table class="compare-table"><thead><tr>'+''.join('<th scope="col">'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">' if i==0 else '<td>')+v+('</th>' if i==0 else '</td>') for i,v in enumerate(r))+'</tr>' for r in rows)+'</tbody></table></div>'
items=[{
'slug':'why-7800-tax-advisory-saves-50k','published':'2026-05-15','title':'Is Tax Advisory Worth It? | AE Tax Advisors','h1':'Is Tax Advisory Worth the Cost for Your Situation?',
'description':'Evaluate tax advisory value using a clear baseline, complete costs and smaller-benefit scenarios. Compare a written proposal before committing.',
'intent':'Decide whether to purchase advisory given uncertain benefits','scores':[24,29,12,19,9],
'sections':[
('Define the problem before calculating a return',p('Tax advisory can be worth the cost when it helps you make an important decision or resolve a documented planning problem. The value depends on your facts, the work purchased and what happens after the review. Paying a particular fee does not establish that you will save a particular amount.')+p('Begin with the decision you cannot confidently make today. Perhaps your operating business and rental properties have separate preparers, or a proposed sale needs review before you agree to its terms. Ask what analysis would change that decision. If you only need an accurate return for a straightforward situation, ask whether a preparation-only service meets the need.')+p('This guide is a buying framework. It does not estimate your tax liability or report client results. The examples below are hypothetical so you can see how different assumptions affect the purchase.')),
('Keep four measures separate',table(['Measure','Meaning','What to ask'],[
('Proposed deduction','An amount that may reduce taxable income if applicable','Which facts and limitations determine whether it can be used?'),('Estimated tax reduction','A modeled change from a defined tax baseline','Which taxes, periods and assumptions are included?'),('Cash refund','A payment outcome that depends on the filed return and prior payments','Has it been filed and received, or is it only projected?'),('Net economic benefit','Benefit after required costs and other relevant consequences','Which fees, spending and later effects remain outside the estimate?')])+p('Do not compare a deduction directly with an advisory fee. Do not call a proposed refund received cash. Ask the professional to label each figure, explain the baseline and identify what has not been established. A neat percentage is not useful if the underlying measures differ.')),
('Build the complete cost before estimating value',p('AE’s <a href="/pricing/">published standard advisory price</a> is $7,800, with no required recurring annual planning fee. Returns, amendments, cost segregation and additional services are separately scoped and priced. Use your written quote to determine the actual project cost.')+p('Add required implementation charges and independent professional fees. Keep optional work separate. If a recommendation requires a purchase or contribution, distinguish that cash commitment from the professional fee; spending money is not itself proof of a benefit. Record future obligations when relevant and ask what assumptions require a separate analysis.')+p('Use the <a href="/blog/comparing-tax-advisory-fees-apples-to-oranges/">proposal comparison worksheet</a> to organize the numbers. An unknown item should remain unknown rather than being entered as zero.')),
('Worked example: test a smaller benefit',p('Hypothetical project: $7,800 of advisory plus $2,200 of required additional work gives a $10,000 fee budget. Assume the modeled tax reductions below are incremental to a defined baseline. They are arithmetic scenarios, not expected AE outcomes. No deduction, refund or investment return is promised.')+table(['Scenario','Modeled reduction','Less $10,000 fees','Narrow net result'],[
('Lower benefit','$4,000','$10,000','Negative $6,000'),('Fee break-even','$10,000','$10,000','$0'),('Higher benefit','$18,000','$10,000','Positive $8,000')])+p('The first scenario does not support buying the project solely for tax reduction. The middle scenario merely covers the assumed fees; it does not compensate for your time or any omitted costs. The last produces a positive figure only under the stated assumptions. If the benefit is delayed, compare the timing of the payments and benefits as well.')+p('A review may also clarify a transaction, document an uncertain position or help prevent an implementation gap. Those can be valid reasons to buy professional work, but describe them directly. Do not assign invented savings to a compliance or decision-quality benefit just to make the calculation positive.')),
('Ask what could make the estimate smaller',p('Request the lower-benefit case before signing. Which missing record, eligibility issue, changed transaction or implementation delay would reduce the modeled result? What work remains valuable if a proposed strategy is unavailable? Ask which conclusions are established by reviewed documents and which remain assumptions.')+p('If the recommendation shifts timing between years, ask for the relevant later-year comparison instead of focusing on the first year alone. If it relies on another professional, confirm their scope and fee. If you cannot complete the required actions, ask whether the analysis should be narrowed or deferred.')),
('Choose a scope you can justify',p('A useful proposal identifies your decision, the analysis to be delivered, the responsible professional and the implementation handoff. You should be able to explain why that work is worth buying even after reading the limitations. If you cannot, ask for clarification or a smaller initial review.')+p('Prepare your entity list, recent returns, current books and planned transaction dates. Review <a href="/blog/what-you-actually-get-with-ae-tax-advisors/">AE’s engagement questions</a>, then <a href="/discovery/">book a call with AE</a> to discuss an appropriate written scope. This is general information, not individual tax or legal advice.'))],
'faq':[('Does paying $7,800 guarantee $50,000 in savings?',p('No. A fee does not establish an outcome. Review your facts, the complete project costs, assumptions and implementation responsibilities before relying on an estimate.')),('How should I calculate advisory value?',p('Use a defined baseline and separate proposed deductions, modeled tax reductions and received refunds. Subtract required costs and review timing and other consequences with the professional.')),('What if the estimate is smaller than the fee?',p('Ask whether the project still addresses a decision or compliance need you value, whether a smaller scope is appropriate, or whether to defer the work. Do not assume more strategies will produce a larger result.'))],
'tool':'Baseline worksheet and three-case fee sensitivity',
'overlap':'Refresh existing value/ROI article; retain fee-comparison article for proposal normalization.'
},{
'slug':'how-much-should-you-pay-tax-advisory','published':'2026-06-06','title':'Tax Advisory Budget and Scope | AE Tax Advisors','h1':'How Much Should You Budget for Tax Advisory?',
'description':'Build a tax advisory budget around your decision, required work and written quote. Compare preparation, focused review and coordinated planning scopes.',
'intent':'Select an appropriate service scope and budget before requesting a quote','scores':[23,28,12,19,9],
'sections':[
('Budget for a defined job',p('How much you should pay for tax advisory depends on the job you need done. Start by describing the decision, documents and deadline. An advisor cannot reliably price an undefined promise to “optimize everything,” and a low initial fee can leave necessary work unquoted.')+p('Avoid choosing a budget solely from a generic industry price range. Providers organize services differently. Some quote a focused review; others bundle ongoing accounting or preparation. Ask for the smallest scope that addresses the decision and identify what would trigger additional work. This guide helps you prepare that request without assuming a market-wide fee or tax result.')),
('Choose the type of work first',table(['Your immediate need','Scope to discuss','Boundary to confirm'],[
('Report completed transactions','Return preparation','Which returns, entities and states are covered?'),('Answer one upcoming decision','Focused professional review','Which question, assumptions and written conclusion are included?'),('Coordinate interacting business and property decisions','Advisory planning','Which workstreams and implementation handoffs are covered?'),('Complete approved filings or specialist work','Separately assigned implementation','Who performs each task, at what fee and by which date?'),('Keep changing facts under review','Ongoing service','Meetings, support period, renewal terms and exclusions.')])+p('These are ways to frame a scope discussion, not official service categories or claims about every provider. A single firm can offer several of them. Ask it to explain the proposal in terms of the work you need rather than relying on the package name.')),
('Create a quote-ready situation summary',p('List your entities and ownership, relevant states, recent returns, financial statements, property records and the transaction you are planning. Describe what your current preparer already does. Identify the decision date and any documents still missing. Ask about the secure submission process before sharing sensitive records.')+p('Then write one sentence describing a successful deliverable: “I need a written review of the proposed transaction and a handoff my preparer can use before I commit.” That sentence is more useful for pricing than an income figure alone. A large income does not establish that a particular strategy applies or that a broad engagement is justified.')+p('Tell the firm what you can implement yourself and what requires help. If your bookkeeper will supply reconciled records, confirm that arrangement. If cleanup is needed, ask whether it must happen before analysis and whether its fee belongs in the quote.')),
('Worked example: two budgets for two different jobs',p('Hypothetical owner with a business and two rentals: the current preparer handles annual filing, but an upcoming acquisition creates one question. The owner can either request a focused review or a broader coordinated plan. The following invented figures demonstrate scope budgeting; they are not AE prices or competitor quotes.')+table(['Budget item','Focused review','Broader plan'],[
('Professional review','$2,000','$6,000'),('Required separate implementation','$1,000','$2,000'),('Known project budget','$3,000','$8,000'),('Annual preparation','Existing arrangement; not included','Existing arrangement; not included')])+p('The broader proposal costs $5,000 more in this example. It is worth considering only if its additional work addresses decisions the owner actually needs help making. Ask which deliverables differ. If both proposals answer the acquisition question adequately, the focused option may be enough. If several unresolved decisions interact, the broader review may be more useful.')+p('Do not assume either proposal includes a study, amended return or unlimited support. Mark conditional work separately and request a revised quote if it becomes necessary. No savings amount is assumed here, so the table does not establish a return on either purchase.')),
('Fit published AE pricing into your actual scope',p('Use <a href="/pricing/">AE’s current pricing page</a> as a starting point, then request a written quote for your situation. Published standard packages do not resolve every entity, filing or implementation requirement. Confirm your service boundaries in the <a href="/blog/what-you-actually-get-with-ae-tax-advisors/">engagement scope checklist</a>.')+p('If you are deciding between providers, normalize their written proposals using the <a href="/blog/comparing-tax-advisory-fees-apples-to-oranges/">fee comparison guide</a>. If you are deciding whether to buy advisory at all, use the <a href="/blog/why-7800-tax-advisory-saves-50k/">value assessment</a> and test a smaller-benefit case. Those are distinct decisions; completing one does not settle the others.')),
('Manage scope changes after the first quote',p('Before signing, ask how additional entities, changed transactions or incomplete records affect the price. Identify who approves new work and whether the firm will provide the revised scope before starting. Agree on the support period and treatment of later questions. Keep the initial quote, approvals and completion records together.')+p('A useful budget is a record of agreed work and known uncertainty. It does not need a speculative tax-savings figure to look persuasive. <a href="/discovery/">Book a call with AE</a> with your situation summary to discuss the right scope. General information only; the signed agreement governs services and fees.'))],
'faq':[('Is there one correct tax advisory budget?',p('No. The appropriate budget depends on your decision, required analysis and implementation. Ask for a written quote rather than assuming a generic fee range applies.')),('Can I request a focused review?',p('Ask the provider whether a focused scope can address your question and what limitations it would have. Do not assume every firm offers the same service or that the review includes implementation.')),('What should happen when scope expands?',p('Confirm the additional work, responsible party and revised fee in writing before authorizing it. Keep conditional work separate from the initial required budget.'))],
'tool':'Scope selector and two-job budget example',
'overlap':'Refresh existing budget article; distinguish choosing service scope from comparing competing quotes.'
}]
ledger=json.loads((ROOT/'_gen/ae-buyer-content-scores.json').read_text())
manifest=[]
for x in items:
 path='/blog/'+x['slug']+'/'
 body=T.page_header(h1=x['h1'],subtitle=x['description'],trail=[('Home','/'),('Blog','/blog/'),(x['h1'],path)])
 body+=T.section('Publication and review',p('Published '+x['published']+'; updated '+DATE+'. By AE Tax Advisors. Pricing source reviewed October 7, 2026.'))
 body+=''.join(T.section(h,b) for h,b in x['sections'])+T.faq_section(x['faq'])
 body+=T.section('Source and scope',p('<a href="/pricing/">AE published service pricing</a>. All worked examples above are hypothetical; the signed proposal determines actual services and fees.'))
 body+=T.related_section([('/blog/'+y['slug']+'/',y['h1']) for y in items if y!=x]+[('/blog/how-to-evaluate-tax-advisor/','Choose an advisor'),('/pricing/','AE pricing')])
 schema=T.article_schema(title=x['h1'],description=x['description'],url=T.SITE+path,published=x['published'],modified=DATE,section='Working With Us',citations=[T.SITE+'/pricing/'])
 org={'@type':'Organization','@id':T.SITE+'/#organization','name':T.BRAND,'url':T.SITE+'/','logo':{'@type':'ImageObject','url':T.SITE+'/assets/ae-tax-logo.png'}}
 schema['author']=dict(org);schema['publisher']=dict(org)
 rendered=T.build_page(title=x['title'],description=x['description'],path=path,body=body,schemas=[schema,T.faq_schema(x['faq']),T.breadcrumb_schema([('Home','/'),('Blog','/blog/'),(x['h1'],path)])],published=x['published'],modified=DATE,active_nav='/blog/')
 T.write_page(path,re.sub(r'[ \t]+\n','\n',rendered))
 ledger['articles']=[a for a in ledger['articles'] if a['url']!=T.SITE+path]
 ledger['articles'].append({'url':T.SITE+path,'action':'refresh','intent':x['intent'],'scores':dict(zip(ledger['weights'],x['scores'])),'total':sum(x['scores']),'decisionSupport':x['tool'],'overlapDecision':x['overlap'],'evidence':'Existing public question article; no search volume or conversion evidence claimed.','sources':[T.SITE+'/pricing/']})
 archive=ROOT/'blog/index.html';s=archive.read_text();matches=[m for m in re.finditer(r'<article class="blog-card"[^>]*>[\s\S]*?</article>',s) if 'href="'+path+'"' in m.group()];assert len(matches)==1
 m=matches[0];c=m.group();c=re.sub(r'data-text="[^"]*"','data-text="'+html.escape((x['h1']+' '+x['description']).lower(),quote=True)+'"',c)
 c=re.sub(r'(<h3><a[^>]*>)[\s\S]*?(</a></h3>)',lambda m:m[1]+html.escape(x['h1'])+m[2],c,count=1);c=re.sub(r'<p>[\s\S]*?</p>','<p>'+html.escape(x['description'])+'</p>',c,count=1)
 archive.write_text(s[:m.start()]+c+s[m.end():])
 for name in ['sitemap.xml','sitemap-blog.xml']:
  f=ROOT/name;s=f.read_text();pat=r'<url>\s*<loc>'+re.escape(T.SITE+path)+r'</loc>[\s\S]*?</url>';matches=list(re.finditer(pat,s));assert len(matches)==1
  old=matches[0].group();f.write_text(s.replace(old,re.sub(r'<lastmod>[^<]*</lastmod>','<lastmod>'+DATE+'</lastmod>',old)))
(ROOT/'_gen/ae-buyer-content-scores.json').write_text(json.dumps(ledger,indent=2)+'\n')
(ROOT/'_gen/ae-buyer-value-batch.json').write_text(json.dumps([{'url':T.SITE+'/blog/'+x['slug']+'/','score':sum(x['scores']),'published':x['published']} for x in items],indent=2)+'\n')
print('Refreshed two value and budget articles')
