#!/usr/bin/env python3
"""Build 100 focused real estate and business tax explainers.

Each row carries a distinct fact pattern, decision, evidence request, and failure mode.
The shared renderer supplies site chrome; this file owns editorial content.
"""
from __future__ import annotations

import html
import re
from pathlib import Path

import seo_render

seo_render.BASE = "https://www.aetaxadvisors.com"

# slug | question | direct answer | planning decision | evidence to retain | common mistake
REAL_ESTATE = """
rental-property-security-deposit-tax|Is a rental security deposit taxable when received?|A refundable tenant deposit is generally a liability rather than rent when the landlord expects to return it; an amount kept for unpaid rent or damage becomes income when retained.|Reconcile the deposit ledger to the lease at move-out and distinguish withheld rent from reimbursement for damage before posting income and expenses.|Keep the signed lease, deposit receipt, itemized deductions, move-out photos, and refund confirmation.|Treating every deposit as rent on receipt overstates current income; omitting a forfeited deposit understates it.
rental-property-prepaid-rent-tax|How is prepaid rent taxed to a rental owner?|Advance rent is generally included in rental income when received, even if it covers a later occupancy period; a refundable security deposit has different treatment.|Separate prepaid rent from a genuinely refundable deposit in the lease and accounting system.|Save the lease, payment dates, rent ledger, and any written allocation of lump-sum payments.|Calling nonrefundable last-month rent a security deposit does not postpone tax.
rental-property-tenant-paid-expenses|Are expenses paid by a tenant taxable to the landlord?|When a tenant pays an expense that is the landlord's obligation, the payment is generally rental income to the owner and the owner may separately deduct an eligible expense.|Read the lease to identify who legally owes the cost before recording the tenant's payment.|Retain the lease clause, vendor bill, proof of tenant payment, and the owner's expense ledger.|Netting the payment away can hide both rental income and the matching expense.
rental-property-services-in-lieu-of-rent|How are tenant services in exchange for rent taxed?|The fair market value of services a tenant provides instead of rent is generally rental income, with the related expenditure analyzed separately for deduction or capitalization.|Value the work and decide whether it was routine maintenance or a capital improvement rather than booking a zero-dollar month.|Keep the rent concession, scope of work, invoices or value estimate, and before-and-after records.|Ignoring the barter transaction or deducting an improvement immediately misstates the return.
rental-property-cancelled-lease-payment|Is a lease cancellation payment rental income?|A payment received from a tenant for cancelling a lease is ordinarily rental income to the property owner.|Identify whether the payment is for lost rent, property damage, or another claim, because related expenses may be treated differently.|Retain the original lease, termination agreement, payment statement, and correspondence describing the claim.|Labelling a settlement as damages does not by itself determine the federal tax character.
rental-property-owner-paid-utilities|Can landlords deduct utilities they pay for tenants?|Utilities paid by a rental owner are generally deductible rental operating expenses when the property is held for rent; amounts reimbursed by tenants are rental income.|Allocate shared meters between rental and personal areas using a supportable measure.|Keep utility bills, reimbursement ledger, meter data, and allocation worksheet.|Deducting the full bill for a partly personal property ignores the personal-use portion.
rental-property-vacancy-expenses|Can you deduct expenses while a rental sits vacant?|Ordinary expenses may remain deductible while a property is vacant if it is genuinely held out for rent; personal use and improvements require separate analysis.|Document the marketing period and the date the unit was ready and available to rent.|Keep listings, inquiries, agent agreement, insurance, bills, and a vacancy calendar.|A property held for future personal use is not automatically a rental simply because it is empty.
rental-property-placed-in-service-date|When does rental-property depreciation start?|Depreciation begins when the property is ready and available for its intended rental use, not necessarily when a tenant first moves in or when the purchase closes.|Pin down the date repairs ended and active rental marketing began; separate later improvements into their own placed-in-service dates.|Keep dated listings, inspection records, contractor completion invoices, and lease applications.|Starting depreciation on closing day while major renovations prevent occupancy can accelerate it improperly.
rental-property-land-value-allocation|How do you split a rental purchase between land and building?|Land is not depreciable, so the purchase price and qualifying acquisition costs must be allocated between land and depreciable improvements on a reasonable basis.|Compare the appraisal, assessor values, and transaction evidence rather than copying a generic percentage.|Retain the settlement statement, appraisal, assessor allocation, and a written basis calculation.|Assigning all purchase price to the building overstates depreciation and creates future recapture exposure.
rental-property-closing-costs-basis|Which rental-property closing costs add to basis?|Costs directly tied to acquiring the property generally add to basis; loan costs and prorated operating items may receive different treatment.|Classify each settlement line instead of capitalizing the entire closing statement or deducting it all.|Keep the closing disclosure, loan documents, invoices, and basis schedule by asset.|Lender charges, title costs, escrow deposits, and prepaid taxes do not all follow one rule.
rental-property-loan-origination-fees|How are loan origination fees on a rental deducted?|Borrowing costs are generally recovered over the loan term rather than treated as the building's depreciable basis or a full current deduction.|Separate acquisition costs from financing charges and track refinancing or early payoff events.|Save loan disclosures, amortization schedule, payoff statement, and refinancing documents.|Putting financing costs into building basis can defer or distort the deduction.
rental-property-mortgage-points|Can rental-property mortgage points be deducted at closing?|Points on a loan for rental property are generally spread over the loan term, unlike the limited immediate deduction sometimes available for a principal residence.|Determine the term and whether the payment truly represents prepaid interest.|Retain the settlement statement, note, amortization worksheet, and payoff records.|Applying the personal-home point rule to an investment property can produce an early deduction.
rental-property-replacement-roof|Is a replacement roof on a rental an expense or improvement?|Replacing a roof is generally a capital improvement recovered through depreciation; isolated repairs to a small damaged area can differ.|Compare the work with the building's roof unit of property and consider any remaining basis in the disposed old component.|Keep contractor scope, photographs, invoice detail, and the fixed-asset ledger.|Describing a complete roof replacement as a repair does not change its substance.
rental-property-appliance-replacement|How do landlords depreciate replacement appliances?|A separately identifiable appliance placed in a rental may have a different recovery period from the building; the acquisition and placed-in-service facts determine treatment.|Track appliances separately and review applicable expensing elections rather than merging every purchase into building basis.|Keep itemized invoices, delivery date, asset location, and disposal record for the replaced appliance.|Losing the asset-level records can cause duplicate depreciation after a replacement.
rental-property-fence-depreciation|Is a new fence on a rental property deductible immediately?|A new fence is generally a land improvement that must be capitalized and depreciated under its applicable class rather than deducted as ordinary maintenance.|Distinguish a new installation from repairing an existing section and identify the area used for rental activity.|Retain site plan, work order, invoice, and placed-in-service evidence.|Treating every outdoor project as a nondeductible land cost can also miss allowable depreciation.
rental-property-driveway-improvement|How is a new rental-property driveway depreciated?|A newly installed or substantially improved driveway is generally a depreciable land improvement, while routine patching may be a repair.|Identify whether the work restored the existing surface or created a new or materially better one.|Keep before-and-after photos, contractor scope, cost detail, and date opened for use.|A single invoice labelled paving cannot settle the repair-versus-improvement question.
rental-property-landscaping-basis|Can a landlord depreciate landscaping costs?|Certain land improvements such as landscaping features may be depreciable, while the underlying land itself is not; classification depends on the asset created.|Separate grading integral to a building, removable landscaping, and routine maintenance before assigning recovery periods.|Retain plans, itemized bills, photographs, and asset schedule.|A blanket land allocation can miss depreciable improvements or depreciate nondepreciable land.
rental-property-casualty-insurance-proceeds|How are rental insurance proceeds handled after damage?|Insurance recovery and the property's adjusted basis must be compared; a casualty loss, gain, repair deduction, or basis adjustment can result depending on facts.|Model the damaged component, proceeds, deductible, and restoration costs before booking the settlement.|Keep the insurer's adjustment, repair estimates, checks, photographs, and pre-loss basis records.|Deducting the full repair bill while ignoring the insurance recovery can double-count a loss.
rental-property-condemnation-proceeds|What happens when rental land is condemned?|A condemnation can create a taxable gain or loss, with possible deferral under involuntary conversion rules if qualifying replacement property is acquired on time.|Identify the property taken and the statutory replacement period before committing proceeds to another investment.|Keep the condemnation award, appraisal, adjusted-basis allocation, and replacement closing documents.|Assuming every government payment is ordinary rent overlooks gain and replacement-property rules.
rental-property-property-tax-proration|Who deducts prorated property taxes at a rental closing?|Real property taxes at a sale are generally allocated between buyer and seller according to the period of ownership, even when one party remits the bill.|Reconcile the closing statement to the local tax period and distinguish taxes from transfer fees or assessments.|Keep the tax bill, closing disclosure, and allocation worksheet.|Using only the cash paid at closing may assign the seller's tax to the buyer.
rental-property-special-assessment|Is a street or sewer assessment on a rental deductible?|A local assessment for a specific property improvement generally increases basis; a charge for ordinary maintenance may be deductible as a rental expense.|Read the assessment notice to identify the improvement and any separately stated maintenance or interest.|Keep the municipal notice, payment schedule, and basis entry.|Booking every municipal charge as property tax ignores capital assessments.
rental-property-hoa-dues|Are HOA fees on a rental property deductible?|Regular association dues related to an income-producing rental are generally operating expenses; a special assessment for a capital project may need capitalization.|Request the association's explanation of how a special assessment will be spent.|Retain HOA statements, budget, project notice, and rental-use calendar.|A roof replacement funded through an HOA assessment does not automatically become a routine dues deduction.
rental-property-owner-travel|When is travel to manage a rental deductible?|Travel must have a genuine rental business purpose and be substantiated; mixed personal trips require allocation, and improvements may require capitalization of related costs.|Plan and document the work done at each property before deciding how to allocate transportation and lodging.|Keep dated itinerary, mileage log, receipts, work orders, and property communications.|A vacation with a brief property visit does not convert the whole trip into a rental expense.
rental-property-mileage-between-properties|Can landlords deduct mileage between rental properties?|Transportation between rental activities may be deductible when tied to rental operations, subject to the applicable vehicle and substantiation rules.|Track trips by destination and purpose, and distinguish commuting or personal errands.|Keep contemporaneous mileage, maintenance appointments, tenant messages, and total annual mileage.|A year-end estimate from a map is weaker than a trip-by-trip log.
rental-property-home-office-management|Can a landlord claim a home office for rental management?|A dedicated management space may qualify only if the business-use-of-home tests are met; rental activity alone does not automatically satisfy them.|Assess exclusive and regular use and whether the rental operation qualifies under the relevant trade-or-business standard.|Keep a floor plan, photos, expense records, and activity calendar.|Occasional bookkeeping at a kitchen table does not establish exclusive use.
rental-property-paid-property-manager|Does using a property manager affect rental tax losses?|Management fees are generally rental expenses, but outsourcing operational work may leave an owner without enough participation for certain passive-loss exceptions.|Separate expense treatment from the distinct question of whether the owner materially participates.|Keep the management contract, invoices, owner work log, and activity grouping records.|Claiming the manager's hours as the owner's own participation is not permitted.
rental-property-co-owner-expense-sharing|How do co-owners split rental income and deductions?|Co-owners generally report their shares of rental income and expenses based on beneficial ownership and actual arrangements; a joint venture may require partnership analysis.|Reconcile title, contributions, cash distributions, and who actually bears liabilities before preparing separate returns.|Keep deed, co-ownership agreement, bank statements, and annual settlement schedule.|Splitting everything 50/50 when ownership and economics differ can misstate both returns.
rental-property-gifted-property-basis|What is the tax basis of a gifted rental property?|A donee's basis often carries over from the donor, with special rules for property received at a loss and for gift tax paid; fair market value alone is not the default.|Obtain the donor's original cost, improvements, depreciation, and gift-date valuation before claiming deductions.|Keep gift documents, donor depreciation schedule, appraisals, and Form 709 if filed.|Resetting depreciation basis to market value at the gift date generally overstates deductions.
rental-property-inherited-basis|How does inherited rental-property basis work?|Inherited property's basis is generally tied to date-of-death value, subject to applicable estate and alternate-valuation rules; a new depreciation schedule may begin when held for rent.|Separate inherited land and building values and account for any estate-level valuation choice.|Keep estate inventory, appraisal, probate records, and rental placed-in-service evidence.|Continuing the decedent's depreciation schedule without examining the new basis can miss or overstate deductions.
rental-property-converted-home-basis|What basis applies when a home becomes a rental?|For depreciation after a personal residence converts to rental use, the starting basis is generally the lower of adjusted basis or fair market value at conversion, excluding land.|Establish conversion-date value and accumulated improvements before computing depreciation.|Keep appraisal or comparable sales, historic purchase and improvement records, and first rental listing.|Using today's market value after a decline can create depreciation the tax rules do not allow.
rental-property-converted-to-personal-use|What happens when a rental becomes a personal home?|Rental expenses and depreciation end when the property is no longer held for income production; basis and depreciation history remain relevant to a later sale.|Set a documented conversion date and separate expenses incurred before and after it.|Keep move-in records, listing withdrawal, depreciation schedules, and annual use calendar.|Continuing Schedule E deductions after permanent personal conversion is a common error.
rental-property-partial-personal-use|How do you allocate expenses for a partly personal rental?|A property used both personally and for rent requires allocation of shared costs; vacation-home limits can apply when personal use exceeds statutory thresholds.|Count personal and rental days accurately and identify direct expenses that belong entirely to one use.|Keep reservation calendar, owner-use dates, utility bills, and allocation worksheet.|Ignoring family use or treating a below-market rental as a market rental can change the allowed deduction.
rental-property-family-below-market-rent|Is a rental to family at below-market rent a rental activity?|Renting to a family member below fair rental value can be treated as personal use for vacation-home rules, limiting rental deductions.|Compare the charged rent with comparable market terms and document whether the family member uses the home as a principal residence.|Keep comparable listings, signed lease, payments, and occupancy calendar.|A signed lease alone does not make a discounted family arrangement arm's-length.
rental-property-airbnb-cleaning-fees|Are cleaning fees on short-term rentals taxable income?|Guest cleaning fees are generally receipts of the rental activity; payments to cleaners are separately analyzed as expenses.|Reconcile platform gross receipts to deposits and fees rather than recording only the net payout.|Keep platform statements, guest invoices, cleaner bills, and payment records.|Reporting net payouts can omit both revenue and platform expenses.
rental-property-airbnb-occupancy-taxes|How should short-term rental occupancy taxes be recorded?|The treatment depends on whether the tax is imposed on the host or collected from the guest as an agent for the taxing authority; platform remittance adds another layer.|Read the local ordinance and platform statement before classifying tax collected and paid.|Keep platform tax reports, jurisdiction rules, filings, and bank reconciliation.|Counting pass-through tax as revenue without the remittance, or omitting a host tax obligation, distorts results.
rental-property-short-stay-average-period|How is average guest stay measured for short-term rental passive rules?|The average customer use period is based on actual rental periods and can affect whether the activity is classified as a rental activity under Section 469 regulations.|Calculate a weighted average from all stays rather than looking only at the shortest reservation.|Keep booking exports showing arrival and departure dates, cancellations, and owner-use days.|A listing advertised for short stays does not prove the actual average use period.
rental-property-short-stay-services|When do services turn a short-term rental into a different tax activity?|Substantial services primarily for guest convenience can change how an accommodation activity is reported and may affect self-employment tax; routine cleaning between stays differs.|List services delivered during occupancy and compare them with ordinary lodging or hotel services.|Keep service menus, staffing records, guest messages, and revenue by service.|Assuming every short-term rental belongs on Schedule E can be wrong when hotel-like services are provided.
rental-property-guest-damage-fees|Are guest damage charges rental income?|Amounts retained from guests for damage may be rental receipts, while the repair, insurance, and basis consequences need separate analysis.|Reconcile claims from platform protection programs with actual restoration costs and any capitalized replacement.|Keep incident photos, guest charge, platform settlement, and contractor invoices.|Netting a damage reimbursement against a capital improvement may hide both transactions.
rental-property-lease-option-payment|How is an option payment on rental real estate taxed?|A genuine option payment is usually held for later characterization: it may enter the sale proceeds if exercised or become income if the option expires.|Review whether the agreement is truly an option or an installment sale in substance.|Keep the signed option, payment schedule, exercise notice, and settlement statement.|Immediately treating every option payment as ordinary rent can be premature.
rental-property-lease-purchase-rent-credit|How do rent credits in a lease-purchase arrangement work?|Amounts called rent may partly function as purchase consideration when they are credited toward a binding purchase; the contract's economics matter.|Separate fair-market rent from the purchase-credit portion and examine whether benefits and burdens transferred early.|Keep the lease-option agreement, fair-rent comparables, payment ledger, and final closing statement.|The contract label cannot override an arrangement that operates like a sale.
rental-property-abandoned-tenant-property|Can a landlord deduct abandoned tenant property cleanup?|Reasonable cleanup after a tenant leaves may be an operating expense, while replacement or restoration of a major component can be capital.|Separate debris removal, minor repair, and new asset costs in contractor billing.|Keep move-out report, dated photos, itemized invoices, and insurance settlement.|Combining renovation and cleanup on one invoice encourages an unsupported current deduction.
rental-property-eviction-legal-fees|Are eviction legal fees deductible for a rental?|Legal fees tied to collecting rent or removing a tenant are generally rental operating expenses; fees to acquire or defend title may be capital.|Ask counsel to itemize work by claim when litigation has both operating and title issues.|Keep pleadings, engagement letter, itemized invoices, and settlement allocation.|Deducting a title defense as ordinary eviction expense can be improper.
rental-property-uncollectible-rent|Can a landlord deduct unpaid rent that was never received?|A cash-method landlord generally has no bad-debt deduction for rent never included in income; an accrual-method landlord may face a different analysis.|Confirm accounting method and whether the unpaid amount was previously reported as taxable income.|Keep ledger, lease, collection records, and prior return treatment.|Claiming both no rental income and a bad-debt deduction for the same unpaid cash rent double-counts the loss.
rental-property-refinance-cash-out|Is cash-out refinancing of a rental property taxable income?|Loan proceeds normally are not income because they must be repaid; interest deductibility can depend on how the borrowed funds are used.|Trace the cash from refinance proceeds to each use before assigning interest to rental, investment, or personal categories.|Keep closing statement, wire trail, account transfers, and purchase or expense receipts.|Assuming all interest is a rental deduction because the rental secured the loan ignores tracing rules.
rental-property-heloc-interest-tracing|Can rental owners deduct HELOC interest used for property costs?|Interest treatment generally follows the use of borrowed proceeds, not simply the property that secures the debt.|Maintain a separate account or clear tracing ledger for advances spent on the rental and other purposes.|Keep draws, bank transfers, invoices, and loan interest statements.|Mixing personal and rental spending in one revolving line makes the deduction hard to support.
rental-property-loss-sale-to-relative|Can you claim a loss when selling a rental to family?|A loss on a sale to a related person may be disallowed even when the property was genuinely rented and sold for fair value.|Identify the buyer's relationship and model gain or loss before signing the contract.|Keep deed, appraisal, related-party facts, and adjusted-basis schedule.|A fair-market appraisal does not remove statutory related-party loss restrictions.
rental-property-sale-depreciation-allowed|What if you failed to claim rental depreciation before selling?|Gain calculations generally reflect depreciation allowed or allowable, including depreciation that could have been claimed; omitted deductions do not simply disappear at sale.|Reconstruct the asset schedule and ask whether an amended return or accounting-method correction is appropriate.|Keep original returns, placed-in-service evidence, basis records, and sale closing statement.|Using unreduced original cost as sale basis because depreciation was missed understates gain.
rental-property-installment-sale-depreciation|Can depreciation recapture be spread with an installment sale?|Depreciation recapture under Section 1245 and certain Section 1250 rules may be recognized in the year of sale even when sale payments arrive later.|Project the immediate tax cash requirement before agreeing to seller financing.|Keep asset-by-asset depreciation, installment note, allocation schedule, and closing disclosure.|Assuming all tax follows the note payments can create an unexpected first-year bill.
rental-property-selling-costs-gain|Do real-estate commissions reduce taxable gain on a rental sale?|Selling expenses generally reduce amount realized in computing gain or loss, but loan payoff is repayment of debt rather than a selling expense.|Build the sale worksheet from gross price, eligible selling costs, adjusted basis, and debt separately.|Keep settlement statement, broker agreement, and depreciation schedule.|Subtracting mortgage payoff as a tax cost understates taxable gain.
rental-property-rent-concession-tax|How does a free-rent concession affect rental income?|A landlord using the cash method generally reports rent actually received; a negotiated free month does not create cash income, while related expenses still require normal analysis.|Record the concession in the signed lease and reconcile scheduled rent to actual receipts.|Keep the lease amendment, tenant ledger, bank deposits, and marketing offer.|Recording contract rent that was expressly waived can overstate taxable receipts.
"""

BUSINESS = """
business-customer-deposits-tax|Are customer deposits taxable to a small business?|An advance payment can be income when received, while a genuinely refundable deposit held as security may be a liability; method of accounting and contract terms matter.|Separate deposits that will be applied to price from refundable security balances in the ledger.|Keep customer contract, refund terms, invoices, payment dates, and reconciliation.|Calling every advance a deposit cannot defer tax when it is actually payment for services.
business-gift-card-revenue-timing|When does a business recognize gift-card sales for tax?|Gift-card proceeds are advance payments; the available deferral rules depend on accounting method, applicable election, and recognition in financial statements.|Reconcile sales, redemptions, breakage, and refunds before choosing a tax treatment.|Keep card-level liabilities, redemption history, terms, and financial-statement policy.|Leaving unredeemed balances off every tax return indefinitely is not a valid default.
business-refunds-returns-tax|How do customer refunds affect business taxable income?|Refunds, returns, and allowances reduce sales when properly recorded, subject to the business's accounting method and the timing of the original sale.|Reconcile processor chargebacks to invoices so refunded sales are not counted twice.|Keep original receipt, refund authorization, bank evidence, and sales ledger.|Deducting a refund as a separate operating cost while leaving an incorrect gross sale can obscure the books.
business-sales-tax-collected|Is sales tax collected from customers business income?|Sales tax collected as an agent for the state is generally a liability rather than business revenue; taxes imposed directly on the seller can differ.|Read the state rule and reconcile gross processor deposits to net sales and remittances.|Keep taxable-sales report, returns, payment confirmations, and platform withholding statements.|Treating a marketplace's remitted tax as both the seller's income and expense inflates turnover.
business-credit-card-cashback-tax|Is business credit-card cash back taxable?|A rebate tied to purchases often reduces the cost or basis of those purchases rather than being separate taxable income; promotional awards can differ.|Allocate rewards to the underlying expense or asset when material, especially large equipment purchases.|Keep card rewards statement and purchase ledger.|Deducting the full purchase cost and ignoring a substantial rebate overstates cost.
business-barrier-to-cash-method|When must a business use accrual rather than cash accounting?|Accounting-method eligibility depends on entity type, inventory activity, and the applicable gross-receipts tests and exceptions.|Review receipts over the required measurement period before changing methods or filing a new entity return.|Keep prior returns, gross-receipts worksheet, inventory records, and method-election history.|Switching methods in the books without a required tax accounting-method change can create a mismatch.
business-unpaid-invoices-cash-basis|Can a cash-basis business deduct unpaid customer invoices?|A cash-method business generally does not recognize an unpaid invoice as income and therefore generally has no bad-debt deduction when it goes uncollected.|Confirm whether any part was previously reported, such as a deposit or a prior-year receipt.|Keep invoice history, payment record, and tax method documentation.|Deducting an invoice never included in taxable income claims a loss that never arose for tax purposes.
business-bad-debt-accrual-method|When can an accrual-method business deduct a bad debt?|An accrual-method business may deduct a bona fide receivable previously included in income when it becomes worthless, subject to substantiation.|Document collection efforts and the specific year the debt became uncollectible.|Keep original invoice, income recognition, correspondence, bankruptcy notice, and write-off approval.|An accounting allowance for doubtful accounts alone does not establish a tax deduction for a particular debt.
business-inventory-damaged-goods|How are damaged inventory items deducted?|Inventory losses generally affect cost of goods sold or inventory valuation under the taxpayer's adopted method; insurance reimbursements must be accounted for.|Count damaged units, document salvage value, and reconcile the book adjustment to the tax inventory method.|Keep dated count sheets, photographs, disposal evidence, and insurer statement.|Taking an additional expense after inventory already flowed through cost of goods sold double-counts cost.
business-inventory-samples-tax|Can a business deduct products given away as samples?|The cost of samples used to promote sales may be an advertising expense or move through inventory accounting, but must not be deducted twice.|Track units removed from saleable inventory and their business purpose.|Keep campaign records, unit cost, recipient log, and inventory adjustment.|Deducting retail selling price rather than tax cost exaggerates the expense.
business-inventory-owner-withdrawal|How are inventory withdrawals for personal use taxed?|Inventory taken for an owner's personal use is not a business cost of goods sold; the bookkeeping must remove that cost from deductible inventory expense.|Record withdrawals at cost and distinguish gifts to customers from personal consumption.|Keep inventory transfer log and purchase-cost support.|Leaving personal items in cost of goods sold understates business profit.
business-freight-in-inventory-cost|Is shipping paid to acquire inventory immediately deductible?|Freight-in and other acquisition costs often form part of inventory cost and are recovered as the goods are sold, subject to applicable simplified rules.|Separate inbound product freight from shipping goods to customers.|Keep vendor invoices, bills of lading, inventory costing policy, and sales dates.|Expensing all inbound freight immediately may mismatch costs with unsold inventory.
business-website-development-costs|Can a business deduct a newly built website?|Website costs can include currently deductible maintenance, capitalizable development, purchased software, and separately amortizable intangibles; scope determines treatment.|Have the developer separate design, software functions, hosting, and routine updates on invoices.|Keep contract, milestones, launch date, source ownership terms, and invoices.|One website invoice does not prove every component is an advertising expense.
business-domain-name-purchase-tax|Is the purchase of a premium domain name deductible?|A purchased domain can be a capital asset or intangible rather than a routine annual registration fee; the rights and acquisition price matter.|Distinguish recurring registration from buying an existing valuable domain and document how it is used.|Keep purchase contract, registrar transfer, fees, and business-use records.|Immediately expensing a substantial acquired domain may ignore its continuing value.
business-software-subscription-vs-license|How are SaaS subscriptions different from software purchases for tax?|Recurring access fees may be operating expenses, while acquisition of a perpetual license or custom software can require capitalization or different recovery.|Read whether the company receives access, a transferable license, or ownership of developed code.|Keep order form, service term, implementation invoice, and contract rights.|Treating all technology spending as a monthly subscription despite an acquired asset can distort timing.
business-prepaid-insurance-tax|Can a small business deduct prepaid multiyear insurance immediately?|A premium covering future years generally cannot all be deducted when paid; the coverage period and accounting rules control recovery.|Map the policy term and premium to tax years before making a year-end prepayment.|Keep policy declarations, payment receipt, and coverage schedule.|A December payment for several years of coverage is not automatically a December deduction.
business-prepaid-rent-tax|When can a business deduct rent paid in advance?|Prepaid rent generally is allocated to the period it covers, with timing rules that vary by accounting method and benefit period.|Compare the prepayment with the lease term and the applicable economic-performance and 12-month rules.|Keep lease, payment proof, and rent allocation worksheet.|Prepaying multiple years solely to reduce current tax is unlikely to yield a full immediate deduction.
business-lease-security-deposit|Is a commercial lease security deposit deductible?|A refundable lease deposit is generally an asset when paid, not current rent expense; a forfeited or applied deposit is analyzed when its status changes.|Track deposit balances separately from first and last month's rent.|Keep lease, deposit receipt, landlord statement, and termination settlement.|A ledger entry labelled rent does not turn refundable collateral into an expense.
business-tenant-improvement-allowance|How is a landlord's tenant-improvement allowance taxed?|The treatment of a construction allowance depends on lease terms, who owns the improvements, and whether a specific statutory exclusion applies.|Coordinate lease drafting with tax ownership and depreciation before work begins.|Keep executed lease, allowance clause, contractor invoices, ownership terms, and completion certificate.|Netting the allowance against all construction costs without analyzing tax ownership can be wrong.
business-commercial-lease-buyout|Can a business deduct a payment to exit a commercial lease?|A lease termination payment may be deductible or capitalized depending on whether it ends a burden, acquires another right, or is part of a relocation or asset transaction.|Identify precisely what the payment buys and its connection to a new site or business acquisition.|Keep old and new leases, settlement agreement, and itemized legal invoices.|Calling a lump-sum relocation package rent does not resolve its character.
business-trade-show-booth-costs|Are trade-show booth costs deductible?|Event fees and short-lived promotional costs may be operating expenses; a reusable booth structure or equipment can be a depreciable asset.|Separate exhibit space, travel, printed materials, and reusable equipment.|Keep event contract, asset invoices, photos, and future-use plan.|Deducting a durable display as a one-time event fee can accelerate recovery improperly.
business-promotional-giveaways-tax|Can a business deduct promotional giveaways?|Ordinary promotional items can be advertising expense, while gifts to identified recipients can trigger business-gift limits and documentation rules.|Classify mass-distributed branded items separately from valuable items given to particular clients.|Keep item costs, recipients or campaign distribution, and business purpose.|Labelling a personal gift advertising does not avoid substantiation or gift limitations.
business-referral-fees-1099|Are referral fees deductible and reportable?|A bona fide referral payment for business may be deductible, but information-reporting, licensing, and anti-kickback rules can also matter.|Confirm the service, recipient status, and reporting obligation before paying.|Keep agreement, invoice, W-9, payment evidence, and referral result.|Cash or app payments do not eliminate Form 1099 obligations where applicable.
business-contractor-reimbursement-tax|How should contractor expense reimbursements be handled?|Amounts paid to a contractor for expenses can be part of reportable compensation depending on the arrangement; the business still needs ordinary expense substantiation.|Specify whether the contractor buys supplies as agent or includes reimbursed costs in the invoice.|Keep contract, receipts, invoice breakdown, and tax information form.|Excluding every reimbursement from reporting simply because receipts were provided can be incorrect.
business-owner-reimbursement-no-accountable-plan|What happens if an S corporation reimburses owners without an accountable plan?|Without an accountable plan satisfying business connection, substantiation, and return-of-excess requirements, payments may be taxable wages rather than tax-free reimbursement.|Adopt written procedures and reconcile advances to actual expenses promptly.|Keep plan, receipts, mileage or expense logs, reimbursement requests, and payroll records.|A recurring flat allowance with no accounting is not the same as substantiated reimbursement.
business-employee-cell-phone|Can a business pay for an employee's cell phone tax-free?|Employer-provided phones primarily for noncompensatory business reasons can receive favorable fringe-benefit treatment, but cash allowances and personal arrangements need review.|Document why employees need mobile access and distinguish device provision from unrestricted extra pay.|Keep policy, role requirements, invoices, and reimbursement records.|Adding a fixed phone stipend to payroll but treating it as automatically tax-free is risky.
business-employee-home-internet|Can an employer reimburse home internet for remote work?|A substantiated business share of necessary home internet may fit an accountable plan; a blanket payment for a personal household bill needs closer review.|Choose a reasonable allocation and require employees to document the bill and business necessity.|Keep remote-work policy, bill, allocation method, and reimbursement claim.|Paying the full household bill without a business-use rationale can create taxable compensation.
business-employee-meal-overtime|Are overtime meals for employees deductible?|Meal deductions depend on business purpose, who receives the food, location, and statutory limitations; merely working late does not create unlimited tax-free meals.|Record why the employer provided the meal and apply the correct deduction and fringe-benefit rules.|Keep receipts, attendance, work schedule, and written policy.|Treating every team dinner as a fully deductible de minimis benefit ignores limitations.
business-team-event-meals|Are meals at a company-wide employee event fully deductible?|Recreational events primarily for employees may receive different deduction treatment from ordinary business meals when they satisfy the statutory requirements.|Document who attended and whether the event was primarily for rank-and-file employees rather than owners alone.|Keep invitation, attendee list, invoices, and event purpose.|An owner-only dinner cannot be reclassified as an employee recreation event by its label.
business-client-gift-vs-entertainment|Is a client experience a gift or entertainment expense?|The tax treatment of a tangible gift differs from entertainment, and separating food from event admission requires adequate billing.|Ask vendors to itemize meals separately and identify what the client actually received.|Keep invoice detail, recipient, business relationship, and event records.|Calling tickets a client gift does not convert nondeductible entertainment into a deductible gift.
business-sponsorship-vs-charity|Is a local sponsorship an advertising deduction or donation?|A payment for meaningful advertising can be a business promotion cost, while an amount paid without substantial return benefit may be a charitable contribution.|Document signage, audience, deliverables, and fair value received from the organization.|Keep sponsorship agreement, photographs, receipt, and event materials.|Assuming every nonprofit payment is a charitable gift can miss the actual advertising exchange.
business-charity-through-s-corp|How do S corporation charitable gifts reach shareholders?|An S corporation generally separately states eligible charitable contributions to shareholders, whose individual deductions can be limited by basis and personal rules.|Model owner basis and itemization before using corporate cash for a large gift.|Keep acknowledgment, Form 1120-S K-1, basis schedule, and valuation support.|Treating the gift as an ordinary business expense on the S corporation return is usually wrong.
business-business-loan-proceeds-tax|Is a bank loan taxable income for a business?|Ordinary loan proceeds are generally not taxable because the borrower has a repayment obligation; interest and financing fees receive separate treatment.|Record principal as a liability and trace borrowed funds to business or personal use.|Keep note, draw schedule, bank deposits, and use-of-funds ledger.|Booking proceeds as sales revenue and loan repayments as expenses distorts taxable profit.
business-forgiven-loan-tax|Is forgiven business debt taxable?|Cancelled debt can create income unless an exclusion or other special rule applies; the tax effect can also adjust attributes such as basis or losses.|Identify the creditor, amount discharged, insolvency status, and whether the obligation was genuinely cancelled.|Keep discharge agreement, Form 1099-C, balance sheet, and tax-attribute worksheet.|Assuming every forgiven loan is tax-free because the original proceeds were untaxed is incorrect.
business-interest-personal-guarantee|Can an owner deduct interest on a personally guaranteed business loan?|A guarantee alone does not make interest the owner's deduction; who is the borrower, who pays, and how proceeds are used all matter.|Document intercompany advances or capital contributions if the owner pays an entity obligation.|Keep note, guarantee, bank transfers, board approval, and loan tracing.|Paying the entity's bill personally without accounting for the transaction can obscure basis and deductions.
business-intercompany-loan-documentation|What records make an owner-to-business loan bona fide?|A genuine loan needs a real obligation to repay, credible terms, payment history, and consistent accounting; otherwise advances may be treated as equity or distributions.|Set interest, maturity, and repayment terms when funds move rather than after an audit begins.|Keep signed note, bank transfers, payment ledger, and corporate approvals.|A year-end journal entry called loan cannot substitute for an actual debtor-creditor relationship.
business-owner-loan-repayment-tax|Is repayment of an owner's loan from an S corporation taxable?|Return of bona fide principal is generally not income, while stated or imputed interest is income to the lender; debt basis and prior losses can complicate repayment.|Reconcile principal, accrued interest, and any debt basis reduced by prior deductions before issuing payment.|Keep original note, loan roll-forward, shareholder basis schedule, and payment detail.|Calling a distribution loan repayment after the fact can misstate both income and basis.
business-s-corp-distribution-basis|When are S corporation distributions taxable?|Nondividend S corporation distributions are generally tax-free only to the extent of stock basis, with excess potentially treated as gain; accumulated earnings can change ordering.|Update shareholder stock basis before deciding the amount of a year-end distribution.|Keep Forms 1120-S and K-1, contributions, prior losses, and distribution ledger.|Bank balance is not shareholder tax basis.
business-s-corp-loss-debt-basis|Can an S corporation owner use losses against a personal loan guarantee?|A guarantee alone generally does not create debt basis for an S corporation shareholder; an actual economic outlay or direct indebtedness is relevant.|Calculate stock basis, debt basis, at-risk amount, and passive limits in the correct order.|Keep lender documents, shareholder advances, repayments, and basis worksheet.|Claiming a pass-through loss solely because the owner signed a guarantee can overstate the deduction.
business-s-corp-shareholder-health-insurance|How is health insurance for a more-than-2-percent S corporation shareholder reported?|Premiums paid or reimbursed by the S corporation generally need proper W-2 inclusion for a more-than-2-percent shareholder before a potential above-the-line deduction is evaluated.|Coordinate payroll and plan ownership before the final payroll of the year.|Keep policy, payment evidence, W-2, and payroll entries.|Paying premiums from the company account without correct wage reporting can jeopardize the individual deduction.
business-partnership-guaranteed-payment|What is a partnership guaranteed payment for services?|A guaranteed payment is made to a partner without regard to partnership income and is generally separately reported, unlike a distributive profit share.|Draft the operating agreement to distinguish fixed service compensation from profit allocations.|Keep agreement, payment ledger, Form 1065, and each partner's K-1.|Putting a partner on ordinary employee payroll can conflict with partnership tax treatment.
business-partner-expenses-unreimbursed|Can a partner deduct expenses paid personally for a partnership?|An unreimbursed partnership expense may be deductible by a partner when the partnership agreement requires the partner to bear it and reimbursement is unavailable.|Put the expense obligation in the agreement and check whether the partnership actually offers reimbursement.|Keep signed agreement, receipts, reimbursement policy, and K-1.|Voluntarily paying an expense personally does not automatically create a partner-level deduction.
business-partnership-distribution-property|Is a partnership distribution of equipment taxable?|A property distribution is often not immediately taxable, but special rules, partner basis, liabilities, and disguised-sale provisions can change the result.|Model both the partner's outside basis and the partnership's asset basis before transferring equipment.|Keep asset ledger, fair-value support, liabilities, agreement, and basis roll-forward.|Treating a property distribution exactly like a cash draw ignores basis and asset character.
business-partnership-buyout-ordinary-income|Why is part of a partnership buyout ordinary income?|A partner's sale can produce ordinary income to the extent attributable to certain unrealized receivables or inventory, often called hot assets, even if the rest is capital gain.|Obtain an asset-level allocation and estimate Section 751 exposure before setting a headline price.|Keep valuation, receivables detail, inventory, purchase agreement, and partner basis.|Calling the entire buyout capital gain can understate ordinary income.
business-purchase-price-allocation-assets|How do buyers and sellers allocate a business purchase price?|An applicable asset acquisition generally requires allocation among asset classes, affecting buyer deductions and seller gain character.|Negotiate allocation alongside price and coordinate consistent reporting by both parties.|Keep purchase agreement, valuation, allocation workpapers, and Form 8594.|Agreeing on price while leaving allocation vague can create conflicting returns.
business-acquired-customer-list|Can a buyer deduct the cost of an acquired customer list?|A purchased customer-based intangible in a business acquisition may be subject to Section 197 amortization rather than an immediate advertising deduction.|Identify whether the list was separately purchased or part of a broader business acquisition.|Keep acquisition agreement, allocation, valuation, and rights transferred.|Expensing a durable acquired customer relationship at closing can accelerate tax recovery incorrectly.
business-sale-escrow-holdback|When is an escrow holdback from a business sale taxed?|An escrowed portion of sale proceeds can have different timing depending on whether the seller has a fixed right to funds and the escrow conditions.|Read the escrow restrictions and model each earnout, indemnity, or price-adjustment condition separately.|Keep sale agreement, escrow contract, release notices, and closing statement.|Assuming all cash withheld from the seller is automatically deferred taxable gain can be wrong.
business-sale-working-capital-adjustment|How does a working-capital true-up affect business sale tax?|A purchase-price adjustment can change amount realized or asset allocation; its character depends on the agreement and facts.|Reconcile the closing balance sheet, post-closing true-up, and any separately paid compensation.|Keep purchase agreement, target calculation, final settlement, and amended allocation.|Booking a price adjustment as ordinary consulting revenue without reviewing the contract can misclassify it.
business-sale-noncompete-payment|How are noncompete payments in a business sale taxed?|A separately bargained covenant can produce different tax character for the seller and amortization treatment for the buyer than goodwill does.|Value the covenant realistically and coordinate its allocation with the transaction documents.|Keep covenant, negotiation record, valuation, and Form 8594.|A label inserted solely for tax results is vulnerable if the covenant has no economic substance.
business-asset-sale-sales-tax|Does sales tax apply when a business sells its equipment?|State sales-tax treatment of a business asset sale varies by jurisdiction and transaction type, while federal gain is computed from proceeds and adjusted tax basis.|Check the applicable state exemption or bulk-sale rules before closing and separately calculate federal gain or loss.|Keep bill of sale, original purchase invoice, depreciation schedule, and state tax determination.|Assuming an isolated equipment sale has no state sales-tax consequence can surprise buyer and seller.
"""

SOURCES = {
    "real": ("IRS Publication 527: Residential Rental Property", "https://www.irs.gov/publications/p527"),
    "passive": ("IRS Publication 925: Passive Activity and At-Risk Rules", "https://www.irs.gov/publications/p925"),
    "depreciation": ("IRS Publication 946: How To Depreciate Property", "https://www.irs.gov/publications/p946"),
    "business": ("IRS Publication 334: Tax Guide for Small Business", "https://www.irs.gov/publications/p334"),
    "partnership": ("IRS Publication 541: Partnerships", "https://www.irs.gov/publications/p541"),
    "sale": ("IRS Publication 544: Sales and Other Dispositions of Assets", "https://www.irs.gov/publications/p544"),
}


def parse(block: str) -> list[tuple[str, ...]]:
    rows = [tuple(x.strip() for x in line.split("|")) for line in block.strip().splitlines()]
    assert all(len(row) == 6 for row in rows), "Every entry needs six fields"
    return rows


def source_for(slug: str, real: bool) -> tuple[str, str]:
    if any(w in slug for w in ("partnership", "partner-")):
        return SOURCES["partnership"]
    if any(w in slug for w in ("sale-", "selling-", "buyout", "forgiven", "condemnation")):
        return SOURCES["sale"]
    if any(w in slug for w in ("depreciation", "basis", "improvement", "appliance", "fence", "driveway")):
        return SOURCES["depreciation"]
    if any(w in slug for w in ("loss", "participation", "short-stay", "manager")):
        return SOURCES["passive"]
    return SOURCES["real" if real else "business"]


def make_post(row: tuple[str, ...], real: bool) -> dict:
    slug, title, answer, decision, evidence, mistake = row
    topic = title.rstrip("?")
    category = "Real Estate Tax" if real else "Business Tax"
    hub = ("/real-estate-tax-planning/", "Real estate tax planning") if real else ("/business-owner-small-business-tax/", "Business tax planning")
    source_name, source_url = source_for(slug, real)
    esc = html.escape
    related = [hub, ("/blog/", "All tax strategy articles")]
    if real:
        related.append(("/cost-segregation-studies-for-real-estate-investors/", "Depreciation and cost segregation"))
    else:
        related.append(("/business-owner-tax-planning/", "Business owner tax strategy"))
    body = f"""
        <h2>The tax treatment</h2>
        <p>{esc(answer)} This is a federal income tax starting point; the contract, ownership, accounting method, and actual use can change the result. State and local treatment should be checked separately.</p>

        <h2>The decision to make before filing</h2>
        <p>{esc(decision)} The useful planning step is to resolve the classification while the underlying documents are still available, then reconcile it to the books and the prior-year return. If the transaction spans more than one year, track the opening balance and what happened to it afterward.</p>

        <h2>Records that support the position</h2>
        <p>{esc(evidence)} Tie amounts on the return to bank activity and the agreement. When several assets, people, or uses are involved, write down the allocation method and apply it consistently. A short dated workpaper is easier to defend than a reconstructed explanation years later.</p>

        <h2>A common reporting error</h2>
        <p>{esc(mistake)} Review both sides of the entry: a payment can affect income, basis, liability, or an expense at different times. A correct cash total alone does not establish the correct tax character.</p>

        <h2>Where to verify the rule</h2>
        <p>Start with <a href="{source_url}" rel="noopener">{esc(source_name)}</a>. Its examples and cross-references explain the underlying federal rule; check the current version and any later IRS guidance for the year at issue. For a coordinated review of related deductions and limitations, see <a href="{hub[0]}">{esc(hub[1])}</a>.</p>
    """
    return {
        "slug": slug, "title": topic, "h1": title,
        "title_tag": f"{topic} | AE Tax Advisors",
        "breadcrumb": topic, "category": category,
        "description": (answer[:152].rsplit(" ", 1)[0].rstrip(";,. ") + ".") if len(answer) > 155 else answer,
        "date": "2026-09-22", "date_display": "September 22, 2026",
        "lead": f"<strong>{esc(answer)}</strong>",
        "body": re.sub(r"(?m)^[ \t]+$", "", body),
        "faqs": [(title, answer), ("What should I document?", evidence)],
        "related": related,
        "cta_head": f"Need to classify this {('rental' if real else 'business')} transaction?",
        "cta_text": "AE Tax Advisors can review the documents, reporting history, and the decision before filing.",
    }


def main() -> None:
    real, business = parse(REAL_ESTATE), parse(BUSINESS)
    assert len(real) == len(business) == 50, (len(real), len(business))
    assert len({r[0] for r in real + business}) == 100
    manifest = Path("long_tail_100_slugs.txt")
    slugs = {r[0] for r in real + business}
    prior = set(manifest.read_text().splitlines()) if manifest.exists() else set()
    assert not prior or prior == slugs, "Manifest does not match the current page inventory"
    for row, is_real in [(r, True) for r in real] + [(r, False) for r in business]:
        assert re.fullmatch(r"[a-z0-9-]+", row[0])
        target = Path("blog") / row[0] / "index.html"
        assert not target.exists() or row[0] in prior, f"Existing page collision: {target}"
        seo_render.write_post(make_post(row, is_real))
    manifest.write_text("\n".join(sorted(slugs)) + "\n")
    # Keep prior lastmod dates untouched: these are the only URLs changed today.
    for sitemap in (Path("sitemap.xml"), Path("sitemap-blog.xml")):
        xml = sitemap.read_text()
        additions = []
        for slug, *_ in real + business:
            url = f"https://www.aetaxadvisors.com/blog/{slug}/"
            if url not in xml:
                additions.append(
                    f"  <url><loc>{url}</loc><lastmod>2026-09-22</lastmod>"
                    "<changefreq>monthly</changefreq><priority>0.6</priority></url>"
                )
        assert len(additions) in (0, 100), (sitemap, len(additions))
        if additions:
            sitemap.write_text(xml.replace("</urlset>", "\n".join(additions) + "\n</urlset>"))
    index = Path("sitemap-index.xml")
    index.write_text(index.read_text().replace(
        "sitemap-blog.xml</loc><lastmod>2026-09-18",
        "sitemap-blog.xml</loc><lastmod>2026-09-22",
    ))
    print("Built 100 new pages: 50 real estate and 50 business tax")


if __name__ == "__main__":
    main()
