"""Publish 25 distinct owner FAQs, with source-linked answers and self-canonical URLs."""
import json, html, re, xml.etree.ElementTree as ET
from pathlib import Path
import site_template as T
ROOT=Path(__file__).resolve().parent
DATE='2026-09-30'
S={k:'https://www.irs.gov/'+v for k,v in {
'expenses':'publications/p463','home':'publications/p587','passive':'publications/p925','rental':'publications/p527','depreciation':'publications/p946','basis':'publications/p551','sale':'publications/p544','method':'instructions/i3115','salary':'businesses/small-businesses-self-employed/s-corporation-compensation-and-medical-insurance-issues','solo':'retirement-plans/one-participant-401k-plans','distribution':'retirement-plans/retirement-plan-faqs-regarding-contributions-s-corporation','pension':'retirement-plans/defined-benefit-plan','repairs':'businesses/small-businesses-self-employed/tangible-property-final-regulations'}.items()}
P=[]
def add(slug,title,cluster,answer,explanation,example,records,q,a,source,hub):
 P.append(dict(slug=slug,title=title,cluster=cluster,answer=answer,explanation=explanation,example=example,records=records,q=q,a=a,source=source,hub=hub))
add('s-corp-personal-credit-card-reimbursement','Can My S Corp Reimburse Business Purchases on My Personal Credit Card?','Owner reimbursements',
'Yes, a qualifying business expense paid personally can be reimbursed through an accountable arrangement. The card’s name does not decide deductibility. Business connection, substantiation and the return of excess advances are the key requirements.',
'Keep the purchase separate from the payment of the credit-card bill. A bill may contain both business and personal charges, so reimbursing the full statement balance can create a problem. The expense report should identify each item, its business purpose and the amount attributable to the corporation. A reimbursement must also be recorded once: the corporation should not deduct the receipt and the reimbursement as two separate expenses. A recurring monthly review helps the bookkeeper reconcile owner-paid costs without moving personal spending into the company’s profit and loss statement. Confirm the timing and accounting treatment before reimbursing old charges.',
'An owner buys a $240 business software subscription and $160 of personal groceries on one card. Subject to the reimbursement rules and the software’s tax treatment, the expense report identifies the $240 business charge. The company does not reimburse the groceries merely because both purchases appear on the same statement.',
'Itemized receipt; personal-card statement; business purpose; expense report; reimbursement transfer; ledger entry.',
'Does paying the personal card directly replace an expense report?',
'No. Paying a card balance does not establish which items were business expenses. Support the qualifying charges and keep the personal portion outside the reimbursement.', ['expenses'],'/accountable-plan/')
add('accountable-plan-missing-receipts','What If I Lost a Receipt for an S Corp Accountable Plan Reimbursement?','Owner reimbursements',
'A missing receipt should trigger a documentation review, not an automatic reimbursement or an automatic denial. The evidence needed depends on the expense and applicable substantiation rules; a bank charge alone may not explain what was purchased or why.',
'Ask the vendor for a duplicate invoice first. Combine any available transaction record with a dated explanation of the business purpose, attendees where relevant and the expense category. Travel, meals, gifts and vehicle costs have specific recordkeeping requirements, and certain expenses require documentary evidence. Do not assume that a small-dollar transaction is exempt from every documentation requirement. The company should distinguish a reconstructed record from an original receipt and have the claim reviewed under its policy. If an item cannot be adequately supported, decide how to treat the payment rather than describing unsupported amounts as tax-free reimbursements.',
'An owner’s card shows a restaurant charge, but the receipt is missing. A reconstructed file identifies the client meeting and participants and requests an itemized receipt from the restaurant. The charge is evaluated under the meal and reimbursement rules, rather than deducted simply because it occurred during the workweek.',
'Duplicate invoice request; transaction date; amount; merchant; business purpose; participants; written approval.',
'Is a credit-card statement enough for every reimbursement?',
'No. It may establish payment, but it does not always establish the nature or business purpose of the expense. Specific substantiation requirements still apply.', ['expenses'],'/accountable-plan/')
add('accountable-plan-reimbursement-after-60-days','Can an Accountable Plan Reimburse Expenses More Than 60 Days Later?','Owner reimbursements',
'Possibly, but the facts matter. IRS guidance treats substantiation within 60 days as a reasonable-period safe harbor. Missing that period does not turn every later claim into an automatic tax-free reimbursement.',
'The reimbursement arrangement must require timely accounting for business expenses and repayment of excess advances. Outside the safe-harbor timing, reasonableness depends on the surrounding facts. A year-end transfer labeled “accountable plan” does not cure an unsupported claim. Identify when the expense was incurred, when records were submitted, why the delay occurred and what the company’s policy required. Delayed claims from a prior tax year may also raise separate questions about payroll, deduction timing and previously filed returns. Review those issues before moving cash or editing the books. A practical monthly submission schedule is easier to support than a large retroactive reconstruction.',
'An owner submits a travel expense report several months after the trip because records were delayed. The reviewer considers the explanation, receipts and the policy’s timing requirements. The company does not assume the 60-day safe harbor still applies, and does not conclude that the delay alone proves every expense is nondeductible.',
'Expense date; submission date; delay explanation; reimbursement policy; substantiation; prior payroll and return treatment.',
'Can I backdate the policy to make old reimbursements compliant?',
'Backdating does not establish the historical facts. Review the arrangement actually in effect, supportable expenses and the correct tax treatment of any prior payments.', ['expenses'],'/accountable-plan/')
add('s-corp-phone-internet-business-percentage','How Much of My Personal Phone and Internet Can My S Corp Reimburse?','Owner reimbursements',
'Reimburse a supportable business portion under the company’s policy and the applicable expense rules. A personal subscription used partly for work is not automatically a 100% business expense.',
'Identify who uses each service and how the business benefits. The evidence for a dedicated business connection may differ from a family plan serving several people. Keep billing statements, document the allocation method and apply it consistently. Revisit the percentage when work habits or household users change. A simple written explanation is useful, but an arbitrary percentage chosen to achieve a tax deduction is not a substitute for facts. Employer-provided cell phones and reimbursements can involve special rules, so the treatment should match the arrangement. Coordinate these reimbursements with any office-expense calculation to prevent deducting the same internet cost twice.',
'An owner works from home and uses one internet connection for business meetings and family streaming. The expense report applies a reasonable business allocation supported by usage and the work arrangement. The household’s total bill is not treated as a business cost simply because a company meeting occurred online.',
'Bills; users; business needs; allocation method; policy approval; check for duplicate home-office expense entries.',
'Should I claim the same internet expense through two reimbursement categories?',
'No. Different categories do not create two deductions for one cost. Reconcile reimbursements to the underlying bill and total eligible business amount.', ['expenses','home'],'/accountable-plan/')
add('s-corp-home-office-simplified-method-reimbursement','Can an S Corp Reimburse the Simplified Home Office Deduction?','Owner reimbursements',
'Do not assume the individual simplified home-office calculation is a ready-made corporate reimbursement amount. The corporation’s reimbursement must be evaluated under the accountable arrangement and qualifying expense rules.',
'The simplified method described for an individual business deduction and the reimbursement of a shareholder-employee are different reporting questions. First determine whether the space qualifies, then identify the expenses the company may reimburse and how the amount is calculated. Ownership of an S corporation does not convert every household cost into a company expense. Records should support the office’s size, qualifying use and allocation of actual costs where applicable. The shareholder’s personal deductions also need coordination so the same cost is not counted twice. Ask the preparer to explain the calculation and where it appears in both the corporation’s books and the owner’s return.',
'An owner has a qualifying 150-square-foot office and asks the company to reimburse a flat amount based only on square footage. The advisor reviews the corporate arrangement and actual eligible costs before approving a payment. The simplified individual method is not used as proof that the transfer is a tax-free employee reimbursement.',
'Floor plan; office measurements; use description; household invoices; allocation worksheet; reimbursement policy.',
'Does owning the corporation mean I file a Schedule C home-office deduction?',
'No. A shareholder’s role as an employee of the corporation requires different reporting from a sole proprietor. Coordinate the corporation’s reimbursement with the owner’s personal return.', ['home','expenses'],'/accountable-plan/')
add('home-office-dining-room-exclusive-use','Does a Dining Room Used for Work Qualify as a Home Office?','Owner reimbursements',
'Ordinary home-office qualification generally requires regular and exclusive business use, subject to specific exceptions. A dining table routinely used for family meals normally fails the exclusive-use requirement.',
'The question is how the area is actually used, not what the room is called. A clearly identifiable portion of a room may qualify if its use meets the rules, while a beautifully furnished room may fail if it serves personal purposes. Document the boundaries, business activity and regularity of use. Storage and daycare exceptions have their own conditions and should not be assumed for an office-based business. For a shareholder-employee, a qualifying space is only one part of the analysis: the reimbursement arrangement and eligible costs must also be reviewed. Changing household use prospectively is different from claiming that past mixed use never occurred.',
'An owner uses the dining table for emails during the day and family dinners each evening. That pattern is not exclusive business use. A separately identifiable workstation used only for qualifying business activity may produce a different result, but the facts and the applicable home-office conditions must support it.',
'Photographs; measurements; activities conducted; personal-use history; recurring schedule; expense allocation.',
'Can a room have both a qualifying area and a personal area?',
'Potentially. A separate room is not always required, but the claimed business area must satisfy the applicable tests. Identify and measure the area rather than claiming the entire mixed-use room.', ['home'],'/accountable-plan/')
add('part-time-s-corp-owner-reasonable-salary','How Do I Set a Reasonable S Corp Salary When I Work Part Time?','S corporation owner pay',
'Part-time hours can affect reasonable compensation, but they do not remove the wage requirement for services an owner performs. Evaluate duties, time, experience and comparable pay rather than using distributions as a substitute for wages.',
'The IRS considers factors such as training, responsibilities, time devoted to the business and what comparable businesses pay for similar services. Document the owner’s actual roles, including management, sales and client delivery. An owner who delegates operations may perform fewer hours, but the remaining work can still be valuable. Compare a realistic job description and work schedule with appropriate compensation data. Also separate revenue attributable to the owner’s services from revenue attributable to staff, capital or equipment. Review the analysis as responsibilities change, and coordinate payroll with retirement contributions and other parts of the tax plan.',
'An owner works 15 hours weekly overseeing staff and handling key sales. A salary analysis describes those responsibilities and evaluates comparable compensation for that level of work. The owner’s separate full-time job does not, by itself, justify taking all S corporation cash as distributions.',
'Role description; hours; comparable wage evidence; delegation records; payroll history; distribution schedule.',
'Can my salary be zero because I have another employer?',
'Another employer does not eliminate compensation for services performed for your S corporation. Assess the work and the compensation required for that corporation separately.', ['salary'],'/services/reasonable-compensation/')
add('s-corp-60-40-salary-rule','Does the IRS Require a 60/40 Salary Split for S Corp Owners?','S corporation owner pay',
'No universal IRS 60/40 salary-to-distribution safe harbor applies to every S corporation owner. Reasonable compensation depends on the services performed and the business facts.',
'An easy percentage can be a starting estimate for budgeting, but it cannot replace a compensation analysis. Two companies with identical profit may require different salaries if one relies on the owner’s personal services and the other relies on employees or substantial equipment. The work, market pay and sources of revenue matter. Review the calculation with the payroll provider before changing wages, especially where retirement contributions depend on compensation. Distributions also have their own basis and tax reporting considerations. Calling a transfer a distribution does not resolve whether it should have been wages. Keep a dated compensation file rather than relying only on an online ratio.',
'Two owners each have $300,000 of company profit. One personally delivers nearly all client services; the other manages a staffed business a few hours per week. The same 60/40 split is not proof of reasonable pay for both owners. Each company needs an analysis of the services actually performed.',
'Comparable compensation; owner duties; hours; employee roles; profit sources; written annual review.',
'Can a salary percentage be used as an IRS safe harbor?',
'A percentage alone is not a general reasonable-compensation safe harbor. Support the wage amount with facts about the owner’s services and comparable compensation.', ['salary'],'/services/reasonable-compensation/')
add('s-corp-health-insurance-spouse-employer-plan','Can I Deduct S Corp Health Insurance If My Spouse Has Employer Coverage?','S corporation owner pay',
'Eligibility for a subsidized health plan maintained by your employer or your spouse’s employer can restrict the self-employed health-insurance deduction. Choosing not to enroll does not necessarily preserve the deduction.',
'For a more-than-2% shareholder, the S corporation payment or reimbursement and W-2 reporting must also be handled correctly. These reporting steps and the eligibility restriction answer separate questions. Review which months employer-sponsored coverage was available and which premiums were paid under the corporation’s arrangement. A change in employment during the year can make a month-by-month review important. Keep the benefits eligibility documents rather than relying on whether an insurance card was ever issued. The corporation’s treatment of premiums, the shareholder’s deduction and payroll reporting should be reconciled before filing. Do not treat every medical expense as equivalent to an insurance premium.',
'An owner purchases individual coverage while the spouse’s employer offers eligible subsidized family coverage. The advisor checks the eligibility rules before claiming the shareholder’s deduction. The owner’s decision to buy a preferred policy does not establish that the statutory restriction is inapplicable.',
'Benefit eligibility dates; policy premiums; corporate payments; reimbursements; W-2; ownership percentage.',
'Does declining my spouse’s available plan automatically make premiums deductible?',
'No. Eligibility, rather than enrollment alone, is relevant to the restriction. Review the applicable months and benefit arrangement before claiming the deduction.', ['salary'],'/business-owner-small-business-tax/')
add('s-corp-distributions-solo-401k-contributions','Can S Corp Distributions Count Toward Solo 401(k) Contributions?','Owner retirement planning',
'No. S corporation distributions do not count as earned income for retirement-plan contribution purposes. Contributions for a shareholder-employee are based on qualifying compensation, subject to plan and annual limits.',
'A large distribution can reflect substantial business profit without increasing the compensation used for the owner’s retirement contribution. Separate employee deferrals from employer contributions and review the plan’s definition of compensation. Payroll and the retirement administrator’s calculations should agree. Reasonable compensation still must be supported independently; changing wages solely to reach a desired contribution does not resolve that requirement. If the owner also participates in another employer’s retirement plan, coordinate applicable individual deferral limits and other rules. Use the limits for the actual contribution year rather than a number copied from a prior-year worksheet. Resolve excess contributions promptly with the administrator.',
'An owner receives $80,000 of W-2 compensation and $220,000 of S corporation distributions. The retirement contribution calculation does not treat all $300,000 as compensation. The plan administrator applies the employee and employer rules to qualifying pay and the relevant annual limits.',
'W-2; payroll reports; plan document; ownership data; contributions to other plans; administrator calculation.',
'Can I relabel a distribution after filing to increase the contribution limit?',
'Relabeling a bank transfer is not enough. Any payroll correction, tax reporting and contribution change must be evaluated under the applicable rules and deadlines.', ['distribution','solo'],'/retirement-exit-ma-tax-strategy/')
add('solo-401k-first-eligible-employee','What Happens to a Solo 401(k) When I Hire My First Employee?','Owner retirement planning',
'Hiring requires a plan-eligibility review. A one-participant 401(k) generally covers an owner with no employees, or the owner and spouse; when an employee becomes eligible, the plan’s obligations can change.',
'Do not assume that every new hire enters the plan immediately or that labeling someone part time avoids coverage. Eligibility can depend on age, service, hours and the plan document, including applicable long-term part-time rules. The employer should provide the administrator with a complete census, hiring dates and service records. Review related businesses and ownership relationships where relevant rather than considering only the entity that pays the owner. A plan that must cover eligible employees may require additional administration and testing. Decide how to transition before the eligibility date, and coordinate notices and contributions with the administrator. Keeping the old “solo” label does not override coverage requirements.',
'An owner hires an assistant and continues the existing owner-only plan. The administrator checks the assistant’s age, hours, service and the plan’s terms. The employer does not wait until year-end to ask whether coverage should already have begun.',
'Employee census; birth dates; hire dates; hours; related-entity ownership; plan document; eligibility calculations.',
'Does hiring my spouse always end owner-only plan treatment?',
'An owner-and-spouse plan can still be a one-participant arrangement under IRS guidance. Other eligible employees and the full plan facts require a separate review.', ['solo'],'/retirement-exit-ma-tax-strategy/')
add('cash-balance-plan-variable-business-income','Is a Cash Balance Plan Suitable If My Business Income Fluctuates?','Owner retirement planning',
'It may be suitable, but funding obligations need to fit the business’s cash flow. A cash balance plan is a defined benefit arrangement with actuarial requirements, not a flexible account into which any desired deduction can be deposited.',
'Model several years of profit, payroll and liquidity before establishing the plan. Contribution levels depend on the plan formula, compensation, participant demographics and actuarial assumptions. Investment results can affect funding needs. A strong year does not establish that the business can sustain contributions through weaker periods. Ask the enrolled actuary and administrator for projected funding ranges, employee costs, fees and the consequences of reduced profit. Review alternatives or combinations with defined contribution plans where appropriate. Plan amendments, freezes and termination are governed by rules and timing requirements; they are not an unrestricted way to erase an obligation after a downturn.',
'A business expects $600,000 profit this year but has historically ranged from $200,000 to $700,000. The planning team models lower-profit years before recommending a cash balance plan. A proposed current deduction is considered alongside future funding capacity and employee benefits.',
'Multiyear profit forecast; employee census; compensation; existing plans; actuarial illustration; liquidity reserve.',
'Can I choose the same $200,000 contribution every year?',
'Not simply by preference. Obtain annual actuarial funding and deduction calculations. The permissible contribution depends on the plan and current facts.', ['pension'],'/retirement-exit-ma-tax-strategy/')
add('str-material-participation-exactly-100-hours','Is Exactly 100 Hours Enough for STR Material Participation?','Short-term rental participation',
'Not for the commonly cited more-than-100-hours test. That test requires more than 100 hours and participation at least as much as any other individual. Other material-participation tests may apply depending on the facts.',
'First classify the activity under the rental exceptions. A short booking history alone does not establish the full tax result. Then identify the particular material-participation test and the work that can count. Track time by activity and property, distinguish owner work from investor monitoring and retain evidence of other individuals’ involvement. Meeting a participation test does not eliminate basis, at-risk or other loss limitations. A projection that uses a large depreciation loss should identify each of these steps. Avoid rounding 99 or 100 hours upward to meet a threshold. The actual work and records must support the claimed position.',
'An owner records exactly 100 qualifying hours while a cleaner records 80. Those figures do not satisfy the more-than-100-hours test. The preparer evaluates whether another test applies rather than treating the owner’s rounded total as enough.',
'Dated task log; booking history; average stays; cleaner and manager hours; work descriptions; loss-limit review.',
'Is working more than the cleaner the only requirement?',
'No. The more-than-100-hours test requires both its hour threshold and the comparison with every other individual. Activity classification and other tax limitations still matter.', ['passive'],'/short-term-rental-tax-strategy/')
add('str-spouse-hours-married-filing-separately','Do My Spouse’s STR Hours Count If We File Separate Returns?','Short-term rental participation',
'For material-participation purposes, IRS guidance includes a spouse’s participation even when the spouse has no ownership interest and the spouses do not file a joint return. Other rules can make the filing-status analysis different.',
'Combine only qualifying participation in the relevant activity and maintain records identifying each spouse’s work. Do not confuse this rule with real estate professional qualification: the latter has its own personal-service requirements and joint-return rules. Married filing separately can also affect other deductions, credits and rental-loss allowances. The ability to count spouse participation therefore does not establish that separate filing produces a usable loss or a better overall tax result. Ask the preparer to show the complete return comparison. Logs should distinguish management and operating tasks from investment review, and should preserve each spouse’s dates and actual time.',
'One spouse performs guest communication and the other coordinates repairs for the same qualifying activity. They retain separate task logs even though the preparer evaluates combined participation for the material-participation test. The filing-status decision is reviewed separately.',
'Each spouse’s task log; ownership; filing status; activity classification; other workers’ participation; full-return comparison.',
'Can spouse hours automatically satisfy the real estate professional tests?',
'No. Spousal participation for material participation and the individual requirements for real estate professional status are different analyses. Do not transfer one rule to the other.', ['passive'],'/short-term-rental-tax-strategy/')
add('str-cleaner-more-hours-than-owner','Can I Use the STR 100-Hour Test If My Cleaner Works More Hours?','Short-term rental participation',
'If another individual works more qualifying hours than you, the more-than-100-hours comparison test is not satisfied on those facts. More than 100 owner hours by itself does not meet both parts of that test.',
'Compare individuals, rather than treating a management company’s entire staff as one person without analysis. Obtain records showing who performed the work and for how long. The comparison can involve cleaners, managers, co-hosts and others, not only owners. Another material-participation test may be available, but it must be evaluated on its own terms. Do not inflate owner hours or ignore outsourced work to rescue a preferred result. Before ordering a study based on a projected nonpassive loss, analyze activity classification and participation using realistic records. A cost segregation study changes depreciation classification; it does not fix insufficient participation.',
'An owner has 140 qualifying hours and one cleaner has 180. The owner does not pass the more-than-100-hours comparison test using those figures. If the property has two cleaners with different hours, each person’s involvement is evaluated instead of assuming an unsupported total.',
'Individual worker logs; invoices; management agreement; owner and spouse records; activity grouping history.',
'Does using any cleaner automatically make the activity passive?',
'No. Outsourcing does not itself decide the result. Apply the available material-participation tests to the actual participation and the activity’s classification.', ['passive'],'/short-term-rental-tax-strategy/')
add('str-property-research-material-participation-hours','Do Property Research and Investment Review Count as STR Participation?','Short-term rental participation',
'Investor-type work generally does not count as participation unless it is directly connected to day-to-day management or operations. Studying returns and monitoring financial performance should not automatically be included in an operating-hour total.',
'Label tasks according to what actually happened. Reviewing a statement as an investor differs from managing a guest problem or coordinating work necessary to operate the property. The IRS identifies investment review and nonmanagerial financial monitoring as examples that generally do not count. Pre-acquisition education or broad market research also should not be assumed to support participation in a particular operating activity. Preserve a description, date and reasonable duration for each task. If the distinction is unclear, ask the preparer to review it rather than assigning every real estate conversation to a participation log. The strongest records explain the operational connection.',
'An owner logs four hours reviewing market appreciation reports and three hours arranging a repair for a guest-ready rental. The reviewer distinguishes investment research from direct operations. Combining both entries without a task analysis can overstate qualifying participation.',
'Task descriptions; dates; property identification; communications; operational purpose; separate investor-review entries.',
'Can watching tax videos increase my material-participation hours?',
'General education is not automatically participation in a rental activity. The claimed work needs an appropriate connection to the activity under the applicable rules.', ['passive'],'/short-term-rental-tax-strategy/')
add('rental-depreciation-before-first-guest','Can Rental Depreciation Start Before My First Guest Arrives?','Rental basis and depreciation',
'Yes, rental depreciation can begin when the property is ready and available for its specific rental use, even before the first actual booking. Buying the property or starting renovations is not necessarily the placed-in-service date.',
'Identify when the property could actually be rented for the intended use. A listing, required approvals, completed essential work and usable furnishings can help support the timeline, but no single document replaces the factual review. A listing for a property that cannot legally or practically accept guests may not establish readiness. Keep the chronology of acquisition, renovations, advertising and availability. Separate the building’s service date from later assets or improvements that become usable on different dates. Also analyze the costs incurred before readiness, since some must be capitalized rather than deducted immediately. The service date influences depreciation and should be consistent across the return and asset schedule.',
'A furnished rental is ready and advertised in September but receives its first guest in November. If the facts support September readiness for rental use, depreciation may begin then. A property still under major renovation in September has a different timeline even if a future booking is accepted.',
'Availability calendar; listing dates; permits; completion records; furnishing invoices; first booking; depreciation schedule.',
'Does the closing date always start rental depreciation?',
'No. Closing establishes ownership, while placement in service depends on readiness and availability for the income-producing use.', ['rental','depreciation'],'/rental-property-tax-planning/')
add('vacation-rental-personal-use-cost-segregation','How Does Personal Use of a Vacation Rental Affect Cost Segregation?','Rental basis and depreciation',
'Personal use can limit the rental deductions available from a cost segregation study. Reclassifying assets does not make the personal portion of the property depreciable or remove vacation-home limitations.',
'Prepare the rental and personal-use calendar before estimating benefits. The residential rental rules consider the relationship between personal-use days and days rented at fair rental value. Family use and below-market arrangements can create additional questions. Expenses may need allocation, and a dwelling treated as a home can face deduction limits. The passive-activity analysis is a separate step. A projection should identify which costs belong to income-producing use and whether resulting losses can actually be claimed. Owning the property through an entity does not erase personal-use facts. Update the analysis if your use changes after a study is completed.',
'An owner rents a beach house to paying guests and also uses it for family vacations. The study’s depreciation classifications are combined with a use-day and expense-allocation review. The owner does not claim all classified basis as a current rental deduction without considering personal use.',
'Rental days; personal days; family stays; nightly rates; allocation worksheet; activity classification; property costs.',
'Are maintenance visits always personal-use days?',
'The treatment depends on what was done and the applicable use-day rules. Document substantial repair or maintenance work and avoid assuming every trip has the same classification.', ['rental','passive'],'/rental-property-tax-planning/')
add('condo-cost-segregation-zero-land-basis','Can I Use Zero Land Basis for a Condo Cost Segregation Study?','Rental basis and depreciation',
'Not merely because the property is a condo. Determine what ownership interest was purchased, including any land or common-property interest, and use a supportable allocation. Land is not depreciable.',
'Review the deed, purchase documents, association information and valuation evidence. A unit owner may have an interest beyond the interior walls, and the appropriate allocation depends on the property rights and facts. A tax assessment can be helpful evidence but should be considered in context rather than used mechanically. The study should start from a reconciled depreciable basis, not an assumed zero-land figure selected to maximize deductions. Compare the allocation with any prior return treatment before changing it. If the basis is wrong, fixing asset classification alone will not make the depreciation schedule correct. Ask who is responsible for the allocation and how it is supported.',
'A condominium purchase includes a proportional interest in common land. The owner cannot remove that interest from the analysis solely because the unit occupies an upper floor. The reviewer reconciles the ownership and valuation evidence before determining the study’s depreciable basis.',
'Deed; closing statement; association documents; appraisal; assessment details; prior basis allocation; asset schedule.',
'Can I use a fixed land percentage for every condo?',
'No universal percentage fits every property. Document an allocation reflecting the actual ownership interests and supportable values.', ['basis','rental'],'/cost-segregation-study/')
add('cash-out-refinance-cost-segregation-new-appraisal','Does a Refinance Appraisal Increase My Cost Segregation Basis?','Rental basis and depreciation',
'An ordinary refinance appraisal does not generally reset the property’s tax basis to current market value. Depreciation starts from tax basis, including applicable adjustments, rather than the lender’s newest valuation.',
'Reconcile original acquisition cost, capital improvements and depreciation already claimed. Loan proceeds and a market-value appraisal answer financing questions, while basis answers a tax accounting question. If refinance proceeds fund a new improvement, that improvement’s supported cost may create a separate basis addition; the borrowing itself is not the addition. Interest treatment may depend on how proceeds are used and should be evaluated separately. A cost segregation study may still be relevant after refinancing, but the study must use the correct property costs and service dates. Do not combine cash received from a loan with depreciation savings as though they arise under the same rule.',
'A rental bought for $500,000 is later appraised at $750,000 during refinancing. The appraisal does not automatically add $250,000 of depreciable basis. A separately documented $40,000 capital improvement is evaluated as an actual addition to basis.',
'Original closing; capital improvements; depreciation history; refinance documents; proceeds use; new asset service dates.',
'Can a refinance create a new placed-in-service date for the whole property?',
'Refinancing alone does not normally place the existing property in service again. New assets or improvements may have their own service dates.', ['basis','depreciation'],'/cost-segregation-study/')
add('rental-renovation-before-placed-in-service-repair','Can I Deduct Rental Renovations Before the Property Is Ready to Rent?','Rental basis and depreciation',
'Some pre-rental costs must be capitalized, and others require a separate expense or startup analysis. Calling renovation work a repair does not establish an immediate deduction.',
'Review the property’s condition at acquisition and the purpose of each project. Work that improves a unit of property through a betterment, restoration or adaptation is evaluated under capitalization rules. The timing of readiness for rental use also matters. A single contractor invoice can include several categories, so obtain itemized descriptions instead of assigning the entire payment to repairs. Costs associated with acquiring or preparing assets may be handled differently from recurring operating expenses after the rental is ready. Safe harbors have requirements and elections that need review. The correct result is established item by item, then reconciled with the basis and depreciation schedule.',
'An owner buys an uninhabitable rental and replaces essential systems before making it available. The reviewer analyzes the projects and acquisition condition rather than deducting the total as routine maintenance. A small recurring service visit after the property is operating can involve different facts.',
'Acquisition condition; contractor scope; itemized invoices; photographs; readiness date; capitalization policy; elections.',
'Does paying the contractor before year-end guarantee a deduction?',
'No. Payment timing alone does not determine whether a cost is deductible or must be capitalized and depreciated.', ['repairs','rental'],'/rental-property-tax-planning/')
add('missed-rental-depreciation-one-year-vs-multiple','Does Missed Rental Depreciation Require an Amendment or Form 3115?','Depreciation corrections',
'The correction route depends on the error and whether an accounting method has been adopted. A one-return error and depreciation treatment used across multiple returns can require different procedures.',
'Reconstruct the asset schedule before choosing a filing route. Identify the service date, basis, method, life and deductions actually claimed. Distinguish an incorrect method from a mathematical or posting error. Form 3115 may be appropriate for an eligible accounting-method change, while an amended return may be appropriate in other situations. Automatic consent procedures have eligibility rules and designated change numbers that must be checked. The Section 481(a) calculation also must reconcile the old and new treatment. Do not simply write off every omitted amount on the current return without identifying the applicable procedure. Refund limitations and activity loss limits can affect the practical result.',
'An owner discovers an omission after filing one return; another owner has used incorrect depreciation on several returns. The preparer evaluates each history separately. Both situations concern depreciation, but that does not establish that the same form or correction year applies.',
'All affected returns; service dates; basis records; depreciation schedules; method history; prior changes; deadlines.',
'Can I choose an amendment just because it is cheaper?',
'The applicable tax procedure controls. Compare implementation costs only after identifying a permitted correction method and its eligibility requirements.', ['method','depreciation'],'/form-3115-cost-segregation/')
add('form-3115-tax-return-extension-duplicate-copy','Does a Tax Return Extension Also Cover Form 3115 Filing?','Depreciation corrections',
'For an eligible automatic change, the original Form 3115 is generally attached to the timely filed return for the year of change, including applicable extensions. The duplicate-copy procedure must also be satisfied under current instructions.',
'An extension does not eliminate eligibility conditions, signature requirements or separate filing steps. The preparer should identify whether the change is automatic or nonautomatic and check the applicable revenue procedure. For automatic procedures, the original and duplicate copies have specified timing and destinations. Use the current address or permitted submission method; do not assume an old address remains correct. Retain proof of the return filing and separate submission, with the complete adjustment computation. A draft form in the client folder is not evidence that either filing occurred. Review the process before the extended deadline so a missing signature or attachment does not undermine the correction.',
'A taxpayer extends the return and plans an eligible automatic depreciation change. The preparer checks both the return attachment and required duplicate submission. Filing the extension by itself does not mean the accounting-method change has been filed.',
'Extension acceptance; signed Form 3115; eligibility review; adjustment schedule; return acceptance; duplicate submission proof.',
'Is attaching Form 3115 to the return always the only filing step?',
'No. Automatic changes generally involve a separate duplicate-copy submission under the instructions. Confirm the procedure for the particular change.', ['method'],'/form-3115-cost-segregation/')
add('cost-segregation-selling-rental-next-year','Is Cost Segregation Worth It If I Plan to Sell the Rental Next Year?','Rental sale planning',
'A short holding period can reduce the economic benefit of accelerated depreciation. Model the deduction and expected sale together, including basis reductions, recapture rules, fees and whether losses can be used.',
'A study can improve current cash flow without producing permanent tax savings equal to the initial deduction. Accelerated depreciation changes the timing and sometimes the character of tax at disposition. Different asset classes may have different recapture treatment, so one blanket sale-year rate is not a complete model. Include projected proceeds, transaction costs and the owner’s expected tax profile in each year. A suspended loss changes the cash-flow timing as well. Compare the study and implementation fees with the after-tax result over the expected ownership period. The right recommendation can differ between a long-term hold and an imminent sale, even for the same property.',
'An investor expects to sell a rental within twelve months of a study. The advisor compares current benefit with the sale-year basis and recapture consequences. The initial deduction is not presented as a permanent tax saving without that second calculation.',
'Expected sale date; sale price; adjusted basis; asset classes; loss carryovers; implementation fees; tax projections.',
'Does depreciation recapture always equal the original tax savings?',
'No. Rates, asset classifications, loss usability and sale facts can change the outcome. Model the transaction rather than assuming a universal offset.', ['sale','depreciation','passive'],'/cost-segregation-study/')
add('rental-sale-suspended-passive-losses-full-interest','Will Selling One Rental Release All My Suspended Passive Losses?','Rental sale planning',
'Not necessarily. Full release generally requires a qualifying disposition of your entire interest in a passive activity in a fully taxable transaction to an unrelated person. The relevant activity may differ from one property.',
'Review grouping elections and the history of the losses before treating a property sale as the disposal of an entire activity. If multiple properties are grouped, selling one asset can create a different result from selling the whole activity. A partial disposition, installment sale, gift, related-party transfer or tax-deferred exchange can require different rules. Reconcile the return’s passive-loss schedules with the assets being sold. Basis and at-risk restrictions also need separate attention; not every unused deduction is suspended solely under the passive rules. Ask for a sale-year projection showing recognized gain, losses used and losses remaining. The settlement statement alone does not answer those questions.',
'An owner sells one of three rentals that were treated as a single activity. The preparer examines the grouping and sale facts instead of assuming all activity losses are released. A separate, fully taxable sale of the owner’s entire unrelated activity may have a different result.',
'Grouping disclosures; Form 8582 history; ownership; sale agreement; buyer relationship; financing; basis and at-risk schedules.',
'Does a 1031 exchange automatically release every suspended loss?',
'No. A tax-deferred exchange is not the same as a fully taxable disposition of an entire activity. Evaluate recognized income and the continuing activity under the applicable rules.', ['passive','sale'],'/rental-property-tax-planning/')
assert len(P)==25
links=[('/faq/'+x['slug']+'/',x['title']) for x in P]
def paras(text): return '<p>'+html.escape(text)+'</p>'
for x in P:
 path='/faq/'+x['slug']+'/'
 title=x['title']; desc=title+' Review IRS rules, a practical example and records to gather for your tax review.'
 faqs=[(title,paras(x['answer'])),(x['q'],paras(x['a']))]
 records=[v.strip() for v in x['records'].rstrip('.').split(';')]
 body=T.page_header(h1=html.escape(title),subtitle='A focused answer for business owners and rental-property owners.',trail=[('Home','/'),('FAQ','/faq/'),(html.escape(title),path)])
 body+=T.section('The direct answer',paras(x['answer']))
 body+=T.section('How to evaluate your situation',paras(x['explanation']))
 body+=T.section('Hypothetical example',paras(x['example']))
 body+=T.section('Records to gather','<ul>'+''.join('<li>'+html.escape(t)+'</li>' for t in records)+'</ul>')
 body+=T.faq_section([(x['q'],paras(x['a']))],heading='Related question')
 body+=T.section('Source and next step',paras('Updated September 30, 2026. This general federal tax discussion does not decide an individual filing position. Apply the current instructions for the actual tax year and your complete facts.')+'<ul>'+''.join('<li><a href="'+S[k]+'">IRS '+html.escape(k)+' guidance</a></li>' for k in x['source'])+'</ul><p><a href="'+x['hub']+'">Review the related AE service</a> and bring the listed records to a <a href="/discovery/">discovery call</a>.</p>')
 body+=T.section('AE engagement pricing','<p><strong>$7,800 standard advisory engagement. No required recurring annual planning fee.</strong> Two $3,900 payments, 30 days apart. Returns, amendments, cost segregation and additional services are separately scoped. See <a href="/pricing/">published pricing</a> for the service you need.</p>')
 siblings=[l for l,y in zip(links,P) if y['cluster']==x['cluster'] and y['slug']!=x['slug']][:4]
 body+=T.related_section(siblings+[('/faq/','All tax FAQs'),(x['hub'],'Related service guide')])
 schemas=[T.article_schema(title=title,description=desc,url=T.SITE+path,published=DATE,modified=DATE,section=x['cluster'],keywords=[title,x['cluster']],citations=[S[k] for k in x['source']]),T.faq_schema(faqs),T.breadcrumb_schema([('Home','/'),('FAQ','/faq/'),(title,path)])]
 T.write_page(path,T.build_page(title=('S Corp Health Insurance: Spouse Employer Coverage' if x['slug']=='s-corp-health-insurance-spouse-employer-plan' else (title+' | AE Tax' if len(title)<=60 else title)),description=desc,path=path,body=body,schemas=schemas,published=DATE,modified=DATE))
# A visible hub and topic sitemap expose every new URL through normal crawl paths.
hub=ROOT/'faq/index.html'; s=hub.read_text(); start='<!-- LONG_TAIL_FAQ_START -->'; end='<!-- LONG_TAIL_FAQ_END -->'
section=start+T.section('25 Detailed Business and Rental Tax FAQs','<p>Explore specific reimbursement, S corporation, retirement, rental depreciation and participation questions.</p><ul>'+''.join('<li><a href="'+p+'">'+html.escape(t)+'</a></li>' for p,t in links)+'</ul>')+end
if start in s:s=re.sub(re.escape(start)+'.*?'+re.escape(end),lambda m:section,s,flags=re.S)
else:s=s.replace('</main>',section+'\n</main>',1)
hub.write_text(s)
ns='http://www.sitemaps.org/schemas/sitemap/0.9'; ET.register_namespace('',ns)
r=ET.Element('{'+ns+'}urlset')
for path,title in [('/faq/','All FAQs')]+links:
 el=ET.SubElement(r,'{'+ns+'}url');ET.SubElement(el,'{'+ns+'}loc').text=T.SITE+path;ET.SubElement(el,'{'+ns+'}lastmod').text=DATE
ET.ElementTree(r).write(ROOT/'sitemap-faq.xml',encoding='utf-8',xml_declaration=True)
for fn in ['sitemap-index.xml','sitemap_index.xml']:
 fp=ROOT/fn;s=fp.read_text()
 if '/sitemap-faq.xml' not in s:s=s.replace('</sitemapindex>','<sitemap><loc>'+T.SITE+'/sitemap-faq.xml</loc><lastmod>'+DATE+'</lastmod></sitemap>\n</sitemapindex>')
 fp.write_text(s)
# Keep machine-readable discovery limited to actual pages and known pricing.
for fn in ['llms.txt','llms.md','llms-full.txt']:
 fp=ROOT/fn;s=fp.read_text();mark='## Detailed business and rental tax FAQs'
 if mark not in s:s+='\n'+mark+'\n\n'+''.join('- ['+t+']('+T.SITE+p+')\n' for p,t in links)
 fp.write_text(s)
(ROOT/'.well-known/llms.txt').write_text((ROOT/'llms.txt').read_text())
print('Created 25 FAQ pages and a linked hub. Search-volume counts were unavailable and are not invented.')
