#!/usr/bin/env python3
"""Independent, source-linked alternatives for the WCI physician tax directory."""

from __future__ import annotations

import html
import site_template as T

DATE = "2026-09-28"
WCI = "https://www.whitecoatinvestor.com/tax-strategists/"

# Each entry states a distinct buying decision. No fee or missing-service claim is inferred.
FIRMS = [
    dict(slug="duncan-carter-tax-advisory", name="Duncan Carter Tax Advisory", category="Tax strategy", url="https://duncancartertaxadvisory.com/", focus="self-employed physicians with 1099 income and real estate investments", offer="The practice describes an initial written tax plan with a personal video, followed by optional 1040 preparation, projections, and medical accounting with S corporation filing, books, and payroll.", best="a self-employed doctor who wants Duncan's physician-specific explanations, a written plan, and the option to add routine entity accounting", angle="For a practice owner whose operating company and rental portfolio have several prior-year depreciation or entity questions, compare the detailed amendment and property implementation scope in both proposals.", ask="Does the initial plan include review of prior returns and depreciation schedules, and who prepares any Form 3115 or amendment?"),
    dict(slug="thrive-wise-advisors", name="Thrive Wise Advisors", category="Tax strategy", url="https://thrivewisetax.com/", focus="medical professionals seeking holistic tax and wealth planning", offer="Thrive Wise describes customized, ongoing planning around family goals, cash flow, investment assets, and tax decisions; its private-client material describes scheduled quarterly strategy sessions.", best="a physician family that wants a personal tax and financial-life relationship with recurring advisor meetings", angle="If the immediate problem is an operating practice, real estate depreciation, and specific returns to correct, ask both firms for a defined implementation schedule and full first-year fees.", ask="Which wealth-planning services are included, and who prepares and files each tax return and election?"),
    dict(slug="physician-tax-solutions", name="Physician Tax Solutions", category="Tax strategy", url="https://www.physiciantaxsolutions.com/", focus="physicians seeking an integrated strategic wealth system", offer="Physician Tax Solutions by Provident CPAs advertises tax preparation, proactive strategy, accounting, bookkeeping, estate and asset protection coordination, and financial coaching.", best="a physician who wants a broad finance and practice system alongside tax compliance", angle="AE Tax Advisors may fit a profitable practice owner seeking a narrower written tax plan, prior-year review, real estate strategy, and separately priced filing. Scope any estate or asset-protection work with the responsible professional.", ask="Which elements of the Strategic Wealth System are delivered by licensed tax, legal, or financial professionals, and what is the total annual cost?"),
    dict(slug="fox-and-company-cpas", name="Fox & Company CPAs", category="Tax strategy", url="https://fox-cpas.com/", focus="doctor families and practice owners", offer="Fox & Company CPAs describes year-round physician tax advice, practice startups and management, real estate investment advice, compliance, and filing.", best="a doctor family that wants long-term practice and family tax advice from a firm centered on physicians", angle="Compare how each proposal treats the separate business, individual, and real estate returns, and whether a lookback or cost segregation project is included or separately quoted.", ask="Who will own the practice return, family return, and property depreciation work, and how are those fees bundled?"),
    dict(slug="cerebral-tax-advisors", name="Cerebral Tax Advisors", category="Tax strategy", url="https://www.cerebraltaxadvisors.com/", focus="medical practice owners seeking intensive tax strategy", offer="Cerebral describes physician-specific planning, implementation, tax preparation, bookkeeping, payroll, CFO services, and representation. Its WCI listing describes a first-year savings identification guarantee subject to its eligibility conditions.", best="a qualifying medical practice owner who wants hands-on planning and business services under Cerebral's model", angle="Compare each firm's written savings methodology, documentation, responsible professional, and whether the proposed plan addresses old returns and property losses after passive-activity limits.", ask="What are the exact conditions, exclusions, and measurement period of the 2x plan-investment guarantee?"),
    dict(slug="doc-wealth", name="Doc Wealth", category="Tax strategy", url="https://www.docwealth.com/", focus="physicians exclusively, from 1099 work to practice ownership", offer="Doc Wealth describes planning, filing, entity formation, payroll, and bookkeeping by a US-based team. The WCI listing says its flat-priced service starts at $3,799 annually, with the actual quote depending on scope.", best="a physician wanting one provider for routine tax, books, payroll, and entity setup at a published starting price", angle="AE Tax Advisors' $7,800 strategic tier may make sense when substantial business or real estate planning, prior-year review, amendments, and property work justify a larger project. A simple W-2 return would seldom justify that fee.", ask="At the quoted tier, which entity returns, bookkeeping months, payroll services, and planning meetings are included?"),
    dict(slug="taxstra", name="Taxstra PLLC", category="Tax strategy", url="https://taxstra.com/", focus="physicians, physician practices, and other high-income professionals", offer="Taxstra presents physician tax planning integrated with preparation, bookkeeping, and payroll, with attention to retirement, real estate, and business investments.", best="a physician seeking a continuing CPA relationship spanning practice books, payroll, returns, and planning", angle="For an owner with several entities and rentals, compare the written treatment of basis, entity elections, depreciation, old returns, and who implements each decision.", ask="Is tax planning a separate deliverable, and which bookkeeping and payroll services are part of the quoted price?"),
    dict(slug="reza-and-sharif-cpas", name="Reza & Sharif CPAs PC", category="Tax strategy", url="https://rezasharif.com/", focus="independent contractors and private medical practices", offer="The physician-family-owned firm describes business startup, accounting, payroll, year-round planning, and business and personal tax preparation. Its WCI partner profile says most clients use a subscription with an average annual fee of $2,500; that is a reported average, not a quote.", best="a practice that wants ongoing accounting and payroll in a physician-focused CPA relationship", angle="The lower published average should be compared on deliverables rather than against AE's advisory fee alone. Add entity returns, amendments, and any cost segregation project before assessing the total.", ask="What does the quoted subscription cover for my practice entities, owner returns, meetings, and prior-year corrections?"),
    dict(slug="1099-tax-doctor", name="1099 Tax Doctor", category="Tax strategy", url="https://www.1099taxdoctor.com/", focus="independent-contractor physicians", offer="1099 Tax Doctor describes an integrated package of S corporation structures, payroll, defined benefit or cash balance plan administration, tax filing, and advice.", best="a 1099 physician who needs S corporation and retirement-plan operations handled with tax filing", angle="AE Tax Advisors can be compared when the doctor's business and real estate portfolio raise more complex multi-entity and prior-year issues. Retirement plan design and administration should be identified separately in either proposal.", ask="Who administers the retirement plan and payroll, and what are the annual fees and employer contribution requirements?"),
    dict(slug="sfc-cpa", name="SFC CPA", category="Tax strategy", url="https://www.sfccpapllc.com/", focus="healthcare professionals, contractors, and S corporation owners", offer="SFC CPA advertises direct CPA access, QuickBooks support, bookkeeping, business formation, tax preparation, and proactive meetings throughout the year.", best="an owner who wants a close CPA relationship and routine bookkeeping integrated with annual filing", angle="Ask whether the quoted service reaches the specific business-owner and real-estate planning, prior-year analysis, amendments, and property depreciation work that AE emphasizes.", ask="What response and meeting cadence is in the engagement letter, and what tax projects are outside the recurring fee?"),
    dict(slug="kislay-shah-cpa", name="Kislay Shah CPA PC", category="Tax preparation", url="https://shahcpaus.com/", focus="small and mid-sized businesses, physicians, and transactions", offer="The firm lists corporate, partnership, and individual tax preparation, bookkeeping, audit and review work, outsourced CFO services, and quality-of-earnings work for acquisitions.", best="a practice owner who needs assurance, transaction due diligence, or ongoing accounting as well as returns", angle="AE Tax Advisors is a closer match for a focused tax planning and prior-year recovery project involving operating profit and rentals; it does not replace an independent audit or quality-of-earnings report.", ask="If I am buying or selling a practice, which assurance or transaction services are required, and who signs the reports?"),
    dict(slug="convenient-tax-solutions", name="Convenient Tax Solutions", category="Tax preparation", url="https://www.convenient.tax/", focus="busy professionals wanting virtual tax preparation", offer="Convenient Tax Solutions describes secure remote document sharing, scheduling flexibility, and preparation with planning support for professionals who cannot easily visit an office.", best="a professional whose main need is accurate, accessible filing with convenient meetings", angle="An owner with entity, rental, and prior-year strategy questions should compare the depth of a separate planning engagement and the fees for implementation. A straightforward return is a different purchase.", ask="What written planning analysis is included beyond preparing the current return?"),
    dict(slug="tailwind-cpa", name="Tailwind CPA", category="Tax preparation", url="https://www.tailwindfinancial.com/cpa", focus="medical professionals with business ownership, rentals, and multi-state filings", offer="Tailwind describes a small-firm model with quarterly estimates, proactive reviews, off-hours appointments, and experience spanning businesses, rental property, and multi-state returns.", best="a physician who values a smaller ongoing CPA relationship and flexible scheduling", angle="Compare how each team will review depreciation history and real estate loss limits before recommending a study or amendment, then identify who files each affected return.", ask="Are prior-year depreciation and state filings part of the review, and who prepares any corrected returns?"),
    dict(slug="gelt", name="Gelt", category="Tax preparation", url="https://www.joingelt.com/", focus="physician, practice, and healthcare-group tax filing", offer="Gelt describes a technology-supported platform for business and individual returns, quarterly estimates, multi-state filings, and coordination of practice, locums, K-1, and real estate activity.", best="a healthcare group seeking a technology-enabled filing process for multiple income streams", angle="AE Tax Advisors is an alternative for a defined advisory engagement where entity design, return lookback, property depreciation, and amendments are the central problem. Confirm the actual human review and strategy work in either engagement.", ask="Who is the named reviewer for complex K-1 and real estate positions, and what written plan is delivered before filing?"),
    dict(slug="novapoint-cfo", name="NovaPoint CFO", category="Business services", url="https://novapointcfo.com/", focus="physicians and practices seeking tax, accounting, payroll, and wealth management", offer="NovaPoint describes incorporation, accounting and payroll systems, business and personal returns, strategic tax plans, and wealth management with separate asset-based fees.", best="a physician who wants a finance and wealth relationship in addition to tax work", angle="AE Tax Advisors can fit a narrower tax project. Compare fixed tax-plan fees and recurring accounting costs separately from any assets-under-management fee and clarify advisory conflicts.", ask="Which services are fixed fee, which are monthly, and which involve an assets-under-management charge?"),
    dict(slug="realbooks-pro", name="Realbooks Pro", category="Business services", url="https://realbookspro.com/", focus="solo, independent, or part-time physicians", offer="Its WCI listing describes $250 to $500 monthly packages for bookkeeping, year-end preparation, and foundational guidance on S corporations, solo 401(k)s, and student loans. Confirm current tiers directly.", best="a solo or part-time doctor who needs reliable financial basics at a modest monthly cost", angle="A larger AE advisory fee fits a different level of complexity, such as a profitable practice plus rental portfolio and old-year corrections. Do not buy a major strategy engagement when basic books and filing will solve the problem.", ask="Which returns, bookkeeping volume, payroll needs, and planning meetings are included in my monthly tier?"),
]


def esc(s): return html.escape(s, quote=True)
def para(s): return f"            <p>{esc(s)}</p>"


def page(f):
    path = f"/compare/{f['slug']}-alternatives/"
    title = f"{f['name']} Alternatives for Practice Owners | AE Tax"
    desc = f"Considering {f['name']}? Compare its physician tax services with AE Tax Advisors on scope, client fit, implementation, and the questions to ask before signing."
    crumb = [("Home", "/"), ("Compare", "/compare/"), (f["name"] + " alternatives", path)]
    name = esc(f['name'])
    comparison = f'''            <div class="ae-table-scroll" style="overflow-x:auto"><table class="compare-table">
                <caption>Based on public descriptions reviewed September 28, 2026. A proposal controls the actual scope.</caption>
                <thead><tr><th scope="col">Decision</th><th scope="col">{name}</th><th scope="col">AE Tax Advisors</th></tr></thead>
                <tbody><tr><th scope="row">Primary public focus</th><td>{esc(f['focus'])}</td><td>Profitable operating businesses and real estate investors, including practice owners</td></tr>
                <tr><th scope="row">Described model</th><td>{esc(f['offer'])}</td><td>Written tax advisory with prior-year review, entity and property planning, and separately scoped filings</td></tr>
                <tr><th scope="row">Advisory pricing</th><td>Request a current proposal and confirm included work</td><td>$7,800 strategic or $9,800 complex advisory; other services separately priced</td></tr></tbody></table></div>'''
    q = f['ask']
    faqs = [
        (f"What is an alternative to {f['name']}?", f"<p>AE Tax Advisors is one option when a profitable practice owner needs a defined business and real estate tax plan, prior-year review, and coordinated implementation. {name} may fit better for {esc(f['best'])}. Compare written proposals for your actual facts.</p>"),
        (f"Is {f['name']} better for a physician?", f"<p>It depends on the physician's income and work. {name} describes services for {esc(f['focus'])}. A physician with only a W-2 and a simple return may not need an extensive advisory engagement. A practice owner with entities and properties should compare the depth of the tax plan, assigned professionals, and filing scope.</p>"),
        (f"How much does {f['name']} cost?", "<p>Confirm current pricing directly with the firm and request a written first-year and renewal proposal. Make sure the quote specifies every entity and individual return, books, payroll, strategy meeting, amendment, and property study you need. AE Tax Advisors publishes $7,800 strategic and $9,800 complex advisory tiers, with other work priced separately.</p>"),
    ]
    body = '\n'.join([
        T.page_header(h1=title, subtitle=desc, trail=crumb),
        T.section("The decision in brief", para(f"{f['name']} is a relevant option for {f['focus']}. {f['offer']} AE Tax Advisors is worth comparing when a profitable owner needs a structured review of business and property taxes, old returns, and implementation across multiple filings. Neither firm's name alone tells you which work is included.")),
        T.section(f"Where {f['name']} may be the stronger fit", para(f"A good reason to shortlist {f['name']} is {f['best']}. Ask who will personally handle that work and whether the quoted package includes the services you expect. A plan for a simple physician return is a different purchase from recurring practice accounting or a complex tax strategy. The advertised model may include more or less than your specific proposal.")),
        T.section("Where AE Tax Advisors may fit", para(f['angle']) + para("AE Tax Advisors publishes $7,800 strategic and $9,800 complex advisory tiers. Business and individual returns, amendments, and cost segregation have separate prices. A tax plan should identify the actual opportunity, legal limitations, responsible person, filing year, documentation, and implementation cost before anyone compares projected savings with fees.")),
        T.section("Service comparison", comparison),
        T.section("Questions to resolve before signing", f'''            <ul class="takeaway-list">
                <li>{esc(q)}</li>
                <li>Which business, individual, and state returns are included, and who signs them?</li>
                <li>Who reviews prior returns, entity elections, books, and depreciation schedules?</li>
                <li>If real estate losses are proposed, who tests basis, at-risk, material participation, and passive activity limits?</li>
                <li>What written work product will I receive, when will it be implemented, and what costs recur next year?</li>
            </ul>'''),
        T.section("Sources and editorial note", f'''            <p>This independent comparison uses the <a href="{WCI}" rel="nofollow external noopener">White Coat Investor physician tax directory</a> and <a href="{esc(f['url'])}" rel="nofollow external noopener">{name}'s public website</a>. The directory separates strategy, tax preparation, and business services, which are different purchases. AE Tax Advisors is responsible for this page and is not affiliated with either organization. Listed services and fees can change; a service omitted from public materials may still be offered. Check the current proposal directly.</p>'''),
        T.faq_section(faqs),
        T.related_section([('/compare/physician-tax-advisor-alternatives/', 'Compare all physician tax firms'), ('/pricing/', 'AE Tax Advisors pricing'), ('/business-owner-tax-planning/', 'Business owner tax planning'), ('/discovery/', 'Book a discovery call')], 'Continue your research'),
    ])
    schema = [T.article_schema(title=title, description=desc, url=T.SITE+path, published=DATE, modified=DATE, section='Physician Tax Advisor Comparison', keywords=[f['name']+' alternatives', f['name']+' vs AE Tax Advisors', 'physician tax advisor'], citations=[WCI, f['url'], T.SITE+'/pricing/']), T.breadcrumb_schema(crumb)]
    return T.build_page(title=title, description=desc, path=path, body=body, schemas=schema, published=DATE, modified=DATE)


def hub():
    path='/compare/physician-tax-advisor-alternatives/'
    title='Physician Tax Advisor Alternatives: Compare 16 Firms (2026)'
    desc='Compare the tax strategy, preparation, and business-service firms in the White Coat Investor physician tax directory with AE Tax Advisors by actual service need.'
    groups=[]
    for group in ('Tax strategy', 'Tax preparation', 'Business services'):
        cards=[]
        for f in FIRMS:
            if f['category'] != group: continue
            slug=f"/compare/{f['slug']}-alternatives/"
            cards.append(f'''                <article class="cs-card"><h3><a href="{slug}">{esc(f['name'])} alternatives</a></h3><p>{esc(f['focus'].capitalize())}. {esc(f['offer'])}</p><a href="{slug}" class="btn-secondary">Compare the services</a></article>''')
        groups.append(f'''    <section class="content-section fade-in-section"><div class="container"><h2>{group}</h2><div class="cs-grid">{''.join(cards)}</div></div></section>''')
    body='\n'.join([T.page_header(h1=title, subtitle=desc, trail=[('Home','/'),('Compare','/compare/'),('Physician tax advisor alternatives',path)]), T.section('Start with the work you need', para('A physician with a W-2 and a simple return may only need preparation. A 1099 doctor may need entity and retirement-plan operations. A profitable practice owner with rental property may need a written multi-year tax plan, depreciation review, and coordinated business and individual filings. Compare firms on those deliverables before comparing a headline fee.')+para('The firms below appear in the White Coat Investor physician tax directory as of September 28, 2026. This is an independent AE Tax Advisors guide, not a White Coat Investor endorsement of AE Tax Advisors. The directory describes its listings as advertising partnerships; verify each firm and proposal directly.')), *groups, T.section('Compare the full first-year price', para('Ask each firm for a written list of covered entities, returns, accounting months, payroll, meetings, prior-year review, amendments, cost segregation, and renewal terms. AE Tax Advisors publishes $7,800 strategic and $9,800 complex advisory tiers, with returns and specialized work separately priced. A lower filing package can be the right choice when the problem is routine compliance.')), T.related_section([('/pricing/','AE Tax Advisors pricing'),('/discovery/','Book a discovery call')])])
    crumb=[('Home','/'),('Compare','/compare/'),('Physician tax advisor alternatives',path)]
    schema=[T.article_schema(title=title,description=desc,url=T.SITE+path,published=DATE,modified=DATE,section='Physician Tax Advisor Comparison',citations=[WCI,T.SITE+'/pricing/']),T.breadcrumb_schema(crumb)]
    return T.build_page(title=title,description=desc,path=path,body=body,schemas=schema,published=DATE,modified=DATE)


if __name__ == '__main__':
    for f in FIRMS:
        print(T.write_page('/compare/'+f['slug']+'-alternatives', page(f)))
    print(T.write_page('/compare/physician-tax-advisor-alternatives', hub()))
