from pathlib import Path
import re,json,html
import site_template as T
DATE='2026-10-08'
SRC='https://growyournetworth.com/'
GC=SRC+'growthcircle'
BBB='https://www.bbb.org/us/mt/billings/profile/tax-consultant/ae-tax-advisors-1296-1000196769'
PAGES=[
('compare/braiden-shaw-alternatives','Braiden Shaw Alternatives: Choose the Right Type of Help','Compare Braiden Shaw alternatives by education, tax advisory, financial planning and investment access before choosing a provider.',[
('Start with the decision you need to make','Someone searching for Braiden Shaw alternatives may want very different things: financial education, a community of investors, a personalized tax plan, or a professional who manages investments. Those are separate purchases. Braiden Shaw’s Grow Your Net Worth website presents Amplifi Foundations and Growth Circle as learning and community programs. Its disclosure says the material is education and identifies Amplifi and Shaw as outside the roles of registered investment adviser, tax adviser and law firm. That distinction helps you decide which alternatives actually solve your problem.'),
('Four alternatives, depending on your goal','For budgeting and financial literacy, compare educational programs on curriculum, coaching access, total membership cost and cancellation terms. For portfolio advice, compare appropriately registered investment advisers on services, compensation and conflicts. For entity, property and return questions, compare tax advisory firms on the written analysis and implementation included. For legal documents, use an attorney engaged for the relevant jurisdiction. You may need more than one provider; a membership should not be assumed to include all of these professional assignments.'),
('When AE Tax Advisors belongs on your shortlist','AE is relevant when your immediate need is business or real estate tax planning. Bring recent returns, entity details and depreciation schedules to discuss the work required. Confirm whether the proposed engagement includes a written plan, prior-year review, projections, amendments, property studies and implementation. AE’s tax engagement should be compared with another tax engagement, while education and private-deal access should be evaluated on their own terms.'),
('How to compare the complete cost','Ask for the first-year and renewal cost, deliverables, meeting cadence and separately billed work. A program fee and a tax-plan fee cannot be compared fairly until their scope is clear. Do not treat an advertised deduction, investment return or another person’s experience as your expected savings. Review the fee against your actual needs and available alternatives before signing.')]),
('compare/amplifi-alternatives','Amplifi Alternatives for Tax Planning and Wealth Education','Evaluate alternatives to Braiden Shaw’s Amplifi by curriculum, professional scope, implementation, fees and the support your situation needs.',[
('Decide whether you need education or professional work','Amplifi’s public website describes Foundations as a wealth education program with tools, lessons and group coaching. It also presents Growth Circle for people seeking community and private-market opportunities. When evaluating Amplifi alternatives, first identify whether you want to learn the concepts or hire someone to apply them to your records. Education can make you a better-informed client, but a separate engagement defines who will review your returns, model a strategy and prepare filings.'),
('A useful education comparison','Request the curriculum and sample lesson before choosing a program. Compare live versus recorded teaching, access to instructors, the experience level of the audience and whether there is feedback on your work. Ask how sponsors and referrals are compensated, what is included in the membership and what requires additional capital. If your primary goal is confidence with budgeting or basic investing, a complex tax advisory engagement may be unnecessary.'),
('A useful tax advisory comparison','For an operating business or rental portfolio, compare the assigned professional, records reviewed, written recommendations and implementation responsibilities. Ask whether the analysis covers existing elections, depreciation history, state filings and prior-year opportunities where relevant. A service should explain the assumptions and unresolved questions before presenting an estimated result. Make sure any return preparation, amendments and cost segregation studies appear explicitly in the proposal.'),
('How AE fits the decision','AE Tax Advisors offers a tax-focused conversation for business owners and real estate investors. Its pricing and engagement scope should be evaluated separately from membership education or investment access. Use the discovery call to identify the problem, records needed and proposed work. If your goal is discretionary portfolio management, securities recommendations or legal drafting, engage the appropriate professional for that separate assignment.')]),
('compare/growth-circle-vs-ae-tax','Growth Circle vs AE Tax Advisors: Membership or Tax Engagement?','Compare Growth Circle’s education and investment community with an AE tax advisory engagement by purpose, scope and implementation.',[
('Two different service models','Growth Circle’s official page describes a private investing community led by Braiden Shaw, with education, coaching and opportunities to learn about private-market deals. AE Tax Advisors presents business and real estate tax planning under a defined engagement. The practical choice is whether you need a learning community, a tax assignment, or both. Neither model should be judged only by a headline price.'),
('What to confirm with Growth Circle','Ask for current membership terms, renewal charges, access periods, coaching arrangements and any additional costs attached to an investment opportunity. Its public FAQ distinguishes membership from individual deals and explains that each deal has its own offering documents and eligibility. Evaluate the documents and economic risks for each opportunity separately. Also ask whether a named tax professional will review your specific records under a separate engagement; do not infer that from a discussion of tax strategies.'),
('What to confirm with AE','Identify the entities, returns and properties in scope. Ask who prepares the written analysis, what documents you must supply and who implements each accepted recommendation. Confirm separate charges for returns, studies, amendments and ongoing work. If the plan relies on another professional, make the handoff explicit. A well-defined proposal makes it possible to compare competing tax firms on the same assignment.'),
('A practical way to decide','A business owner with an unresolved depreciation or entity question can start by obtaining professional analysis of that issue. A person seeking broader financial literacy and networking can compare education memberships instead. Someone considering both should budget separately and avoid counting the same projected benefit twice. Compare written deliverables and eligibility rather than assuming a membership or a firm can deliver another customer’s outcome.')]),
('compare/braiden-shaw-reviews','Braiden Shaw Reviews: How to Evaluate Amplifi and Growth Circle','A source-based guide to reading Braiden Shaw reviews, distinguishing membership experiences from tax implementation and checking current terms.',[
('Match the review to the product','Braiden Shaw appears across financial education, business and investing content. A review of an event does not establish the quality of a separate tax engagement or investment. When reading Braiden Shaw reviews, identify whether the writer attended a workshop, joined Foundations, purchased Growth Circle or participated in an individual deal. Look for the date, product, length of participation and specific service described.'),
('Separate experience from financial outcome','Communication, teaching quality and community access are useful experience measures. Tax savings and investment performance need different evidence. Ask whether a number is an estimate, a deduction, a deferral, a realized investment gain or a final result after fees. A favorable experience does not establish your eligibility for a strategy. A negative experience should also be read in context rather than generalized to every service associated with a person.'),
('Use original sources','Read the current program website and terms alongside independent review platforms. Check the reviewer’s actual description rather than relying solely on a star average. Identify referral incentives or sponsorship disclosures where available. AE has not purchased or audited Amplifi or Growth Circle and this page is not a firsthand customer review, a rating or an endorsement. It is a guide to evaluating the evidence before buying.'),
('If your search is really about tax help','Amplifi’s website distinguishes education from professional tax advice. If you need someone to review returns, quantify opportunities and implement work, compare a separately scoped tax engagement. AE Tax Advisors is an option for business and real estate tax work. Request a written proposal and compare it with other firms using the same entities, properties, deadlines and deliverables.')]),
('compare/tax-education-vs-tax-advisory','Tax Education vs Tax Advisory: What Are You Buying?','Understand the difference between a tax education membership and a professional engagement that reviews records and implements a plan.',[
('Learning a strategy and applying it are different steps','A lesson can explain an entity structure or a property tax concept without establishing whether it works for a particular household. A professional assignment begins with records, facts and a defined scope. The key question is who will move from the general idea to a documented recommendation and then carry out the required work. Ask this before comparing prices or promised benefits.'),
('What an education program can help you do','Education can introduce terminology, improve the questions you ask and help you organize your goals. Compare programs on curriculum, instruction and access rather than assuming they include return review or filing. If professional services are offered separately, obtain that separate proposal. A group discussion of an example is not evidence that your facts have been examined.'),
('What to ask a tax advisory firm','Request a list of records reviewed and the work product delivered. Clarify who owns projections, elections, return preparation and follow-up. Find out how recommendations are documented and what happens when information is missing. Confirm deadlines, client responsibilities, additional fees and the limits of any audit support. The written engagement is the basis for evaluating the service.'),
('Make the handoff visible','If you learn an idea through a membership, take it to the professional responsible for your tax work before implementing it. Share the source and explain the intended business purpose. Ask the professional to identify eligibility, documentation, costs and alternative approaches. AE’s discovery process can help determine whether a business or real estate tax engagement is appropriate; the agreed scope controls the work delivered.')]),
('ae-tax-advisors-reviews/business-owners','AE Tax Advisors Reviews for Business Owners: What to Evaluate','Evaluate AE Tax Advisors for business tax work using review sources, entity scope, professional responsibilities and a written proposal.',[
('Look for evidence that matches your business','A review about a simple individual return may say little about planning for several entities, payroll and an operating company. When evaluating AE Tax Advisors reviews as a business owner, look for the service purchased, timing and responsibilities described. Ask whether the reviewer’s needs resemble yours. This page is written by AE and is not an independent review or a collection of newly verified customer testimonials.'),
('Compare the engagement, not just the impression','Prepare a list of your entities, states, owners and filing years. Ask which returns are included, whether books need correction and whether the proposal covers planning or preparation. Confirm who evaluates owner compensation and existing elections where those issues are in scope. Request a written description of the analysis and implementation, including work assigned to your payroll provider or attorney.'),
('Use the review source and the planning stories differently','Third-party feedback can describe the experience a customer reports. AE’s case studies explain planning situations and are published by AE. They do not establish a typical result or an independent star rating. Read each story’s facts, status and limitations. Use the main reviews page to reach the available external source and evaluate any feedback in its original context.'),
('Questions to bring to discovery','Who is responsible for reviewing my records? What is included in the first-year fee, and what renews? Which current and prior-year filings require separate quotes? What records are needed before recommendations can be made? What timeline applies after those records are complete? Have the agreed answers included in the engagement. If your needs are limited to routine compliance, compare a preparation-only proposal as well.')]),
('ae-tax-advisors-reviews/real-estate-investors','AE Tax Advisors Reviews for Real Estate Investors: What to Check','Assess AE’s real estate tax services through review sources, case-study context, property scope and implementation responsibilities.',[
('Identify the property work you actually need','Real estate investors may need a property study, return preparation, depreciation correction or a broader tax plan. Those are different assignments. When evaluating AE Tax Advisors reviews, identify which service the customer received and whether it resembles your situation. This AE-authored guide helps you compare scope; it does not add customer ratings or claim independently verified outcomes.'),
('Bring a clear property inventory','List properties, ownership entities, acquisition dates, placed-in-service dates and prior depreciation schedules. Tell the team whether each property is a long-term rental, short-term rental, former residence or another use. Ask whether the engagement includes reviewing prior filings and the records needed for a property study. The proposal should identify which properties and tax years are covered and what additional work costs.'),
('Evaluate the implementation responsibilities','Ask who produces the study, who reviews how its results apply to your returns and who prepares any necessary filing. Establish which documentation you must retain and which assumptions still require confirmation. If a proposed result depends on your activity or ownership facts, ask how those facts will be reviewed. An attractive deduction estimate is not the same thing as an implemented and usable tax benefit.'),
('Read stories and reviews with their limitations','A property case study can show the questions a plan considered, while a customer review can describe the reported service experience. Neither predicts your result. Use AE’s main reviews page for external feedback sources and its case-study library for examples with their stated limitations. Confirm the complete scope, named professional, fee and delivery milestones in writing before starting.')])]
links=[('/'+s+'/',t) for s,t,_,_ in PAGES]
for slug,title,desc,sections in PAGES:
 path='/'+slug+'/'
 trail=[('Home','/'),('Compare','/compare/') if slug.startswith('compare/') else ('AE reviews','/ae-tax-advisors-reviews/'),(title,path)]
 body=T.page_header(h1=title,subtitle=desc,trail=trail)
 for head,txt in sections:body+=T.section(head,'<p>'+html.escape(txt)+'</p>')
 body+=T.section('Sources and disclosure',f'<p>Published by AE Tax Advisors. AE is not affiliated with Braiden Shaw or Amplifi. Public descriptions reviewed October 8, 2026: <a href="{SRC}" rel="external noopener">Grow Your Net Worth</a>, <a href="{GC}" rel="external noopener">Growth Circle</a>, and <a href="{BBB}" rel="external noopener">AE’s BBB business profile</a>. Services and terms may change. AE’s scope is confirmed in a signed engagement. Outcomes depend on individual facts.</p>')
 body+=T.related_section([(p,t) for p,t in links if p!=path]+[('/ae-tax-advisors-reviews/','AE Tax Advisors reviews and case studies'),('/pricing/','Current AE pricing'),('/discovery/','Book a discovery call')])
 schema=[T.article_schema(title=title,description=desc,url=T.SITE+path,published=DATE,modified=DATE,citations=[SRC,GC,BBB]),T.breadcrumb_schema(trail)]
 T.write_page(path,T.build_page(title=title,description=desc,path=path,body=body,schemas=schema,published=DATE,modified=DATE))
nav=T.related_section(links,'Compare Braiden Shaw, Amplifi and AE Tax Advisors')
nav=nav.replace('<section ','<section id="braiden-ae-review-cluster" ',1)
for relative in ['compare/index.html','ae-tax-advisors-reviews/index.html']:
 p=T.ROOT/relative;s=p.read_text();assert 'braiden-ae-review-cluster' not in s
 s=s.replace('</main>',nav+'</main>',1);p.write_text(s)
p=T.ROOT/'sitemap-braiden-reviews.xml'
p.write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{T.SITE}{path}</loc><lastmod>{DATE}</lastmod></url>' for path,_ in links)+'</urlset>')
for filename in ['sitemap_index.xml','sitemap-index.xml']:
 p=T.ROOT/filename;s=p.read_text()
 if 'sitemap-braiden-reviews.xml' not in s:p.write_text(s.replace('</sitemapindex>',f'<sitemap><loc>{T.SITE}/sitemap-braiden-reviews.xml</loc><lastmod>{DATE}</lastmod></sitemap>\n</sitemapindex>'))
print('Created',len(PAGES),'pages and expanded reviews/comparison navigation.')
