"""Separate owner deductions, employer phone benefits and internet reimbursement."""
import json
import re
import site_template as T

DATE='2026-09-26'
OVERVIEW='/blog/can-my-business-pay-for-my-cell-phone-and-internet/'
PHONE='/blog/business-employee-cell-phone/'
INTERNET='/blog/business-employee-home-internet/'
LEGACY='/how-to-write-off-your-cell-phone-and-internet-for-business-use/'
POSTS=[
dict(path=OVERVIEW,title='Business Cell Phone and Internet Deductions',published='2026-08-02',
description='Can your business pay your phone and internet bills? Review business-use allocation, entity differences and links to employer reimbursement guides.',
lead='Your business may deduct qualifying phone and internet costs, but paying a bill from the business account does not make a personal expense deductible. Start with who owns the business, who pays the bill and how the service is used. Employer-provided phones and employee reimbursements require their own review.',
sources=[('https://www.irs.gov/publications/p334','IRS Publication 334: business expenses'),('https://www.irs.gov/faqs/small-business-self-employed-other-business/income-expenses/income-expenses-1','IRS: separating business and personal expenses'),('https://www.irs.gov/publications/p15','IRS Publication 15: employee reimbursements')],
body='''<h2>Choose the question that matches the payment</h2>
<ul><li><strong>Your own business phone bill:</strong> use the allocation and recordkeeping steps below.</li><li><strong>A company phone or a payment to staff:</strong> use the <a href="/blog/business-employee-cell-phone/">employer cell-phone benefit and reimbursement guide</a>.</li><li><strong>Home internet paid by a corporation or reimbursed to a remote worker:</strong> use the <a href="/blog/business-employee-home-internet/">home-internet reimbursement guide</a>.</li></ul>
<p>These arrangements can look identical in a bank feed while having different reporting consequences. Keep the service contract, invoice, person using the service and legal payer together in the review file. An owner should be able to explain the expense without relying on the name of a bookkeeping category.</p>
<h2>How much of a personal cell-phone bill can a business owner deduct?</h2>
<p>For a sole proprietor using one phone for business and personal activity, separate the supported business portion from personal use. There is no universal percentage that turns a mixed-use phone into a full deduction. The IRS small-business guidance requires ordinary and necessary business expenses and separation of personal spending.</p>
<p>Build a reasonable allocation from the actual use pattern. Review business contacts, calendar activity, service needs and available usage records. Explain why the method fits the work and review it when the business or plan changes. A percentage copied from another owner’s return is not evidence for your business.</p>
<h2>Example: allocate the relevant line before applying a percentage</h2>
<p>Suppose a consultant pays a $180 monthly family-plan bill. The invoice and plan details support assigning $75 to the consultant’s line and related service. If a documented review supports 60% business use of that portion, the working calculation is $45 a month, or $540 for twelve identical months. Applying 60% to the entire family bill would instead produce $1,296 and would include other household users in the calculation.</p>
<p>This is a hypothetical allocation example, not an IRS-approved safe harbor. The advisor should review the method, shared charges, credits and any separately purchased device. A handset installment, service charge and personal subscription bundled onto the bill may need different treatment. Do not turn the example into a default deduction percentage.</p>
<h2>What changes when an S corporation pays?</h2>
<p>A corporation’s payment of an owner’s personal bill needs classification; it is not automatically the same as a sole proprietor claiming a business expense. Identify whether the company owns the service, reimburses a supported business cost or pays an owner benefit requiring separate treatment. Ask the advisor to consider the owner’s employee and shareholder status.</p>
<p>Publication 15 describes accountable-plan requirements: a business connection, timely substantiation and timely return of excess advances. A transfer labeled “reimbursement” is not enough by itself. See the <a href="/blog/business-owner-reimbursement-no-accountable-plan/">owner reimbursement review</a> if payments were made without an established process. Partners and sole proprietors should not assume that they are employees of their own businesses for reimbursement purposes.</p>
<h2>Can the business also pay for home internet?</h2>
<p>Review home internet separately from the phone. List the business tasks, household users, bundled services and allocation support. Reconcile any amount claimed directly with reimbursements and other workpapers so the same expense is not counted twice. A home-office square-foot percentage is not automatically evidence of how a household uses its internet connection. The <a href="/blog/business-employee-home-internet/">internet reimbursement guide</a> walks through the company’s payment and review process.</p>
<h2>Keep a compact expense file</h2>
<ul><li>Monthly invoices showing the line, service period, credits and separate device charges.</li><li>A dated explanation of the business purpose and allocation method.</li><li>Proof of payment and any reimbursement claim or approval.</li><li>A reconciliation to the business ledger and the final tax workpaper.</li></ul>
<p>Review the file when a family member joins the plan, a role changes, a service is canceled or the company starts paying directly. That short review prevents an old allocation from becoming a permanent assumption.</p>''',
faqs=[('Can I deduct my entire family phone plan?','<p>Do not assume the whole family plan is a business expense. Identify the relevant line and service costs, support the business use and review personal charges separately.</p>'),('Does using a business card make the bill deductible?','<p>No. The payment source does not establish the business purpose or eliminate personal use. Classify the underlying expense and reconcile it to the records.</p>'),('Where are the rules for phones provided to employees?','<p>See the <a href="/blog/business-employee-cell-phone/">employer phone guide</a> for the separate benefit and reimbursement analysis.</p>')]),
dict(path=PHONE,title='Employer Cell Phones and Reimbursements: Tax Rules',published='2026-09-22',
description='Business owners: compare company phones, personal-phone reimbursements and cash stipends, with a policy checklist and payroll review questions.',
lead='A business owner deciding how to pay for employees’ phones should distinguish a company-provided device, reimbursement of an employee’s phone expense and unrestricted cash compensation. The business reason and payment design matter more than calling every payment a phone allowance.',
sources=[('https://www.irs.gov/pub/irs-drop/n-11-72.pdf','IRS Notice 2011-72: employer-provided cell phones'),('https://www.irs.gov/pub/foia/ig/sbse/sbse-04-0911-083.pdf','IRS memorandum: reimbursement of employee cell-phone expenses'),('https://www.irs.gov/publications/p15b','IRS Publication 15-B: fringe benefits')],
body='''<h2>Company-provided phone: document the operational need</h2>
<p>Under Notice 2011-72, a phone provided primarily for noncompensatory business reasons can receive favorable treatment: business use is a working-condition fringe benefit and incidental personal use is a de minimis fringe benefit. The notice’s substantiation treatment is tied to those conditions. A phone supplied primarily as extra compensation does not qualify merely because it can receive business calls.</p>
<p>Write the actual business reason into the approval. A property-management employee may need to receive urgent maintenance calls after office hours. A service technician may need dispatch instructions while visiting customers. Identify the job requirement, the person approving the device and the plan that meets that requirement. Avoid a generic statement that every possible device is required for every employee.</p>
<h2>Personal-phone reimbursement needs a separate check</h2>
<p>The IRS reimbursement memorandum addresses employers requiring personal-phone use for substantial noncompensatory business reasons. It considers whether the coverage is reasonably related to business needs, the reimbursement reasonably matches the expense and the payment substitutes for wages. That guidance does not make every flat payment or family-plan reimbursement tax-free.</p>
<p>Before payroll implements the arrangement, compare the company’s communication needs with the employee’s service cost and the proposed reimbursement. Identify unusually expensive plans, household lines and unrelated bundled purchases. Record how the company will respond when the bill decreases, service changes or the employee stops performing the role that justified payment.</p>
<h2>Example: the same $60 payment can mean different things</h2>
<p>Consider a plumbing company that requires its on-call coordinator to use a personal phone for customer dispatch. The company reviews the relevant service cost and approves a $60 monthly reimbursement that fits its documented need. Compare that with a business adding $60 to everyone’s pay after a compensation negotiation and labeling it a phone reimbursement without reviewing costs or duties.</p>
<p>The dollar amount alone cannot settle the payroll treatment. This hypothetical comparison identifies the facts the reviewer needs. It is not a tax-free allowance schedule or a conclusion that $60 is reasonable for every role. Maintain the support for the actual arrangement instead of copying the example into a policy.</p>
<h2>Build the policy around decisions payroll can apply</h2>
<ul><li><strong>Eligibility:</strong> which duties require mobile access, and who authorizes participation?</li><li><strong>Payment model:</strong> does the company contract with the carrier or reimburse the employee?</li><li><strong>Cost review:</strong> what bill, role description and approval must be retained?</li><li><strong>Changes:</strong> how are leave, job changes, plan changes and termination handled?</li><li><strong>Exceptions:</strong> who reviews family lines, upgrades, overseas use and disputed amounts?</li><li><strong>Payroll treatment:</strong> who determines and records the applicable exclusion or wage treatment?</li></ul>
<p>Ask the payroll provider to confirm its configuration before the first payment. A correct written policy can still be implemented incorrectly if payroll codes an allowance differently from the approved decision. Reconcile the first payment and review an exception, not just the standard case.</p>
<h2>Owner payments and other benefits are not automatic extensions</h2>
<p>Tell the advisor when the recipient is an owner, partner or shareholder-employee so the applicable status and benefit rules are considered. Keep home internet, computer equipment and other reimbursements out of a phone-only approval unless each has been analyzed. Publication 15-B addresses fringe-benefit categories; a result for one benefit does not establish the treatment of another.</p>
<p>For the business owner’s personal bill and mixed-use allocation, return to the <a href="/blog/can-my-business-pay-for-my-cell-phone-and-internet/">phone and internet deduction overview</a>. For remote-work broadband, use the <a href="/blog/business-employee-home-internet/">home-internet reimbursement checklist</a>.</p>''',
faqs=[('Is a phone stipend automatically tax-free?','<p>No. Review the business reason, payment design, expense support and applicable payroll treatment. The name assigned to the payment does not decide the result.</p>'),('Do these phone rules automatically cover home internet?','<p>No. Evaluate broadband separately using the <a href="/blog/business-employee-home-internet/">internet reimbursement guide</a>.</p>')]),
dict(path=INTERNET,title='Home Internet Reimbursement: A Business Owner’s Guide',published='2026-09-22',
description='Build a home-internet reimbursement process for your business: document necessary use, allocate shared bills and prevent duplicate expense claims.',
lead='A company may reimburse a supported business share of home internet under a qualifying reimbursement arrangement. Paying the full household bill or a fixed allowance without support requires further review. This guide is for business owners designing the payment process for staff or owner-employees.',
sources=[('https://www.irs.gov/publications/p15','IRS Publication 15: accountable and nonaccountable plans'),('https://www.irs.gov/publications/p463','IRS Publication 463: reimbursement arrangements'),('https://www.irs.gov/faqs/small-business-self-employed-other-business/income-expenses/income-expenses-1','IRS: business and personal expense allocation')],
body='''<h2>Define the work the connection supports</h2>
<p>Start with the company’s operational needs: client calls, secure access to business files, property-management communications or other duties performed from home. Record which roles need the connection and who approves reimbursement. This makes the policy understandable to the person reviewing a claim rather than leaving each employee to guess what the company intended.</p>
<p>Keep equipment, installation, monthly service and unrelated bundles distinct. A bill that combines broadband, entertainment and a device installment should not enter the expense report as one unexplained business amount. Ask the claimant to identify the relevant service period, credits and the portion actually being submitted.</p>
<h2>Support an allocation instead of selecting a standard percentage</h2>
<p>There is no universal allocation in this guide. Review the work pattern, shared household use, service requirements and facts supporting the proposed business share. The method should fit the expense being allocated. A floor-area percentage used elsewhere in a home-office calculation does not automatically measure broadband use.</p>
<p>Document the rationale in plain language and retain the bill. Revisit it when duties, household use or the service plan materially changes. A dedicated business connection presents different facts from a family connection shared with entertainment and personal activity. Avoid treating a proposed allocation as approved until the reviewer has examined those facts.</p>
<h2>Example: reconcile the bill, claim and payment</h2>
<p>Suppose an owner-employee submits a $120 monthly bundle. The invoice identifies $30 of entertainment service and $90 of broadband. A documented review supports a hypothetical 50% business allocation of the broadband portion. The proposed reimbursement is $45, not $60 and not $120. The business must still review the eligibility of the arrangement and the support for that allocation.</p>
<p>If the company already paid $45 directly toward the same bill, an additional $45 expense-report payment could duplicate it. Track the service month and invoice reference so two payment systems do not pay the same supported cost. The numbers illustrate a workflow; neither 50% nor $45 is an IRS safe harbor.</p>
<h2>Apply the reimbursement conditions</h2>
<p>Publication 15 requires an accountable arrangement to have a business connection, timely substantiation and timely repayment of excess advances. Amounts meeting its conditions are not wages; unsupported or excess amounts can receive nonaccountable-plan treatment. Publication 463 provides additional reimbursement guidance. Review owner status and the actual arrangement before payroll decides the treatment.</p>
<p>A recurring reminder can help the company obtain missing bills, but an approval workflow is only useful if someone resolves the exceptions. Decide who follows up on missing documentation, who reviews disputed allocations and how overpayments are recovered or reported. Do not silently carry an unresolved claim into the next tax year.</p>
<h2>Use a claim checklist that can be reconciled</h2>
<ol><li>Identify the employee or owner-employee, company and service month.</li><li>Attach the itemized bill and proof of payment when applicable.</li><li>Separate excluded bundle items and explain the proposed business share.</li><li>Check for a company payment or reimbursement already made for that month.</li><li>Record reviewer approval, the approved amount and payment reference.</li><li>Resolve any difference between an advance and the substantiated amount.</li></ol>
<p>At year-end, compare approved claims with the reimbursement ledger and payroll treatment. Keep direct business charges and reimbursements separate enough to detect duplicates. If the business deducted a cost elsewhere, have the preparer reconcile the treatment before filing.</p>
<h2>Keep the owner’s direct deduction question separate</h2>
<p>A sole proprietor paying for a business connection needs a direct expense and allocation analysis rather than assuming an employee reimbursement to themself. Return to the <a href="/blog/can-my-business-pay-for-my-cell-phone-and-internet/">business phone and internet deduction overview</a> for that starting point. A company-provided phone has separate guidance covered in the <a href="/blog/business-employee-cell-phone/">employer phone guide</a>.</p>''',
faqs=[('Can the company reimburse the whole home internet bill?','<p>Do not assume the whole household bill qualifies. Review the business need, personal or bundled services, allocation support and reimbursement arrangement.</p>'),('Is an internet allowance the same as a phone benefit?','<p>No. The payment should be evaluated under the rules and facts applicable to internet reimbursement. A phone-benefit conclusion cannot simply be copied.</p>')])
]

def main():
    for p in POSTS:
        target=T.ROOT/p['path'].strip('/')/'index.html'
        previous=target.read_text()
        preserved=re.findall(r'<!-- commercial-owner-path -->.*?<!-- /commercial-owner-path -->',previous,re.S)
        trail=[('Home','/'),('Blog','/blog/'),(p['title'],p['path'])]
        body=T.page_header(h1=p['title'],subtitle='Practical expense decisions for business owners.',trail=trail)
        body+=T.section('The short answer',T.definition(T.esc(p['lead']))+f'<p>By AE Tax Advisors Team · Published <time datetime="{p["published"]}">{p["published"]}</time> · Updated <time datetime="{DATE}">September 26, 2026</time></p>'+p['body'])
        body+=T.faq_section(p['faqs'])
        body+=T.section('Sources and scope','<ul>'+''.join(f'<li><a href="{url}">{label}</a></li>' for url,label in p['sources'])+'</ul><p>Sources checked September 26, 2026. Examples are hypothetical and do not establish an approved allocation or a conclusion about your return. <a href="/editorial-policy/">Editorial policy</a>.</p>')
        body+=''.join(preserved)
        body+=T.related_section([(q['path'],q['title']) for q in POSTS if q['path']!=p['path']]+[('/business-owner-tax-planning/','Business owner tax planning'),('/tax-return-mistakes/','Review business return mistakes')])
        schemas=[T.article_schema(title=p['title'],description=p['description'],url=T.SITE+p['path'],published=p['published'],modified=DATE,section='Business Deductions',citations=[s[0] for s in p['sources']]),T.breadcrumb_schema(trail),T.faq_schema(p['faqs'])]
        target.write_text(T.build_page(title=p['title']+' | AE Tax',description=p['description'],path=p['path'],body=body,schemas=schemas,published=p['published'],modified=DATE))
    config_path=T.ROOT/'vercel.json';config=json.loads(config_path.read_text())
    config['redirects']=[r for r in config['redirects'] if r['source']!=LEGACY]
    config['redirects'].insert(0,{'source':LEGACY,'destination':OVERVIEW,'statusCode':301})
    config_path.write_text(json.dumps(config,indent=2)+'\n')
    # A canonical fallback for non-Vercel static previews; production uses the 301.
    (T.ROOT/LEGACY.strip('/')/'index.html').write_text(f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Business Phone and Internet Guide Has Moved | AE Tax</title><meta name="description" content="Read the updated business owner phone and internet expense guide."><meta name="robots" content="noindex, follow"><link rel="canonical" href="{T.SITE}{OVERVIEW}"></head><body><main><h1>Business phone and internet guide</h1><p><a href="{OVERVIEW}">Read the current business phone and internet deduction guide</a>.</p></main></body></html>\n')
    changed=0
    for target in T.ROOT.rglob('*.html'):
        original=target.read_text();updated=original.replace('href="'+LEGACY+'"','href="'+OVERVIEW+'"')
        if original!=updated:target.write_text(updated);changed+=1
    print('Rebuilt 3 focused guides, consolidated 1 duplicate, updated direct links in',changed,'files')

if __name__=='__main__':main()
