#!/usr/bin/env python3
"""Build 100 focused real estate and business tax explainers.

Each row carries a distinct fact pattern, decision, evidence request, and failure mode.
The shared renderer supplies site chrome; this file owns editorial content.
"""
from __future__ import annotations

import html
import re
from pathlib import Path

import seo_render
import site_template as template

seo_render.BASE = "https://www.aetaxadvisors.com"


META_DANGLING = {
    "a", "an", "the", "and", "or", "but", "of", "to", "in", "on", "at",
    "by", "for", "from", "with", "without", "that", "which", "as", "when",
}


def meta_description(answer: str, limit: int = 155) -> str:
    """Shorten an answer without publishing a sentence fragment."""
    if len(answer) <= limit:
        return answer
    clause_cuts = [m.start() for m in re.finditer(r"[;,](?=\s|$)", answer[:limit + 1])
                   if 85 <= m.start() <= limit]
    if clause_cuts:
        return answer[:clause_cuts[-1]].rstrip(" ,;:-.") + "."
    cut = answer[:limit].rsplit(" ", 1)[0].rstrip(" ,;:-.")
    words = cut.split()
    while len(words) > 8 and words[-1].lower().strip(" ,;:") in META_DANGLING:
        words.pop()
    return " ".join(words).rstrip(" ,;:-.") + "..."

# slug | question | direct answer | planning decision | evidence to retain | common mistake
REAL_ESTATE = """
rental-property-security-deposit-tax|Is a rental security deposit taxable when received?|A refundable tenant deposit is generally a liability rather than rent when the landlord expects to return it; an amount kept for unpaid rent or damage becomes income when retained.|Reconcile the deposit ledger to the lease at move-out and distinguish withheld rent from reimbursement for damage before posting income and expenses.|Keep the signed lease, deposit receipt, itemized deductions, move-out photos, and refund confirmation.|Treating every deposit as rent on receipt overstates current income; omitting a forfeited deposit understates it.
rental-property-prepaid-rent-tax|How is prepaid rent taxed to a rental owner?|Advance rent is generally included in rental income when received, even if it covers a later occupancy period; a refundable security deposit has different treatment.|Separate prepaid rent from a genuinely refundable deposit in the lease and accounting system.|Save the lease, payment dates, rent ledger, and any written allocation of lump-sum payments.|Calling nonrefundable last-month rent a security deposit does not postpone tax.
rental-property-tenant-paid-expenses|Are expenses paid by a tenant taxable to the landlord?|When a tenant pays an expense that is the landlord's obligation, the payment is generally rental income to the owner and the owner may separately deduct an eligible expense.|Read the lease to identify who legally owes the cost before recording the tenant's payment.|Retain the lease clause, vendor bill, proof of tenant payment, and the owner's expense ledger.|Netting the payment away can hide both rental income and the matching expense.
rental-property-services-in-lieu-of-rent|How are tenant services in exchange for rent taxed?|The fair market value of services a tenant provides instead of rent is generally rental income, with the related expenditure analyzed separately for deduction or capitalization.|Value the work and decide whether it was routine maintenance or a capital improvement rather than booking a zero-dollar month.|Keep the rent concession, scope of work, invoices or value estimate, and before-and-after records.|Ignoring the barter transaction or deducting an improvement immediately misstates the return.
rental-property-cancelled-lease-payment|Is a lease cancellation payment rental income?|A payment received from a tenant for cancelling a lease is ordinarily rental income to the property owner.|Identify whether the payment is for lost rent, property damage, or another claim, because related expenses may be treated differently.|Retain the original lease, termination agreement, payment statement, and correspondence describing the claim.|Labelling a settlement as damages does not by itself determine the federal tax character.
rental-property-owner-paid-utilities|Can landlords deduct utilities they pay for tenants?|Utilities paid by a rental owner are generally deductible rental operating expenses when the property is held for rent; amounts reimbursed by tenants are rental income.|Allocate shared meters between rental and personal areas using a supportable measure.|Keep utility bills, reimbursement ledger, meter data, and allocation worksheet.|Deducting the full bill for a partly personal property ignores the personal-use portion.
rental-property-vacancy-expenses|Can you deduct expenses while a rental sits vacant?|Ordinary expenses may remain deductible while a property is vacant if it is genuinely held out for rent; personal use and improvements require separate analysis.|Document the marketing period and the date the unit was ready and available to rent.|Keep listings, inquiries, agent agreement, insurance, bills, and a vacancy calendar.|A property held for future personal use is not automatically a rental simply because it is empty.
rental-property-placed-in-service-date|When does rental-property depreciation start?|Depreciation begins when the property is ready and available for its intended rental use, not necessarily when a tenant first moves in or when the purchase closes.|Pin down the date repairs ended and active rental marketing began; separate later improvements into their own placed-in-service dates.|Keep dated listings, inspection records, contractor completion invoices, and lease applications.|Starting depreciation on closing day while major renovations prevent occupancy can accelerate it improperly.
rental-property-land-value-allocation|How do you split a rental purchase between land and building?|Land is not depreciable, so the purchase price and qualifying acquisition costs must be allocated between land and depreciable improvements on a reasonable basis.|Compare the appraisal, assessor values, and transaction evidence rather than copying a generic percentage.|Retain the settlement statement, appraisal, assessor allocation, and a written basis calculation.|Assigning all purchase price to the building overstates depreciation and creates future recapture exposure.
rental-property-closing-costs-basis|Which rental-property closing costs add to basis?|Costs directly tied to acquiring the property generally add to basis; loan costs and prorated operating items may receive different treatment.|Classify each settlement line instead of capitalizing the entire closing statement or deducting it all.|Keep the closing disclosure, loan documents, invoices, and basis schedule by asset.|Lender charges, title costs, escrow deposits, and prepaid taxes do not all follow one rule.
rental-property-loan-origination-fees|How are loan origination fees on a rental deducted?|Borrowing costs are generally recovered over the loan term rather than treated as the building's depreciable basis or a full current deduction.|Separate acquisition costs from financing charges and track refinancing or early payoff events.|Save loan disclosures, amortization schedule, payoff statement, and refinancing documents.|Putting financing costs into building basis can defer or distort the deduction.
rental-property-mortgage-points|Can rental-property mortgage points be deducted at closing?|Points on a loan for rental property are generally spread over the loan term, unlike the limited immediate deduction sometimes available for a principal residence.|Determine the term and whether the payment truly represents prepaid interest.|Retain the settlement statement, note, amortization worksheet, and payoff records.|Applying the personal-home point rule to an investment property can produce an early deduction.
rental-property-replacement-roof|Is a replacement roof on a rental an expense or improvement?|Replacing a roof is generally a capital improvement recovered through depreciation; isolated repairs to a small damaged area can differ.|Compare the work with the building's roof unit of property and consider any remaining basis in the disposed old component.|Keep contractor scope, photographs, invoice detail, and the fixed-asset ledger.|Describing a complete roof replacement as a repair does not change its substance.
rental-property-appliance-replacement|How do landlords depreciate replacement appliances?|A separately identifiable appliance placed in a rental may have a different recovery period from the building; the acquisition and placed-in-service facts determine treatment.|Track appliances separately and review applicable expensing elections rather than merging every purchase into building basis.|Keep itemized invoices, delivery date, asset location, and disposal record for the replaced appliance.|Losing the asset-level records can cause duplicate depreciation after a replacement.
rental-property-fence-depreciation|Is a new fence on a rental property deductible immediately?|A new fence is generally a land improvement that must be capitalized and depreciated under its applicable class rather than deducted as ordinary maintenance.|Distinguish a new installation from repairing an existing section and identify the area used for rental activity.|Retain site plan, work order, invoice, and placed-in-service evidence.|Treating every outdoor project as a nondeductible land cost can also miss allowable depreciation.
rental-property-driveway-improvement|How is a new rental-property driveway depreciated?|A newly installed or substantially improved driveway is generally a depreciable land improvement, while routine patching may be a repair.|Identify whether the work restored the existing surface or created a new or materially better one.|Keep before-and-after photos, contractor scope, cost detail, and date opened for use.|A single invoice labelled paving cannot settle the repair-versus-improvement question.
rental-property-landscaping-basis|Can a landlord depreciate landscaping costs?|Certain land improvements such as landscaping features may be depreciable, while the underlying land itself is not; classification depends on the asset created.|Separate grading integral to a building, removable landscaping, and routine maintenance before assigning recovery periods.|Retain plans, itemized bills, photographs, and asset schedule.|A blanket land allocation can miss depreciable improvements or depreciate nondepreciable land.
rental-property-casualty-insurance-proceeds|How are rental insurance proceeds handled after damage?|Insurance recovery and the property's adjusted basis must be compared; a casualty loss, gain, repair deduction, or basis adjustment can result depending on facts.|Model the damaged component, proceeds, deductible, and restoration costs before booking the settlement.|Keep the insurer's adjustment, repair estimates, checks, photographs, and pre-loss basis records.|Deducting the full repair bill while ignoring the insurance recovery can double-count a loss.
rental-property-condemnation-proceeds|What happens when rental land is condemned?|A condemnation can create a taxable gain or loss, with possible deferral under involuntary conversion rules if qualifying replacement property is acquired on time.|Identify the property taken and the statutory replacement period before committing proceeds to another investment.|Keep the condemnation award, appraisal, adjusted-basis allocation, and replacement closing documents.|Assuming every government payment is ordinary rent overlooks gain and replacement-property rules.
rental-property-property-tax-proration|Who deducts prorated property taxes at a rental closing?|Real property taxes at a sale are generally allocated between buyer and seller according to the period of ownership, even when one party remits the bill.|Reconcile the closing statement to the local tax period and distinguish taxes from transfer fees or assessments.|Keep the tax bill, closing disclosure, and allocation worksheet.|Using only the cash paid at closing may assign the seller's tax to the buyer.
rental-property-special-assessment|Is a street or sewer assessment on a rental deductible?|A local assessment for a specific property improvement generally increases basis; a charge for ordinary maintenance may be deductible as a rental expense.|Read the assessment notice to identify the improvement and any separately stated maintenance or interest.|Keep the municipal notice, payment schedule, and basis entry.|Booking every municipal charge as property tax ignores capital assessments.
rental-property-hoa-dues|Are HOA fees on a rental property deductible?|Regular association dues related to an income-producing rental are generally operating expenses; a special assessment for a capital project may need capitalization.|Request the association's explanation of how a special assessment will be spent.|Retain HOA statements, budget, project notice, and rental-use calendar.|A roof replacement funded through an HOA assessment does not automatically become a routine dues deduction.
rental-property-owner-travel|When is travel to manage a rental deductible?|Travel must have a genuine rental business purpose and be substantiated; mixed personal trips require allocation, and improvements may require capitalization of related costs.|Plan and document the work done at each property before deciding how to allocate transportation and lodging.|Keep dated itinerary, mileage log, receipts, work orders, and property communications.|A vacation with a brief property visit does not convert the whole trip into a rental expense.
rental-property-mileage-between-properties|Can landlords deduct mileage between rental properties?|Transportation between rental activities may be deductible when tied to rental operations, subject to the applicable vehicle and substantiation rules.|Track trips by destination and purpose, and distinguish commuting or personal errands.|Keep contemporaneous mileage, maintenance appointments, tenant messages, and total annual mileage.|A year-end estimate from a map is weaker than a trip-by-trip log.
rental-property-home-office-management|Can a landlord claim a home office for rental management?|A dedicated management space may qualify only if the business-use-of-home tests are met; rental activity alone does not automatically satisfy them.|Assess exclusive and regular use and whether the rental operation qualifies under the relevant trade-or-business standard.|Keep a floor plan, photos, expense records, and activity calendar.|Occasional bookkeeping at a kitchen table does not establish exclusive use.
rental-property-paid-property-manager|Does using a property manager affect rental tax losses?|Management fees are generally rental expenses, but outsourcing operational work may leave an owner without enough participation for certain passive-loss exceptions.|Separate expense treatment from the distinct question of whether the owner materially participates.|Keep the management contract, invoices, owner work log, and activity grouping records.|Claiming the manager's hours as the owner's own participation is not permitted.
rental-property-co-owner-expense-sharing|How do co-owners split rental income and deductions?|Co-owners generally report their shares of rental income and expenses based on beneficial ownership and actual arrangements; a joint venture may require partnership analysis.|Reconcile title, contributions, cash distributions, and who actually bears liabilities before preparing separate returns.|Keep deed, co-ownership agreement, bank statements, and annual settlement schedule.|Splitting everything 50/50 when ownership and economics differ can misstate both returns.
rental-property-gifted-property-basis|What is the tax basis of a gifted rental property?|A donee's basis often carries over from the donor, with special rules for property received at a loss and for gift tax paid; fair market value alone is not the default.|Obtain the donor's original cost, improvements, depreciation, and gift-date valuation before claiming deductions.|Keep gift documents, donor depreciation schedule, appraisals, and Form 709 if filed.|Resetting depreciation basis to market value at the gift date generally overstates deductions.
rental-property-inherited-basis|How does inherited rental-property basis work?|Inherited property's basis is generally tied to date-of-death value, subject to applicable estate and alternate-valuation rules; a new depreciation schedule may begin when held for rent.|Separate inherited land and building values and account for any estate-level valuation choice.|Keep estate inventory, appraisal, probate records, and rental placed-in-service evidence.|Continuing the decedent's depreciation schedule without examining the new basis can miss or overstate deductions.
rental-property-converted-home-basis|What basis applies when a home becomes a rental?|For depreciation after a personal residence converts to rental use, the starting basis is generally the lower of adjusted basis or fair market value at conversion, excluding land.|Establish conversion-date value and accumulated improvements before computing depreciation.|Keep appraisal or comparable sales, historic purchase and improvement records, and first rental listing.|Using today's market value after a decline can create depreciation the tax rules do not allow.
rental-property-converted-to-personal-use|What happens when a rental becomes a personal home?|Rental expenses and depreciation end when the property is no longer held for income production; basis and depreciation history remain relevant to a later sale.|Set a documented conversion date and separate expenses incurred before and after it.|Keep move-in records, listing withdrawal, depreciation schedules, and annual use calendar.|Continuing Schedule E deductions after permanent personal conversion is a common error.
rental-property-partial-personal-use|How do you allocate expenses for a partly personal rental?|A property used both personally and for rent requires allocation of shared costs; vacation-home limits can apply when personal use exceeds statutory thresholds.|Count personal and rental days accurately and identify direct expenses that belong entirely to one use.|Keep reservation calendar, owner-use dates, utility bills, and allocation worksheet.|Ignoring family use or treating a below-market rental as a market rental can change the allowed deduction.
rental-property-family-below-market-rent|Is a rental to family at below-market rent a rental activity?|Renting to a family member below fair rental value can be treated as personal use for vacation-home rules, limiting rental deductions.|Compare the charged rent with comparable market terms and document whether the family member uses the home as a principal residence.|Keep comparable listings, signed lease, payments, and occupancy calendar.|A signed lease alone does not make a discounted family arrangement arm's-length.
rental-property-airbnb-cleaning-fees|Are cleaning fees on short-term rentals taxable income?|Guest cleaning fees are generally receipts of the rental activity; payments to cleaners are separately analyzed as expenses.|Reconcile platform gross receipts to deposits and fees rather than recording only the net payout.|Keep platform statements, guest invoices, cleaner bills, and payment records.|Reporting net payouts can omit both revenue and platform expenses.
rental-property-airbnb-occupancy-taxes|How should short-term rental occupancy taxes be recorded?|The treatment depends on whether the tax is imposed on the host or collected from the guest as an agent for the taxing authority; platform remittance adds another layer.|Read the local ordinance and platform statement before classifying tax collected and paid.|Keep platform tax reports, jurisdiction rules, filings, and bank reconciliation.|Counting pass-through tax as revenue without the remittance, or omitting a host tax obligation, distorts results.
rental-property-short-stay-average-period|How is average guest stay measured for short-term rental passive rules?|The average customer use period is based on actual rental periods and can affect whether the activity is classified as a rental activity under Section 469 regulations.|Calculate a weighted average from all stays rather than looking only at the shortest reservation.|Keep booking exports showing arrival and departure dates, cancellations, and owner-use days.|A listing advertised for short stays does not prove the actual average use period.
rental-property-short-stay-services|When do services turn a short-term rental into a different tax activity?|Substantial services primarily for guest convenience can change how an accommodation activity is reported and may affect self-employment tax; routine cleaning between stays differs.|List services delivered during occupancy and compare them with ordinary lodging or hotel services.|Keep service menus, staffing records, guest messages, and revenue by service.|Assuming every short-term rental belongs on Schedule E can be wrong when hotel-like services are provided.
rental-property-guest-damage-fees|Are guest damage charges rental income?|Amounts retained from guests for damage may be rental receipts, while the repair, insurance, and basis consequences need separate analysis.|Reconcile claims from platform protection programs with actual restoration costs and any capitalized replacement.|Keep incident photos, guest charge, platform settlement, and contractor invoices.|Netting a damage reimbursement against a capital improvement may hide both transactions.
rental-property-lease-option-payment|How is an option payment on rental real estate taxed?|A genuine option payment is usually held for later characterization: it may enter the sale proceeds if exercised or become income if the option expires.|Review whether the agreement is truly an option or an installment sale in substance.|Keep the signed option, payment schedule, exercise notice, and settlement statement.|Immediately treating every option payment as ordinary rent can be premature.
rental-property-lease-purchase-rent-credit|How do rent credits in a lease-purchase arrangement work?|Amounts called rent may partly function as purchase consideration when they are credited toward a binding purchase; the contract's economics matter.|Separate fair-market rent from the purchase-credit portion and examine whether benefits and burdens transferred early.|Keep the lease-option agreement, fair-rent comparables, payment ledger, and final closing statement.|The contract label cannot override an arrangement that operates like a sale.
rental-property-abandoned-tenant-property|Can a landlord deduct abandoned tenant property cleanup?|Reasonable cleanup after a tenant leaves may be an operating expense, while replacement or restoration of a major component can be capital.|Separate debris removal, minor repair, and new asset costs in contractor billing.|Keep move-out report, dated photos, itemized invoices, and insurance settlement.|Combining renovation and cleanup on one invoice encourages an unsupported current deduction.
rental-property-eviction-legal-fees|Are eviction legal fees deductible for a rental?|Legal fees tied to collecting rent or removing a tenant are generally rental operating expenses; fees to acquire or defend title may be capital.|Ask counsel to itemize work by claim when litigation has both operating and title issues.|Keep pleadings, engagement letter, itemized invoices, and settlement allocation.|Deducting a title defense as ordinary eviction expense can be improper.
rental-property-uncollectible-rent|Can a landlord deduct unpaid rent that was never received?|A cash-method landlord generally has no bad-debt deduction for rent never included in income; an accrual-method landlord may face a different analysis.|Confirm accounting method and whether the unpaid amount was previously reported as taxable income.|Keep ledger, lease, collection records, and prior return treatment.|Claiming both no rental income and a bad-debt deduction for the same unpaid cash rent double-counts the loss.
rental-property-refinance-cash-out|Is cash-out refinancing of a rental property taxable income?|Loan proceeds normally are not income because they must be repaid; interest deductibility can depend on how the borrowed funds are used.|Trace the cash from refinance proceeds to each use before assigning interest to rental, investment, or personal categories.|Keep closing statement, wire trail, account transfers, and purchase or expense receipts.|Assuming all interest is a rental deduction because the rental secured the loan ignores tracing rules.
rental-property-heloc-interest-tracing|Can rental owners deduct HELOC interest used for property costs?|Interest treatment generally follows the use of borrowed proceeds, not simply the property that secures the debt.|Maintain a separate account or clear tracing ledger for advances spent on the rental and other purposes.|Keep draws, bank transfers, invoices, and loan interest statements.|Mixing personal and rental spending in one revolving line makes the deduction hard to support.
rental-property-loss-sale-to-relative|Can you claim a loss when selling a rental to family?|A loss on a sale to a related person may be disallowed even when the property was genuinely rented and sold for fair value.|Identify the buyer's relationship and model gain or loss before signing the contract.|Keep deed, appraisal, related-party facts, and adjusted-basis schedule.|A fair-market appraisal does not remove statutory related-party loss restrictions.
rental-property-sale-depreciation-allowed|What if you failed to claim rental depreciation before selling?|Gain calculations generally reflect depreciation allowed or allowable, including depreciation that could have been claimed; omitted deductions do not simply disappear at sale.|Reconstruct the asset schedule and ask whether an amended return or accounting-method correction is appropriate.|Keep original returns, placed-in-service evidence, basis records, and sale closing statement.|Using unreduced original cost as sale basis because depreciation was missed understates gain.
rental-property-installment-sale-depreciation|Can depreciation recapture be spread with an installment sale?|Depreciation recapture under Section 1245 and certain Section 1250 rules may be recognized in the year of sale even when sale payments arrive later.|Project the immediate tax cash requirement before agreeing to seller financing.|Keep asset-by-asset depreciation, installment note, allocation schedule, and closing disclosure.|Assuming all tax follows the note payments can create an unexpected first-year bill.
rental-property-selling-costs-gain|Do real-estate commissions reduce taxable gain on a rental sale?|Selling expenses generally reduce amount realized in computing gain or loss, but loan payoff is repayment of debt rather than a selling expense.|Build the sale worksheet from gross price, eligible selling costs, adjusted basis, and debt separately.|Keep settlement statement, broker agreement, and depreciation schedule.|Subtracting mortgage payoff as a tax cost understates taxable gain.
rental-property-rent-concession-tax|How does a free-rent concession affect rental income?|A landlord using the cash method generally reports rent actually received; a negotiated free month does not create cash income, while related expenses still require normal analysis.|Record the concession in the signed lease and reconcile scheduled rent to actual receipts.|Keep the lease amendment, tenant ledger, bank deposits, and marketing offer.|Recording contract rent that was expressly waived can overstate taxable receipts.
"""

BUSINESS = """
business-customer-deposits-tax|Are customer deposits taxable to a small business?|An advance payment can be income when received, while a genuinely refundable deposit held as security may be a liability; method of accounting and contract terms matter.|Separate deposits that will be applied to price from refundable security balances in the ledger.|Keep customer contract, refund terms, invoices, payment dates, and reconciliation.|Calling every advance a deposit cannot defer tax when it is actually payment for services.
business-gift-card-revenue-timing|When does a business recognize gift-card sales for tax?|Gift-card proceeds are advance payments; the available deferral rules depend on accounting method, applicable election, and recognition in financial statements.|Reconcile sales, redemptions, breakage, and refunds before choosing a tax treatment.|Keep card-level liabilities, redemption history, terms, and financial-statement policy.|Leaving unredeemed balances off every tax return indefinitely is not a valid default.
business-refunds-returns-tax|How do customer refunds affect business taxable income?|Refunds, returns, and allowances reduce sales when properly recorded, subject to the business's accounting method and the timing of the original sale.|Reconcile processor chargebacks to invoices so refunded sales are not counted twice.|Keep original receipt, refund authorization, bank evidence, and sales ledger.|Deducting a refund as a separate operating cost while leaving an incorrect gross sale can obscure the books.
business-sales-tax-collected|Is sales tax collected from customers business income?|Sales tax collected as an agent for the state is generally a liability rather than business revenue; taxes imposed directly on the seller can differ.|Read the state rule and reconcile gross processor deposits to net sales and remittances.|Keep taxable-sales report, returns, payment confirmations, and platform withholding statements.|Treating a marketplace's remitted tax as both the seller's income and expense inflates turnover.
business-credit-card-cashback-tax|Is business credit-card cash back taxable?|A rebate tied to purchases often reduces the cost or basis of those purchases rather than being separate taxable income; promotional awards can differ.|Allocate rewards to the underlying expense or asset when material, especially large equipment purchases.|Keep card rewards statement and purchase ledger.|Deducting the full purchase cost and ignoring a substantial rebate overstates cost.
business-barrier-to-cash-method|When must a business use accrual rather than cash accounting?|Accounting-method eligibility depends on entity type, inventory activity, and the applicable gross-receipts tests and exceptions.|Review receipts over the required measurement period before changing methods or filing a new entity return.|Keep prior returns, gross-receipts worksheet, inventory records, and method-election history.|Switching methods in the books without a required tax accounting-method change can create a mismatch.
business-unpaid-invoices-cash-basis|Can a cash-basis business deduct unpaid customer invoices?|A cash-method business generally does not recognize an unpaid invoice as income and therefore generally has no bad-debt deduction when it goes uncollected.|Confirm whether any part was previously reported, such as a deposit or a prior-year receipt.|Keep invoice history, payment record, and tax method documentation.|Deducting an invoice never included in taxable income claims a loss that never arose for tax purposes.
business-bad-debt-accrual-method|When can an accrual-method business deduct a bad debt?|An accrual-method business may deduct a bona fide receivable previously included in income when it becomes worthless, subject to substantiation.|Document collection efforts and the specific year the debt became uncollectible.|Keep original invoice, income recognition, correspondence, bankruptcy notice, and write-off approval.|An accounting allowance for doubtful accounts alone does not establish a tax deduction for a particular debt.
business-inventory-damaged-goods|How are damaged inventory items deducted?|Inventory losses generally affect cost of goods sold or inventory valuation under the taxpayer's adopted method; insurance reimbursements must be accounted for.|Count damaged units, document salvage value, and reconcile the book adjustment to the tax inventory method.|Keep dated count sheets, photographs, disposal evidence, and insurer statement.|Taking an additional expense after inventory already flowed through cost of goods sold double-counts cost.
business-inventory-samples-tax|Can a business deduct products given away as samples?|The cost of samples used to promote sales may be an advertising expense or move through inventory accounting, but must not be deducted twice.|Track units removed from saleable inventory and their business purpose.|Keep campaign records, unit cost, recipient log, and inventory adjustment.|Deducting retail selling price rather than tax cost exaggerates the expense.
business-inventory-owner-withdrawal|How are inventory withdrawals for personal use taxed?|Inventory taken for an owner's personal use is not a business cost of goods sold; the bookkeeping must remove that cost from deductible inventory expense.|Record withdrawals at cost and distinguish gifts to customers from personal consumption.|Keep inventory transfer log and purchase-cost support.|Leaving personal items in cost of goods sold understates business profit.
business-freight-in-inventory-cost|Is shipping paid to acquire inventory immediately deductible?|Freight-in and other acquisition costs often form part of inventory cost and are recovered as the goods are sold, subject to applicable simplified rules.|Separate inbound product freight from shipping goods to customers.|Keep vendor invoices, bills of lading, inventory costing policy, and sales dates.|Expensing all inbound freight immediately may mismatch costs with unsold inventory.
business-website-development-costs|Can a business deduct a newly built website?|Website costs can include currently deductible maintenance, capitalizable development, purchased software, and separately amortizable intangibles; scope determines treatment.|Have the developer separate design, software functions, hosting, and routine updates on invoices.|Keep contract, milestones, launch date, source ownership terms, and invoices.|One website invoice does not prove every component is an advertising expense.
business-domain-name-purchase-tax|Is the purchase of a premium domain name deductible?|A purchased domain can be a capital asset or intangible rather than a routine annual registration fee; the rights and acquisition price matter.|Distinguish recurring registration from buying an existing valuable domain and document how it is used.|Keep purchase contract, registrar transfer, fees, and business-use records.|Immediately expensing a substantial acquired domain may ignore its continuing value.
business-software-subscription-vs-license|How are SaaS subscriptions different from software purchases for tax?|Recurring access fees may be operating expenses, while acquisition of a perpetual license or custom software can require capitalization or different recovery.|Read whether the company receives access, a transferable license, or ownership of developed code.|Keep order form, service term, implementation invoice, and contract rights.|Treating all technology spending as a monthly subscription despite an acquired asset can distort timing.
business-prepaid-insurance-tax|Can a small business deduct prepaid multiyear insurance immediately?|A premium covering future years generally cannot all be deducted when paid; the coverage period and accounting rules control recovery.|Map the policy term and premium to tax years before making a year-end prepayment.|Keep policy declarations, payment receipt, and coverage schedule.|A December payment for several years of coverage is not automatically a December deduction.
business-prepaid-rent-tax|When can a business deduct rent paid in advance?|Prepaid rent generally is allocated to the period it covers, with timing rules that vary by accounting method and benefit period.|Compare the prepayment with the lease term and the applicable economic-performance and 12-month rules.|Keep lease, payment proof, and rent allocation worksheet.|Prepaying multiple years solely to reduce current tax is unlikely to yield a full immediate deduction.
business-lease-security-deposit|Is a commercial lease security deposit deductible?|A refundable lease deposit is generally an asset when paid, not current rent expense; a forfeited or applied deposit is analyzed when its status changes.|Track deposit balances separately from first and last month's rent.|Keep lease, deposit receipt, landlord statement, and termination settlement.|A ledger entry labelled rent does not turn refundable collateral into an expense.
business-tenant-improvement-allowance|How is a landlord's tenant-improvement allowance taxed?|The treatment of a construction allowance depends on lease terms, who owns the improvements, and whether a specific statutory exclusion applies.|Coordinate lease drafting with tax ownership and depreciation before work begins.|Keep executed lease, allowance clause, contractor invoices, ownership terms, and completion certificate.|Netting the allowance against all construction costs without analyzing tax ownership can be wrong.
business-commercial-lease-buyout|Can a business deduct a payment to exit a commercial lease?|A lease termination payment may be deductible or capitalized depending on whether it ends a burden, acquires another right, or is part of a relocation or asset transaction.|Identify precisely what the payment buys and its connection to a new site or business acquisition.|Keep old and new leases, settlement agreement, and itemized legal invoices.|Calling a lump-sum relocation package rent does not resolve its character.
business-trade-show-booth-costs|Are trade-show booth costs deductible?|Event fees and short-lived promotional costs may be operating expenses; a reusable booth structure or equipment can be a depreciable asset.|Separate exhibit space, travel, printed materials, and reusable equipment.|Keep event contract, asset invoices, photos, and future-use plan.|Deducting a durable display as a one-time event fee can accelerate recovery improperly.
business-promotional-giveaways-tax|Can a business deduct promotional giveaways?|Ordinary promotional items can be advertising expense, while gifts to identified recipients can trigger business-gift limits and documentation rules.|Classify mass-distributed branded items separately from valuable items given to particular clients.|Keep item costs, recipients or campaign distribution, and business purpose.|Labelling a personal gift advertising does not avoid substantiation or gift limitations.
business-referral-fees-1099|Are referral fees deductible and reportable?|A bona fide referral payment for business may be deductible, but information-reporting, licensing, and anti-kickback rules can also matter.|Confirm the service, recipient status, and reporting obligation before paying.|Keep agreement, invoice, W-9, payment evidence, and referral result.|Cash or app payments do not eliminate Form 1099 obligations where applicable.
business-contractor-reimbursement-tax|How should contractor expense reimbursements be handled?|Amounts paid to a contractor for expenses can be part of reportable compensation depending on the arrangement; the business still needs ordinary expense substantiation.|Specify whether the contractor buys supplies as agent or includes reimbursed costs in the invoice.|Keep contract, receipts, invoice breakdown, and tax information form.|Excluding every reimbursement from reporting simply because receipts were provided can be incorrect.
business-owner-reimbursement-no-accountable-plan|What happens if an S corporation reimburses owners without an accountable plan?|Without an accountable plan satisfying business connection, substantiation, and return-of-excess requirements, payments may be taxable wages rather than tax-free reimbursement.|Adopt written procedures and reconcile advances to actual expenses promptly.|Keep plan, receipts, mileage or expense logs, reimbursement requests, and payroll records.|A recurring flat allowance with no accounting is not the same as substantiated reimbursement.
business-employee-cell-phone|Can a business pay for an employee's cell phone tax-free?|Employer-provided phones primarily for noncompensatory business reasons can receive favorable fringe-benefit treatment, but cash allowances and personal arrangements need review.|Document why employees need mobile access and distinguish device provision from unrestricted extra pay.|Keep policy, role requirements, invoices, and reimbursement records.|Adding a fixed phone stipend to payroll but treating it as automatically tax-free is risky.
business-employee-home-internet|Can an employer reimburse home internet for remote work?|A substantiated business share of necessary home internet may fit an accountable plan; a blanket payment for a personal household bill needs closer review.|Choose a reasonable allocation and require employees to document the bill and business necessity.|Keep remote-work policy, bill, allocation method, and reimbursement claim.|Paying the full household bill without a business-use rationale can create taxable compensation.
business-employee-meal-overtime|Are overtime meals for employees deductible?|Meal deductions depend on business purpose, who receives the food, location, and statutory limitations; merely working late does not create unlimited tax-free meals.|Record why the employer provided the meal and apply the correct deduction and fringe-benefit rules.|Keep receipts, attendance, work schedule, and written policy.|Treating every team dinner as a fully deductible de minimis benefit ignores limitations.
business-team-event-meals|Are meals at a company-wide employee event fully deductible?|Recreational events primarily for employees may receive different deduction treatment from ordinary business meals when they satisfy the statutory requirements.|Document who attended and whether the event was primarily for rank-and-file employees rather than owners alone.|Keep invitation, attendee list, invoices, and event purpose.|An owner-only dinner cannot be reclassified as an employee recreation event by its label.
business-client-gift-vs-entertainment|Is a client experience a gift or entertainment expense?|The tax treatment of a tangible gift differs from entertainment, and separating food from event admission requires adequate billing.|Ask vendors to itemize meals separately and identify what the client actually received.|Keep invoice detail, recipient, business relationship, and event records.|Calling tickets a client gift does not convert nondeductible entertainment into a deductible gift.
business-sponsorship-vs-charity|Is a local sponsorship an advertising deduction or donation?|A payment for meaningful advertising can be a business promotion cost, while an amount paid without substantial return benefit may be a charitable contribution.|Document signage, audience, deliverables, and fair value received from the organization.|Keep sponsorship agreement, photographs, receipt, and event materials.|Assuming every nonprofit payment is a charitable gift can miss the actual advertising exchange.
business-charity-through-s-corp|How do S corporation charitable gifts reach shareholders?|An S corporation generally separately states eligible charitable contributions to shareholders, whose individual deductions can be limited by basis and personal rules.|Model owner basis and itemization before using corporate cash for a large gift.|Keep acknowledgment, Form 1120-S K-1, basis schedule, and valuation support.|Treating the gift as an ordinary business expense on the S corporation return is usually wrong.
business-business-loan-proceeds-tax|Is a bank loan taxable income for a business?|Ordinary loan proceeds are generally not taxable because the borrower has a repayment obligation; interest and financing fees receive separate treatment.|Record principal as a liability and trace borrowed funds to business or personal use.|Keep note, draw schedule, bank deposits, and use-of-funds ledger.|Booking proceeds as sales revenue and loan repayments as expenses distorts taxable profit.
business-forgiven-loan-tax|Is forgiven business debt taxable?|Cancelled debt can create income unless an exclusion or other special rule applies; the tax effect can also adjust attributes such as basis or losses.|Identify the creditor, amount discharged, insolvency status, and whether the obligation was genuinely cancelled.|Keep discharge agreement, Form 1099-C, balance sheet, and tax-attribute worksheet.|Assuming every forgiven loan is tax-free because the original proceeds were untaxed is incorrect.
business-interest-personal-guarantee|Can an owner deduct interest on a personally guaranteed business loan?|A guarantee alone does not make interest the owner's deduction; who is the borrower, who pays, and how proceeds are used all matter.|Document intercompany advances or capital contributions if the owner pays an entity obligation.|Keep note, guarantee, bank transfers, board approval, and loan tracing.|Paying the entity's bill personally without accounting for the transaction can obscure basis and deductions.
business-intercompany-loan-documentation|What records make an owner-to-business loan bona fide?|A genuine loan needs a real obligation to repay, credible terms, payment history, and consistent accounting; otherwise advances may be treated as equity or distributions.|Set interest, maturity, and repayment terms when funds move rather than after an audit begins.|Keep signed note, bank transfers, payment ledger, and corporate approvals.|A year-end journal entry called loan cannot substitute for an actual debtor-creditor relationship.
business-owner-loan-repayment-tax|Is repayment of an owner's loan from an S corporation taxable?|Return of bona fide principal is generally not income, while stated or imputed interest is income to the lender; debt basis and prior losses can complicate repayment.|Reconcile principal, accrued interest, and any debt basis reduced by prior deductions before issuing payment.|Keep original note, loan roll-forward, shareholder basis schedule, and payment detail.|Calling a distribution loan repayment after the fact can misstate both income and basis.
business-s-corp-distribution-basis|When are S corporation distributions taxable?|Nondividend S corporation distributions are generally tax-free only to the extent of stock basis, with excess potentially treated as gain; accumulated earnings can change ordering.|Update shareholder stock basis before deciding the amount of a year-end distribution.|Keep Forms 1120-S and K-1, contributions, prior losses, and distribution ledger.|Bank balance is not shareholder tax basis.
business-s-corp-loss-debt-basis|Can an S corporation owner use losses against a personal loan guarantee?|A guarantee alone generally does not create debt basis for an S corporation shareholder; an actual economic outlay or direct indebtedness is relevant.|Calculate stock basis, debt basis, at-risk amount, and passive limits in the correct order.|Keep lender documents, shareholder advances, repayments, and basis worksheet.|Claiming a pass-through loss solely because the owner signed a guarantee can overstate the deduction.
business-s-corp-shareholder-health-insurance|How is health insurance for a more-than-2-percent S corporation shareholder reported?|Premiums paid or reimbursed by the S corporation generally need proper W-2 inclusion for a more-than-2-percent shareholder before a potential above-the-line deduction is evaluated.|Coordinate payroll and plan ownership before the final payroll of the year.|Keep policy, payment evidence, W-2, and payroll entries.|Paying premiums from the company account without correct wage reporting can jeopardize the individual deduction.
business-partnership-guaranteed-payment|What is a partnership guaranteed payment for services?|A guaranteed payment is made to a partner without regard to partnership income and is generally separately reported, unlike a distributive profit share.|Draft the operating agreement to distinguish fixed service compensation from profit allocations.|Keep agreement, payment ledger, Form 1065, and each partner's K-1.|Putting a partner on ordinary employee payroll can conflict with partnership tax treatment.
business-partner-expenses-unreimbursed|Can a partner deduct expenses paid personally for a partnership?|An unreimbursed partnership expense may be deductible by a partner when the partnership agreement requires the partner to bear it and reimbursement is unavailable.|Put the expense obligation in the agreement and check whether the partnership actually offers reimbursement.|Keep signed agreement, receipts, reimbursement policy, and K-1.|Voluntarily paying an expense personally does not automatically create a partner-level deduction.
business-partnership-distribution-property|Is a partnership distribution of equipment taxable?|A property distribution is often not immediately taxable, but special rules, partner basis, liabilities, and disguised-sale provisions can change the result.|Model both the partner's outside basis and the partnership's asset basis before transferring equipment.|Keep asset ledger, fair-value support, liabilities, agreement, and basis roll-forward.|Treating a property distribution exactly like a cash draw ignores basis and asset character.
business-partnership-buyout-ordinary-income|Why is part of a partnership buyout ordinary income?|A partner's sale can produce ordinary income to the extent attributable to certain unrealized receivables or inventory, often called hot assets, even if the rest is capital gain.|Obtain an asset-level allocation and estimate Section 751 exposure before setting a headline price.|Keep valuation, receivables detail, inventory, purchase agreement, and partner basis.|Calling the entire buyout capital gain can understate ordinary income.
business-purchase-price-allocation-assets|How do buyers and sellers allocate a business purchase price?|An applicable asset acquisition generally requires allocation among asset classes, affecting buyer deductions and seller gain character.|Negotiate allocation alongside price and coordinate consistent reporting by both parties.|Keep purchase agreement, valuation, allocation workpapers, and Form 8594.|Agreeing on price while leaving allocation vague can create conflicting returns.
business-acquired-customer-list|Can a buyer deduct the cost of an acquired customer list?|A purchased customer-based intangible in a business acquisition may be subject to Section 197 amortization rather than an immediate advertising deduction.|Identify whether the list was separately purchased or part of a broader business acquisition.|Keep acquisition agreement, allocation, valuation, and rights transferred.|Expensing a durable acquired customer relationship at closing can accelerate tax recovery incorrectly.
business-sale-escrow-holdback|When is an escrow holdback from a business sale taxed?|An escrowed portion of sale proceeds can have different timing depending on whether the seller has a fixed right to funds and the escrow conditions.|Read the escrow restrictions and model each earnout, indemnity, or price-adjustment condition separately.|Keep sale agreement, escrow contract, release notices, and closing statement.|Assuming all cash withheld from the seller is automatically deferred taxable gain can be wrong.
business-sale-working-capital-adjustment|How does a working-capital true-up affect business sale tax?|A purchase-price adjustment can change amount realized or asset allocation; its character depends on the agreement and facts.|Reconcile the closing balance sheet, post-closing true-up, and any separately paid compensation.|Keep purchase agreement, target calculation, final settlement, and amended allocation.|Booking a price adjustment as ordinary consulting revenue without reviewing the contract can misclassify it.
business-sale-noncompete-payment|How are noncompete payments in a business sale taxed?|A separately bargained covenant can produce different tax character for the seller and amortization treatment for the buyer than goodwill does.|Value the covenant realistically and coordinate its allocation with the transaction documents.|Keep covenant, negotiation record, valuation, and Form 8594.|A label inserted solely for tax results is vulnerable if the covenant has no economic substance.
business-asset-sale-sales-tax|Does sales tax apply when a business sells its equipment?|State sales-tax treatment of a business asset sale varies by jurisdiction and transaction type, while federal gain is computed from proceeds and adjusted tax basis.|Check the applicable state exemption or bulk-sale rules before closing and separately calculate federal gain or loss.|Keep bill of sale, original purchase invoice, depreciation schedule, and state tax determination.|Assuming an isolated equipment sale has no state sales-tax consequence can surprise buyer and seller.
"""

# Illustrative fact patterns are written for each question, not copied from clients.
EXAMPLES = """
rental-property-security-deposit-tax|A tenant pays $2,000 at signing, and the lease requires its return after inspection. The owner records a deposit liability. At move-out, the owner keeps $300 for unpaid rent and refunds $1,700; the retained portion is evaluated as rental income in the year it is kept.
rental-property-prepaid-rent-tax|A tenant pays January rent in December to avoid a late payment during travel. The cash-method landlord includes the amount in the December tax year, even though the tenant occupies the unit in January. The lease and payment ledger should show that this was rent rather than refundable security.
rental-property-tenant-paid-expenses|A lease requires the owner to pay the water bill, but a tenant pays the utility directly after a shutoff warning. The owner should not simply omit the transaction because no money entered the owner's bank account. The payment and corresponding qualifying expense need separate entries.
rental-property-services-in-lieu-of-rent|A tenant paints the unit in exchange for one month's rent. The owner records the fair value of the rent concession and evaluates the painting cost under the repair and improvement rules. A written change order and comparable contractor price make the valuation easier to support.
rental-property-cancelled-lease-payment|A commercial tenant pays a negotiated amount to surrender the space six months early. The settlement agreement should distinguish the release payment from reimbursement for broken fixtures. The owner then analyzes the receipt in the year received and separately records any restoration work.
rental-property-owner-paid-utilities|An owner pays one electric meter serving a rented basement and the owner's living quarters. The full bill is not a rental expense. A reasonable allocation based on separate submeters, square footage, or another documented measure gives the preparer a defensible rental portion.
rental-property-vacancy-expenses|An apartment is empty for seven weeks between tenants, but the owner advertises it throughout and schedules showings. Insurance and ordinary upkeep may remain rental expenses during the gap. Renovations that make the unit unavailable for rent need their own capitalization and placed-in-service review.
rental-property-placed-in-service-date|A buyer closes on a duplex in March, replaces unsafe wiring through May, and first advertises it for rent in June. The owner should not begin building depreciation merely because title transferred in March. Dated contractor completion and listings establish when it became ready and available.
rental-property-land-value-allocation|An investor buys a house and lot for a single price. The land remains nondepreciable even though the entire purchase is financed. The owner compares a contemporary appraisal and assessor data, allocates acquisition costs consistently, and begins depreciation only on the building and eligible separate improvements.
rental-property-closing-costs-basis|A closing disclosure includes title insurance, lender origination charges, escrowed taxes, and prepaid insurance. The buyer should map each line to acquisition basis, financing cost, or a current or prepaid operating item. A single journal entry to building basis conceals those different recovery periods.
rental-property-loan-origination-fees|A landlord pays a lender fee to obtain a ten-year rental mortgage, then refinances in year four. The unamortized borrowing cost may need to be addressed at payoff; it is not simply part of the building's depreciation schedule. Retaining both loan statements is essential.
rental-property-mortgage-points|An investor pays points to lower the rate on a loan secured by a rental condo. Even if the closing statement calls them discount points, the rental-property timing rules differ from the familiar principal-residence exception. The lender documents and loan term control the schedule.
rental-property-replacement-roof|A contractor removes the entire aging roof and installs new materials. That project is substantially different from patching a small leak after a storm. The owner capitalizes the new roof as appropriate and asks whether a disposition deduction is available for any remaining basis of the old roof.
rental-property-appliance-replacement|A landlord replaces a broken refrigerator in one apartment and removes the old unit. The new refrigerator should be separately tracked with its own cost and in-service date. The old asset should be removed from the fixed-asset schedule if its remaining tax basis is disposed of.
rental-property-fence-depreciation|A property owner builds a new perimeter fence for a rented house. The cost is not the price of the underlying land and is not a routine patch to an existing fence. Invoices that separate posts, gates, and related work support an asset-level depreciation decision.
rental-property-driveway-improvement|One owner fills potholes in an existing rental driveway; another tears it out and installs a wider concrete surface. The projects have different facts under the improvement rules. Contractor scopes and before-and-after photos show whether the work merely maintained the old surface or created a new asset.
rental-property-landscaping-basis|A landlord pays for mowing and seasonal cleanup, then installs a permanent irrigation system. The recurring service and new system do not share one tax treatment. Itemized invoices let the owner distinguish maintenance from a depreciable improvement and keep land itself out of the depreciation schedule.
rental-property-casualty-insurance-proceeds|A pipe bursts, and an insurer pays for floor restoration after applying a deductible. The owner records the damaged asset's basis, insurance proceeds, and restoration invoices rather than claiming the contractor's full bill in isolation. New upgraded flooring may also have a different treatment from repair work.
rental-property-condemnation-proceeds|A city takes a strip of a rental lot to widen a street and pays the owner an award. The owner allocates basis to the part taken and reviews whether reinvestment qualifies for gain deferral. Depositing the award into a bank account alone does not establish its tax treatment.
rental-property-property-tax-proration|A rental sale closes halfway through a local property-tax year, and the seller credits the buyer on the settlement statement. The tax return allocation should follow the period of ownership, not just the person who later sends the county a check. Transfer charges need a separate classification.
rental-property-special-assessment|A town bills owners for a new sewer connection and separately charges for annual sewer maintenance. The owner should capitalize the improvement portion as appropriate and evaluate the recurring charge as an operating cost. The municipal notice is better evidence than the payment memo alone.
rental-property-hoa-dues|A condo association bills monthly dues and a separate assessment for replacing the building roof. The monthly operating charge and roof project should be reviewed separately, even though both are paid to the same association. The board's project notice explains what the special payment funded.
rental-property-owner-travel|An out-of-state owner spends three days inspecting two rentals and four days visiting family. Contemporaneous notes of inspections, meetings, and mileage support only the business portion of the trip. The fact that a rental was visited does not make every airfare, meal, and hotel night deductible.
rental-property-mileage-between-properties|A landlord drives from one managed rental to another to meet a plumber, then stops for personal shopping. The rental leg should be recorded with date, distance, and purpose. A single annual estimate based on the number of properties cannot show which miles were business miles.
rental-property-home-office-management|An owner uses a separate room exclusively to run a large rental operation and keeps records there; another works occasionally at a kitchen counter. Exclusive use differs in the two cases. The owner must still establish the other requirements before claiming home-office costs.
rental-property-paid-property-manager|A manager collects rent, handles maintenance, and arranges tenants while the owner reviews monthly statements. The fee is a rental expense, but the manager's work does not count as the owner's participation hours. The owner should maintain a separate log of genuine operational work.
rental-property-co-owner-expense-sharing|Two siblings own a duplex in unequal shares, and one pays the entire insurance bill. Their returns should reflect the ownership and economic arrangement rather than a reflexive equal split. A year-end settlement worksheet can reconcile direct payments, distributions, and each person's share.
rental-property-gifted-property-basis|A parent gives an adult child a rental bought years ago and later improved. The child cannot simply depreciate the property's current market value. The donor's cost, improvements, prior depreciation, and gift-date value must be assembled before creating a new schedule.
rental-property-inherited-basis|An heir receives a rented house with a prior depreciation history. The heir should obtain estate valuation records and allocate the inherited basis between building and land. Carrying forward the decedent's old building basis without review can misstate both future depreciation and gain on sale.
rental-property-converted-home-basis|A homeowner moves out and rents a house after its value has fallen below adjusted cost. For depreciation, the lower fair-market-value rule may apply at conversion. A dated appraisal and the home's purchase and improvement history allow the preparer to calculate the correct starting basis.
rental-property-converted-to-personal-use|A landlord stops advertising a rental and moves into it permanently in July. Schedule E expenses should be separated before and after conversion, while depreciation taken through the rental period remains part of the later sale calculation. The move date needs more support than a verbal estimate.
rental-property-partial-personal-use|An owner rents a lake cabin for part of the summer and reserves weekends for family. The expense allocation depends on actual rental and personal days and on whether the vacation-home thresholds apply. A booking calendar should include family stays, not just paid reservations.
rental-property-family-below-market-rent|A parent charges an adult child half of comparable market rent for a vacation property. The arrangement may create personal-use days for federal tax purposes despite a signed lease. Nearby rental listings and evidence of the child's residence clarify the fair-rent and usage analysis.
rental-property-airbnb-cleaning-fees|A booking platform charges a guest $175 for cleaning, withholds its platform fee, and remits a smaller net amount to the host. The host reconciles gross guest charges and separately records cleaner and platform costs. Recording only the bank deposit understates receipts and expenses.
rental-property-airbnb-occupancy-taxes|A platform collects local lodging tax from guests and remits it directly to the city. The host checks whether that tax legally belongs to the host or was collected solely as an agent. Platform reports and local filings should agree before the amount is included or excluded from receipts.
rental-property-short-stay-average-period|A property has many two-night bookings and several month-long stays. The owner calculates average customer use from actual stay records rather than relying on the listing's minimum-night setting. A few long stays can materially affect the average and therefore the passive-activity classification.
rental-property-short-stay-services|One host provides keys and cleans only between stays; another supplies daily housekeeping, breakfast, and concierge service during occupancy. The services differ for tax classification. The owner should describe what guests actually received, not just the platform used to collect reservations.
rental-property-guest-damage-fees|A guest breaks a door, and the platform transfers a damage payment to the host. The owner records that receipt and examines whether replacing the door is a repair or part of a larger renovation. Photos and the platform's claim detail link the payment to the work.
rental-property-lease-option-payment|A prospective buyer pays an owner for a one-year option to buy a rental. If the option is exercised, the payment may become part of the sale transaction; if it expires, the treatment changes. The agreement should state when and how the option payment applies.
rental-property-lease-purchase-rent-credit|A tenant pays above-market monthly amounts, with part credited toward a required purchase price. The owner needs to determine whether the agreement remains a lease with an option or has shifted benefits and burdens of ownership. Comparable market rent and contract terms make the distinction concrete.
rental-property-abandoned-tenant-property|A tenant leaves furniture and trash behind after moving out, and the landlord also upgrades the kitchen. Disposal and cleanup costs should be separated from the new cabinets and appliances. An itemized contractor invoice prevents the whole job from being assigned one treatment.
rental-property-eviction-legal-fees|An attorney handles an eviction for unpaid rent and also resolves a dispute over title to a parking parcel. The two services may have different tax character. Detailed legal billing lets the owner separate operating litigation from costs that protect or acquire a property interest.
rental-property-uncollectible-rent|A cash-method landlord invoices a tenant for three months but receives no payment. Because those amounts were not included in income, writing off the unpaid ledger balance does not create another tax deduction. Related court and collection costs are separate questions.
rental-property-refinance-cash-out|An owner borrows against an apartment building and uses half the proceeds for a new rental and half for a personal vacation. The loan itself generally is not income, but interest cannot all be assigned to the original building. A clear funds trail identifies the different uses.
rental-property-heloc-interest-tracing|A landlord draws from a HELOC secured by a rental, using one advance for roof work and another for a personal car. The collateral is the same, but the interest allocation follows use of proceeds. Separate draws and bank transfers make that tracing possible.
rental-property-loss-sale-to-relative|An investor sells a rental at a loss to a sibling. Even with an appraisal and real payment, related-party loss limitations may prevent a current deduction. The relationship should be identified before closing so price, basis, and possible future consequences can be modeled.
rental-property-sale-depreciation-allowed|A landlord never claimed building depreciation and later sells the property. The sale computation still takes allowed-or-allowable depreciation into account. Rebuilding the missing schedule can reveal a prior-year correction path while producing a defensible adjusted basis for the sale.
rental-property-installment-sale-depreciation|A landlord sells an investment property in exchange for a note paid over several years. Part of the tax connected to prior depreciation may be due in the sale year despite delayed cash collections. An asset-by-asset schedule should be modeled before agreeing to the note terms.
rental-property-selling-costs-gain|A rental sells for a stated price with broker commission, transfer charges, and a mortgage payoff at closing. The commission can reduce amount realized as an eligible selling cost; paying off the loan does not reduce gain. The settlement statement must be translated into a separate tax worksheet.
rental-property-rent-concession-tax|A landlord offers one free month to secure a twelve-month tenant and signs a lease reflecting that concession. There is no cash receipt for the waived month under the cash method. The lease, rent roll, and bank deposits should reconcile so the concession is not mistaken for an unpaid receivable.
business-customer-deposits-tax|A contractor collects a payment before work begins. If the customer can demand return of the money under specified conditions, the obligation differs from an earned advance payment. The signed agreement and later invoices show when the amount becomes consideration for completed work.
business-gift-card-revenue-timing|A shop sells cards in November and customers redeem them across several tax years. Card liabilities, redemptions, and breakage need a year-by-year roll-forward. The treatment depends on the applicable advance-payment rule and the shop's accounting method, not simply when cash reached the register.
business-refunds-returns-tax|An online seller records a December sale, then refunds it in January after a return. The owner should reconcile the original receipt and processor chargeback to the correct year under the chosen accounting method. A generic chargeback expense may conceal the underlying sales adjustment.
business-sales-tax-collected|A retailer receives a $108 payment that includes $8 of state sales tax collected for the state. The owner records the tax liability and remittance separately from product revenue if acting as the state's collection agent. Marketplace facilitator collections should be reconciled as well.
business-credit-card-cashback-tax|A company buys a machine on a card and later receives a purchase-based cash rebate. The rebate may reduce the machine's tax cost rather than create ordinary sales income. The same analysis matters less for routine small supplies but should still match the books.
business-barrier-to-cash-method|A growing company wants to switch from accrual to cash reporting after a profitable year. The owners should calculate the applicable gross-receipts test and review inventory activity before filing. A bookkeeper changing software settings does not itself establish a valid tax-method change.
business-unpaid-invoices-cash-basis|A consultant using the cash method sends an invoice in December but the client never pays. The invoice was never taxable cash receipt, so there is usually no separate bad-debt deduction for its face amount. Collection fees actually paid are a different expense.
business-bad-debt-accrual-method|A wholesaler reports a customer sale on an accrual return, then the customer liquidates without paying. The company documents the prior income inclusion, collection efforts, and year of worthlessness. A broad reserve against every slow-paying customer is not the same as a specific tax write-off.
business-inventory-damaged-goods|A warehouse flood destroys a countable batch of merchandise. The business removes affected units from ending inventory under its adopted method and records any insurance recovery. It should not also deduct the same goods as an unrelated casualty expense without tracing their cost.
business-inventory-samples-tax|A seller distributes sample products at a trade show. The tax cost of units given away should move out of saleable inventory and into the appropriate promotion category. The hoped-for retail sales price is not an amount the business actually spent.
business-inventory-owner-withdrawal|An owner takes products home for family use. The goods leave inventory, but their cost is not an ordinary cost of products sold to customers. A withdrawal log preserves the distinction between owner consumption and documented promotional distribution.
business-freight-in-inventory-cost|A company pays freight to receive items it will resell and separately pays postage to ship sold orders. Inbound freight may be part of inventory cost; outbound shipping is analyzed as a selling cost. Vendor and carrier invoices should be coded separately.
business-website-development-costs|A developer invoices a business for a custom checkout system, monthly hosting, and copy updates. Those three elements need separate analysis because they provide different benefits and rights. A detailed statement of work is stronger support than the invoice description website services.
business-domain-name-purchase-tax|A company pays a broker a substantial amount for an established domain name, then pays an annual registrar fee. The acquired domain right and recurring registration are different costs. Purchase documentation should identify the right transferred and whether it was part of a larger business acquisition.
business-software-subscription-vs-license|A practice pays monthly to access cloud scheduling software, then pays separately to acquire custom code it owns. The recurring access and owned code do not necessarily have the same tax recovery. Contract rights and implementation milestones matter more than a vendor's software label.
business-prepaid-insurance-tax|A business pays in December for a policy covering the next two years. The deduction should be matched to the coverage period under applicable rules rather than assumed to be fully current. The declarations page and payment date establish both the benefit period and cash timing.
business-prepaid-rent-tax|A company prepays several months of next year's office rent before December 31. The lease and benefit period determine whether any timing rule applies. Moving cash before year-end does not by itself transform every future rent obligation into an immediate deduction.
business-lease-security-deposit|A restaurant pays its landlord a refundable security deposit plus first month's rent. The deposit is a recoverable asset; the rent is a separate lease cost. At lease termination, the landlord's refund or application of the deposit triggers the next accounting step.
business-tenant-improvement-allowance|A landlord gives a new commercial tenant money to construct interior improvements. The lease must establish who owns the completed work and how the allowance is conditioned. Both parties should coordinate their tax reporting instead of each independently depreciating the same project.
business-commercial-lease-buyout|A business pays its landlord to exit an expensive lease and then signs a new lease across town. The payment's purpose, contract rights, and connection to the new location must be analyzed. The business should not simply book the whole settlement as monthly rent.
business-trade-show-booth-costs|A company pays for exhibit space, printed handouts, and a reusable modular booth. The event fee and handouts may be current promotion costs; the booth is a durable asset used at later shows. Separating invoices by component supports the timing of each deduction.
business-promotional-giveaways-tax|A firm hands out inexpensive branded pens to hundreds of visitors and gives a valuable watch to one referral partner. Those transactions may fall under different advertising and business-gift rules. Recipient and item records should match the claimed category.
business-referral-fees-1099|A business pays an independent consultant for introducing a new customer. The agreement should show the service, the consultant's tax status, and payment amount. The company then evaluates information reporting instead of assuming a payment platform handles all obligations.
business-contractor-reimbursement-tax|An independent contractor buys materials for a client project and bills the business for labor plus reimbursed materials. The contract should show whether the contractor acted as purchasing agent or charged a combined fee. The business reconciles the invoice and evaluates reporting on the payment.
business-owner-reimbursement-no-accountable-plan|An S corporation sends an owner a fixed monthly expense allowance without receipts or a mileage log. That arrangement differs from reimbursement of documented business costs under an accountable plan. Payroll and the owner return may need correction if the allowance was treated as tax-free.
business-employee-cell-phone|A field technician needs a mobile phone to receive dispatches and report customer visits. The employer's written job requirements help support a business reason for providing the device. An unrestricted cash payment to every employee needs its own wage and reimbursement analysis.
business-employee-home-internet|A remote employee submits an internet bill and documents a necessary business portion. The employer's reimbursement policy states how that portion is calculated. Paying an identical full-bill allowance to everyone without documentation may produce a different tax result.
business-employee-meal-overtime|A business orders food for a team working through an emergency deadline. The owner records attendees, work circumstances, and itemized cost. The deduction and employee fringe treatment should be considered separately rather than assuming that all late-night food is tax-free and fully deductible.
business-team-event-meals|A company hosts a holiday event open to its full staff, then holds a separate dinner for its two owners. The events have different attendee groups and purposes. Invitations and invoices allow the company to apply the appropriate employee recreation and meal rules to each.
business-client-gift-vs-entertainment|A firm buys a client tickets to a game and also pays for a separately itemized meal. Ticket admission and meal cost require separate analysis. The vendor's itemized invoice matters more than the company's internal label client appreciation gift.
business-sponsorship-vs-charity|A local charity gives a business prominent signage, a program advertisement, and speaking time in exchange for payment. The owner documents the advertising benefits received and considers whether any remaining amount is a gift. A nonprofit payee alone does not determine the category.
business-charity-through-s-corp|An S corporation donates to a qualified charity and passes the contribution through to two shareholders. Each owner must consider basis and personal deduction limits; the corporate cash payment does not guarantee an immediate personal tax benefit. The K-1 and acknowledgment should reconcile.
business-business-loan-proceeds-tax|A bank deposits loan proceeds into a new company's account. The deposit creates cash and a repayment liability, not product revenue. Later principal payments reduce debt, while interest and financed purchases follow their own deduction or basis rules.
business-forgiven-loan-tax|A lender agrees to discharge part of a company's outstanding note. The business gathers the cancellation agreement, its solvency data, and any Form 1099-C before deciding whether income or an exclusion applies. The fact that borrowed money was not taxable when received does not settle the later discharge.
business-interest-personal-guarantee|An owner guarantees a corporate loan, and the corporation pays interest from its own account. The owner's guarantee does not itself transfer the interest deduction to the owner's return. If the owner later pays the lender, the payment's effect on debt, basis, or reimbursement must be documented.
business-intercompany-loan-documentation|A shareholder advances cash to a company during a slow quarter. A contemporaneous note states repayment terms and interest, and actual payments follow the agreement. Without those facts, a later claim that the transfer was debt is much harder to defend.
business-owner-loan-repayment-tax|An S corporation repays part of a shareholder's documented loan. The bookkeeper separates principal and interest and checks whether prior pass-through losses reduced debt basis. The shareholder's tax treatment may differ from a simple return of untouched principal.
business-s-corp-distribution-basis|An S corporation has enough cash for a large owner distribution, but prior losses reduced stock basis. Before sending cash, the company prepares a basis roll-forward from old K-1s and contributions. Cash in the bank is not proof the full distribution is tax-free.
business-s-corp-loss-debt-basis|A shareholder signs a guarantee on the company's bank line but has not made a payment or directly lent the company money. The guarantee alone generally does not create debt basis to absorb losses. The preparer must test stock basis, debt basis, at-risk, and passive limits in order.
business-s-corp-shareholder-health-insurance|An S corporation pays a majority owner's health-insurance premiums directly. Before issuing the W-2, payroll confirms the required wage inclusion and the owner checks eligibility for an individual deduction. A company card payment without the payroll step can leave the reporting incomplete.
business-partnership-guaranteed-payment|A partner receives a fixed amount for managing the firm whether or not the partnership earns profit. The operating agreement and K-1 should reflect the guaranteed-payment arrangement. Treating the partner as a W-2 employee without analyzing partner status can create inconsistent filings.
business-partner-expenses-unreimbursed|A partner pays required travel costs personally under the partnership agreement, and the firm does not reimburse them. The partner retains the agreement and receipts to evaluate a partner-level deduction. A voluntary personal purchase without a reimbursement restriction presents a different case.
business-partnership-distribution-property|A partnership distributes a machine to one partner. The partners determine the machine's tax basis, the recipient's outside basis, and any liabilities or special assets before reporting. Its current market value alone does not determine the immediate tax effect.
business-partnership-buyout-ordinary-income|A buyer purchases a partner's interest in a firm holding unpaid receivables and inventory. The transaction price must be analyzed for the portion attributable to those hot assets. That portion can have ordinary character even though the contract calls the deal an interest sale.
business-purchase-price-allocation-assets|A buyer acquires a small operating business with equipment, inventory, customer relationships, and goodwill. Buyer and seller negotiate how the total price is allocated across these assets. Their allocations affect both depreciation and gain character, so matching transaction schedules matter.
business-acquired-customer-list|A company buys another firm's client list as part of an asset purchase. The list can be a durable acquired intangible rather than an immediate marketing expense. Contract rights, valuation, and whether other assets were acquired help identify the correct recovery method.
business-sale-escrow-holdback|A seller receives most business-sale proceeds at closing while a portion stays in escrow against warranty claims. The agreement determines whether the seller has a fixed right to the holdback or a contingent one. The escrow statement and later releases should be tracked separately.
business-sale-working-capital-adjustment|A buyer and seller set a target level of working capital, then settle a difference after closing. The payment may change purchase price rather than pay for a new service. The signed formula and final balance sheet reveal what was adjusted.
business-sale-noncompete-payment|A seller agrees not to compete locally after selling a practice. If the covenant has real economic value, a documented allocation can affect buyer amortization and seller character. A nominal covenant inserted late without valuation support should not drive the tax return.
business-asset-sale-sales-tax|A company sells a used machine to an unrelated buyer. The federal return measures gain or loss using adjusted basis; the state may separately require sales tax or recognize an exemption. A bill of sale and state-specific review should happen before the buyer pays.
"""

SOURCES = {
    "real": ("IRS Publication 527: Residential Rental Property", "https://www.irs.gov/publications/p527"),
    "passive": ("IRS Publication 925: Passive Activity and At-Risk Rules", "https://www.irs.gov/publications/p925"),
    "depreciation": ("IRS Publication 946: How To Depreciate Property", "https://www.irs.gov/publications/p946"),
    "business": ("IRS Publication 334: Tax Guide for Small Business", "https://www.irs.gov/publications/p334"),
    "partnership": ("IRS Publication 541: Partnerships", "https://www.irs.gov/publications/p541"),
    "sale": ("IRS Publication 544: Sales and Other Dispositions of Assets", "https://www.irs.gov/publications/p544"),
}


def parse(block: str) -> list[tuple[str, ...]]:
    rows = [tuple(x.strip() for x in line.split("|")) for line in block.strip().splitlines()]
    assert all(len(row) == 6 for row in rows), "Every entry needs six fields"
    return rows


def source_for(slug: str, real: bool) -> tuple[str, str]:
    if any(w in slug for w in ("partnership", "partner-")):
        return SOURCES["partnership"]
    if any(w in slug for w in ("sale-", "selling-", "buyout", "forgiven", "condemnation")):
        return SOURCES["sale"]
    if any(w in slug for w in ("depreciation", "basis", "improvement", "appliance", "fence", "driveway")):
        return SOURCES["depreciation"]
    if any(w in slug for w in ("loss", "participation", "short-stay", "manager")):
        return SOURCES["passive"]
    return SOURCES["real" if real else "business"]


def make_post(row: tuple[str, ...], real: bool, example: str, sibling_links: list[tuple[str, str]]) -> dict:
    slug, title, answer, decision, evidence, mistake = row
    topic = title.rstrip("?")
    category = "Real Estate Tax" if real else "Business Tax"
    hub = ("/real-estate-tax-planning/", "Real estate tax planning") if real else ("/business-owner-small-business-tax/", "Business tax planning")
    source_name, source_url = source_for(slug, real)
    esc = html.escape
    subhub = (("/guides/rental-property-tax-questions/", "Rental property tax questions")
              if real else ("/guides/business-tax-questions/", "Business tax questions"))
    related = [subhub, hub] + sibling_links
    if real:
        related.append(("/cost-segregation-studies-for-real-estate-investors/", "Depreciation and cost segregation"))
    else:
        related.append(("/business-owner-tax-planning/", "Business owner tax strategy"))
    body = f"""
        <h2>The tax treatment</h2>
        <p>{esc(answer)} This is a federal income tax starting point; the contract, ownership, accounting method, and actual use can change the result. State and local treatment should be checked separately.</p>

        <h2>The decision to make before filing</h2>
        <p>{esc(decision)} The useful planning step is to resolve the classification while the underlying documents are still available, then reconcile it to the books and the prior-year return. If the transaction spans more than one year, track the opening balance and what happened to it afterward.</p>

        <h2>Illustrative example</h2>
        <p>{esc(example)}</p>

        <h2>Records that support the position</h2>
        <p>{esc(evidence)} Tie amounts on the return to bank activity and the agreement. When several assets, people, or uses are involved, write down the allocation method and apply it consistently. A short dated workpaper is easier to defend than a reconstructed explanation years later.</p>

        <h2>A common reporting error</h2>
        <p>{esc(mistake)} Review both sides of the entry: a payment can affect income, basis, liability, or an expense at different times. A correct cash total alone does not establish the correct tax character.</p>

        <h2>Where to verify the rule</h2>
        <p>Start with <a href="{source_url}" rel="noopener">{esc(source_name)}</a>. Its examples and cross-references explain the underlying federal rule; check the current version and any later IRS guidance for the year at issue. For a coordinated review of related deductions and limitations, see <a href="{hub[0]}">{esc(hub[1])}</a>.</p>
    """
    return {
        "slug": slug, "title": topic, "h1": title,
        "title_tag": f"{topic} | AE Tax Advisors",
        "breadcrumb": topic, "category": category,
        "description": meta_description(answer),
        "date": "2026-09-22", "date_display": "September 22, 2026",
        "lead": f"<strong>{esc(answer)}</strong>",
        "body": re.sub(r"(?m)^[ \t]+$", "", body),
        "faqs": [],
        "related": related,
        "cta_head": f"Need to classify this {('rental' if real else 'business')} transaction?",
        "cta_text": "AE Tax Advisors can review the documents, reporting history, and the decision before filing.",
    }


GROUP_NAMES = {
    True: ["Rental receipts and acquisition", "Improvements and property costs",
           "Management, ownership, and basis", "Short stays and lease arrangements",
           "Financing, losses, and sale"],
    False: ["Revenue and inventory", "Technology and commercial leases",
            "Marketing and employee costs", "Financing and S corporation owners",
            "Partnerships and business sales"],
}


def build_hub(rows: list[tuple[str, ...]], real: bool) -> tuple[str, str]:
    slug = "rental-property-tax-questions" if real else "business-tax-questions"
    path = f"/guides/{slug}/"
    title = "Rental Property Tax Questions: A Practical Guide" if real else "Business Tax Questions: A Practical Guide"
    subtitle = ("Find the tax treatment, documentation, and common errors for 50 situations rental owners encounter."
                if real else "Find the tax treatment, documentation, and common errors for 50 situations business owners encounter.")
    intro = ("Rental income, basis, improvements, short stays, refinancing, and sales are connected. "
             "Use these focused articles to classify an actual transaction, then return to the "
             "broader real estate tax planning guide for the full portfolio context."
             if real else
             "Revenue recognition, inventory, reimbursements, entity basis, and business sales "
             "interact across tax years. Use these focused articles for a transaction-level answer, "
             "then return to the broader business tax planning guide for entity-wide decisions.")
    parent = ("/real-estate-tax-planning/", "Real estate tax planning") if real else ("/business-owner-small-business-tax/", "Business tax planning")
    parts = [template.page_header(h1=title, subtitle=subtitle,
              trail=[("Home", "/"), ("Guides", "/guides/"), (title, path)]),
             template.section("How to use this guide", f'<p>{intro} Start with the question that matches your facts. Each article identifies a decision, records to keep, an illustrative example, and a primary IRS reference.</p><p>For a broader plan, see <a href="{parent[0]}">{parent[1]}</a>.</p>')]
    for i, group_name in enumerate(GROUP_NAMES[real]):
        items = rows[i*10:(i+1)*10]
        lis = "\n".join(f'<li><a href="/blog/{r[0]}/">{html.escape(r[1])}</a><br>{html.escape(r[2])}</li>' for r in items)
        parts.append(template.section(group_name, f'<ul class="related-links">{lis}</ul>'))
    body = "\n".join(parts)
    page = template.build_page(title=f"{title} | AE Tax Advisors", description=subtitle,
              path=path, body=body,
              schemas=[template.breadcrumb_schema([("Home", "/"), ("Guides", "/guides/"), (title, path)])],
              published="2026-09-22", modified="2026-09-22", og_type="website")
    out = Path("guides") / slug / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page)
    return path, title


def main() -> None:
    real, business = parse(REAL_ESTATE), parse(BUSINESS)
    assert len(real) == len(business) == 50, (len(real), len(business))
    assert len({r[0] for r in real + business}) == 100
    examples = dict(line.split("|", 1) for line in EXAMPLES.strip().splitlines())
    assert len(examples) == 100 and set(examples) == {r[0] for r in real + business}
    manifest = Path("long_tail_100_slugs.txt")
    slugs = {r[0] for r in real + business}
    prior = set(manifest.read_text().splitlines()) if manifest.exists() else set()
    assert not prior or prior == slugs, "Manifest does not match the current page inventory"
    for row, is_real in [(r, True) for r in real] + [(r, False) for r in business]:
        # These have distinct, expanded content maintained by the cluster builder.
        if row[0] in {'business-employee-cell-phone', 'business-employee-home-internet'}:
            continue
        assert re.fullmatch(r"[a-z0-9-]+", row[0])
        target = Path("blog") / row[0] / "index.html"
        assert not target.exists() or row[0] in prior, f"Existing page collision: {target}"
        group_rows = real if is_real else business
        pos = group_rows.index(row)
        start = (pos // 10) * 10
        siblings = [r for r in group_rows[start:start+10] if r[0] != row[0]]
        # Adjacent questions are related by the editor's subtopic group.
        picks = siblings[max(0, pos % 10 - 1):max(0, pos % 10 - 1)+2]
        sibling_links = [(f"/blog/{r[0]}/", r[1]) for r in picks]
        seo_render.write_post(make_post(row, is_real, examples[row[0]], sibling_links))
    manifest.write_text("\n".join(sorted(slugs)) + "\n")
    real_hub = build_hub(real, True)
    business_hub = build_hub(business, False)
    for pillar, subhub in (("real-estate-tax-planning", real_hub),
                           ("business-owner-small-business-tax", business_hub)):
        page = Path(pillar) / "index.html"
        markup = page.read_text()
        marker = "long-tail-question-hub"
        if marker not in markup:
            block = (f'<section class="content-section fade-in-section {marker}">'
                     '<div class="container narrow"><h2>Explore Specific Tax Questions</h2>'
                     f'<p>For transaction-level answers and records to keep, browse '
                     f'<a href="{subhub[0]}">{subhub[1]}</a>. The guide groups 50 focused '
                     'questions by topic and links each answer back to broader planning.</p>'
                     '</div></section>')
            page.write_text(markup.replace("</main>", block + "\n</main>", 1))
    # Keep prior lastmod dates untouched: these are the only URLs changed today.
    for sitemap in (Path("sitemap.xml"), Path("sitemap-blog.xml"), Path("sitemap-pages.xml")):
        xml = sitemap.read_text()
        additions = []
        paths = ([f"/blog/{slug}/" for slug, *_ in real + business]
                 if sitemap.name != "sitemap-pages.xml" else [])
        if sitemap.name != "sitemap-blog.xml":
            paths += [real_hub[0], business_hub[0]]
        for path in paths:
            url = f"https://www.aetaxadvisors.com{path}"
            if url not in xml:
                additions.append(
                    f"  <url><loc>{url}</loc><lastmod>2026-09-22</lastmod>"
                    "<changefreq>monthly</changefreq><priority>0.6</priority></url>"
                )
        if additions:
            sitemap.write_text(xml.replace("</urlset>", "\n".join(additions) + "\n</urlset>"))
    index = Path("sitemap-index.xml")
    index.write_text(index.read_text().replace(
        "sitemap-blog.xml</loc><lastmod>2026-09-18",
        "sitemap-blog.xml</loc><lastmod>2026-09-22",
    ).replace("sitemap-pages.xml</loc><lastmod>2026-09-18",
              "sitemap-pages.xml</loc><lastmod>2026-09-22"))
    print("Built 100 new pages: 50 real estate and 50 business tax")


if __name__ == "__main__":
    main()
