#!/usr/bin/env python3
"""Build a transparent outcomes report from the original case-study cohort.

The benchmark intentionally excludes scenario pages generated by case_engine.py
and any original page whose headline outcome is a deduction, deferral, offset,
recovery amount, or otherwise not a plain annual tax-savings dollar figure.
"""

from __future__ import annotations

import csv
import io
import json
import random
import re
import statistics
from html.parser import HTMLParser
from pathlib import Path

import case_engine as E
import site_template as T

DATE = "2026-09-26"
PATH = "/research/tax-planning-case-study-outcomes/"
JSON_PATH = "/research/tax-planning-case-study-outcomes.json"
CSV_PATH = "/research/tax-planning-case-study-outcomes.csv"


class TableParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.cell = None
        self.buffer = []
        self.cells = []

    def handle_starttag(self, tag, attrs):
        if tag in ("th", "td"):
            self.cell = tag
            self.buffer = []

    def handle_data(self, data):
        if self.cell:
            self.buffer.append(data)

    def handle_endtag(self, tag):
        if tag == self.cell:
            value = " ".join("".join(self.buffer).split())
            self.cells.append((tag, value))
            self.cell = None


def generated_slugs():
    rng = random.Random(20260815)
    slugs, seen = [], set()
    for builder, count in E.BUILDERS:
        for _ in range(count):
            slug = builder(rng, len(slugs) + 1)["slug"]
            if slug in seen:
                slug += "-b"
            seen.add(slug)
            slugs.append(slug)
    return set(slugs)


def table_fields(page: Path):
    parser = TableParser()
    parser.feed(page.read_text(encoding="utf-8", errors="ignore"))
    fields = {}
    for i in range(len(parser.cells) - 1):
        first, second = parser.cells[i], parser.cells[i + 1]
        if first[0] in ("th", "td") and second[0] == "td":
            fields[first[1]] = second[1]
    return fields


def cohort():
    generated = generated_slugs()
    rows = []
    originals = []
    for page in sorted((T.ROOT / "case-studies").glob("*/index.html")):
        slug = page.parent.name
        if slug in generated:
            continue
        originals.append(slug)
        fields = table_fields(page)
        raw = fields.get("Annual Tax Savings", "")
        if not re.fullmatch(r"\$[\d,]+", raw):
            continue
        rows.append({
            "slug": slug,
            "url": T.SITE + "/case-studies/" + slug + "/",
            "industry": fields.get("Industry", "Not specified"),
            "annualTaxSavings": int(raw[1:].replace(",", "")),
            "headlineOutcome": raw,
            "keyMetric": fields.get("Key Metric", ""),
        })
    return originals, rows, len(generated)


def money(value):
    return f"${value:,.0f}"


def percentile(values, p):
    ordered = sorted(values)
    position = (len(ordered) - 1) * p
    low = int(position)
    high = min(low + 1, len(ordered) - 1)
    weight = position - low
    return round(ordered[low] * (1 - weight) + ordered[high] * weight)


def report_html(originals, rows, generated_count):
    values = [r["annualTaxSavings"] for r in rows]
    count = len(rows)
    median = round(statistics.median(values))
    average = round(statistics.mean(values))
    total = sum(values)
    at_50 = sum(v >= 50_000 for v in values)
    at_100 = sum(v >= 100_000 for v in values)
    buckets = [
        ("Under $50,000", sum(v < 50_000 for v in values)),
        ("$50,000 to $99,999", sum(50_000 <= v < 100_000 for v in values)),
        ("$100,000 to $199,999", sum(100_000 <= v < 200_000 for v in values)),
        ("$200,000 or more", sum(v >= 200_000 for v in values)),
    ]
    bars = "\n".join(
        f'<div class="outcome-row"><span>{label}</span><div class="outcome-track"><span style="width:{n / count * 100:.1f}%"></span></div><strong>{n}</strong></div>'
        for label, n in buckets
    )
    selected = [
        "consultant-six-figure-s-corp",
        "ecommerce-amazon-fba-s-corp",
        "w2-couple-str-offset",
        "physician-w2-str-reps",
        "restaurant-cost-seg-tip-credit",
        "self-storage-facility-cost-seg-automation",
        "manufacturing-company-rd-credit-macrs",
        "construction-company-equipment-depreciation-entity-layering",
        "private-medical-practice-c-corp-defined-benefit",
        "tech-founder-equity-comp-83b",
    ]
    by_slug = {r["slug"]: r for r in rows}
    sample_rows = "\n".join(
        f'<tr><th scope="row"><a href="/case-studies/{slug}/">{by_slug[slug]["industry"]}</a></th><td>{money(by_slug[slug]["annualTaxSavings"])}</td><td>{by_slug[slug]["keyMetric"]}</td></tr>'
        for slug in selected if slug in by_slug
    )
    faqs = [
        ("What is the median reported annual tax savings in these case studies?", f"<p>The median across the {count}-case benchmark cohort is {money(median)}. This describes the published cohort and is not a prediction for a prospective client.</p>"),
        ("How many case studies are included?", f"<p>The statistical cohort includes {count} original case studies with one plain annual tax-savings figure. It excludes {len(originals) - count} other original studies whose headline measures were deductions, deferrals, offsets, recoveries, or did not provide a comparable annual figure. It also excludes {generated_count} templated scenarios.</p>"),
        ("Are these results guaranteed?", "<p>No. Tax outcomes depend on income, marginal rates, basis, entity structure, participation, substantiation, timing, state law, and implementation. No case-study result guarantees a similar outcome.</p>"),
        ("Can the underlying data be downloaded?", f'<p>Yes. The included rows and methodology are available as <a href="{JSON_PATH}">JSON</a> and <a href="{CSV_PATH}">CSV</a>.</p>'),
    ]
    cards = f'''<div class="outcome-grid">
        <article><strong>{count}</strong><span>comparable case studies</span></article>
        <article><strong>{money(median)}</strong><span>median reported annual savings</span></article>
        <article><strong>{money(average)}</strong><span>average reported annual savings</span></article>
        <article><strong>{at_100 / count:.0%}</strong><span>reported $100,000 or more</span></article>
    </div>'''
    body = "\n\n".join([
        T.page_header(h1="Tax Planning Case Study Outcomes Report", subtitle=f"An analysis of {count} comparable AE Tax Advisors case studies published through September 20, 2026.", trail=[("Home", "/"), ("Research", "/research/"), ("Case Study Outcomes", PATH)], cta="Compare Your Tax Situation"),
        T.section("Headline Findings", T.definition(f"Across {count} original published case studies with a comparable annual tax-savings measure, the median reported outcome is {money(median)} and the average is {money(average)}. These are descriptive case-study figures, not audited performance statistics or a promise of future savings.") + cards + '<p class="disclosure"><strong>Important:</strong> AE Tax Advisors selected and published these case studies. The cohort is not a random sample, may overrepresent situations with substantial planning opportunities, and should not be generalized to every taxpayer.</p>'),
        T.section("Outcome Distribution", f'<div class="outcome-bars">{bars}</div><p>{at_50} of {count} cases ({at_50 / count:.0%}) report at least $50,000 in annual tax savings. {at_100} cases ({at_100 / count:.0%}) report at least $100,000.</p>'),
        T.section("Range and Quartiles", f'<ul class="takeaway-list"><li>Lowest reported annual figure: <strong>{money(min(values))}</strong></li><li>25th percentile: <strong>{money(percentile(values, .25))}</strong></li><li>Median: <strong>{money(median)}</strong></li><li>75th percentile: <strong>{money(percentile(values, .75))}</strong></li><li>Highest reported annual figure: <strong>{money(max(values))}</strong></li><li>Sum of the cohort headline figures: <strong>{money(total)}</strong>, without adjustment for overlap, duration, realization, or present value</li></ul>'),
        T.section("Representative Cases", f'<div class="ae-table-scroll" style="overflow-x:auto"><table class="compare-table"><caption>Selected cases illustrate the range of taxpayer profiles and strategies in the cohort.</caption><thead><tr><th>Published case</th><th>Reported annual savings</th><th>Key fact</th></tr></thead><tbody>{sample_rows}</tbody></table></div>'),
        T.section("Methodology", f'<ol class="takeaway-list"><li>We separated the {len(originals)} pre-existing case-study pages from {generated_count} deterministic scenario-template pages. Scenario pages are excluded from every statistic on this page.</li><li>We included only original pages whose client-profile table contains the field <strong>Annual Tax Savings</strong> followed by one unqualified dollar amount.</li><li>We excluded {len(originals) - count} original pages reporting deductions, offsets, deferrals, recoveries, mixed time periods, or no comparable annual measure.</li><li>We calculated the median, arithmetic mean, quartiles, range, and distribution directly from the {count} included headline figures.</li><li>We did not independently audit the underlying returns, realization of the savings, or the counterfactual calculation.</li></ol><p><a href="{JSON_PATH}">Download JSON</a> or <a href="{CSV_PATH}">download CSV</a>. Each row links to its published case study.</p>'),
        T.takeaways(["Use the median as a description of this selected cohort, not an expected client result.", "Larger outcomes often accompany higher income, larger asset basis, multiple entities, or several coordinated strategies.", "A deduction amount is not the same as tax savings, which is why deduction-only studies were excluded.", "Deferral is not permanent savings and was excluded from the comparable annual cohort.", "Every proposed strategy still requires fact-specific tax, legal, substantiation, and implementation review."], "How to Interpret the Findings"),
        T.faq_section(faqs),
        T.related_section([("/case-studies/", "Browse All Case Studies"), ("/compare/tax-advisor-fit-assessment/", "Tax Advisor Fit Assessment"), ("/compare/proactive-tax-advisor-pricing-guide/", "Proactive Tax Advisor Pricing Guide"), ("/business-tax-second-opinion/", "Business Tax Second Opinion")]),
    ])
    schemas = [
        T.article_schema(title="Tax Planning Case Study Outcomes Report (2026)", description=f"Analysis of {count} comparable AE Tax Advisors case studies, including median and average reported annual tax savings, distribution, methodology, and downloadable data.", url=T.SITE + PATH, published=DATE, modified=DATE, section="Tax Research", keywords=["tax planning case studies", "tax savings case studies", "tax advisory outcomes"], about=[{"@type": "Dataset", "name": "AE Tax Advisors published case-study outcomes cohort", "url": T.SITE + JSON_PATH}], citations=[T.SITE + r["url"].replace(T.SITE, "") for r in rows]),
        {"@context": "https://schema.org", "@type": "Dataset", "name": "AE Tax Advisors Tax Planning Case Study Outcomes", "description": f"{count} original published case studies with a comparable annual tax-savings measure.", "url": T.SITE + JSON_PATH, "dateModified": DATE, "creator": {"@type": "Organization", "name": "AE Tax Advisors", "url": T.SITE + "/"}, "distribution": [{"@type": "DataDownload", "encodingFormat": "application/json", "contentUrl": T.SITE + JSON_PATH}, {"@type": "DataDownload", "encodingFormat": "text/csv", "contentUrl": T.SITE + CSV_PATH}], "variableMeasured": ["Annual tax savings", "Industry", "Key metric"]},
        T.faq_schema(faqs),
        T.breadcrumb_schema([("Home", "/"), ("Research", "/research/"), ("Case Study Outcomes", PATH)]),
    ]
    extra = '''<style>.outcome-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:28px 0}.outcome-grid article{padding:22px;border:1px solid #dbe3ea;border-radius:10px;background:#fff}.outcome-grid strong{display:block;font-size:1.75rem;color:var(--accent)}.outcome-grid span{display:block;margin-top:6px}.outcome-row{display:grid;grid-template-columns:190px 1fr 32px;gap:12px;align-items:center;margin:14px 0}.outcome-track{height:14px;background:#e8edf2;border-radius:20px;overflow:hidden}.outcome-track span{display:block;height:100%;background:var(--accent)}@media(max-width:760px){.outcome-grid{grid-template-columns:1fr 1fr}.outcome-row{grid-template-columns:145px 1fr 25px;font-size:.9rem}}</style>'''
    return T.build_page(title="Tax Planning Case Study Outcomes Report (2026)", description=f"Analysis of {count} comparable AE Tax Advisors case studies, with median and average reported annual savings, distribution, methodology, and downloadable data.", path=PATH, body=body, schemas=schemas, published=DATE, modified=DATE, extra_head=extra)


def main():
    originals, rows, generated_count = cohort()
    values = [r["annualTaxSavings"] for r in rows]
    report = {
        "name": "AE Tax Advisors Tax Planning Case Study Outcomes",
        "dateModified": DATE,
        "methodologyUrl": T.SITE + PATH,
        "includedCaseCount": len(rows),
        "originalCaseStudyCount": len(originals),
        "excludedOriginalCaseCount": len(originals) - len(rows),
        "excludedTemplatedScenarioCount": generated_count,
        "statistics": {
            "medianReportedAnnualTaxSavings": round(statistics.median(values)),
            "averageReportedAnnualTaxSavings": round(statistics.mean(values)),
            "minimumReportedAnnualTaxSavings": min(values),
            "maximumReportedAnnualTaxSavings": max(values),
            "sumOfHeadlineAnnualFigures": sum(values),
            "casesAtOrAbove50000": sum(v >= 50_000 for v in values),
            "casesAtOrAbove100000": sum(v >= 100_000 for v in values),
        },
        "limitations": [
            "Publisher-selected case-study cohort, not a random sample.",
            "Underlying returns and realization of savings were not independently audited for this report.",
            "Results do not guarantee or predict a prospective client's outcome.",
            "Templated scenario pages and non-comparable headline measures are excluded.",
        ],
        "cases": rows,
    }
    out = T.ROOT / "research"
    out.mkdir(exist_ok=True)
    (out / "tax-planning-case-study-outcomes.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=["slug", "url", "industry", "annualTaxSavings", "headlineOutcome", "keyMetric"])
    writer.writeheader()
    writer.writerows(rows)
    (out / "tax-planning-case-study-outcomes.csv").write_text(buffer.getvalue(), encoding="utf-8")
    T.write_page(PATH, report_html(originals, rows, generated_count))
    print(f"report built: {len(rows)} included, {len(originals) - len(rows)} non-comparable originals excluded, {generated_count} scenarios excluded")


if __name__ == "__main__":
    main()
