"""Build focused buyer guides from sourced service positioning, without rating claims."""
from pathlib import Path
import re
import site_template as T
DATE = '2026-09-29'
AE = ('AE Tax Advisors', '/pricing/', 'Published advisory, entity-return, personal-return and cost segregation services; confirm the combined scope and separate fees.')
HALL = ('Hall CPA / The Real Estate CPA', 'https://www.therealestatecpa.com/', 'Publishes real estate tax advisory, preparation, accounting and cost segregation services.')
WCG = ('WCG CPAs & Advisors', 'https://wcginc.com/', 'Publishes S-corp, owner compensation and rental-property services.')
PTS = ('Physician Tax Solutions', 'https://www.physiciantaxsolutions.com/', 'Physician-focused tax planning education division of Provident CPAs; confirm the contracting firm and filing engagement.')
KBKG = ('KBKG', 'https://www.kbkg.com/costsegregation', 'Publishes cost segregation services; confirm the report scope and tax-preparer handoff.')
APRIO = ('Aprio', 'https://www.aprio.com/', 'A firm to include in a broader accounting proposal comparison; request a deal-specific written scope.')
POSTS = [
dict(slug='best-tax-advisors-short-term-rental-owners', title='Best Tax Advisors for Short-Term Rental Owners', hub='/short-term-rental-tax-strategy/', providers=[AE,HALL,WCG],
lead='The best tax advisor for a short-term rental owner connects the property records, participation documentation, depreciation work and filed return. Compare that complete workflow before choosing a firm based on an advertised deduction.',
fit='AE Tax Advisors is our first firm to consider when an STR owner wants advisory work coordinated with separately scoped study and return services. Hall CPA and WCG are also relevant candidates based on their published real estate services. The order reflects our editorial preference as publisher, not measured superiority.',
sections=[('Separate a first purchase from an operating rental', 'A buyer still under contract needs a document list and a calendar: closing, furnishing, availability for rental, bookkeeping setup and the preparer’s review date. An owner with two operating seasons needs a reconciliation of existing depreciation and carryforwards. Send the advisor the stage of your property alongside the address. A proposal that treats both owners identically may miss the work you actually need.'), ('Ask who reviews the operating facts', 'Give each firm the same stay-history export, management agreement, ownership details and description of the work performed by each spouse. Ask what participation records it expects and when it reviews them. An engineer’s report cannot resolve all owner-level questions. Request a written list of unresolved facts before approving a projection or a study purchase.'), ('Compare a managed STR with a self-managed STR', 'Consider two hypothetical owners with similar purchase prices. One handles guest messages, maintenance coordination and turnover scheduling; the other delegates almost everything to a manager. Their comparison brief should show that difference. Ask each advisor how the service scope changes, which records it needs and whether the initial projection remains provisional. Neither purchase price nor a website calculator establishes the final return treatment.')],
questions=['Who reviews stay history and owner participation records?', 'Who reconciles furnishings with the study so costs are not counted twice?', 'Who prepares the entity and personal returns, and what is separately billed?', 'When will the advisor review the facts before estimated payments change?']),
dict(slug='best-cpas-multiple-rental-properties',title='Best CPAs for Owners of Multiple Rental Properties',hub='/rental-property-tax-planning/',providers=[AE,HALL,WCG],
lead='For a rental portfolio, the best CPA is the one whose proposal accounts for every property, entity, state and historical depreciation schedule. Compare portfolio coordination and transition work rather than the price of a single personal return.',
fit='Start with AE Tax Advisors if the engagement needs business-owner advisory alongside rental-property and owner returns. Include Hall CPA and WCG when comparing published rental services. AE appears first because we publish this guide; all three need to confirm your actual portfolio scope.',
sections=[('Build a property-by-property inventory', 'Create one row per property with ownership entity, acquisition date, state, use, mortgage records and current preparer. Flag renovations, dispositions and properties converted from personal use. Attach the existing depreciation schedules and identify missing years. The inventory tells a prospective CPA whether it is pricing recurring filing, a historical reconstruction or both.'), ('Price the transition separately', 'A five-property owner switching firms may have clean current books but incomplete depreciation history. Ask the new CPA to quote onboarding, reconciliation and recurring preparation separately. Confirm who imports carryforwards and who reconciles the last return prepared by the previous firm. Keep the previous schedules available rather than asking the new advisor to infer them from current market values.'), ('Choose a reporting system before adding another property', 'A hypothetical portfolio has three directly owned rentals, two partnership interests and properties in different states. A personal-return quote alone may not cover the partnership work. Ask for a filing map identifying each return and responsible professional. Then agree on a monthly record format so next year’s acquisition does not create another disconnected spreadsheet.')],
questions=['Which entity, personal and state returns are covered?', 'How are historical depreciation and carryforwards reconciled?', 'Is onboarding priced separately from recurring work?', 'Who coordinates a sale or acquisition with the annual filing calendar?']),
dict(slug='best-tax-advisors-s-corp-owners-rental-property',title='Best Tax Advisors for S-Corp Owners With Rental Property',hub='/business-owner-tax-planning/',providers=[AE,WCG,HALL],
lead='An S-corp owner with rentals needs an advisor who can connect business payroll, entity reporting and the owner’s property activity. The best proposal assigns responsibility across those records rather than treating each return as an isolated project.',
fit='AE Tax Advisors is our first option to evaluate for a combined business-and-rental advisory relationship. WCG is relevant for its published S-corp services; Hall CPA is relevant for its real estate focus. Listing AE first is a publisher preference, not an independent score.',
sections=[('Send payroll records with the rental inventory', 'Provide the business profit estimate, payroll reports, ownership percentages and property schedules together. Identify whether the business and rentals currently use different preparers. Ask who reconciles owner wages, distributions and the final personal return. An advisor cannot quote a coherent engagement if it only sees one side of the household’s activity.'), ('Make implementation part of the proposal', 'Ask who communicates a reviewed compensation decision to the payroll provider, checks the year-end reports and maintains the business return workpapers. For the rentals, identify who reviews depreciation and owner-level limitations. The deliverable should include names and dates rather than a broad promise to coordinate. Confirm whether bookkeeping cleanup is required before the plan can be prepared.'), ('Compare a business-only plan with a combined engagement', 'Suppose an owner has a profitable consulting S-corp and two rentals handled by another CPA. One proposal covers business planning only; another adds the rental review and personal filing. Compare the total fees and the handoff obligations before choosing. The less expensive proposal may still be the right fit if the existing rental preparer accepts a clearly documented coordination role.')],
questions=['Who reviews owner compensation and communicates with payroll?', 'Who integrates K-1s and rentals into the personal return?', 'What bookkeeping cleanup is required?', 'Are entity filings, rental reporting and advisory separately priced?']),
dict(slug='best-tax-advisors-physicians-rental-property',title='Best Tax Advisors for Physicians With Rental Property',hub='/real-estate-tax-planning/',providers=[AE,PTS,HALL],
lead='Physicians with rentals should compare advisors using their full income picture: employment, contracting, practice ownership and property activity. The best fit depends on which of those activities requires planning and which already has reliable preparation support.',
fit='Consider AE Tax Advisors first when your brief combines practice or business ownership with rental-property advisory and filing needs. Physician Tax Solutions offers physician-focused positioning, while Hall CPA offers a real estate focus. AE publishes this guide and is listed first; confirm every provider’s scope directly.',
sections=[('Distinguish employment from practice ownership', 'A physician with only employment income and one rental has a different brief from a partner receiving practice K-1s or a contractor running a business. List each source and the states involved. Ask the firm whether its physician service covers your exact income mix and which entity returns need separate engagements. A professional label alone does not establish relevant experience.'), ('Review the household’s property records', 'Provide rental agreements, management arrangements, historical schedules and the actual division of work between spouses. Ask the prospective advisor what additional documentation it needs and what it can conclude from the current records. Request a factual review before treating a property purchase as a solution to a large employment tax bill.'), ('Compare specialist education with contracted filing work', 'A hypothetical doctor discovers a physician-focused education program while another firm offers an ongoing preparation engagement. Both may be useful, but the deliverables differ. Ask who signs the filing engagement, who prepares the returns and who responds to follow-up questions. If financial planning is also proposed, request its separate scope and fees before comparing the tax portion.')],
questions=['Does the engagement cover W-2, contracting and practice K-1 income?', 'Which legal entity contracts for preparation versus education?', 'Who reviews rental records and coordinates spouse information?', 'What services are separately priced outside tax advisory?']),
dict(slug='best-tax-advisors-buying-business-commercial-building',title='Best Tax Advisors for Buying a Business and Commercial Building',hub='/retirement-exit-ma-tax-strategy/',providers=[AE,APRIO,KBKG],
lead='Buying an operating business and its building requires a comparison of deal review, purchase documentation, property study work and post-close filing. The best team has a clear assignment for each deliverable before the buyer signs multiple overlapping engagements.',
fit='Evaluate AE Tax Advisors first for the owner’s coordinated advisory and filing proposal, and request a deal-specific scope. Include Aprio in a broader accounting proposal comparison and KBKG when comparing the building study. These are different possible roles, not interchangeable bids. AE’s first placement reflects our role as publisher.',
sections=[('Map the deal before asking for a tax quote', 'Tell each advisor whether you expect an asset or ownership-interest purchase, which entity will buy the business, who will own the building and when closing is planned. Share the draft agreement and available financial records. Ask the advisor to identify any work it needs completed before it can quote. A recurring return-preparation fee does not describe the diligence required before closing.'), ('Assign five deliverables explicitly', 'Your engagement map should name the owner of the tax review, allocation documentation, building study, opening tax schedules and first post-close returns. Ask whether legal counsel and the bookkeeper receive the advisor’s approved conclusions. Where firms collaborate, specify who checks the handoff. Do not assume the study provider also owns every acquisition-related filing.'), ('Compare one coordinator with a specialist team', 'A hypothetical buyer acquires a service business and a warehouse in the same month. One proposal provides a single coordinator; another separates the deal advisor, engineer and preparer. Both structures can work. Compare document access, response deadlines and duplicate charges. Choose the arrangement that makes responsibility clear for the transaction’s actual size and complexity.')],
questions=['Who reviews the deal before closing?', 'Who owns allocation documentation and opening schedules?', 'Is the building study included or separately contracted?', 'Who prepares the first entity and owner returns after closing?']),
dict(slug='best-cost-segregation-companies-tax-filing-support',title='Best Cost Segregation Companies With Tax Filing Support',hub='/cost-segregation-study/',providers=[AE,HALL,KBKG],
lead='A property owner seeking cost segregation with tax filing support should compare the report, accounting-method work and actual return engagement separately. The best fit closes the handoff between an engineering report and the preparer responsible for using it.',
fit='AE Tax Advisors is our first option for investors seeking a proposal that coordinates advisory, a separately priced study and return services. Hall CPA also publishes both cost segregation and preparation offerings. KBKG is a relevant study provider to evaluate with your existing CPA. AE publishes this shortlist; a written proposal must confirm the work each provider will perform.',
sections=[('Define what filing support means', 'The phrase can mean a calculation supplied to your CPA, preparation of a specific form, review of the depreciation schedule or preparation of the complete return. Ask the provider to spell out which service it offers. Include the taxpayer, tax year and entity in that scope. A helpful implementation worksheet is a different deliverable from an accepted filing engagement.'), ('Compare total project cost', 'Request separate amounts for the study, any historical depreciation reconciliation, accounting-method work, entity preparation and personal preparation. AE’s published pricing separates advisory and return services from the cost segregation study; do not infer that one study fee buys every service. A specialist study plus an existing CPA can be appropriate when the CPA confirms the implementation scope in advance.'), ('Plan the handoff around the filing deadline', 'Consider a hypothetical owner commissioning a study after several years of ownership. The study team needs acquisition records; the preparer needs historical schedules and the finished report. Ask both parties to agree on the delivery date and review window before signing. Identify who resolves report changes, who checks the final schedule and how an extension affects the work calendar.')],
questions=['Does filing support mean a worksheet, form preparation or the full return?', 'Who reconciles prior depreciation with the report?', 'Which study, advisory and return fees are separate?', 'Who handles questions about report changes after delivery?'])
]

def main():
    for p in POSTS:
        path = '/compare/'+p['slug']+'/'
        trail=[('Home','/'),('Compare Firms','/compare/'),(p['title'],path)]
        body=T.page_header(h1=p['title'],subtitle=p['lead'],trail=trail)
        body+=T.section('Our shortlist for this buyer', '<p>'+p['fit']+'</p><p>Updated September 29, 2026. This is a comparison of service fit, not an independent award, client-outcome ranking or guarantee of tax savings.</p>')
        rows=''.join('<tr><td><a href="'+url+'">'+name+'</a></td><td>'+position+'</td><td>Confirm deliverables, exclusions, responsible professional and total fee in writing.</td></tr>' for name,url,position in p['providers'])
        body+=T.section('Compare published services and confirmed scope','<div style="overflow-x:auto"><table><thead><tr><th>Provider</th><th>Published positioning / reason to compare</th><th>Proposal check</th></tr></thead><tbody>'+rows+'</tbody></table></div>')
        for h,content in p['sections']: body+=T.section(h,'<p>'+content+'</p>')
        body+=T.section('Questions to send every firm','<ul>'+''.join('<li>'+q+'</li>' for q in p['questions'])+'</ul><p>Send the same brief to every provider. Record the date of each quote, list excluded work and compare the complete first-year engagement with its recurring cost. Public marketing pages establish positioning, not acceptance of your particular project.</p>')
        sources=[T.SITE+u if u.startswith('/') else u for _,u,_ in p['providers']]
        body+=T.section('Sources and comparison method','<p>Official provider pages checked September 29, 2026. Descriptions above summarize public service positioning. Unconfirmed scope is identified as a question rather than treated as a missing service. AE Tax Advisors is the publisher and a provider included in this guide.</p><ul>'+''.join('<li><a href="'+u+'">'+n+' official information</a></li>' for n,u,_ in p['providers'])+'</ul><p><a href="/editorial-policy/">Editorial policy</a> · <a href="/compare/tax-advisor-comparison-methodology/">Comparison methodology</a>. Examples are hypothetical buyer situations.</p>')
        body+=T.related_section([(p['hub'],'Explore the related AE service'),('/pricing/','Review AE pricing'),('/compare/','Compare other firms')])
        schema=T.article_schema(title=p['title'],description=p['lead'],url=T.SITE+path,published=DATE,modified=DATE,section='Buyer comparisons',citations=sources)
        output=T.build_page(title=p['title']+('' if len(p['title'])>60 else ' | AE Tax'),description=p['lead'],path=path,body=body,schemas=[schema,T.breadcrumb_schema(trail)],published=DATE,modified=DATE)
        dest=T.ROOT/path.strip('/')/'index.html'; dest.parent.mkdir(parents=True,exist_ok=True); dest.write_text(output)
    # Keep insertion idempotent and avoid regenerating unrelated content.
    block='<!-- long-tail-best:start -->'+T.related_section([('/compare/'+p['slug']+'/',p['title']) for p in POSTS],'Best firms for specific owner needs')+'<!-- long-tail-best:end -->'
    for hub in ['/compare/']+sorted({p['hub'] for p in POSTS}):
        dest=T.ROOT/hub.strip('/')/'index.html'
        if not dest.exists(): raise FileNotFoundError(dest)
        text=dest.read_text(); text=re.sub(r'<!-- long-tail-best:start -->.*?<!-- long-tail-best:end -->','',text,flags=re.S)
        section=block if hub=='/compare/' else '<!-- long-tail-best:start -->'+T.related_section([('/compare/'+p['slug']+'/',p['title']) for p in POSTS if p['hub']==hub],'Compare advisors for your situation')+'<!-- long-tail-best:end -->'
        dest.write_text(text.replace('</main>',section+'\n</main>'))
    for name in ['sitemap.xml','sitemap-comparisons.xml']:
        dest=T.ROOT/name; text=dest.read_text()
        for p in POSTS:
            url=T.SITE+'/compare/'+p['slug']+'/'
            if '<loc>'+url+'</loc>' not in text:
                text=text.replace('</urlset>','  <url><loc>'+url+'</loc><lastmod>'+DATE+'</lastmod></url>\n</urlset>')
        dest.write_text(text)
    print('Built',len(POSTS),'guides; linked comparison/service hubs and updated sitemaps.')
if __name__=='__main__': main()
