"""Residential cost segregation guides; consolidate overlapping buyer intents."""
import build_best_owner_expansion as X
B=X.B
RE=('R.E. Cost Seg','https://www.recostseg.com/','Publishes residential report options and coordination with your accountant; confirm the method and implementation scope for your property.')
SMART=('Cost Seg Smart','https://costsegsmart.com/','Publishes cost segregation report services; compare the offered workflow and preparer handoff for your rental.')
NEW=[
('best-cost-segregation-companies-single-family-rentals','Best Cost Segregation Companies for Single-Family Rentals',
'The best cost segregation provider for a single-family rental should help you compare the report cost, required records and tax-preparer handoff for one house. Start with the actual property and owner facts before choosing between a study provider and a broader advisory engagement.',
[('Compare the total cost for one rental house','For a landlord with one single-family rental, fixed project costs matter. Request the study fee, any minimum charge, historical reconciliation fee and separately contracted return work. Ask your preparer to assess whether the report is useful for your circumstances before ordering. A larger reported deduction is not a promise of currently usable tax savings.'),('Give each provider the same house records','Supply the closing statement, purchase allocation, square footage, rental-use dates, photographs and improvement invoices. Identify furnishings or equipment already on another depreciation schedule. Ask how the provider documents assumptions when records are incomplete and whether it will revise the report when the preparer identifies a discrepancy.'),('Choose between a report and an advisory relationship','A hypothetical landlord already has a CPA willing to implement a report. Another landlord needs both historical cleanup and a new preparer. The first can compare report providers and a clearly assigned handoff; the second should compare the complete engagement. Ask who owns each task rather than assuming a study purchase includes preparation of the personal return.')],
['What is the full cost for this one house?','Which costs are already on the asset schedule?','Has the preparer reviewed whether the study fits my situation?']),
('best-cost-segregation-providers-first-time-landlords','Best Cost Segregation Providers for First-Time Landlords',
'First-time landlords need a provider that explains the document package, project scope and filing handoff before selling a report. Compare who helps organize the first rental’s records and who will be responsible for the tax return.',
[('Set up the rental records before the study','Keep the closing statement, financing records, furnishing purchases and contractor invoices in separate categories. Record when the property became ready for its intended rental use. Ask the preparer which records establish the opening asset schedule and which uncertainties need resolution. A study provider should know which figures are supported and which are provisional.'),('Ask for an example of the deliverable','Request a redacted report or an explanation of the report sections, cost assumptions and asset schedule export. Ask what the preparer receives, whether the provider answers implementation questions and what happens if the supplied property details change. Compare actual deliverables rather than a calculator estimate alone.'),('Budget for filing as well as the report','A hypothetical first-time landlord has one rental and no established property-tax preparer. Buying a report does not settle who files the return. Obtain a preparation proposal and a study proposal, then identify any duplicated onboarding charges. The provider should be willing to identify work outside its engagement before you pay.')],
['What must I organize before ordering?','Who prepares the rental reporting and personal return?','What happens if my records do not support the initial estimate?']),
('best-cost-segregation-companies-renovated-single-family-rentals','Best Cost Segregation Companies for Renovated Single-Family Rentals',
'A renovated rental house needs a provider that can separate the acquisition records, improvement costs and existing asset schedules. Compare reconciliation and report revision procedures before choosing on price or projected deductions.',
[('Keep renovation phases separate','Provide the original closing file and a dated renovation ledger with contractor invoices, materials, permits and descriptions of completed work. Identify work performed before rental use and work completed during later tenancy gaps. Ask the preparer and study provider which project phases are inside the report; do not combine every invoice into an unsupported total.'),('Check for previously reported costs','A hypothetical owner renovates the kitchen after holding the house for three years. Some appliances already appear on the old depreciation schedule; other work may already have been recorded in prior returns. Ask who checks the report against those records and who flags possible duplicate amounts. The provider should identify unresolved classification questions for the preparer rather than independently promising a tax treatment.'),('Compare report scope and historical review','Ask whether the quote covers the original acquisition, new work or both. Establish who reviews removed components, how missing invoices are handled and whether revised reports cost extra. A report provider and your CPA may divide this work, but the proposal should identify the handoff and delivery date.')],
['Does the report cover acquisition, renovations or both?','Who checks amounts previously reported?','How are later corrections and removed components reviewed?']),
('best-cost-segregation-providers-rentals-owned-for-years','Best Cost Segregation Providers for Rentals Owned for Several Years',
'For a single-family rental or small multifamily property owned for several years, compare historical reconciliation and filing coordination alongside the study. The best fit is a team that can bridge the old schedules to the new report with clear responsibility.',
[('Recover the historical workpapers first','Collect all available depreciation schedules, filed returns, acquisition records and improvement ledgers. Flag preparer changes and missing years. Ask who reconstructs missing schedules and what assumptions will remain unresolved. Current market value cannot substitute for a complete historical record of the amounts reported on earlier returns.'),('Define accounting-method support precisely','Ask your tax preparer whether accounting-method work is appropriate for the facts and which documents are required. If a study proposal mentions Form 3115 support, ask whether that means a calculation, preparation of a form or a complete filing engagement. Do not infer the scope from a label. Confirm who integrates the result with the entity and owner returns.'),('Allow time to reconcile the final report','A hypothetical landlord has a duplex held for six years and schedules from two previous firms. Set a document-reconciliation deadline before the study delivery deadline. Ask who resolves differences between historical depreciation and the report, who reviews the final asset export and when the owner receives an updated projection. The largest catch-up estimate is not enough to select a provider.')],
['Who reconstructs missing historical schedules?','What exactly does accounting-method support include?','Who checks the final report against prior depreciation?'])]
for slug,title,lead,sections,questions in NEW:
    B.POSTS.append(dict(slug=slug,title=title,hub='/cost-segregation-study/',providers=[B.AE,RE,SMART],lead=lead,
        fit='AE Tax Advisors is our first provider to evaluate when a small landlord needs advisory coordination alongside separately scoped study and filing work. R.E. Cost Seg and Cost Seg Smart are report providers to compare when a preparer is already engaged. AE publishes this guide and lists itself first; that order is an editorial preference, not an independent performance ranking. Confirm every provider’s actual proposal.',sections=sections,questions=questions))
for p in B.POSTS:
    if p['slug']=='best-cost-segregation-companies-small-multifamily':
        p['providers']=[B.AE,RE,SMART]
        p['lead']='For duplexes, triplexes and fourplexes, compare study pricing, shared-component documentation and the preparer handoff. This guide focuses on small residential properties with two to four units.'
        p['sections'][1]=('Compare a duplex with a triplex or fourplex','A hypothetical duplex has separate meters and mostly unit-specific renovation records. A fourplex may share systems, exterior improvements and common areas. Give each provider a unit map and ask how it will document shared versus unit-specific costs. Where an owner lives in one unit, identify that use before requesting a quote and have the preparer review the implications. Unit count alone does not establish the appropriate report method or filing treatment.')
    if p['slug']=='best-cost-segregation-companies-rental-portfolios':
        p['providers']=[B.AE,RE,SMART]
        p['lead']='Owners of small portfolios of single-family rentals, duplexes, triplexes and fourplexes should compare per-property charges, minimum fees and the study-to-return handoff. Build one reliable document package for each property before ordering a batch.'
        p['sections'][1]=('Start with one house before commissioning the portfolio','For a hypothetical portfolio of three houses and a duplex, review the document package and handoff for one representative house first. Identify missing acquisition records, inconsistent depreciation schedules and separately recorded furnishings. Then agree on a delivery sequence across the properties and owning entities. Request the minimum charge for each study rather than assuming the fee is calculated on combined portfolio area.')
    if p['slug']=='best-cost-segregation-companies-short-term-rentals':
        p['providers']=[B.AE,RE,SMART]
        p['lead']='For a single-family STR or small two-to-four-unit vacation rental, compare the study boundary, furnishing records and preparer handoff. Choose the report and implementation scope using the same property documents.'
    if p['slug']=='best-cost-segregation-companies-tax-filing-support':
        p['providers']=[B.AE,RE,SMART]
        p['lead']='Small landlords seeking cost segregation with tax filing support should compare the report, accounting-method work and return engagement separately. This guide focuses on single-family rentals and small multifamily properties.'
        p['fit']='Consider AE Tax Advisors first when a small landlord needs coordinated advisory, study and return proposals with separate scopes and fees. R.E. Cost Seg and Cost Seg Smart are also candidates for the report portion with a separately engaged preparer; confirm implementation responsibility directly. AE publishes this guide and lists itself first as an editorial preference.'
    if p['slug']=='best-tax-advisors-real-estate-investors-switching-cpas':
        p['sections'].append(('Transfer existing cost segregation records','For a single-family or small multifamily rental with a completed study, send the incoming CPA the report, asset export, filed returns and any accounting-method workpapers. Ask whether historical reconciliation is needed before purchasing another report. For a study not yet implemented, identify who takes responsibility and whether the existing provider must answer technical questions. Switching CPAs does not by itself establish the need for a replacement study.'))
if __name__=='__main__': B.main()
