#!/usr/bin/env python3
"""Asset-class cost segregation pages and cost seg audit defense content."""

ASSETS = [
{
 "slug": "cost-segregation-for-car-wash",
 "asset": "car wash",
 "h1": "Cost Segregation for Car Washes",
 "title": "Cost Segregation for Car Washes (2026)",
 "lo": 35, "hi": 46,
 "desc": "Car washes reclassify 35% to 46% of depreciable basis, among the highest of any property type, because most of the investment is equipment and site work rather than building structure.",
 "definition": "Cost segregation for a car wash is an engineering study that reallocates the property's cost from the 39-year nonresidential schedule into 5-year, 7-year, and 15-year MACRS classes. Car washes reclassify 35% to 46% of depreciable basis, the highest range of any common commercial asset class, because tunnel equipment, water reclamation systems, vacuum stations, and paving dominate the investment while the building shell is comparatively small.",
 "why": [
  "An express tunnel car wash is essentially a machine with a roof over part of it. The conveyor, wraps, brushes, blowers, dryers, chemical delivery systems, and control electronics are equipment, not building, and they represent a large share of total cost.",
  "Water treatment and reclamation systems, including tanks, pumps, filtration, and separators, are process equipment serving the wash operation rather than the building's plumbing.",
  "Vacuum stations, pay stations, canopies, and signage sit outside the structure entirely and fall into 5-year and 15-year categories.",
  "The site itself carries enormous 15-year value: stacking lanes, queuing pavement, curbing, drainage, retaining walls, lighting, landscaping, and the concrete aprons that take heavy repeated vehicle loading.",
 ],
 "components": {
  "5-year": "tunnel conveyor and wash equipment, blowers and dryers, chemical delivery and mixing systems, water reclamation pumps and filtration, vacuum stations, pay stations and point-of-sale, control systems and sensors, security cameras, and specialty electrical and plumbing serving that equipment",
  "7-year": "office furniture, break room fixtures, and equipment without an assigned class life",
  "15-year": "paving, stacking and queuing lanes, concrete aprons, curbing, sidewalks, drainage and oil-water separators outside the building line, site lighting, landscaping and irrigation, fencing, and exterior signage",
  "39-year": "the tunnel structure itself, foundation, roof, exterior walls, and base building mechanical, electrical, and plumbing",
 },
 "table": [("Express tunnel, single bay", "$3,200,000", "$2,560,000", 42, ),
           ("Express tunnel with 20 vacuum stalls", "$5,800,000", "$4,640,000", 44),
           ("Flex-serve, two tunnels", "$8,500,000", "$6,800,000", 40),
           ("Self-serve, six bays", "$1,400,000", "$1,120,000", 36)],
 "extra": [
  ("Equipment Replacement Cycles Create Repeat Opportunities",
   ["Car wash equipment wears out on a predictable cycle. Conveyors, brushes, wraps, and dryers get replaced every several years under heavy volume, and each replacement is both a new short-life asset and a partial disposition of the component coming out.",
    "A partial disposition election under the tangible property regulations writes off the remaining basis of the retired equipment. Without it, you depreciate the old conveyor alongside the new one for years. On a facility that has been through two or three equipment cycles, cleaning that up frequently produces a deduction independent of any new study.",
    "The repair regulations matter here too. Not every equipment expenditure is a capital improvement. The routine maintenance safe harbor covers work you reasonably expect to perform more than once in a ten-year period, which describes a great deal of car wash maintenance."]),
  ("Passive Loss Treatment for Car Wash Owners",
   ["A car wash is an operating business, not a rental activity, so losses are non-passive for an owner who materially participates. There is no need to navigate the rental exceptions that short-term rental owners rely on.",
    "Where the real estate sits in a separate entity leasing to the operating company, the self-rental rules of Reg. 1.469-2(f)(6) apply: net rental income from a self-rental is recharacterized as non-passive while net rental losses stay passive. A grouping election under Reg. 1.469-4 generally resolves the asymmetry where the entities are commonly controlled and form an appropriate economic unit."]),
 ],
},
{
 "slug": "cost-segregation-for-warehouse",
 "asset": "warehouse",
 "h1": "Cost Segregation for Warehouses and Distribution Facilities",
 "title": "Cost Segregation for Warehouses (2026)",
 "lo": 14, "hi": 26,
 "desc": "Warehouses reclassify 14% to 26% of basis, lower than most asset classes because the building shell dominates, but racking, dock equipment, and site work still produce substantial first-year deductions.",
 "definition": "Cost segregation for a warehouse or distribution facility reallocates the property's cost from the 39-year nonresidential schedule into shorter MACRS classes. Warehouses reclassify 14% to 26% of depreciable basis, a lower range than most commercial property because the structure itself is the majority of the investment, but the absolute dollars are large because warehouse buildings are large.",
 "why": [
  "A warehouse is mostly shell: slab, tilt-up or metal walls, structural frame, and roof. That is 39-year property and no study changes it.",
  "What does reclassify is everything supporting the operation. Dock levelers, dock seals and shelters, dock bumpers, and overhead doors serving loading operations are equipment rather than structure.",
  "Racking systems, mezzanines that are not structural, conveyors, and material handling equipment fall into 5-year and 7-year categories. On a modern distribution facility this can be a very large number.",
  "Specialty electrical serving equipment, high-bay lighting on dedicated circuits, compressed air distribution, and process plumbing separate from the base building systems.",
  "Site work on a distribution property is extensive: truck courts and trailer parking take heavy pavement sections, plus striping, guard shacks, fencing, site lighting, drainage, and landscaping.",
 ],
 "components": {
  "5-year": "racking and shelving systems, conveyors and material handling equipment, dock levelers and seals, security and access control, high-bay lighting on dedicated circuits, compressed air distribution, office furniture and workstations, and specialty electrical serving equipment",
  "7-year": "office furnishings, non-structural mezzanines where facts support it, and equipment without an assigned class life",
  "15-year": "truck court and trailer parking paving, striping, curbing, guard shacks, fencing and gates, site lighting, storm drainage and retention, landscaping and irrigation, and exterior signage",
  "39-year": "structural frame, slab, tilt-up or metal exterior walls, roof, and base building mechanical, electrical, plumbing, and fire suppression",
 },
 "table": [("Small distribution, 40,000 sq ft", "$4,200,000", "$3,400,000", 18),
           ("Mid-size distribution, 120,000 sq ft", "$11,500,000", "$9,300,000", 21),
           ("Cold storage, 80,000 sq ft", "$18,000,000", "$14,400,000", 29),
           ("Large fulfillment, 300,000 sq ft", "$34,000,000", "$27,200,000", 23)],
 "extra": [
  ("Cold Storage Is a Different Asset Class",
   ["A refrigerated warehouse reclassifies far better than a dry one, commonly 26% to 34%, because refrigeration is process equipment rather than building HVAC.",
    "Compressors, condensers, evaporators, refrigerant piping, insulated panel systems, and the controls managing them are equipment serving the freezing and cooling function. So are the specialty electrical feeds and the backup power systems supporting them.",
    "The insulated panel envelope is worth particular attention. Where panels are a non-structural system installed inside the building shell, there is a defensible argument they are not part of the structure. That determination requires engineering documentation, and it moves a large dollar amount."]),
  ("Fire Suppression, Roofs, and Section 179",
   ["Warehouse roofs are large and expensive, and they are 39-year property that bonus depreciation cannot reach. Section 179 can expense them, along with HVAC, fire protection and alarm systems, and security systems on nonresidential buildings.",
    "For a distribution facility replacing a roof or upgrading an ESFR sprinkler system, Section 179 is the only accelerated path, subject to the annual cap, the purchase phase-out, and the taxable income limitation. This is the single most common missed deduction we see on industrial property."]),
 ],
},
{
 "slug": "cost-segregation-for-medical-office",
 "asset": "medical office building",
 "h1": "Cost Segregation for Medical Office Buildings",
 "title": "Cost Segregation for Medical Offices (2026)",
 "lo": 22, "hi": 33,
 "desc": "Medical office buildings reclassify 22% to 33% of basis, driven by specialty plumbing and electrical serving exam and procedure rooms, medical gas, imaging power, and casework.",
 "definition": "Cost segregation for a medical office building reallocates the property's cost from the 39-year nonresidential schedule into 5-year, 7-year, and 15-year MACRS classes. Medical offices reclassify 22% to 33% of depreciable basis, above a standard office building, because exam rooms, procedure suites, imaging, and lab space require specialty plumbing, electrical, and casework that serve equipment rather than the building.",
 "why": [
  "A medical build-out is dense with systems that serve equipment rather than the structure. Dedicated electrical to imaging equipment, isolated power in procedure rooms, and emergency power distribution all follow the equipment they serve.",
  "Plumbing is similarly specialized: sinks in every exam room, eyewash stations, lab sinks with acid-resistant waste, and sterilization equipment connections.",
  "Medical gas systems, vacuum, oxygen, and nitrous distribution, are process systems rather than building plumbing.",
  "Casework and millwork throughout exam rooms, nurse stations, and lab areas is typically 5-year property, and there is a great deal of it.",
  "Lead shielding in imaging rooms, specialty flooring in procedure areas, and dedicated HVAC serving equipment rooms all warrant separate analysis.",
 ],
 "components": {
  "5-year": "exam room and lab casework, medical gas and vacuum distribution, dedicated electrical to imaging and procedure equipment, isolated power systems, specialty plumbing serving equipment, decorative and task lighting, reception and waiting area furnishings, security and access control, and audiovisual and nurse call systems",
  "7-year": "office furniture, and specialty fixtures without an assigned class life",
  "15-year": "parking and drive lanes, covered patient drop-off paving, sidewalks and curbing, site lighting, landscaping and irrigation, drainage, and exterior signage",
  "39-year": "structural frame, foundation, roof, exterior envelope, elevators, and base building mechanical, electrical, plumbing, and life safety",
 },
 "table": [("Single-specialty suite, 4,500 sq ft", "$1,800,000", "$1,500,000", 26),
           ("Multi-specialty building, 18,000 sq ft", "$6,400,000", "$5,200,000", 28),
           ("Surgery center, 12,000 sq ft", "$9,200,000", "$7,400,000", 33),
           ("Imaging center, 8,000 sq ft", "$7,600,000", "$6,100,000", 31)],
 "extra": [
  ("Practice Owners Versus Passive Landlords",
   ["The passive activity analysis depends on who owns what. Where a physician owns the practice and the building through separate entities, the practice is an active business and the building is a rental to a related party.",
    "That triggers the self-rental rules of Reg. 1.469-2(f)(6), under which net rental income from a self-rental is non-passive while net rental losses remain passive. A large first-year depreciation deduction in the property entity can therefore create a suspended loss even though the same taxpayer has substantial active income.",
    "A grouping election under Reg. 1.469-4 treating the rental and the practice as a single activity generally resolves this where the entities are commonly controlled and form an appropriate economic unit. Making that election deliberately, and documenting it with the return, is the difference between a usable deduction and a carryforward."]),
  ("Coordinating With Practice Equipment Purchases",
   ["Medical practices buy substantial equipment, and the building study should be coordinated with it rather than run in isolation.",
    "Equipment purchases interact with the Section 179 cap and phase-out, the mid-quarter convention, and the taxable income limitation. A large fourth-quarter imaging purchase can push more than 40% of the year's personal property into Q4 and trigger the mid-quarter convention on everything placed in service that year.",
    "Where the practice is an S corporation, the deduction also interacts with reasonable compensation and the Section 199A limits. Medical practices are specified service businesses, so above the taxable income thresholds the QBI deduction phases out entirely, which changes the value of accelerating deductions."]),
 ],
},
{
 "slug": "cost-segregation-for-dental-office",
 "asset": "dental office",
 "h1": "Cost Segregation for Dental Offices",
 "title": "Cost Segregation for Dental Offices (2026)",
 "lo": 24, "hi": 35,
 "desc": "Dental offices reclassify 24% to 35% of basis. Operatory plumbing and electrical, vacuum and compressed air, casework, and imaging power drive the result.",
 "definition": "Cost segregation for a dental office reallocates the property's cost from the 39-year nonresidential schedule into shorter MACRS classes. Dental practices reclassify 24% to 35% of depreciable basis because each operatory requires dedicated plumbing, vacuum, compressed air, and electrical serving the chair and delivery unit, and because casework runs throughout the build-out.",
 "why": [
  "Every operatory is a small equipment installation. The chair, delivery unit, light, and monitor each require dedicated electrical, and the operatory needs water, drain, vacuum, and compressed air lines.",
  "Central vacuum and compressed air systems, including pumps, receivers, and distribution piping, are process equipment serving the operatories rather than building plumbing.",
  "Imaging, whether panoramic, cephalometric, or cone beam, requires dedicated power and often lead shielding, both of which warrant separate treatment.",
  "Sterilization areas need specialty plumbing, dedicated electrical, and extensive casework.",
  "Casework and millwork throughout operatories, sterilization, lab, and reception is substantial and generally 5-year property.",
 ],
 "components": {
  "5-year": "operatory casework and delivery unit connections, central vacuum and compressed air systems and distribution, dedicated electrical to chairs and imaging, sterilization casework and specialty plumbing, nitrous oxide distribution, decorative and task lighting, reception and waiting furnishings, audiovisual and practice management systems, and security and access control",
  "7-year": "office furniture and fixtures without an assigned class life",
  "15-year": "parking and drive lanes, sidewalks and curbing, site lighting, landscaping and irrigation, drainage, fencing, and exterior signage",
  "39-year": "structural frame, foundation, roof, exterior envelope, and base building mechanical, electrical, plumbing, and fire protection",
 },
 "table": [("4-operatory practice", "$1,150,000", "$950,000", 29),
           ("8-operatory practice with imaging", "$2,400,000", "$1,950,000", 32),
           ("Multi-site DSO location", "$3,100,000", "$2,500,000", 30),
           ("Oral surgery suite", "$3,800,000", "$3,050,000", 34)],
 "extra": [
  ("Leasehold Build-Outs Versus Owned Buildings",
   ["Many dental practices lease. Where the practice pays for and owns the build-out, the improvements are the practice's asset to depreciate.",
    "Interior improvements to nonresidential property placed in service after the building was first placed in service generally qualify as qualified improvement property with a 15-year recovery period, which is bonus-eligible at 100%. Combined with 5-year equipment and specialty systems, a pure leasehold build-out with no structural work can be close to fully deductible in year one.",
    "Read the lease before the study. Where the landlord funds and owns the improvements, the landlord depreciates them and the tenant may have income or a basis adjustment depending on how the tenant improvement allowance is written.",
    "If the practice relocates or closes before the improvements are fully depreciated, the remaining basis is generally deductible on abandonment. That is a commonly missed deduction."]),
  ("Coordinating With the Practice Entity",
   ["Most dental practices operate as S corporations, which makes the depreciation decision interact with reasonable compensation and Section 199A.",
    "Dentistry is a specified service trade or business, so above the taxable income thresholds the qualified business income deduction phases out entirely regardless of W-2 wages. That changes the calculus: for an owner already above the phase-out, a large depreciation deduction does not cost a QBI deduction they were not going to get.",
    "Below the thresholds, the interaction matters and should be modeled before the depreciation elections are finalized."]),
 ],
},
{
 "slug": "cost-segregation-for-retail",
 "asset": "retail property",
 "h1": "Cost Segregation for Retail and Strip Centers",
 "title": "Cost Segregation for Retail Property (2026)",
 "lo": 20, "hi": 31,
 "desc": "Retail centers reclassify 20% to 31% of basis. Parking and site work usually form the largest bucket, with tenant build-outs and storefront systems adding meaningfully.",
 "definition": "Cost segregation for retail property reallocates a strip center, single-tenant building, or shopping center's cost from the 39-year nonresidential schedule into 5-year, 7-year, and 15-year MACRS classes. Retail reclassifies 20% to 31% of depreciable basis, with parking and site improvements typically the largest single category because retail sites carry more paved area per square foot of building than almost any other asset class.",
 "why": [
  "Retail sites are dominated by parking. A strip center commonly has three to five parking spaces per thousand square feet of building, which means the paved area often exceeds the building footprint. All of it is 15-year land improvement.",
  "Site infrastructure adds more: curbing, sidewalks, cart corrals, light poles, pylon and monument signage, landscaping islands, and storm drainage.",
  "Storefront systems, entry vestibules, and decorative facade elements that are not structural warrant separate analysis.",
  "Tenant build-outs contribute 5-year property and qualified improvement property, though who owns them depends on the lease.",
  "Common area finishes, decorative lighting, and specialty electrical serving signage and tenant meters round out the short-life categories.",
 ],
 "components": {
  "5-year": "decorative and accent lighting, storefront and vestibule systems where non-structural, specialty electrical serving signage and tenant meters, security and camera systems, common area furnishings, and tenant-specific equipment connections",
  "7-year": "office and management furnishings and fixtures without an assigned class life",
  "15-year": "parking lots and striping, drive aisles, curbing and sidewalks, cart corrals, site and parking lot lighting, pylon and monument signage, landscaping and irrigation, storm drainage and retention, and fencing",
  "39-year": "structural frame, foundation, roof, exterior walls, and base building mechanical, electrical, plumbing, and fire protection",
 },
 "table": [("Single-tenant retail, 8,000 sq ft", "$2,600,000", "$2,000,000", 24),
           ("Neighborhood strip center, 25,000 sq ft", "$6,800,000", "$5,100,000", 27),
           ("Grocery-anchored center, 90,000 sq ft", "$21,000,000", "$15,800,000", 29),
           ("Outparcel with drive-through", "$2,200,000", "$1,700,000", 31)],
 "extra": [
  ("Tenant Improvements and Who Owns Them",
   ["The single most important question on a retail study is who paid for and owns each improvement, because that determines who depreciates it.",
    "Where the landlord funds the build-out and owns the improvements, the landlord depreciates them, generally as qualified improvement property over 15 years, bonus-eligible. Where the tenant pays and owns them, the tenant depreciates them.",
    "Tenant improvement allowances complicate this. Depending on how the lease is written, an allowance can be landlord-owned property, tenant income, or a reduction in rent, and each treatment produces a different depreciation outcome.",
    "When a tenant vacates and the landlord demolishes the build-out for the next tenant, a partial disposition election writes off the remaining basis of what was removed. On a center with regular turnover this is a recurring deduction most owners never claim."]),
  ("Roofs, Parking Lots, and What Bonus Cannot Reach",
   ["Retail owners face two large recurring capital items: roofs and parking lots.",
    "A roof on nonresidential property is 39-year property that bonus depreciation cannot touch, but Section 179 specifically includes it as qualified real property along with HVAC, fire protection, and security systems. For an owner replacing a roof, Section 179 is the only accelerated route.",
    "Parking lot work is different. A full reconstruction is a 15-year land improvement eligible for bonus depreciation. Resurfacing and sealcoating frequently qualify as deductible repairs under the routine maintenance safe harbor. Sorting the scope before the work begins is worth far more than analyzing invoices afterward."]),
 ],
},
{
 "slug": "cost-segregation-for-office-building",
 "asset": "office building",
 "h1": "Cost Segregation for Office Buildings",
 "title": "Cost Segregation for Office Buildings (2026)",
 "lo": 15, "hi": 26,
 "desc": "Office buildings reclassify 15% to 26% of basis. Tenant improvements, cabling, decorative finishes, and site work drive the result on a structure-heavy asset class.",
 "definition": "Cost segregation for an office building reallocates the property's cost from the 39-year nonresidential schedule into 5-year, 7-year, and 15-year MACRS classes. Office buildings reclassify 15% to 26% of depreciable basis, a lower range than specialty-use property because the structure and base building systems dominate, though tenant improvements and site work still produce meaningful first-year deductions.",
 "why": [
  "An office building is structure-heavy. Frame, envelope, elevators, and base building mechanical and electrical systems are 39-year property and represent most of the cost.",
  "The reclassifiable value concentrates in tenant improvements: partitions that are demountable rather than structural, carpeting and resilient flooring, millwork, decorative lighting, and window treatments.",
  "Low-voltage systems reclassify well. Data and telephone cabling, audiovisual, access control, security cameras, and the specialty electrical serving them are 5-year property.",
  "Supplemental HVAC serving server rooms and equipment closets is process equipment rather than base building HVAC.",
  "Site work follows the usual pattern: parking, drives, sidewalks, landscaping, site lighting, drainage, and signage as 15-year land improvements.",
 ],
 "components": {
  "5-year": "demountable partitions, carpeting and resilient flooring, decorative and accent lighting, millwork and casework, window treatments, data and telecom cabling, audiovisual systems, access control and security cameras, supplemental HVAC serving equipment rooms, and break room equipment",
  "7-year": "office furniture and systems furniture, and fixtures without an assigned class life",
  "15-year": "parking lots and structures at grade, drive aisles, sidewalks and plazas, site lighting, landscaping and irrigation, storm drainage, fencing, and monument signage",
  "39-year": "structural frame, foundation, roof, curtain wall and envelope, elevators, and base building mechanical, electrical, plumbing, and life safety",
 },
 "table": [("Suburban office, 20,000 sq ft", "$4,400,000", "$3,500,000", 19),
           ("Medical-adjacent office, 30,000 sq ft", "$8,200,000", "$6,600,000", 24),
           ("Flex office with warehouse, 45,000 sq ft", "$9,500,000", "$7,600,000", 22),
           ("Class A multi-tenant, 120,000 sq ft", "$32,000,000", "$25,600,000", 21)],
 "extra": [
  ("Tenant Turnover Creates Recurring Deductions",
   ["Office buildings re-tenant on a cycle, and every re-tenanting is both new short-life property and a disposal of the old build-out.",
    "When a suite is demolished and rebuilt for a new tenant, the partitions, flooring, lighting, and millwork removed frequently still carry undepreciated basis. A partial disposition election writes that basis off in the year of removal.",
    "Without the election, the building's depreciation schedule accumulates layers of improvements that no longer exist, and the owner depreciates all of them. On a multi-tenant building held ten years, cleaning that up often produces a substantial catch-up."]),
  ("Section 163(j) and the ADS Trap",
   ["Office buildings are frequently leveraged, which makes the business interest limitation of Section 163(j) relevant.",
    "An electing real property trade or business escapes the interest limitation, but the price is the Alternative Depreciation System on residential rental, nonresidential real property, and qualified improvement property. ADS property is not eligible for bonus depreciation, and the recovery period for nonresidential real property extends to 40 years.",
    "Making that election without modeling it against the cost segregation outcome can cost far more than the interest deduction it preserves. The election is generally irrevocable, so it deserves analysis before it is made rather than after."]),
 ],
},
]


AUDIT_PAGES = [
{
 "slug": "cost-segregation-audit-defense",
 "h1": "What Happens If Your Cost Segregation Study Is Audited",
 "title": "Cost Segregation Audit Defense Guide (2026)",
 "desc": "What an IRS examination of a cost segregation study actually involves, which allocations get challenged, what documentation decides the outcome, and how a study is defended.",
 "definition": "A cost segregation audit is an IRS examination of the component allocations in a depreciation study, typically reached through examination of the return that claimed the deduction rather than as a standalone review. The IRS evaluates studies against its Cost Segregation Audit Techniques Guide, which identifies the detailed engineering approach as the most reliable method and treats allocations without site inspection or construction document support as weaker positions.",
 "sections": [
  ("A Study Does Not Trigger an Audit by Itself", [
   "There is a persistent belief that claiming cost segregation invites examination. That is not how selection works. Returns are selected through scoring systems, information return mismatches, and random sampling under the National Research Program.",
   "What raises examination risk is a large deduction relative to reported income with thin support behind it. A cost segregation study is support. A study performed properly makes the position stronger, not weaker.",
   "What genuinely does attract scrutiny is the combination that surrounds the study: a substantial loss offsetting wage income, a real estate professional status claim, or a short-term rental material participation position. Those are fact-dependent positions, and facts are what examinations test.",
  ]),
  ("What the IRS Actually Examines", [
   "The Cost Segregation Audit Techniques Guide is public, and it tells you exactly what an examiner is trained to look for.",
   "<strong>The method used.</strong> The guide describes several approaches and ranks their reliability. The detailed engineering approach, using construction documents and a site inspection, sits at the top. Rule-of-thumb and modeled allocations sit well below it.",
   "<strong>Who performed the study.</strong> The guide notes that a quality study is prepared by someone with expertise in both construction and tax law. Credentials and methodology description are examined.",
   "<strong>The allocation of indirect costs.</strong> Soft costs such as architecture, engineering, and permits should be allocated proportionally across asset classes, not loaded into short-life categories.",
   "<strong>Land allocation.</strong> Land is not depreciable, and an aggressive land allocation inflates the entire study. Examiners look for support, typically an appraisal.",
   "<strong>The Section 1245 versus 1250 line.</strong> This is the heart of most disputes: whether a component is personal property or a structural component of the building.",
  ]),
  ("The Allocations That Get Challenged Most", [
   "<strong>Electrical and plumbing serving equipment.</strong> Wiring that serves a specific piece of equipment can be 5-year property; wiring serving the building generally is a structural component. The distinction turns on what the system actually serves, and it requires drawings to substantiate.",
   "<strong>Partitions.</strong> Whether a partition is personal property depends on how it is attached, whether it is designed to be moved, and what damage removal causes. Demountable systems have a defensible argument. Framed and finished walls generally do not.",
   "<strong>HVAC.</strong> Supplemental units serving specific equipment or process loads can be separated. Base building HVAC serving occupant comfort is a structural component.",
   "<strong>Site improvements.</strong> The line between a land improvement, which is 15-year depreciable, and land itself, which is not depreciable, matters. Grading directly supporting a structure may be inseparable from the building; general site grading may be land.",
   "<strong>Millwork and casework.</strong> Built-in cabinetry attached to the structure is frequently challenged, and the answer depends on the specific installation.",
  ]),
  ("What Documentation Decides the Outcome", [
   "Examinations of cost segregation studies are won or lost on documentation assembled before the return was filed, not on argument afterward.",
   "The engineering report itself, describing the method, the personnel, the site visit, and the basis for each allocation.",
   "Construction documents, drawings, specifications, and the contractor's schedule of values where available.",
   "Photographs of the components allocated, particularly for partitions, specialty systems, and site improvements.",
   "The appraisal or other support for the land allocation.",
   "Invoices and the cost basis reconciliation tying the study's total back to the property's actual basis.",
   "For a Form 3115 catch-up, the change in accounting method filing itself, the Section 481(a) computation, and evidence the duplicate copy went to the IRS in Ogden.",
  ]),
  ("How the Position Is Actually Defended", [
   "Representation before the IRS requires a CPA, enrolled agent, or attorney holding a power of attorney on Form 2848. That representative controls the flow of information and limits direct contact between the examiner and the taxpayer, which matters because statements made during an examination cannot be retracted.",
   "The first response to an information document request sets the tone. Producing the engineering report, the drawings, and the basis reconciliation promptly and completely signals that the position was taken carefully.",
   "Where an examiner challenges a specific allocation, the argument is technical and specific: what does this component serve, how is it attached, what happens if it is removed. Generalities do not win these.",
   "If the examination produces an adjustment you disagree with, the case can go to Appeals, which is a separate function evaluating the hazards of litigation rather than re-auditing the facts. Many cost segregation disputes settle there.",
   "The practical point is that the defense is built during the study, not during the audit. A study with a site visit, drawings, photographs, and a clear methodology write-up is straightforward to defend. One without them is not.",
  ]),
  ("Reducing Exposure Before You File", [
   "Use a detailed engineering study on anything material. The cost difference against a modeled allocation is small relative to the exposure.",
   "Get a supportable land allocation, ideally from an appraisal that separates land from improvements.",
   "Make sure the passive activity position is documented contemporaneously. Most of what looks like a cost segregation audit is really a material participation audit.",
   "File the Form 3115 correctly, including the Ogden duplicate, and attach the study.",
   "Keep the workpapers. A study is only as good as the file behind it, and files go missing when firms change.",
  ]),
 ],
 "faqs": [
  ("Does a cost segregation study increase audit risk?",
   "<p>Not by itself. Returns are selected through scoring, information matching, and random sampling. A properly performed study is support for the deduction rather than a red flag. What attracts scrutiny is a large loss offsetting wage income, which usually turns on material participation rather than the study.</p>"),
  ("What does the IRS look for in a cost segregation study?",
   "<p>Its Cost Segregation Audit Techniques Guide identifies the method used, the preparer's qualifications, the allocation of indirect costs, the land allocation, and the classification of components between Section 1245 personal property and Section 1250 structural components. The detailed engineering approach is treated as most reliable.</p>"),
  ("Which allocations are challenged most often?",
   "<p>Electrical and plumbing serving specific equipment, partitions, supplemental versus base building HVAC, the line between land improvements and non-depreciable land, and built-in millwork. Each turns on what the component serves and how it is attached, which is why drawings and photographs matter.</p>"),
  ("Can I defend a DIY or software-generated study?",
   "<p>It is harder. A questionnaire-based allocation without a site visit or construction document review sits low in the reliability hierarchy the IRS applies. It is not automatically disallowed, but there is less to point to when an examiner asks what supports a specific allocation.</p>"),
  ("Who represents me if my study is examined?",
   "<p>A CPA, enrolled agent, or attorney holding a power of attorney on Form 2848. Representation limits direct contact with the examiner and keeps the scope defined. AE Tax Advisors represents clients through examination and Appeals on studies we performed and on studies performed elsewhere.</p>"),
 ],
 "related": [
  ("/cost-segregation-study/", "Cost Segregation Study: How It Works"),
  ("/form-3115-cost-segregation-lookback/", "Form 3115 Cost Segregation Lookback"),
  ("/reps-real-estate-professional-status/", "Real Estate Professional Status"),
  ("/tax-compliance-irs-representation/", "Tax Compliance and IRS Representation"),
  ("/compare/diy-cost-segregation-vs-ae-tax/", "DIY Cost Segregation vs a Professional Study"),
 ],
},
]

# Shared: how a cost segregation engagement actually runs, start to finish.
PROCESS = [
 ("Confirm the deduction is usable before spending anything",
  "This comes first because it decides whether the rest is worth doing. We model material participation, outside basis, the at-risk rules of Section 465, and the excess business loss limitation of Section 461(l). If the loss would be suspended under Section 469, we say so before you pay for a study rather than after."),
 ("Establish the depreciable basis and the land allocation",
  "Purchase price is not depreciable basis. Land is stripped out first, and the allocation needs support, normally an appraisal separating land from improvements. A ten-point swing in the land allocation moves the first-year deduction by tens or hundreds of thousands of dollars, so this step gets as much attention as the component analysis."),
 ("Perform the engineering analysis",
  "An engineer reviews construction documents where they exist, inspects the property, and prices components using recognized cost estimating data. Each component is assigned to its correct MACRS class with a documented basis for the assignment. This is the detailed engineering approach the IRS Cost Segregation Audit Techniques Guide treats as most reliable."),
 ("Identify partial dispositions and repair opportunities",
  "On a property that has been improved or renovated, components that were replaced are often still sitting on the depreciation schedule alongside their replacements. A partial disposition election writes off the remaining basis. At the same time, spending that qualified as a repair under Reg. 1.263(a)-3 rather than a capital improvement gets identified."),
 ("File correctly, including the Form 3115 if the property is not new to you",
  "For a property acquired this year, the study simply informs the depreciation schedule. For a property held longer, the catch-up runs through a change in accounting method: Form 3115, a Section 481(a) adjustment deducted in full in the year of change, the original attached to the return, and a duplicate copy filed separately with the IRS in Ogden."),
 ("Model the exit before you claim the deduction",
  "Accelerated depreciation on personal property is recaptured as ordinary income under Section 1245 on sale. Deducting at 35% and recapturing at 37% is a bad trade. We model the full holding period, including whether a 1031 exchange or the basis step-up at death converts the timing benefit into a permanent one."),
]
