#!/usr/bin/env python3
"""Competitor comparison content.

These are written to be fair. Every firm listed is legitimate and good at what
it does; the comparisons describe different business models rather than
attacking anyone. Competitor pricing is never invented: where a firm quotes per
engagement, the table says so.
"""

# Reusable blocks so every page describes AE Tax consistently.

AE_INTRO = [
 "AE Tax Advisors is a strategic tax advisory firm based in Billings, Montana, working with clients nationwide. The practice centers on business owners, real estate investors, and high-income professionals who have outgrown compliance-only accounting.",
 "The model is deliberately different from a study-only provider. A cost segregation study is one deliverable inside a broader engagement that also covers the passive activity analysis under IRC Section 469, material participation documentation, Form 3115 catch-up filings, entity structuring, reasonable compensation, retirement plan design, and the tax returns themselves.",
 "Pricing is published rather than quoted case by case: $7,800 for the strategic advisory engagement, $2,500 per amended year, $1,500 and up for entity returns, $1,000 and up for individual returns, and $1 per square foot with a $2,000 minimum for cost segregation studies.",
]

AE_WHY = [
 "<strong>The deduction is analyzed before the study is sold.</strong> A large depreciation deduction is worth nothing if the passive activity loss rules suspend it. Every engagement models material participation, basis, at-risk, and the excess business loss limitation before a study is recommended.",
 "<strong>The filing is handled, not handed off.</strong> Form 3115 with its Section 481(a) adjustment, the duplicate Ogden copy, partial disposition elections, and the depreciation schedules all get prepared in-house.",
 "<strong>Prior years get reviewed.</strong> Every engagement opens with a three-year lookback. Recovering overpaid tax from returns already filed frequently covers a meaningful part of the engagement fee.",
 "<strong>Pricing is published.</strong> You can compare the cost against the modeled benefit before committing.",
]

FAQ_SHARED = [
 ("Can I use a specialist firm for the study and AE Tax Advisors for the strategy?",
  "<p>Yes, and that is a common arrangement on larger or unusual properties. We regularly work from a third-party engineering report, prepare the Form 3115 and depreciation schedules, run the passive activity analysis, and file the returns. The study and the strategy do not have to come from the same place.</p>"),
 ("Does a cheaper cost segregation study mean a worse outcome?",
  "<p>Not necessarily, but the method matters more than the price. The IRS Cost Segregation Audit Techniques Guide identifies the detailed engineering approach as the most reliable. A study without site work or construction document review is the first thing challenged on examination, particularly on specialty systems and site improvements.</p>"),
]


COMPETITORS = [

# ---------------------------------------------------------------- 1
{
"slug": "madison-specs-vs-ae-tax",
"name": "Madison SPECS",
"h1": "Madison SPECS vs AE Tax Advisors Cost Segregation",
"title": "Madison SPECS vs AE Tax Advisors (2026)",
"desc": "An honest comparison of Madison SPECS and AE Tax Advisors for cost segregation: engineering methodology, property fit, pricing model, and what each firm does after the study is delivered.",
"short": [
 "Madison SPECS is a high-volume cost segregation specialist and does that work well, particularly on commercial and multifamily assets. It is a study provider: you receive an engineering report and take it to whoever prepares your return.",
 "AE Tax Advisors is a tax advisory firm that performs cost segregation as one component of a broader engagement, and then files the return that uses it.",
 "If you already have a CPA you are happy with and simply need a defensible study on a large asset, Madison SPECS is a strong choice. If nobody is analyzing whether you can actually deduct the loss this year, that is the gap AE Tax fills.",
],
"who": [
 "Madison SPECS is the cost segregation arm of the Madison group of real estate service companies, based in Lakewood, New Jersey. The firm has performed studies across a very large number of properties nationally, with particular depth in multifamily, commercial, and portfolio work.",
 "The methodology is engineering-based, which is the approach the IRS Cost Segregation Audit Techniques Guide treats as most reliable. For institutional owners and syndicators running many assets, the firm's volume experience is a genuine advantage: they have seen the asset class before and the component allocations reflect that.",
 "What Madison SPECS does not do is prepare your tax return, file the Form 3115 that a lookback requires, or analyze whether the resulting loss clears the passive activity rules. That is by design. They are a specialist provider and the tax work belongs to your CPA.",
],
"table": [
 ("Engineering-based study", "Yes", "Yes"),
 ("Typical pricing model", "Quoted per property", "$1/sq ft, $2,000 minimum"),
 ("Best fit property size", "Mid to large commercial, multifamily, portfolios", "Residential, STR, small to mid commercial"),
 ("Portfolio and volume experience", "Extensive", "Moderate"),
 ("Tax return preparation included", "No", "Yes"),
 ("Form 3115 prepared for you", "No", "Yes"),
 ("Section 469 passive activity analysis", "No", "Yes"),
 ("Material participation documentation", "No", "Yes"),
 ("Prior-year amendment recovery", "No", "Yes"),
 ("Entity structuring advice", "No", "Yes"),
 ("Ongoing year-round advisory", "No", "Yes"),
 ("Audit support for the study", "Yes", "Yes"),
 ("Typical turnaround", "Weeks", "Days to weeks"),
],
"pros_them": [
 "Deep experience in multifamily and commercial asset classes",
 "High study volume means well-developed component libraries",
 "Engineering-based methodology with audit support",
 "Comfortable handling portfolios and repeat acquisitions",
],
"cons_them": [
 "Study only: no return preparation, Form 3115, or passive loss analysis",
 "Pricing quoted per property rather than published",
 "You still need a tax advisor to make the deduction usable",
],
"choose_them": "you own mid-size or larger commercial and multifamily assets, already have a CPA handling the tax side, and want a specialist with heavy volume experience in your asset class",
"choose_us": "you want the study, the Form 3115, the passive activity analysis, and the return handled together, or nobody has yet confirmed you can actually use the deduction this year",
"faqs": [
 ("Is AE Tax Advisors better than Madison SPECS?",
  "<p>They solve different problems. Madison SPECS produces engineering studies at volume and does that well, especially on larger commercial and multifamily assets. AE Tax Advisors produces the study and then handles the tax work that turns it into a deduction you can actually claim. If you already have strong tax representation, Madison SPECS may be the better fit for the study itself.</p>"),
 ("How much does Madison SPECS charge for a cost segregation study?",
  "<p>Madison SPECS quotes per property based on size, type, and complexity rather than publishing a rate. AE Tax Advisors publishes $1 per square foot with a $2,000 minimum. Confirm current pricing with either firm before engaging.</p>"),
 ("Who is better for a large apartment complex?",
  "<p>For a large multifamily asset, Madison SPECS has extensive experience in that class and is a strong choice for the engineering work. The question worth asking separately is who will prepare the Form 3115 if the property has been held for years, and who will confirm the loss is not suspended under Section 469.</p>"),
 ("Does Madison SPECS prepare tax returns?",
  "<p>No. Madison SPECS provides the cost segregation study and supporting documentation. Return preparation, Form 3115 filing, and passive activity analysis are handled by your own CPA or advisory firm.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 2
{
"slug": "capstan-tax-strategies-vs-ae-tax",
"name": "Capstan Tax Strategies",
"h1": "Capstan Tax Strategies vs AE Tax Advisors",
"title": "Capstan vs AE Tax Advisors (2026)",
"desc": "Capstan Tax Strategies and AE Tax Advisors compared on cost segregation methodology, tangible property regulations work, energy incentives, pricing model, and who each firm is built to serve.",
"short": [
 "Capstan Tax Strategies is a specialty tax engineering firm with unusually strong depth in the tangible property regulations, and it works primarily alongside CPA firms rather than directly replacing them.",
 "AE Tax Advisors is the CPA-side firm in that equation: strategy, structuring, filings, and returns, with cost segregation performed as part of the engagement.",
 "If your CPA needs a technical partner for a complex repair-versus-capitalization analysis or an energy incentive study, Capstan is excellent. If you need the advisor rather than the technical partner, that is a different role.",
],
"who": [
 "Capstan Tax Strategies is based in Jenkintown, Pennsylvania and focuses on engineering-driven specialty tax work: cost segregation, tangible property regulations consulting, and energy incentives under Section 179D and Section 45L.",
 "The firm is best known for its depth on the tangible property regulations, the framework in Reg. 1.263(a)-3 that determines whether spending is a deductible repair or a capitalized improvement. That analysis is genuinely difficult, it moves large dollar amounts, and it is the kind of work most generalist firms avoid.",
 "Capstan's model is largely to serve CPA firms as a technical resource. Accountants bring them in for the engineering analysis and retain the client relationship and the filings. That is a well-designed model, and it means Capstan is not trying to be your tax advisor.",
],
"table": [
 ("Engineering-based study", "Yes", "Yes"),
 ("Tangible property regulations depth", "Extensive", "Working knowledge"),
 ("Section 179D and 45L energy incentives", "Yes", "Referred out"),
 ("Typical pricing model", "Quoted per engagement", "$1/sq ft, $2,000 minimum"),
 ("Primary client", "CPA firms and their clients", "Property owners and business owners directly"),
 ("Tax return preparation included", "No", "Yes"),
 ("Form 3115 prepared for you", "Supports the CPA", "Yes"),
 ("Section 469 passive activity analysis", "No", "Yes"),
 ("Entity structuring advice", "No", "Yes"),
 ("Reasonable compensation and payroll planning", "No", "Yes"),
 ("Prior-year amendment recovery", "No", "Yes"),
 ("Ongoing year-round advisory", "No", "Yes"),
 ("Typical turnaround", "Weeks", "Days to weeks"),
],
"pros_them": [
 "Exceptional depth on tangible property regulations and repair versus capitalization",
 "Genuine Section 179D and 45L energy incentive capability",
 "Strong technical resource for CPA firms handling complex assets",
 "Engineering-based methodology throughout",
],
"cons_them": [
 "Not structured to be your primary tax advisor",
 "No return preparation or standalone passive activity planning",
 "Pricing quoted per engagement rather than published",
],
"choose_them": "your CPA needs a specialist for a complex repair-versus-capitalization question, a large renovation, or an energy incentive study, and you want to keep your existing tax relationship intact",
"choose_us": "you want a firm that does the planning, the structuring, the filings, and the returns, and treats the study as one part of that rather than the product itself",
"faqs": [
 ("Is AE Tax Advisors better than Capstan Tax Strategies?",
  "<p>They occupy different positions. Capstan is a specialty engineering firm that serves CPA firms as a technical partner, with unusual depth on the tangible property regulations. AE Tax Advisors is the advisory firm that would engage a partner like Capstan on a complex asset. On a straightforward property, AE Tax handles the study directly.</p>"),
 ("What are the tangible property regulations and why do they matter?",
  "<p>They are the rules in Reg. 1.263(a)-3 determining whether spending is a deductible repair or a capitalized improvement, using a betterment, adaptation, and restoration framework plus safe harbors. On a large renovation the distinction can move hundreds of thousands of dollars between an immediate deduction and a 39-year schedule.</p>"),
 ("Does Capstan work directly with property owners?",
  "<p>Capstan's model centers on serving CPA firms, though owners do engage them. If you do not have a CPA handling the strategy, a study alone leaves the passive activity analysis, Form 3115, and return preparation unaddressed.</p>"),
 ("Can AE Tax Advisors handle 179D and 45L energy incentives?",
  "<p>We evaluate whether they apply and coordinate a qualified provider for the certification work, which requires specific modeling and, in some cases, prevailing wage and apprenticeship compliance. We do not perform the certification in-house, and Capstan is a genuinely strong option for that piece.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 3
{
"slug": "bedford-cost-segregation-vs-ae-tax",
"name": "Bedford Cost Segregation",
"h1": "Bedford Cost Segregation vs AE Tax Advisors",
"title": "Bedford Cost Segregation vs AE Tax Advisors (2026)",
"desc": "Bedford Cost Segregation and AE Tax Advisors compared: engineering methodology, fixed asset services, property fit, pricing model, and what happens after the study is delivered.",
"short": [
 "Bedford Cost Segregation is one of the longer-established engineering firms in the field, with a national practice covering cost segregation, fixed asset review, and related specialty tax services.",
 "AE Tax Advisors is an advisory firm that performs studies inside a wider engagement and files the returns that use them.",
 "Bedford is a strong choice for the engineering deliverable on established commercial portfolios. It does not replace a tax advisor.",
],
"who": [
 "Bedford Cost Segregation has been performing engineering-based studies for decades and operates nationally. The practice spans cost segregation, fixed asset reviews, and specialty tax services including energy incentives and research credits.",
 "Longevity matters in this field for a specific reason: an older firm has been through examination cycles and has seen how allocations hold up under scrutiny. Fixed asset review work in particular, cleaning up depreciation schedules that have drifted over years of additions and disposals, is a real strength and is undersupplied in the market.",
 "As with other specialist providers, Bedford delivers the study and supporting documentation. Your CPA prepares the return, files any Form 3115, and determines whether the deduction is usable in the current year.",
],
"table": [
 ("Engineering-based study", "Yes", "Yes"),
 ("Years in the field", "Decades", "Focused practice"),
 ("Fixed asset review and cleanup", "Extensive", "Included in engagement"),
 ("Typical pricing model", "Quoted per property", "$1/sq ft, $2,000 minimum"),
 ("Best fit property size", "Established commercial portfolios", "Residential, STR, small to mid commercial"),
 ("Tax return preparation included", "No", "Yes"),
 ("Form 3115 prepared for you", "No", "Yes"),
 ("Section 469 passive activity analysis", "No", "Yes"),
 ("Real estate professional status planning", "No", "Yes"),
 ("Prior-year amendment recovery", "No", "Yes"),
 ("Entity structuring advice", "No", "Yes"),
 ("Audit support for the study", "Yes", "Yes"),
 ("Typical turnaround", "Weeks", "Days to weeks"),
],
"pros_them": [
 "Long track record and experience across examination cycles",
 "Strong fixed asset review and depreciation schedule cleanup",
 "National coverage across commercial asset classes",
 "Engineering-based methodology with audit support",
],
"cons_them": [
 "Study and engineering only, no tax filing or advisory",
 "Pricing quoted rather than published",
 "Passive activity usability is left to your own advisor",
],
"choose_them": "you hold an established commercial portfolio with messy depreciation schedules and want an experienced engineering firm to clean them up and produce a defensible study",
"choose_us": "you want the study coordinated with the Form 3115, the passive activity analysis, the entity structure, and the return itself",
"faqs": [
 ("Is AE Tax Advisors better than Bedford Cost Segregation?",
  "<p>Not better, different. Bedford is an established engineering firm producing the study and fixed asset analysis. AE Tax Advisors produces the study and then does the tax work that makes it deductible. Owners with strong existing CPA representation often prefer a specialist for the engineering.</p>"),
 ("What is a fixed asset review?",
  "<p>A review of your depreciation schedule to find assets that were misclassified, retired components still being depreciated alongside their replacements, and improvements capitalized that qualified as repairs. On a portfolio held many years it frequently produces deductions independent of any new study.</p>"),
 ("How much does Bedford charge?",
  "<p>Bedford quotes per property based on size and complexity. AE Tax Advisors publishes $1 per square foot with a $2,000 minimum. Confirm current pricing with either firm directly.</p>"),
 ("Can I use a Bedford study with a Form 3115 catch-up?",
  "<p>Yes. A third-party engineering report is exactly what should support a Section 481(a) adjustment. Someone still has to prepare the Form 3115, file the duplicate copy with the IRS in Ogden, and evaluate late partial disposition elections. We do that work regularly from studies produced elsewhere.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 4
{
"slug": "moss-adams-vs-ae-tax",
"name": "Moss Adams",
"h1": "Moss Adams vs AE Tax Advisors for Real Estate Tax Strategy",
"title": "Moss Adams vs AE Tax Advisors (2026)",
"desc": "Moss Adams and AE Tax Advisors compared: firm scale, service breadth, typical client size, cost segregation capability, pricing model, and who each is genuinely built to serve.",
"short": [
 "Moss Adams is a large national accounting and consulting firm serving the middle market, with audit, tax, and advisory under one roof and a specialty tax group that includes cost segregation.",
 "AE Tax Advisors is a focused advisory practice serving individual business owners and real estate investors, with published pricing and direct access to the person doing the work.",
 "The deciding factor is usually scale. If you need audited financial statements, multi-entity consolidations, or international structuring, that is Moss Adams territory. If you need proactive tax strategy on a handful of entities and properties, a large firm's minimums frequently exceed the value delivered.",
],
"who": [
 "Moss Adams is one of the largest accounting firms in the United States, headquartered in Seattle with offices across the country. It serves middle-market and larger companies with assurance, tax, and consulting services, and maintains specialty groups covering credits and incentives, international tax, transaction services, and cost segregation.",
 "For a company that needs an audit, has institutional investors or lenders requiring assured financials, operates across multiple states or countries, or is preparing for a transaction, the breadth is genuinely valuable. Depth in industry verticals is real, and the firm carries the infrastructure to support complex compliance.",
 "The tradeoff is structural rather than a criticism. Large firms are organized around larger engagements. Work is typically delivered through teams with rotating staff, engagement economics favor clients above certain revenue thresholds, and pricing is quoted per engagement based on scope and hours.",
],
"table": [
 ("Firm scale", "Large national firm", "Focused advisory practice"),
 ("Audited financial statements", "Yes", "No"),
 ("International and transfer pricing", "Yes", "Referred out"),
 ("Transaction and M&A due diligence", "Yes", "Strategy only"),
 ("Cost segregation", "Yes, within specialty tax", "Yes, in-house"),
 ("Typical pricing model", "Quoted per engagement", "Published fixed fees"),
 ("Typical client size", "Middle market and larger", "Owners and investors of most sizes"),
 ("Direct access to the strategist", "Through an engagement team", "Direct"),
 ("Section 469 passive activity planning", "Available", "Core focus"),
 ("Short-term rental material participation", "Available", "Core focus"),
 ("Prior-year amendment recovery", "Available", "Standard in every engagement"),
 ("Three-year lookback as standard", "No", "Yes"),
],
"pros_them": [
 "Full service including assurance, international, and transaction work",
 "Deep industry vertical specialization",
 "Infrastructure for complex multi-state and multi-entity compliance",
 "Recognized name for lender and investor requirements",
],
"cons_them": [
 "Engagement economics favor larger clients",
 "Pricing quoted rather than published",
 "Service typically delivered through a rotating team rather than one advisor",
],
"choose_them": "you need audited financials, international structuring, transaction due diligence, or compliance infrastructure for a company of meaningful size",
"choose_us": "you are an owner or investor who wants proactive strategy, published pricing, and direct access to the person building your plan",
"faqs": [
 ("Is AE Tax Advisors better than Moss Adams?",
  "<p>They serve different client profiles. Moss Adams is built for middle-market and larger companies needing assurance, international, and transaction services alongside tax. AE Tax Advisors is built for owners and investors who want proactive planning without the scale and cost of a national firm. Neither is a substitute for the other.</p>"),
 ("Does Moss Adams do cost segregation?",
  "<p>Yes, within its specialty tax practice, and it is capable work. The practical question is whether the engagement size fits. A single short-term rental or a small commercial building may fall below the threshold where a national firm can serve you economically.</p>"),
 ("Do I need a big firm name for my lender?",
  "<p>Sometimes, for audited financial statements or a formal review. For tax planning and return preparation there is generally no such requirement. If your lender requires assurance work, that is a genuine reason to engage a firm like Moss Adams for that specific deliverable.</p>"),
 ("Can I use both firms?",
  "<p>Yes, and it is a reasonable structure. A large firm handles the audit and complex compliance while a focused advisor drives tax strategy and coordinates implementation. We regularly work alongside a client's existing accounting firm rather than replacing it.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 5
{
"slug": "cherry-bekaert-vs-ae-tax",
"name": "Cherry Bekaert",
"h1": "Cherry Bekaert vs AE Tax Advisors for Tax Strategy",
"title": "Cherry Bekaert vs AE Tax Advisors Compared (2026)",
"desc": "Cherry Bekaert and AE Tax Advisors compared on firm scale, credits and incentives capability, cost segregation, pricing model, and the type of client each is structured to serve.",
"short": [
 "Cherry Bekaert is a large national accounting and advisory firm with a well-developed credits and incentives practice that includes cost segregation, research credits, and energy incentives.",
 "AE Tax Advisors is a focused practice for owners and investors, with published pricing and a strategy-first engagement model.",
 "The choice comes down to whether you need enterprise breadth or owner-level strategy.",
],
"who": [
 "Cherry Bekaert is among the larger accounting and advisory firms in the United States, headquartered in Richmond, Virginia, with a national footprint. It provides assurance, tax, and advisory services with meaningful strength in government contracting, healthcare, technology, real estate, and private equity.",
 "Its credits and incentives group covers research credits, energy incentives, and cost segregation. For a company already using the firm for audit or complex compliance, adding a study through the same relationship is efficient and the technical work is sound.",
 "As with any firm of that size, the model is built around larger engagements delivered by teams. That is appropriate for the clients it serves and less economical for an individual investor with one or two properties.",
],
"table": [
 ("Firm scale", "Large national firm", "Focused advisory practice"),
 ("Assurance and audit", "Yes", "No"),
 ("Research and development credits", "Yes", "Evaluated and referred"),
 ("Energy incentives (179D, 45L)", "Yes", "Referred out"),
 ("Cost segregation", "Yes, within credits and incentives", "Yes, in-house"),
 ("Typical pricing model", "Quoted per engagement", "Published fixed fees"),
 ("Typical client size", "Middle market and larger", "Owners and investors of most sizes"),
 ("Direct access to the strategist", "Through an engagement team", "Direct"),
 ("Short-term rental and REPS planning", "Available", "Core focus"),
 ("Three-year lookback as standard", "No", "Yes"),
 ("Entity restructuring and PTET planning", "Yes", "Yes"),
 ("Published pricing", "No", "Yes"),
],
"pros_them": [
 "Broad service line including assurance and industry specialization",
 "Strong credits and incentives practice beyond cost segregation",
 "Capacity for complex multi-state and private equity backed structures",
 "Single relationship covering audit, tax, and advisory",
],
"cons_them": [
 "Built around larger engagements",
 "Pricing quoted rather than published",
 "Individual investor work is not the core market",
],
"choose_them": "you run a company that needs assurance, industry-specific compliance, or a combination of research credits, energy incentives, and cost segregation under one roof",
"choose_us": "you want owner-level tax strategy with published pricing, direct access, and the passive activity analysis handled as a first-class part of the work",
"faqs": [
 ("Is AE Tax Advisors better than Cherry Bekaert?",
  "<p>They target different clients. Cherry Bekaert serves middle-market and larger organizations across assurance, tax, and advisory. AE Tax Advisors serves owners and investors directly with a strategy-first model and published pricing. For an individual with a few properties, a national firm's engagement economics rarely fit.</p>"),
 ("Which is better for research and development credits?",
  "<p>Cherry Bekaert. A dedicated credits and incentives practice with the documentation infrastructure for a defensible study is genuinely valuable, and R&D credits reward that depth. We evaluate whether the credit applies and coordinate a specialist rather than performing the study in-house.</p>"),
 ("Do large firms produce better cost segregation studies?",
  "<p>Not inherently. What matters is whether the study uses the detailed engineering approach with site work and construction document review, which the IRS Cost Segregation Audit Techniques Guide treats as most reliable. Both large firms and focused providers can meet that standard, and both can fall short of it.</p>"),
 ("Can AE Tax Advisors work alongside my current firm?",
  "<p>Yes, and it is common. We frequently drive strategy and implementation while an existing firm retains the audit or a portion of the compliance work, coordinating so that positions are consistent across both.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 6
{
"slug": "kpmg-vs-ae-tax",
"name": "KPMG",
"h1": "KPMG vs AE Tax Advisors for High-Income Tax Planning",
"title": "KPMG vs AE Tax Advisors for High Earners (2026)",
"desc": "KPMG and AE Tax Advisors compared for high-income individuals and business owners: engagement scale, service model, cost segregation and real estate planning, pricing, and practical fit.",
"short": [
 "KPMG is one of the Big Four, built to serve multinational corporations, funds, and very large private wealth structures.",
 "AE Tax Advisors serves individual business owners, real estate investors, and high-income professionals with published pricing.",
 "For most high earners, even at seven-figure income, a Big Four engagement is not the right instrument. The minimums and the service model are calibrated to a much larger scale of problem.",
],
"who": [
 "KPMG is a global professional services network providing audit, tax, and advisory to some of the largest organizations in the world. Its tax practice covers international structuring, transfer pricing, mergers and acquisitions, state and local tax across large footprints, and a private client practice for substantial family wealth.",
 "The technical capability is not in question. For a business with cross-border operations, a fund with complex partner allocations, or a family office managing generational structures across jurisdictions, the depth is unmatched by smaller firms and the work needs that depth.",
 "The mismatch for most individual clients is one of scale. Big Four engagement economics are built around large mandates, work is delivered through layered teams, and the individual real estate strategies that drive results for a physician with two short-term rentals are not what the practice is organized to deliver.",
],
"table": [
 ("Firm scale", "Global Big Four network", "Focused advisory practice"),
 ("International and transfer pricing", "Extensive", "Referred out"),
 ("Fund and partnership structuring at scale", "Extensive", "Owner-level structures"),
 ("Family office and generational planning", "Yes", "Coordinated with counsel"),
 ("Cost segregation for a single property", "Not the core market", "Core service"),
 ("Short-term rental material participation", "Not the core market", "Core focus"),
 ("Typical pricing model", "Quoted, substantial minimums", "Published fixed fees"),
 ("Typical client", "Multinationals, funds, large family wealth", "Owners, investors, high-income professionals"),
 ("Direct access to the strategist", "Through a layered team", "Direct"),
 ("Three-year lookback as standard", "No", "Yes"),
 ("Prior-year amendment recovery", "Available", "Standard in every engagement"),
 ("Published pricing", "No", "Yes"),
],
"pros_them": [
 "Unmatched depth on international and cross-border structuring",
 "Capacity for the largest and most complex mandates",
 "Global footprint with local expertise in most jurisdictions",
 "Recognized name where institutional credibility is required",
],
"cons_them": [
 "Engagement minimums exceed what most individual clients need",
 "Individual real estate strategy is not the practice focus",
 "Layered team delivery rather than direct advisor access",
],
"choose_them": "you have cross-border operations, a fund with complex allocations, or family wealth structures spanning jurisdictions where the cost of getting it wrong justifies Big Four depth",
"choose_us": "you are a high earner or owner whose plan turns on entity structure, depreciation strategy, retirement plan design, and passive activity treatment rather than international structuring",
"faqs": [
 ("Is AE Tax Advisors better than KPMG?",
  "<p>For a multinational or a large fund, no, and it would be dishonest to claim otherwise. For an individual business owner or real estate investor, AE Tax Advisors is built for exactly that work while KPMG is not, and the engagement economics reflect that difference.</p>"),
 ("Do I need a Big Four firm if I earn over $1 million?",
  "<p>Income alone rarely justifies it. What justifies Big Four engagement is structural complexity: cross-border operations, institutional investors, fund structures, or transactions of significant size. A high W-2 income with real estate and a business is squarely in the range a focused advisory firm handles.</p>"),
 ("Does KPMG do cost segregation?",
  "<p>Big Four firms have fixed asset and specialty tax capability, but a single property study is not the market they are structured around. For an individual property, a specialist provider or a focused advisory firm is generally both more economical and more responsive.</p>"),
 ("What if my business grows into needing a large firm?",
  "<p>That transition is normal and we plan for it. Where a client approaches the scale that requires assurance work or international structuring, we coordinate the handoff and continue on the strategy side where it is useful.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 7
{
"slug": "deloitte-tax-vs-ae-tax",
"name": "Deloitte Tax",
"h1": "Deloitte Tax vs AE Tax Advisors for High-Income Clients",
"title": "Deloitte Tax vs AE Tax Advisors Compared (2026)",
"desc": "Deloitte Tax and AE Tax Advisors compared for high-income individuals and business owners: scale, service model, real estate and depreciation strategy, pricing, and realistic fit.",
"short": [
 "Deloitte is the largest professional services organization in the world, and its tax practice serves multinationals, funds, and substantial private wealth.",
 "AE Tax Advisors serves owners, investors, and high-income professionals directly, with published pricing and a strategy-first model.",
 "The comparison is less about quality than about instrument fit. Both do good work; they are built for different problems.",
],
"who": [
 "Deloitte Tax provides business tax, international tax, transfer pricing, mergers and acquisitions, indirect tax, and private wealth services globally. Its technology and process infrastructure for large-scale compliance is a genuine differentiator at enterprise scale.",
 "For a company operating in many jurisdictions, a fund with complex waterfalls, or a family with substantial multi-generational structures, that infrastructure solves problems smaller firms cannot.",
 "For an individual owner or investor, the same infrastructure is overhead. The strategies that move the needle at that level, cost segregation with a proper Section 469 analysis, entity selection, reasonable compensation, cash balance plan design, are well within the reach of a focused practice, and get more attention there.",
],
"table": [
 ("Firm scale", "Largest global network", "Focused advisory practice"),
 ("International and transfer pricing", "Extensive", "Referred out"),
 ("Enterprise compliance technology", "Extensive", "Not applicable"),
 ("Private wealth and family office", "Yes", "Coordinated with counsel"),
 ("Cost segregation for a single property", "Not the core market", "Core service"),
 ("Real estate professional status planning", "Not the core market", "Core focus"),
 ("Typical pricing model", "Quoted, substantial minimums", "Published fixed fees"),
 ("Typical client", "Multinationals, funds, large private wealth", "Owners, investors, high-income professionals"),
 ("Direct access to the strategist", "Through a layered team", "Direct"),
 ("Three-year lookback as standard", "No", "Yes"),
 ("Turnaround on a planning question", "Formal process", "Days"),
 ("Published pricing", "No", "Yes"),
],
"pros_them": [
 "Greatest depth and global reach available",
 "Enterprise-grade compliance infrastructure",
 "Full service across audit, consulting, and tax",
 "Institutional credibility for the largest mandates",
],
"cons_them": [
 "Engagement minimums far above individual client needs",
 "Individual real estate and owner strategy is not the focus",
 "Formal processes slow simple planning questions",
],
"choose_them": "you operate across jurisdictions, manage a fund, or hold family wealth structures where global depth and institutional credibility are requirements",
"choose_us": "your plan turns on depreciation strategy, entity structure, retirement plan design, and passive activity treatment, and you want direct access and published pricing",
"faqs": [
 ("Is AE Tax Advisors better than Deloitte Tax?",
  "<p>For enterprise and cross-border work, no. For individual owners and real estate investors, AE Tax Advisors is purpose-built for that work and Deloitte is not organized around it. The right answer depends entirely on the complexity of what you are solving.</p>"),
 ("Would Deloitte take me as a client?",
  "<p>Possibly, through a private client practice, but engagement minimums are substantial and an individual property strategy is not what the practice is designed to deliver. Many high earners find the scope and cost poorly matched to their actual needs.</p>"),
 ("Who is better for a short-term rental strategy?",
  "<p>A focused firm, in almost every case. The strategy depends on the seven-day average customer use test, material participation documentation, and a cost segregation study, and it needs someone monitoring those facts during the year rather than reviewing them at filing.</p>"),
 ("Can a smaller firm defend an IRS examination?",
  "<p>Yes. Representation before the IRS requires a CPA, enrolled agent, or attorney, not a particular firm size. What matters is the quality of contemporaneous documentation supporting the position, which is built during the year the position is taken.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 8
{
"slug": "the-real-estate-cpa-vs-ae-tax",
"name": "The Real Estate CPA",
"h1": "The Real Estate CPA vs AE Tax Advisors",
"title": "The Real Estate CPA vs AE Tax Advisors (2026)",
"desc": "The Real Estate CPA (Hall CPA) and AE Tax Advisors compared: real estate tax focus, service model, community and education, pricing, and which fits different types of investor.",
"short": [
 "The Real Estate CPA is the brand associated with Hall CPA, a firm built specifically around real estate investors, known for its podcast, education, and investor community alongside tax services.",
 "AE Tax Advisors covers real estate with the same technical depth but also serves operating business owners, with entity structuring, reasonable compensation, and retirement plan design as core work.",
 "Both are genuine specialists. The difference is breadth beyond real estate, and how the engagement is priced and delivered.",
],
"who": [
 "The Real Estate CPA is the public-facing brand of Hall CPA, a firm focused on real estate investors. It has built a substantial audience through its podcast and educational content, and offers tax preparation, advisory, and an investor community.",
 "The technical focus is real: short-term rental material participation, real estate professional status, cost segregation, and passive activity planning are the firm's daily work rather than an occasional request. Investors who engage them are not explaining the seven-day rule to their accountant.",
 "The education and community component is a genuine differentiator. For investors who want to understand the mechanics themselves rather than delegate entirely, that model has real value.",
 "Because Hall CPA and The Real Estate CPA are the same practice, a separate comparison of Hall CPA covers much of the same ground from the firm rather than the brand perspective.",
],
"table": [
 ("Real estate tax specialization", "Yes, primary focus", "Yes, core focus"),
 ("Operating business owner strategy", "Secondary", "Core focus"),
 ("Cost segregation in-house", "Coordinated", "Yes, in-house"),
 ("Short-term rental material participation", "Core focus", "Core focus"),
 ("Real estate professional status planning", "Core focus", "Core focus"),
 ("Entity structuring and PTET", "Yes", "Yes"),
 ("Reasonable compensation analysis", "Yes", "Core focus"),
 ("Cash balance and defined benefit design", "Limited", "Core focus"),
 ("Education, podcast, and community", "Extensive", "Written guides and case studies"),
 ("Three-year lookback as standard", "Varies", "Yes"),
 ("Typical pricing model", "Tiered packages", "Published fixed fees"),
 ("Direct access to the strategist", "Varies by tier", "Direct"),
],
"pros_them": [
 "Deep, genuine real estate tax specialization",
 "Strong educational content and investor community",
 "Well-known brand with a large body of public material",
 "Team depth in short-term rental and REPS planning",
],
"cons_them": [
 "Less centered on operating business owner strategy",
 "Advanced retirement plan design is not the primary focus",
 "Service tier determines how much direct advisor access you get",
],
"choose_them": "you are primarily a real estate investor, value education and community as part of the relationship, and want a firm whose entire identity is built around that niche",
"choose_us": "you have both an operating business and real estate, or your plan needs entity restructuring, reasonable compensation, and retirement plan design alongside the property work",
"faqs": [
 ("Is The Real Estate CPA the same as Hall CPA?",
  "<p>Yes. The Real Estate CPA is the public brand associated with Hall CPA. A separate comparison page covers Hall CPA and addresses much of the same ground from the firm perspective.</p>"),
 ("Is AE Tax Advisors better than The Real Estate CPA?",
  "<p>Both are real specialists in real estate taxation, which puts them well ahead of a generalist firm for this work. The practical difference is breadth: if you also run an operating business where entity structure, reasonable compensation, and retirement plan design matter, AE Tax covers more of that ground. If you are purely an investor and value the education and community model, that is a genuine reason to prefer them.</p>"),
 ("Which is better for short-term rental tax strategy?",
  "<p>Either firm handles this competently, which is not true of most accountants. The strategy hinges on the seven-day average customer use test and material participation documentation, and both firms treat those as core work rather than an unusual request.</p>"),
 ("Do I need a real estate specialist at all?",
  "<p>If real estate drives a meaningful part of your tax position, yes. The most expensive failures we see come from generalist preparers who suspend a deduction the client was entitled to take, or who never raise cost segregation, material participation, or a Form 3115 catch-up at all.</p>"),
] + FAQ_SHARED,
},

# ---------------------------------------------------------------- 9
{
"slug": "diy-cost-segregation-vs-ae-tax",
"name": "DIY Cost Segregation Software",
"h1": "DIY Cost Segregation vs a Professional Study",
"title": "DIY Cost Segregation vs Professional Study (2026)",
"desc": "DIY cost segregation software compared with a professional engineering-based study: cost, methodology, audit exposure, what gets missed, and when the self-service route is genuinely reasonable.",
"short": [
 "DIY cost segregation tools are software products that generate a component allocation from data you enter, at a fraction of the cost of a professional study.",
 "They are legitimate products and there are situations where they are a reasonable choice, particularly on small residential rentals where the dollars at stake are modest.",
 "The risk is not that the software is dishonest. It is that a self-service allocation without site work or construction document review is exactly the kind of study the IRS scrutinizes most, and that the software cannot analyze whether you can deduct the loss at all.",
],
"who": [
 "Several platforms now offer self-service cost segregation, typically producing a report from photographs, a questionnaire, and public property data. Pricing is commonly a few hundred to roughly two thousand dollars, well below a professional study.",
 "For a modest single-family rental where the depreciable basis is small, that economic tradeoff can genuinely make sense. A professional study on a $180,000 basis may cost more than the deduction's present value justifies, and a software allocation is better than no analysis at all.",
 "The limitation is methodological. The IRS Cost Segregation Audit Techniques Guide identifies the detailed engineering approach, involving site inspection and review of construction documents, as the most reliable method. Rule-of-thumb and modeled allocations sit lower in that hierarchy, and the allocations that carry the most value, specialty electrical and plumbing serving specific equipment, site improvements, and non-structural partitions, are precisely the ones a questionnaire cannot substantiate.",
 "The larger gap is that software produces a number, not a strategy. It cannot tell you whether the resulting loss is suspended under Section 469, whether you materially participate, whether a Form 3115 is required for a property held several years, or whether accelerating into Section 1245 property will cost you at sale.",
],
"table": [
 ("Typical cost", "A few hundred to ~$2,000", "$1/sq ft, $2,000 minimum"),
 ("Methodology", "Modeled from questionnaire and photos", "Detailed engineering with document review"),
 ("Site inspection", "No", "Yes"),
 ("Construction document review", "No", "Yes"),
 ("Specialty MEP allocation", "Limited", "Yes"),
 ("Non-structural partition analysis", "No", "Yes"),
 ("Audit support if challenged", "Limited or none", "Yes"),
 ("Form 3115 prepared for you", "No", "Yes"),
 ("Section 469 passive activity analysis", "No", "Yes"),
 ("Material participation documentation", "No", "Yes"),
 ("Recapture and exit modeling", "No", "Yes"),
 ("Tax return preparation", "No", "Yes"),
 ("Best fit", "Small residential rentals, low basis", "Most properties above ~$500K basis"),
],
"pros_them": [
 "Substantially cheaper than a professional study",
 "Fast turnaround, often days",
 "Reasonable for small residential rentals where a full study is not economic",
 "Better than claiming no component depreciation at all",
],
"cons_them": [
 "No site work or construction document review, the weakest position on examination",
 "Misses the specialty systems and site improvements that carry the most value",
 "No passive activity analysis, so the deduction may be unusable",
 "No Form 3115, no recapture modeling, no return preparation",
],
"choose_them": "you own a small residential rental with modest depreciable basis, you have confirmed the loss is usable, and a full study would cost more than the benefit justifies",
"choose_us": "your basis exceeds roughly $500,000, the property has meaningful site work or specialty systems, it has been held for years and needs a Form 3115, or nobody has confirmed the loss is deductible this year",
"faqs": [
 ("Is DIY cost segregation legal?",
  "<p>Yes. Nothing requires a particular provider. What the IRS evaluates is the quality and support behind the allocation, and its Cost Segregation Audit Techniques Guide treats the detailed engineering approach as the most reliable. A modeled allocation is permissible but sits in a weaker position if examined.</p>"),
 ("Will a DIY study trigger an audit?",
  "<p>A study does not trigger an audit by itself. What draws scrutiny is a large deduction with thin support. If your return is examined, the question becomes whether the allocation can be substantiated, and a questionnaire-based report generally offers less to point to than an engineering report with site documentation.</p>"),
 ("How much more does a professional study produce?",
  "<p>It varies by property, but the difference concentrates in categories software cannot substantiate: specialty electrical and plumbing serving equipment, site improvements, and non-structural components. On properties with meaningful site work or build-out, the gap is often several percentage points of basis, which on a $1 million basis is tens of thousands of dollars of first-year deduction.</p>"),
 ("Can I use DIY software and still have you handle the tax side?",
  "<p>Yes. We will review the allocation, tell you honestly whether it is defensible for your property, prepare the Form 3115 if the property has been held for years, run the passive activity analysis, and file the return. Where the allocation looks thin relative to the dollars at stake, we will say so.</p>"),
 ("When is a professional study clearly worth it?",
  "<p>Generally once depreciable basis exceeds roughly $500,000, on any commercial or specialty-use property, on anything with substantial site work, and on any property held several years where a Form 3115 catch-up is on the table. In those cases the incremental deduction typically exceeds the cost difference by a wide margin.</p>"),
],
},

]

# A genuinely useful evaluation checklist, shared across every comparison page.
EVALUATE = [
 ("Ask which method the study uses", "There are several accepted approaches and they are not equivalent. The IRS Cost Segregation Audit Techniques Guide treats the detailed engineering approach, using construction documents and a site inspection, as the most reliable. Ask directly whether someone will inspect the property and review the drawings, or whether the allocation is modeled from photographs and public data. Both are permissible. Only one is easy to defend."),
 ("Ask who runs the passive activity analysis", "This is the question that decides whether the deduction is worth anything this year. A study can produce a $400,000 first-year deduction that is entirely suspended under IRC Section 469. Ask who is confirming that you materially participate, that your average period of customer use is what you believe, and that you clear the basis, at-risk, and excess business loss limits. If the answer is nobody, the study is a number on paper."),
 ("Ask who prepares the Form 3115", "If you have owned the property for more than a year without a study, the catch-up runs through a change in accounting method rather than an amended return. That means a Form 3115, a Section 481(a) adjustment, a duplicate copy filed with the IRS in Ogden, and often a late partial disposition election. Study providers generally do not prepare it. Confirm who will."),
 ("Ask what happens if the study is examined", "Audit support means different things. Ask whether the provider will produce the workpapers, respond to an information document request, and stand behind the allocation, and whether that is included or billed separately. Ask how many of their studies have been examined and what happened."),
 ("Ask for the exit math, not just the year-one number", "Accelerated depreciation on personal property is recaptured as ordinary income under Section 1245 when you sell. If you deduct at 35% and recapture at 37%, you have borrowed from the IRS at a negative spread. A provider who only shows you the first-year deduction is showing you half the picture. Ask for the modeled outcome over your actual holding period, including whether a 1031 exchange or a step-up at death is part of the plan."),
 ("Compare total cost, not study cost", "A cheaper study plus a CPA who does not understand Section 469 is not cheaper. Add up the study, the return preparation, the Form 3115, and the planning work, then weigh that against the modeled after-tax benefit over your holding period. That is the only comparison that means anything."),
]
