#!/usr/bin/env python3
"""Press and media mentions.

Add new entries to the top of PRESS. Each needs title, outlet, url, date (or
None), topic, and a one-sentence summary. The page and its schema rebuild from
this list, so adding a mention is a one-line change plus a rebuild.
"""

PRESS = [
{
 "title": "AE Tax Advisors on Why Audit-Proof Tax Planning Is the Only Kind Worth Paying For",
 "outlet": "NewsBlaze",
 "url": "https://newsblaze.com/business/latest-business/ae-tax-advisors-on-why-audit-proof-tax-planning-is-the-only-kind-worth-paying-for_212588/",
 "topic": "Methodology",
 "summary": "Why a strategy that cannot be defended under examination is not worth its fee, and how statutory citation and documentation discipline separate durable planning from the rest.",
},
{
 "title": "What to Expect from the Discovery Conversation with AE Tax Advisors",
 "outlet": "The American News",
 "url": "https://theamericannews.com/what-to-expect-from-the-discovery-conversation-with-ae-tax-advisors/",
 "topic": "Working With Us",
 "summary": "A walkthrough of the initial discovery call, what gets reviewed, and how a prospective client learns whether proactive planning is worth it before committing.",
},
{
 "title": "Why Some High-Income Professionals Consider Specialized Tax Advisors",
 "outlet": "Artist Weekly",
 "url": "https://artistweekly.com/why-some-high-income-professionals-consider-specialized-tax-advisors/",
 "topic": "High-Income Planning",
 "summary": "Why physicians, attorneys, and executives often outgrow compliance-only accounting, and what a specialized advisory relationship changes.",
},
{
 "title": "How AE Tax Advisors Evaluates Whether a Client Should Convert to a C-Corporation",
 "outlet": "ATL Wire",
 "url": "https://atlwire.com/how-ae-tax-advisors-evaluates-whether-a-client-should-convert-to-a-c-corporation/",
 "topic": "Entity Structuring",
 "summary": "The analysis behind a C-Corp conversion: the 21% rate on retained earnings, the second layer of tax on distributions, and why the decision is modeled over a decade rather than a year.",
},
{
 "title": "How AE Tax Advisors Builds IRC-Cited Tax Plans That Hold Up to Scrutiny",
 "outlet": "BLK News",
 "url": "https://blknews.com/how-ae-tax-advisors-builds-irc-cited-tax-plans-that-hold-up-to-scrutiny/",
 "topic": "Methodology",
 "summary": "Why every recommendation in an AE Tax plan carries a statutory citation, and how that discipline changes what survives examination.",
},
{
 "title": "How AE Tax Advisors Approaches Tax Strategy for Executives at Major Companies",
 "outlet": "CA Gazette",
 "url": "https://cagazette.com/how-ae-tax-advisors-approaches-tax-strategy-for-executives-at-major-companies/",
 "topic": "High-Income Planning",
 "summary": "Planning for corporate executives whose income is concentrated in wages and equity, where traditional deduction strategies do not apply.",
},
{
 "title": "Estate Tax Exemption Planning: How AE Tax Advisors Helps Families Lock In Current Benefits",
 "outlet": "California Observer",
 "url": "https://californiaobserver.com/estate-tax-exemption-planning-how-ae-tax-advisors-helps-families-lock-in-current-benefits/",
 "topic": "Estate and Wealth Transfer",
 "summary": "How families use current exemption levels and the basis step-up under IRC Section 1014 to transfer wealth efficiently across generations.",
},
{
 "title": "Why AE Tax Advisors Begins Every Engagement with a 3-Year Tax Lookback",
 "outlet": "Economic Insider",
 "url": "https://economicinsider.com/why-ae-tax-advisors-begins-every-engagement-with-a-3-year-tax-lookback/",
 "topic": "Methodology",
 "summary": "Why the first step is always reviewing returns already filed, and how recovering overpaid tax frequently funds a meaningful part of the engagement.",
},
{
 "title": "The OBBBA Bonus Depreciation Change Explained: What AE Tax Advisors Wants Business Owners to Understand",
 "outlet": "Celebrity News",
 "url": "https://celebritynews.com/the-obbba-bonus-depreciation-change-explained-what-ae-tax-advisors-wants-business-owners-to-understand/",
 "topic": "Depreciation",
 "summary": "How the One Big Beautiful Bill Act restored 100% bonus depreciation permanently, and why the acquisition date matters more than most owners realize.",
},
{
 "title": "How AE Tax Advisors Helps Attorneys with High-Income Tax Strategy",
 "outlet": "CEO Weekly",
 "url": "https://ceoweekly.com/how-ae-tax-advisors-helps-attorneys-with-high-income-tax-strategy/",
 "topic": "High-Income Planning",
 "summary": "Tax planning for law firm partners and practice owners, covering entity structure, deferred compensation, and the specified service business limits under Section 199A.",
},
{
 "title": "Reasonable Compensation Analysis for S-Corp Owners and How AE Tax Advisors Sets Defensible Salary Levels",
 "outlet": "E Monthly News",
 "url": "https://emonthlynews.com/reasonable-compensation-analysis-for-s-corp-owners-and-how-ae-tax-advisors-sets-defensible-salary-levels/",
 "topic": "S-Corp Planning",
 "summary": "Why there is no 60/40 rule, and how reasonable compensation is priced from market wage data rather than chosen as a percentage of profit.",
},
{
 "title": "How AE Tax Advisors Approaches Bookkeeping and Financial Statement Preparation for Business Owners",
 "outlet": "Entertainment Post",
 "url": "https://entertainmentpost.com/how-ae-tax-advisors-approaches-bookkeeping-and-financial-statement-preparation-for-business-owners/",
 "topic": "Bookkeeping",
 "summary": "Why timely, accurate books are a prerequisite for planning rather than a separate service, and what monthly reconciliation makes possible.",
},
{
 "title": "Understanding the $7,800 AE Tax Advisors Advisory Engagement: What's Included and Why It's Structured This Way",
 "outlet": "Famous Times",
 "url": "https://famoustimes.com/understanding-the-7-800-ae-tax-advisors-advisory-engagement-what-s-included-and-why-it-s-structured-this-way/",
 "topic": "Working With Us",
 "summary": "A breakdown of the advisory engagement: the three-year lookback, the IRC-cited plan, implementation support, and why the fee is published rather than quoted.",
},
{
 "title": "Retirement Plan Design for Business Owners and How AE Tax Advisors Approaches Deductible Contributions",
 "outlet": "Wall Street Times",
 "url": "https://wallstreettimes.com/retirement-plan-design-for-business-owners-and-how-ae-tax-advisors-approaches-deductible-contributions/",
 "topic": "Retirement Planning",
 "summary": "How cash balance and defined benefit plans allow six-figure deductions, and why the contribution scales with the owner's age rather than income alone.",
},
{
 "title": "How AE Tax Advisors Coordinates with Clients' Local CPAs and Attorneys",
 "outlet": "Influencer Daily",
 "url": "https://influencerdaily.com/how-ae-tax-advisors-coordinates-with-clients-local-cpas-and-attorneys/",
 "topic": "Working With Us",
 "summary": "How an advisory engagement works alongside an existing accountant or attorney rather than replacing the relationship.",
},
{
 "title": "Estate, Trust, and Wealth Transfer Planning: How AE Tax Advisors Helps High-Net-Worth Clients Protect Generational Wealth",
 "outlet": "LA Wire",
 "url": "https://lawire.com/estate-trust-and-wealth-transfer-planning-how-ae-tax-advisors-helps-high-net-worth-clients-protect-generational-wealth/",
 "topic": "Estate and Wealth Transfer",
 "summary": "Coordinating income tax strategy with transfer tax planning, and why the basis step-up shapes decisions about holding versus selling appreciated assets.",
},
{
 "title": "IRS Audit Defense: How AE Tax Advisors Represents Clients Before the Internal Revenue Service",
 "outlet": "Market Daily",
 "url": "https://marketdaily.com/irs-audit-defense-how-ae-tax-advisors-represents-clients-before-the-internal-revenue-service/",
 "topic": "IRS Representation",
 "summary": "What representation under a power of attorney involves, how examination scope is controlled, and why contemporaneous documentation decides outcomes.",
},
{
 "title": "Section 179 Expensing: How AE Tax Advisors Helps Business Owners Deduct Equipment Purchases Immediately",
 "outlet": "Music Observer",
 "url": "https://musicobserver.com/section-179-expensing-how-ae-tax-advisors-helps-business-owners-deduct-equipment-purchases-immediately/",
 "topic": "Depreciation",
 "summary": "When Section 179 beats bonus depreciation, including roofs and HVAC on nonresidential buildings that bonus depreciation cannot reach.",
},
{
 "title": "Entity Restructuring Strategy: When AE Tax Advisors Recommends Converting Between LLC, S-Corp, and C-Corp",
 "outlet": "Texas Today",
 "url": "https://texastoday.com/entity-restructuring-strategy-when-ae-tax-advisors-recommends-converting-between-llc-s-corp-and-c-corp/",
 "topic": "Entity Structuring",
 "summary": "The thresholds that justify an S election, when a C-Corp makes sense, and why appreciating real estate rarely belongs in either.",
},
{
 "title": "Multi-State Tax Planning: How AE Tax Advisors Helps Clients Navigate Cross-Jurisdictional Income",
 "outlet": "Miami Wire",
 "url": "https://miamiwire.com/multi-state-tax-planning-how-ae-tax-advisors-helps-clients-navigate-cross-jurisdictional-income/",
 "topic": "Multi-State Tax",
 "summary": "Nexus, apportionment, and residency for clients earning across state lines, including pass-through entity tax elections that restore a federal deduction.",
},
{
 "title": "Form 3115 Catch-Up Depreciation: How AE Tax Advisors Recovers Missed Tax Benefits Without Amending Returns",
 "outlet": "Real Estate Today",
 "url": "https://realestatetoday.com/form-3115-catch-up-depreciation-how-ae-tax-advisors-recovers-missed-tax-benefits-without-amending-returns/",
 "topic": "Depreciation",
 "summary": "How a change in accounting method reaches back to the placed-in-service year with no statute of limitations cap, claimed as a single Section 481(a) adjustment.",
},
{
 "title": "Bonus Depreciation Under OBBBA: What AE Tax Advisors Want Real Estate Investors to Understand",
 "outlet": "San Francisco Post",
 "url": "https://sanfranciscopost.com/bonus-depreciation-under-obbba-what-ae-tax-advisors-want-real-estate-investors-to-understand/",
 "topic": "Depreciation",
 "summary": "What permanent 100% bonus depreciation means for property acquisitions, and why the deduction is worthless if the passive activity rules suspend it.",
},
{
 "title": "Real Estate Professional Status: How AE Tax Advisors Helps Investors Qualify Under IRC 469",
 "outlet": "Portland News",
 "url": "https://portlandnews.com/real-estate-professional-status-how-ae-tax-advisors-helps-investors-qualify-under-irc-469/",
 "topic": "Real Estate Tax",
 "summary": "The two statutory tests under Section 469(c)(7), why the more-than-half test defeats most high earners, and what documentation survives examination.",
},
{
 "title": "Why AE Tax Advisors Built a Virtual Advisory Model for Nationwide Service",
 "outlet": "NetWorth",
 "url": "https://networth.us/why-ae-tax-advisors-built-a-virtual-advisory-model-for-nationwide-service/",
 "topic": "Working With Us",
 "summary": "Why a firm headquartered in Billings, Montana serves clients in every state, and how a virtual model changes access to specialized planning.",
},
{
 "title": "Equity Compensation Strategy: How AE Tax Advisors Helps Tech Professionals Navigate RSUs, ISOs, and Deferred Comp",
 "outlet": "NY Weekly",
 "url": "https://nyweekly.com/business/equity-compensation-strategy-how-ae-tax-advisors-helps-tech-professionals-navigate-rsus-isos-and-deferred-comp/",
 "topic": "High-Income Planning",
 "summary": "Planning around restricted stock units, incentive stock options, and deferred compensation for technology professionals with concentrated equity.",
},
{
 "title": "Tax Strategy for Physicians: How AE Tax Advisors Helps Doctors Reduce High Marginal Rates",
 "outlet": "NY Wire",
 "url": "https://nywire.com/tax-strategy-for-physicians-how-ae-tax-advisors-helps-doctors-reduce-high-marginal-rates/",
 "topic": "High-Income Planning",
 "summary": "Why physician income is difficult to shelter, and how real estate, retirement plan design, and entity structure create deduction capacity.",
},
{
 "title": "AE Tax Advisors on When to Consider S-Corporation Status",
 "outlet": "US Reporter",
 "url": "https://usreporter.com/ae-tax-advisors-on-when-to-consider-s-corporation-status/",
 "topic": "S-Corp Planning",
 "summary": "The profit threshold where an S election starts paying for itself, and the compliance costs and Section 199A interaction that can reverse the answer.",
},
{
 "title": "Why Tax Preparation Is Not Tax Planning and the Distinction AE Tax Advisors Is Built Around",
 "outlet": "Voyage NY",
 "url": "https://voyageny.com/why-tax-preparation-is-not-tax-planning-and-the-distinction-ae-tax-advisors-is-built-around/",
 "topic": "Methodology",
 "summary": "Preparation reports what already happened; planning changes what happens. Why nearly every meaningful strategy has a deadline before year end.",
},
{
 "title": "How AE Tax Advisors Helps Investors Qualify for Active Loss Treatment",
 "outlet": "The Chicago Journal",
 "url": "https://thechicagojournal.com/how-ae-tax-advisors-helps-investors-qualify-for-active-loss-treatment/",
 "topic": "Real Estate Tax",
 "summary": "How the short-term rental exception and material participation tests convert suspended passive losses into deductions against wage income.",
},
{
 "title": "How AE Tax Advisors' Three-Year Tax Lookback Can Help Identify Potentially Missed Deductions",
 "outlet": "US Insider",
 "url": "https://usinsider.com/how-ae-tax-advisors-three-year-tax-lookback-can-help-identify-potentially-missed-deductions/",
 "topic": "Methodology",
 "summary": "How reviewing three years of filed returns surfaces overlooked deductions, misapplied depreciation, and credits that can still be recovered.",
},
]
