"""Maintain canonical owner-service destinations and contextual buyer paths."""
import html, json, re
from pathlib import Path
from site_template import ROOT, SITE, build_page, page_header, section, related_section, faq_section, faq_schema, breadcrumb_schema
from discovery_inventory import eligible, redirects

DATE = '2026-09-26'
PAGES = {
'cost-segregation-study': {
 'title': 'Cost Segregation Study Services & Pricing | AE Tax Advisors',
 'h1': 'Cost Segregation Studies for Property Owners',
 'description': 'Cost segregation studies for rental and commercial property owners. Review pricing, report scope, depreciation implementation and whether deductions are usable.',
 'intro': 'Evaluate your building, the study fee and the deduction you can actually use before committing to a cost segregation study. AE Tax Advisors serves business owners and real estate owners nationwide.',
 'sections': [
 ('Cost segregation services at a glance', '''<p>A cost segregation study identifies supported building costs that belong in shorter depreciation categories. The business decision is whether moving those deductions forward produces enough usable tax benefit to justify the study and implementation costs.</p><p><strong>Published study pricing: $1 per square foot, with a $2,000 minimum per study.</strong> Cost segregation is priced separately from tax advisory. The written proposal defines the property, deliverables, implementation responsibilities and any additional work. <a href="/cost-segregation-study-cost-pricing/">Review study pricing and what to compare</a>.</p><div class="cta-buttons"><a class="btn-cta" href="/discovery/">Discuss Your Property and Study Scope</a></div><p><a href="/cost-segregation-calculator/">Test an illustrative tax-benefit scenario</a></p>'''),
 ('Which property owners should consider a study?', '''<p>Start with a feasibility review if you purchased, constructed or substantially improved income-producing real estate, or if an existing property's depreciation schedule has never been evaluated. Common situations include an owner who bought the building used by their business, a landlord adding rental units, and an investor reviewing a commercial portfolio.</p><ul><li><a href="/cost-segregation-airbnb/">Short-term rental and Airbnb owners</a>: coordinate property classification and participation records with the depreciation analysis.</li><li><a href="/cost-segregation-for-multifamily/">Multifamily owners</a>: reconcile each building, unit improvements and shared site costs.</li><li><a href="/cost-segregation-owner-occupied-commercial/">Business owners with commercial buildings</a>: separate the operating business from the property's ownership and tax treatment.</li><li><a href="/cost-segregation-for-warehouse/">Warehouse owners</a> and <a href="/cost-segregation-for-medical-office/">medical-office owners</a>: identify the actual use of building systems rather than relying on a generic reclassification percentage.</li></ul><p>A purchase price alone cannot establish the deduction or make the study worthwhile. Planned sale timing, land allocation, improvements, prior depreciation, expected income and loss limitations all affect the decision.</p>'''),
 ('What the study and tax implementation need to cover', '''<p>AE's published study service includes an engineering-based analysis, component classification, depreciation calculations and a supporting report. The scope should identify the property and tax years, the records needed, and whether additional improvement histories or prior studies must be reconciled.</p><ol><li><strong>Property and basis review.</strong> Reconcile the closing statement, land allocation, improvement invoices and existing asset schedule.</li><li><strong>Classification support.</strong> Document the function and cost of components, with the rationale for recovery periods.</li><li><strong>Depreciation comparison.</strong> Compare the existing treatment with the proposed schedules and identify elections or restrictions.</li><li><strong>Return coordination.</strong> Establish who updates the tax return and fixed-asset schedule, and whether a method change is needed.</li><li><strong>Support after delivery.</strong> Confirm the scope of preparer questions, report corrections and examination support in the written engagement.</li></ol><p>A report, a Form 3115 catch-up calculation, Form 3115 preparation, and filing the return are different deliverables. Confirm which are included before signing. <a href="/cost-segregation-documents-checklist/">See the document checklist</a> and <a href="/blog/cost-segregation-report-basis-reconciliation/">report-to-basis reconciliation guide</a>.</p>'''),
 ('Bonus depreciation and current-year usability are separate questions', '''<p>Under current federal rules, qualifying property acquired and placed in service after January 19, 2025 generally qualifies for 100% bonus depreciation. Asset eligibility, acquisition facts, required depreciation systems and elections still matter. A study does not make every component eligible, and land is not depreciable. See <a href="https://www.irs.gov/publications/p946">IRS Publication 946</a>.</p><p>A deduction may be limited or suspended under basis, at-risk and passive-activity rules. The property's rental use and the owner's participation must be evaluated independently. See <a href="https://www.irs.gov/publications/p925">IRS Publication 925</a>. State treatment and tax on a later disposition also affect the result.</p><p>Use our <a href="/cost-segregation-calculator/">scenario calculator</a> to distinguish reclassified basis, additional first-year depreciation and an illustrative usable federal benefit. It is an initial model, not a property valuation or a determination of your tax treatment.</p>'''),
 ('Already owned the property for several years?', '''<p>A lookback review starts with the original acquisition and service dates, the depreciation actually claimed, and every subsequent improvement. Do not replace historical rules with the bonus percentage in effect when the study is ordered.</p><p>The correction method depends on whether an accounting method was adopted and on the available procedures. Review <a href="/form-3115-cost-segregation/">Form 3115 and catch-up depreciation</a> with the return preparer before choosing a filing approach. Properties involving exchanges, related parties or changes in ownership need additional basis analysis.</p>'''),
 ('When to pause before ordering a study', '''<p>Pause when you cannot reconcile the purchase price to depreciable basis, cannot establish who owns the assets, lack the prior depreciation schedules, or expect a near-term sale that has not been modeled. The same applies when the projected loss will be suspended and the proposal presents it as immediate cash savings.</p><p>A smaller deduction that is supported and usable can be more valuable than a larger estimate that cannot be implemented. No provider can determine the outcome simply by multiplying the purchase price by a standard percentage.</p>'''),
 ('What to bring to the first conversation', '''<p>Have the property type, approximate square footage, purchase price, acquisition date, placed-in-service date and ownership entity available. Note whether you are planning a sale, recently renovated, acquired from a related party, or completed a 1031 exchange. These facts help define the review.</p><p>Tax returns, closing documents and detailed asset records should be exchanged through the agreed document-collection process after the scope is established. The initial call is an opportunity to identify the next steps, not a promise of a particular deduction.</p>''')],
 'faqs': [('How much does an AE cost segregation study cost?', 'Published pricing is $1 per square foot with a $2,000 minimum per study. The written quote controls the scope and any additional work. Studies are separately priced from advisory.'),('Is Form 3115 filing included?', 'Do not assume that a catch-up calculation includes preparing and filing Form 3115. The proposal should identify the responsible preparer and the fees for implementation.'),('Can a study create an immediate refund?', 'A study creates a classification and depreciation analysis. Whether it changes current tax depends on the return, applicable limitations and filing method. A deduction is not a dollar-for-dollar refund.'),('Can I use my existing CPA?', 'Define the coordination arrangement in the proposal. Identify who reviews the report, updates the asset schedule, prepares any method change and files the return.')],
 'links': [('cost-segregation-study-cost-pricing','Study pricing and proposal comparison'),('cost-segregation-study-timeline-process','Study timeline and process'),('cost-segregation-audit-defense','Study documentation and audit questions'),('real-estate-tax-planning','Real estate tax advisory')]
},
'cost-segregation-study-cost-pricing': {
 'title':'Cost Segregation Study Cost: $1/Sq Ft, $2K Minimum | AE Tax',
 'h1':'Cost Segregation Study Cost and Pricing',
 'description':'AE cost segregation pricing is $1 per square foot with a $2,000 minimum per study. Compare scope, implementation fees and usable value before ordering.',
 'intro':'Compare the total cost of a completed, implemented study—not just the price of a report. Start with AE’s published fee, then confirm the property-specific scope in writing.',
 'sections':[
 ('AE Tax Advisors cost segregation pricing','''<p><strong>$1 per square foot, with a $2,000 minimum per study.</strong> This is AE's published standard pricing, not an industry-wide average. Complex or specialized work may be quoted separately. Confirm the square footage used for billing and the final scope before work begins.</p><ul><li>A 1,500-square-foot property reaches the $2,000 minimum.</li><li>A 3,000-square-foot property has an illustrative standard study fee of $3,000.</li><li>An 8,000-square-foot property has an illustrative standard study fee of $8,000.</li></ul><p>These examples show the pricing formula only. They do not estimate deductions or confirm eligibility. Cost segregation is separate from the $7,800 Strategic Tax Advisory or $9,800 Complex Tax Advisory engagements. <a href="/pricing/">View all published service fees</a>.</p><p><a href="/discovery/" class="btn-cta">Request a Property-Specific Scope</a></p>'''),
 ('What should the proposal include?','''<p>Identify the property address, ownership entity, relevant tax years, acquisition history and improvements. A recently purchased single building and an older portfolio with multiple renovations have different records and reconciliation needs.</p><ul><li><strong>Engineering and documentation:</strong> who performs and reviews the analysis, what records are required, and whether inspection or other documentation is included.</li><li><strong>Report:</strong> asset classifications, allocation of basis, depreciation schedules and supporting rationale.</li><li><strong>Implementation:</strong> who updates the return and asset register, and whether Form 3115 preparation or state adjustments are separately priced.</li><li><strong>Support:</strong> the scope and limits of report corrections, preparer questions and audit support.</li><li><strong>Timing:</strong> the deadline, dependencies, review steps and treatment of incomplete records.</li></ul><p>AE's published study scope includes an engineering-based analysis and a supporting report. A catch-up calculation should not be mistaken for a commitment to prepare and file the method change or every related return.</p>'''),
 ('Compare proposals using the same facts','''<p>Give each provider the same property details and ask them to state assumptions. If one estimate uses acquisition price including land and another uses depreciable basis, their projected percentages cannot be compared directly. The same is true when an estimate includes new renovation costs that another omits.</p><p>Ask for the total engagement cost, not a fee disconnected from return implementation. Confirm whether discounts, travel, additional buildings, amendments, state schedules or missing-record reconstruction change that cost.</p><p><a href="/cost-segregation-study/">Review AE's study process and deliverables</a> before comparing proposals. Use the <a href="/cost-segregation-documents-checklist/">documents checklist</a> to identify information a provider still needs.</p>'''),
 ('How to evaluate whether the study is worth the fee','''<p>Evaluate incremental tax benefit relative to the depreciation available without a study. A projected deduction is not itself tax savings, and suspended deductions do not generate the same immediate cash result as currently usable ones.</p><p>For example, if a reviewed projection showed $12,000 of current incremental tax benefit and the combined study and implementation cost were $4,000, the initial net cash benefit would be $8,000 before later-year effects. This is arithmetic using hypothetical inputs, not an AE client result or a forecast for your property.</p><p>Model the holding period and eventual disposition as well. Accelerated deductions change timing, and future deductions or sale taxes can offset some of today's benefit. The <a href="/cost-segregation-calculator/">calculator</a> provides a limited first-year scenario; a full engagement should examine the broader facts.</p>'''),
 ('When a low quote may become an expensive decision','''<p>A low report price is less useful if the basis does not reconcile, the return preparer cannot implement the schedule, or the proposed loss cannot be used. Conversely, a higher price does not establish better quality. Compare the documented work and accountable deliverables.</p><p>Be cautious about choosing a provider solely because its forecast has the largest reclassification percentage or because it promises that the report is IRS-approved. Ask for the basis of the classification and the specific support promised under the engagement.</p>''')],
 'faqs':[('Is $2,000 the fee for every property?','No. It is the minimum under the published $1-per-square-foot formula. A larger property may have a higher fee, and complex work may be quoted separately.'),('Does the advisory fee include the study?','No. The website prices cost segregation studies separately from Strategic and Complex Tax Advisory.'),('Does the cheapest study offer the best return?','Not necessarily. Compare the fee, report quality, implementation responsibilities, usable deduction and expected holding period together.'),('Can a previously acquired building be quoted?','Yes, a lookback review can be scoped, but the original service dates, prior asset schedule and improvement history are needed. Confirm any additional reconciliation and filing work.')],
 'links':[('cost-segregation-study','Cost segregation study services'),('form-3115-cost-segregation','Lookback study and Form 3115'),('cost-segregation-roi-by-property-type','Property-specific ROI considerations')]
},
'business-owner-tax-planning': {
 'title':'Business Owner Tax Planning & Advisory Services | AE Tax',
 'h1':'Tax Planning for Business Owners',
 'description':'Year-round tax advisory for operating business and practice owners. Coordinate entity structure, owner pay, investments and filing responsibilities. View scope and fees.',
 'intro':'Make tax decisions while you can still act on them. AE Tax Advisors helps operating business and professional practice owners connect their entity structure, cash flow and major transactions to a coordinated tax plan.',
 'sections':[
 ('Who this service is for','''<p>This service is for owners making decisions about a profitable operating business, professional practice or business-owned real estate. It is especially relevant when owner compensation, multiple entities, new equipment, retirement contributions or a planned sale make a return-only approach insufficient.</p><p>The first review should identify your actual decision, its deadline, and the records needed to model it. An S corporation election, a new retirement plan or a building purchase is not automatically the right move because it has a tax benefit.</p><p><strong>Published advisory fees:</strong> Strategic Tax Advisory is $7,800; Complex Tax Advisory is $9,800. Both are listed as two equal payments 30 days apart. Returns, amendments and cost segregation are separately priced. <a href="/pricing/">Review current pricing</a> and the written engagement for the final scope.</p><p><a class="btn-cta" href="/discovery/">Discuss Your Business Tax Plan</a></p>'''),
 ('Decisions to coordinate in one plan','''<ul><li><strong>Entity structure and owner compensation:</strong> compare the operating and administrative consequences of the existing structure before changing it.</li><li><strong>Cash flow and estimated taxes:</strong> connect projected business results to the owner's expected payments.</li><li><strong>Equipment and real estate:</strong> review purchase timing, service dates, financing and depreciation before committing funds.</li><li><strong>Retirement and employee benefits:</strong> evaluate the business's contribution capacity and obligations to eligible employees.</li><li><strong>Acquisitions and exits:</strong> involve the tax team before purchase-price allocation, ownership changes and sale terms are finalized.</li><li><strong>Prior-year issues:</strong> distinguish amendments, accounting-method changes and forward-looking corrections rather than assuming every issue uses the same filing.</li></ul><p>Each recommendation should state the assumptions, expected benefit, implementation cost, deadline and responsible party. The goal is a plan the owner and preparer can execute.</p>'''),
 ('What an advisory engagement should deliver','''<p>AE's published advisory scope includes strategy and planning, entity review, prior-year amendment analysis, return preparation oversight and ongoing advisory support. Complex advisory covers additional multi-entity and real estate planning needs. The engagement should identify which of these apply to you.</p><ol><li><strong>Review:</strong> establish the ownership structure, financial baseline and upcoming decisions.</li><li><strong>Model:</strong> compare viable choices using your records and assumptions.</li><li><strong>Assign:</strong> document the actions, elections, payroll or legal coordination and filing responsibilities.</li><li><strong>Revisit:</strong> update the analysis when income, ownership or plans change.</li></ol><p>Confirm which filings and implementation services are included; oversight is not the same thing as preparing every return. Read <a href="/what-a-tax-advisory-engagement-includes/">what a tax advisory engagement includes</a>.</p>'''),
 ('Business-owner planning resources','''<ul><li><a href="/s-corp-tax-strategy/">S corporation tax planning</a></li><li><a href="/retirement-planning-for-business-owners/">Retirement planning for business owners</a></li><li><a href="/equipment-leasing-section-179/">Equipment purchases, leasing and Section 179</a></li><li><a href="/cost-segregation-owner-occupied-commercial/">Cost segregation for an owner-occupied building</a></li><li><a href="/blog/business-equipment-delivered-not-operational-year-end/">Equipment delivered but not operational at year end</a></li><li><a href="/blog/business-equipment-trade-in-depreciation-recapture/">Equipment trade-ins and depreciation recapture</a></li></ul>'''),
 ('Prepare for an effective first review','''<p>Outline your business activities, entities, ownership percentages, approximate revenue and profit, payroll arrangements and major upcoming decisions. Note the deadlines and whether another CPA, bookkeeper or attorney is already involved.</p><p>After scope is established, the review may require recent returns, year-to-date financials, payroll reports, depreciation schedules and relevant agreements. The value of the analysis depends on complete records and the time available to implement it.</p>''')],
 'faqs':[('Do I need to replace my current CPA?','The engagement should specify how AE and your existing preparer will coordinate. Assign responsibility for returns, implementation and ongoing questions before work starts.'),('Is this for employees without a business?','This service is designed for business and practice owners. Real estate owners can review the separate real estate tax planning service.'),('Are tax returns included in the advisory price?','The website lists return preparation and amendments separately. Your written scope should identify all included and separately priced work.'),('How much will I save?','A reliable estimate requires your records, alternatives and implementation costs. No fixed savings amount applies to every owner.')],
 'links':[('best-tax-advisor-for-business-owners','How to evaluate a business tax advisor'),('real-estate-tax-planning','Tax planning for owners with real estate'),('pricing','Service pricing')]
},
'real-estate-tax-planning': {
 'title':'Real Estate Tax Planning & Advisory for Owners | AE Tax',
 'h1':'Real Estate Tax Planning for Property Owners',
 'description':'Tax advisory for rental, commercial and short-term rental owners. Coordinate depreciation, ownership, acquisitions, sales and filing scope with AE Tax Advisors.',
 'intro':'Plan around the property decisions you are making now: an acquisition, renovation, refinance, change in ownership or sale. AE Tax Advisors connects those decisions with the tax position of the owner and portfolio.',
 'sections':[
 ('Choose the review that matches your property decision','''<p>Real estate planning starts with the owner, the assets and the transaction—not a standard deduction percentage. A first rental, an operating business's building and a multi-state partnership portfolio need different analysis.</p><ul><li><strong>Buying or improving property:</strong> organize basis, dates, ownership and supporting costs before the return is prepared.</li><li><strong>Reviewing an existing portfolio:</strong> reconcile depreciation schedules, carryforwards and prior elections before pursuing new deductions.</li><li><strong>Operating short-term rentals:</strong> assess the activity facts and records alongside depreciation.</li><li><strong>Refinancing or distributing cash:</strong> review the entity and owner's tax basis and debt allocations.</li><li><strong>Selling or exchanging:</strong> model the exit before contracts and deadlines restrict the options.</li></ul><p><a href="/discovery/" class="btn-cta">Discuss Your Property Tax Plan</a></p>'''),
 ('Advisory pricing and separately scoped work','''<p>Published fees are $7,800 for Strategic Tax Advisory and $9,800 for Complex Tax Advisory, payable in two equal installments 30 days apart. The Complex scope lists real estate portfolio planning, cost segregation coordination, STR strategy, 1031 planning and multi-entity issues.</p><p>A cost segregation study is a separate service, published at $1 per square foot with a $2,000 minimum per study. Tax returns and amendments are also separately priced. Review <a href="/pricing/">the full pricing page</a> and confirm the specific properties, entities, years and deliverables in the engagement.</p>'''),
 ('Depreciation, ownership and usable deductions','''<p>Separate the property's depreciation analysis from the owner's ability to use a loss. Participation, basis and at-risk limitations may prevent a paper deduction from reducing current tax. A portfolio review needs the returns and carryforward schedules, not just a closing statement.</p><p>Changing the entity name on a deed does not by itself create a new depreciable purchase. Likewise, the label “Airbnb” does not resolve every classification or filing question. Review the transaction and operating facts before deciding which treatment applies.</p><p><a href="/cost-segregation-study/">Cost segregation services</a> can be evaluated as part of this plan. The study report and the return implementation should reconcile to the same supported property basis.</p>'''),
 ('Planning paths for different owners','''<ul><li><a href="/rental-property-tax-planning/">Long-term rental owners</a>: organize rent, expenses, depreciation and portfolio decisions.</li><li><a href="/short-term-rental-tax-strategy/">Short-term rental owners</a>: evaluate guest stays, participation records and operating details.</li><li><a href="/cost-segregation-owner-occupied-commercial/">Owners of buildings used by their business</a>: coordinate property and operating-entity treatment.</li><li><a href="/1031-exchange-planning/">Owners considering an exchange</a>: address the transaction before closing and coordinate with the appropriate professionals.</li><li><a href="/form-3115-cost-segregation/">Owners reviewing missed depreciation</a>: determine the correct review and correction process.</li><li><a href="/blog/rental-partnership-refinance-distribution-basis/">Rental partnerships refinancing and distributing cash</a>: assemble the owner-level basis analysis.</li></ul>'''),
 ('Records that make the review productive','''<p>Prepare a property list with addresses, ownership entities, acquisition dates, service dates and planned transactions. Identify each state's filing needs and whether the property has personal use, related-party use, prior improvements or a previous cost segregation study.</p><p>After the engagement is scoped, supporting records may include returns, depreciation schedules, closing statements, improvement invoices, debt information and partnership agreements. A clear file prevents double counting and reveals inconsistencies that should be resolved before a new tax position is implemented.</p><p>The resulting plan should name the action, responsible professional, filing deadline and outstanding assumptions. Confirm who prepares each return and how AE coordinates with your existing CPA or bookkeeper.</p>''')],
 'faqs':[('Does cost segregation belong in every property plan?','No. Compare the study and implementation costs with the expected usable benefit and holding period. A feasibility review may conclude that another issue should be addressed first.'),('Can AE review properties in several states?','The published Complex advisory scope includes multi-state filing coordination. Confirm the states, entities and separately priced returns in the written engagement.'),('Is this service only for full-time real estate professionals?','No. It is for real estate owners, including business owners with property. The planning review must determine which rules and limitations apply to the particular owner.'),('What happens on the first call?','Discuss your portfolio, upcoming transaction, timing and current tax support. The next step is to define the records, scope and responsibilities needed for a substantive review.')],
 'links':[('real-estate-investor-cpa','Choosing tax support for a real estate portfolio'),('cost-segregation-study-cost-pricing','Cost segregation fees and scope'),('business-owner-tax-planning','Business-owner advisory')]
}}


def main():
 for slug, data in PAGES.items():
  p = ROOT/slug/'index.html'
  original = p.read_text()
  # Preserve established article discovery links while replacing the service narrative.
  related = []
  for block in re.findall(r'<section\b.*?</section>',original,re.S):
   heading = re.search(r'<h2[^>]*>(.*?)</h2>',block,re.S)
   if heading and any(label in heading.group(1) for label in ['Related Articles','Tax Decisions Before','Owner decisions','Property Transaction','Explore Specific','Real Estate Tax Planning by Situation']):
    related.append(block)
  path='/'+slug+'/'
  trail=[('Home','/'),('Services','/services/'),(data['h1'],path)]
  faqs=[(q,'<p>'+html.escape(a)+'</p>') for q,a in data['faqs']]
  body=page_header(h1=data['h1'],subtitle=data['intro'],trail=trail,cta='Schedule a Discovery Call')
  body+='\n'.join(section(h,b) for h,b in data['sections'])
  body+=faq_section(faqs)+related_section([('/'+s+'/',label) for s,label in data['links']])+''.join(related)
  schemas=[breadcrumb_schema(trail),faq_schema(faqs),{'@context':'https://schema.org','@type':'Service','@id':SITE+path+'#service','name':data['h1'],'url':SITE+path,'description':data['description'],'provider':{'@type':'Organization','name':'AE Tax Advisors','url':SITE+'/'},'areaServed':{'@type':'Country','name':'United States'}}]
  p.write_text(build_page(title=data['title'],description=data['description'],path=path,body=body,schemas=schemas,published='2026-09-12',modified=DATE,og_type='website'))
 # Two substantially overlapping pricing articles now resolve to one complete answer.
 config=ROOT/'vercel.json';v=json.loads(config.read_text())
 old='/cost-segregation-pricing/';new='/cost-segregation-study-cost-pricing/'
 v['redirects']=[r for r in v['redirects'] if r['source'].rstrip('/')!=old.rstrip('/')]
 v['redirects'].insert(0,{'source':old,'destination':new,'statusCode':301})
 config.write_text(json.dumps(v,indent=2)+'\n')
 for p in ROOT.rglob('*.html'):
  s=p.read_text();updated=s.replace('href="'+old+'"','href="'+new+'"')
  if s!=updated:p.write_text(updated)
 print('Rebuilt',len(PAGES),'commercial destinations; consolidated pricing intent')

if __name__=='__main__':main()
