"""Buyer education matched to the sourced service categories, without attributing unverified capabilities."""
import re,html
E=lambda x:html.escape(str(x),quote=True)
SCOPES=[
 ('real estate|rental|cost seg|property','Real estate and rental activities','A property engagement can involve an owner return, operating entities, property-level records, and a separate specialist study. Ask the candidate to identify which pieces it will actually deliver. A study vendor, return preparer, and planning advisor may have different responsibilities.', ['Which property records and prior depreciation schedules will you review before proposing work?','Who coordinates any specialist study with the professional filing the returns?','Will the written scope address the interaction between the operating business and property interests?'], 'real-estate'),
 ('construction|contractor','Construction and contracting businesses','Contract-based businesses often need their advisor to understand job records, project timing, equipment, and owner compensation. A directory category does not establish experience with your contract type. Bring a representative project summary and ask the firm to explain the work it would perform.', ['How do you work with job-cost reports and the bookkeeper maintaining them?','Which parts of a multi-state project fall inside the proposed engagement?','Who reviews major equipment purchases and project cash-flow assumptions?'], 'construction'),
 ('international|cross.border|expatriate','International or cross-border matters','International work requires a clear boundary between domestic advice, foreign-country advice, and information reporting. A broad tax-service description does not show that every jurisdiction is covered. Identify the countries, entities, and reporting questions before requesting a fee.', ['Which countries and entity types have you handled in comparable engagements?','Will a separate in-country advisor be required and who coordinates that relationship?','Which filings and information-gathering tasks are explicitly included?'], 'international'),
 ('estate|trust|succession|exit','Ownership transitions and succession','A transition project involves decisions that may belong to different professionals: the tax advisor, transaction attorney, valuation professional, and financial planner. Clarify who models the alternatives and who implements the chosen documents. Do not assume a firm’s general planning category includes legal drafting or valuation.', ['At what stage should the tax professional join the transaction or succession discussion?','Who owns the written timeline and coordinates with counsel?','Does the scope include reviewing assumptions when deal terms change?'], 'succession'),
 ('payroll|bookkeep|accounting|outsourc|cfo','Ongoing accounting and planning coordination','Bookkeeping, payroll, financial reporting, return preparation, and forward-looking planning are different deliverables. If you need several, ask for a responsibility map rather than assuming one monthly fee includes every function. Reliable planning conversations start with records that are current enough to support the decisions.', ['Who closes the books, and when will usable reports be available?','How are bookkeeping adjustments communicated to the return preparer?','Are owner planning meetings and written recommendations part of the fee or separate work?'], 'accounting'),
 ('business|corporate|entity|s.corp|partnership','Business-owner advisory','The relevant comparison is the complete business-and-owner scope: entities, owners, jurisdictions, decision calendar, and implementation responsibility. Ask candidates to show how their proposal connects those pieces. A general business-tax listing does not establish a year-round planning engagement.', ['Will the proposal cover both business entities and the owners’ related planning questions?','Who will produce projections and explain their assumptions?','How are recommendations handed to the people responsible for completing them?'], 'business'),
 ('retire|benefit','Retirement and benefit coordination','Retirement and benefit discussions can require coordination with a plan administrator and other specialists. Ask the advisor to separate tax analysis from administration, investment advice, and legal work. Establish which assumptions depend on payroll or employee information before relying on a proposal.', ['Which employee and owner information is needed for the initial review?','Who coordinates with the plan administrator and confirms implementation dates?','Which ongoing administration tasks are excluded from the advisory fee?'], 'retirement')]
def profile_context(f, firms, guides):
 text=' '.join(f.get('services',[]))+' '+(f.get('description') or '');selected=[x for x in SCOPES if re.search(x[0],text,re.I)][:3]
 out='<h2>Build a decision-ready brief for '+E(f['name'])+'</h2><p>Start your inquiry with the work you need, rather than a request for a generic tax-savings estimate. For this listing, the documented location is '+E(f['location'])+'. Ask whether the firm can serve each jurisdiction relevant to your business; a listed office does not establish nationwide coverage.</p>'
 if selected:
  out+='<p>The following research questions are matched to service words in the cited listing. They are questions to investigate, not independently verified capabilities or recommendations about your tax position.</p>'
  for _,title,context,qs,_ in selected:out+='<h3>'+title+'</h3><p>'+context+'</p><ul>'+''.join('<li>'+q+'</li>' for q in qs)+'</ul>'
 else:
  out+='<h3>When the source is only a directory record</h3><p>The available evidence does not support a detailed specialty narrative for this firm. First ask for its current service list, the professionals who would do the work, and an example of the deliverables offered to a business like yours. Once those facts are supplied, compare the proposed work with your actual needs rather than treating an unknown service as absent.</p>'
 out+='<h3>Evaluate the answer, not just the introduction</h3><p>A useful response identifies the responsible professional, records required, deliverables, timing, exclusions, and complete fee. If a response promises an outcome before reviewing your facts, ask which assumptions support it and what could change the conclusion. Keep open questions on the proposal worksheet until you receive a written answer.</p><p><a href="/compare/">Compare written scopes</a> · <a href="/comparisons/ae-evidence-and-fit/">Review AE’s documented offering and fit</a> · <a href="/guides/verify-tax-adviser-credentials/">Check the responsible professional’s credentials</a>.</p>'
 peers=[x for x in firms if x['slug']!=f['slug'] and f.get('state') and x.get('state')==f.get('state')][:4]
 if peers:out+='<h3>Continue the local research</h3><p>Other source-listed firms with the same state label include '+', '.join('<a href="/firms/'+x['slug']+'/">'+E(x['name'])+'</a>' for x in peers)+'. These are research links, not endorsements or claims that the firms offer equivalent services. Compare each source and written scope separately.</p>'
 return out
