"""Additional original narrative for new guides and replacement worked examples."""
EXTRA = {
6: [
('Before purchase: preserve options and collect the right facts', '''Before a purchase closes, ask what records the study provider and preparer will need. Obtain property information, a preliminary financing structure and a list of included furnishings or equipment. The useful output at this stage is a feasibility discussion with explicit assumptions, not a final depreciation schedule. If the transaction involves a related seller, an exchange or an entity-interest purchase, raise that issue before relying on an ordinary asset-purchase illustration.'''),
('After closing: replace estimates with transaction evidence', '''Once the transaction is complete, reconcile the final settlement statement, capitalizable costs, supported land allocation and improvements. Record when the property and later-added assets are ready and available for their intended use. A contract price may differ from the total supported basis, and a building can enter service on a different date from a later furnishing purchase. Provide those differences to the study team before the report is finalized.'''),
('After filing: coordinate the procedural review', '''If depreciation has already been reported, collect the existing schedules before commissioning overlapping work. The preparer must determine whether an accounting method change, an amendment or another correction is appropriate. Preserve elections from the original returns. A new report is evidence for the analysis; it is not permission to replace historical dates or apply today's bonus rules to older acquisitions. If a sale is imminent, review the sale-year procedure and economics first.''')],
7: [
('Locate the taxpayer and the asset', '''Start with the deed, entity classification and return on which depreciation is claimed. A disregarded LLC, partnership and S corporation have different reporting paths. For an entity-owned property, the owner's K-1 is one input, not the entire deductibility analysis. Obtain basis schedules and financing information before assuming a loss allocation will reach the personal return. Keep ownership changes visible in the analysis.'''),
('Identify why a deduction could be deferred', '''Losses can encounter more than one restriction. Basis and at-risk limits may apply before passive activity rules, with further limits relevant afterward. A dollar deferred under one rule is not necessarily released by an event relevant to another. Ask the preparer to label the limitation and carryforward rather than showing one unexplained suspended-loss balance. Future projections should use that same distinction.'''),
('Request two outputs from the projection', '''The first output is the property or entity's depreciation calculation. The second is the deduction currently usable by the taxpayer and its modeled tax effect. Reconcile the two explicitly. If a key fact is unresolved, show an alternative scenario instead of silently assuming the favorable answer. Include state treatment and the expected holding period before using the estimate to make a purchase or financing decision.''')],
12: [
('Create a unit map before allocating cost', '''List each unit, its approximate size, whether it is rented or personally occupied, and the periods of use during the year. Identify common halls, parking, storage and shared mechanical systems. Different allocations may be appropriate for different expenses. A unit with more space or different facilities is not automatically one-quarter of a fourplex merely because there are four doors.'''),
('Keep acquisition and later unit turns separate', '''The purchase reconciliation establishes the initial basis. Subsequent unit renovations have their own invoices and service dates. Label appliance replacements, flooring projects and shared improvements by the space they serve. When records describe work only as unit renovation, ask for the underlying scope and itemization. This helps the preparer identify capitalization, asset categories and any relevant replaced components.'''),
('Plan for changes in occupancy', '''If the owner moves into a previously rented unit, or a personal unit becomes available for rent, notify the preparer with the date and supporting facts. The original study should remain part of the history; it is not a substitute for recording later changes in use. Keep the unit map, depreciation schedules and occupancy records together so the next return and eventual sale use consistent assumptions.''')],
14: [
('Begin with legal ownership boundaries', '''Request the deed and relevant condominium declaration or townhome ownership documents. Identify the unit, land interest, exclusive-use areas and shared facilities. The physical appearance of a building does not determine who owns an asset for tax purposes. If an association purchases or maintains a facility, distinguish its expenditure from the unit owner's supported basis before assigning a cost to the study.'''),
('Evaluate association charges by purpose', '''Regular dues, reserve contributions and special assessments may pay for different things. Keep the association's explanation of the project and any cost detail. A large assessment for replacing common infrastructure is not automatically a current repair expense. Conversely, not every association payment should be added to the unit's depreciable basis. The preparer needs the purpose and ownership facts to evaluate treatment.'''),
('Reconcile unit furnishings and personal use', '''Separately purchased beds, appliances or electronics may already appear on the owner's schedule. Match them against the report before importing assets. Preserve the unit's actual rental and personal-use calendar, especially when the owner uses the property seasonally. Ownership of a condominium rather than a house does not remove the vacation-home rules or establish that a generated loss is currently deductible.''')],
15: [
('Describe the building and site instead of applying a cabin percentage', '''Collect the cabin's plans or available property records, photographs, acquisition documents and major improvement invoices. Describe access roads, utilities, outdoor amenities and attachments clearly. A classification depends on the asset's actual function and applicable law. Avoid treating wood construction, remote location or vacation use as a reason that the entire structure qualifies for accelerated depreciation.'''),
('Separate later amenities from the original acquisition', '''Cabin owners often add hot tubs, game equipment, fire features or furniture after closing. Preserve those invoices and installation dates independently. Some items may need separate asset analysis; others may involve structural improvements or land. The study should reconcile assets acquired with the property and assets added later, without inventing basis from the current replacement value of the finished rental.'''),
('Use the operating calendar as a separate tax record', '''Mountain cabins may have seasonal access limitations, personal stays and long gaps between bookings. Keep evidence of when the property was ready and held out for rent, as well as the owner's actual use. Participation and average-use analysis are separate from asset classification. Before committing to a study, explain the management arrangement and expected holding period so the projected deduction can be evaluated on the return.''')],
16: [
('Start with land and the acquisition history', '''For a beach rental, the parcel can represent a substantial part of the transaction value. Support the land allocation using appropriate valuation evidence rather than borrowing a percentage from an unrelated property. Keep the final closing statement and any separately purchased furnishings. The current value of a desirable location is not an additional depreciable asset created by ordering a study.'''),
('Keep storm work and routine turnover records distinct', '''A coastal property may require recurring maintenance and occasional major restoration. Retain insurance correspondence, contractor scopes, before-and-after photographs and invoices. Separate restoration from elective upgrades where the records support that distinction. Do not count an expenditure as both an operating expense and an improvement in the asset schedule. Insurance recoveries can create additional tax questions that the study alone does not resolve.'''),
('Review seasonal availability and owner visits', '''Track when the rental is available, when it is unavailable for substantial work and when owners or relatives use it. A seasonal booking calendar is not a substitute for personal-use records. Furnishings installed after a restoration can have different dates from the original property. Share the operational history with the tax preparer so the depreciation, expense and loss analyses use the same facts.''')],
44: [
('Ask for the detailed export', '''A depreciation schedule may include federal, state, book and alternative-minimum-tax views. Request the complete asset-level export rather than only a summary page. Ask whether disposed assets, accumulated depreciation, conventions and election information are included. The outgoing preparer may have these records even when they were not attached to the copies of filed returns supplied to the owner.'''),
('Build an evidence hierarchy', '''Use closing documents, actual invoices and prior prepared workpapers before relying on recollection. Bank records can help identify payments, but may not explain what was purchased or whether an amount included financing or personal costs. Label any estimate and the method used to derive it. Keep a separate unresolved-items list so an assumed value does not quietly become an established fact in later years.'''),
('Reconcile before correcting', '''Compare reconstructed annual depreciation with the amounts on filed returns and identify differences by asset and year. Determine whether an apparent omission was actually an election, a limitation or an asset reported elsewhere. The preparer can then evaluate the correct procedure. Do not import a new study into an empty register and ignore depreciation that may already have been claimed.''')],
47: [
('Use one cost register for several source documents', '''Assign an internal reference to each material acquisition or improvement. Link that reference to the invoice, purchase allocation, report entry and existing depreciation asset. The same expenditure may legitimately appear in several documents, but it should not become several deductions. Preserve the record of prior expensing elections as well as depreciation, because an already expensed asset still needs reconciliation.'''),
('Distinguish replacements from duplicate descriptions', '''Two refrigerators with the same description may be different assets purchased years apart, while a single refrigerator may be described differently by the seller, bookkeeper and study provider. Use dates, locations, invoice details and serial numbers when available. If an old item was removed, identify its disposition for professional review instead of simply deleting the old record to make totals match.'''),
('Approve the final bridge before filing', '''The final schedule should explain original basis, supported additions, prior treatment, reclassifications and any dispositions. Resolve differences with the provider and preparer while the documents are available. Keep the completed matching table with the report so a future accountant understands why a line was adjusted. A clean total without an explanation is less useful than a traceable reconciliation.''')],
62: [
('Compare ownership choices before forming an entity', '''List the proposed owners, their tax classifications and the parties responsible for financing. Separate legal liability goals from federal tax treatment. A single-member LLC may be disregarded, while an entity taxed as a corporation can create different distribution and exit consequences. Obtain legal and lender input alongside the tax analysis so the selected structure fits the transaction.'''),
('Write down rent and expense responsibilities', '''Specify who pays taxes, insurance, repairs, improvements and utilities. Support rent using relevant market information and document changes when terms change. The operating business and property owner should use consistent records. If one pays the other's obligation, retain the reason and accounting treatment rather than treating all transfers as rent by default.'''),
('Evaluate the eventual sale or separation', '''Consider whether the owner expects to sell the operating company, retain the building, admit a partner or transfer an interest to family. Each can affect the usefulness of the initial structure. Review self-rental and any permitted grouping decisions with those goals in mind. A structure should be assessed across ownership and exit, rather than selected solely to create a current rent deduction.''')],
64: [
('Identify the income you want the loss to offset', '''Business income may come directly from a sole proprietorship or through an entity. Rental losses likewise can arise directly or through a K-1. Record the taxpayer and activity producing each amount. The labels active business and investment property are not enough to decide deductibility. Obtain the relevant returns, ownership schedules and participation facts before combining the numbers.'''),
('Evaluate the applicable path independently', '''A long-term rental, a qualifying short-stay activity and a rental owned by a qualifying real estate professional can involve different passive-activity analyses. Even a nonpassive result does not remove every other loss limitation. Self-rental rules and grouping restrictions also need attention where the operating business uses the property. Ask the advisor to identify the specific rule supporting the proposed offset.'''),
('Use a conditional projection for unresolved facts', '''If qualification depends on participation that has not occurred or records that have not been reviewed, show the deduction as conditional. Compare cash flow if the loss is currently usable with cash flow if it is deferred. Keep separate carryforwards where multiple limitations apply. This helps prevent an acquisition or estimated-tax decision from relying on a tax benefit that has not been established.''')],
66: [
('Review the existing corporation before changing ownership', '''Identify whether the corporation has always been an S corporation, who owns its shares and how the property is financed. Review the property's tax basis and current value. Prior C corporation history, shareholder basis and other facts can affect the analysis. Do not transfer a deed or refinance solely because an online guide says all rental real estate belongs outside corporations.'''),
('Distinguish cash distributions from property distributions', '''A distribution of appreciated property can trigger gain at the corporation level even when the shareholder receives no cash. The resulting pass-through and shareholder basis adjustments then need analysis. The absence of a third-party buyer does not establish tax-free treatment. Have the preparer model the complete transaction before legal documents are executed.'''),
('Compare practical alternatives', '''Depending on the facts, an owner may retain the current structure, sell the property from the entity or consider a different transaction. Each option can carry taxes, lender requirements and legal costs. Evaluate the real alternatives rather than assuming an immediate transfer is necessary. Keep the final analysis with corporate records so future preparers understand the decision and remaining exposure.''')],
68: [
('Give the transaction team a single property brief', '''Describe the buyer, business use, financing, existing occupants and planned work. Identify whether equipment is purchased with the real estate and whether related parties are involved. Send the same facts to the attorney, lender and tax preparer. Conflicting assumptions about the buyer or purchased assets can create problems that are difficult to repair after closing.'''),
('Preserve the allocation evidence', '''Retain appraisals, contracts, equipment lists and invoices supporting the allocation of consideration. Distinguish real estate acquisition charges from loan costs and prepaid items. A study later in the process may help classify supported building costs, but it cannot replace the transaction's underlying evidence. Ask for itemization while the seller and service providers are still involved.'''),
('Plan for work after closing', '''A building may need improvements before the business can use it. Record the intended use, required work and actual readiness dates. Separately purchased assets can have different dates. Coordinate the opening fixed-asset ledger with the business books and any property-owning entity. The purchase date and first mortgage payment are not substitutes for a placed-in-service review.''')],
72: [
('Lead with decisions and assumptions', '''State what the owner is trying to accomplish and which facts the plan relies on. Identify income sources, ownership, filing status, time horizon and expected transactions. Mark incomplete records and conditional qualification clearly. A plan should explain why a recommendation applies to this situation, not merely list tax-code references or strategies available to someone else.'''),
('Show the economics consistently', '''For each recommendation, distinguish the deduction, credit, timing effect, cash required, fees and modeled tax change. Use a consistent baseline so several strategies do not claim the same benefit. Explain what changes in later years or on a sale. A retirement contribution and a reimbursement have different cash implications even if both reduce taxable income in a projection.'''),
('Finish with an implementation schedule', '''List each action, responsible person, deadline, required document and completion evidence. Explain which services are included and which require a separate engagement. Keep a status field and a revision history so the next meeting starts with progress rather than another copy of the original recommendation. The return preparer should be able to trace completed work into the actual filing.''')],
82: [
('Compare the property description first', '''Check the address, size, ownership, acquisition year and improvement scope on each proposal. Confirm whether separate buildings or later renovations are included. A quote based on preliminary details may need revision after records are reviewed. If two proposals describe different projects, align their assumptions before comparing price.'''),
('Separate report work from tax work', '''List asset analysis, basis reconciliation, report delivery and post-delivery questions. Then list any method-change filing, return preparation, state adjustment and owner-level deduction analysis. Identify who provides each service. Cost segregation is separately priced from AE advisory; neither service should be treated as an unlimited promise to complete every tax task arising from the property.'''),
('Read the support and revision terms', '''Ask what happens if the owner supplies a missing invoice after delivery, the preparer finds a discrepancy or an examiner later asks about the report. Confirm time limits, additional charges and the difference between answering study questions and representing a taxpayer. Save the accepted proposal with the final report so future questions can be evaluated against the actual engagement.''')],
99: [
('Establish what was actually promised', '''Start with the engagement and written plan. Separate contracted deliverables from optional ideas discussed in a meeting. Gather messages assigning tasks and records showing completed work. This avoids blaming a preparer for a step that was never engaged while still identifying recommendations that were approved but left unresolved.'''),
('Triage by deadline and consequence', '''Identify items affecting an upcoming filing, payment, transaction or election. Ask the responsible professional which steps remain available and which require a corrective procedure. Keep the original dates intact; do not create documents that falsely imply an earlier action occurred. Update the projection when an anticipated deduction is no longer supported.'''),
('Create a recovery schedule', '''Assign one accountable person to each open task and identify dependencies. A bookkeeper may need to reconcile an expense before the advisor can analyze it, and a preparer may need the advisor's conclusion before filing. Agree on evidence that will close each item. Review that evidence at the next check-in instead of accepting a general statement that the plan is in progress.''')],
100: [
('Use a clear approval point', '''After facts are gathered, the advisor should explain the recommendation, assumptions, expected effect and required action. The owner needs to understand any funding or operational commitment before implementation. Record the approved scope, including work assigned to attorneys, plan administrators, study providers or other professionals.'''),
('Reconcile implementation with accounting', '''Completed actions should reach the appropriate books and workpapers. Reimbursements need supporting claims and payment records; asset purchases need basis and service dates; entity changes need effective dates and required filings. The accountant should identify unresolved differences before preparing the return. A document in a folder is not proof that the accounting reflects it correctly.'''),
('Close the loop after submission', '''Review the return against the approved and completed work. Retain signed authorizations, filed forms and applicable submission or acceptance evidence. Update future-year depreciation, basis and carryforward records. If the filing differs from the plan, explain why and identify the next action. This final reconciliation is what makes the next year's planning start from reliable information.''')],
}

CASE_EXTRA = {
91: ('Separate study scope from eligibility', 'A study should reconcile the supported purchase and improvement basis, including land and assets already reported separately. The taxpayer must separately establish acquisition eligibility, service dates and how the rental is treated. Short stays alone do not prove material participation. The illustration uses assumed inputs to teach the calculation; it does not estimate what a new client will save.'),
92: ('Document the owner-level limitations', 'Obtain the property return, any K-1, relevant basis and at-risk schedules, and passive-loss worksheets. If the owner claims real estate professional treatment, preserve the separate qualification and material-participation analysis. An election should be located and reviewed rather than inferred from last year’s result. A change in activity or ownership needs its own analysis.'),
93: ('Use both entities’ records', 'The operating business and property owner need consistent rent, expense and ownership records. Compare their ledgers and the written lease. If the property generates a loss, do not assume the business’s profit makes that loss usable. The self-rental and grouping analyses are separate from proving that rent was actually paid and correctly recorded.'),
94: ('Do not substitute current percentages for historical rules', 'Recalculate the relevant years with the appropriate acquisition dates, service dates, methods, conventions and elections. Confirm which correction procedure applies under current guidance. A report produced today does not change the dates on which the original assets were acquired. Keep the historical bridge and current-year depreciation separate so the adjustment does not duplicate a deduction.'),
95: ('Create a property-by-property work schedule', 'Each row should name a property, its owner, the prior treatment, missing records, a next action and the person responsible. A portfolio can require a mixture of record reconstruction, feasibility review, study reconciliation and sale modeling. Combining those tasks into one savings estimate before resolving them would conceal important differences between the properties.'),
96: ('Measure owner cash after implementation costs', 'Use the same profit assumptions before and after the proposed changes. Include compensation, payroll, contribution funding and separately priced professional work. Explain which deductions reflect actual spending, which change timing and which depend on eligibility. Avoid adding overlapping tax estimates. Retain the assumptions so the result can be revised when actual wages or profits differ.'),
}

EXTRA.update({
1: [('Purchase price is only the starting point', 'A $400,000, $750,000 or $1 million purchase does not establish a fixed cost segregation deduction. For each property, reconcile land, acquisition costs, later improvements and separately purchased assets. Request a supported feasibility estimate rather than applying a universal percentage. Two properties purchased for the same price can produce different asset allocations and different tax results.'),
('Measure timing rather than claiming a permanent windfall', 'Accelerated depreciation generally moves deductions forward. The comparison should include reduced future deductions and the expected disposition, as well as the value of earlier cash. If a loss is deferred for several years, the immediate value can be small. Compare the study fee and implementation costs against the incremental usable benefit under realistic assumptions.'),
('Decide whether to proceed', 'Gather the existing depreciation schedule and give the advisor the expected holding period and other income. Ask for a written explanation of unresolved assumptions. The next step may be a study, a records reconstruction or a decision to defer. The appropriate answer should follow the property and taxpayer facts, rather than a promised return on every dollar of study fees.')],
9: [('A passive owner may still receive value', 'A passive rental loss may offset eligible passive income, subject to the applicable limitations and special rules. Otherwise it may be carried forward. Do not confuse lack of a wage offset with an invalid study. The economic question is when the benefit can be used and whether that timing justifies the cost.'),
('Recognize reasons to defer', 'An unresolved land allocation, missing acquisition documents or a planned ownership transfer may make other work the first priority. If the owner expects to sell soon, compare the current deduction with the disposition consequences. If the projection assumes future passive income, test a lower-income scenario rather than treating that income as certain.'),
('Use a documented decision', 'Record the estimated incremental deduction, usability assumptions, fees and expected sale year. Keep the decision with the property file so it can be revisited when circumstances change. A decision not to order a study today does not mean the property can never benefit, and a favorable estimate does not guarantee the final tax result.')],
13: [('Inventory common and unit-specific assets', 'Walk through the acquisition and improvement records by building, unit and common area. Appliances, flooring and site improvements need asset-specific classification; permanent building systems should not be assigned short lives just because they serve rental units. Keep original construction, acquisition and replacement dates separate.'),
('Avoid a standard allocation by building size', 'There is no universal reclassification percentage for a five-unit or twenty-unit property. Property condition, construction, improvements and supported cost all matter. A feasibility estimate should explain its assumptions and the report should reconcile final classifications to basis. Unit count and square footage can inform scope without proving a deduction.'),
('Evaluate the owner return', 'A large depreciation deduction can produce a rental loss, but current use depends on the owner. Review passive income, participation, any relevant exception and other limitations. Ask for both the property calculation and the owner-level projection before comparing the study fee with tax savings. Preserve the resulting asset schedules for later renovations and sale planning.')],
21: [('Classify the activity from actual operations', 'For passive-activity purposes, an average customer-use period of seven days or less is one exception to rental-activity treatment. Other exceptions have their own requirements. Obtain complete booking and service records before deciding which applies. Do not confuse the passive-activity definition with local zoning, lodging tax rules or a platform label.'),
('Document material participation', 'If the activity is outside rental treatment under the applicable exception, evaluate material participation under the relevant tests. The more-than-100-hours/no-other-individual-more test differs from the more-than-500-hours test. Spouse participation and other workers’ time may matter. Record actual work and separate investor activities rather than retrofitting a log to a desired result.'),
('Calculate depreciation and loss use', 'Reconcile land, building basis, furnishings and improvements. Confirm acquisition and placed-in-service dates before applying bonus depreciation. Then evaluate applicable loss limits. Cost segregation is separately priced from advisory, and the written engagement should assign report review, tax implementation and return preparation responsibilities.'),
('Keep personal use and reporting questions separate', 'Owner stays can affect the vacation-home rules. Substantial services can affect return reporting and self-employment tax. A short average stay alone does not answer either question. Give the preparer one coherent record of operations, personal use, assets and participation so the final return does not rely on inconsistent assumptions.')],
23: [('Understand the seven tests', 'The regulations address more than 500 hours; substantially all participation; more than 100 hours with no other individual participating more; significant participation activities totaling more than 500 hours; material participation in five of the prior ten years; certain personal-service activities with participation in three prior years; and a facts-and-circumstances test. Each has conditions. Significant participation activities have their own definition, and the facts-and-circumstances test is not a shortcut around paid management or other restrictions.'),
('Confirm the test fits this activity', 'First establish whether the activity is treated as a rental for passive-activity purposes. Some tests discussed for trades or businesses cannot simply be copied onto a passive rental. The relevant rules also exclude certain investor activities and contain special restrictions. Read the regulatory requirements with the actual operation in view before selecting a test.'),
('Keep evidence through the entire year', 'Retain a dated task log and corroborating records. Check for overlapping hours, implausible totals and tasks performed by someone else. Where a test compares individuals, gather available evidence about their participation. A professional review should explain both the test selected and the facts supporting it; a log template alone cannot establish qualification.')],
29: [('Review the rental activity exception', 'The average customer-use period is calculated from actual use, not the listing’s minimum stay. If the applicable rental exception is satisfied, the next question is material participation. If it is not, evaluate the rental rules and any other applicable exception. A wage earner should not assume all properties marketed as Airbnb investments follow the same tax path.'),
('Separate employment time from property work', 'Record the tasks actually performed by the owner and spouse and identify work performed by managers or contractors. A full-time employment schedule may be relevant to evaluating the claimed participation. Do not count investment review or projected future work as completed operational participation.'),
('Use realistic cash and deduction scenarios', 'Review acquisition cost, financing, operating performance and expected sale alongside the tax projection. A depreciation deduction is not rental revenue and does not make an unprofitable property a sound investment. Ask the advisor to show what happens if the deduction is suspended, income is lower or the property is sold earlier than expected.')],
39: [('Compare operations before comparing deductions', 'Short and long stays can affect passive-activity classification, but the labels STR and LTR do not establish every tax consequence. Review actual customer-use periods, services and participation. Building recovery periods likewise require their own property-classification analysis; they should not be selected solely from the seven-day passive-activity exception.'),
('Track a midyear change in use', 'Keep the final short-stay reservations, the new long-term lease and the date the operating model changes. Inform the preparer of personal-use periods and any periods unavailable for rent. Historical elections and grouping can matter. Do not simply apply one year’s operating assumptions to the next because the owner and address remain unchanged.'),
('Keep portfolio records separable', 'Maintain property-level income, expenses and depreciation along with owner-level limitation worksheets. A valid combined activity may be relevant for a particular purpose, but detailed records are still useful for a renovation, refinance or sale of one property. Compare the after-tax result of each business model using realistic occupancy, costs and management requirements.')],
43: [('Start with the existing return history', 'Collect all depreciation schedules, election statements, prior studies and records of improvements. Determine whether the same taxpayer has owned the property throughout the period. A transfer, exchange or entity-interest acquisition can change the analysis. The current market value does not replace the supported tax basis.'),
('Calculate the historical difference', 'The preparer should use the depreciation rules applicable to the original asset dates. Compare proper cumulative depreciation with prior treatment and calculate current-year depreciation separately. If a method change is appropriate, confirm eligibility and procedural requirements. An amendment is a different path and should not be selected merely because it appears simpler.'),
('Define the study boundary', 'For a house, condo or other property, identify the assets and ownership interests actually acquired. Land and personal-use portions require separate treatment. Common areas owned through an association need supporting ownership and basis records. Use the dedicated condo and report-reconciliation guides for these questions, then integrate the findings into one consistent asset history.')],
67: [('Understand the corporation-level passive rules', 'Closely held C corporations can have different passive-loss treatment, including potential use against net active income under applicable rules. Personal service corporations and portfolio income require separate attention. This is not permission to move an individual’s passive loss onto another taxpayer’s return. Confirm the corporation’s classification, ownership and actual income before modeling a benefit.'),
('Consider distributions and appreciated property', 'A later sale may generate corporation-level tax, and distributing proceeds can create shareholder-level consequences. Distributing appreciated property can itself trigger corporate gain. A shareholder’s estate basis adjustment in stock does not automatically reset the corporation’s basis in its building. These differences make an exit model essential.'),
('Use commercial assumptions', 'Compare operating needs, financing, retained cash and owner withdrawals across alternatives. Do not assume the owner will never need the cash or that every shareholder loan can replace a distribution. Review legal and tax requirements before moving property or income. A lower current corporate tax bill is one output, not the complete investment result.')],
83: [('Providers to research using primary sources', 'AE Tax Advisors offers separately priced cost segregation and tax advisory. KBKG publishes cost segregation and fixed-asset services. CSSI publishes cost segregation services, and R.E. Cost Seg presents cost segregation services for property owners. These are a research shortlist, not a ranked claim that one provider is universally superior. Use the source links below to confirm current offerings.'),
('Compare residential fit and implementation', 'Give each provider the same address, property type, acquisition year, improvement history and existing depreciation information. Ask whether it accepts the project and which deliverables are included. Confirm separately who prepares any Form 3115, reviews loss usability and files the return. Do not infer that a provider lacks a service because a particular page does not describe it.'),
('Use a proposal-based final decision', 'Compare the current written proposals and the total work remaining after delivery. Do not rely on old online prices, promised universal savings or unverified turnaround claims. For AE, cost segregation is separately priced from advisory. Ask about the specific property and scope on a call; the engagement should identify any additional preparation or implementation fees.')],
84: [('Identify the questions the tool expects you to answer', 'Review how the software obtains cost, land allocation, asset condition and service dates. Ask whether the user must make classification judgments and how incomplete records are handled. A convenient interface cannot validate facts that were entered incorrectly. Keep the input records and the assumptions behind the generated output.'),
('Evaluate the professional engagement by its actual scope', 'Professional services vary in methodology, inspection, cost analysis and support. Request a sample deliverable and the written scope rather than assuming every professional report is identical. The IRS cost segregation audit guide describes considerations useful for evaluating a study, but it does not certify providers or guarantee acceptance.'),
('Confirm implementation before choosing', 'Ask the return preparer whether the output can be reconciled and used for the particular filing. Historical depreciation, ownership changes and method-change procedures may require work beyond either a software report or a study. Compare total cost and responsibility, including corrections and later questions, before selecting an approach.')],
85: [('A report and a return are different deliverables', 'The report explains supported asset classifications. The tax preparer determines the appropriate reporting and any correction procedure using the taxpayer’s facts. The owner or advisor supplies participation and other information needed for loss analysis. One provider may coordinate several stages, but the written engagement must say so.'),
('Use a responsibility table', 'List the study provider, bookkeeper, advisor and preparer beside their tasks. Include who resolves differences, who communicates changes and who approves final assumptions. Where one person has several roles, keep the tasks separate so report completion is not confused with filing completion. Track pending records and deadlines in the same schedule.'),
('Confirm AE scope on a call', 'Cost segregation is separately priced from AE tax advisory. Return preparation, method-change work and other implementation services should be confirmed in the applicable engagement. Ask which tasks AE will perform and which remain with an existing professional. This gives the owner a practical comparison without making unsupported claims about another provider’s capabilities.')],
87: [('Compare the complete service relationship', 'List the entity and personal returns, rental properties, states and planned transactions. Ask each firm which work it performs and which it coordinates. A business owner may need current planning, historical cleanup and recurring preparation, each with a different scope and fee. Match the engagement to those needs rather than choosing the longest strategy list.'),
('Use evidence for credentials and experience', 'Verify professional licenses through the appropriate regulator and ask for relevant examples with confidential information removed. A case study should distinguish hypothetical illustrations from documented outcomes. Ask who will be responsible for the work and how questions reach that person. Published credentials do not prove that a particular professional reviewed your file.'),
('Compare communication and handoffs', 'Confirm meeting cadence, document channels, implementation responsibility and handling of late changes. If the business and property returns are prepared elsewhere, ask how the advisor communicates approved recommendations. The best fit is the engagement that addresses the actual work with clear accountability, not a claim that one firm is best for all investors.')],
88: [('A starting shortlist, not an unsupported ranking', 'Consider AE Tax Advisors alongside firms whose public materials describe relevant advisory services, including Peter Holtz CPA, Prime Path Advisory and Neil Jesani Advisors. Verify the current offerings through the linked official pages. This page does not claim that any listed firm is universally best, and AE’s role as publisher and provider is disclosed.'),
('Match public positioning to a written proposal', 'Peter Holtz CPA publishes accounting, tax strategy and CFO advisory services. Prime Path’s terms describe tax planning, preparation and ongoing advisory. Neil Jesani’s official site describes private tax strategy services. These broad descriptions do not establish the scope available to a specific prospect. Ask each firm to respond to the same client brief.'),
('Verify prices instead of repeating estimates', 'Obtain current fees and terms directly. An old estimated starting price is not a verified quote and should not decide the comparison. Ask about separately billed returns, studies, entity work and other projects. AE cost segregation is separately priced from advisory. Compare the total engagement and implementation responsibilities before booking follow-up conversations.')],
89: [('Build a service-by-service cost sheet', 'Create rows for initial planning, recurring advisory, entity returns, individual returns, depreciation work and any special projects. Record whether each item is included, separately quoted or not offered under the proposal. This prevents an advisory fee from being mistaken for the total annual cost of a complex engagement.'),
('Compare payment timing and future commitments', 'Identify deposits, installment dates, renewal terms and cancellation provisions. Ask whether future-year work requires a new engagement and how scope changes are priced. A monthly payment amount does not necessarily describe a monthly service, and an annual price does not prove all filings are included.'),
('Use current verified information', 'Use AE’s published pricing page as a starting point and confirm the written engagement for the actual work. Obtain competitor pricing directly instead of treating historical market estimates as facts. Cost segregation is separately priced. Record the date and source of every quote so later decisions do not rely on stale numbers.')],
})
