"""Reviewed decision modules for the September 2026 owner content sprint.

Each entry has a distinct decision, worked illustration, and evidence checklist.
These supplement existing guides; new routes receive additional original sections.
"""
MODULES = {}

def add(n, heading, decision, example, checklist):
    MODULES[n] = dict(heading=heading, decision=decision, example=example,
                      checklist=checklist.split('|'))

add(1, 'Compare usable benefit with the full implementation cost',
'''Evaluate the incremental deduction, not the study's entire short-life allocation. Some depreciation would have been available without the study. Then determine how much of the incremental deduction survives the applicable loss limitations. A property price is useful for identifying the project, but it is not depreciable basis: land, transaction costs, improvements and prior depreciation require reconciliation. Compare at least the current year and expected sale year before choosing a study.''',
'''Hypothetical illustration: a study accelerates an additional $60,000 into the current year. If the full amount is usable and the assumed incremental federal rate is 32%, the modeled current federal effect is $19,200. If only $10,000 is usable, that illustration falls to $3,200 before fees, state differences and future consequences. Neither figure is a study estimate or a permanent saving.''',
'Request both the baseline and proposed depreciation schedules|Identify the current-year deduction usable on the owner return|Include study and implementation fees|Model a sale or change in ownership before committing')
add(2, 'Compare written scope before comparing the headline fee',
'''A useful price comparison lists the property, assets, tax years and deliverables covered by each proposal. A study quote and a return-preparation quote solve different parts of the project. Confirm whether prior depreciation reconciliation, Form 3115 preparation, owner-level loss analysis, state adjustments and responses to later questions are included or separately billed. Cost segregation is separately priced from AE tax advisory; the signed engagement controls the work.''',
'''Suppose Proposal A covers the report only while Proposal B also includes a preparer handoff and a prior-year schedule reconciliation. Comparing the two prices without assigning those remaining tasks can understate the total project cost. Ask both providers to complete the same scope list rather than assuming that a longer report includes more implementation.''',
'Identify the property and square footage used in the quote|List report, tax filing and advisory work separately|Confirm additional-property and revision charges|Record who handles questions from the return preparer')
add(3, 'A useful deliverable connects assets to supported cost',
'''Request an explanation of how costs were identified, allocated and reconciled to the property's total depreciable basis. The report should make it possible for a preparer to understand the classifications and the source of each material amount. Photos, construction records and estimates serve different purposes; a collection of photographs alone does not explain the tax treatment. Ask how the provider documents assumptions where original cost detail is missing.''',
'''An appliance schedule identifies $18,000 of assets, but the owner has already depreciated $7,000 of those appliances separately. A useful report handoff identifies the overlap and reconciles it before the preparer creates new assets. The report's gross classification total should never become an additional deduction without checking the existing schedule.''',
'Request a sample deliverable with confidential details removed|Check property identity, ownership and dates|Tie asset totals to the basis reconciliation|Confirm a usable asset schedule and implementation contact')
add(4, 'Schedule the project around dependencies',
'''Separate elapsed calendar time from time spent analyzing a complete file. Missing closing records, unresolved land basis, renovation invoices and an incomplete depreciation schedule can prevent a report from being finalized. Obtain milestones for intake, analysis, questions, report delivery and preparer review. The tax filing date is a separate deadline; an extension does not make every election or payment deadline disappear.''',
'''If a report is expected shortly before filing, the owner still needs time for basis reconciliation, method-change review and return preparation. Work backward from the preparer's actual cutoff and include time to answer questions. An estimated report date is not confirmation that the return will be ready on that date.''',
'Confirm when the provider considers the file complete|Name the person resolving technical questions|Reserve preparer review time after report delivery|Check filing and payment deadlines independently')
add(5, 'Build one property packet with a clear missing-items list',
'''Group documents by purpose: acquisition records establish cost; land support explains the nondepreciable portion; improvement records identify later additions; existing depreciation schedules show prior treatment. Label records with the property address and relevant year. If an invoice covers several properties, retain the allocation rather than placing the whole cost in each folder. A missing document should remain visible as an unresolved item.''',
'''A portfolio owner provides a single spreadsheet showing three renovation totals. The preparer cannot tell which costs belong to the acquisition year or whether furniture was already deducted. Splitting the spreadsheet by property, invoice, date and existing tax treatment is more useful than resending the same total with a new filename.''',
'Closing statement and purchase agreement|Land valuation support and property details|Improvement invoices and asset purchase records|Complete federal and state depreciation schedules|List of missing records and the person obtaining each')
add(6, 'Choose the study date after mapping the transaction',
'''A feasibility discussion before closing can identify records to retain and questions to resolve. The final analysis still needs the actual transaction, supported basis and placed-in-service facts. Ordering after the first rental year introduces prior reporting into the review; ordering before an anticipated sale requires an exit model. Do not select the study date solely because a marketing deadline creates urgency.''',
'''An investor considering a December acquisition can discuss feasibility in November, collect final closing records in December and separately document when the property becomes ready and available for rent. Paying the study invoice in December does not establish the rental's depreciation start date or settle which tax year receives a deduction.''',
'Map contract, closing and placed-in-service dates|Ask which facts must be final before analysis|Identify whether a return has already been filed|Coordinate the study with the preparer and any planned sale')
add(7, 'Move from the property report to the taxpayer return',
'''Start with the owner and entity tax classification, then identify applicable basis, at-risk and passive-activity limitations. Other limits may apply after those tests. A partnership allocation, an S corporation loss and a directly owned rental do not all begin at the same step. The study determines asset classifications; it does not establish the owner's participation or available basis.''',
'''Two owners receive the same $40,000 depreciation allocation. One has sufficient basis, amount at risk and usable passive income; the other has a basis restriction. Their current deductions can differ even though the underlying study is identical. A useful projection labels both the generated amount and the amount actually carried onto each owner's return.''',
'Identify the taxpayer claiming depreciation|Reconcile owner basis where applicable|Review at-risk and passive limitations in order|Separate current deductions from each type of carryforward')
add(8, 'Give the preparer an implementation handoff',
'''Before importing a report, reconcile its basis and asset list with the tax depreciation records. Determine whether the project concerns a new asset, a current return or a change to an established accounting method. Document the required filing procedure, owner approvals and state differences. Keep the report with the workpapers, but also preserve the final schedule actually used on the return.''',
'''A report delivered in February does not prove that the March return used it. Ask for a tie-out identifying the assets added or changed, the adjustment if applicable and the final return workpaper. This catches a report left in an upload folder as well as a report entered twice.''',
'Assign one implementation owner|Resolve differences with the existing asset ledger|Confirm filing procedure and deadlines|Retain the filed schedules and reconciliation|Track unresolved items through completion')
add(9, 'Use a stop-or-proceed decision instead of a universal rule',
'''A study can be technically possible without being the best next expenditure. Unusable losses, a near-term sale, uncertain ownership, low supported basis or missing records may shift the priority. Regular depreciation continues to matter even if acceleration offers limited immediate value. Compare the study with correcting the books or establishing the records needed for a reliable projection.''',
'''An owner planning to sell next year may prefer to model the sale first. A projected current deduction could be offset in part by later recapture, and the owner may incur both study and implementation fees. Another owner expecting a long hold and usable deductions can reach a different decision with the same purchase price.''',
'Explain why the deduction would be useful now|Include likely disposition timing|Resolve ownership and basis uncertainty|Estimate all project costs|Document why proceeding or deferring makes economic sense')
add(10, 'Read the reconciliation before the headline deduction',
'''Find the report's total basis, nondepreciable land, asset categories and placed-in-service dates. Compare those figures with the closing records and the preparer's existing schedule. Ask which amounts are measured, estimated or supplied by the owner. A classification percentage without the cost bridge cannot show whether the same expenditure appears in two categories.''',
'''If the closing reconciliation supports $620,000 of depreciable cost but report assets total $660,000, investigate the $40,000 difference before filing. It might be a later improvement omitted from the first worksheet, or an asset counted twice. The mismatch is a question to resolve, not an automatic reason to accept either total.''',
'Check owner, property address and report date|Reconcile total cost and land|Identify separately purchased assets|Compare recovery periods and conventions with preparer records|Resolve every material difference in writing')
add(11, 'A single rental needs its own basis and usability review',
'''Do not borrow an allocation from a neighboring house or a portfolio average. A furnished acquisition, an unfurnished house and a property renovated after purchase have different asset histories. Separate the initial building purchase from later appliances, landscaping and other improvements. A single-family rental can still produce a passive loss that is not usable against wages.''',
'''An owner buys a house for $500,000 and later spends $25,000 furnishing it. The furniture may already have its own tax treatment. A study of the building should reconcile that separate purchase rather than treating the furnished property's current value as a new acquisition cost.''',
'Retain the purchase allocation and land support|Separate post-closing purchases|Check whether furnishings already appear on Form 4562|Model the loss on the owner return|Compare fees with incremental usable benefit')
add(12, 'Separate owner-occupied space from rental units',
'''A duplex owner living in one unit cannot assume the entire property is depreciable rental property. Identify rental and personal portions and support allocations of shared costs. A triplex or fourplex may also include common areas, separate improvements and staggered rental start dates. Unit count alone does not determine the depreciation outcome.''',
'''Suppose the owner occupies one side of a duplex and rents the other. Replacing a refrigerator in the rented unit is a different allocation problem from replacing a roof serving both sides. The property packet should identify which unit received each expenditure and how shared work was allocated. An equal split is an assumption that needs support, not a rule for every duplex.''',
'Draw a unit and common-area map|Identify personal-use periods|Label unit-specific invoices|Explain shared-cost allocation|Retain each unit’s readiness and rental records')
add(13, 'Build a unit-level record without losing the building total',
'''Smaller apartment buildings often have several renovation vintages. Reconcile the property acquisition first, then track unit turns and shared systems separately. Do not turn each apartment's current replacement cost into additional tax basis. Existing fixtures, later improvements and disposed assets must fit one consistent history.''',
'''An eight-unit owner upgrades two kitchens this year. The study and preparer need to know whether those costs are already on the fixed-asset register and what happened to the old components. Eight similar floor plans do not establish that all kitchens were installed at the same time or cost the same amount.''',
'List units, renovations and installation years|Separate common-area work from unit work|Reconcile the asset register to invoices|Identify replaced components for preparer review|Keep the complete property basis tie-out')
add(14, 'Identify what the owner actually owns',
'''A condominium purchase includes rights described in the governing documents, not unrestricted ownership of every amenity in the development. Distinguish the unit, any relevant common-element interest and assets owned by the association. Townhome ownership can differ from condominium ownership even when the buildings look alike. The deed and governing documents matter more than the marketing label.''',
'''An owner cannot automatically add a share of the community pool's replacement cost to the unit's tax basis. A special assessment also needs analysis of what it pays for and how the payment is treated. Retain the association notice and supporting project description instead of labeling every assessment a repair.''',
'Provide deed and governing ownership documents|Separate unit assets from association assets|Explain special assessments and reserve payments|Document personal versus rental use|Reconcile purchase basis before allocating components')
add(15, 'Cabin amenities require asset-specific evidence',
'''A cabin may include furniture, access improvements, septic infrastructure, decks and outdoor amenities. Classification depends on function, permanence and the applicable rules. Rustic appearance or a vacation-rental listing does not establish shorter recovery periods. Identify what was purchased with the property and what was installed later.''',
'''A freestanding hot tub bought after closing and a deck structurally integrated into the cabin should not be assigned the same recovery period merely because both appear in the outdoor amenity photos. Provide invoices, installation information and photographs showing how each item is used and attached.''',
'Identify included and later-purchased amenities|Document structural attachment and function|Separate land from improvements|Track rental readiness for later installations|Reconcile personal-use days with the tax file')
add(16, 'Separate coastal repairs from acquisition and improvement costs',
'''Salt exposure, storm damage and seasonal maintenance create recordkeeping challenges for beach rentals. Cost segregation classifies supported basis; it does not automatically turn recurring maintenance into an asset or a reconstruction project into a repair. Retain the scope of work and insurance documentation when a project combines damage restoration and upgrades.''',
'''A contractor replaces damaged exterior components and also adds a new outdoor shower. One invoice may include several tax questions. Ask for a cost breakdown and record what existed before the work. Do not deduct the full invoice and then include the same expenditure in the study's improvement schedule.''',
'Retain original acquisition and land support|Separate insurance proceeds from project costs|Document before-and-after condition|Identify upgrades separately from restoration|Track personal use and seasonal availability')
add(17, 'Furnishing does not determine rental activity classification',
'''A furnished lease to a traveling worker can generate depreciation on furniture while remaining subject to rental activity rules. Analyze actual customer-use periods and services rather than relying on a listing platform's mid-term label. For the exception involving average use of 30 days or less, significant personal services are an additional requirement; the duration alone does not settle it.''',
'''A furnished 60-day lease and a five-day guest stay can use identical beds and appliances but require different passive-activity analysis. Keep the asset schedule separate from the stay-length calculation. A cost segregation report cannot replace that operational evidence.''',
'Export actual occupancy periods|Describe services provided during stays|Separate furniture and building records|Document participation under the applicable activity classification|Model current usability of any resulting loss')
add(18, 'Use construction detail before it becomes difficult to recover',
'''New construction may provide access to contracts, pay applications and subcontractor schedules that are unavailable for an older acquisition. Preserve them before the project team closes its files. Reconcile change orders, indirect costs and owner-purchased items to the final project total. The construction budget is not necessarily the final tax basis.''',
'''The owner buys appliances directly while the contractor's budget also includes an appliance allowance. The final reconciliation must identify the allowance credit before adding the owner's invoices. Otherwise the study can begin with duplicated cost even though each document looks legitimate on its own.''',
'Obtain final contractor cost detail|Reconcile allowances and change orders|List owner-purchased assets|Separate land and capitalized project costs|Document when each rental area becomes ready and available')
add(19, 'Connect the new work to the assets it replaces',
'''A renovation can add assets, improve existing property and remove old components. Preserve photographs and cost records before demolition. Ask the preparer to evaluate whether a partial disposition or another treatment applies rather than assuming the old asset disappears automatically. Cost segregation and repair analysis should use the same project scope.''',
'''A landlord renovates bathrooms after ordering a study. If the original report describes the old bathrooms but the tax ledger adds all new fixtures, the handoff needs both dates and both cost histories. A report prepared before work began should not silently be treated as a report of the completed renovation.''',
'Identify the report’s inspection and valuation dates|Keep demolition and installation records|Separate repairs, improvements and new assets for review|Reconcile old and new fixed-asset entries|Confirm any disposition election with the preparer')
add(20, 'Rank properties using records and expected usability',
'''Create one row per property showing ownership, acquisition year, supported basis, prior studies, missing records and planned sale timing. The largest purchase price is not automatically the best first project. Properties with clean records and a usable current deduction may be easier to implement than properties with unresolved historical reporting.''',
'''A six-property owner finds that two houses already had studies, one is scheduled for sale and three have only straight-line schedules. Ordering six new studies would skip the first planning decision. Reconcile prior work and request a feasibility assessment for the remaining properties before setting a portfolio budget.''',
'Identify prior studies and accounting-method filings|List separate taxpayers and ownership changes|Reconcile all existing depreciation schedules|Rank missing documents and expected benefit|Agree on a property-by-property implementation sequence')
add(21, 'Keep three separate STR decisions in the tax file',
'''First determine the activity's treatment under the passive-activity rules using actual operations. Next evaluate participation. Then calculate depreciation and test the resulting loss against other applicable limits. Schedule C versus Schedule E reporting and self-employment tax require their own service-based analysis; a short average stay does not automatically mean Schedule C.''',
'''An owner advertises a seven-night minimum but accepts several month-long bookings. The advertised minimum is not the average customer-use calculation. Another owner has short stays but outsources nearly all work. Both need an operational review before assuming the same tax result as an online example.''',
'Export complete booking history|Describe services provided to guests|Retain owner and spouse participation records|Reconcile asset basis and dates|Confirm loss limitations and return reporting separately')
add(22, 'Calculate actual average use rather than quoting the listing',
'''The seven-day exception concerns average customer use, not the longest stay, a listing category or a minimum-night setting. Use complete records and review extensions, repeated use and cancellations under the applicable rules. If average use exceeds seven days, do not assume the activity has no other possible exception, but evaluate those requirements independently.''',
'''A simplified illustration has ten customer-use periods totaling 60 days, giving a six-day average. Adding a separate 30-day period changes the arithmetic to 90 divided by 11, approximately 8.18 days. This example is arithmetic only; determine the proper customer-use periods from the actual arrangements before applying the rule.''',
'Reconcile reservations to completed occupancy|Separate cancellations from actual use|Review extensions and repeated customer periods|Retain the annual calculation and source export|Recheck classification when the operating model changes')
add(23, 'Choose the participation test that the records actually support',
'''More than 500 hours and more than 100 hours with no other individual participating more are different tests. The latter requires evidence about other people's participation, including paid workers. There are additional tests, but each has conditions. Do not select a target hour count first and then reconstruct a calendar to reach it.''',
'''An owner documents 120 hours while a manager documents 160. The owner has not established the more-than-100-hours/no-one-more test. That does not by itself resolve every possible test, but it shows why a page promising qualification at 100 hours is incomplete. Investor-type review work may also need to be excluded.''',
'Name the test being evaluated|Record tasks rather than only totals|Identify other individuals whose hours matter|Separate operational work from investor activities|Review the full year before finalizing the return')
add(24, 'Make the log traceable to actual work',
'''A useful participation record identifies date, property, task, duration and supporting evidence. Keep email, maintenance tickets and management records as corroboration. Avoid counting the same hour twice across properties or treating an entire trip as work without identifying activities. Document travel facts separately for professional review rather than assuming all travel qualifies.''',
'''A calendar entry reading rental work, eight hours gives little insight. A contemporaneous entry identifying a guest lockout, vendor coordination and a repair inspection, with realistic separate durations and linked messages, is easier to evaluate. Neither record format guarantees that the activity counts under a participation test.''',
'Record each property and task|Use realistic start, end or duration information|Link records to messages or invoices|Identify overlapping entries|Review logs monthly while facts remain accessible')
add(25, 'Read the management agreement before planning around hours',
'''A property manager can handle reservations, guest communication, maintenance and vendor supervision. Those responsibilities affect which tasks the owner actually performs. Some participation tests compare the owner's hours with another individual's hours; compare people, not an unsupported aggregate estimate for a company. Management use does not automatically disqualify an owner, but it changes the evidence needed.''',
'''An owner performs all bookkeeping and occasional inspections while a co-host handles daily operations. Ask whether the owner's tasks support a specific test and whether investor activities have been separated. Reducing the manager's stated responsibilities on paper without changing actual work does not solve the factual issue.''',
'Obtain the current management scope|Identify people performing recurring work|Retain owner task evidence|Request available operational time records|Evaluate all applicable tests without assuming qualification')
add(26, 'Separate spouse participation from unrelated co-host work',
'''A spouse's participation is generally considered when evaluating material participation, but an unrelated co-host's hours are not simply added to the owner's hours. Real estate professional qualification has separate rules: on a joint return, one spouse must separately satisfy its qualifying tests. Do not transfer conclusions from one test into another.''',
'''One spouse handles guests and the other coordinates cleaning. Preserve both sets of tasks and identify overlapping time rather than doubling a shared activity automatically. If the family also hires a co-host, retain that person's role separately because it can matter when comparing participation.''',
'Identify who did each task|Separate spouses from employees and contractors|Avoid double-counting joint activities|Keep REPS qualification and material participation analyses distinct|Retain the source records behind annual totals')
add(27, 'Keep a day-by-day use calendar',
'''Vacation-home rules use both rental and personal-use facts. Family use, below-market use and time spent maintaining the property require careful classification. A property used as a home can face limits on rental deductions. Do not assume a platform's booked-night total contains all the information needed to apply these rules.''',
'''An owner stays at the property for a family weekend and handles a brief maintenance call. The maintenance task does not automatically convert the whole visit into nonpersonal use. Conversely, a full-time repair and maintenance visit can present different facts. Retain activities and occupancy evidence instead of deciding from the trip's label.''',
'Record paid rental days and rates|Identify owner and family stays|Document maintenance work by day|Retain booking and access records|Review expense allocations and deduction limits together')
add(28, 'Use asset-specific readiness dates',
'''A December payment, furniture order or design contract is not the same as property ready and available for rental use. Some assets may be placed in service later than the building. Keep evidence of installation, required approvals and availability. A listing is relevant evidence, but an advertised property that cannot actually be rented presents unresolved facts.''',
'''An owner pays for beds in December, but delivery and assembly occur in January while the rental remains unavailable. The payment does not establish December depreciation. If the house is already operating and a separate optional amenity is unfinished, analyze that amenity's date separately from the house.''',
'Record delivery and installation dates|Document readiness and actual availability|Identify unfinished work and its effect on use|Separate each later-added asset|Review the year-end facts before reducing estimated payments')
add(29, 'Model the wage offset only after establishing eligibility',
'''The existence of W-2 wages does not itself create or prevent an STR deduction. The operational classification, material participation, basis, at-risk amounts and other applicable limits control whether a loss reaches the return. A full-time job can make participation documentation particularly important. Do not buy a property solely to produce a target deduction.''',
'''A wage earner projects $80,000 of property losses but has not reviewed the management arrangement or stay history. Treat the projected wage offset as unresolved until those facts are tested. A projection should show a qualifying and a nonqualifying scenario so the financing decision does not depend on an assumed result.''',
'Review actual work schedules|Determine activity classification|Identify a supported participation test|Compute loss limitations|Compare after-tax cash flow with and without a current deduction')
add(30, 'Close the first year with a complete property handoff',
'''Separate one-time acquisition and setup items from recurring operating expenses. Platform payouts should be reconciled to gross rental activity, fees, refunds and any tax reporting forms. Retain a detailed opening asset schedule so a future study or sale does not depend on reconstructing the first year from bank statements.''',
'''A payout of $2,700 may reflect $3,000 of rent less platform charges and refunds. Recording only the payout as gross revenue can make a reporting-form reconciliation confusing. The preparer needs the transaction detail and the expense treatment, not just the bank deposit.''',
'Reconcile gross bookings and payouts|Provide closing and furnishing invoices|Document rental start and personal-use days|Complete participation records|Keep the final return and depreciation schedules together')
add(31, 'Review income, expenses and loss use as separate steps',
'''A rental can have positive cash flow and a tax loss, or a cash shortfall with taxable income. Loan principal, capital improvements, depreciation and tenant deposits help explain these differences. Maintain property-level books rather than judging profitability from the checking account alone. The owner-level passive-activity analysis comes after the property's income calculation.''',
'''A landlord spends $12,000 on mortgage principal and $12,000 on a capital project. Neither payment should automatically be booked as a current operating deduction. Reconcile the loan and classify the project before using the property profit and loss statement for a tax projection.''',
'Reconcile rents and deposit liabilities|Separate interest from principal|Identify capital projects and asset purchases|Reconcile tax depreciation|Track owner-level loss carryforwards')
add(32, 'Find the limitation that is actually stopping the loss',
'''A carryforward is not a single universal bucket. Basis limitations, at-risk rules and passive-activity limits may defer different amounts under different conditions. Other restrictions can also apply. Determine where the loss stopped before deciding whether more depreciation or a different activity arrangement would change the current tax bill.''',
'''If a partner's loss is limited by outside basis, passive income elsewhere does not automatically make that basis-limited amount deductible. If the loss survives basis and at-risk rules but is passive, the relevant next analysis is different. Ask for the limitation worksheets rather than only the K-1 amount.''',
'Obtain entity and owner loss worksheets|Identify each limitation separately|Reconcile beginning and ending carryforwards|Record events that may release or change a limitation|Avoid treating all deferred losses as immediately usable')
add(33, 'Document qualification and rental participation separately',
'''Real estate professional status generally requires more than 750 hours in qualifying real property trades or businesses and more than half of the individual's personal services in those activities. Employee-service and ownership rules also matter. Qualification alone does not make every rental nonpassive; material participation in the relevant rental activity must also be addressed.''',
'''A person meets the qualifying real estate service tests but holds several rentals with limited involvement. The return still needs a rental participation analysis and any valid aggregation election. A real estate license or job title alone is not a substitute for the statutory service tests.''',
'Separate qualifying and nonqualifying service time|Retain employment and ownership facts|Review each rental or valid combined activity|Locate election statements|Reconcile the annual log with other work commitments')
add(34, 'Identify which grouping rule is under discussion',
'''An election by a qualifying real estate professional to treat rental real estate interests as one activity is not interchangeable with general grouping under the passive-activity regulations. Grouping rentals with a trade or business has additional restrictions. Decisions may affect participation, disclosures and future dispositions, so retain the original statement and rationale.''',
'''An owner asks to group a rental with a profitable operating company to use losses. Common ownership alone does not establish that the proposed grouping is permitted or produces a nonpassive loss. Have the advisor identify the exact authority, conditions and ongoing consequences before filing.''',
'Identify the relevant grouping authority|Map ownership and economic relationships|Locate prior elections and disclosures|Model the effect of selling one component|Document consistency requirements for future returns')
add(35, 'Keep a loss ledger that survives a change of preparer',
'''Track suspended amounts by activity, year and limitation. A current return may show only part of the history needed to explain the opening balance. Sales, gifts, death and changes in participation do not all release losses in the same way. Reconcile the ledger annually and keep the underlying worksheets with permanent property records.''',
'''An owner transfers a rental to a family member and assumes suspended passive losses can now offset wages. A gift has different consequences from a fully taxable disposition to an unrelated buyer. The transfer should be reviewed before it occurs rather than treated as a generic release event.''',
'Obtain prior-year limitation worksheets|Tie opening balances to last year|Separate current losses from prior carryforwards|Identify ownership changes and dispositions|Record the authority for any claimed release')
add(36, 'Ask what changed in the property',
'''The invoice label does not decide whether work is deductible or capitalized. Review betterment, restoration and adaptation standards, the relevant unit of property and any available safe harbor. A large bill is not automatically an improvement, and a small bill is not automatically a repair. Several related invoices may form one project.''',
'''A contractor issues separate invoices for demolition, plumbing and fixtures during a bathroom remodel. Reviewing each in isolation can hide the project's full scope. Provide the preparer with the complete contract and before-and-after information before classifying the payments.''',
'Describe the original condition and completed work|Group related invoices|Identify the unit of property affected|Evaluate applicable safe harbors and elections|Coordinate capitalization with the fixed-asset schedule')
add(37, 'Preserve both cost history and conversion-date value',
'''When a home becomes rental property, depreciation generally uses the lower of adjusted basis or fair market value at conversion, with land excluded. Later sale calculations can require different basis analyses. Preserve the original purchase, improvements, conversion-date valuation and rental-readiness evidence instead of retaining only the latest mortgage statement.''',
'''If a home's adjusted basis is $420,000 and conversion-date value is $380,000, the depreciable starting point is not automatically $420,000. Land must also be removed from the appropriate figure. These hypothetical totals illustrate why a preparer needs both values and their support.''',
'Reconstruct adjusted cost basis|Obtain support for conversion-date value|Allocate nondepreciable land|Document the rental start date|Keep records needed for a later sale calculation')
add(38, 'Check fair rent and actual use before calling it a rental',
'''Renting to a relative can be a legitimate arrangement, but below-market rent and personal-use rules can change the treatment. Record market support, payment history and the occupant's actual use. A lease alone does not prove the property is operated on the terms stated in it.''',
'''A parent charges an adult child $800 while comparable rent is $1,800. The owner should not assume ordinary investment-rental deductions simply because payments occur monthly. Review the personal-use rules and relevant exceptions with the preparer, using actual comparable properties rather than an unsupported estimate.''',
'Retain current market-rent comparisons|Document the lease and actual payments|Identify the family relationship and occupancy use|Review personal-use implications|Classify expenses under the applicable treatment')
add(39, 'Maintain separate operating evidence for each rental model',
'''A portfolio can include short stays, annual leases and properties changing use during the year. Determine the relevant activity treatment from facts and any valid grouping, not a blanket portfolio label. Keep personal-use records, customer-use calculations and participation evidence where applicable. The same owner can have nonpassive business income and passive rental losses.''',
'''A house moves from vacation rentals to a twelve-month lease midyear. Retain the transition date, reservations and lease. Do not simply copy last year's STR classification into the return. The changed operations may affect the activity analysis even though the furniture and legal owner remain unchanged.''',
'Identify each property’s operating periods|Retain actual bookings and leases|Review elections before combining activities|Track personal use separately|Reconcile property-level results to the owner return')
add(40, 'Finish the year with a property exception list',
'''Review more than income and expense totals. Identify acquisitions, refinances, major work, casualty events, tenant deposits, changes in use and properties held for sale. Resolve missing documents before return preparation starts. A year-end checklist should distinguish completed decisions from ideas that still need analysis.''',
'''A landlord's books show a large maintenance expense and no new assets. The year-end review finds that the payment replaced an entire roof. Flag the project for capitalization and disposition analysis while the contractor records are still accessible, rather than assuming the bookkeeping category controls.''',
'Reconcile each bank and loan balance|Review large or unusual expenses|Update the asset and improvement register|Confirm deposit liabilities|Prepare a list of sales, conversions and unresolved tax questions')
add(41, 'Classify the error before selecting the form',
'''An incorrect depreciation method, a mathematical error, an omitted asset and an incorrect acquisition basis can require different correction procedures. Determine whether an accounting method has been adopted and whether an automatic change is available under the current procedures. An amended return is not a universal alternative to obtaining required method-change consent.''',
'''An owner discovers several years of omitted depreciation. The preparer should identify the affected assets and prior reporting before deciding whether Form 3115 is appropriate. A different owner correcting an isolated first-return error may have a different path. Neither should be promised an amendment refund based only on the words missed depreciation.''',
'Identify the precise error and affected years|Reconstruct prior treatment|Check current automatic-change eligibility|Review filing deadlines and duplicate-copy requirements|Reconcile federal and state corrections')
add(42, 'Build the adjustment from a year-by-year bridge',
'''A Section 481(a) adjustment prevents duplication or omission when an accounting method changes. For depreciation, compare the cumulative amount under the proper method with the prior treatment through the beginning of the year of change. Keep the adjustment separate from current-year depreciation. The applicable procedure determines eligibility and the adjustment period.''',
'''Assume a supported method change shows $90,000 of cumulative proper depreciation and $25,000 previously taken. The $65,000 difference is the starting reconciliation for the adjustment, not an automatic refund. Current-year depreciation is a separate calculation, and the resulting deduction remains subject to applicable limitations.''',
'List each asset and original service date|Recompute prior-year depreciation using the applicable historical rules|Reconcile the cumulative difference|Calculate current depreciation separately|Retain the method-change filing and adjustment workpapers')
add(43, 'Use the law applicable to the original asset dates',
'''A study completed today does not turn an older property's acquisition into a current-year purchase. Reconstruct acquisition and placed-in-service dates, historical bonus rules, elections and prior depreciation. Current bonus percentages should not be applied retroactively to every past year. Ownership changes and prior studies also affect what can be corrected.''',
'''A property placed in service several years ago receives a study this year. The preparer must calculate the prior treatment using the rules applicable to those earlier dates, then evaluate the correction procedure. Multiplying the entire short-life allocation by today's bonus percentage can materially overstate the catch-up amount.''',
'Obtain all prior depreciation schedules|Confirm original acquisition and service dates|Locate bonus and other election statements|Review transfers and previous studies|Reconcile historical and current-year amounts separately')
add(44, 'Reconstruct from source records before entering new assets',
'''Request complete depreciation reports from the former preparer, including disposed assets and state schedules. A filed return may not contain the full asset detail. If records remain unavailable, reconstruct acquisition cost, land, improvements and prior deductions from available documents and transcripts. Identify estimates explicitly instead of presenting them as recovered records.''',
'''An owner has five years of Schedule E forms but no fixed-asset register. Those returns may show total depreciation without identifying which appliances or improvements produced it. Rebuilding the ledger from totals alone risks duplicating assets or missing dispositions. Start with the source purchases and reconcile back to each filed year.''',
'Request the full asset export from the prior preparer|Gather acquisition and improvement evidence|Reconcile filed depreciation by year|List unresolved assumptions|Have the preparer determine any correction procedure')
add(45, 'Distinguish a basis problem from a classification problem',
'''Cost segregation classifies supported cost; it cannot create acquisition basis that was never incurred. Reconcile the purchase and improvements before changing recovery periods. An incorrect basis figure can affect every subsequent year's depreciation and an eventual sale. Do not assume that every basis error is corrected through the same accounting-method procedure.''',
'''A spreadsheet uses the property's $900,000 current market value, while the acquisition and supported additions total $640,000 before land allocation. A study should not simply allocate $900,000 among asset classes. Establish the appropriate tax basis and correction path before asking how much depreciation can be accelerated.''',
'Tie basis to the acquisition and later capital costs|Identify land and other exclusions|Reconcile credits and reimbursements|Compare all filed schedules|Determine the correction procedure for the specific error')
add(46, 'Support the allocation rather than choosing a target percentage',
'''Land is not depreciable. For a combined acquisition, support the division between land and improvements using appropriate relative values and available evidence. An assessor's ratio may be relevant, but assess whether it reflects the property and transaction. A low land allocation should not be chosen merely to increase depreciation.''',
'''A coastal parcel and an inland property have the same purchase price but very different underlying land values. Applying the same 10% land assumption to both can misstate basis. Retain an appraisal, assessment information and any other valuation support used to reach the allocation.''',
'Document the valuation date and source|Explain the relative-value allocation|Reconcile total allocated cost to the purchase|Review unusual land features or redevelopment value|Retain the rationale with permanent tax records')
add(47, 'Match every study asset to the existing register',
'''The same furniture, appliances or renovation cost can appear in a purchase allocation, a separate invoice and a prior depreciation schedule. Create a matching table before adding assets from the study. Each cost should have one clearly explained treatment, including any reclassification or correction of its prior treatment.''',
'''A furnished rental acquisition allocates $20,000 to furniture. The preparer already created a $20,000 furniture asset. If the study later includes those same items, adding another $20,000 duplicates basis. Keep serial numbers, descriptions and invoice references where available to distinguish replacements from the original items.''',
'Export existing assets before importing the study|Match descriptions, dates and invoice references|Separate original assets from replacements|Record reclassifications rather than duplicate additions|Reconcile the final total to supported basis')
add(48, 'Request a findings schedule, not only a savings total',
'''A prior-year review should identify the issue, affected taxpayer and years, supporting records, proposed procedure and expected effect. Some findings reduce tax, some increase it and others improve records without changing liability. Distinguish an available correction from an idea that cannot be supported or is outside the applicable deadline.''',
'''A review identifies a possible omitted expense but also finds that the business reimbursed the owner and already deducted it. The correct finding may be no additional deduction. A useful review documents that reconciliation rather than counting the expense as recovered savings.''',
'Provide full returns and depreciation schedules|Tie proposed changes to evidence|Identify deadlines and owner-level effects|Separate estimates from confirmed findings|Compare preparation fees with the supported benefit')
add(49, 'Separate the filing window from the refund limit',
'''Refund claims generally involve both a filing deadline and rules limiting which payments can be refunded. Exceptions and special circumstances can change the result. An accounting-method correction is a different procedural question from reopening an old return. Review filing, payment and extension dates for each taxpayer and year.''',
'''Two taxpayers amend the same tax year on the same day but paid at different times. Their refund positions may differ. A slogan such as three years back cannot replace the actual date analysis. Partnership correction procedures can also differ from ordinary amended-return procedures.''',
'Collect original filing and extension dates|Identify when tax was paid|Check the refund claim and lookback rules|Review entity-specific procedures|Preserve evidence supporting any exception')
add(50, 'Omitted depreciation can still affect sale basis',
'''Failing to claim depreciation does not necessarily preserve basis for a later sale. Allowed-or-allowable rules can reduce basis even when the owner missed deductions. Reconstruct the asset history and evaluate the correction before filing a sale-year return. The procedure and timing depend on the facts and applicable method-change rules.''',
'''An owner assumes a $300,000 building basis remains unchanged because depreciation was never entered. A sale calculation may still require a reduction for allowable depreciation. The corrective work should address both missed deductions and adjusted basis rather than treating one as an optional alternative to the other.''',
'Establish original building basis and service date|Calculate allowable depreciation by year|Review prior returns and elections|Evaluate the correction before sale-year filing|Reconcile the corrected basis with disposition reporting')
add(51, 'Read the settlement statement line by line',
'''Some acquisition costs affect property basis, while financing costs, prepaid items and tax prorations can have different treatment. Do not capitalize or deduct the entire closing-cost total as one line. Ask for supporting invoices when a bundled settlement charge includes several services. Separate amounts paid for obtaining the property from amounts paid for borrowing money.''',
'''An owner pays title charges, loan origination fees and prepaid insurance at closing. Those items do not automatically receive identical treatment. A worksheet showing the purpose, amount and proposed category for each charge gives the preparer a traceable basis reconciliation.''',
'Retain the final settlement statement|Identify acquisition versus financing charges|Review tax and insurance prorations|Reconcile deposits and credits|Tie the asset and loan entries back to cash paid')
add(52, 'Identify what the seller credit actually pays for',
'''A seller credit may adjust the price, reimburse a particular charge or fund a repair-related arrangement. Read the contract and closing statement together. The label seller credit does not decide whether the amount changes basis or another tax item. Record the gross charges and the agreed treatment rather than losing the credit inside net cash paid.''',
'''A buyer receives a $10,000 closing credit after an inspection. If the buyer later pays a contractor, the credit and contractor invoice must be reconciled with the acquisition terms. Do not assume the credit is rental income, or that the full contractor bill can be deducted immediately.''',
'Read the amendment creating the credit|Identify the charge or price adjustment involved|Retain repair estimates and final invoices|Reconcile cash, basis and capital work|Avoid counting the same cost twice')
add(53, 'Create a furnishing register before opening the rental',
'''List each material asset or supported group with cost, business use and placed-in-service date. Supplies, depreciable property and items eligible for a valid expensing election require different analysis. Separate sales tax, delivery and installation costs as needed for basis. Do not assume every furnishing purchase is deductible because it was paid before year-end.''',
'''A December order includes beds delivered in December and replacement appliances delivered in January. Record the actual readiness of each asset. A single credit-card charge date does not establish that the entire order entered service in the same tax year.''',
'Keep itemized invoices rather than card totals alone|Record installation and readiness|Separate personal items and mixed use|Reconcile any safe-harbor election|Match furnishings to the cost segregation report')
add(54, 'Check acquisition rules as well as the service date',
'''Current federal law generally restored 100% bonus depreciation for qualifying property acquired and placed in service after January 19, 2025. Eligibility, acquisition rules, binding contracts, elections and asset type still matter. A building does not become wholly eligible merely because some components qualify. Prior-year assets and state returns require separate analysis.''',
'''Two similar assets enter service on the same date but were acquired under different arrangements. The preparer needs contract and acquisition details before applying a percentage. A current-year cost segregation report does not reset an older asset's original acquisition date.''',
'Confirm acquisition and binding-contract facts|Document placed-in-service dates|Identify eligible asset classes|Review elections and excluded property|Reconcile state treatment and historical assets separately')
add(55, 'Compare eligibility and limits before choosing a deduction',
'''Section 179 and bonus depreciation have different requirements. Section 179 involves trade-or-business use, taxable-income limits and restrictions relevant to leasing arrangements. Bonus depreciation has its own acquisition, asset and election rules. A taxpayer cannot assume that a rental asset qualifies for Section 179 just because its recovery period is short.''',
'''An owner expects to expense furniture under Section 179 while reporting limited business income. The preparer should review eligibility and the income limitation, then compare any available bonus or regular depreciation treatment. The largest advertised statutory limit is not the owner's allowable deduction.''',
'Identify who owns and leases the asset|Confirm business-use requirements|Review Section 179 income and other limits|Evaluate bonus eligibility independently|Compare federal and state schedules')
add(56, 'Allocate sale proceeds across the relevant assets',
'''After cost segregation, the property can include assets with different gain and recapture treatment. Reconcile proceeds, selling expenses and adjusted basis by the appropriate categories. Section 1245 recapture, Section 1250 rules and unrecaptured Section 1250 gain are not interchangeable. Applying a single 25% rate to every dollar of depreciation is inaccurate.''',
'''A sale includes furniture that has been fully depreciated and a building with remaining basis. The allocation between them can affect gain character. Retain the purchase agreement and support for the allocation rather than assigning all sale value to whichever category produces the preferred result.''',
'Obtain complete asset-level depreciation history|Reconcile sale consideration and expenses|Support the allocation among assets|Calculate gain and character separately|Model state tax and applicable loss releases')
add(57, 'Put the anticipated sale in the same model as the deduction',
'''Compare the study's incremental current benefit with fees, later depreciation differences and the expected disposition. A near-term sale can materially change the economics. Also review whether a catch-up method change is available in the disposition year under the applicable procedure. Do not assume that a sale makes every study beneficial or impossible.''',
'''An owner expects a current deduction and a sale six months later. A model showing only the current-year tax reduction omits the planned disposition and potentially different gain character. Request a combined projection using the anticipated sale price, asset allocation and applicable losses.''',
'Estimate sale timing and consideration|Compare with and without the study|Include all implementation costs|Review disposition-year procedural eligibility|Evaluate after-tax cash over the full period')
add(58, 'Separate loan payoff from taxable gain',
'''Cash received at closing depends on debt repayment and settlement adjustments. Taxable gain generally depends on amount realized, adjusted basis and selling expenses, with special rules for particular transactions. Mortgage payoff is not itself a deduction from gain. Reconcile the closing statement and tax asset schedule together.''',
'''Ignoring other adjustments, a property sells for $700,000 with $40,000 of selling expenses and $420,000 adjusted basis. The illustrative gain is $240,000. A $500,000 mortgage payoff reduces closing cash, but it does not reduce that calculation to the cash remaining. Gain character and tax are additional steps.''',
'Reconcile gross consideration and selling expenses|Separate debt payoff and prorations|Update adjusted basis through disposition|Calculate gain by asset category|Compare the tax reserve with actual closing cash')
add(59, 'Reconcile exchange eligibility with the asset schedule',
'''Section 1031 generally applies to qualifying real property held for investment or business use. A cost segregation asset list does not by itself decide which transferred items meet the exchange definition of real property. Personal property, cash received, liabilities and the exchange structure require review. Coordinate the tax preparer and qualified intermediary before the transfer.''',
'''A furnished rental sale includes the building and separate furniture. Do not assume every item follows the building into tax-deferred treatment. The parties need a supportable allocation and an exchange analysis under the applicable real-property definitions.''',
'Provide the study and full depreciation register|Identify each asset transferred|Review exchange structure before closing|Track identification and completion deadlines|Model cash, liabilities and potentially taxable components')
add(60, 'Identify how the property was acquired before calculating depreciation',
'''A gift commonly carries over the donor's basis, with additional rules relevant to losses and certain adjustments. Inherited property generally follows date-of-death value or an applicable alternative valuation, subject to exceptions. Neither rule means that every transfer creates a new purchase basis. Debt, partial sales and entity ownership can add further issues.''',
'''Two siblings receive comparable rentals: one by lifetime gift and one through an estate. Identical market values do not establish identical tax basis. Obtain the donor's history for the gift and the estate valuation records for the inheritance before preparing depreciation.''',
'Identify gift, inheritance or part-sale treatment|Obtain donor basis or estate valuation records|Separate land and improvements|Review prior depreciation and suspended losses|Document the recipient’s rental service date')
add(61, 'Build one ownership map and separate tax calculations',
'''List the operating businesses, property owners, entity tax classifications and transactions between them. Then reconcile rents, reimbursements, loans and capital contributions. Coordinated planning does not mean all income and losses can be combined without restriction. Each taxpayer and activity needs the relevant basis, participation and reporting analysis.''',
'''An S corporation pays rent to a property LLC owned by its shareholder. The business deduction and the owner's rental result must both be recorded, while self-rental rules may affect the rental income's character. Counting only the corporation's rent deduction overstates the overall benefit.''',
'Map legal ownership and tax classification|Reconcile payments between entities|Review rental and business income character|Identify separate filings and elections|Prepare one owner-level projection using all relevant returns')
add(62, 'Treat the lease as a real transaction',
'''Separate ownership of business premises can create useful legal and operational boundaries, but tax consequences depend on the entities and actual lease. Review market rent, expense responsibilities, financing and related-party rules. Establish the property owner's records independently from the tenant business. A separate bank account does not by itself establish a separate federal taxpayer.''',
'''A business pays building insurance directly even though the lease makes the property owner responsible. The bookkeeper and preparer need to determine how that payment is recorded on both sides. Ignoring it can make the rent and expense schedules inconsistent.''',
'Identify landlord and tenant tax classifications|Document rent and lease responsibilities|Coordinate lender and legal requirements|Reconcile related-party payments|Review self-rental treatment and long-term exit plans')
add(63, 'Do not assume self-rental income and losses are symmetrical',
'''Under the applicable self-rental rules, net rental income from property rented to a business in which the taxpayer materially participates can be recharacterized as nonpassive. A net loss does not automatically receive the same treatment. Evaluate the taxpayer, activity and relevant exceptions or valid grouping rather than applying one label to all related-party rentals.''',
'''An owner expects passive losses from another property to offset profitable rent from their operating company. The self-rental recharacterization may prevent that result. Conversely, creating a loss in the leased building does not automatically make it deductible against the company's income.''',
'Identify material participation in the tenant business|Calculate the property’s net rental result|Review prior grouping positions|Analyze income and loss treatment separately|Reconcile rent terms and actual payments')
add(64, 'Start with the character of the loss',
'''Ordinary business income does not automatically absorb passive rental losses. Determine the rental's classification, participation, any relevant exception and the applicable owner-level limits. A supported nonpassive result can differ from a passive result, but a grouping election cannot simply be created to reach a desired offset without meeting its requirements.''',
'''A business owner earns $400,000 from an operating company and generates a $70,000 rental loss. Subtracting the two figures is only a preliminary illustration. The preparer must determine whether the rental loss is currently deductible before using $330,000 as a projection input.''',
'Identify rental activity treatment|Review participation and any qualifying exception|Evaluate grouping under the correct rules|Apply basis and at-risk limits where relevant|Separate usable losses from carryforwards in the projection')
add(65, 'Reconcile the same transaction on both returns',
'''When several preparers work on related entities, specify who owns the final reconciliation. Rent, loans, reimbursements and asset purchases should have consistent descriptions and amounts. K-1 timing can affect the owner return, and a revised entity return may require an owner-level change. Keep an unresolved-items list until all affected filings agree.''',
'''The operating company records $48,000 of rent, while the property records show $42,000 received. The $6,000 difference may be an unpaid amount, a misclassification or a timing issue. Resolve it using the agreements and accounting methods instead of forcing one return to match the other without analysis.''',
'Compare intercompany ledgers|Reconcile K-1s and owner schedules|Confirm shared asset and depreciation assumptions|Assign responsibility for state returns|Document how late changes reach every affected preparer')
add(66, 'Model taking the property out before putting it in',
'''An S corporation may own real estate, but appreciated-property distributions and a later exit can create consequences owners do not expect. S corporation loss and debt-basis rules also differ from partnership rules. Review the long-term ownership plan, financing and shareholder needs before choosing an entity solely because it is already available.''',
'''An owner plans to move an appreciated rental from an S corporation into a personally owned LLC before selling. That move is not automatically tax-free merely because the ultimate owner remains the same. The corporation and shareholder consequences must be modeled before a deed is signed.''',
'Identify current basis and fair market value|Review financing and shareholder basis|Model sale and distribution alternatives|Check prior C corporation history where relevant|Coordinate legal documents only after the tax analysis')
add(67, 'Compare the owner’s eventual cash, not only the corporate rate',
'''A C corporation's tax rate is one part of an ownership decision. Rental profits, a property sale and distributions to shareholders can involve separate tax consequences. Retaining cash, paying compensation and making loans each have their own requirements. A 21% corporate rate should not be presented as the final rate on all money an owner ultimately receives.''',
'''An owner compares holding a rental personally with holding it in a C corporation. Include annual rental profits, the expected sale and how sale proceeds would reach the owner. A model that stops before the shareholder distribution can make the corporate option appear artificially inexpensive.''',
'Model annual operations and eventual sale|Specify how cash reaches shareholders|Review accumulated earnings and other applicable rules|Compare state consequences|Document commercial reasons for the selected ownership structure')
add(68, 'Resolve ownership and records before the closing deadline',
'''Discuss the intended buyer, taxpayer classification, financing and business use while the contract can still be reviewed. Obtain a cost breakdown for separately purchased equipment and planned improvements. Coordinate tax advice with lender and legal requirements. A last-minute LLC name change can have consequences beyond the depreciation schedule.''',
'''A practice acquires a building and equipment in one transaction. If the agreement does not identify what was purchased, the later allocation may become harder to support. Ask the transaction team to preserve valuation and asset detail rather than relying on an estimated split after closing.''',
'Confirm the legal buyer and federal taxpayer|Document the asset allocation|Separate acquisition from financing costs|Plan improvement and readiness records|Identify who will coordinate depreciation and the first return')
add(69, 'Distinguish the property owner from the practice using it',
'''An owner-occupied business property may be held by the operating company or a different taxpayer. That determines who claims depreciation and how rent or related-party payments are treated. The study should describe actual building use and asset function, with support for specialized systems. A practice's industry does not automatically establish the recovery period of every fixture.''',
'''A dental practice leases from a related property entity and purchases equipment itself. The building owner's study should not include the practice's separately owned equipment as if it were the landlord's basis. Reconcile both asset registers before implementing the report.''',
'Identify owner and tenant for each asset|Separate equipment from building improvements|Document specialized asset function|Reconcile related-party rent and expenses|Assign study implementation to the correct preparer')
add(70, 'Use one year-end agenda across all ownership interests',
'''Collect projected business income, rental results, owner compensation, distributions, estimated payments and planned transactions. Distinguish decisions that require action before year-end from filings that may occur later. Record who implements each item. A consolidated agenda helps identify interactions, but does not erase separate entity or activity rules.''',
'''A business owner considers a retirement contribution while also planning a rental improvement and a large distribution. Each draws on cash, and the tax benefits depend on different requirements. Model funding and tax effects together so three individually plausible strategies do not exceed available liquidity.''',
'Refresh entity and personal projections|Reconcile cash and estimated payments|Review upcoming asset service dates|Confirm retirement-plan funding obligations|Assign deadlines and completion evidence for each decision')
add(71, 'Ask what happens between the recommendation and filing',
'''Tax preparation reports completed activity and applicable positions. Planning evaluates choices while they can still be implemented. An effective engagement specifies whether the advisor recommends a strategy, prepares documents, coordinates third parties, monitors completion or files the resulting return. These responsibilities may be divided across separately priced services.''',
'''A memo recommends an accountable plan, but no policy is adopted and no expenses are substantiated or reimbursed. The memo alone does not establish the deduction. Ask which person will turn the recommendation into a documented process and which preparer checks the resulting entries.''',
'Request written deliverables|Identify implementation responsibilities|Confirm separately billed filing work|Schedule progress reviews|Retain evidence that approved steps were completed')
add(72, 'Make the plan usable by the people completing the work',
'''A written tax plan should identify the taxpayer, relevant facts, assumptions, applicable rules, alternatives and recommended actions. Separate estimated benefits from confirmed results. Include an owner, deadline, required document and completion standard for each action. A strategy name without these details is difficult to implement reliably.''',
'''Instead of listing consider cost segregation, a plan can assign acquisition-record collection to the owner, feasibility analysis to the advisor and return implementation to the preparer. The plan should also state that the study is separately priced and that deduction usability remains subject to analysis.''',
'Record facts and unresolved assumptions|Explain the recommended action and alternatives|Separate tax estimates from implementation status|Assign responsible people and dates|Define what proves each step is complete')
add(73, 'Compare distributions and an exit alongside annual tax',
'''A fair S corporation and C corporation comparison uses the same operating assumptions, owner cash needs and expected holding period. Include reasonable compensation, payroll, owner-level tax, applicable deductions and state treatment. For a C corporation, model shareholder distributions and exit consequences. Eligibility and administrative requirements matter alongside the calculated rate.''',
'''Two models show the same business profit, but one assumes the owner takes all cash and the other retains it indefinitely. Those are different financial scenarios. Align the owner cash requirement before deciding which entity produces the better after-tax outcome.''',
'Use consistent profit and compensation assumptions|Model owner withdrawals explicitly|Include federal and state consequences|Review eligibility and conversion costs|Compare a realistic sale or liquidation scenario')
add(74, 'Document the work before selecting the salary',
'''Reasonable compensation depends on services, responsibilities, time, experience and relevant market evidence. A fixed percentage of profit is not a universal IRS rule. Explain how revenue is generated by the owner's services, other workers and capital. Revisit the analysis when the role or business changes materially.''',
'''A founder moves from delivering every service to managing a staffed company. Last year's salary analysis may no longer describe the role. Document actual responsibilities and comparable compensation rather than reducing wages simply because distributions increased.''',
'Describe the owner’s duties and hours|Collect relevant compensation comparisons|Explain revenue sources and staffing|Document the selected wage and rationale|Coordinate payroll changes with retirement and QBI analysis')
add(75, 'Build a reimbursement process with actual substantiation',
'''An accountable arrangement requires a business connection, timely substantiation and timely return of excess advances. A policy document alone does not turn personal spending into a business deduction. Identify eligible costs, submission evidence, approval responsibility and how excess or unsupported payments are treated.''',
'''An owner submits a mixed personal and business internet bill. The business should reimburse only the supported eligible portion under the arrangement, checking that it has not already paid or deducted the same cost elsewhere. A round monthly allowance without substantiation requires different treatment.''',
'Adopt a clear written reimbursement process|Retain receipts and allocation support|Review claims within the applicable timing rules|Recover or properly report excess payments|Reconcile reimbursements to books and payroll')
add(76, 'Match the reimbursement to an eligible business use',
'''An S corporation owner should not automatically claim the corporation's business expenses directly on an individual schedule. Review the workspace's qualifying use and the corporation's reimbursement arrangement. Distinguish direct room costs, allocable home costs and personal expenses. A floor-plan allocation needs supporting measurements and the appropriate expense treatment.''',
'''A room used as both a guest bedroom and an office may not satisfy an exclusive-use requirement. Calling the room an office in a reimbursement form does not resolve that fact. Review use before calculating a percentage of the entire home's expenses.''',
'Document workspace use and measurements|Identify applicable home-office requirements|Retain eligible expense records|Prepare a supported reimbursement claim|Reconcile corporation and individual reporting to prevent duplication')
add(77, 'Support the business rental, not just the day count',
'''The less-than-15-day home-rental exclusion and the business's deduction are separate analyses. The home must meet the relevant residence rules, while the business needs a legitimate expense and reasonable rent. Keep agreements, agendas, attendance, comparable pricing and payment records. Fourteen calendar entries alone do not establish a defensible business deduction.''',
'''A company holds one planning meeting at the owner's home. A proposed daily rent should reflect the actual space, use and market evidence rather than a target deduction. Multiple related companies also need coordination so the owner's total rental days are not overlooked.''',
'Confirm the home and annual rental-day facts|Document the meeting’s business purpose|Support fair rental value|Retain agreement and payment evidence|Review both business and owner tax treatment')
add(78, 'Compare funding obligations as well as deductions',
'''Retirement-plan selection depends on owner age, compensation, employee census, related businesses and sustainable cash flow. A defined benefit or cash balance plan can require actuarial work and ongoing funding. A solo plan depends on eligibility, and adding employees can change the available choices. Annual limits are not interchangeable across plan types.''',
'''An owner wants a large deduction after one unusually profitable year but expects lower cash flow next year. Compare the commitment and employee costs of a pension arrangement with more flexible alternatives. A contribution estimate is not a plan recommendation until the census and funding assumptions are reviewed.''',
'Provide employee and owner census data|Identify related employers|Model several years of funding|Include administration and employee costs|Confirm adoption and contribution deadlines with the plan professional')
add(79, 'Evaluate wages within the complete Section 199A calculation',
'''The qualified business income deduction depends on taxable income, business type, wages, qualified property and other rules. Owner wages are not themselves QBI. Increasing wages can reduce business income while affecting a wage limitation, so maximizing one input does not necessarily maximize after-tax cash. Use the current year's thresholds and filing status.''',
'''An S corporation owner considers a wage increase solely to improve the QBI wage limit. The projection should include reduced pass-through income, payroll tax and any retirement contribution effect. A spreadsheet that changes only the wage-limit line can give the wrong direction.''',
'Confirm filing status and taxable-income assumptions|Identify specified service business issues|Reconcile QBI, wages and qualified property|Include payroll and retirement effects|Compare total tax rather than the deduction in isolation')
add(80, 'Give each quarter a decision and a completion check',
'''Quarterly planning works best when current books lead to specific actions. Early reviews can address prior-year findings and record systems; midyear reviews can revise projections; later reviews can resolve timing and implementation. Track the same action list across meetings so recommendations do not restart each quarter.''',
'''A second-quarter review identifies missing owner reimbursement records. The next meeting should confirm whether the process was adopted and claims were substantiated, not merely recommend an accountable plan again. Use the books and completed documents to verify progress.''',
'Update books and the annual projection|Review compensation and estimated payments|Identify changes in entities or property operations|Assign action owners and due dates|Check completion evidence at the next meeting')
add(81, 'Ask questions that reveal who owns the outcome',
'''Ask a prospective provider how it reconciles basis, handles incomplete records, supports asset classifications and communicates with the preparer. Request a description of deliverables and exclusions. Audit support may mean answering report questions, while representation can be a separate engagement. Compare written terms rather than treating the words audit-ready as a guarantee.''',
'''A buyer receives a sample report and a promise of support. Ask what happens if the preparer identifies a duplicated asset, a state adjustment or a question two years later. The answer should identify the responsible party and any additional fee, not merely repeat that support is included.''',
'What property records are required?|How are classifications and estimates supported?|Who reconciles existing depreciation?|Who handles tax forms and owner loss analysis?|What precisely does post-delivery support cover?')
add(82, 'Put every quote into the same scope comparison',
'''Compare property coverage, asset detail, basis reconciliation, delivery format, revision terms and support. Separately identify the tax return, method-change filing and owner-level projection. Do not assume these are included because the study will ultimately be used for tax purposes. AE cost segregation is separately priced from advisory.''',
'''One proposal covers a building as acquired, while another also analyzes a later renovation. The prices are not directly comparable until the scope is aligned. Ask how the provider will handle newly supplied invoices and whether the quote covers federal and state implementation.''',
'Identify properties and tax years covered|List assumptions and missing records|Compare report and asset-schedule deliverables|Separate implementation and return fees|Confirm revision, cancellation and support terms')
add(83, 'Select a provider for the property and implementation needs',
'''A residential rental owner should compare relevant property experience, methodology, documented deliverables and how the report reaches the tax return. National scale, software convenience and bundled advisory are different characteristics. There is no universal best provider for every property. AE publishes this guide and offers separately priced cost segregation services.''',
'''An investor with complete records and an experienced preparer may need a different scope from an owner missing five years of depreciation history. Use the same factual property brief when requesting information from providers. A provider's public website is a starting point; confirm current terms in its proposal.''',
'Confirm experience with the actual property type|Request current primary-source scope information|Distinguish software output from professional deliverables|Identify implementation ownership|Compare total scope without assuming unpublished competitor terms')
add(84, 'Match the method to the complexity of the property',
'''Software can organize inputs and produce calculations, but output quality depends on accurate facts, appropriate methodology and the user's judgment. Professional engagements can differ in inspection, analysis and support. Neither a software label nor an engineering label alone establishes that a particular report correctly treats the property.''',
'''A straightforward acquisition with complete cost records differs from a mixed-use property with several renovations and missing asset history. Before selecting a method, list the decisions the tool cannot resolve by itself, including land support, existing depreciation and the owner's loss limitations.''',
'Identify who validates the input records|Review treatment of unusual assets|Request methodology and assumption disclosures|Confirm revision and question support|Ensure the preparer can implement the output')
add(85, 'Separate report delivery from completed tax work',
'''A standalone study and coordinated implementation are different scopes, not necessarily different report quality. The owner needs to know who reviews the study, reconciles historical schedules, evaluates loss usability and prepares any required filings. These services may be provided by several professionals. Confirm their responsibilities before paying for work.''',
'''The study provider delivers a report while the existing CPA expects another firm to prepare Form 3115. Unless the engagement assigns that task, the project can stall despite a completed report. A responsibility table prevents the owner from discovering the gap at filing time.''',
'Assign report questions to the provider|Assign basis reconciliation to a named preparer|Confirm responsibility for Form 3115 if needed|Assign owner-level loss analysis|Track the final return implementation separately from report delivery')
add(86, 'Interview the CPA using your actual operating model',
'''Describe average stays, guest services, management arrangements, personal use, property ownership and other income. Ask how the CPA analyzes each fact and documents the conclusions. A preparer familiar with ordinary rental returns may still need additional support for an STR with complex participation or asset issues. Credentials should be verified through the relevant official licensing source.''',
'''Ask how the preparer would handle a property moving from weekend stays to monthly leases. A useful answer identifies the operational records and tax questions that change. A blanket claim that every Airbnb loss offsets wages is a reason to request a more specific explanation.''',
'Describe actual stays and services|Ask about participation documentation|Confirm depreciation and method-change experience|Verify credentials and engagement scope|Ask who answers implementation questions during filing')
add(87, 'Choose an advisor who can connect all the relevant returns',
'''Business and rental owners need clarity about entity filings, owner projections, depreciation, carryforwards and state coordination. Compare the documented scope and communication process rather than only the advisor's list of strategies. A firm may coordinate with outside professionals; ask who remains accountable for the handoff.''',
'''A prospective advisor offers planning but the owner has three business returns and five rental properties with another CPA. Before signing, identify who receives the plan, who implements each recommendation and who reconciles the final personal return. Coordination should be explicit rather than assumed.''',
'List all entities, properties and states|Verify relevant licenses through official sources|Compare planning and filing scope|Ask how multiple preparers coordinate|Confirm meeting cadence and response expectations in writing')
add(88, 'Compare firms using a consistent client brief',
'''Give each firm the same summary of profit, ownership, rental activity, states and unfinished work. Compare published scope and confirmed proposals, with dates for pricing information. A firm may be a strong fit for one client and unsuitable for another. AE publishes this comparison and is one of the service providers discussed.''',
'''A low planning fee may exclude return preparation, entity work or cost segregation. A higher fee may include some of those services, or may simply cover a different engagement. Do not infer value from the price alone. Ask each firm to identify the exact deliverables and exclusions.''',
'Use the same client facts for every comparison|Verify current provider information|Compare implementation responsibilities|Separate recurring and one-time fees|Disclose missing or unconfirmed information')
add(89, 'Compare total annual scope without assuming a renewal term',
'''Separate the initial planning engagement, recurring advisory, return preparation and project fees. Identify payment timing, renewal terms and cancellation provisions. Cost segregation is not included in AE advisory. A fee published for one service should not be reused as the total cost of every engagement.''',
'''A business owner needs advisory, two entity returns, a personal return and a study. A comparison that lists only advisory pricing leaves out material work. Request a written scope-based estimate from each provider without assuming that either firm includes those additional services.''',
'List every required service|Identify one-time versus recurring charges|Confirm renewal and cancellation terms|Review payment milestones|Record the date and source of each verified fee')
add(90, 'Use business changes to identify a planning need',
'''Planning becomes more valuable when decisions remain open: a new property purchase, entity change, employee hiring, a large distribution, retirement funding or an anticipated sale. The issue is whether the engagement covers those decisions before they happen. Annual preparation can be appropriate for a simpler situation.''',
'''An owner signs a property sale contract and then asks the preparer about exchange planning after closing. Earlier advice could have identified deadlines and structural requirements. The lesson is to notify the advisor when a transaction is contemplated, rather than assuming every tax choice can be made during filing.''',
'List transactions expected in the next year|Identify decisions with pre-transaction deadlines|Review changes in profit and owner cash needs|Ask whether current engagement covers planning|Schedule a call before signing consequential agreements')
add(91, 'Worked example: a study allocation is not a tax refund',
'''This hypothetical example uses a rental with $500,000 of supported depreciable basis and a professionally supported $100,000 short-life allocation. It does not assume that a purchase price alone establishes either number. Acquisition dates, asset eligibility, participation and applicable loss limits remain separate requirements. These are teaching assumptions, not verified AE client results.''',
'''If the proposed treatment creates $80,000 of incremental currently usable deductions and the assumed incremental federal rate is 32%, the modeled current federal effect is $25,600. If the deductions are suspended, the immediate modeled effect can be zero. Fees, state treatment and future recapture are excluded from this simplified calculation.''',
'Verify acquisition basis and land|Document asset-level eligibility|Establish activity and participation treatment|Calculate incremental usable deductions|Distinguish modeled effect from a filed outcome')
add(92, 'Worked example: a long-term rental loss may be deferred',
'''Assume a hypothetical long-term rental produces a $30,000 tax loss after depreciation. The owner has no offsetting passive income and does not establish an applicable exception. Subject to the complete limitation analysis, the loss may be suspended rather than reducing wages. This example does not document an actual client or a completed filing.''',
'''If facts later change, the owner must evaluate the relevant release rules; they cannot simply relabel the old loss as active. Real estate professional qualification and material participation are distinct questions. Any aggregation election must be valid and supported, with its ongoing consequences understood.''',
'Calculate property income and depreciation|Review basis and at-risk rules|Determine passive treatment and exceptions|Track any suspended amount by activity|Retain elections and annual participation support')
add(93, 'Worked example: reconcile business rent and property income',
'''A hypothetical business pays $36,000 annual rent to a separately owned property entity. The business's deduction does not represent a $36,000 combined reduction in taxable income because the property side must report the corresponding rental transaction. Property expenses, depreciation and self-rental treatment require separate analysis.''',
'''If a projection subtracts rent from business profit but omits rental income from the owner's other return, it understates the combined result. Start with both sides of the transaction, then evaluate the property's actual expenses and the owner's limitations. No tax-saving amount is claimed from these assumptions alone.''',
'Identify landlord and tenant taxpayers|Reconcile rent paid and received|Review the lease and expense responsibilities|Analyze self-rental rules|Combine completed entity results in the owner projection')
add(94, 'Worked example: bridge prior depreciation before filing',
'''Assume an eligible hypothetical method change has $75,000 of cumulative proper depreciation and $20,000 previously deducted through the beginning of the year of change. The $55,000 difference illustrates the reconciliation behind a potential catch-up adjustment. It is not proof that this procedure applies to a particular owner.''',
'''The preparer still needs to confirm the current automatic-change rules, applicable form, statement and filing requirements. Current-year depreciation is calculated separately. Even a valid negative adjustment may not produce an immediate tax reduction if the resulting loss is limited. This is not a confirmed refund or AE client outcome.''',
'Identify the adopted method and correction eligibility|Recompute historical depreciation|Reconcile the adjustment without duplicating current depreciation|Complete required filing steps|Apply owner-level limits and retain the workpapers')
add(95, 'Worked example: prioritize five properties separately',
'''Consider a hypothetical portfolio of five rentals. Two already have studies, one is scheduled for sale and two have unresolved depreciation questions. The appropriate work is not necessarily five new studies. Review prior reports, remaining basis, proposed transactions and records before setting the project scope.''',
'''A portfolio worksheet can show prior study status, missing records, expected holding period and preparer responsibility for each address. The owner may first reconcile an existing report, model the planned sale and evaluate the two unresolved properties. No portfolio savings total can be responsibly calculated from property count alone.''',
'List ownership and acquisition history by property|Identify studies and method changes already completed|Separate missing records from new study needs|Model the pending sale|Assign a next action and implementation owner to each address')
add(96, 'Worked example: wages, reimbursements and retirement are separate',
'''A hypothetical consulting S corporation reviews owner compensation, eligible expense reimbursements and a retirement plan. Each requires its own analysis. Wages must reflect reasonable compensation; reimbursements require actual eligible expenses and substantiation; retirement contributions depend on the plan and relevant limits.''',
'''The company cannot count the same $10,000 expense once in operating costs and again as a reimbursement saving. Likewise, a retirement contribution is a funding commitment, not free cash. A combined projection should reconcile deductions, payroll, cash outflows and the owner's return without stacking overlapping benefits.''',
'Document compensation responsibilities and market support|Reconcile reimbursements with existing expenses|Confirm employee and plan eligibility|Model funding and payroll costs|Compare combined after-tax cash using explicit assumptions')
add(97, 'Transfer the tax history, not only last year’s PDF',
'''Request complete returns, depreciation registers, carryforward worksheets, election statements and unresolved correspondence. Confirm who handles extensions, pending amendments and notices during the transition. A new preparer should not have to infer historical choices from summary totals. Use a secure document channel for returns and identity information.''',
'''The outgoing CPA supplies the personal return but not entity basis schedules or a rental aggregation election. The new preparer may be missing information that materially affects the next filing. Track each missing item and its requested source rather than marking the transition complete after one upload.''',
'List each taxpayer and outstanding filing|Request asset and carryforward exports|Obtain election and notice records|Confirm extension and payment responsibility|Reconcile the opening balances before preparing the next return')
add(98, 'Prepare a short decision summary for the call',
'''Bring the main question, business and property ownership summary, approximate income sources, upcoming transactions and any known deadline. The first call can help define scope and next steps; it does not replace a document-based technical review. Do not email sensitive tax records through an unsecured channel merely to prepare for a discovery conversation.''',
'''An owner considering a rental purchase can explain the property type, anticipated closing date, existing advisor and desired planning outcome. That is more useful than requesting a guaranteed savings figure before basis, operating plans and eligibility have been reviewed.''',
'Identify the decision you need to make|List entities, properties and states|Mention contracts or filing deadlines|Describe unfinished work with the current preparer|Ask how records, scope and next steps will be handled')
add(99, 'Turn every recommendation into a verifiable task',
'''Collect the written plan and identify which steps were approved, completed, blocked or never assigned. For each open step, list the required record, responsible person, deadline and completion evidence. Some missed actions can still be addressed; others may have procedural limits. Do not backdate documents or assume late implementation recreates earlier facts.''',
'''A plan recommends a retirement contribution, but the funds were never transferred and no plan professional confirmed the deadline. Verify the adoption and contribution rules before treating the deduction as available. Mark the item unresolved until the responsible professional confirms the permitted next step.''',
'Inventory recommendations and commitments|Attach actual completion evidence|Identify missed deadlines|Assign one owner to each unresolved item|Obtain a revised implementation schedule and tax projection')
add(100, 'Use completion evidence at each handoff',
'''The process moves from facts and analysis to an approved action, supporting records, accounting entries, return preparation, review and filing. Each stage can fail independently. A signed engagement is not proof that a strategy was implemented, and a completed memo is not proof that a return reflects it.''',
'''For a cost segregation project, the file should connect the report to the reconciled asset schedule, any required method-change filing and the final return workpaper. Where a return is electronically filed, retain the applicable acceptance evidence. Where a filing uses another method, preserve the relevant proof of submission.''',
'Confirm facts and written recommendations|Record approval and implementation tasks|Reconcile completed work to the books|Review the resulting return and elections|Retain filing evidence and update future-year records')
