#!/usr/bin/env python3
"""Delete the machine-facing `definition-lead` paragraphs from every page.

That copy now lives in dedicated files instead, generated by llm_txt.py:

    /llms.txt
    /llms.md
    /.well-known/llms.txt

so retrieval systems get the firm description, pricing, stats and citation
guidance from one canonical place, and no visitor sees a boxed paragraph.

Two shapes exist on the site and they are handled differently:

  * The paragraph is alone in the section llm_leads.py wrapped around it.
    The whole section goes, otherwise an empty bordered block is left behind.
  * The paragraph sits beside a `post-meta` byline. Only the paragraph goes,
    because the byline is real page furniture.

Idempotent. Run after any pass that might reintroduce a lead.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

LEAD = re.compile(r'[ \t]*<p class="definition-lead">.*?</p>\n?', re.S)
SECTION_OPEN = re.compile(r"<section\b", re.I)
SECTION_TAG = re.compile(r"<(/?)section\b", re.I)
CONTENT_TAG = re.compile(r"<(p|h1|h2|h3|h4|ul|ol|table|iframe|img|blockquote)\b", re.I)


def _section_bounds(html: str, pos: int) -> tuple[int, int] | None:
    """Span of the <section> enclosing `pos`, matched by depth."""
    start = -1
    for m in SECTION_OPEN.finditer(html):
        if m.start() > pos:
            break
        start = m.start()
    if start == -1:
        return None

    depth, i = 0, start
    while i < len(html):
        m = SECTION_TAG.search(html, i)
        if not m:
            return None
        depth += -1 if m.group(1) else 1
        i = m.end()
        if depth == 0:
            close = html.find(">", i)
            if close == -1:
                return None
            end = close + 1
            return (start, end) if start <= pos < end else None
    return None


def strip(html: str) -> tuple[str, int, int]:
    """Returns (html, paragraphs_removed, sections_removed)."""
    paras = sections = 0

    while True:
        m = LEAD.search(html)
        if not m:
            break

        bounds = _section_bounds(html, m.start())
        if bounds:
            s, e = bounds
            body = html[s:e]
            remaining = CONTENT_TAG.findall(body.replace(m.group(0), ""))
            if not remaining:
                # Nothing but the lead lived here; drop the wrapper too.
                line_start = html.rfind("\n", 0, s) + 1
                end = e
                while end < len(html) and html[end] in "\r\n":
                    end += 1
                html = html[:line_start] + html[end:]
                paras += 1
                sections += 1
                continue

        html = html[: m.start()] + html[m.end() :]
        paras += 1

    return html, paras, sections


def main(dry: bool = False) -> int:
    files = changed = total_p = total_s = 0
    for path in sorted(ROOT.rglob("*.html")):
        if ".git" in path.parts:
            continue
        before = path.read_text(encoding="utf-8")
        if "definition-lead" not in before:
            continue
        files += 1
        after, p, s = strip(before)
        total_p += p
        total_s += s
        if after != before:
            changed += 1
            if not dry:
                path.write_text(after, encoding="utf-8")

    verb = "would remove" if dry else "removed"
    print(f"strip_llm_leads: {verb} {total_p} paragraphs "
          f"({total_s} empty wrapper sections) across {changed}/{files} files")
    return 0


if __name__ == "__main__":
    sys.exit(main(dry="--dry-run" in sys.argv))
