"""Batch: additional profession tax strategy guides."""

from blog_gen import write_all

C = "Tax Strategy"
D = "2026-08-11"

ARTICLES = [
{
"slug": "tax-strategy-for-day-traders",
"title": "Tax Strategy for Day Traders: Trader Status and the Section 475 Election",
"meta_title": "Tax Strategy for Day Traders and Section 475 (2026) | AE Tax Advisors",
"meta_desc": "Trader tax status plus a Sec. 475(f) mark to market election removes wash sales and the capital loss cap. Requirements and the April deadline for 2026.",
"category": C, "date": D,
"intro": [
"Active traders face two problems that have nothing to do with market performance. Capital losses are limited to $3,000 per year against ordinary income, and wash sale rules under IRC Sec. 1091 disallow losses on positions repurchased within 30 days.",
"For someone making hundreds of trades, both are severe. A trader with $340,000 of realized losses can deduct $3,000. A trader with substantial round-trip activity can end the year with a taxable gain despite losing money.",
"Trader tax status combined with a Section 475(f) election solves both. The election has a deadline most traders miss by months.",
],
"sections": [
("Trader Tax Status Comes First", [
"There is no statute defining a trader. The distinction between an investor and a trader is developed through case law, and it turns on whether the activity rises to the level of a trade or business.",
"Courts look at whether the trading is substantial, frequent, regular, and continuous, and whether the taxpayer seeks profit from short-term price swings rather than from dividends, interest, or long-term appreciation.",
"The factual markers that carry weight are trade frequency and volume, average holding period measured in days rather than months, hours devoted to the activity, and the presence of a business-like operation with equipment, data services, and a defined methodology.",
"There is no bright line, but the pattern that survives examination generally involves hundreds of trades across most trading days, short holding periods, and the activity functioning as the taxpayer's primary occupation or a substantial secondary one.",
"Part-time traders with other full-time employment can qualify but face a harder case. The activity must still be regular, continuous, and substantial.",
]),
("What Trader Status Alone Provides", [
"Trading expenses become deductible as business expenses on Schedule C rather than as investment expenses, which are not currently deductible at all for individuals.",
"That covers data feeds, platform fees, education, a home office, computers and monitors, and professional fees. For an active trader these can total $30,000 or more annually, and without trader status none of it is deductible.",
"Trading gains and losses remain capital, however. The $3,000 limitation and the wash sale rules still apply. Trader status alone does not solve the core problem.",
]),
("The Section 475(f) Mark to Market Election", [
"IRC Sec. 475(f) permits a trader in securities to elect mark to market accounting. Under the election, positions are treated as sold at fair market value on the last business day of the year, and gains and losses become ordinary rather than capital.",
"Three consequences follow. Wash sale rules no longer apply, because there are no capital transactions to which they attach. The $3,000 capital loss limitation no longer applies, because losses are ordinary. And there is no need to track holding periods or basis lots for trading positions.",
"The tradeoff is that gains are also ordinary, forfeiting long-term capital gain rates. For a genuine day trader with a holding period measured in hours, this costs nothing because no position was going to be long-term anyway.",
"Ordinary trading losses can also create or increase a net operating loss under IRC Sec. 172, carrying forward to offset future income, subject to the 80% of taxable income limitation.",
]),
("The Deadline Nobody Meets", [
"For an existing individual taxpayer, the Sec. 475(f) election must be made by attaching a statement to the prior year return or to a request for extension, filed by the unextended due date of the prior year return.",
"In practical terms, to have the election effective for 2026, an individual generally must file the election statement by the April 2026 filing deadline for the 2025 return. The election is made before the year it applies to, not after it.",
"This is the single most common failure. A trader who has a devastating year and seeks help in February of the following year cannot elect retroactively. The loss is capital, limited to $3,000, and the wash sales stand.",
"A newly formed entity has more flexibility. A new trading entity can make the election in its own books and records within two and a half months of formation, which is why traders who miss the individual deadline sometimes form an entity mid-year to capture the election prospectively.",
"Form 3115 must also be filed in the year the election takes effect to change the method of accounting.",
]),
("Entity Structure for Traders", [
"Many traders operate through an entity, usually an LLC taxed as a partnership or S corporation, for reasons beyond the election timing.",
"An S corporation allows the trader to pay themselves a salary, which creates earned income. This matters because trading gains, even under a 475 election, are not self-employment income and therefore do not support retirement plan contributions. Without earned income, a trader cannot fund a solo 401(k).",
"A trader with $600,000 of trading income and no salary has no retirement plan capacity at all. Paying a $180,000 salary through an S corporation creates the earned income needed to fund a solo 401(k) with profit sharing, and potentially a cash balance plan.",
"The salary costs payroll tax, so the analysis is whether the retirement deduction exceeds the payroll tax cost. For a trader capable of funding $70,000 to $250,000 of retirement contributions, it usually does by a wide margin.",
]),
("What the Election Does Not Cover", [
"The Sec. 475(f) election for securities does not automatically cover commodities and futures, which are a separate election under Sec. 475(f)(2).",
"Section 1256 contracts, including regulated futures and broad-based index options, already receive favorable treatment under IRC Sec. 1256: 60% long-term and 40% short-term regardless of holding period, with mark to market at year end and no wash sale application.",
"A trader active in Sec. 1256 contracts generally should not elect 475 for commodities, because doing so converts the favorable 60/40 blend into fully ordinary income. This is a real and expensive mistake.",
"Investment positions held separately from the trading business can be segregated and excluded from the election, preserving capital gain treatment on a long-term portfolio. The segregation must be identified contemporaneously in the records.",
]),
("Worked Example: Election Timing", [
"A trader executes roughly 1,900 trades annually with an average holding period of under two days, devotes 45 hours a week to the activity, and has $58,000 of platform, data, and equipment expense.",
"In year one without trader status or an election, they realize $410,000 of gross gains and $486,000 of gross losses. Wash sale adjustments disallow $94,000 of losses, so reported net capital loss is a fraction of the economic loss and only $3,000 is deductible. Trading expenses are not deductible. Taxable income reflects almost none of the economic reality.",
"They file a Sec. 475(f) election statement with their year one return by the April deadline, effective for year two, and file Form 3115 with the year two return.",
"In year two they realize $520,000 of gross gains and $571,000 of gross losses. Under mark to market, the net $51,000 loss is ordinary and fully deductible, wash sales do not apply, and $58,000 of trading expenses are deductible on Schedule C.",
"They also form an S corporation, pay a $150,000 salary, and fund a $70,000 solo 401(k) contribution that was unavailable to them before.",
"The economics of the trading did not change. The tax result changed by roughly $190,000.",
]),
],
"faqs": [
("What is trader tax status?",
 "A case law determination that trading activity rises to the level of a trade or business. Courts weigh trade frequency and volume, holding periods measured in days, hours devoted, and whether the operation is business-like. There is no statutory definition or bright line."),
("What does the Section 475 election actually do?",
 "It treats positions as sold at fair market value at year end and converts trading gains and losses to ordinary. That eliminates the wash sale rules under IRC Sec. 1091 and the $3,000 capital loss limitation, at the cost of forfeiting long-term capital gain rates you were not earning anyway."),
("When is the Section 475 election due?",
 "For an existing individual, by the unextended due date of the prior year return. To be effective for 2026, an individual generally files the statement with the 2025 return by the April 2026 deadline. It cannot be made retroactively after a bad year."),
("Can I still make the election if I missed the deadline?",
 "Not for the current year as an individual. A newly formed trading entity can make the election in its books and records within two and a half months of formation, which is why traders who miss the deadline sometimes form an entity to capture it prospectively."),
("Should I elect 475 for futures and commodities?",
 "Usually not. Section 1256 contracts already receive 60% long-term and 40% short-term treatment with year-end mark to market and no wash sales. Electing 475 for commodities converts that favorable blend into fully ordinary income, which is a costly mistake."),
],
"related": [
("/blog/how-much-can-i-contribute-to-a-solo-401k/", "Solo 401(k) contribution limits"),
("/blog/should-i-elect-s-corp-status-for-my-llc/", "Electing S corp status for your LLC"),
("/blog/3115-change-accounting-method-playbook/", "Form 3115 accounting method changes"),
],
"cta_head": "The Deadline Is Before the Year You Need It",
"cta_body": "If you are trading actively and have not filed the election, the window for next year closes in April. Bring your trade history and expense detail.",
},

{
"slug": "tax-strategy-for-crypto-investors",
"title": "Tax Strategy for Crypto Investors: Lot Selection, Staking, and the Wash Sale Question",
"meta_title": "Tax Strategy for Crypto Investors (2026 Guide) | AE Tax Advisors",
"meta_desc": "Crypto basis tracking, per-wallet accounting, staking income timing, and loss harvesting rules. What changed with broker reporting and what to do in 2026.",
"category": C, "date": D,
"intro": [
"Crypto taxation is not conceptually difficult. Digital assets are property, so every disposition is a taxable event measured against basis. The difficulty is entirely in the record keeping, and the rules on how those records must be kept have tightened substantially.",
"Investors who moved assets across a dozen wallets and exchanges over several years have a reconstruction problem that gets more expensive every year they postpone it.",
],
"sections": [
("Every Disposition Is a Taxable Event", [
"Selling crypto for dollars is a disposition. So is trading one token for another, spending crypto on goods or services, and paying a fee in crypto.",
"Gain or loss is the difference between the fair market value received and the basis in the units disposed of, characterized as short-term or long-term based on the holding period.",
"Token-to-token trades are the item investors most often overlook. Swapping one asset for another is a sale of the first asset at fair market value, not a like-kind exchange. IRC Sec. 1031 has been limited to real property since 2017, and the IRS position was that crypto never qualified even before that.",
]),
("Per-Wallet Accounting Changed the Rules", [
"The IRS has moved to a per-wallet or per-account basis tracking requirement for digital assets, replacing the universal pooling approach many taxpayers and software packages used.",
"Under the universal approach, an investor treated all units of a token across all wallets as a single pool and selected lots from that pool. Under per-wallet accounting, basis must be tracked separately by wallet or account, and a disposition from one wallet can only draw on lots held in that wallet.",
"This matters for lot selection. An investor holding high-basis units on one exchange and low-basis units on another can no longer sell from one and identify lots from the other.",
"Transitional guidance permitted a one-time allocation of existing basis across wallets under a reasonable method, documented as of a specified date. Investors who did not perform that allocation have a gap in their records that becomes harder to defend over time.",
]),
("Specific Identification Requires Contemporaneous Records", [
"The default method is first in, first out within each wallet. Specific identification is permitted and is almost always more favorable, but it requires identifying the specific units at the time of the transaction, not at tax time.",
"That means the identification must be made in the records or with the broker before or at the time of the sale, specifying the acquisition date, basis, and quantity of the units disposed of.",
"An investor who sells in March and decides in the following February which lots those were has not made a valid specific identification. The default applies.",
"Practically, this means using software that records lot selection at transaction time and instructing exchanges accordingly where they support it.",
]),
("Wash Sales Do Not Currently Apply, But Plan Carefully", [
"IRC Sec. 1091 applies to stock and securities. Digital assets are treated as property rather than securities for this purpose, so the wash sale rules have not applied to most crypto positions.",
"That has allowed loss harvesting without a 30-day wait: sell at a loss, recognize it, and repurchase immediately.",
"Legislative proposals to extend wash sale treatment to digital assets have been introduced repeatedly. Investors should treat the current treatment as available now rather than permanent, and should not build a strategy that depends on it continuing indefinitely.",
"There is also an economic substance consideration. A transaction executed solely to generate a loss with no change in economic position invites scrutiny even without a specific wash sale rule.",
]),
("Staking, Mining, and Airdrops Create Ordinary Income", [
"Rewards received from staking are includable in gross income at fair market value when the taxpayer gains dominion and control over them. The IRS position, set out in Revenue Ruling 2023-14, is that the income arises upon receipt rather than upon later sale.",
"That value becomes the basis in the received units, so a subsequent sale produces capital gain or loss measured from that point.",
"Mining income is ordinary income at receipt as well, and where mining is conducted as a trade or business it is subject to self-employment tax, with the offsetting benefit that equipment and electricity are deductible business expenses.",
"Airdrops of new tokens are generally income at receipt when the taxpayer has dominion and control, per Revenue Ruling 2019-24.",
"The practical difficulty is valuation at receipt for illiquid tokens received in high volume. Documenting the methodology used, applied consistently, is the defensible approach.",
]),
("Charitable Contributions Are Unusually Efficient", [
"Donating appreciated crypto held more than one year to a qualified charity generally produces a deduction at fair market value with no recognition of the gain, subject to the applicable adjusted gross income limitations.",
"For an investor with a position carrying a very low basis, this is substantially better than selling and donating cash.",
"Contributions of digital assets exceeding $5,000 generally require a qualified appraisal under IRC Sec. 170(f)(11). The IRS has taken the position that an exchange price does not substitute for an appraisal, and taxpayers have lost deductions entirely for omitting it.",
"This is a mechanical requirement with an expensive failure mode, and it should be handled before the donation rather than at filing.",
]),
("Worked Example: Cleaning Up a Portfolio", [
"An investor accumulated positions across four exchanges and three self-custody wallets over six years, with roughly 2,400 transactions including swaps, staking rewards, and transfers between wallets.",
"They had been filing using a universal pooling method with incomplete records, and had never reported staking rewards as income at receipt.",
"The remediation reconstructs basis by wallet as of the transition date, documents a reasonable allocation method, and rebuilds the transaction history from exchange exports and on-chain data.",
"Staking income of $84,000 across three years is identified and reported, which increases income but also establishes basis in those units, reducing gain on their eventual sale by the same amount.",
"Loss harvesting on positions with $310,000 of unrealized loss is executed with immediate repurchase, generating deductible losses that offset gains realized earlier in the year.",
"An appreciated position with $12,000 basis and $190,000 value held four years is donated to a donor advised fund with a qualified appraisal, producing a fair market value deduction and eliminating $178,000 of embedded gain.",
"The cleanup cost several thousand dollars in professional fees and produced a materially better and far more defensible position.",
]),
],
"faqs": [
("Is trading one crypto for another taxable?",
 "Yes. A token-to-token swap is a disposition of the first asset at fair market value. Like-kind exchange treatment under IRC Sec. 1031 has been limited to real property since 2017, and the IRS position was that digital assets never qualified."),
("Do I have to track basis separately for each wallet?",
 "Yes, under the per-wallet accounting approach that replaced universal pooling. A disposition from one wallet can only draw on lots held in that wallet. Investors who did not perform the transitional basis allocation have a gap that gets harder to defend over time."),
("Do wash sale rules apply to crypto?",
 "Currently no, because IRC Sec. 1091 applies to stock and securities and digital assets are treated as property. This permits immediate repurchase after harvesting a loss. Legislative proposals to extend the rule have been introduced repeatedly, so treat the treatment as available now rather than permanent."),
("When is staking income taxable?",
 "At receipt, when you gain dominion and control over the rewards, at their fair market value. That is the IRS position in Rev. Rul. 2023-14. The included value becomes your basis, so a later sale produces gain or loss measured from that point."),
("Do I need an appraisal to donate crypto?",
 "For contributions exceeding $5,000, generally yes, under IRC Sec. 170(f)(11). The IRS has taken the position that an exchange quoted price does not substitute for a qualified appraisal, and taxpayers have lost the entire deduction for omitting it."),
],
"related": [
("/blog/tax-strategy-for-day-traders/", "Tax strategy for day traders"),
("/blog/what-deductions-are-most-commonly-missed-on-tax-returns/", "Commonly missed deductions"),
("/blog/tax-strategies-for-high-income-w2-earners-over-200k/", "Tax strategies for high income W-2 earners"),
],
"cta_head": "Reconstruction Gets More Expensive Every Year",
"cta_body": "If your basis records are incomplete, the cost of fixing them rises with every additional year of transactions. Send us your exchange exports and wallet addresses.",
},

{
"slug": "tax-strategy-for-airline-pilots",
"title": "Tax Strategy for Airline Pilots: Residency, Per Diem, and the 50 Percent State Rule",
"meta_title": "Tax Strategy for Airline Pilots (2026 Guide) | AE Tax Advisors",
"meta_desc": "Federal law limits which states can tax an airline crew member's wages. Residency planning, per diem substantiation, and real estate strategy for 2026.",
"category": C, "date": D,
"intro": [
"Airline pilots have a state tax advantage almost no other profession has, written into federal law. Under 49 U.S.C. Sec. 40116, a state may not tax the compensation of an air carrier employee who performs regularly assigned duties in more than one state unless the state is the employee's residence or the employee earns more than 50% of pay in that state.",
"For a line pilot, that means one state taxes your wages: the state you live in. Which makes where you live the largest single tax decision available to you.",
],
"sections": [
("The Federal Preemption Rule", [
"The statute applies to an employee of an air carrier who performs regularly assigned duties on aircraft in at least two states. It prohibits any state other than the employee's state of residence from taxing that compensation, unless more than 50% of the employee's compensation is earned in that state.",
"For a pilot flying multi-state routes, the 50% threshold is almost never met in any single state other than possibly the domicile state, and even there it usually is not, since flight time is spread across airspace and destinations.",
"The practical result is that a pilot based in Newark but residing in Florida generally owes no New Jersey income tax on flight compensation, and no Florida tax, because Florida has none.",
"This is not a loophole. It is an express federal preemption enacted to prevent airline crew from facing filing obligations in dozens of states.",
]),
("Residency Is the Whole Game", [
"Because only the residence state can tax the wages, moving from a high-tax state to a no-tax state eliminates state income tax on the entire salary.",
"For a wide-body captain earning $420,000, a move from California to Florida, Texas, Nevada, Washington, or Tennessee saves approximately $40,000 to $50,000 annually. Over a twenty-year career remainder, that is real money.",
"The commute is a lifestyle question, and many pilots already commute to base. Establishing residency in a no-tax state while commuting to a base elsewhere is a well-worn path in the industry.",
"Departure states audit these moves. Domicile turns on where you actually live: where your family is, where your possessions are, where you vote, where your professional and social connections sit, and where you spend your days. Cell phone records, credit card activity, and crew scheduling data are all discoverable and all get used.",
"Document the move from the start. Driver's license, voter registration, vehicle registration, primary bank and physician relationships, and a genuine residence. Selling or leasing the former home is the strongest single fact.",
]),
("Per Diem and the Substantiation Rules", [
"Airlines pay per diem for time away from base. Amounts paid under an accountable plan up to the federal meals and incidental expense rates are excluded from wages and reported as such.",
"Where per diem received exceeds the federal rate for the locations and days involved, the excess is taxable wages. Where it falls below, the difference was historically deductible as an unreimbursed employee expense, but that deduction is suspended for individuals under current law, so the shortfall is simply not deductible.",
"Transportation industry employees may use a special standard rate for meals and incidental expenses rather than tracking location-specific rates, and are subject to an 80% limitation rather than 50% under IRC Sec. 274(n)(3) for individuals subject to Department of Transportation hours of service limits.",
"This matters mainly for pilots who fly under Part 135 as independent contractors or who own an aviation business, since employee unreimbursed expenses are not currently deductible.",
]),
("Second Careers and Side Businesses", [
"Many pilots run a business alongside flying: flight instruction, consulting, aircraft management, or an unrelated venture.",
"That business income is not protected by the aviation preemption statute. It is sourced under ordinary rules, which generally means the state where the services are performed or where the business operates.",
"A pilot residing in Florida with a consulting business serving clients in California may have California source income and a California filing obligation on that portion, even though the flight wages remain untaxed by California.",
"Structuring the side business through an entity, with a defensible salary and retirement plan, is where most of the additional planning value sits. A pilot with $80,000 of consulting income can fund a solo 401(k) that flight wages alone would not support beyond the employee deferral in the airline plan.",
]),
("Real Estate Is the Common Strategy", [
"Pilots have high W-2 income, irregular schedules, and often a strong interest in real estate. The obstacle is the passive activity rules under IRC Sec. 469.",
"Real estate professional status is effectively unavailable to a line pilot. The more-than-half test in IRC Sec. 469(c)(7)(B) compares real estate hours against all personal service hours, and a full-time pilot cannot meet it.",
"A non-working or lower-earning spouse can qualify, and that is the standard structure. The spouse must independently meet both tests, and both spouses' hours then count for material participation under IRC Sec. 469(h)(5).",
"Short-term rentals are the alternative. Under Treasury Regulation Sec. 1.469-1T(e)(3)(ii)(A), a property with an average customer use period of seven days or less is not a rental activity, so only material participation applies. A pilot with concentrated days off is actually well positioned to meet the 100-hour test where no other person participates more.",
"Documentation is the constraint. Crew schedules make it easy to demonstrate where you were, which cuts both ways: helpful when your logged hours align with days off, damaging when they do not.",
]),
("Worked Example: Relocation Plus Real Estate", [
"A 44-year-old captain earning $390,000 resides in New York and is based at JFK. New York taxes the full salary as the residence state.",
"They relocate to Florida, sell the New York home, register vehicles and voting in Florida, and continue commuting to JFK. Under 49 U.S.C. Sec. 40116, New York can no longer tax the flight compensation, since New York is no longer the residence state and the 50% threshold is not met.",
"State tax savings are approximately $28,000 annually.",
"They then acquire a $780,000 short-term rental, self-manage it, and document 118 hours of material participation with no other person exceeding that. A cost segregation study reclassifies 27% of depreciable basis.",
"The resulting $196,000 first-year deduction is non-passive because the average stay is under seven days and material participation is established. It offsets flight wages directly, saving roughly $72,000 federally.",
"Combined first-year benefit is approximately $100,000, with the state savings recurring every year thereafter.",
]),
],
"faqs": [
("Which states can tax an airline pilot's wages?",
 "Generally only the state of residence. Under 49 U.S.C. Sec. 40116, a state cannot tax an air carrier employee performing regularly assigned duties in more than one state unless it is the employee's residence or more than 50% of compensation is earned there."),
("Does my base state tax my income?",
 "Generally not, unless it is also your residence state or you earn more than 50% of your compensation there, which is uncommon for multi-state flying. A pilot based in Newark but residing in Florida generally owes no New Jersey tax on flight wages."),
("Is moving to a no-tax state worth it?",
 "For a high-earning pilot, often $28,000 to $50,000 annually. But departure states audit these moves and domicile turns on where you actually live. Document the move thoroughly from the start, and understand that crew scheduling data and phone records are discoverable."),
("Can a pilot qualify as a real estate professional?",
 "Effectively no. IRC Sec. 469(c)(7)(B) requires more than half of all personal service time in real property trades or businesses, which a full-time pilot cannot meet. A spouse can qualify independently, or short-term rentals under the seven-day rule can be used instead."),
("Is per diem taxable?",
 "Amounts paid under an accountable plan up to the applicable federal rate are excluded from wages. Excess above the federal rate is taxable. The shortfall where per diem falls below the federal rate is not currently deductible for employees under present law."),
],
"related": [
("/blog/str-loophole-7-day-rule-explained/", "The short-term rental seven-day rule"),
("/blog/can-my-spouse-qualify-for-real-estate-professional-status/", "Can your spouse qualify for REPS"),
("/blog/tax-strategies-for-high-income-w2-earners-over-200k/", "Tax strategies for high income W-2 earners"),
],
"cta_head": "Residency Is the Largest Lever You Have",
"cta_body": "For crew members, where you live outweighs almost every other planning decision. Bring your current residence, base, and any real estate you own or are considering.",
},

{
"slug": "tax-strategy-for-franchise-owners",
"title": "Tax Strategy for Franchise Owners: Franchise Fees, Multi-Unit Growth, and Build-Out",
"meta_title": "Tax Strategy for Franchise Owners (2026 Guide) | AE Tax Advisors",
"meta_desc": "Franchise fees amortize over 15 years under IRC Sec. 197. How build-out, QIP, entity structure, and multi-unit expansion should be planned for 2026.",
"category": C, "date": D,
"intro": [
"Franchise ownership creates a specific set of tax issues that independent business owners do not face: an upfront fee that cannot be deducted, ongoing royalties that can, and a build-out that is largely deductible in the opening year if handled correctly.",
"For multi-unit operators, the more important point is that each new unit is a fresh deduction event, which lets growth offset the profit from mature locations.",
],
"sections": [
("The Franchise Fee Is Not Deductible", [
"The initial franchise fee is a Sec. 197 intangible. Under IRC Sec. 197(d)(1)(F), a franchise, trademark, or trade name is an amortizable intangible recovered ratably over 15 years beginning with the month of acquisition.",
"A $48,000 initial franchise fee produces $3,200 of annual amortization for 15 years. It is not a current deduction, regardless of how the franchisor characterizes it.",
"The same treatment applies to transfer fees paid to acquire an existing unit and to territory or development fees securing rights to future locations.",
"Ongoing royalties and advertising fund contributions are different. Those are current business expenses deductible when paid or accrued, because they are payments for ongoing services and rights rather than for acquiring an intangible.",
"Renewal fees paid at the end of a franchise term are also generally Sec. 197 intangibles amortized over 15 years from the renewal.",
]),
("The Build-Out Is Where the Deduction Lives", [
"Franchise build-outs reclassify heavily. Depending on concept, 35% to 50% of construction cost is five-year personal property: signage, decorative and accent lighting, specialty flooring, millwork and casework, sound systems, point of sale infrastructure, dedicated power and plumbing serving equipment, and branded finish elements.",
"The structural remainder of an interior build-out in a leased nonresidential space generally qualifies as qualified improvement property under IRC Sec. 168(e)(6), carrying a 15-year recovery period with full bonus eligibility under IRC Sec. 168(k).",
"Equipment purchased separately is five-year property, fully deductible in the placed-in-service year.",
"Between the three categories, a franchise build-out is frequently close to fully deductible in the year the unit opens. For a $620,000 build-out plus $280,000 of equipment, that can mean $850,000 or more of first-year deduction.",
"Site work at a freestanding location adds 15-year land improvements: paving, drive-through lanes, menu boards and their foundations, site lighting, landscaping, and pylon sign bases. Sign cabinets and their electrical service are five-year property.",
]),
("Multi-Unit Growth Funds Its Own Tax Efficiency", [
"An operator opening one unit a year generates $600,000 to $1,000,000 of first-year deduction annually, offsetting the profit produced by units that have matured.",
"This is the structural advantage of a growth franchise portfolio, and it makes the opening schedule a tax planning variable rather than purely an operational one. Placing a unit in service in December versus January shifts an entire year of deduction.",
"The limit is the excess business loss rule under IRC Sec. 461(l), which caps the amount of net business loss an individual can use against non-business income, with the excess converting to a net operating loss carryforward. For an operator whose deductions substantially exceed business income, part of the benefit defers.",
"Operators expanding rapidly should model this rather than assuming each opening produces a full current-year benefit.",
]),
("Entity Structure Across Units", [
"Most multi-unit operators hold each location in a separate LLC for liability isolation, with a common parent or with the operator holding interests directly.",
"S corporation treatment at the operating level is standard once profit is meaningful. Reasonable compensation should reflect the operator's actual role, and for a multi-unit operator with general managers running each location, a lower percentage of profit as salary is generally defensible than for a single-unit owner working in the store.",
"Controlled group and affiliated service group rules under IRC Sec. 414(b), (c), and (m) treat commonly owned entities as one employer for retirement plan testing. Operators who assume separate entities allow separate plans are mistaken, and plan design must account for the aggregate workforce.",
"A management company employing shared administrative staff and charging each unit a documented fee is common and works, provided the fee is supportable under IRC Sec. 482 and the entity has real substance.",
]),
("The FICA Tip Credit for Food Service Concepts", [
"Franchisees in food service should confirm they are claiming the credit under IRC Sec. 45B for employer social security and Medicare taxes paid on employee tips exceeding those treated as wages for minimum wage purposes.",
"For a restaurant with substantial tipped employees, this credit runs into the tens of thousands annually per location and is claimed on Form 8846. It is a credit, not a deduction, so it reduces tax dollar for dollar.",
"It is routinely missed by preparers unfamiliar with the industry, and it can generally be claimed on amended returns within the statute of limitations.",
]),
("Worked Example: Third Unit Opening", [
"An operator with two mature quick service units producing $640,000 of combined profit opens a third location. Build-out is $710,000 in leased space, equipment is $320,000, and the initial franchise fee is $45,000.",
"The study allocates build-out to five-year property of $305,300 (43%), QIP of $355,000 (50%), and non-qualifying structural components of $49,700 (7%). All equipment is five-year property.",
"Under IRC Sec. 168(k), five-year property, QIP, and equipment are bonus eligible, producing approximately $980,300 of first-year deduction.",
"The franchise fee produces $3,000 of amortization in the opening year, not a deduction.",
"Combined with the third unit's own opening losses, taxable income across the enterprise drops well below the $640,000 the mature units generated. The excess business loss limitation under IRC Sec. 461(l) is modeled to determine how much converts to a carryforward.",
"The operator also claims approximately $34,000 of FICA tip credit across the three locations, which had not been claimed in prior years and is recovered on amended returns for open years.",
]),
],
"faqs": [
("Can I deduct my initial franchise fee?",
 "No. A franchise, trademark, or trade name is a Sec. 197 intangible under IRC Sec. 197(d)(1)(F), amortized over 15 years from the month of acquisition. Transfer fees, territory fees, and renewal fees receive the same treatment."),
("Are royalties deductible?",
 "Yes. Ongoing royalties and advertising fund contributions are current business expenses deductible when paid or accrued, because they pay for ongoing services and rights rather than acquiring an intangible asset."),
("How much of a franchise build-out is deductible in year one?",
 "Typically 35% to 50% reclassifies to five-year property, with most of the balance qualifying as 15-year QIP under IRC Sec. 168(e)(6). Combined with separately purchased equipment, a build-out is often close to fully deductible in the opening year."),
("Can each of my units have its own retirement plan?",
 "Generally not as owners expect. Controlled group and affiliated service group rules under IRC Sec. 414(b), (c), and (m) treat commonly owned entities as a single employer for plan testing, regardless of how many separate LLCs exist."),
("What is the FICA tip credit?",
 "A credit under IRC Sec. 45B for employer social security and Medicare taxes paid on tips exceeding those treated as wages for minimum wage purposes, claimed on Form 8846. For food service franchises it often runs into the tens of thousands annually and is frequently missed."),
],
"related": [
("/blog/cost-segregation-restaurants-qip-treatment/", "Cost segregation for restaurants and QIP"),
("/blog/tax-strategy-for-restaurant-group-owners/", "Tax strategy for restaurant group owners"),
("/blog/how-to-structure-multiple-businesses-for-tax-efficiency/", "Structuring multiple businesses"),
],
"cta_head": "Time the Openings Against the Mature Units",
"cta_body": "Placing a unit in service in December versus January shifts a full year of deduction. Bring your opening schedule and current unit economics.",
},

{
"slug": "tax-strategy-for-pharmacy-owners",
"title": "Tax Strategy for Independent Pharmacy Owners: Inventory, DIR Fees, and Thin Margins",
"meta_title": "Tax Strategy for Independent Pharmacy Owners (2026) | AE Tax Advisors",
"meta_desc": "Pharmacies carry heavy inventory on thin margins. Accounting method, inventory treatment, entity structure, and build-out strategy explained for 2026.",
"category": C, "date": D,
"intro": [
"An independent pharmacy runs on gross margins that would not sustain most retail businesses, with a balance sheet dominated by inventory and receivables from third-party payers. That combination creates a specific and often large tax opportunity that most pharmacy owners have never been offered.",
"The opportunity is the accounting method, and it is worth more than every other item on the list combined for many pharmacies.",
],
"sections": [
("The Accounting Method Opportunity", [
"Under IRC Sec. 448(c), a business with average annual gross receipts below the inflation-adjusted threshold, $31 million for 2025, may generally use the cash method of accounting.",
"Most independent pharmacies fall below that threshold comfortably, and many are nonetheless on the accrual method because a prior accountant set it up that way or because inventory was assumed to require accrual.",
"That assumption is outdated. The small business exception also exempts qualifying taxpayers from the uniform capitalization rules of IRC Sec. 263A and permits treating inventory as non-incidental materials and supplies, deductible when consumed, or following the book method.",
"For a pharmacy with $780,000 of inventory and $420,000 of third-party receivables against $360,000 of payables, changing to the cash method produces a Sec. 481(a) adjustment approaching $840,000, deductible in the year of change.",
"The change is made on Form 3115 under the automatic procedures. A favorable adjustment is taken entirely in the year of change.",
]),
("Inventory Treatment After the Change", [
"Once on the cash method with the inventory exception, purchases are generally deducted when the inventory is consumed or sold rather than being capitalized into a formal inventory account.",
"This substantially simplifies the bookkeeping and aligns the deduction more closely with cash outflow, which matters for a business that finances inventory.",
"Pharmacies should be deliberate about the method elected and consistent thereafter. The available approaches produce different timing, and switching between them requires another method change.",
"Physical inventory counts remain necessary for operational and financial reporting purposes even where the tax treatment simplifies.",
]),
("DIR Fees and Timing", [
"Direct and indirect remuneration fees clawed back by pharmacy benefit managers have been a persistent margin problem. Changes moving these adjustments to the point of sale have altered the timing of when the reduction hits revenue.",
"For a pharmacy on the accrual method, retroactive fee assessments create a mismatch between recognized revenue and eventual collection. On the cash method, revenue is recognized when received, net of point-of-sale adjustments, which aligns the tax result with economic reality more closely.",
"This is a secondary benefit of the method change but a real one for pharmacies that experienced large retroactive assessments.",
]),
("Entity Structure and Compensation", [
"S corporation treatment is standard once profit is meaningful. Pharmacy is a health service and therefore a specified service trade or business under IRC Sec. 199A, so the qualified business income deduction phases out above the income threshold.",
"That simplifies the salary analysis, since there is no wage limitation to preserve above the phase-out. The question is purely payroll tax against reasonable compensation risk.",
"Reasonable compensation for a pharmacist-owner should reflect what a comparable staff pharmacist would earn plus a management component. Given prevailing pharmacist salaries, the defensible floor is higher than in many small businesses, which limits how much profit can be taken as distribution.",
"Owners with multiple locations should account for controlled group rules under IRC Sec. 414(b) and (c) in retirement plan design.",
]),
("Build-Out, Automation, and Delivery", [
"Pharmacy build-outs reclassify well, generally 30% to 42% of construction cost. Dispensing counters and casework, robotics and automated dispensing systems, refrigeration for temperature-sensitive products, compounding hoods and clean rooms, security and camera systems, point of sale and pharmacy management hardware, and specialty lighting and finishes are five-year property.",
"Compounding areas are worth particular attention. USP compliant clean rooms with dedicated air handling, HEPA filtration, and pressure control are equipment enclosures rather than building space, and the systems serving them classify with the function.",
"The structural remainder of a leasehold build-out generally qualifies as QIP under IRC Sec. 168(e)(6) with a 15-year life and full bonus eligibility.",
"Delivery vehicles over 6,000 pounds gross vehicle weight rating avoid the luxury auto limits under IRC Sec. 280F and are fully deductible in the placed-in-service year. Smaller delivery vehicles are subject to the caps.",
]),
("Retirement Plans on Thin Margins", [
"Pharmacies carry meaningful staff relative to owner profit, which constrains aggressive plan design. A safe harbor 401(k) with new comparability profit sharing is the practical base, and the staff cost should be modeled rather than assumed.",
"Where the workforce skews younger than the owner, cross-testing performs well. Where technicians are long-tenured and close to the owner's age, the ratio deteriorates and a cash balance plan may not be economic.",
"For an owner with a strong year following a method change, the combination of a large Sec. 481(a) deduction and a substantial plan contribution can be poorly sequenced. Taking both in one year may waste deduction capacity that would have been more valuable spread. This should be modeled across years.",
]),
("Worked Example: Method Change Plus Build-Out", [
"An owner operates two pharmacies with $9,600,000 of combined revenue and $410,000 of profit before owner compensation, structured as an S corporation with a $190,000 salary. Both are on the accrual method.",
"Inventory is $840,000, third-party receivables are $470,000, and payables and accruals are $390,000.",
"Changing to the cash method on Form 3115 produces a Sec. 481(a) deduction of approximately $920,000 in the year of change.",
"A remodel of the older location, including automated dispensing and a compounding clean room, costs $480,000 in construction plus $220,000 of equipment. Reclassification and QIP treatment make nearly all of it deductible in the placed-in-service year.",
"Combined, the deductions far exceed current income, creating a net operating loss carryforward under IRC Sec. 172 limited to 80% of taxable income in future years.",
"Because the excess carries forward rather than being lost, the sequencing question is about how quickly the benefit is realized rather than whether it is realized. Modeling the remodel timing against the method change year would have improved that timing materially.",
]),
],
"faqs": [
("Can a pharmacy use the cash method with inventory?",
 "Generally yes, if average annual gross receipts are under the threshold, $31 million for 2025. The small business exception under IRC Sec. 448(c) also exempts qualifying taxpayers from Sec. 263A and permits treating inventory as non-incidental materials and supplies."),
("How large is the accounting method change deduction?",
 "It reflects inventory plus receivables less payables and accruals at the change date, claimed as a Sec. 481(a) adjustment in the year of change. For a pharmacy with substantial inventory and third-party receivables, this is frequently high six or seven figures."),
("Does a pharmacy qualify for the QBI deduction?",
 "Pharmacy is a health service and therefore a specified service trade or business under IRC Sec. 199A, so the deduction phases out above the income threshold. Below the threshold it is fully available."),
("How is a compounding clean room classified?",
 "As equipment rather than building space. The panel systems, HEPA filtration, dedicated air handling, pressure controls, and hoods serve the compounding function rather than the building, and classify with that function under Treas. Reg. Sec. 1.48-1(e)(2)."),
("Are delivery vehicles fully deductible?",
 "Vehicles with a gross vehicle weight rating over 6,000 pounds are outside the luxury auto limits in IRC Sec. 280F and are fully deductible in the placed-in-service year. Smaller passenger vehicles remain subject to the annual caps."),
],
"related": [
("/blog/3115-change-accounting-method-playbook/", "Form 3115 accounting method change playbook"),
("/blog/cost-segregation-medical-office-buildings/", "Cost segregation for medical office buildings"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
],
"cta_head": "The Method Change Is Usually the Whole Conversation",
"cta_body": "For an inventory-heavy pharmacy, one accounting method change can outweigh every other strategy combined. Send us your balance sheet and trailing revenue.",
},

{
"slug": "tax-strategy-for-optometrists",
"title": "Tax Strategy for Optometrists: The Optical Retail Split and QBI",
"meta_title": "Tax Strategy for Optometrists (2026 Guide) | AE Tax Advisors",
"meta_desc": "Optical retail may not be a specified service business, preserving QBI on part of the income. Entity, build-out, and equipment strategy for ODs in 2026.",
"category": C, "date": D,
"intro": [
"An optometry practice is two businesses sharing a floor plate. One provides professional eye care services. The other sells frames, lenses, and contact lenses at retail.",
"For income tax purposes those two businesses can be treated very differently, and the difference is worth up to 20% of the retail income to an owner above the qualified business income phase-out.",
],
"sections": [
("The Specified Service Question", [
"Health services are a specified service trade or business under IRC Sec. 199A, so above the income phase-out the qualified business income deduction is unavailable on the professional side.",
"Retail sale of goods is not a specified service trade or business. An optical dispensary selling frames, lenses, and contacts is selling products.",
"Treasury Regulation Sec. 1.199A-5(c) governs when activities can be treated separately and when one taints the other. Where a trade or business provides property or services to an SSTB and there is 50% or more common ownership, the portion providing those services is treated as an SSTB. An optical dispensary selling to patients, not to the practice, is not providing services to the SSTB.",
"There are de minimis rules cutting both ways. A business with gross receipts of $25,000,000 or less is not an SSTB if less than 10% of gross receipts are attributable to the performance of services in an excluded field. Above $25,000,000 the threshold is 5%.",
"For a practice where professional fees are 55% and optical is 45%, neither de minimis rule applies, and the question becomes whether the optical operation is a separate trade or business.",
]),
("Separating the Optical Business", [
"Where the optical operation is genuinely separate, with its own books, its own inventory, its own employees, its own economics, and ideally its own entity, the position that it is a non-SSTB trade or business is considerably stronger.",
"Practices that run optical as an undifferentiated department of the professional practice, with combined books and shared staff, have a weaker position.",
"This is not a paper exercise. Building the separation requires real operational changes: separate general ledger, separate payroll for optical staff, arm's length arrangements for shared space and services, and separate financial reporting.",
"For a practice with $600,000 of optical income, the deduction at stake is $120,000 annually. That justifies meaningful operational effort.",
"The arrangement should be documented and implemented prospectively. Reclassifying retroactively at filing is not a position that holds up.",
]),
("Inventory and Accounting Method", [
"Optical dispensaries carry substantial frame and lens inventory. Practices with average annual gross receipts under the IRC Sec. 448(c) threshold may use the cash method, are exempt from Sec. 263A, and may treat inventory as non-incidental materials and supplies.",
"For a practice on the accrual method with $180,000 of frame inventory and $140,000 of insurance receivables, a change to the cash method produces a meaningful Sec. 481(a) deduction in the year of change, filed on Form 3115.",
"This is a smaller opportunity than in a pharmacy, but it is real and it is usually available.",
]),
("Equipment Is Substantial and Recurring", [
"Optical coherence tomography, visual field analyzers, fundus cameras, autorefractors, phoropters, slit lamps, lensometers, edgers and finishing equipment, and practice management hardware are five-year property, fully deductible in the placed-in-service year under IRC Sec. 168(k) or IRC Sec. 179.",
"Diagnostic equipment cycles every five to eight years, which makes this a recurring rather than one-time planning item. A practice adding $150,000 of diagnostic capacity every few years has a deduction stream that should be timed against income.",
"Financing does not reduce the deduction. Equipment placed in service with 10% down is fully deductible that year, which decouples the purchase decision from cash availability.",
]),
("Build-Out and Real Estate", [
"Optometry build-outs reclassify at 32% to 45% of construction cost. Exam lane casework and instrument stands, dedicated power and data serving each lane, dispensary display fixtures and lighting, finishing lab equipment and its dedicated plumbing and dust collection, decorative lighting, and specialty finishes are five-year property.",
"Retail display lighting deserves attention. Optical dispensaries invest heavily in display lighting because frame presentation drives sales, and decorative and accent lighting is five-year property rather than building.",
"The structural remainder of a leasehold build-out generally qualifies as QIP under IRC Sec. 168(e)(6) with a 15-year life and full bonus eligibility.",
"Owners who purchase their building have a second study available, typically reclassifying 20% to 30%, subject to the self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6).",
]),
("Worked Example: Two-Doctor Practice", [
"A 49-year-old owner runs a practice with $2,100,000 of revenue, of which $1,150,000 is professional fees and $950,000 is optical, producing $520,000 of profit before owner compensation. The structure is an S corporation with a $215,000 salary and 11 employees.",
"The optical operation is separated into its own entity with its own books, staff, inventory, and a documented arm's length arrangement for shared space. Optical profit of approximately $210,000 is analyzed as a non-SSTB, preserving a qualified business income deduction of roughly $42,000 that was previously unavailable.",
"A $190,000 diagnostic equipment purchase is placed in service and fully deducted.",
"A safe harbor 401(k) with new comparability profit sharing directs $69,000 to the owner at approximately $23,000 of staff cost.",
"A look-back cost segregation study on the $620,000 build-out completed five years ago, filed with Form 3115, produces a $228,000 catch-up deduction.",
"Combined first-year tax reduction is approximately $200,000, with the QBI position recurring annually.",
]),
],
"faqs": [
("Can an optometry practice claim the QBI deduction?",
 "The professional side is health services and therefore a specified service trade or business under IRC Sec. 199A, phasing out above the income threshold. The optical retail operation sells goods and is not an SSTB, so that portion may retain the deduction if genuinely separate."),
("What does separating the optical business require?",
 "Real operational separation: its own general ledger, its own inventory, its own payroll for optical staff, arm's length arrangements for shared space and services, and ideally its own entity. Reclassifying retroactively at filing is not a defensible position."),
("Does the de minimis rule help me?",
 "Only at the extremes. A business under $25,000,000 of gross receipts is not an SSTB if less than 10% of receipts come from excluded field services. For a practice where professional fees are half the revenue, the de minimis rule does not apply and separation is the path."),
("Can I use the cash method with frame inventory?",
 "Generally yes if average annual gross receipts are under the threshold, $31 million for 2025. The small business exception exempts you from Sec. 263A and permits treating inventory as non-incidental materials and supplies. The change is made on Form 3115."),
("Is diagnostic equipment fully deductible in year one?",
 "Yes, as five-year property under IRC Sec. 168(k) or Sec. 179. Financing does not reduce the deduction, since it follows the placed-in-service date rather than cash paid, so a purchase with 10% down produces the full write-off."),
],
"related": [
("/blog/tax-strategy-for-dentists/", "Tax strategy for dentists"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
("/blog/cost-segregation-medical-office-buildings/", "Cost segregation for medical office buildings"),
],
"cta_head": "The Optical Split Is Worth Six Figures Over Time",
"cta_body": "Building the separation takes real operational work and needs to be done prospectively. Bring your revenue mix, staffing, and entity structure.",
},

{
"slug": "tax-strategy-for-engineering-and-architecture-firms",
"title": "Tax Strategy for Engineering and Architecture Firms: QBI, Section 174, and the R&D Credit",
"meta_title": "Tax Strategy for Engineering and Architecture Firms (2026) | AE Tax Advisors",
"meta_desc": "Engineering and architecture are excluded from the SSTB list, preserving QBI at high income. Section 174 treatment and the R&D credit explained for 2026.",
"category": C, "date": D,
"intro": [
"Engineering and architecture firms hold a specific advantage in the qualified business income rules that most professional service firms do not. Both fields were carved out of the specified service trade or business definition, which means the 20% deduction remains available at any income level.",
"That single fact is worth six figures annually to a mid-sized firm, and it changes how salary and entity decisions should be made.",
],
"sections": [
("Engineering and Architecture Are Not SSTBs", [
"IRC Sec. 199A(d)(2)(A) defines a specified service trade or business by reference to IRC Sec. 1202(e)(3)(A), but expressly excludes engineering and architecture from that reference.",
"The result is that an engineering or architecture firm may claim the full qualified business income deduction even at high income, subject only to the W-2 wage and qualified property limitations rather than the SSTB phase-out.",
"On $1,400,000 of qualified business income, that is a $280,000 deduction that a law firm or medical practice at the same income cannot claim.",
"Note the asymmetry with Sec. 1202. Engineering and architecture remain excluded businesses for qualified small business stock purposes under IRC Sec. 1202(e)(3), so a firm organized as a C corporation cannot use the QSBS exclusion on an exit. The two provisions borrow the same list but reach opposite conclusions for these fields.",
]),
("Salary Optimization Runs the Other Direction", [
"Because the deduction is available, the W-2 wage limitation becomes the binding constraint above the income threshold. The deduction is limited to the greater of 50% of W-2 wages or 25% of wages plus 2.5% of unadjusted basis in qualified property.",
"That creates a genuine tension with S corporation salary minimization. Lowering owner salary to save payroll tax reduces the wage base and can cost more in lost QBI deduction than it saves.",
"For a firm with substantial non-owner payroll, the limitation is rarely binding. For a small firm where the owner is most of the payroll, it frequently is, and the optimal salary is higher than payroll tax minimization alone would suggest.",
"The calculation moves annually with income and payroll and should be run each year rather than set once.",
]),
("Section 174 Changed and Then Changed Back", [
"The 2017 law required specified research or experimental expenditures under IRC Sec. 174 to be capitalized and amortized over five years for domestic activity, rather than deducted currently, beginning in 2022.",
"For firms with substantial engineering development activity, that created a cash tax problem disconnected from economics: expenses paid in full but deducted over five years.",
"Legislation enacted in 2025 restored current deductibility for domestic research expenditures, with transition rules addressing amounts previously capitalized. Foreign research remains subject to a longer amortization period.",
"Firms that capitalized amounts in 2022 through 2024 should confirm how the transition applies to their unamortized balances, since the mechanism for recovering them affects which year the deduction lands in. This is worth reviewing rather than assuming the prior treatment simply continues.",
]),
("The Research Credit Is Frequently Available", [
"The credit for increasing research activities under IRC Sec. 41 applies to qualified research undertaken to discover information technological in nature, intended to develop or improve a business component, where substantially all activities constitute a process of experimentation.",
"Engineering firms frequently qualify on projects involving new structural systems, novel mechanical or electrical designs, energy modeling, geotechnical problem solving, or environmental remediation approaches.",
"The funded research exclusion is the main obstacle. Research funded by a client through a contract is excluded where the taxpayer does not retain substantial rights and does not bear economic risk of failure. Fixed-price contracts where the firm bears the risk of overruns generally support the credit. Cost-plus contracts generally do not.",
"Contract terms therefore drive credit eligibility, and firms doing genuine development work should review their standard agreements with this in mind.",
"Documentation requires project-level tracking of qualified wages, supplies, and contract research, tied to specific business components and a documented process of experimentation. Firms that reconstruct this years later capture far less than firms that track contemporaneously.",
]),
("Retirement Plans and Firm Demographics", [
"Engineering and architecture firms typically have a small number of high-earning principals and a larger technical staff that skews younger. That is favorable demographics for cross-tested plan design.",
"A safe harbor 401(k) with new comparability profit sharing directs a large share of employer contributions to the principal group. A cash balance plan layered on top can add $140,000 to $250,000 of annual deductible contribution for a principal over 45.",
"The interaction with the QBI wage limitation is worth noting. Employer retirement contributions are not W-2 wages, so they reduce qualified business income without increasing the wage base. Where the wage limitation is binding, this can reduce the QBI deduction as it increases the retirement deduction. The two should be optimized together rather than separately.",
]),
("Worked Example: 34-Person Engineering Firm", [
"A firm has $6,800,000 of revenue and $1,320,000 of profit before principal compensation, with three principals and 31 staff, structured as an S corporation.",
"Combined principal salaries are set at $780,000, modeled against the QBI wage limitation. Total W-2 wages including staff are $3,900,000, so the 50% wage limitation of $1,950,000 far exceeds the potential deduction and is not binding.",
"Qualified business income of approximately $540,000 supports a deduction of $108,000, fully available because engineering is not an SSTB.",
"A research credit study covering fixed-price projects with genuine development content identifies $1,240,000 of qualified research expenses, producing a credit of approximately $86,000.",
"A safe harbor 401(k) with new comparability directs $210,000 across the three principals at approximately $74,000 of staff cost, and a cash balance plan adds $420,000 across the principals at $61,000 of additional staff cost.",
"Combined annual tax reduction exceeds $340,000, and the QBI position and research credit both recur.",
]),
],
"faqs": [
("Do engineering and architecture firms qualify for the QBI deduction?",
 "Yes. IRC Sec. 199A(d)(2)(A) expressly excludes engineering and architecture from the specified service trade or business definition, so the deduction is available at any income level, subject to the W-2 wage and qualified property limitations."),
("Should I lower my salary to save payroll tax?",
 "Not automatically. Above the income threshold, the QBI deduction is limited by W-2 wages, so cutting salary can cost more in lost deduction than it saves in payroll tax. For a small firm where the owner is most of the payroll, the optimal salary is often higher than expected."),
("Do I still have to capitalize research expenses under Section 174?",
 "Legislation enacted in 2025 restored current deductibility for domestic research expenditures, with transition rules for amounts previously capitalized in 2022 through 2024. Foreign research remains subject to longer amortization. Confirm how the transition applies to your unamortized balance."),
("Can an engineering firm claim the R&D credit?",
 "Frequently yes, on projects involving genuine technical uncertainty and a process of experimentation. The main obstacle is the funded research exclusion. Fixed-price contracts where you bear overrun risk generally support the credit. Cost-plus contracts generally do not."),
("Does QSBS apply to an engineering firm?",
 "No. Engineering and architecture remain excluded businesses under IRC Sec. 1202(e)(3), so a C corporation engineering firm cannot use the qualified small business stock exclusion. The two provisions borrow the same list but reach opposite conclusions for these fields."),
],
"related": [
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
("/blog/qualified-small-business-stock-section-1202/", "Qualified small business stock explained"),
("/blog/cash-balance-plans-business-owners-2026/", "Cash balance plans for business owners"),
],
"cta_head": "Two Provisions, Opposite Answers",
"cta_body": "Engineering firms win on QBI and lose on QSBS, which drives entity choice. Bring your ownership structure, payroll, and project mix.",
},

{
"slug": "tax-strategy-for-salon-and-spa-owners",
"title": "Tax Strategy for Salon and Spa Owners: Booth Rental, Tip Credits, and Build-Out",
"meta_title": "Tax Strategy for Salon and Spa Owners (2026 Guide) | AE Tax Advisors",
"meta_desc": "Booth rental versus employee classification drives everything for salons. FICA tip credit, retail product income, and build-out deductions explained for 2026.",
"category": C, "date": D,
"intro": [
"Salon and spa economics turn on one structural decision: whether stylists are employees, independent contractors, or booth renters. That choice determines payroll tax exposure, benefit obligations, worker classification risk, and whether a valuable tax credit is available.",
"Most owners make the decision for operational reasons and never revisit the tax consequences, which run in both directions.",
],
"sections": [
("The Three Models and What Each Costs", [
"In an employee model, the salon employs stylists, withholds and pays payroll tax, controls scheduling and pricing, and collects all service revenue. Payroll tax cost is real, but the salon controls the client relationship and the brand.",
"In a booth rental model, the stylist is an independent business renting space. The salon collects rent, has no payroll tax exposure for that stylist, and reports rental income. The stylist sets their own prices, keeps their own revenue, and files their own return.",
"In a contractor model without booth rental, the salon pays stylists as independent contractors while controlling scheduling, pricing, and the client relationship. This is the highest risk position and the one most likely to fail a worker classification review.",
"Classification turns on behavioral control, financial control, and the nature of the relationship. Setting prices, mandating schedules, providing all supplies, and requiring the worker to follow salon procedures all point toward employee status regardless of what the agreement says.",
"Section 530 of the Revenue Act of 1978 provides relief where the business had a reasonable basis for contractor treatment, treated all similar workers consistently, and filed all required Forms 1099. The consistency requirement is where salons commonly fail, because they typically have some stylists as employees and some as contractors doing identical work.",
]),
("The FICA Tip Credit Requires Employees", [
"The credit under IRC Sec. 45B allows an employer to claim a credit for social security and Medicare taxes paid on employee tips exceeding those treated as wages for minimum wage purposes.",
"For a salon with employed stylists receiving substantial tips, this credit runs into the tens of thousands annually. It is a credit rather than a deduction, so it reduces tax dollar for dollar.",
"Critically, it applies only to employees. A salon that converted to booth rental to avoid payroll tax also gave up the credit, and for a high-tip business the credit can offset a meaningful share of the payroll tax it was avoiding.",
"The credit is claimed on Form 8846 and is routinely missed by preparers unfamiliar with the industry. It can generally be claimed on amended returns for open years.",
"The comparison worth running is total payroll tax cost net of the tip credit against booth rental economics, rather than payroll tax cost alone.",
]),
("Retail Product Income Is a Separate Business", [
"Salons and spas sell $80,000 to $400,000 of product annually, and this is inventory-based retail with different characteristics from service revenue.",
"Personal care services are health-adjacent but generally not health services for IRC Sec. 199A purposes. Most salon and spa services are not specified service trades or businesses, which means the qualified business income deduction remains available even at higher income, subject to the wage limitation.",
"Med spa services performed under medical supervision are a different analysis and can be health services. A business offering both should segregate the revenue.",
"Product sales are unambiguously retail. Separating product revenue and cost of goods sold clarifies profitability, supports the tax position, and makes the business easier to value at sale.",
]),
("Build-Out Reclassifies Heavily", [
"Salon and spa build-outs are among the better reclassification candidates in retail service, generally 35% to 50% of construction cost.",
"Styling stations and their dedicated plumbing and electrical, shampoo bowls and their plumbing, treatment room fixtures, wet room and hydrotherapy equipment, sauna and steam equipment, dedicated ventilation for chemical services, decorative and accent lighting, millwork and reception casework, sound systems, and specialty finishes are all five-year property.",
"Dedicated exhaust and makeup air serving color and chemical service areas is worth specific attention. It exists to handle the chemical process rather than to condition the building, and classifies with that function under Treasury Regulation Sec. 1.48-1(e)(2).",
"The structural remainder of a leasehold build-out generally qualifies as QIP under IRC Sec. 168(e)(6) with a 15-year life and full bonus eligibility.",
"Between the categories, a $420,000 salon build-out is frequently close to fully deductible in the opening year.",
]),
("Entity Structure and Multi-Location Growth", [
"S corporation treatment is standard once profit is meaningful. Reasonable compensation should reflect the owner's actual role, which for many salon owners includes both service production behind the chair and management.",
"Owners who stopped taking clients and now manage full time have a different compensation profile than working owners, and the analysis should reflect the change rather than carrying forward a stale number.",
"Multi-location operators should account for controlled group rules under IRC Sec. 414(b) and (c) in retirement plan design, and should consider whether a management company employing shared administrative staff is warranted.",
]),
("Worked Example: Employee Model Salon", [
"An owner operates a salon with $1,850,000 of revenue, including $290,000 of retail product, and 22 employed stylists and support staff. Profit before owner compensation is $340,000.",
"Employee tips reported total approximately $410,000. Employer social security and Medicare tax on tips exceeding the minimum wage threshold supports a FICA tip credit of roughly $29,000 annually, which had never been claimed. It is claimed currently and recovered on amended returns for three open years, producing approximately $116,000 of total benefit.",
"Salon services are analyzed as a non-SSTB, preserving a qualified business income deduction of approximately $48,000 subject to the wage limitation, which is not binding given the payroll base.",
"A look-back cost segregation study on the $510,000 build-out completed four years ago, filed with Form 3115, produces a $198,000 catch-up deduction.",
"Combined first-year benefit exceeds $190,000, with the tip credit and QBI deduction recurring annually.",
]),
],
"faqs": [
("Should my stylists be employees, contractors, or booth renters?",
 "It depends on how much control you exercise. Setting prices, mandating schedules, and providing supplies point toward employee status regardless of the agreement. The riskiest position is paying contractors while controlling the client relationship and pricing."),
("What is the FICA tip credit and do I qualify?",
 "A credit under IRC Sec. 45B for employer social security and Medicare taxes paid on employee tips above the minimum wage threshold, claimed on Form 8846. It applies only to employees, not to booth renters or contractors, and is frequently missed by preparers."),
("Does a salon qualify for the QBI deduction?",
 "Generally yes. Most salon and spa services are not specified service trades or businesses under IRC Sec. 199A, so the deduction remains available subject to the wage limitation. Med spa services performed under medical supervision are a different analysis and can be health services."),
("How much of a salon build-out is deductible in year one?",
 "Typically 35% to 50% reclassifies to five-year property, including styling stations and their utilities, shampoo plumbing, treatment room fixtures, and chemical service ventilation, with most of the balance qualifying as 15-year QIP."),
("Does booth rental save me money overall?",
 "Not always. It eliminates payroll tax on those stylists but also gives up the FICA tip credit, which for a high-tip business can offset a meaningful share of that cost. The comparison should be run net of the credit rather than on payroll tax alone."),
],
"related": [
("/blog/tax-strategy-for-med-spa-owners/", "Tax strategy for med spa owners"),
("/blog/cost-segregation-fitness-centers-gyms/", "Cost segregation for gyms and fitness centers"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
],
"cta_head": "Run the Comparison Net of the Credit",
"cta_body": "Most salons choose booth rental without pricing the tip credit they are giving up. Bring your headcount, tip reporting, and revenue mix.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
