"""Batch: real estate investor strategy guides (long-tail gaps)."""

from blog_gen import write_all

C = "Real Estate Tax"
D = "2026-08-10"

ARTICLES = [
{
"slug": "brrrr-method-tax-strategy",
"title": "BRRRR Method Tax Strategy: What the Refinance Actually Does to Your Return",
"meta_title": "BRRRR Method Tax Strategy (2026 Guide) | AE Tax Advisors",
"meta_desc": "The refinance in a BRRRR is not taxable, but it changes basis, interest tracing, and at-risk limits. Full tax mechanics of the BRRRR method for 2026.",
"category": C, "date": D,
"intro": [
"The BRRRR method, buy, rehab, rent, refinance, repeat, is a financing strategy, not a tax strategy. But it produces four distinct tax events, and investors who do not understand them tend to be surprised at exactly the wrong moment.",
"The good news dominates. Cash pulled out in the refinance is not taxable income. The complications are in basis, in how the new interest is deducted, and in whether the losses you generate are actually usable.",
],
"sections": [
("The Rehab Is Not All Deductible", [
"This is the first place BRRRR investors get it wrong. Money spent to put a property in service is capitalized into basis, not deducted as a repair.",
"Under Treasury Regulation Sec. 1.263(a)-3, amounts paid for betterments, restorations, or adaptations to a new use must be capitalized. A gut rehab of a distressed property is the textbook restoration. So is replacing a roof, rewiring, or replacing HVAC.",
"Work performed before the property is placed in service is capitalized regardless of whether it would have been a repair on an operating rental. There is no repair deduction on a property that is not yet in service, because there is no activity to deduct against.",
"The safe harbors help at the margins. The de minimis safe harbor election under Treasury Regulation Sec. 1.263(a)-1(f) allows expensing items under $2,500 per invoice or item for taxpayers without an applicable financial statement. The routine maintenance safe harbor applies to recurring work on property already in service. Neither one rescues a $70,000 rehab.",
"The upside is that the capitalized rehab increases depreciable basis, which is exactly what makes the cost segregation study on a BRRRR property so productive.",
]),
("The Refinance Is Not Taxable, But It Is Not Free", [
"Loan proceeds are not income. Pulling $180,000 out of a stabilized property through a cash-out refinance produces no taxable event, which is the central appeal of the strategy.",
"What it does not do is increase basis. Your depreciable basis is what you paid plus what you capitalized, not what the property is now worth or what you owe against it. An investor with $40,000 of remaining basis and a $240,000 loan has negative equity for tax purposes and a large gain waiting at sale.",
"This compounds across a BRRRR portfolio. Ten properties refinanced repeatedly can produce a portfolio where debt substantially exceeds basis. That is manageable while you hold, but a sale, a foreclosure, or a deed in lieu will produce gain far exceeding the cash received.",
]),
("Interest Tracing Determines Deductibility", [
"Here is the rule most BRRRR investors have never heard. Under Treasury Regulation Sec. 1.163-8T, interest is allocated based on how the loan proceeds are used, not on what secures the loan.",
"Cash-out proceeds reinvested into the next rental property are traced to that property, and the interest is deductible against rental income. Cash-out proceeds used to pay down personal credit cards or buy a car are personal interest and generally not deductible at all, even though the loan is secured by a rental.",
"This means the cash from a refinance should be tracked deliberately. Depositing $180,000 of refinance proceeds into an account that already contains personal funds and then spending from it creates a tracing problem the regulations resolve through ordering rules that rarely favor the taxpayer.",
"The practical answer is a separate account. Refinance proceeds in, next acquisition out, with nothing else touching it. This costs nothing and preserves the deduction cleanly.",
]),
("At-Risk and Basis Limits on the Losses", [
"BRRRR properties generate large losses, particularly with a cost segregation study on a rehabbed property. Three separate limitations apply in order.",
"First, basis. In a partnership or S corporation, you cannot deduct a loss exceeding your basis in the entity. Qualified nonrecourse financing generally increases partnership basis but S corporation shareholders do not get basis for entity-level debt they have not personally guaranteed. This is a common and expensive surprise for investors who put rentals in an S corporation.",
"Second, at-risk under IRC Sec. 465. You are at risk for cash contributed and for debt you are personally liable on. Qualified nonrecourse financing secured by real property is generally treated as at-risk, which is why most conventional rental debt does not create a problem.",
"Third, passive activity under IRC Sec. 469. This is the wall. Unless you qualify as a real estate professional or the property is a short-term rental with an average stay of seven days or less, the loss is passive and suspends against wages.",
"Investors run cost segregation studies on BRRRR properties all the time without checking these three limits first, and then discover the deduction they paid for is sitting suspended.",
]),
("Worked Example: A Single BRRRR Cycle", [
"An investor buys a distressed duplex for $195,000, spends $84,000 on a full rehab, and places it in service. Basis is $279,000, of which $42,000 is allocated to land, leaving $237,000 depreciable.",
"A cost segregation study reclassifies 26%, producing $61,620 of five-year and 15-year property fully deductible under IRC Sec. 168(k), plus $8,618 of structural depreciation in the first partial year. Total first-year depreciation is roughly $70,238.",
"The property appraises at $355,000 and refinances at 75% loan to value, producing a $266,250 loan. After paying off the $210,000 acquisition and rehab financing, the investor pulls out $56,250 tax free.",
"The investor moves that $56,250 into a segregated account and uses it as the down payment on the next property. The interest on the portion traced to that acquisition is deductible against the new property.",
"If the investor qualifies as a real estate professional or the duplex is operated as a short-term rental, the $70,238 loss offsets other income. If not, it suspends and carries forward.",
]),
("The Exit Nobody Models", [
"After four BRRRR cycles on the same property with cumulative refinancing, an investor may have $180,000 of remaining basis, $520,000 of debt, and a $610,000 property. The taxable gain on sale is roughly $430,000, of which the depreciation recapture component is taxed at up to 25% for unrecaptured Sec. 1250 gain and at ordinary rates for the Sec. 1245 property from the cost segregation study.",
"The cash at closing after paying off $520,000 of debt is roughly $70,000. The tax bill exceeds it.",
"This is not an argument against BRRRR. It is an argument for planning the exit through a 1031 exchange under IRC Sec. 1031, which defers the entire gain, or through an installment structure. Investors who build a portfolio on refinancing and then sell without an exchange discover the arithmetic at the closing table.",
]),
],
"faqs": [
("Is the cash from a BRRRR refinance taxable?",
 "No. Loan proceeds are not income regardless of how much equity you extract. But the refinance does not increase your depreciable basis either, so repeated refinancing creates a growing gap between debt and basis that shows up as taxable gain at sale."),
("Can I deduct my BRRRR rehab costs?",
 "Generally no, not currently. Work performed to put a property in service is capitalized into basis under Treas. Reg. Sec. 1.263(a)-3, not deducted as a repair. The upside is that it increases depreciable basis, which is what makes a cost segregation study on a rehabbed property so productive."),
("Is the interest on a cash-out refinance deductible?",
 "It depends on how you use the proceeds, not on what secures the loan. Under Treas. Reg. Sec. 1.163-8T, interest is traced to the use of funds. Proceeds reinvested in another rental produce deductible interest. Proceeds used personally generally do not, even though a rental secures the loan."),
("Why is my BRRRR loss not offsetting my W2 income?",
 "Most likely the passive activity rules in IRC Sec. 469. Unless you qualify as a real estate professional or the property has an average stay of seven days or less, rental losses are passive and suspend. Basis and at-risk limits under IRC Sec. 465 can also apply first."),
("What happens tax-wise when I finally sell a heavily refinanced BRRRR?",
 "Gain is measured against basis, not against debt. After multiple refinances your basis may be far below your loan balance, producing taxable gain that exceeds the cash you receive at closing. A 1031 exchange under IRC Sec. 1031 defers this entirely and is the standard answer."),
],
"related": [
("/blog/what-repairs-vs-improvements-can-i-deduct-on-rental-property/", "Repairs versus improvements on rental property"),
("/blog/how-does-1031-exchange-work-for-rental-properties/", "How a 1031 exchange works"),
("/blog/passive-activity-loss-rules-for-real-estate-investors/", "Passive activity loss rules"),
],
"cta_head": "Model the Exit Before the Fourth Refinance",
"cta_body": "BRRRR works until the basis runs out. Send us your portfolio schedule with basis, debt, and current values and we will show you where the gap is heading.",
},

{
"slug": "house-hacking-tax-rules",
"title": "House Hacking Tax Rules: Allocating Between Personal Residence and Rental",
"meta_title": "House Hacking Tax Rules (2026 Guide) | AE Tax Advisors",
"meta_desc": "House hacking splits one property into personal and rental use. Allocation methods, depreciation, Sec. 121 exclusion, and cost segregation rules for 2026.",
"category": C, "date": D,
"intro": [
"House hacking, living in one unit of a small multifamily while renting the others, or renting rooms in a single family home, creates a property that is partly a residence and partly a rental. The tax code handles this by splitting it.",
"The split determines your depreciation, your deductions, your capital gain exclusion at sale, and whether a cost segregation study is worth running. Most house hackers do the allocation casually and lose real money on both ends.",
],
"sections": [
("How the Allocation Works", [
"You must allocate the property between personal use and rental use on a reasonable basis. For a duplex where you occupy one unit and rent the other, square footage is the standard method and is generally the cleanest.",
"For a single family home with rented bedrooms, the allocation is more nuanced. The rented bedrooms are clearly rental. Shared common areas, the kitchen, living room, and hallways, are commonly allocated between personal and rental use based on the ratio of exclusive space or on occupancy. Both approaches have support. What matters is choosing a defensible method and applying it consistently year over year.",
"The allocation percentage drives everything downstream. Depreciation applies only to the rental portion of the building. Mortgage interest and property taxes split, with the rental share deducted on Schedule E and the personal share deducted on Schedule A subject to the SALT cap and mortgage interest limitations. Utilities, insurance, and repairs affecting the whole property split by the same percentage. Repairs affecting only the rental portion are fully deductible against rental income.",
]),
("Depreciation on the Rental Portion", [
"The rental portion of the building is depreciated over 27.5 years as residential rental property under IRC Sec. 168(e)(2)(A). Land is not depreciable, so the purchase price must first be split between land and building, then the building split between personal and rental use.",
"On a $520,000 duplex with $95,000 of land value, the depreciable building is $425,000. At a 50% rental allocation, depreciable basis for the rental is $212,500, producing $7,727 of annual depreciation.",
"Furniture and appliances placed in the rental unit are separately depreciable as five-year property, fully deductible in the placed-in-service year under IRC Sec. 168(k). For a furnished unit, this is a meaningful first-year item that house hackers routinely miss.",
]),
("Cost Segregation on the Rental Share", [
"A cost segregation study applies to the rental portion. On a duplex with 50% rental allocation and $212,500 of rental depreciable basis, a study reclassifying 24% produces roughly $51,000 of first-year deduction.",
"Whether that is worth the study cost depends on the property value and on whether the loss is usable. For a $500,000 duplex, the arithmetic is marginal. For a fourplex where the investor occupies one unit and rents three, with $700,000 of rental basis, it is clearly worth running.",
"The usability question is the same as for any rental. Under IRC Sec. 469 the loss is passive unless you qualify as a real estate professional. The $25,000 special allowance under IRC Sec. 469(i) is available to active participants with modified adjusted gross income under $100,000, phasing out completely at $150,000. Many house hackers are early in their careers and actually fall within this range, which makes the allowance more relevant here than in most rental contexts.",
]),
("The Section 121 Exclusion at Sale", [
"This is where house hacking gets genuinely favorable. Under IRC Sec. 121, you may exclude up to $250,000 of gain, $500,000 for married filing jointly, on the sale of a principal residence owned and used as such for two of the preceding five years.",
"For a house hack, the exclusion applies to the personal use portion. The rental portion's gain is not excluded, and depreciation claimed after May 6, 1997, is recaptured as unrecaptured Sec. 1250 gain at up to 25% regardless of the exclusion.",
"There is an important distinction between separate dwelling units and rented space within one dwelling unit. Where the rental is a separate unit in a duplex, the allocation applies and only the residence portion qualifies. Where you rented bedrooms within the same dwelling unit you occupied, the regulations under Treasury Regulation Sec. 1.121-1(e) generally do not require allocation for the non-residence use within the dwelling unit, though depreciation recapture still applies. This distinction is worth understanding before choosing a house hacking structure.",
]),
("Worked Example: Fourplex House Hack", [
"An investor buys a fourplex for $760,000, occupies one unit, and rents three. Land is allocated at $140,000, leaving $620,000 of building. The rental allocation by square footage is 74%, giving $458,800 of rental depreciable basis.",
"A cost segregation study reclassifies 25% of the rental basis, producing $114,700 of five-year and 15-year property deductible in year one under IRC Sec. 168(k), plus roughly $12,500 of structural depreciation. First-year depreciation on the rental portion is approximately $127,200.",
"The investor's modified adjusted gross income is $128,000, so the $25,000 special allowance under IRC Sec. 469(i) is partially phased out, allowing $11,000 of the loss currently. The balance suspends and carries forward.",
"Three years later the investor moves out, converts the fourth unit to a rental, and the property becomes fully rental. The suspended losses remain available and release against future passive income or on a fully taxable sale.",
]),
("Converting Fully to a Rental Later", [
"Most house hackers eventually move out. On conversion, the former personal use portion becomes rental property, and depreciation begins on it.",
"The basis for depreciation on the converted portion is the lesser of adjusted basis or fair market value at the date of conversion, under Treasury Regulation Sec. 1.168(i)-4. In an appreciating market this generally means your original cost basis, which is lower than value, so appreciation does not increase your depreciation.",
"Timing matters for the Sec. 121 exclusion. You must have used the property as a principal residence for two of the five years before sale. An investor who moves out and rents for more than three years loses the exclusion on the residence portion entirely. For a house hacker with substantial appreciation in the personal use share, selling within that window, or executing a 1031 exchange on the rental portion while excluding the residence portion, can be worth six figures.",
]),
],
"faqs": [
("How do I split expenses between personal and rental use?",
 "On any reasonable basis, applied consistently. Square footage is standard for separate units in a duplex or fourplex. For rented rooms in a single family home, allocation based on exclusive space or occupancy both have support. Choose a method, document it, and apply it the same way every year."),
("Can I depreciate a house hack?",
 "Yes, on the rental portion only. Split the purchase price between land and building, then apply your rental use percentage to the building. Furniture and appliances placed in the rental space are separately depreciable as five-year property and fully deductible in year one."),
("Is a cost segregation study worth it on a house hack?",
 "It depends on the rental basis. On a duplex with roughly $200,000 of rental basis, the arithmetic is marginal. On a fourplex with $450,000 or more of rental basis, it usually is worth running, provided you can actually use the resulting loss."),
("Do I lose my capital gains exclusion by renting part of my home?",
 "Partly. The IRC Sec. 121 exclusion applies to the residence portion. Gain on a separate rental unit is not excluded, and depreciation claimed after May 6, 1997, is recaptured at up to 25% regardless. Renting rooms within your own dwelling unit is treated more favorably than renting a separate unit."),
("Can I use house hacking losses against my W2 income?",
 "Possibly, through the $25,000 special allowance under IRC Sec. 469(i) for active participants. It phases out between $100,000 and $150,000 of modified adjusted gross income. Many house hackers are early enough in their careers to fall within the range, which is unusual among rental owners."),
],
"related": [
("/blog/convert-primary-residence-to-rental-property/", "Converting a primary residence to a rental"),
("/blog/what-is-the-25000-rental-loss-allowance/", "The $25,000 rental loss allowance"),
("/blog/cost-segregation-small-multifamily-5-20-units/", "Cost segregation for small multifamily"),
],
"cta_head": "The Allocation Decision Compounds for Years",
"cta_body": "Get the split right at the start and it works for the whole hold period. Send us your closing statement, square footage, and occupancy plan.",
},

{
"slug": "seller-financing-tax-treatment-installment-sales",
"title": "Seller Financing and Installment Sales: How the Tax Actually Works",
"meta_title": "Seller Financing Tax Treatment and Installment Sales (2026) | AE Tax Advisors",
"meta_desc": "Seller financing spreads gain under IRC Sec. 453, but recapture is taxed upfront. Interest imputation, elections, and planning traps explained for 2026.",
"category": C, "date": D,
"intro": [
"Seller financing solves a cash flow problem for the buyer and a tax problem for the seller. Under IRC Sec. 453, gain is recognized as payments are received rather than all at once, which can keep a seller out of the top bracket and away from the net investment income tax.",
"There are three traps that catch sellers who assume the deferral is complete. Depreciation recapture is not deferred. Interest must be adequate or the IRS will impute it. And the note itself has consequences if the seller later disposes of it or dies.",
],
"sections": [
("The Installment Method Mechanics", [
"Under IRC Sec. 453, each principal payment received carries out gain in the same proportion that total gain bears to the total contract price. That ratio is the gross profit percentage.",
"On a property sold for $1,400,000 with an adjusted basis of $600,000, gross profit is $800,000 and the gross profit percentage is roughly 57.1%. A $200,000 down payment carries out $114,200 of gain. Each subsequent principal payment does the same until the note is retired.",
"Interest received is separately taxable as ordinary interest income in the year received. It is not part of the installment gain computation.",
"The installment method applies automatically to a qualifying sale. You must affirmatively elect out under IRC Sec. 453(d) if you want to recognize all gain in the year of sale, which is occasionally the right answer when the seller has expiring losses or an unusually low-income year.",
]),
("Depreciation Recapture Is Not Deferred", [
"This is the trap that surprises sellers most. Under IRC Sec. 453(i), depreciation recapture under IRC Sec. 1245 and IRC Sec. 1250 is recognized in full in the year of sale, regardless of how little cash was received.",
"For a seller who ran a cost segregation study and has substantial Sec. 1245 property, this can be a significant amount of ordinary income due immediately with almost no cash to pay it. A property sold with a $50,000 down payment and $340,000 of Sec. 1245 recapture creates a tax bill exceeding the cash received.",
"The planning answer is to size the down payment against the recapture liability rather than against a rule of thumb. A seller with heavy recapture needs more cash at closing, and that is a negotiating point that should be raised early.",
"Unrecaptured Sec. 1250 gain, the straight-line depreciation on the building taxed at up to 25%, does spread under the installment method. It is treated as recognized first as payments come in, before the lower-rate capital gain, which is a detail that affects year-by-year projections.",
]),
("Interest Must Be Adequate", [
"If the note does not charge adequate stated interest, the IRS will impute it under IRC Sec. 483 or the original issue discount rules of IRC Sec. 1274, depending on the transaction. The effect is to recharacterize part of what the parties called principal as interest.",
"This matters because it converts capital gain into ordinary interest income for the seller. A seller who agreed to a 2% note on a $1,200,000 sale to help the buyer will find a meaningful portion of the principal recharacterized.",
"The threshold is the applicable federal rate published monthly by the IRS. Charging at or above the relevant AFR avoids imputation entirely. There is no reason to go below it, since a below-market rate helps the buyer's cash flow but costs the seller in rate arbitrage that the code neutralizes anyway.",
]),
("What Happens If the Seller Disposes of the Note", [
"Selling, gifting, or pledging the installment note accelerates the remaining gain. Under IRC Sec. 453B, disposition of an installment obligation triggers recognition of the deferred gain immediately.",
"Pledging is the version sellers stumble into. Under IRC Sec. 453A(d), using the installment obligation as security for a loan is generally treated as a payment on the obligation, accelerating gain to the extent of the loan proceeds. A seller who borrows against the note has effectively cashed it out for tax purposes.",
"There is also an interest charge under IRC Sec. 453A on large installment obligations. Where the face amount of all installment obligations arising in a year and outstanding at year end exceeds $5,000,000, the seller owes interest on the deferred tax. This applies to larger commercial transactions and should be modeled where relevant.",
]),
("Death and Basis", [
"Installment notes do not receive a stepped-up basis at death. Under IRC Sec. 691, the remaining deferred gain is income in respect of a decedent, taxable to the estate or beneficiaries as payments come in.",
"This is a meaningful difference from holding the property itself, which would receive a basis step-up under IRC Sec. 1014. A seller in poor health or advanced age is trading a full step-up for a rate deferral, and that is usually a bad trade.",
"For an older seller, holding the property and passing it to heirs with a stepped-up basis frequently beats selling on an installment note. The heirs can then sell with little or no gain. This should be modeled explicitly rather than assumed either way.",
]),
("Worked Example: Seller-Financed Commercial Sale", [
"A seller disposes of a small commercial building for $1,850,000. Adjusted basis is $740,000 after 14 years of depreciation totaling $460,000, of which $180,000 is Sec. 1245 property from a prior cost segregation study.",
"Terms are $370,000 down and a $1,480,000 note at 7.25% over 15 years with a balloon at year seven.",
"In the year of sale, the $180,000 of Sec. 1245 recapture is fully taxable as ordinary income under IRC Sec. 453(i), regardless of the installment method. That is roughly $67,000 of federal tax against $370,000 of cash received, which is manageable but would not have been on a $100,000 down payment.",
"The remaining gain of $930,000 spreads. Gross profit percentage applies to each principal payment, and the $280,000 of unrecaptured Sec. 1250 gain is layered out first at the 25% rate before the balance is taxed at long-term capital gain rates.",
"By spreading the gain across seven years to the balloon, the seller stays below the threshold for the top capital gain rate in most years and reduces net investment income tax exposure meaningfully.",
]),
],
"faqs": [
("Does seller financing defer all of my tax?",
 "No. Depreciation recapture under IRC Sec. 1245 and Sec. 1250 is recognized in full in the year of sale under IRC Sec. 453(i), regardless of how little cash you receive. Only the remaining capital gain spreads across payments. Size your down payment against the recapture liability."),
("What interest rate do I have to charge?",
 "At least the applicable federal rate for the term of the note. Below that, the IRS imputes interest under IRC Sec. 483 or Sec. 1274, converting part of your principal into ordinary interest income. There is no benefit to charging below the AFR."),
("Can I borrow against my installment note?",
 "Not without consequences. Under IRC Sec. 453A(d), pledging an installment obligation as security for a loan is generally treated as receiving payment, accelerating the deferred gain to the extent of the loan proceeds. Selling or gifting the note triggers acceleration under IRC Sec. 453B."),
("What happens to an installment note when I die?",
 "It does not get a basis step-up. Under IRC Sec. 691 the remaining deferred gain is income in respect of a decedent, taxable to your estate or heirs as payments arrive. For an older seller, holding the property for a full step-up under IRC Sec. 1014 often beats an installment sale."),
("Can I choose not to use the installment method?",
 "Yes. The installment method applies automatically, but you may elect out under IRC Sec. 453(d) and recognize all gain in the year of sale. This is occasionally the right choice when you have expiring capital losses, net operating losses, or an unusually low income year."),
],
"related": [
("/blog/depreciation-recapture-planning/", "Depreciation recapture planning"),
("/blog/how-to-avoid-capital-gains-tax-when-selling-rental-property/", "Avoiding capital gains tax on a rental sale"),
("/blog/how-does-1031-exchange-work-for-rental-properties/", "How a 1031 exchange works"),
],
"cta_head": "Size the Down Payment Against the Recapture",
"cta_body": "The most common seller financing mistake is a down payment too small to cover the immediate recapture tax. Send us your basis, depreciation history, and proposed terms.",
},

{
"slug": "self-directed-ira-real-estate-ubit-udfi",
"title": "Self-Directed IRA Real Estate: UBIT, UDFI, and Why Leverage Creates a Tax Bill",
"meta_title": "Self-Directed IRA Real Estate, UBIT and UDFI Explained (2026) | AE Tax Advisors",
"meta_desc": "Leveraged real estate in a self-directed IRA triggers UDFI tax under IRC Sec. 514. Prohibited transactions, UBIT rules, and the Solo 401k alternative for 2026.",
"category": C, "date": D,
"intro": [
"A self-directed IRA can own real estate. That much is true and widely advertised. What is advertised far less is that a leveraged property inside an IRA generates taxable income to the IRA itself, at trust tax rates that reach 37% at approximately $15,650 of income in 2025.",
"Add the prohibited transaction rules, which can disqualify the entire account, and the self-directed IRA becomes a tool that works well in narrow circumstances and badly in most others.",
],
"sections": [
("UDFI: The Leverage Problem", [
"Under IRC Sec. 514, income from debt-financed property held by a tax-exempt entity, including an IRA, is unrelated debt-financed income and is subject to unrelated business income tax.",
"The taxable portion is determined by the debt-financed percentage, calculated as the average acquisition indebtedness during the year divided by the average adjusted basis. A property purchased for $400,000 with $240,000 of debt has a 60% debt-financed percentage, so 60% of the net rental income is taxable to the IRA.",
"The IRA files Form 990-T and pays at trust rates, which compress brutally. The top 37% rate applies at roughly $15,650 of taxable income in 2025, meaning an IRA with $40,000 of net rental income and 60% leverage pays close to the top marginal rate on the taxable portion.",
"Depreciation is allowed in the calculation, which helps considerably. A leveraged property generating $38,000 of net rental income before depreciation, with $14,000 of depreciation, has $24,000 of net income of which 60% or $14,400 is subject to UBIT. That produces a manageable but real tax bill inside a supposedly tax-free account.",
]),
("UDFI on Sale Is the Larger Item", [
"The gain on sale is also subject to UDFI, using the highest debt-financed percentage during the twelve months preceding the sale. A property that appreciated $260,000 with a 55% average debt-financed percentage produces $143,000 of taxable gain to the IRA.",
"There is a meaningful planning point here. If the debt is fully paid off more than twelve months before the sale, the debt-financed percentage for the sale calculation drops to zero and the entire gain is sheltered.",
"For an IRA holding a leveraged property with substantial appreciation, paying off the loan thirteen months before listing can eliminate a six-figure tax. Almost nobody does this, because almost nobody knows the twelve-month lookback exists.",
]),
("Prohibited Transactions Are the Real Risk", [
"Under IRC Sec. 4975, transactions between the IRA and disqualified persons are prohibited. Disqualified persons include the IRA owner, the owner's spouse, ancestors, lineal descendants and their spouses, and entities in which those persons hold controlling interests.",
"The consequence is severe. A prohibited transaction generally disqualifies the entire IRA as of the first day of the year, treating the whole account as distributed. For a $900,000 IRA held by someone under 59 and a half, that is immediate ordinary income on the full balance plus a 10% early distribution penalty.",
"The failure modes are mundane. Performing repairs yourself on IRA-owned property is a prohibited transaction, because you are providing services to the plan. Paying a property expense from personal funds is a prohibited contribution. Staying a night at an IRA-owned vacation property is self-dealing. Renting to your child is prohibited. Personally guaranteeing the loan is prohibited, which is why IRA real estate loans must be non-recourse.",
"This is what makes IRA real estate operationally difficult. The account must be entirely arm's length, funded entirely from IRA assets, with all work performed by unrelated third parties.",
]),
("The Solo 401k Alternative", [
"A qualified plan, including a solo 401(k), receives an exception from UDFI on real property under IRC Sec. 514(c)(9) where the acquisition satisfies specific requirements including a fixed purchase price, non-participating debt terms, and restrictions on seller financing from disqualified persons.",
"For a self-employed person eligible for a solo 401(k), this is generally the better vehicle for leveraged real estate. Same asset, same account protection, without the UDFI tax on the leveraged portion.",
"The prohibited transaction rules still apply in full. The exception addresses the tax, not the operational restrictions.",
]),
("What Actually Works Inside an IRA", [
"Unleveraged property held for appreciation and rent works cleanly. No debt means no UDFI, and the income compounds tax deferred or tax free in a Roth.",
"Private lending works well. An IRA making mortgage loans earns interest income that is not unrelated business income and is not debt-financed, provided the IRA is not itself borrowing to fund the loans.",
"Tax lien investing and note purchases have similar clean profiles.",
"What works badly is anything requiring the owner's labor, anything leveraged for a short hold, and anything involving family. Investors drawn to real estate specifically because they want to add value through their own work are the worst candidates for IRA ownership, because that work is exactly what is prohibited.",
]),
("Worked Example: Leveraged IRA Rental", [
"A self-directed IRA buys a $420,000 rental with $170,000 of IRA cash and a $250,000 non-recourse loan. The average debt-financed percentage in year one is 59.5%.",
"Net rental income before depreciation is $31,000. Depreciation on the $340,000 building portion is $12,364. Net income is $18,636, of which 59.5% or $11,088 is unrelated debt-financed income.",
"After the $1,000 specific deduction, taxable income is $10,088, producing roughly $2,700 of tax at trust rates on Form 990-T.",
"Six years later the property is worth $610,000 and the loan balance is $214,000. If sold immediately, the average debt-financed percentage of roughly 52% applies to the $190,000 of appreciation plus depreciation recapture, producing over $35,000 of tax.",
"If the IRA instead retires the loan from other IRA assets and waits thirteen months, the debt-financed percentage for the sale calculation is zero and the entire gain is sheltered.",
]),
],
"faqs": [
("Do I pay tax on real estate held in my IRA?",
 "Only if it is debt-financed. Under IRC Sec. 514, income and gain attributable to acquisition indebtedness is unrelated debt-financed income, taxable to the IRA at trust rates on Form 990-T. Unleveraged property produces no UBIT and compounds tax deferred or tax free."),
("How do I avoid UDFI on the sale of an IRA property?",
 "Pay off the debt more than twelve months before the sale. The debt-financed percentage for the gain calculation looks back twelve months, so a loan retired thirteen months before closing reduces that percentage to zero and shelters the entire gain."),
("Can I do repairs myself on a property my IRA owns?",
 "No. Performing services for the IRA is a prohibited transaction under IRC Sec. 4975, which can disqualify the entire account as of the first day of the year. All work must be done by unrelated third parties and paid from IRA funds."),
("Is a solo 401k better than an IRA for real estate?",
 "For leveraged real estate, generally yes. Qualified plans receive a UDFI exception for real property under IRC Sec. 514(c)(9) when specific conditions are met. The prohibited transaction rules still apply in full, so the operational restrictions are unchanged."),
("What is the penalty for a prohibited transaction?",
 "The IRA is generally treated as fully distributed as of the first day of the year in which it occurred. That means ordinary income tax on the entire balance, plus a 10% early distribution penalty if you are under 59 and a half. There is no partial remedy for most violations."),
],
"related": [
("/blog/what-retirement-plan-gives-the-largest-tax-deduction/", "Which retirement plan gives the largest deduction"),
("/blog/how-much-can-i-contribute-to-a-solo-401k/", "Solo 401(k) contribution limits"),
("/blog/passive-activity-loss-rules-for-real-estate-investors/", "Passive activity loss rules"),
],
"cta_head": "Most IRA Real Estate Should Be Somewhere Else",
"cta_body": "If you are considering leverage inside a retirement account, the structure decision matters more than the property. Bring your account type, funding plan, and target property.",
},

{
"slug": "real-estate-syndication-lp-investor-tax-guide",
"title": "Real Estate Syndication Tax Guide for Limited Partners: Reading the K-1",
"meta_title": "Real Estate Syndication Tax Guide for LP Investors (2026) | AE Tax Advisors",
"meta_desc": "Syndication K-1 losses are usually passive and suspend. Basis, at-risk, capital accounts, state filings, and exit taxation explained for LP investors in 2026.",
"category": C, "date": D,
"intro": [
"Limited partners in real estate syndications receive a K-1 showing a large loss in year one, usually driven by a cost segregation study and bonus depreciation. Many investors were sold on that loss offsetting their W-2 income. For nearly all of them, it will not.",
"Understanding why, and what the loss actually does, changes how you should size these investments and when you should expect the benefit.",
],
"sections": [
("The Loss Is Almost Always Passive", [
"A limited partner is, by regulation, presumed not to materially participate. Treasury Regulation Sec. 1.469-5T(e) provides that an interest in a limited partnership is generally treated as a passive activity, with narrow exceptions for LPs who also hold a general partner interest or who meet certain participation tests.",
"That means the loss on your K-1 is passive under IRC Sec. 469. It can offset passive income from other sources, including other syndications, rental properties, and certain business interests where you do not materially participate. It cannot offset wages, business income where you do materially participate, portfolio interest, or dividends.",
"Real estate professional status does not fix this for most investors. Even if you qualify under IRC Sec. 469(c)(7), you must still materially participate in the specific activity, and a limited partner in a deal run by a sponsor does not.",
"The practical effect is that syndication losses build a suspended loss balance. Those losses are not wasted. They release when the deal produces passive income, when other passive income appears, or when the interest is disposed of in a fully taxable transaction.",
]),
("Basis and At-Risk Limits Come First", [
"Before the passive rules even apply, two other limits screen the loss.",
"Your outside basis in the partnership interest limits deductible losses under IRC Sec. 704(d). Basis starts with your capital contribution and increases with your allocable share of partnership liabilities. For a real estate syndication, qualified nonrecourse financing is generally allocated to partners and increases basis, which is why a $100,000 investment in a leveraged deal can support more than $100,000 of loss.",
"The at-risk rules under IRC Sec. 465 apply next. Qualified nonrecourse financing secured by real property is generally treated as at-risk, so conventional agency and bank debt usually does not create a limitation. Mezzanine debt, preferred equity structured as debt, and sponsor-affiliated loans require closer review.",
"Losses blocked by basis or at-risk carry forward until basis or at-risk amounts are restored, which for most syndications happens through additional allocations of income or debt.",
]),
("State Filing Obligations Multiply", [
"A syndication owning property in Texas, Arizona, and Georgia gives you a filing obligation in each of those states, subject to their filing thresholds. Many investors receive a federal K-1 and several state K-1s and file only the federal.",
"Some sponsors file composite returns on behalf of non-resident partners, which resolves the obligation but often at a higher effective rate than filing individually and without the ability to claim state-specific deductions or offset losses across years. Others withhold at the entity level, which generates a credit you must claim on a non-resident return to recover.",
"For an investor in eight syndications across twelve states, the compliance cost becomes real and should be part of the underwriting. A $50,000 investment producing $1,800 of annual return does not carry $2,400 of additional state filing cost gracefully.",
]),
("Capital Accounts and the Waterfall", [
"Your K-1 shows a capital account that will diverge from both your investment and your economic position. This is normal and reflects the allocation of depreciation, which is disproportionate in most deal structures.",
"What matters at exit is the waterfall and how gain is allocated to bring capital accounts into line with distributions. A deal with a preferred return and a promote will allocate gain in a specific order, and your share of gain at exit will often exceed your share of losses along the way.",
"Negative capital accounts are common in leveraged deals after several years of depreciation and are not, by themselves, a problem. They become a problem on a disposition, because a negative capital account generally produces gain even where there is no cash. Investors who receive a capital call or watch a deal go sideways can face taxable gain on a loss-making investment.",
]),
("Exit Taxation", [
"When the property sells, the K-1 reports gain in several components. Sec. 1245 recapture from the cost segregation study is ordinary income. Unrecaptured Sec. 1250 gain from building depreciation is taxed at up to 25%. The remaining gain is long-term capital gain.",
"Your suspended passive losses release in full on a fully taxable disposition of the entire interest under IRC Sec. 469(g), and they offset the gain. This is the moment the deferred benefit arrives.",
"The net result for most LP investors is that a syndication converts what would have been ordinary income at up to 37% into deferred gain taxed at a blend of 25% and 20% rates several years later, with suspended losses offsetting part of it. That is a genuine benefit. It is simply not the year-one W-2 offset the pitch deck implied.",
"Where the sponsor executes a 1031 exchange at the property level, the deferral continues and no gain is recognized, but partners who want out face the drop-and-swap problem, which requires planning well before the sale.",
]),
("Worked Example: $200,000 LP Investment", [
"An investor commits $200,000 to a multifamily syndication. The sponsor runs a cost segregation study, and the year one K-1 shows a $148,000 loss.",
"The investor is a surgeon with $900,000 of W-2 and practice income and no other passive income. The entire $148,000 suspends under IRC Sec. 469. Current year benefit is zero.",
"Over years two through five, the deal produces $34,000 of cumulative passive income, absorbing $34,000 of the suspended loss. Remaining suspended loss is $114,000.",
"In year six the property sells. The K-1 reports $61,000 of Sec. 1245 recapture, $79,000 of unrecaptured Sec. 1250 gain, and $186,000 of capital gain, on $326,000 of total gain. The $114,000 of suspended losses release and offset the gain.",
"Net taxable gain is $212,000, taxed at a blend of 25% and 20% rates rather than the 37% ordinary rate the investor pays on practice income. The benefit is real and it arrives in year six.",
]),
],
"faqs": [
("Can syndication losses offset my W2 income?",
 "Almost never. Limited partners are presumed not to materially participate under Treas. Reg. Sec. 1.469-5T(e), so the loss is passive under IRC Sec. 469 and can only offset passive income. Real estate professional status does not change this, because you still must materially participate in the specific activity."),
("What happens to my suspended syndication losses?",
 "They carry forward indefinitely and release when the deal or another investment produces passive income, or in full when you dispose of your entire interest in a fully taxable transaction under IRC Sec. 469(g). They are deferred, not lost."),
("Do I have to file state returns for every syndication?",
 "Generally yes, in each state where the partnership owns property, subject to that state's filing thresholds. Some sponsors file composite returns or withhold at the entity level. Composite filing is convenient but often produces a higher effective rate than filing individually."),
("Why is my capital account negative?",
 "Because depreciation allocations have exceeded your contributions and income allocations. This is normal in leveraged real estate and is not a problem while you hold. It matters on disposition, because a negative capital account generally produces taxable gain even without cash proceeds."),
("How is the gain taxed when the property sells?",
 "In layers. Sec. 1245 recapture from the cost segregation study is ordinary income. Unrecaptured Sec. 1250 gain is taxed at up to 25%. The balance is long-term capital gain. Your suspended passive losses release and offset the total."),
],
"related": [
("/blog/how-does-syndication-k1-income-affect-my-taxes/", "How syndication K-1 income affects your taxes"),
("/blog/cost-segregation-syndication-k1-impact/", "Cost segregation and syndication K-1s"),
("/blog/passive-activity-loss-rules-investor-guide/", "Passive activity loss rules for investors"),
],
"cta_head": "Know What the K-1 Will Actually Do Before You Wire",
"cta_body": "We model syndication investments against your full income picture so you know whether the loss lands in year one or year six. Bring your current holdings and the deal materials.",
},

{
"slug": "interest-tracing-rules-real-estate-investors",
"title": "Interest Tracing Rules: Why Your Loan Security Does Not Determine Deductibility",
"meta_title": "Interest Tracing Rules for Real Estate Investors (2026) | AE Tax Advisors",
"meta_desc": "Under Treas. Reg. 1.163-8T interest follows the use of proceeds, not the collateral. How to trace HELOC, cash-out, and portfolio loan interest in 2026.",
"category": C, "date": D,
"intro": [
"Almost every real estate investor believes interest is deductible because the loan is secured by a rental property. That is not the rule, and the difference is worth thousands of dollars annually to investors who move money between properties and personal use.",
"Under Treasury Regulation Sec. 1.163-8T, interest expense is allocated according to how the loan proceeds are used. The collateral is irrelevant.",
],
"sections": [
("The Basic Rule", [
"Debt is allocated to expenditures, and interest on that debt takes the character of the expenditure. Proceeds used to buy or improve a rental produce interest allocable to a rental activity, deductible on Schedule E. Proceeds used to buy inventory for a business produce trade or business interest. Proceeds used to buy a boat produce personal interest, which is not deductible at all.",
"This cuts both directions. A HELOC on your primary residence used to buy a rental property produces interest deductible against rental income, even though the loan is secured by your home and would not qualify as acquisition indebtedness under the home mortgage interest rules.",
"Conversely, a cash-out refinance on a rental property used to pay off credit cards or fund a vacation produces personal interest, non-deductible, even though the loan is secured by an income-producing asset and appears on the rental's loan statement.",
]),
("The Ordering Rules When Funds Are Mixed", [
"The regulations provide ordering rules for what happens when loan proceeds land in an account with other money. Under Treasury Regulation Sec. 1.163-8T(c)(4), expenditures from an account containing debt proceeds are treated as made first from the debt proceeds, in the order the proceeds were deposited, for a period of fifteen days.",
"After that window, a more complex set of rules applies, generally treating expenditures as coming from debt proceeds to the extent of the outstanding balance attributable to those proceeds.",
"The practical consequence is that commingling creates a tracing mess with results that rarely favor the taxpayer. An investor who deposits $200,000 of refinance proceeds into an operating account, pays personal expenses from that account for four months, and then buys a property is going to have a difficult time establishing that the full $200,000 was traced to the acquisition.",
"The fix costs nothing. Open a dedicated account. Deposit loan proceeds there. Spend from it only for the intended purpose. This creates an unambiguous trace that survives examination.",
]),
("The Thirty-Day Rules That Help", [
"Two rules give useful flexibility. Under Treasury Regulation Sec. 1.163-8T(c)(4)(iii)(B), the taxpayer may treat any expenditure made within thirty days before or after debt proceeds are deposited as made from those proceeds.",
"This matters when the timing does not line up cleanly. An investor who closes on a rental with cash on March 3 and closes a refinance on the prior property March 20 can elect to treat the acquisition as funded by the refinance proceeds, tracing the interest to the rental.",
"There is also a rule allowing debt proceeds received in cash to be treated as used for personal expenditures on the date received, which is occasionally useful for isolating a personal-use portion cleanly rather than letting it contaminate an otherwise clean trace.",
]),
("Reallocation When the Use Changes", [
"Debt is reallocated when the proceeds are repaid and reborrowed, or when the underlying asset changes character. If you sell a rental funded by a traced loan and use the proceeds to buy another rental, the debt follows.",
"If you convert a rental to a personal residence, the interest on debt allocated to that property becomes personal residence interest going forward, subject to the home mortgage interest rules under IRC Sec. 163(h)(3) including the acquisition indebtedness limits.",
"Under Treasury Regulation Sec. 1.163-8T(c)(1), the allocation of debt is redetermined whenever there is a reallocation event, so this is not a one-time decision made at closing.",
]),
("Portfolio Loans and Blanket Debt", [
"Investors with blanket loans covering multiple properties, or portfolio lines of credit drawn against several assets, face a harder tracing problem. The loan is secured by everything and funds are drawn as needed.",
"The answer is the same: trace each draw to its use. A $2,400,000 portfolio line drawn in eleven separate advances over three years produces eleven separate traces, each allocated to whatever the advance funded.",
"This requires a schedule maintained as you go. Reconstructing it four years later from bank statements is possible but expensive and less reliable. Investors using portfolio debt should maintain a draw log that records date, amount, and use, cross-referenced to closing statements or invoices.",
]),
("Worked Example: HELOC-Funded Acquisition", [
"An investor takes a $220,000 HELOC on a primary residence and uses $185,000 as the down payment on a $740,000 rental, keeping $35,000 for a kitchen renovation on the primary residence.",
"Interest on 84% of the HELOC balance, the $185,000 traced to the rental, is deductible against rental income on Schedule E. Interest on the remaining 16% is potentially deductible as home mortgage interest under IRC Sec. 163(h)(3) if the renovation qualifies as a substantial improvement to the residence securing the loan, subject to the acquisition indebtedness limits.",
"At 8.25% on a $220,000 balance, that is $18,150 of annual interest, of which $15,246 is a rental deduction. Without tracing, an investor might have claimed none of it, treating a HELOC as personal debt, or all of it as home mortgage interest and run into the acquisition indebtedness limit.",
"The documentation supporting this is the HELOC draw record, the closing statement on the rental, and the renovation invoices. Three documents, held from the start, protect $15,000 of annual deduction indefinitely.",
]),
],
"faqs": [
("Is interest deductible because the loan is secured by a rental property?",
 "No. Under Treas. Reg. Sec. 1.163-8T, interest follows the use of the loan proceeds, not the collateral. A rental-secured loan used for personal expenses produces non-deductible personal interest, and a home-secured HELOC used to buy a rental produces deductible rental interest."),
("Can I deduct HELOC interest if I used it to buy a rental?",
 "Yes, against the rental. The interest is traced to the rental acquisition and deducted on Schedule E, notwithstanding that the loan is secured by your residence. This is often more favorable than home mortgage interest treatment, which is subject to acquisition indebtedness limits."),
("What happens if I mix loan proceeds with other money?",
 "Ordering rules in Treas. Reg. Sec. 1.163-8T(c)(4) apply, and they rarely favor the taxpayer. Commingling makes tracing difficult to establish. Deposit loan proceeds into a dedicated account and spend only for the intended purpose. The fix costs nothing and is durable."),
("Is there any timing flexibility in tracing?",
 "Yes. You may treat an expenditure made within thirty days before or after debt proceeds are received as made from those proceeds. This resolves most real-world timing mismatches between a refinance closing and an acquisition closing."),
("How do I trace interest on a portfolio line of credit?",
 "Draw by draw. Each advance is traced to whatever it funded. Maintain a draw log recording date, amount, and use, cross-referenced to closing statements or invoices. Reconstructing this years later is possible but expensive and far less defensible."),
],
"related": [
("/blog/can-i-deduct-travel-expenses-to-manage-rental-property/", "Deducting travel to manage rental property"),
("/blog/brrrr-method-tax-strategy/", "BRRRR method tax strategy"),
("/blog/how-to-structure-a-real-estate-portfolio-for-tax-efficiency/", "Structuring a portfolio for tax efficiency"),
],
"cta_head": "A Dedicated Account Protects Years of Deductions",
"cta_body": "If you have moved refinance proceeds through a commingled account, the trace may still be recoverable. Send us your loan and draw history and we will map it.",
},

{
"slug": "mid-term-rental-tax-strategy-30-day",
"title": "Mid-Term Rental Tax Strategy: Why 30-Day Stays Are Treated Like Long-Term Rentals",
"meta_title": "Mid-Term Rental Tax Strategy and the 30-Day Rule (2026) | AE Tax Advisors",
"meta_desc": "Mid-term rentals fail the seven-day test and are passive rental activities. How the 30-day rule works and when significant services change the answer in 2026.",
"category": C, "date": D,
"intro": [
"Mid-term rentals, typically 30 to 90 day furnished stays for traveling nurses, relocating professionals, and insurance placements, have grown quickly. Investors are often told they receive the same tax treatment as short-term rentals.",
"They do not. The short-term rental exception turns on an average customer use period of seven days or less. A mid-term rental averaging 47 nights fails that test by a wide margin, and the property is an ordinary passive rental activity.",
],
"sections": [
("The Two Tests That Matter", [
"Treasury Regulation Sec. 1.469-1T(e)(3)(ii) lists six exceptions under which an activity involving the use of tangible property is not a rental activity for purposes of IRC Sec. 469.",
"The first is the seven-day test. Where the average period of customer use is seven days or less, the activity is not a rental. This is the short-term rental exception that lets Airbnb operators offset W-2 income with material participation alone.",
"The second is the thirty-day test with significant personal services. Where the average period of customer use is thirty days or less and significant personal services are provided by or on behalf of the owner, the activity is also not a rental.",
"Mid-term rentals typically fail both. Average stays exceed thirty days, so the second exception is unavailable regardless of services. And they exceed seven days, so the first is unavailable regardless of anything.",
]),
("What Significant Personal Services Actually Means", [
"Even where the average stay is under thirty days, the significant services requirement is demanding. Under Treasury Regulation Sec. 1.469-1T(e)(3)(iv), services in connection with making property available for use are not counted, which excludes cleaning between tenants, routine repairs, trash collection, and providing utilities.",
"Services that count are those provided to the occupant that are not typical of a rental, such as daily housekeeping, meals, concierge, or transportation. This is a hotel standard, not a furnished apartment standard.",
"Furnishing a unit, providing linens, and including utilities does not make a mid-term rental a service business. Operators who have been told otherwise should look at the regulation text directly.",
"There is also an exception under Treasury Regulation Sec. 1.469-1T(e)(3)(ii)(E) where the property is available during defined business hours for nonexclusive use by various customers, which does not fit residential rental at all.",
]),
("So What Do Mid-Term Rentals Actually Offer", [
"They are ordinary rental real estate for tax purposes, which is not a bad thing. It simply means the standard rules apply.",
"Depreciation runs over 27.5 years as residential rental property under IRC Sec. 168(e)(2)(A), rather than the 39-year nonresidential schedule that applies to short-term rentals with average stays of seven days or less. This is genuinely better on the structural component, producing a faster write-off of the building itself.",
"Furnishings are five-year property fully deductible in the placed-in-service year. A furnished mid-term unit typically carries $18,000 to $35,000 of furniture, appliances, and equipment, all deductible immediately under IRC Sec. 168(k).",
"Cost segregation works normally and produces the same reclassification percentages as any residential rental, generally 20% to 28%.",
"The loss is passive. It offsets other passive income and otherwise suspends, unless the owner qualifies as a real estate professional under IRC Sec. 469(c)(7) and materially participates, or falls within the $25,000 special allowance under IRC Sec. 469(i) for active participants with modified adjusted gross income under $150,000.",
]),
("Mixed Portfolios Create Planning Options", [
"An investor holding both short-term and mid-term rentals has a useful structure. The short-term rental, if material participation is established, produces non-passive income or loss. The mid-term rental produces passive income or loss.",
"Where the mid-term rental generates passive income, it can absorb suspended passive losses from other sources, including syndications. Where it generates a loss, that loss needs passive income to absorb it.",
"Grouping elections under Treasury Regulation Sec. 1.469-4 can combine activities into a single activity for material participation purposes, but grouping a rental with a non-rental activity has specific restrictions, and the seven-day exception operates at the activity level. Grouping decisions here are consequential and generally irrevocable, so they warrant analysis before filing rather than after.",
]),
("The Self-Employment Tax Question", [
"Operators sometimes worry that providing furnishings and utilities makes mid-term rental income subject to self-employment tax. Generally it does not.",
"Rental income from real estate is excluded from net earnings from self-employment under IRC Sec. 1402(a)(1), unless services are rendered to the occupant beyond those customarily provided in connection with the rental of space for occupancy only. That is the same substantial services standard, and furnished housing with utilities does not meet it.",
"This is favorable. Mid-term rental income avoids the 15.3% self-employment tax that would apply to a genuine hotel operation, while short-term rental operators who provide substantial services can find themselves inside it.",
]),
("Worked Example: Traveling Nurse Rental", [
"An investor buys a $410,000 condo near a hospital, furnishes it for $26,000, and rents to traveling nurses on 13-week contracts. Average stay is 91 days.",
"The property is residential rental property on a 27.5-year schedule. Land is allocated at $72,000, leaving $338,000 depreciable.",
"A cost segregation study reclassifies 23%, producing $77,740 of five-year and 15-year property deductible in year one under IRC Sec. 168(k). Structural depreciation adds roughly $9,464. The $26,000 of furnishings is fully deductible as five-year property.",
"Total first-year depreciation is approximately $113,204. Net rental income before depreciation is $19,000, producing a $94,204 loss.",
"The investor is a W-2 employee earning $340,000, does not qualify as a real estate professional, and is above the special allowance phase-out. The entire loss suspends.",
"Had the same property been operated with an average stay of six nights and material participation documented, the loss would have offset W-2 income directly. The property, the study, and the furnishings are identical. Only the average stay differs.",
]),
],
"faqs": [
("Do mid-term rentals qualify for the short-term rental loophole?",
 "No. The exception in Treas. Reg. Sec. 1.469-1T(e)(3)(ii)(A) requires an average customer use period of seven days or less. A mid-term rental averaging 30 to 90 nights fails that test, and is an ordinary passive rental activity under IRC Sec. 469."),
("What about the 30-day exception with significant services?",
 "It requires both an average stay of 30 days or less and significant personal services. Services making property available for use, including cleaning, repairs, and utilities, do not count. The standard is closer to hotel service than furnished apartment service, and most mid-term rentals do not meet it."),
("Is a mid-term rental depreciated over 27.5 or 39 years?",
 "27.5 years, as residential rental property under IRC Sec. 168(e)(2)(A). This is actually better than a true short-term rental with average stays of seven days or less, which is nonresidential property on a 39-year schedule for the structural component."),
("Can I deduct the furnishings in a mid-term rental?",
 "Yes, in full in the year placed in service. Furniture, appliances, electronics, and housewares are five-year property fully eligible for bonus depreciation under IRC Sec. 168(k). A typical furnished unit carries $18,000 to $35,000 of this."),
("Do I owe self-employment tax on mid-term rental income?",
 "Generally no. Rental income from real estate is excluded from self-employment earnings under IRC Sec. 1402(a)(1) unless services beyond those customary for occupancy are provided. Furnished housing with utilities included does not cross that line."),
],
"related": [
("/blog/str-vs-ltr-tax-treatment-differences/", "STR versus LTR tax treatment"),
("/blog/str-loophole-7-day-rule-explained/", "The seven-day rule explained"),
("/blog/how-to-depreciate-furnished-rentals/", "Depreciating furnished rentals"),
],
"cta_head": "The Average Stay Decides Everything",
"cta_body": "If you are choosing between short-term and mid-term operation, the tax difference can exceed the revenue difference. Send us your property and target tenant profile.",
},

{
"slug": "delaware-statutory-trust-dst-1031-exchange",
"title": "Delaware Statutory Trusts and 1031 Exchanges: When a DST Solves the Problem",
"meta_title": "Delaware Statutory Trust DST 1031 Exchange Guide (2026) | AE Tax Advisors",
"meta_desc": "DSTs qualify as replacement property under Rev. Rul. 2004-86. Seven deadly sins, debt replacement, and the 721 UPREIT exit explained for 2026.",
"category": C, "date": D,
"intro": [
"A Delaware statutory trust interest qualifies as like-kind replacement property in a 1031 exchange. Revenue Ruling 2004-86 confirmed that a beneficial interest in a properly structured DST is treated as a direct interest in real estate rather than as a partnership interest, which would be ineligible.",
"That makes DSTs the standard solution for investors facing a 45-day identification deadline with no acquisition target, or investors who want to exit active management without triggering gain.",
],
"sections": [
("Why the Structure Qualifies", [
"IRC Sec. 1031 excludes partnership interests from like-kind treatment. A tenancy-in-common structure works but is operationally difficult with many owners, and lenders dislike it.",
"Revenue Ruling 2004-86 held that where a trust's activities are limited to holding property, the trustee has no power to renegotiate leases, refinance, or reinvest proceeds, and the beneficial interests are fixed, the arrangement is a grantor trust rather than a business entity. Each beneficiary is treated as owning an undivided interest in the underlying real estate directly.",
"That is the entire foundation. It also explains the operational constraints, since the same passivity that qualifies the structure also prevents it from responding to changing circumstances.",
]),
("The Seven Prohibitions", [
"Practitioners refer to the limitations in Revenue Ruling 2004-86 as the seven deadly sins. Once the offering closes, the trust generally may not accept additional capital contributions, renegotiate the existing mortgage or borrow new funds, reinvest sale proceeds, make capital expenditures beyond normal repairs and those required by law or existing leases, hold cash reserves beyond short-term investment between distribution dates, distribute anything other than cash from normal operations, or renegotiate leases or enter new leases except on a master lease already in place.",
"These constraints are why most DSTs use a master lease structure. An affiliate of the sponsor leases the entire property from the trust and handles operations, giving the operating flexibility the trust itself cannot have.",
"The practical consequence is that a DST cannot adapt. If the property needs a major capital improvement not contemplated at closing, or if the loan matures in a bad credit market, the trust has limited options. Sponsors sometimes convert the DST to an LLC to regain flexibility, which is a taxable event for investors unless carefully structured.",
]),
("Debt Replacement Is the Common Use Case", [
"An investor exchanging out of a leveraged property must replace both equity and debt to fully defer gain. Boot is recognized to the extent of debt relief not offset by new debt or additional cash.",
"DSTs are typically offered at specific loan-to-value ratios, and an investor can select an offering matching their debt replacement requirement. This is often easier than finding a direct acquisition with the right leverage profile inside the 45-day window.",
"The debt in a DST is non-recourse to investors, which is generally attractive. It does count for basis and at-risk purposes, and it does generate depreciation deductions on the leveraged portion.",
]),
("Identification and Timing Advantages", [
"The 45-day identification deadline and 180-day closing deadline under IRC Sec. 1031(a)(3) are absolute. There is no extension for a failed acquisition.",
"DSTs close quickly because there is no negotiation, no diligence period, and no financing contingency. An investor at day 42 with a collapsed primary target can identify a DST and close within days.",
"Many investors identify a DST as a backup under the three-property rule alongside their primary target, costing nothing if the primary closes. This is prudent and underused.",
]),
("The 721 UPREIT Exit", [
"Some DST offerings are structured with a planned contribution to a REIT operating partnership under IRC Sec. 721 after a holding period. The investor's DST interest is exchanged for operating partnership units, tax deferred.",
"The units are typically convertible to REIT shares, which is a taxable event, or held for income. This converts illiquid real estate into a more liquid, diversified position without triggering gain at the conversion step.",
"The tradeoff is that once inside the operating partnership, a future 1031 exchange is no longer available, because partnership interests are not like-kind property. The 721 exchange is generally a one-way door, ending the exchange chain and setting up an eventual taxable event or a step-up at death under IRC Sec. 1014.",
"For an investor in their seventies planning to hold until death, this is an excellent outcome. For a 52-year-old investor who intends to keep exchanging, it forecloses the strategy.",
]),
("What DSTs Cost", [
"Load matters. DST offerings typically carry 8% to 12% in combined selling commissions, offering expenses, and acquisition fees, embedded in the offering price. That is a real drag on returns that direct ownership does not carry.",
"Investors should evaluate a DST against the alternative of paying the tax. An investor with $400,000 of deferred gain facing roughly $110,000 of tax should compare that to a $90,000 load on a $900,000 exchange, plus the loss of control and the illiquidity.",
"Sometimes the DST wins clearly, particularly where the alternative is a failed exchange. Sometimes paying the tax and investing freely is better. The analysis is specific to the numbers and should be run rather than assumed.",
]),
("Worked Example: Failed Primary Target", [
"An investor sells a $2,100,000 apartment building with $780,000 of adjusted basis and $960,000 of debt. Deferred gain is $1,320,000, including $340,000 of unrecaptured Sec. 1250 gain and $95,000 of Sec. 1245 recapture from a prior cost segregation study.",
"The primary replacement target falls through on day 38. Tax exposure if the exchange fails is approximately $370,000 federal and state combined.",
"The investor identifies two DST offerings at day 43, one at 52% leverage to satisfy debt replacement and one unleveraged, allocating $1,140,000 of equity across them and closing at day 61.",
"Combined load at roughly 10% is approximately $114,000. Against $370,000 of avoided current tax, the exchange is clearly the better outcome, and the investor retains the option to exchange out of the DSTs at their eventual sale.",
]),
],
"faqs": [
("Does a DST qualify for a 1031 exchange?",
 "Yes. Revenue Ruling 2004-86 holds that a beneficial interest in a properly structured Delaware statutory trust is treated as a direct interest in real estate, not a partnership interest, making it eligible replacement property under IRC Sec. 1031."),
("What are the seven deadly sins of a DST?",
 "Restrictions from Rev. Rul. 2004-86 that prevent the trust from accepting new capital, refinancing or borrowing, reinvesting proceeds, making capital expenditures beyond normal repairs, holding excess reserves, making non-operating distributions, or renegotiating leases. They preserve the tax treatment but eliminate operational flexibility."),
("Can a DST satisfy my debt replacement requirement?",
 "Yes. DSTs are offered at defined loan-to-value ratios, and the non-recourse debt counts toward your replacement requirement. Selecting an offering matched to your prior leverage is often easier than finding a direct acquisition with the right debt profile inside 45 days."),
("What is a 721 UPREIT exit and should I use one?",
 "It is a tax-deferred contribution of your DST interest to a REIT operating partnership in exchange for units. It provides liquidity and diversification but ends the exchange chain, since partnership interests are not like-kind property. Excellent for an investor holding until death, limiting for one who intends to keep exchanging."),
("Are DST fees worth it?",
 "It depends on the alternative. Loads typically run 8% to 12%. Compare that against the tax you would pay on a failed exchange. Where the alternative is recognizing several hundred thousand dollars of gain, a DST usually wins. Where the deferred gain is modest, paying the tax and investing freely may be better."),
],
"related": [
("/blog/1031-exchange-timeline-45-180-day-rules/", "1031 exchange 45 and 180 day rules"),
("/blog/1031-exchange-alternatives/", "1031 exchange alternatives"),
("/blog/reverse-1031-exchange-explained/", "Reverse 1031 exchanges explained"),
],
"cta_head": "Identify a Backup Before Day 40",
"cta_body": "Most failed exchanges fail because there was no plan B. If you are inside an identification window or planning a sale, bring us the timeline and we will structure the contingency.",
},

{
"slug": "cash-out-refinance-tax-treatment-rental-property",
"title": "Cash-Out Refinance on a Rental Property: What Is and Is Not Taxable",
"meta_title": "Cash-Out Refinance Tax Treatment on Rental Property (2026) | AE Tax Advisors",
"meta_desc": "Refinance proceeds are not taxable, but basis, interest tracing, and points treatment all change. Complete tax mechanics of a rental cash-out for 2026.",
"category": C, "date": D,
"intro": [
"A cash-out refinance is the closest thing to tax-free money in real estate. You extract equity, you owe no tax, and you keep the property.",
"That is genuinely true, and it is why the strategy is so widely used. But four things change when you refinance, and three of them get handled incorrectly on most returns.",
],
"sections": [
("The Proceeds Are Not Income", [
"Loan proceeds are not gross income under IRC Sec. 61 because they carry a repayment obligation. This holds regardless of the amount extracted or how much the property has appreciated.",
"An investor who bought a property for $340,000, watched it appreciate to $720,000, and refinances at 75% loan to value receives $540,000 in loan proceeds. After paying off a $210,000 existing loan, $330,000 in cash arrives with no tax consequence.",
"This does not change your basis. Basis remains original cost plus capitalized improvements less accumulated depreciation. It does not increase because you borrowed against the property, and it does not increase because the property appreciated.",
]),
("Interest Deductibility Depends on Use", [
"This is the most commonly mishandled item. Under Treasury Regulation Sec. 1.163-8T, interest is allocated based on how the proceeds are used, not on what secures the loan.",
"Proceeds reinvested into another rental produce interest deductible against that rental. Proceeds used to pay off a personal credit card produce personal interest, non-deductible. Proceeds used to fund a business produce trade or business interest. Proceeds used to buy stocks produce investment interest, deductible only against net investment income under IRC Sec. 163(d).",
"A refinance producing $330,000 of proceeds, of which $240,000 goes into another rental and $90,000 pays for a home renovation and a vehicle, produces interest that is roughly 73% deductible against rental income and 27% subject to other rules or non-deductible.",
"The refinanced property's Schedule E should reflect only the traced portion. Deducting the entire interest against the rental because that is where the loan sits is a common error and is wrong.",
]),
("Points and Loan Costs Amortize", [
"Points paid to obtain a rental property refinance are not currently deductible. They must be amortized over the life of the loan under IRC Sec. 461(g). Points on a refinance of a personal residence follow different rules, but rental refinances are clear.",
"On $9,600 of points on a 30-year loan, that is $320 per year.",
"Where a prior loan being refinanced still carries unamortized points, those remaining points are generally deductible in full in the year the old loan is retired, since the debt to which they related no longer exists. This is a real deduction that gets missed routinely, particularly for investors who refinance every few years.",
"Other loan costs, appraisal, title, lender fees, and origination charges, are also amortized over the loan term rather than deducted currently or added to basis.",
]),
("The Basis Gap Grows", [
"Each refinance widens the gap between what you owe and what you can deduct. After three refinance cycles, an investor may have $90,000 of remaining basis and $480,000 of debt on a $650,000 property.",
"On a sale, gain is measured against basis. The taxable gain here is roughly $560,000 while the cash after debt payoff is roughly $130,000. The tax at blended recapture and capital gain rates can approach or exceed the cash received.",
"This is the structural risk in a refinance-heavy strategy, and it has a well-established answer. Under IRC Sec. 1031, a like-kind exchange defers the entire gain. Exchange rather than sell, and continue exchanging, and the gap never comes due during your lifetime. At death, heirs receive a stepped-up basis under IRC Sec. 1014 and the deferred gain disappears entirely.",
"That is the actual endgame of buy, refinance, hold. Investors who follow the first three steps and then sell without an exchange discover the arithmetic at closing.",
]),
("Refinancing Does Not Reset Depreciation", [
"Depreciation continues on the original schedule regardless of refinancing. A property placed in service in 2016 on a 27.5-year schedule continues on that schedule after a 2026 refinance. The loan is irrelevant to depreciation.",
"Capital improvements made with refinance proceeds are a separate matter. Those are added to basis and depreciated on their own schedule from their own placed-in-service date. A $140,000 renovation funded by refinance proceeds creates $140,000 of new depreciable basis, and a cost segregation study on that improvement can accelerate a large share of it.",
"This is the productive way to use refinance proceeds from a tax perspective: reinvest into improvements or additional property, generating new depreciable basis, rather than extracting for consumption.",
]),
("Worked Example: Refinance and Redeploy", [
"An investor owns a rental purchased for $380,000 in 2018, now worth $690,000, with $198,000 remaining on the original loan and $312,000 of adjusted basis after depreciation.",
"A cash-out refinance at 75% loan to value produces $517,500 of loan proceeds. After retiring the $198,000 existing loan and $11,000 of closing costs, the investor receives $308,500 tax free.",
"Unamortized points of $4,200 from the original loan are deducted in full in the refinance year. New points and loan costs of $11,000 amortize over 30 years at $367 annually.",
"The investor deposits the $308,500 into a dedicated account and uses $290,000 as the down payment on a $1,160,000 fourplex, with $18,500 retained for reserves. Interest on 94% of the new loan is traced to the fourplex acquisition and deductible against that property.",
"A cost segregation study on the fourplex produces $242,000 of first-year deduction. The investor qualifies as a real estate professional and uses it against other income.",
"No tax on $308,500 extracted, a $242,000 deduction created, and interest fully deductible. The basis gap on the original property grows, which the investor plans to resolve through a 1031 exchange at eventual disposition.",
]),
],
"faqs": [
("Do I pay tax on cash-out refinance proceeds?",
 "No. Loan proceeds are not gross income under IRC Sec. 61 because you have a repayment obligation. This is true regardless of how much equity you extract or how much the property has appreciated."),
("Does a refinance increase my depreciable basis?",
 "No. Basis is original cost plus capitalized improvements less accumulated depreciation. Borrowing against appreciation does not change it. Only capital improvements funded with the proceeds create new depreciable basis, on their own schedule from their own placed-in-service date."),
("Is all the interest on a cash-out refinance deductible against the rental?",
 "Only the portion traced to rental use. Under Treas. Reg. Sec. 1.163-8T, interest follows the use of proceeds. Amounts used personally produce non-deductible personal interest even though a rental secures the loan. Deducting the full interest on Schedule E is a common error."),
("Can I deduct the points on a rental refinance?",
 "Not currently. Points on a rental refinance are amortized over the loan term under IRC Sec. 461(g). However, any unamortized points remaining from the loan being paid off are generally deductible in full in the year of the refinance, which is frequently missed."),
("What happens when I eventually sell a heavily refinanced property?",
 "Gain is measured against basis, not debt. After multiple refinances the taxable gain can exceed the cash you receive at closing. A 1031 exchange under IRC Sec. 1031 defers the gain entirely, and holding until death gives heirs a stepped-up basis under IRC Sec. 1014."),
],
"related": [
("/blog/interest-tracing-rules-real-estate-investors/", "Interest tracing rules explained"),
("/blog/brrrr-method-tax-strategy/", "BRRRR method tax strategy"),
("/blog/how-does-1031-exchange-work-for-rental-properties/", "How a 1031 exchange works"),
],
"cta_head": "Trace the Proceeds Before You Spend Them",
"cta_body": "The deduction on a refinance is decided by where the money goes, and it is much easier to get right in advance. Bring us your refinance plan and redeployment target.",
},

{
"slug": "land-investing-tax-strategy",
"title": "Land Investing Tax Strategy: Dealer Status, Carrying Costs, and Installment Sales",
"meta_title": "Land Investing Tax Strategy (2026 Guide) | AE Tax Advisors",
"meta_desc": "Land produces no depreciation and risks dealer classification at ordinary rates. Sec. 266 elections, 1031 treatment, and subdivision rules for 2026.",
"category": C, "date": D,
"intro": [
"Land is the only real estate asset with no depreciation. There is no building to write off, no cost segregation study to run, and no annual deduction against income while you hold.",
"That absence shifts all the tax planning to three other places: how carrying costs are handled, whether you are an investor or a dealer, and how the eventual sale is structured. The dealer question is the one that decides whether you pay 20% or 40%.",
],
"sections": [
("Dealer Versus Investor Is the Central Question", [
"An investor holding land for appreciation has a capital asset. Gain on sale is long-term capital gain, taxed at preferential rates.",
"A dealer holding land primarily for sale to customers in the ordinary course of business has inventory. Gain is ordinary income, taxed at up to 37% and subject to self-employment tax. Land held as inventory is also ineligible for 1031 exchange treatment and cannot use the installment method under IRC Sec. 453(b)(2).",
"There is no bright line. Courts weigh the frequency and substantiality of sales, the extent of development and improvement activity, marketing efforts, the purpose of acquisition, the holding period, and the taxpayer's other business activities. The factors from cases like Winthrop and Biedenharn are still the working framework.",
"The practical risk is that investors who buy raw land, subdivide it, install roads and utilities, and market lots individually look exactly like dealers, because functionally they are. Buying acreage and selling it whole after four years looks like investment.",
"Where an investor engages in both activities, separating them into different entities with different documented purposes is standard practice and generally respected. The dealer entity holds development inventory. The investor entity holds appreciation plays. Commingling them contaminates the investment holdings.",
]),
("Carrying Costs and the Section 266 Election", [
"Property taxes, interest, and other carrying charges on unimproved land produce a specific problem. Investment interest is deductible only against net investment income under IRC Sec. 163(d), and land produces no income while held. Property taxes on investment land are itemized deductions subject to the state and local tax cap.",
"For most land investors, these expenses produce little or no current benefit.",
"IRC Sec. 266 provides the answer. A taxpayer may elect to capitalize taxes, interest, and other carrying charges on unimproved and unproductive real property rather than deducting them. The election is made annually on a statement attached to the return and applies to the specific items and the specific property elected.",
"Capitalizing these amounts increases basis, which reduces capital gain at sale. Converting a deduction that produces zero current benefit into basis that reduces gain taxed at 20% plus net investment income tax is a clear improvement.",
"On a parcel held nine years with $6,800 of annual property tax and $19,000 of annual interest, that is roughly $232,000 of additional basis, worth roughly $55,000 in reduced tax at sale.",
"The election must be made each year on a timely filed return. There is no retroactive fix, which makes this one of the more consequential quiet deadlines in real estate tax.",
]),
("1031 Exchanges Work on Land", [
"Land held for investment or for productive use in a trade or business qualifies for like-kind exchange treatment under IRC Sec. 1031. Since the 2017 changes limited Sec. 1031 to real property, land remains fully eligible.",
"Land is like-kind to improved real property. An investor can exchange raw acreage into an apartment building, a retail center, or a rental house. This is one of the most useful features of land as an investment, because it allows conversion of a non-depreciating asset into a depreciating one without recognizing gain.",
"That conversion is worth emphasizing. Exchanging $900,000 of appreciated land into an improved rental produces a property with depreciable basis carried over from the land. The carryover basis is low, but the replacement property's excess basis, the amount by which the replacement property's cost exceeds the relinquished property's basis plus any boot, is depreciable on a new schedule and is eligible for a cost segregation study.",
"Dealer property is excluded from Sec. 1031, which is another reason the dealer classification matters.",
]),
("Subdivision Relief Under Section 1237", [
"IRC Sec. 1237 provides a narrow safe harbor allowing an investor to subdivide land without automatically becoming a dealer, if specific conditions are met.",
"The taxpayer must not be a dealer in real property or have held other real property primarily for sale in the year of sale, must not have made substantial improvements that substantially increase the value of the lots sold, and generally must have held the tract for five years.",
"Where it applies, gain on the first five lots sold from a tract is capital gain. Beginning with the sixth lot sold, 5% of the selling price is treated as ordinary income, with selling expenses first offsetting that ordinary portion.",
"The substantial improvement restriction is what limits Sec. 1237's usefulness. Installing roads, water, and sewer generally disqualifies the relief, and those are exactly the improvements that make lots salable. The provision works for someone splitting acreage into a handful of parcels along an existing road, not for a developer.",
]),
("Conservation Easements and Charitable Options", [
"Donating a qualified conservation easement under IRC Sec. 170(h) can produce a charitable deduction equal to the reduction in the land's fair market value from the restriction.",
"This area carries substantial IRS scrutiny. Syndicated conservation easement transactions have been listed transactions, disallowed in litigation repeatedly, and are subject to reporting requirements and significant penalties. The IRS has pursued these aggressively and continues to.",
"A genuine conservation easement on land you own, appraised properly, with real conservation purpose and a qualified organization holding it, remains a legitimate planning tool. A promoted transaction offering a four-to-one deduction ratio is not, and investors should treat those offerings as what the IRS treats them as.",
]),
("Worked Example: Long-Held Parcel", [
"An investor bought 84 acres for $290,000 in 2014, made annual Sec. 266 elections to capitalize $7,100 of property tax and $16,400 of interest each year, and sells in 2026 for $1,240,000.",
"Twelve years of capitalized carrying costs total $282,000, bringing adjusted basis to $572,000. Gain is $668,000 rather than $950,000.",
"At a combined 23.8% federal rate on long-term capital gain including net investment income tax, the capitalization election saves approximately $67,000. The deductions given up produced essentially no benefit in the years incurred, because the investor had no net investment income and was already at the SALT cap.",
"Alternatively, the investor exchanges into a $1,240,000 apartment building under IRC Sec. 1031, deferring the entire gain and converting a non-depreciating asset into one generating roughly $34,000 of annual depreciation, with a cost segregation study available on the excess basis.",
]),
],
"faqs": [
("Can I depreciate land?",
 "No. Land is not a depreciable asset because it does not have a determinable useful life. Land improvements such as grading, roads, fencing, and utilities are depreciable over 15 years, but raw land itself produces no annual deduction."),
("What is the difference between a land dealer and a land investor?",
 "An investor holds for appreciation and receives capital gain treatment. A dealer holds primarily for sale to customers, producing ordinary income subject to self-employment tax, with no 1031 exchange or installment sale available. Courts weigh sale frequency, development activity, marketing, and purpose."),
("How do I deduct property taxes and interest on vacant land?",
 "Often you should not deduct them. Under IRC Sec. 266 you may elect annually to capitalize taxes, interest, and carrying charges into basis instead. Since these deductions typically produce no current benefit on unproductive land, capitalizing them to reduce future capital gain is usually better."),
("Can I 1031 exchange raw land into a rental property?",
 "Yes. Land held for investment is like-kind to improved real property under IRC Sec. 1031. This lets you convert a non-depreciating asset into a depreciating one without recognizing gain, and the excess basis in the replacement property is eligible for a cost segregation study."),
("Does subdividing land make me a dealer?",
 "It can. IRC Sec. 1237 provides limited safe harbor relief for investors subdividing a tract held five years without substantial improvements, treating the first five lot sales as capital gain. Installing roads and utilities generally disqualifies the relief, which limits its usefulness for real development."),
],
"related": [
("/blog/how-does-1031-exchange-work-for-rental-properties/", "How a 1031 exchange works"),
("/blog/seller-financing-tax-treatment-installment-sales/", "Seller financing and installment sales"),
("/blog/qualified-opportunity-zones-real-estate-2026/", "Qualified opportunity zones"),
],
"cta_head": "The Section 266 Election Has an Annual Deadline",
"cta_body": "There is no retroactive fix for a missed capitalization election. If you hold unimproved land, bring us your carrying cost history before the next filing.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
