"""Batch: tax strategy by profession (professions not yet covered)."""

from blog_gen import write_all

C = "Tax Strategy"
D = "2026-08-10"

ARTICLES = [
{
"slug": "tax-strategy-for-chiropractors",
"title": "Tax Strategy for Chiropractors: What Changes Once the Practice Clears $400K",
"meta_title": "Tax Strategy for Chiropractors (2026 Guide) | AE Tax Advisors",
"meta_desc": "Chiropractic owners overpay through weak entity structure and unused retirement capacity. Entity, payroll, equipment, and building strategy for 2026.",
"category": C, "date": D,
"intro": [
"A chiropractic practice producing $400,000 or more in collections has a different tax problem than one producing $180,000. At the lower number, the answers are bookkeeping and an S corporation election. At the higher number, the answers involve retirement plan architecture, equipment timing, and often the building.",
"Most chiropractors we meet have the S corporation and nothing else. That is roughly a third of the available planning.",
],
"sections": [
("The S Corporation Is the Floor, Not the Plan", [
"Electing S corporation treatment splits practice profit into wages, which carry payroll tax, and distributions, which do not. On $420,000 of profit, moving from a schedule C to an S corporation with a defensible $150,000 salary saves roughly $7,800 in Medicare tax and additional Medicare tax annually. Real money, but it is the entry fee.",
"The salary number has to be defensible under the reasonable compensation standard. The IRS looks at what a comparable non-owner doctor would be paid for the same clinical duties. Setting it at $60,000 on a $420,000 practice invites reclassification, penalties, and interest. Setting it thoughtfully, documented against survey data for your region and production level, is the difference between a strategy and a target.",
"Salary also drives the qualified business income deduction under IRC Sec. 199A. Chiropractic is a specified service trade or business, so the deduction phases out above the threshold. Above the phase-out, the QBI deduction is gone entirely and the salary optimization question changes shape, because you are no longer balancing payroll tax against a QBI limitation.",
]),
("Retirement Plans Are Where the Real Deduction Lives", [
"A solo 401(k) with profit sharing allows total additions of $70,000 in 2025, plus catch-up contributions for those 50 and over. For a doctor with staff, a safe harbor 401(k) with new comparability profit sharing can direct the large majority of the employer contribution to the owner while satisfying nondiscrimination testing.",
"Above that, a cash balance plan is the tool most chiropractors have never been shown. A 52-year-old owner can often contribute $150,000 to $220,000 annually to a cash balance plan on top of the 401(k), fully deductible. On a practice producing $500,000, this can move taxable income into a completely different bracket.",
"The tradeoff is commitment. Cash balance plans require reasonably consistent funding and cover eligible staff, so the staff cost has to be modeled before adoption. For a practice with two or three employees and a high-earning owner, the ratio usually works decisively in the owner's favor.",
]),
("Equipment and Section 179 Timing", [
"Tables, decompression units, laser and shockwave equipment, digital x-ray, and rehab equipment are five-year property, fully deductible in the year placed in service under IRC Sec. 168(k) bonus depreciation or IRC Sec. 179.",
"The choice between the two matters more than most practices realize. Sec. 179 is limited to business taxable income and cannot create a loss, while bonus depreciation can. Sec. 179 is elected asset by asset, giving precise control over how much deduction to take in a year. Bonus applies to entire asset classes unless you elect out by class.",
"For a doctor whose income varies year to year, this is a real lever. Buying a $95,000 decompression and laser package in December of a high year versus January of a low year is a swing worth tens of thousands.",
]),
("The Building Is the Largest Untapped Opportunity", [
"Chiropractors who own their clinic building usually depreciate it over 39 years and stop thinking about it. A cost segregation study on a $1.2 million building typically reclassifies 20% to 30% into five-year and 15-year property, all bonus eligible.",
"The build-out inside is better still. Treatment room plumbing and electrical serving equipment, specialty flooring, casework, decorative lighting, and signage reclassify heavily, and the structural remainder of an interior build-out generally qualifies as qualified improvement property under IRC Sec. 168(e)(6) with a 15-year life and full bonus eligibility.",
"The complication is the structure. Where the building sits in a separate LLC leasing to the practice, the self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) can leave a large depreciation loss suspended in the property company rather than deductible currently. Grouping elections under Treasury Regulation Sec. 1.469-4 may solve it, but this has to be addressed before the study, not after.",
]),
("Worked Example: $520,000 Practice", [
"A 51-year-old owner runs a practice producing $520,000 of profit before owner compensation, operating as an S corporation with a $145,000 salary. Current planning is the S corporation election alone.",
"Adding a safe harbor 401(k) with new comparability profit sharing directs approximately $66,000 to the owner. A cash balance plan layered on top contributes another $178,000. Staff cost for both plans runs approximately $19,000.",
"A $110,000 equipment purchase timed into the current year adds a full deduction under Sec. 179. A cost segregation study on the $1,150,000 clinic building the owner purchased two years ago, run as a look-back with Form 3115, produces a $247,000 catch-up deduction.",
"Combined, taxable income drops by roughly $582,000 across the household and entity returns in a single year. At a combined federal and state marginal rate near 40%, that is approximately $233,000 of tax reduction, against roughly $30,000 of implementation and staff cost.",
]),
("What Usually Goes Wrong", [
"The two failures we see most often are a salary set without documentation and a retirement plan chosen by whoever sold it. A $60,000 salary on a $500,000 practice is an audit magnet. A SIMPLE IRA in a practice that could support a cash balance plan wastes six figures of annual deduction capacity.",
"The third failure is sequencing. Buying equipment in a low income year, or running a cost segregation study in a year with no income to offset, converts a valuable deduction into a suspended one. The plan should run on a multi-year calendar, not a December scramble.",
]),
],
"faqs": [
("What is a reasonable salary for a chiropractor S corporation owner?",
 "It depends on region, production, and clinical duties, but the standard is what a comparable non-owner doctor would be paid for the same work. On a $450,000 practice, salaries in the $130,000 to $170,000 range are commonly defensible. The number should be documented against compensation survey data, not chosen for convenience."),
("Can a chiropractor use the QBI deduction?",
 "Chiropractic is a specified service trade or business under IRC Sec. 199A, so the deduction phases out above the income threshold and disappears entirely above the phase-out range. Below the threshold it is fully available. This is one reason salary optimization looks different at different income levels."),
("How much can a chiropractor contribute to retirement plans?",
 "A solo or safe harbor 401(k) with profit sharing allows total additions of $70,000 in 2025, plus catch-up amounts at 50 and over. Layering a cash balance plan on top can add $150,000 to $220,000 annually for an owner in their early fifties, all deductible."),
("Should I use Section 179 or bonus depreciation on equipment?",
 "Sec. 179 gives asset-by-asset control and cannot create a loss. Bonus depreciation applies by asset class and can create a loss. For a practice with variable income, Sec. 179 usually offers better precision, while bonus is simpler when you want the full deduction regardless."),
("Is a cost segregation study worth it on a small clinic building?",
 "Usually yes above roughly $700,000 of depreciable basis. A typical clinic reclassifies 20% to 30%, and the interior build-out reclassifies far higher. The larger question is whether a self-rental structure will let you use the deduction currently, which should be resolved first."),
],
"related": [
("/blog/cash-balance-plans-business-owners-2026/", "Cash balance plans for business owners"),
("/blog/reasonable-compensation-s-corp-analysis/", "Reasonable compensation analysis for S corp owners"),
("/blog/self-rental-rules-business-rents-from-you/", "Self-rental rules when your business rents from you"),
],
"cta_head": "Model It Before December",
"cta_body": "Bring your P&L, your current salary, your plan documents, and any building you own. We will map the full stack and tell you what each layer is worth in your specific situation.",
},

{
"slug": "tax-strategy-for-veterinary-practice-owners",
"title": "Tax Strategy for Veterinary Practice Owners: Equipment, Entities, and the Exit",
"meta_title": "Tax Strategy for Veterinary Practice Owners (2026) | AE Tax Advisors",
"meta_desc": "Veterinary owners face consolidator buyouts, heavy equipment cycles, and QBI limits. Entity, retirement, and exit planning strategy for 2026.",
"category": C, "date": D,
"intro": [
"Veterinary practice ownership has changed. Consolidator acquisition activity means many owners are now planning toward a sale rather than a career-long hold, and that changes which strategies are worth implementing and which create problems at exit.",
"At the same time, veterinary practices are capital intensive in a way most professional services are not. Imaging, surgical equipment, and hospital build-out create recurring deduction opportunities that a law or accounting practice simply does not have.",
],
"sections": [
("Entity Structure With an Exit in Mind", [
"An S corporation is the default for a practice generating meaningful profit, and for good reason. It splits profit into wages and distributions, reducing payroll tax on the distribution portion.",
"But S corporation status shapes the exit. Most consolidator transactions are structured as asset sales, and in an asset sale the gain is allocated across asset classes under IRC Sec. 1060. Goodwill receives capital gain treatment. Equipment previously expensed generates ordinary income recapture. Non-compete allocations are ordinary income and, worse, are taxed to the individual while being amortized by the buyer over 15 years.",
"The allocation is negotiated, and it is worth real money. Shifting $400,000 of purchase price from a non-compete allocation to goodwill can change the tax bill by roughly $80,000. Most sellers negotiate price hard and allocation not at all.",
"C corporation practices face a different problem. An asset sale from a C corporation produces two levels of tax, and buyers generally will not do a stock purchase. Practices still sitting in C corporation form should model the conversion and the five-year built-in gains period under IRC Sec. 1374 well before a sale is contemplated.",
]),
("Equipment Cycles and Deduction Timing", [
"Digital radiography, ultrasound, CT, surgical lasers, monitoring equipment, and dental units are five-year property, fully deductible in the placed-in-service year under IRC Sec. 168(k) or IRC Sec. 179.",
"Financing does not change the deduction. A practice that finances a $180,000 CT unit with 10% down still deducts the full $180,000 in year one, because the deduction follows the placed-in-service date rather than cash outlay. This is one of the most under-used positions in practice finance, and it means equipment purchases can be timed against income rather than against cash availability.",
"Leases require more care. A capital lease is treated as a purchase and produces the same deduction. A true operating lease produces a rent deduction spread over the term. Which one you have depends on the lease terms, not on what the vendor calls it.",
]),
("Retirement Plan Architecture", [
"A safe harbor 401(k) with new comparability profit sharing is the baseline for a practice with staff. Correctly designed, it directs the large majority of employer contributions to owners and senior doctors while passing nondiscrimination testing.",
"For owners over 45 with strong profit, a cash balance plan adds $120,000 to $250,000 of annual deductible contribution depending on age and compensation. In a practice with several associate veterinarians, the plan design gets more complex, and the staff cost has to be modeled rather than assumed.",
"There is an exit interaction here as well. Retirement plan assets are not part of the practice sale and are protected from creditors under federal law in most cases. For an owner five years out from a sale, aggressively funding a cash balance plan converts practice profit that would otherwise be taxed at ordinary rates into protected, tax-deferred assets.",
]),
("The Real Estate Question", [
"Owners who hold their hospital real estate have two assets and should treat them as such. A cost segregation study on the building typically reclassifies 20% to 30% of depreciable basis, and the hospital build-out inside reclassifies 35% to 50%.",
"At exit, this becomes more important. Consolidators generally buy the practice and lease the building, often on a long-term triple net lease. That converts the real estate into an income-producing asset with a national credit tenant, frequently worth more than the practice itself. Owners who sold the building along with the practice because nobody separated the two have given away the better asset.",
"The self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) apply while you operate the practice. Once you sell the practice and lease to an unrelated operator, the property becomes ordinary passive rental real estate, and suspended losses from the cost segregation study may free up as passive income appears.",
]),
("Worked Example: Three-Doctor Hospital", [
"A 49-year-old owner runs a hospital producing $760,000 of profit before owner compensation, with two associate veterinarians and 14 staff. The practice is an S corporation with a $210,000 owner salary. The owner also owns the $1,900,000 building through a separate LLC.",
"Adding a safe harbor 401(k) with new comparability profit sharing directs approximately $69,000 to the owner. A cash balance plan adds $164,000. Combined staff cost across both plans runs approximately $41,000.",
"A $310,000 CT and imaging package placed in service in the current year is fully deductible. A cost segregation study on the building, run as a look-back with Form 3115 and paired with a grouping election under Treasury Regulation Sec. 1.469-4, produces a $412,000 catch-up deduction that is usable currently rather than suspended.",
"The combined reduction in taxable income exceeds $950,000 in a single year, worth roughly $380,000 at a 40% combined marginal rate.",
]),
("What to Fix Before a Sale Conversation", [
"Clean books are the first item. Consolidators normalize earnings, and personal expenses run through the practice reduce the multiple applied to EBITDA far more than they ever saved in tax. A $40,000 personal expense habit can cost $280,000 of enterprise value at a 7x multiple.",
"Second, separate the real estate ownership formally if it is not already. Third, resolve any C corporation exposure. Fourth, model the purchase price allocation before the letter of intent, because allocation is far easier to negotiate before price is agreed than after.",
]),
],
"faqs": [
("How does purchase price allocation affect a veterinary practice sale?",
 "Under IRC Sec. 1060, the price is allocated across asset classes and each class is taxed differently. Goodwill is capital gain. Equipment produces ordinary recapture. Non-compete allocations are ordinary income to the seller. Shifting allocation between these classes can change the tax bill by six figures on a mid-size practice."),
("Should I keep my hospital real estate when I sell the practice?",
 "Usually yes. Consolidators typically buy the practice and lease the building on a long-term basis, which converts your real estate into an income property with a strong credit tenant. That asset is frequently worth more than the practice. Selling both together is a common and expensive mistake."),
("Can I deduct financed equipment in full?",
 "Yes. Depreciation follows the placed-in-service date, not the cash outlay. A $180,000 imaging unit financed with 10% down is fully deductible in the year it is placed in service under IRC Sec. 168(k) or Sec. 179, subject to the taxable income limit for Sec. 179."),
("What retirement plan works best for a multi-doctor practice?",
 "A safe harbor 401(k) with new comparability profit sharing as the base, and a cash balance plan layered on for owners over 45 with strong profit. Combined, this can direct $200,000 to $320,000 of annual deductible contribution to an owner, though staff cost must be modeled first."),
("My practice is still a C corporation. Is that a problem?",
 "For an eventual sale, yes. An asset sale from a C corporation produces two levels of tax, and buyers rarely accept stock purchases. Conversion to S corporation status starts a five-year built-in gains period under IRC Sec. 1374, so this should be addressed years before a sale, not during one."),
],
"related": [
("/blog/cost-segregation-veterinary-clinics/", "Cost segregation for veterinary clinics"),
("/blog/purchase-price-allocation-optimization-business-sale/", "Purchase price allocation in a business sale"),
("/blog/cash-balance-plans-business-owners-2026/", "Cash balance plans for business owners"),
],
"cta_head": "Plan the Exit Before the Broker Calls",
"cta_body": "Most of the value in veterinary tax planning is decided years before the sale. Bring your P&L, entity documents, and real estate detail and we will map the timeline.",
},

{
"slug": "tax-strategy-for-med-spa-owners",
"title": "Tax Strategy for Med Spa Owners: Equipment Cycles, Entity Structure, and QBI",
"meta_title": "Tax Strategy for Med Spa Owners (2026 Guide) | AE Tax Advisors",
"meta_desc": "Med spas carry heavy device costs and mixed service revenue. Entity structure, equipment timing, QBI treatment, and build-out strategy for 2026.",
"category": C, "date": D,
"intro": [
"Med spas sit at an unusual intersection. They carry equipment loads closer to a surgical practice than a salon, they often mix medical services with retail product sales, and the ownership structure is frequently constrained by state corporate practice of medicine rules.",
"Each of those facts creates a planning opportunity, and each is routinely handled badly by preparers who treat the business as a generic service company.",
],
"sections": [
("Devices Are the Largest Deduction Lever", [
"Laser platforms, IPL, RF microneedling, body contouring devices, injection and infusion equipment, treatment chairs, and imaging systems are five-year property, fully deductible in the placed-in-service year under IRC Sec. 168(k) bonus depreciation or IRC Sec. 179.",
"Med spas replace and add devices constantly, which makes this a recurring rather than one-time planning item. A practice adding $200,000 to $400,000 of device capacity every other year has a deduction stream that should be timed deliberately against income.",
"Financing does not reduce the deduction. A device placed in service in December with 10% down is fully deductible that year. This decouples the deduction from cash availability entirely and is the single most useful fact in med spa tax planning.",
"Where devices are acquired under a true operating lease rather than a capital lease or financed purchase, the treatment changes to a rent deduction spread over the term. Vendor language is not determinative. The lease terms decide it, and they should be reviewed before signing, not at tax time.",
]),
("Entity Structure and the Corporate Practice of Medicine", [
"Many states require that a medical practice be owned by licensed practitioners. A non-physician owner in those states typically operates through a management services organization that contracts with a professional entity owned by a physician or nurse practitioner.",
"The MSO structure is a legal requirement first, but it has tax consequences. Revenue splits between the professional entity and the MSO determine where profit lands, which entity is a specified service trade or business for QIP purposes, and how much of the income is eligible for the qualified business income deduction under IRC Sec. 199A.",
"Medical services are a specified service trade or business, which phases out the QBI deduction above the income threshold. Management services, retail product sales, and certain non-medical aesthetic services may not be. Where the structure genuinely separates these activities with real substance, a meaningful portion of the income can retain QBI eligibility. Where the separation is cosmetic, it will not hold up.",
]),
("Retail Product Revenue Is a Separate Business", [
"Med spas commonly sell $150,000 to $500,000 of skincare and product annually. This is inventory-based retail, subject to inventory accounting rules, sales tax collection, and a different QBI analysis than the medical services.",
"Practices frequently commingle this into one P&L and lose track of it. Separating product revenue and its cost of goods sold does three things: it clarifies whether the retail line is actually profitable, it supports a defensible QBI position, and it makes the business easier to value at sale.",
]),
("Build-Out and Real Estate", [
"Med spa build-outs reclassify heavily, generally 35% to 50% of construction cost. Treatment room plumbing and dedicated electrical serving devices, specialty lighting, casework and millwork, decorative finishes, sound masking, and retail display fixtures are all five-year property.",
"The structural remainder of an interior build-out in leased space generally qualifies as qualified improvement property under IRC Sec. 168(e)(6), carrying a 15-year life with full bonus eligibility. Between the two, a $700,000 build-out is often close to fully deductible in the opening year.",
"Owners who also own the building have a second study available on the shell, typically reclassifying 20% to 30%. The self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) govern how that loss can be used, so the structure should be reviewed before commissioning the study.",
]),
("Retirement Plans Scale With Profit", [
"A safe harbor 401(k) with profit sharing is the base layer, allowing total additions of $70,000 in 2025 plus catch-up amounts. For an owner over 45 running a practice with $600,000 or more of profit, a cash balance plan adds $130,000 to $220,000 of annual deductible contribution.",
"Med spas typically carry a larger staff than a comparable-revenue medical practice, so the staff cost of these plans is higher and needs modeling. In a practice with 12 employees and one high-earning owner, the ratio usually still works, but it is not automatic the way it is in a two-person office.",
]),
("Worked Example: $1.4M Revenue Med Spa", [
"A 47-year-old owner operates a med spa with $1,400,000 of revenue and $470,000 of profit before owner compensation, structured as an S corporation with a $165,000 salary and nine employees.",
"A $285,000 device purchase placed in service in the current year is fully deductible under Sec. 179, financed at 10% down. A safe harbor 401(k) with new comparability directs approximately $63,000 to the owner at roughly $16,000 of staff cost.",
"A look-back cost segregation study on the $840,000 build-out completed three years ago, filed with Form 3115, produces a $304,000 catch-up deduction in the current year.",
"Taxable income falls by roughly $652,000, worth approximately $261,000 at a 40% combined marginal rate, on roughly $45,000 of cash outlay between the equipment down payment, staff plan cost, and professional fees.",
]),
],
"faqs": [
("Can a non-physician own a med spa?",
 "It depends on state corporate practice of medicine rules. Many states require the professional entity to be owned by a licensed practitioner, with a non-physician owner operating through a management services organization that contracts with it. The structure is a legal question first, but it drives the tax outcome."),
("Do med spas qualify for the QBI deduction?",
 "Medical services are a specified service trade or business under IRC Sec. 199A, so the deduction phases out above the income threshold. Retail product sales and management services may not be. Where the structure genuinely separates activities with real substance, part of the income can retain QBI eligibility."),
("Can I deduct a financed laser in full?",
 "Yes. Depreciation follows the placed-in-service date, not cash paid. A device placed in service in December with 10% down is fully deductible that year under IRC Sec. 168(k) or Sec. 179, subject to the taxable income limit for Sec. 179."),
("How much of a med spa build-out is deductible in year one?",
 "Typically 35% to 50% reclassifies to five-year personal property, and most of the remainder qualifies as 15-year QIP under IRC Sec. 168(e)(6) with full bonus eligibility. Between the two, a leasehold build-out is often close to fully deductible in the opening year."),
("Is device leasing better than buying for tax purposes?",
 "Usually not. A financed purchase or capital lease produces the full deduction in year one. A true operating lease spreads the deduction over the term. Vendor terminology does not control the treatment, so the lease document should be reviewed before signing."),
],
"related": [
("/blog/section-179-deduction-2026-complete-guide/", "Section 179 complete guide"),
("/blog/equipment-leasing-vs-buying-tax-comparison/", "Equipment leasing versus buying"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization under IRC Sec. 199A"),
],
"cta_head": "Device Timing Alone Is Worth a Conversation",
"cta_body": "Bring your P&L, your device purchase plans for the next 18 months, and your build-out detail. We will map the deduction against your income year by year.",
},

{
"slug": "tax-strategy-for-real-estate-agents",
"title": "Tax Strategy for Real Estate Agents: From Schedule C to a Real Structure",
"meta_title": "Tax Strategy for Real Estate Agents (2026 Guide) | AE Tax Advisors",
"meta_desc": "Top producing agents overpay through schedule C filing and missed REPS. Entity, retirement, vehicle, and real estate professional strategy for 2026.",
"category": C, "date": D,
"intro": [
"A real estate agent earning $180,000 in commissions on a schedule C is paying self-employment tax on every dollar of profit. That is roughly $25,000 before a single dollar of income tax.",
"Agents also sit on an advantage almost nobody else has. The real estate professional status rules under IRC Sec. 469(c)(7) were written for people in real property trades or businesses, and a licensed full-time agent is the archetype. Most agents never use it.",
],
"sections": [
("The S Corporation Election Is Usually Overdue", [
"An agent netting $180,000 on a schedule C pays self-employment tax of approximately $25,400. The same agent as an S corporation paying a $95,000 salary pays payroll tax on the salary only, saving roughly $12,000 annually.",
"The salary has to be reasonable. For an agent, the analysis looks at what a comparable licensed producer would earn for the same production, and it should account for the fact that the agent personally generates the revenue. Salaries in the 50% to 60% range of net profit are commonly defensible for a solo producer. Agents running a team with support staff and lead generation systems that produce revenue independently can often justify a lower percentage.",
"The S corporation also creates the payroll infrastructure needed for a retirement plan with employer contributions, which is where the larger money is.",
"There is a real estate specific complication. Some brokerages will only pay commissions to a licensed individual, not to an entity. Many states allow payment to a licensed professional entity, but the rules vary and the brokerage's policy matters as much as the statute. This should be confirmed before the election, not after.",
]),
("Real Estate Professional Status Is the Bigger Prize", [
"An agent who materially participates in real property trades or businesses for more than 750 hours annually, and for more than half of all personal service time, qualifies as a real estate professional under IRC Sec. 469(c)(7).",
"For a full-time agent, both tests are met by the day job. The status does not by itself make rental losses deductible. It removes rental real estate from the automatic passive classification, after which each rental activity must still pass material participation individually, or be grouped through an election under Treasury Regulation Sec. 1.469-9(g).",
"The result is that an agent who owns rental property and makes the aggregation election can use rental depreciation, including large cost segregation deductions, against commission income directly. An agent netting $220,000 who buys a $600,000 rental and runs a cost segregation study can often shelter $130,000 or more of commission income in year one.",
"Hour documentation is the weak point. The IRS challenges REPS claims regularly and contemporaneous logs win these cases. Reconstructed calendars lose them. An agent claiming this status needs a real log, kept as the year goes, tied to MLS activity, showings, closings, and marketing time.",
]),
("Vehicle, Home Office, and the Ordinary Deductions", [
"Agents drive. The standard mileage rate is simpler, but for an agent driving 22,000 business miles in a vehicle with high operating cost, actual expenses plus depreciation frequently produce a larger deduction. The choice is locked for the life of the vehicle if you start with actual expenses, so it should be modeled at purchase.",
"Vehicles over 6,000 pounds gross vehicle weight rating are not subject to the luxury auto depreciation caps under IRC Sec. 280F, which is why they appear so often in agent tax planning. The business use percentage still has to be real and documented.",
"Home office through an S corporation should run through an accountable plan reimbursement rather than a deduction on the personal return, since unreimbursed employee expenses are not deductible. The reimbursement is deductible to the corporation and not income to the agent.",
]),
("Retirement Plans for Variable Income", [
"Commission income is lumpy, which makes plan selection different than for a salaried professional. A solo 401(k) allows total additions of $70,000 in 2025 plus catch-up, and critically, the employer profit sharing portion is discretionary year to year. In a strong year you fund it fully. In a weak year you fund nothing.",
"That flexibility makes the solo 401(k) a better fit than a SEP IRA for most agents, despite similar limits, because the employee deferral portion can be funded early in the year and the employer portion decided at tax filing.",
"Agents with consistently high income and no employees should look at a cash balance plan. A 50-year-old agent netting $400,000 can often add $150,000 or more of annual deductible contribution on top of the 401(k).",
]),
("Worked Example: $310,000 Producer", [
"A 46-year-old agent nets $310,000 on a schedule C, owns two rentals, and has no entity or retirement plan.",
"Electing S corporation status with a $150,000 salary saves approximately $13,900 in self-employment tax. A solo 401(k) with profit sharing contributes $70,000, deductible.",
"The agent qualifies as a real estate professional based on full-time brokerage activity, makes the aggregation election under Treasury Regulation Sec. 1.469-9(g), and runs cost segregation studies on both rentals, producing $186,000 of deductions now usable against commission income rather than suspended.",
"Total taxable income reduction of roughly $256,000, plus the payroll tax savings, produces approximately $115,000 of combined federal and state tax reduction in the first year.",
]),
],
"faqs": [
("When should a real estate agent elect S corporation status?",
 "Generally once net profit consistently exceeds roughly $80,000 to $100,000, where the self-employment tax savings clearly exceed the added payroll and compliance cost. Confirm first that your brokerage will pay commissions to an entity, since some will not."),
("Do real estate agents automatically qualify as real estate professionals?",
 "A full-time licensed agent generally meets the 750-hour and more-than-half tests under IRC Sec. 469(c)(7) through brokerage work alone. But the status alone does not make rental losses deductible. Each rental must still pass material participation, or you must make the aggregation election under Treas. Reg. Sec. 1.469-9(g)."),
("What documentation do I need for real estate professional status?",
 "A contemporaneous time log kept during the year, tied to verifiable activity such as MLS entries, showings, closings, and marketing. Reconstructed calendars prepared after an audit notice consistently lose. This is the most commonly challenged position an agent takes."),
("Is a vehicle over 6,000 pounds actually better for taxes?",
 "It avoids the luxury auto depreciation caps under IRC Sec. 280F, which can allow a much larger first-year deduction. But business use percentage must be real and documented, and the vehicle still has to make sense operationally. The tax benefit should not drive the purchase by itself."),
("What retirement plan works best for commission income?",
 "A solo 401(k) is generally the best fit because the employer profit sharing portion is discretionary, letting you fund heavily in strong years and lightly in weak ones. Agents with consistently high income should also evaluate a cash balance plan layered on top."),
],
"related": [
("/blog/real-estate-professional-status-qualification-guide/", "Real estate professional status qualification guide"),
("/blog/material-participation-hours-tracking-template/", "Material participation hours tracking"),
("/blog/how-to-write-off-a-vehicle-through-your-business/", "Writing off a vehicle through your business"),
],
"cta_head": "Agents Have an Advantage Most Never Use",
"cta_body": "If you are licensed, working full time, and own rental property, the real estate professional election may be the largest single item on your return. Bring your production numbers and your rental schedule.",
},

{
"slug": "tax-strategy-for-insurance-agency-owners",
"title": "Tax Strategy for Insurance Agency Owners: Renewals, Entity Design, and the Book Sale",
"meta_title": "Tax Strategy for Insurance Agency Owners (2026) | AE Tax Advisors",
"meta_desc": "Agency owners face QBI limits, renewal income timing, and book sale allocation. Entity, retirement, and exit tax strategy for insurance agencies in 2026.",
"category": C, "date": D,
"intro": [
"An insurance agency is a recurring revenue business with a predictable exit, which makes it one of the more plannable businesses in professional services. The renewal book has value, the value is measurable, and the sale is largely a question of allocation.",
"That predictability is exactly why the planning should start early. Most of what determines the tax bill on a book sale is decided years before the sale happens.",
],
"sections": [
("Entity Structure and the QBI Question", [
"Insurance agencies are generally not specified service trades or businesses under IRC Sec. 199A. This is an important and frequently misunderstood point. Insurance brokerage is not listed among the excluded fields, and the regulations under Treasury Regulation Sec. 1.199A-5 do not treat it as one.",
"That means an agency owner may claim the full 20% qualified business income deduction even at high income levels, subject only to the wage and property limitations rather than the SSTB phase-out. On $600,000 of qualified business income, that is a $120,000 deduction that a physician or attorney at the same income level cannot claim.",
"Above the income threshold, the deduction is limited to the greater of 50% of W-2 wages or 25% of wages plus 2.5% of unadjusted basis in qualified property. This creates a genuine tension with S corporation salary minimization. Setting salary too low can cost more in lost QBI deduction than it saves in payroll tax. The optimum has to be calculated, not assumed, and it moves each year with income.",
]),
("Renewal Income and Timing", [
"Agencies on the cash method have real control over the timing of income recognition. Commission received in January versus December shifts a full year of tax. For an owner with an unusual income year, whether from a large contingency payment, a book acquisition, or a personal event, accelerating or deferring renewals is a legitimate and underused lever.",
"Contingency and profit sharing payments from carriers are the most volatile line in most agency P&Ls and often arrive in the first quarter for the prior year. Owners should plan for the timing rather than being surprised by it, particularly where the payment pushes income across a threshold that affects QBI, Medicare surtax, or retirement plan design.",
]),
("Book Acquisitions Create Amortization", [
"When an agency buys another agency's book, the purchase price allocated to customer relationships and goodwill is amortized over 15 years under IRC Sec. 197. On a $1,200,000 book purchase, that is $80,000 of annual deduction for 15 years.",
"The allocation between goodwill, customer lists, non-compete agreements, and any tangible assets matters. All Sec. 197 intangibles amortize over 15 years regardless of category, so the allocation among them is less consequential than in other industries. What matters is the split between Sec. 197 intangibles and anything that might be expensed faster, and the seller's tax treatment, which affects negotiation.",
"Financing the acquisition does not change the amortization. The deduction follows the purchase, not the payment schedule, which means a leveraged book acquisition produces a deduction stream substantially larger than the cash cost in the early years.",
]),
("Retirement Plans Fit Agencies Well", [
"Agencies typically have modest headcount relative to owner profit, which is the ideal profile for aggressive retirement plan design. A safe harbor 401(k) with new comparability profit sharing directs the majority of employer contributions to the owner.",
"A cash balance plan layered on top can add $130,000 to $240,000 annually for an owner over 45. For an agency with six employees and a single high-earning owner, the staff cost of the combined plans is often under $30,000 against $250,000 or more of owner contribution.",
"This also interacts with the QBI wage limitation favorably. Employer retirement contributions are not W-2 wages, so they reduce qualified business income without increasing the wage base. The interaction should be modeled together rather than optimizing each in isolation.",
]),
("Selling the Book", [
"Most agency sales are asset sales. Under IRC Sec. 1060, the price is allocated across asset classes. Goodwill and customer relationships produce capital gain to the seller. Non-compete allocations produce ordinary income. Consulting or transition service agreements produce ordinary income and self-employment tax.",
"Buyers often prefer allocating to a non-compete or consulting agreement because the treatment on their side is similar while the seller absorbs a materially worse rate. On a $2,000,000 sale, moving $400,000 from goodwill to a consulting agreement costs the seller roughly $110,000. This is negotiated in the purchase agreement, and it is far easier to negotiate before price is agreed than after.",
"Sellers should also model an installment sale under IRC Sec. 453. Agency sales frequently include earnouts tied to retention, which are naturally installment obligations, and spreading gain across years can keep the seller below thresholds that trigger additional rates.",
]),
("Worked Example: $900,000 Profit Agency", [
"A 50-year-old owner runs an agency with $900,000 of profit before owner compensation, seven employees, and an S corporation structure with a $220,000 salary.",
"Salary is modeled against the QBI wage limitation and increased to $290,000, which costs approximately $8,100 in additional payroll tax but preserves roughly $47,000 of QBI deduction that would otherwise be limited.",
"A safe harbor 401(k) with new comparability directs $70,000 to the owner. A cash balance plan adds $196,000. Staff cost across both is approximately $28,000.",
"A $950,000 book acquisition completed during the year begins generating $63,300 of annual Sec. 197 amortization.",
"Combined, taxable income falls by roughly $376,000 in the first year with a recurring $63,300 amortization stream for 15 years, while the QBI position improves rather than degrades.",
]),
],
"faqs": [
("Do insurance agencies qualify for the QBI deduction?",
 "Generally yes. Insurance brokerage is not a specified service trade or business under IRC Sec. 199A, so the deduction is available even at high income, subject to the wage and property limitations rather than the SSTB phase-out. This is a significant advantage over most professional services."),
("Should I lower my S corporation salary to save payroll tax?",
 "Not automatically. Above the QBI income threshold, the deduction is limited by W-2 wages, so cutting salary can cost more in lost QBI deduction than it saves in payroll tax. The optimum salary should be calculated each year against both effects together."),
("How is a book of business purchase deducted?",
 "Amounts allocated to goodwill, customer relationships, and non-compete agreements are Sec. 197 intangibles amortized over 15 years. A $1,200,000 book produces $80,000 of annual deduction. Financing does not change this, so a leveraged acquisition generates deductions well ahead of cash cost."),
("How is a book sale taxed?",
 "Under IRC Sec. 1060, price is allocated across asset classes. Goodwill and customer relationships are capital gain. Non-compete and consulting agreements are ordinary income and can carry self-employment tax. The allocation is negotiated and is worth six figures on a mid-size agency."),
("Can I spread the tax on a book sale over multiple years?",
 "Often yes, through an installment sale under IRC Sec. 453. Agency sales commonly include retention-based earnouts that are naturally installment obligations. Spreading gain can keep you below thresholds that trigger higher rates and additional Medicare tax."),
],
"related": [
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
("/blog/purchase-price-allocation-optimization-business-sale/", "Purchase price allocation in a business sale"),
("/blog/non-compete-allocation-tax-treatment/", "Non-compete allocation tax treatment"),
],
"cta_head": "The Book Sale Is Decided Years in Advance",
"cta_body": "Salary optimization, plan design, and acquisition structure all compound. Bring your P&L, entity documents, and any acquisition or sale you are contemplating.",
},

{
"slug": "tax-strategy-for-financial-advisors",
"title": "Tax Strategy for Financial Advisors: The SSTB Problem and What Works Around It",
"meta_title": "Tax Strategy for Financial Advisors (2026 Guide) | AE Tax Advisors",
"meta_desc": "Advisory firms are specified service businesses, losing the QBI deduction at high income. Entity, retirement, and real estate strategy for advisors in 2026.",
"category": C, "date": D,
"intro": [
"Financial advisors face a specific structural disadvantage. Investment advisory and wealth management are explicitly specified service trades or businesses under IRC Sec. 199A, which means the 20% qualified business income deduction disappears entirely above the phase-out range.",
"For an advisor with $700,000 of firm profit, that is a $140,000 deduction that an insurance agency or a manufacturer at the same income level receives and the advisor does not. Everything else in the plan has to work harder to compensate.",
],
"sections": [
("Where the SSTB Line Actually Falls", [
"Treasury Regulation Sec. 1.199A-5 defines the field of financial services to include investment advisory services, wealth management, and advisory services relating to valuations, mergers, and acquisitions. Brokerage services are separately listed and also excluded.",
"What is not automatically an SSTB is worth knowing. Insurance brokerage is not. Third-party administration is not. Real estate brokerage is not. Where an advisory firm genuinely operates a separate line of business that falls outside the excluded fields, with its own economics, staff, and client relationships, that line may retain QBI eligibility.",
"The de minimis and anti-abuse rules under Treasury Regulation Sec. 1.199A-5(c) limit how far this can be pushed. A separated business that shares all its staff and overhead with the advisory practice and exists only on paper will be collapsed back. A genuinely operated insurance agency with its own producers and revenue is a different fact pattern. The distinction is substance, and it needs to be built rather than asserted.",
]),
("Retirement Plans Carry More Weight Here", [
"Without the QBI deduction, retirement plan capacity becomes the largest available deduction. Advisors should generally be running the most aggressive plan design their staff economics support.",
"A safe harbor 401(k) with new comparability profit sharing is the base. For advisors over 45, a cash balance plan adds $140,000 to $250,000 of annual deductible contribution depending on age and compensation. An advisor at 55 with $900,000 of profit can often contribute over $300,000 across both plans.",
"Advisory firms typically have favorable demographics for this design, with a small number of high-earning owners and a modest support staff. The staff cost is frequently under 12% of the owner benefit, which is among the best ratios in professional services.",
"There is a credibility dimension as well. An advisor recommending retirement plans to business owner clients while running a SIMPLE IRA is a weak position. The plan is both a tax strategy and a demonstration.",
]),
("Entity Structure and Salary", [
"Because the QBI deduction is unavailable above the phase-out, the salary optimization calculus is simpler than for a non-SSTB business. There is no wage limitation to preserve, so the analysis is purely payroll tax against reasonable compensation risk.",
"The reasonable compensation standard still governs. For an advisor personally producing the revenue, salary in the 50% to 65% range of net profit is commonly defensible. Firms with a genuine enterprise, meaning multiple advisors, a service team, and revenue that does not depend entirely on the owner, can generally justify a lower percentage because the profit is partly a return on the business rather than on personal services.",
"Multi-owner firms should also review whether the operating agreement's compensation and distribution provisions actually match what happens in practice. Mismatches here create partnership allocation problems that surface at the worst possible time, usually during a succession event.",
]),
("Real Estate Is the Most Common Answer", [
"Advisors with high ordinary income and no QBI deduction frequently turn to real estate, and the mechanics are worth understanding rather than assuming.",
"Ordinary rental real estate produces passive losses under IRC Sec. 469 that cannot offset advisory income unless the advisor qualifies as a real estate professional. An advisor working full time in advisory will not meet the more-than-half test in IRC Sec. 469(c)(7). This is the wall most advisors hit.",
"Short-term rentals are the exception. Under Treasury Regulation Sec. 1.469-1T(e)(3)(ii)(A), a property with an average customer use period of seven days or less is not a rental activity. The advisor then only needs to materially participate under Treasury Regulation Sec. 1.469-5T, which the 100-hour and substantially-all test can reach for an owner who self-manages.",
"Paired with a cost segregation study, this is the mechanism that lets a $700,000-income advisor shelter $150,000 or more of ordinary income with a single property. The hour documentation requirements are strict and the participation must be real, but the structure is well established.",
]),
("Worked Example: $840,000 Advisory Firm", [
"A 52-year-old advisor runs a firm with $840,000 of profit before owner compensation, five employees, structured as an S corporation with a $340,000 salary. Income is far above the SSTB phase-out, so no QBI deduction is available.",
"A safe harbor 401(k) with new comparability directs $70,000 to the owner. A cash balance plan adds $211,000. Staff cost across both plans is approximately $31,000.",
"The advisor acquires a $940,000 short-term rental, self-manages it, documents 142 hours of material participation with no other person exceeding that, and runs a cost segregation study reclassifying 29% of depreciable basis. The resulting first-year deduction of $238,000 is non-passive and offsets advisory income.",
"Combined taxable income reduction of approximately $519,000 produces roughly $218,000 of federal and state tax reduction, in a year where the QBI deduction contributed nothing.",
]),
("Succession and Equity Transfers", [
"Advisory firms transfer through internal succession more often than external sale. The tax structure of that transfer matters enormously and is usually addressed too late.",
"A sale of S corporation stock to a junior partner produces capital gain to the seller and no deduction to the buyer, who must fund the purchase with after-tax dollars. An asset sale produces a Sec. 197 amortization stream for the buyer but ordinary recapture exposure for the seller. Structured properly over several years with a combination of equity transfer and compensation adjustment, the total tax cost of the transition can be reduced substantially.",
"This planning takes three to five years to execute well. Firms that start it in the year the senior partner wants to retire have already lost most of the available benefit.",
]),
],
"faqs": [
("Are financial advisors excluded from the QBI deduction?",
 "Above the income phase-out, yes. Investment advisory, wealth management, and brokerage services are specified service trades or businesses under IRC Sec. 199A and Treas. Reg. Sec. 1.199A-5. Below the threshold the deduction is fully available, and it phases out across the range."),
("Can I separate part of my firm to preserve QBI eligibility?",
 "Only where the separated line is a genuine business outside the excluded fields, with its own economics, staff, and clients. Insurance brokerage and third-party administration are not SSTBs. The anti-abuse rules in Treas. Reg. Sec. 1.199A-5(c) will collapse a separation that exists only on paper."),
("What is the largest deduction available to an advisory firm owner?",
 "Usually retirement plan contributions. A safe harbor 401(k) with new comparability profit sharing plus a cash balance plan can direct $250,000 to $320,000 annually to an owner over 50, at staff cost that is typically under 12% of the owner benefit in a small advisory firm."),
("Can I qualify as a real estate professional while running an advisory firm?",
 "Almost certainly not. IRC Sec. 469(c)(7) requires more than half of all personal service time in real property trades or businesses, and a full-time advisor cannot meet that. Short-term rentals under the seven-day rule are the usual alternative, since they avoid the rental activity classification entirely."),
("How should I plan an internal succession?",
 "Start three to five years out. The structure of the equity transfer, whether stock or assets, whether funded with compensation adjustments or purchase notes, drives the total tax cost for both parties. Deals structured in the year of retirement leave most of the available benefit unclaimed."),
],
"related": [
("/blog/str-loophole-7-day-rule-explained/", "The short-term rental seven-day rule"),
("/blog/cash-balance-plans-business-owners-2026/", "Cash balance plans for business owners"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
],
"cta_head": "You Advise on This. Get It Done for Yourself.",
"cta_body": "Most advisory firm owners have a weaker plan than their clients do. Bring your P&L, plan documents, and entity structure and we will model the full stack.",
},

{
"slug": "tax-strategy-for-hvac-plumbing-contractors",
"title": "Tax Strategy for HVAC and Plumbing Contractors: Fleet, Inventory, and the Yard",
"meta_title": "Tax Strategy for HVAC and Plumbing Contractors (2026) | AE Tax Advisors",
"meta_desc": "Trade contractors overpay through fleet mistiming and weak entity design. Vehicle, inventory, accounting method, and real estate strategy for 2026.",
"category": C, "date": D,
"intro": [
"HVAC and plumbing contractors carry three assets most professional service businesses do not: a fleet, an inventory, and usually a yard with a building on it. Each one is a deduction lever, and each one is commonly mishandled.",
"A contractor doing $6,000,000 in revenue with a 12-truck fleet has more annual deduction capacity than a medical practice at the same profit level. Most are not using it.",
],
"sections": [
("Fleet Timing Is the Biggest Annual Lever", [
"Service vehicles with a gross vehicle weight rating over 6,000 pounds are not subject to the luxury auto depreciation limits under IRC Sec. 280F. Most service vans and all one-ton trucks clear this comfortably, which means a $72,000 service van is fully deductible in the year placed in service under IRC Sec. 168(k) or IRC Sec. 179.",
"Upfits count. Shelving, bin systems, ladder racks, inverters, and lift gates are part of the vehicle basis or separate five-year equipment, either way fully deductible. On a fleet addition of four vans at $85,000 each fully upfitted, that is $340,000 of first-year deduction.",
"Financing does not reduce it. Vehicles financed with 10% down produce the same deduction as vehicles bought for cash. This decouples fleet expansion from the tax result and means the purchase decision should be timed against income rather than cash.",
"The choice between Sec. 179 and bonus depreciation matters for contractors with variable income. Sec. 179 cannot create a loss and is elected asset by asset, giving precise control. Bonus applies by class and can create a loss. In a strong year, taking the full bonus is simple. In a year where you want to keep taxable income at a specific level, Sec. 179 lets you land on the number.",
]),
("Accounting Method Is Worth Reviewing", [
"Contractors with average annual gross receipts under the inflation-adjusted threshold, $31 million for 2025, may generally use the cash method under IRC Sec. 448(c), are exempt from the uniform capitalization rules under IRC Sec. 263A, and may use the completed contract method for long-term contracts.",
"Many contractors are on the accrual method for no reason other than that a prior accountant set it up that way, or because a bonding company asked for accrual statements. You can present accrual financial statements to a surety and file on the cash method. These are separate questions.",
"Switching from accrual to cash is a change in accounting method requiring Form 3115, and it produces a Sec. 481(a) adjustment. For a contractor carrying $900,000 of receivables against $300,000 of payables, that adjustment is a $600,000 deduction, taken in the year of change if it is favorable. This is one of the largest one-time deductions available to a growing contractor and it is routinely never considered.",
]),
("Inventory and Materials", [
"Contractors exempt from Sec. 263A under the small business exception may treat inventory as non-incidental materials and supplies, deductible when used, or may follow their book method. This is meaningfully simpler and often faster than full inventory accounting.",
"For a contractor carrying $400,000 of equipment and parts inventory across a yard and 12 trucks, the method choice affects both the tax result and the bookkeeping burden. Truck stock in particular is difficult to count accurately and is a common source of adjustment on audit.",
]),
("The Yard and Shop Building", [
"Contractors who own their yard usually depreciate the building over 39 years and never think about the site. That is backwards. On a contractor yard, the site improvements often exceed the building value.",
"Paving engineered for truck traffic, fencing and security gates, site lighting, drainage, material storage bins, wash pads, and fuel islands are 15-year land improvement property under IRC Sec. 168(e)(3)(C) and fully bonus eligible. The shop building itself carries dedicated power for welding and compressors, overhead cranes, lifts, and compressed air distribution, all of which are five-year equipment rather than building.",
"A cost segregation study on a contractor yard commonly reclassifies 30% to 45% of depreciable basis, well above what a comparable office property produces.",
"Where the yard is held in a separate entity leasing to the operating company, self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) apply. A grouping election under Treasury Regulation Sec. 1.469-4 is frequently appropriate and should be evaluated before the study.",
]),
("Retirement Plans With a Large Workforce", [
"Contractors have more employees than most owner-heavy businesses, which changes plan design. A safe harbor 401(k) with new comparability profit sharing still works, but staff cost is higher and needs modeling before adoption.",
"Where the workforce is young relative to the owner, cross-tested designs perform well because the contribution required to pass testing for younger employees is lower. A 56-year-old owner with a workforce averaging 34 years old is close to the ideal demographic for a cash balance plan, and the owner benefit to staff cost ratio can still exceed six to one.",
]),
("Worked Example: $6.4M Revenue Contractor", [
"A 54-year-old owner runs an HVAC company with $6,400,000 of revenue, $1,050,000 of profit before owner compensation, 31 employees, and an S corporation structure with a $280,000 salary. The company is on the accrual method and owns its yard.",
"Switching to the cash method via Form 3115 produces a $540,000 Sec. 481(a) deduction in the year of change, reflecting receivables net of payables.",
"Four new service vans fully upfitted at $340,000 are deducted in full. A cost segregation study on the $2,100,000 yard and shop, paired with a grouping election, produces a $618,000 first-year deduction that is usable currently.",
"A safe harbor 401(k) with new comparability directs $70,000 to the owner and a cash balance plan adds $184,000, at $61,000 of staff cost across 31 employees.",
"Total taxable income reduction exceeds $1,700,000 in the transition year, though the accounting method change is one time and the fleet and plan deductions recur.",
]),
],
"faqs": [
("Are service vans fully deductible in the first year?",
 "Generally yes. Vehicles with a gross vehicle weight rating over 6,000 pounds are outside the luxury auto limits in IRC Sec. 280F, so a service van is fully deductible under IRC Sec. 168(k) or Sec. 179 in the year placed in service. Upfit costs including shelving, racks, and inverters are included."),
("Can a contractor use the cash method of accounting?",
 "Generally yes if average annual gross receipts are under the threshold, which is $31 million for 2025. Many contractors are on accrual only because a prior accountant or a bonding company asked for accrual statements, and you can present accrual statements to a surety while filing on the cash method."),
("How large is the deduction from switching to cash method?",
 "It equals receivables less payables and accrued expenses at the date of change, claimed as a Sec. 481(a) adjustment. A contractor with $900,000 of receivables and $300,000 of payables generates a $600,000 deduction. It is a one-time item but often the largest single deduction available to a growing contractor."),
("What does a cost segregation study produce on a contractor yard?",
 "Typically 30% to 45% of depreciable basis, higher than most commercial property. Heavy-duty paving, fencing, site lighting, drainage, and wash pads are 15-year land improvements, and shop power, cranes, lifts, and compressed air distribution are five-year equipment."),
("Does financing equipment reduce my deduction?",
 "No. Depreciation follows the placed-in-service date, not cash paid. Vehicles and equipment financed with 10% down produce the same first-year deduction as cash purchases, which means purchase timing should be driven by your income picture rather than by available cash."),
],
"related": [
("/blog/how-to-finance-equipment-10-percent-down-full-tax-deduction/", "Financing equipment with 10 percent down"),
("/blog/3115-change-accounting-method-playbook/", "Form 3115 accounting method change playbook"),
("/blog/construction-company-heavy-equipment-write-off/", "Heavy equipment write-offs for contractors"),
],
"cta_head": "The Accounting Method Change Alone May Pay for the Year",
"cta_body": "Bring your balance sheet, fleet schedule, and yard detail. We will size the method change, the fleet timing, and the yard study together.",
},

{
"slug": "tax-strategy-for-staffing-agency-owners",
"title": "Tax Strategy for Staffing Agency Owners: Working Capital, Entity Design, and Exit",
"meta_title": "Tax Strategy for Staffing Agency Owners (2026 Guide) | AE Tax Advisors",
"meta_desc": "Staffing agencies face receivable-heavy balance sheets and QBI wage limits. Accounting method, entity, retirement, and exit strategy for 2026.",
"category": C, "date": D,
"intro": [
"A staffing agency is a working capital business wearing a service business costume. You pay contractors weekly and collect from clients in 45 to 60 days, which means growth consumes cash and the balance sheet fills with receivables.",
"That structure creates a specific and large tax opportunity that most agency owners have never been shown, and it also creates an unusual QBI position because staffing agencies pay enormous wages relative to profit.",
],
"sections": [
("The Accounting Method Opportunity", [
"Under IRC Sec. 448(c), a business with average annual gross receipts under the threshold, $31 million for 2025, may generally use the cash method. Staffing agencies frequently qualify well past the point where anyone reconsiders the method they started with.",
"For a receivable-heavy business, the difference is dramatic. An agency with $2,400,000 of receivables and $700,000 of accrued payroll and payables carries a $1,700,000 spread. Changing from accrual to cash via Form 3115 produces a Sec. 481(a) adjustment of that amount, deductible in the year of change if favorable.",
"Note the gross receipts definition. For a staffing agency billing $24,000,000 gross with $19,000,000 of contractor cost, gross receipts are the full billing amount, not the gross margin. Many agencies cross the threshold sooner than they expect. The method change should be evaluated before the threshold is crossed, because the opportunity closes.",
]),
("QBI and the Wage Limitation", [
"Staffing agencies are not specified service trades or businesses. Placement and staffing services are not among the excluded fields under IRC Sec. 199A, so the 20% qualified business income deduction remains available at any income level.",
"Better still, the wage limitation that constrains most high-income businesses is almost never binding here. The limitation caps the deduction at the greater of 50% of W-2 wages or 25% of wages plus 2.5% of qualified property. A staffing agency with $19,000,000 of W-2 wages and $1,400,000 of qualified business income has a wage limitation of $9,500,000 against a potential deduction of $280,000.",
"The nuance is which wages count. Wages paid by the entity and reported on returns filed by that entity count. Where placed workers are paid through a professional employer organization or a separate entity, the wage attribution requires review. The regulations under Treasury Regulation Sec. 1.199A-2 address common-law employer status and this should be confirmed rather than assumed, because the answer can swing the deduction entirely.",
]),
("Entity Structure and Reasonable Compensation", [
"S corporation treatment is standard. Because the wage limitation is not binding, salary optimization is a pure payroll tax question rather than a tradeoff against QBI.",
"Reasonable compensation for an agency owner should reflect the actual role. An owner personally recruiting and selling justifies a higher salary than an owner running a management team with independent producers. Agencies with a genuine enterprise, where recruiters and account managers generate revenue without owner involvement, can typically defend a lower owner salary because profit reflects a return on the business rather than on personal services.",
"Multi-owner agencies should confirm that partnership or shareholder agreements match actual economics. Producer-owners taking commission plus distributions create allocation questions that need documenting.",
]),
("Retirement Plans Around a Large Workforce", [
"The workforce is the challenge. An agency with 400 placed workers has a very different plan design problem than a company with 12 employees.",
"Placed workers who are common-law employees of the agency are generally eligible for the plan, subject to age and service requirements. Using the maximum permissible service requirement, one year and 1,000 hours, excludes a large share of a staffing workforce with high turnover and part-time assignments. This is legitimate plan design, not avoidance, and it is what makes an owner-favorable plan feasible.",
"Where the design works, a safe harbor 401(k) with new comparability profit sharing plus a cash balance plan can still direct $250,000 or more annually to an owner. Where it does not, because the workforce is stable and long-tenured, the staff cost may make the cash balance plan uneconomic and the planning shifts elsewhere.",
]),
("Exit Structure", [
"Staffing agencies sell on EBITDA multiples, and buyers scrutinize working capital closely. The purchase agreement will include a working capital target, and receivables quality directly affects the price.",
"Tax-wise, most transactions are asset sales. Under IRC Sec. 1060 the price is allocated across classes. Goodwill and customer relationships are capital gain. Non-compete allocations and consulting agreements are ordinary income to the seller and should be minimized in negotiation.",
"An agency that changed to the cash method has a specific exit consideration. The receivables have already been deducted, so collecting them post-sale, or having them purchased, produces ordinary income. This should be modeled before the transaction, not discovered during it. It does not make the method change wrong, but it changes the timing analysis and the working capital negotiation.",
]),
("Worked Example: $18M Revenue Agency", [
"A 48-year-old owner runs a staffing agency with $18,400,000 of revenue, $1,320,000 of profit before owner compensation, and an S corporation structure with a $300,000 salary. The agency is on the accrual method with $2,600,000 of receivables and $810,000 of accrued payroll.",
"Changing to the cash method via Form 3115 produces a $1,790,000 Sec. 481(a) deduction in the year of change.",
"The QBI deduction of approximately $204,000 remains fully available, unconstrained by the wage limitation given the agency's payroll base.",
"A safe harbor 401(k) with new comparability, designed with a one-year and 1,000-hour eligibility requirement, directs $70,000 to the owner at $34,000 of staff cost. A cash balance plan adds $148,000 at $22,000 of additional staff cost.",
"Taxable income in the transition year falls by more than $2,000,000, with roughly $220,000 of recurring annual deduction thereafter.",
]),
],
"faqs": [
("Can a staffing agency use the cash method of accounting?",
 "Generally yes if average annual gross receipts are under the threshold, $31 million for 2025. Note that gross receipts means total billings, not gross margin, so agencies cross the threshold sooner than expected. The method change should be evaluated before that happens because the opportunity closes."),
("How large is the cash method change deduction?",
 "It equals receivables less payables and accrued expenses at the change date, claimed as a Sec. 481(a) adjustment. For a receivable-heavy staffing agency, this is frequently seven figures and is the single largest deduction available to most agency owners."),
("Do staffing agencies qualify for the QBI deduction?",
 "Yes. Staffing and placement services are not specified service trades or businesses under IRC Sec. 199A. Better still, the W-2 wage limitation is almost never binding for a staffing agency, because the wage base is enormous relative to qualified business income."),
("Are placed workers eligible for my retirement plan?",
 "If they are common-law employees of the agency, generally yes, subject to age and service requirements. Using the maximum permissible eligibility requirement of one year and 1,000 hours excludes much of a high-turnover placed workforce, which is what makes an owner-favorable design feasible."),
("Does switching to cash method create a problem at sale?",
 "It creates a timing consideration. Because receivables were already deducted, collecting them after the sale, or having them purchased, produces ordinary income. This should be modeled during transaction planning and factored into the working capital negotiation."),
],
"related": [
("/blog/3115-change-accounting-method-playbook/", "Form 3115 accounting method change playbook"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
("/blog/purchase-price-allocation-optimization-business-sale/", "Purchase price allocation in a business sale"),
],
"cta_head": "The Method Change Closes When You Cross the Threshold",
"cta_body": "If your agency is growing toward $31 million in billings, the window on this is finite. Bring your balance sheet and trailing revenue and we will size it.",
},

{
"slug": "tax-strategy-for-marketing-agency-owners",
"title": "Tax Strategy for Marketing Agency Owners: Pass-Through Costs, QBI, and Contractors",
"meta_title": "Tax Strategy for Marketing Agency Owners (2026 Guide) | AE Tax Advisors",
"meta_desc": "Agency owners face media pass-through accounting, contractor classification, and QBI questions. Entity, retirement, and structure strategy for 2026.",
"category": C, "date": D,
"intro": [
"Marketing and advertising agencies have three tax issues that do not appear in most service businesses: media spend flowing through the P&L, a workforce that is often a mix of employees and contractors, and a genuinely uncertain position on whether the business is a specified service trade or business.",
"Getting those three right is worth more than any deduction on the list, because each one affects the entire return rather than a single line.",
],
"sections": [
("Media Pass-Through Distorts Everything", [
"An agency that buys $4,000,000 of media on behalf of clients and bills it through reports $4,000,000 more revenue than an agency that has clients pay media directly. Profit is identical. Gross receipts are not.",
"That matters in specific ways. Gross receipts determine eligibility for the cash method under IRC Sec. 448(c) and for the small business exemptions from Sec. 263A and the business interest limitation under IRC Sec. 163(j). An agency with $6,000,000 of fee revenue and $26,000,000 of pass-through media may lose access to all three simply because of how the media is billed.",
"Whether the agency is acting as principal or agent determines the reporting. Agencies that take on credit risk and contract with the media vendor directly are generally principals reporting gross. Agencies that arrange the buy with the client contracting directly are agents reporting net. The commercial arrangement drives it, and the arrangement can be structured deliberately with an eye toward the thresholds.",
]),
("The SSTB Question Is Genuinely Unsettled", [
"Advertising and marketing are not among the fields explicitly excluded under IRC Sec. 199A. The regulations exclude consulting, defined in Treasury Regulation Sec. 1.199A-5(b)(2)(vii) as providing professional advice and counsel to assist a client in achieving goals and solving problems.",
"The regulations then expressly state that advertising services, including the creation and design of advertising and media buying, are not consulting for this purpose. That is a favorable and specific carve-out.",
"But an agency that primarily provides strategic advice, branding consultation, or marketing consulting without executing campaigns looks much more like consulting. Many agencies do both, and the mix determines the answer. Where a de minimis amount of revenue comes from a service that would be an SSTB, Treasury Regulation Sec. 1.199A-5(c) provides thresholds below which the entire business is not tainted.",
"For an agency with $900,000 of qualified business income, this is a $180,000 deduction. It is worth documenting the revenue mix contemporaneously rather than reconstructing it later.",
]),
("Contractor Classification Is the Largest Risk", [
"Agencies run on freelancers. Designers, writers, developers, media buyers, and producers are frequently engaged as contractors, and a meaningful share of them would fail a worker classification test.",
"The exposure is not just payroll tax. Misclassification affects retirement plan coverage testing, workers compensation, state unemployment, and in an acquisition, it becomes a diligence finding that reduces price or lands in an escrow.",
"Section 530 of the Revenue Act of 1978 provides relief where the agency had a reasonable basis for the treatment, treated all similar workers consistently, and filed all required Forms 1099. The consistency requirement is where agencies fail, because they typically have some designers as employees and some as contractors doing identical work.",
"This is worth a real review rather than an assumption, and it is one of the few tax issues where the right answer may be to change behavior rather than change reporting.",
]),
("Entity and Compensation Design", [
"S corporation treatment is standard for a profitable agency. Where the SSTB analysis is favorable and income exceeds the threshold, the QBI wage limitation becomes relevant and salary optimization involves a real tradeoff rather than a simple payroll tax minimization.",
"Agencies with multiple owner-producers should confirm that the operating agreement's compensation provisions match actual practice. Creative and account leadership compensation frequently drifts from what the documents describe, and partnership allocations that do not have substantial economic effect under Treasury Regulation Sec. 1.704-1(b) create problems at the worst time.",
]),
("Retirement Plans and a Young Workforce", [
"Agencies typically employ a young workforce, which is favorable for cross-tested plan design. New comparability profit sharing allocates contributions by age-weighted classes, and a large gap between owner age and average staff age produces a favorable owner-to-staff cost ratio.",
"A 51-year-old owner with a staff averaging 31 can often direct 80% or more of employer contributions to the owner group while passing testing. Layering a cash balance plan can add $140,000 to $200,000 of annual deductible contribution.",
"The turnover typical in agency work also helps. Using a one-year and 1,000-hour eligibility requirement plus a vesting schedule reduces the effective staff cost meaningfully.",
]),
("Worked Example: $5.2M Fee Revenue Agency", [
"A 50-year-old owner runs an agency with $5,200,000 of fee revenue, $22,000,000 of pass-through media, and $980,000 of profit before owner compensation, with 26 employees and an S corporation structure at a $290,000 salary.",
"Restructuring media contracting so that clients contract directly with vendors drops gross receipts below the Sec. 448(c) threshold, preserving cash method eligibility and the small business exemption from the Sec. 163(j) interest limitation.",
"The revenue mix is documented at 87% execution services and 13% strategic consulting, supporting a non-SSTB position and preserving a QBI deduction of approximately $138,000.",
"A safe harbor 401(k) with new comparability directs $70,000 to the owner at $29,000 of staff cost, and a cash balance plan adds $172,000 at $24,000 of additional staff cost.",
"Combined, the annual tax reduction exceeds $170,000, with the media restructuring and SSTB documentation protecting positions worth substantially more over time.",
]),
],
"faqs": [
("Is a marketing agency a specified service trade or business?",
 "Usually not. Treas. Reg. Sec. 1.199A-5(b)(2)(vii) expressly states that advertising services, including creating and designing advertising and media buying, are not consulting. But an agency primarily providing strategic advice looks like consulting, so the revenue mix determines the answer and should be documented."),
("Should media spend run through my P&L?",
 "It depends on whether you are principal or agent commercially, but the choice affects gross receipts, which control cash method eligibility and small business exemptions from Sec. 263A and Sec. 163(j). An agency can lose all three simply from how media contracting is arranged."),
("How risky is contractor classification for an agency?",
 "It is the largest single exposure most agencies carry. Section 530 relief requires a reasonable basis, consistent treatment of similar workers, and filed Forms 1099. Agencies commonly fail the consistency test because they have some designers as employees and some as contractors doing the same work."),
("Do agencies qualify for the QBI deduction?",
 "Generally yes, given the advertising carve-out in the regulations. For an agency with $900,000 of qualified business income, the deduction is worth $180,000, subject to the W-2 wage limitation above the income threshold. Documenting the service mix contemporaneously protects the position."),
("What retirement plan design works for a young agency staff?",
 "New comparability profit sharing performs well when there is a large age gap between owners and staff. A 51-year-old owner with staff averaging 31 can often direct 80% or more of employer contributions to the owner group, and a cash balance plan can layer on top."),
],
"related": [
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
("/blog/cash-balance-plans-business-owners-2026/", "Cash balance plans for business owners"),
("/blog/how-to-structure-multiple-businesses-for-tax-efficiency/", "Structuring multiple businesses"),
],
"cta_head": "Three Structural Issues, One Conversation",
"cta_body": "Media reporting, SSTB documentation, and contractor classification each affect the whole return. Bring your P&L, your contractor list, and a description of your service mix.",
},

{
"slug": "tax-strategy-for-content-creators-and-influencers",
"title": "Tax Strategy for Content Creators and Influencers: Entity, Deductions, and Volatility",
"meta_title": "Tax Strategy for Content Creators and Influencers (2026) | AE Tax Advisors",
"meta_desc": "Creator income is volatile and multi-source. Entity structure, deduction substantiation, retirement plans, and income smoothing strategy for 2026.",
"category": C, "date": D,
"intro": [
"Creator income has two features that break conventional tax planning: it arrives from six or eight sources at once, and it swings violently year to year. A creator can earn $90,000 one year and $740,000 the next on the same content.",
"Both facts point in the same direction. The planning has to be built for variability, which means favoring flexible tools over fixed commitments and thinking in multi-year windows rather than a single December decision.",
],
"sections": [
("Get the Entity Right, Then Stop Overthinking It", [
"A creator netting under roughly $80,000 is usually fine on a schedule C. Above that, an S corporation election starts paying for itself. On $250,000 of net profit with a $110,000 salary, the self-employment tax savings run roughly $19,000 annually against maybe $3,500 of added payroll and compliance cost.",
"Reasonable compensation is the constraint. For a creator, the personal services component is the whole business, which makes low salaries harder to defend than in a business with independent revenue-producing assets. Creators with a genuine team, editors, managers, and staff producing content that generates revenue independently, have a better argument for a lower percentage.",
"Content creation is generally not a specified service trade or business. Performing arts is an excluded field under IRC Sec. 199A, and there is a real question whether some creator activity falls within it. Advertising and licensing revenue generally does not. A creator with substantial brand partnership and licensing income has a defensible position for the QBI deduction on that portion, worth 20% of qualified business income.",
]),
("Deductions Are Real, But Substantiation Decides Them", [
"Cameras, lighting, audio equipment, computers, editing software, studio build-out, and props are ordinary and necessary business expenses, deductible currently or as five-year property under IRC Sec. 168(k) and Sec. 179.",
"Travel is where creators get into trouble. A trip that produces content is not automatically deductible. The primary purpose test under IRC Sec. 162 and the substantiation requirements of IRC Sec. 274(d) both apply, and Sec. 274(d) requires contemporaneous records of amount, time, place, and business purpose. A creator claiming $60,000 of travel with no documentation beyond credit card statements will lose it.",
"The practical answer is a contemporaneous log tied to published content. A trip that generated 14 pieces of published content with documented sponsor deliverables looks entirely different from a trip that generated three vacation posts.",
"Clothing is generally not deductible unless it is unsuitable for ordinary wear. This rule has been litigated repeatedly and creators lose it consistently. Costumes and specialized gear qualify. A wardrobe does not.",
"Home studio space is deductible, and for an S corporation owner it should run through an accountable plan reimbursement rather than a personal deduction, since unreimbursed employee expenses are not deductible.",
]),
("Income Volatility Requires Different Tools", [
"A creator whose income swings from $120,000 to $600,000 should not adopt a plan that requires consistent funding. Cash balance plans, which require reasonably consistent contributions, are usually the wrong tool for a creator in a growth or decline phase, whatever the deduction math looks like in a single year.",
"A solo 401(k) is the right base. The employee deferral can be funded during the year, and the employer profit sharing portion, up to a $70,000 total in 2025 plus catch-up, is discretionary and decided at filing. In a $600,000 year you fund it fully. In a $120,000 year you fund what makes sense.",
"Creators with sustained high income for three or more years and a realistic view that it will continue can then evaluate a cash balance plan. The sequencing matters more than the size.",
"Income smoothing is also available through contract structure. Brand deals paid across a delivery schedule rather than a lump sum, and licensing arrangements with multi-year terms, shift income into years where it faces a lower marginal rate. This has to be negotiated into the agreement, not adjusted afterward, because constructive receipt under Treasury Regulation Sec. 1.451-2 will pull income into the year it was available.",
]),
("Multi-State and Nexus Issues", [
"Creators earn from platforms and sponsors across many states and sometimes many countries. Most platform revenue is sourced to the creator's residence rather than the viewer's, which simplifies things considerably.",
"Where it gets complicated is appearance income, live events, and physical product sales. Appearance fees are generally sourced to where the services were performed, which creates filing obligations in those states. Product sales create sales tax nexus under economic nexus thresholds in most states.",
"Creators who move states mid-year, which happens often, need to handle residency carefully. Partial year residency, source income allocation, and the domicile tests in high-tax states are frequently challenged. Documenting the move properly, meaning driver's license, voter registration, physical presence records, and severed connections, matters far more than the date on a lease.",
]),
("Worked Example: $480,000 Creator Year", [
"A 34-year-old creator nets $480,000 across platform revenue, brand partnerships, an affiliate program, and a digital product, filing on a schedule C with no entity.",
"Electing S corporation status with a $210,000 salary saves approximately $10,900 in self-employment tax. A solo 401(k) contributes $70,000, deductible, funded fully given the strong year.",
"A $62,000 studio build-out and equipment package is fully deductible in the year placed in service. Documented business travel of $38,000 is supported by a contemporaneous log tied to 47 pieces of published content with sponsor deliverables.",
"Approximately 61% of revenue is brand partnership and licensing income supporting a QBI position, producing a deduction of roughly $47,000.",
"Combined tax reduction of approximately $86,000 against a business that had no structure at all twelve months earlier.",
]),
],
"faqs": [
("When should a content creator form an S corporation?",
 "Generally once net profit consistently exceeds roughly $80,000, where self-employment tax savings clearly exceed the added payroll and compliance cost. Because creator income is volatile, the decision should be based on a realistic multi-year view rather than one strong year."),
("Is travel deductible if I make content about the trip?",
 "Only if the primary purpose is business and you meet the substantiation requirements of IRC Sec. 274(d), which demand contemporaneous records of amount, time, place, and business purpose. A trip producing documented deliverables under sponsor agreements is defensible. A vacation with a few posts is not."),
("Can I deduct clothing I wear in videos?",
 "Generally no. Clothing is deductible only if it is unsuitable for ordinary wear. This has been litigated repeatedly and creators lose it consistently. Costumes and specialized protective or performance gear qualify. A wardrobe, however specific to your brand, does not."),
("Do creators qualify for the QBI deduction?",
 "Often for part of their income. Performing arts is a specified service trade or business under IRC Sec. 199A, but advertising, brand partnership, and licensing revenue generally is not. A creator with substantial partnership and licensing income has a defensible position on that portion."),
("What retirement plan works with unpredictable income?",
 "A solo 401(k). The employee deferral funds during the year and the employer profit sharing portion is discretionary and decided at filing, so you can contribute heavily in strong years and lightly in weak ones. Cash balance plans require consistent funding and are usually a poor fit until income stabilizes."),
],
"related": [
("/blog/should-i-elect-s-corp-status-for-my-llc/", "Should you elect S corp status for your LLC"),
("/blog/how-much-can-i-contribute-to-a-solo-401k/", "Solo 401(k) contribution limits"),
("/blog/how-to-deduct-a-home-office-through-your-s-corp/", "Deducting a home office through your S corp"),
],
"cta_head": "Build for the Swing, Not for This Year",
"cta_body": "Creator planning fails when it assumes income stays flat. Bring your last three years of revenue by source and we will build something that survives a down year.",
},

{
"slug": "tax-strategy-for-physical-therapy-practice-owners",
"title": "Tax Strategy for Physical Therapy Practice Owners: Multi-Clinic Growth and Structure",
"meta_title": "Tax Strategy for Physical Therapy Practice Owners (2026) | AE Tax Advisors",
"meta_desc": "PT owners face thin margins, multi-site expansion, and SSTB limits. Entity, build-out, retirement, and real estate strategy for practices in 2026.",
"category": C, "date": D,
"intro": [
"Physical therapy practices operate on thinner margins than most medical specialties, which changes the planning. A PT practice producing $340,000 of owner profit on $1,600,000 of revenue does not have the cushion a surgical practice has, so strategies have to be efficient rather than merely available.",
"The compensating advantage is that PT scales through additional locations, and each new clinic is a fresh build-out with a fresh deduction.",
],
"sections": [
("Build-Outs Are the Recurring Opportunity", [
"A PT clinic build-out reclassifies well, generally 30% to 45% of construction cost. Rubber and specialty flooring in the gym area, treatment table plumbing and dedicated electrical, decorative and accent lighting, casework and reception millwork, sound masking, and privacy partition systems are five-year personal property.",
"The structural remainder of an interior build-out in leased space generally qualifies as qualified improvement property under IRC Sec. 168(e)(6), carrying a 15-year life with full bonus eligibility under IRC Sec. 168(k). Between the two, a $480,000 clinic build-out is often close to fully deductible in the opening year.",
"For an owner opening one clinic a year, this becomes an annual deduction of $400,000 to $600,000 that offsets the profit generated by the mature locations. Growth funds its own tax efficiency, which is the single most useful structural feature of a multi-site PT business.",
"Equipment adds to it. Treatment tables, traction units, modalities, exercise and rehab equipment, dry needling and laser equipment, and practice management hardware are five-year property, fully deductible in the placed-in-service year.",
]),
("The SSTB Limitation and What It Costs", [
"Physical therapy is health services under IRC Sec. 199A, a specified service trade or business. Above the phase-out range, the qualified business income deduction is unavailable entirely.",
"For a practice with $500,000 of qualified business income, that is a $100,000 deduction lost. Below the threshold it is fully available, which means multi-owner practices where each owner's share falls below the threshold may still claim it while a single-owner practice at the same total income does not.",
"This is one of the few places where ownership structure genuinely changes the answer. A practice with three equal owners each showing $220,000 of qualified business income may have the deduction available where a sole owner with $660,000 does not. Practices contemplating partner buy-ins should model this, because it can offset a meaningful portion of the economic cost of admitting a partner.",
]),
("Entity and Compensation", [
"S corporation treatment is standard. Because the QBI deduction is generally unavailable above the threshold, the salary analysis is a straightforward payroll tax question without the wage limitation tradeoff.",
"Reasonable compensation for a PT owner should reflect clinical production plus management. An owner treating patients full time while managing three clinics has a compensation profile with two components, and the analysis is stronger when it accounts for both explicitly rather than picking a round number.",
"Practices with associate therapists should also examine whether the compensation model creates the right incentives without creating tax problems. Productivity bonuses paid as W-2 compensation are straightforward. Profit distributions to non-owner therapists are not, and arrangements that look like equity without being equity create their own issues.",
]),
("Retirement Plans on a Thin Margin", [
"PT practices have more employees per dollar of owner profit than most medical specialties, which makes aggressive plan design harder. A cash balance plan that costs $45,000 in staff contributions to deliver $150,000 of owner contribution is still worth doing, but the ratio needs checking rather than assuming.",
"A safe harbor 401(k) with new comparability profit sharing is the practical base. Where the workforce skews young, which it usually does in PT, cross-testing performs well and the owner can capture a large share of employer contributions.",
"For multi-site practices, plan design should account for the aggregate workforce across entities. Controlled group and affiliated service group rules under IRC Sec. 414(b), (c), and (m) treat commonly owned entities as a single employer for plan testing. Practices that set up each clinic as a separate LLC and assume separate plans are available are frequently wrong about that.",
]),
("Owning the Real Estate", [
"PT clinics are good real estate tenants and many owners eventually buy their buildings. A cost segregation study on a clinic building typically reclassifies 20% to 30% of depreciable basis, and the build-out inside reclassifies far higher.",
"The self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) govern how the resulting loss is used. Net rental income from property leased to a business you materially participate in is recharacterized as non-passive, but a net rental loss generally is not, which can leave a large depreciation deduction suspended.",
"A grouping election under Treasury Regulation Sec. 1.469-4 frequently resolves this where the requirements are met. It should be evaluated before the study is commissioned, because the sequence affects whether the deduction is usable in the year it is generated.",
]),
("Worked Example: Three-Clinic Practice", [
"A 46-year-old owner runs three clinics with $2,900,000 of revenue and $610,000 of profit before owner compensation, with 24 employees, structured as an S corporation with a $230,000 salary.",
"A fourth clinic build-out of $520,000 plus $140,000 of equipment is placed in service in the current year and is substantially fully deductible between five-year property, QIP, and equipment.",
"A safe harbor 401(k) with new comparability directs $69,000 to the owner at $27,000 of staff cost across the controlled group.",
"A look-back cost segregation study on the first clinic build-out completed four years ago, filed with Form 3115, produces a $186,000 catch-up deduction.",
"Taxable income falls by roughly $915,000 in the year, which for a practice with $610,000 of profit creates a loss carryforward that shelters the following year as well.",
]),
],
"faqs": [
("Does physical therapy qualify for the QBI deduction?",
 "Physical therapy is health services and therefore a specified service trade or business under IRC Sec. 199A. Above the phase-out range the deduction is unavailable. Below the threshold it is fully available, which is why multi-owner practices sometimes preserve it where a sole owner would not."),
("How much of a PT clinic build-out is deductible in year one?",
 "Typically 30% to 45% reclassifies to five-year personal property, with most of the balance qualifying as 15-year QIP under IRC Sec. 168(e)(6) with full bonus eligibility. Between the two, a leasehold build-out is often close to fully deductible in the opening year."),
("Can each of my clinics have its own retirement plan?",
 "Usually not in the way owners expect. Controlled group and affiliated service group rules under IRC Sec. 414(b), (c), and (m) treat commonly owned entities as a single employer for plan testing. Separate LLCs do not create separate testing groups when ownership overlaps."),
("Should I buy my clinic building?",
 "Often yes, and a cost segregation study typically reclassifies 20% to 30% of the building plus far more of the build-out. But the self-rental rules under Treas. Reg. Sec. 1.469-2(f)(6) determine whether the loss is usable currently, so evaluate a grouping election before commissioning the study."),
("Does adding a partner change my tax position?",
 "It can, meaningfully. If each owner's share of qualified business income falls below the IRC Sec. 199A threshold, the deduction that was unavailable to a sole owner may become available. This should be modeled as part of the economics of any buy-in."),
],
"related": [
("/blog/cost-segregation-medical-office-buildings/", "Cost segregation for medical office buildings"),
("/blog/self-rental-rules-business-rents-from-you/", "Self-rental rules explained"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
],
"cta_head": "Growth Should Fund Its Own Tax Efficiency",
"cta_body": "If you are opening a clinic a year, the build-out deduction should be planned against your mature clinic profit. Bring your expansion timeline and your P&L.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
