"""Batch: STR deep-dive articles. These slugs are already linked from the
short-term-rentals mega page and other pages but were never written, so
publishing them also clears existing broken internal links.
"""

from blog_gen import write_all

STR = "Short-Term Rentals"
RE = "Real Estate Tax"
BO = "Business Owner Tax"
D = "2026-08-11"

ARTICLES = [
{
"slug": "str-property-manager-co-host-material-participation",
"title": "Does a Property Manager or Co-Host Kill My STR Material Participation?",
"meta_title": "STR Property Manager and Co-Host Material Participation (2026) | AE Tax Advisors",
"meta_desc": "A co-host or manager does not automatically disqualify you, but it makes the 100-hour test far harder. How each participation test survives a manager.",
"category": STR, "date": D,
"intro": [
"This is the question that decides whether most short-term rental tax strategies work. The seven-day rule removes the property from rental activity treatment, but you still have to materially participate under Treasury Regulation Sec. 1.469-5T, and a manager competes directly with you on the test most owners rely on.",
"The answer is not automatic disqualification. It depends entirely on which of the seven tests you are using and how much the manager actually does.",
],
"sections": [
("The Seven Tests and Which Ones a Manager Affects", [
"Treasury Regulation Sec. 1.469-5T(a) provides seven tests. You need to satisfy only one.",
"Test one: more than 500 hours in the activity. A manager does not affect this test at all. If you personally spend 500 hours, you materially participate regardless of what anyone else does.",
"Test two: your participation constitutes substantially all of the participation of all individuals in the activity. A manager destroys this test immediately, since their hours count.",
"Test three: more than 100 hours, and not less than any other individual's participation. This is the test most STR owners rely on, and a manager or co-host is a direct threat to it.",
"Test four: significant participation activities aggregating more than 500 hours across multiple activities where you participate more than 100 hours in each.",
"Test five: material participation in any five of the ten preceding taxable years.",
"Test six: personal service activity material participation in any three preceding years, which does not apply to rental property.",
"Test seven: facts and circumstances, requiring regular, continuous, and substantial participation on more than 100 hours. The regulation excludes reliance on this test where any person other than the owner receives compensation for management of the activity, which is a direct bar when you pay a manager.",
]),
("Why the 100-Hour Test Is the Battleground", [
"Most STR owners cannot reach 500 hours on one property. Cleaning, guest communication, maintenance coordination, listing management, and pricing across a single property rarely totals 500 hours in a year.",
"So they rely on test three: more than 100 hours, and more than any other individual.",
"A full-service property manager typically spends far more than 100 hours on a property annually. Between cleaning coordination, guest messaging, check-ins, maintenance, and listing management, a manager handling a busy property may spend 200 to 400 hours.",
"If the manager spends 260 hours and you spend 140, you fail test three. Your hours were real, but someone else did more.",
"Critically, the test compares you against each individual, not against all others combined. If three separate cleaners each spend 60 hours and you spend 140, you still pass, because no single individual exceeded you.",
]),
("Whose Hours Count", [
"Any individual's participation counts, including employees, contractors, cleaners, and the manager, and including individuals who have no ownership interest.",
"Under Treasury Regulation Sec. 1.469-5T(f)(2)(ii), work not customarily done by an owner does not count as participation if one of its principal purposes is avoiding the passive loss rules. This cuts against manufactured hours, not against the manager.",
"Your spouse's hours count toward your participation under IRC Sec. 469(h)(5), which is a genuine advantage. A couple who together spend 190 hours against a manager's 160 passes test three.",
"An entity's hours are attributed to the individuals performing them. A cleaning company that sends four different people to the property means four individuals, each with their own hour count, rather than one entity with the combined total. This is favorable and is one of the most useful practical facts in STR participation planning.",
]),
("Co-Hosting Arrangements Specifically", [
"A co-host on a platform typically handles guest communication, calendar management, and coordination while the owner handles ownership decisions.",
"Whether this is fatal depends on hours, not on the label. A co-host handling messaging for a property with 140 bookings a year may spend 180 hours. A co-host who only steps in when the owner travels may spend 25.",
"The practical approach for an owner who wants to keep the deduction is to retain the time-intensive functions: guest communication, pricing and calendar management, vendor coordination, and turnover quality control, and delegate only what is genuinely episodic.",
"Where a manager is necessary, an owner with multiple properties should consider whether aggregating them changes the analysis. Grouping under Treasury Regulation Sec. 1.469-4 combines activities, so the owner's total hours across five properties are compared against each individual's hours in the combined activity. An owner with 340 hours across five properties may exceed any single manager's hours on the combined activity even if they would lose property by property.",
]),
("What Counts as Your Participation", [
"Work done in your capacity as an owner counts if it is the type of work customarily done by owners and is not primarily for the purpose of avoiding the passive rules.",
"Guest communication, pricing decisions, listing creation and optimization, vendor selection and coordination, purchasing supplies and furnishings, property inspections, bookkeeping specific to the property, and physical work such as cleaning or repairs all count.",
"Investor-type activities are excluded under Treasury Regulation Sec. 1.469-5T(f)(2)(ii)(B): studying financial statements, analyzing returns, and monitoring finances in a non-managerial capacity do not count.",
"Travel time to the property is contested. The IRS position is generally unfavorable, and courts have not been sympathetic to large travel hour claims.",
]),
("Documentation That Survives Examination", [
"Keep a contemporaneous log with date, hours, and a specific description. Not property management, but responded to 11 guest inquiries, adjusted pricing for three weekends, scheduled HVAC service.",
"Obtain and retain the manager's or co-host's hours. This is the number the examiner will ask for, and if you do not have it, they will estimate it unfavorably.",
"Where you use a cleaning company, document that different individuals perform the work, since that splits their hours across people rather than concentrating them.",
"Retain corroboration: platform message timestamps, pricing change history, vendor invoices and scheduling emails, and receipts.",
]),
("Worked Example: Two Owners, Same Property", [
"Owner A buys a $740,000 short-term rental, hires a full-service manager at 20% of revenue, and personally spends 118 hours on ownership decisions and periodic visits. The manager's records show 291 hours.",
"Owner A fails test three, cannot use test two because the manager participated substantially, and is barred from the facts and circumstances test because a compensated manager handles the activity. Owner A does not materially participate. A $212,000 cost segregation deduction suspends as a passive loss.",
"Owner B buys the same property, handles guest communication, pricing, and vendor coordination personally, and hires an independent cleaning company that sends different cleaners. Owner B logs 164 hours. The cleaning company's individuals log 71, 58, 44, and 39 hours respectively.",
"Owner B exceeds 100 hours and exceeds every individual's participation. Test three is satisfied. Owner B materially participates, the average stay is 4.6 nights so the activity is not a rental, and the $212,000 deduction is non-passive against W-2 income.",
"The property, the study, and the deduction are identical. The management arrangement is the only difference, and it is worth roughly $78,000.",
]),
],
"faqs": [
("Does hiring a property manager disqualify my STR deduction?",
 "Not automatically, but it makes the 100-hour test much harder, since you must exceed every individual's participation and a full-service manager typically spends 200 to 400 hours. It also bars the facts and circumstances test, which excludes reliance where a compensated manager handles the activity."),
("Do the cleaner's hours count against me?",
 "Yes, but per individual rather than in total. If three separate cleaners each spend 60 hours and you spend 140, you still pass the 100-hour test because no single person exceeded you. Using a company that sends different people is therefore more favorable than one dedicated cleaner."),
("Do my spouse's hours count toward mine?",
 "Yes. Under IRC Sec. 469(h)(5) a spouse's participation counts toward yours for material participation, even if the spouse has no ownership interest and even on a separate return. This is one of the most useful facts in STR planning."),
("Can I use a co-host and still qualify?",
 "It depends on hours, not on the label. Retain the time-intensive functions such as guest communication, pricing, and vendor coordination, and delegate only what is episodic. A co-host who spends 25 hours is very different from one who spends 180."),
("Does grouping multiple properties help?",
 "It can. A grouping election under Treas. Reg. Sec. 1.469-4 combines activities, so your total hours across all properties are compared against each individual's hours in the combined activity. An owner with 340 hours across five properties may pass where they would fail property by property."),
],
"related": [
("/blog/material-participation-tests-str-owners/", "Material participation tests for STR owners"),
("/blog/how-to-track-material-participation-hours-for-str/", "Tracking material participation hours"),
("/short-term-rentals/", "Short-term rental tax strategy"),
],
"cta_head": "Get the Manager's Hours Before You File",
"cta_body": "The number that decides your deduction is the one your manager can produce. We help owners structure the arrangement before the year starts rather than after.",
},

{
"slug": "str-loss-limitation-basis-at-risk-passive",
"title": "STR Loss Limitations: Basis, At Risk, and Passive, in That Order",
"meta_title": "STR Loss Limitations: Basis, At Risk, Passive (2026) | AE Tax Advisors",
"meta_desc": "Three limits screen every STR loss in sequence under IRC Sec. 704(d), 465, and 469. Why material participation alone does not guarantee a deduction.",
"category": STR, "date": D,
"intro": [
"Short-term rental owners focus almost entirely on the passive activity rules, because that is where the seven-day rule and material participation live. But passive is the third limitation, not the first.",
"Two other limits screen the loss before IRC Sec. 469 is ever reached, and an owner who clears material participation can still find the deduction blocked. The order matters, because clearing a later limit does nothing if you failed an earlier one.",
],
"sections": [
("Limit One: Basis", [
"You cannot deduct a loss exceeding your basis in the activity. For a property held directly, this is your basis in the property. For a partnership interest, it is your outside basis under IRC Sec. 704(d). For an S corporation, it is your stock and debt basis under IRC Sec. 1366(d).",
"The entity choice matters enormously here and it is where many STR owners create a problem without realizing it.",
"In a partnership or LLC taxed as a partnership, your basis includes your share of partnership liabilities under IRC Sec. 752. Qualified nonrecourse financing secured by real property is generally allocated to partners and increases basis. A partner who contributed $200,000 of cash to a property with $600,000 of debt has basis well above their cash contribution.",
"In an S corporation, shareholders do not receive basis for entity-level debt they have not personally lent to the corporation. A shareholder who contributed $200,000 to an S corporation holding a property with $600,000 of bank debt has $200,000 of basis, full stop.",
"That means an STR generating a $340,000 first-year loss from a cost segregation study, held in an S corporation with $200,000 of shareholder basis, produces a $200,000 deduction and a $140,000 suspended loss. The same property in an LLC taxed as a partnership produces the full deduction.",
"This is the single strongest argument against holding appreciating real estate in an S corporation, alongside the taxable distribution problem under IRC Sec. 311(b).",
"Losses blocked by basis carry forward indefinitely and are allowed when basis is restored through additional contributions, income allocations, or, in a partnership, additional debt.",
]),
("Limit Two: At Risk", [
"IRC Sec. 465 limits deductible losses to the amount you have at risk in the activity.",
"You are at risk for cash contributed, the adjusted basis of property contributed, and amounts borrowed for which you are personally liable or have pledged property other than property used in the activity.",
"You are not at risk for nonrecourse debt, generally. But there is a critical exception: qualified nonrecourse financing under IRC Sec. 465(b)(6) is treated as at risk for activities of holding real property.",
"Qualified nonrecourse financing means debt borrowed with respect to holding real property, from a qualified person such as a bank or other person actively and regularly engaged in lending, that is not convertible, and for which no person is personally liable.",
"Conventional bank and agency mortgages on real property generally qualify. That means most STR owners clear the at-risk limitation without difficulty.",
"Where it becomes a problem is seller financing from a related party, loans from the promoter or a related entity, and certain mezzanine or preferred equity structures. An owner who bought from a family member on a seller note may find the debt is not qualified nonrecourse financing and therefore not at risk.",
]),
("Limit Three: Passive Activity", [
"IRC Sec. 469 is where the STR analysis usually starts and is the third gate, not the first.",
"Under Treasury Regulation Sec. 1.469-1T(e)(3)(ii)(A), an activity is not a rental activity where the average period of customer use is seven days or less. That removes the automatic passive classification.",
"You then must materially participate under Treasury Regulation Sec. 1.469-5T. If you do, the loss is non-passive and offsets wages, business income, and portfolio income.",
"If you do not, the loss is passive, offsets only passive income, and suspends. It carries forward indefinitely and releases on a fully taxable disposition of the entire interest under IRC Sec. 469(g).",
]),
("The Excess Business Loss Limitation", [
"There is a fourth limit that applies after all three, and it catches high-income owners who cleared everything else.",
"Under IRC Sec. 461(l), a non-corporate taxpayer's aggregate net business loss deductible against non-business income is capped at an inflation-adjusted threshold. For 2025 the threshold is $313,000 for single filers and $626,000 for joint filers.",
"An excess business loss is not lost. It converts to a net operating loss carryforward under IRC Sec. 172, deductible in future years subject to the 80% of taxable income limitation.",
"For an STR investor who ran three cost segregation studies in one year producing $900,000 of non-passive loss against $700,000 of W-2 income, this limitation is binding and part of the benefit defers.",
"Because non-passive STR losses count as business losses for this purpose, high-income owners stacking multiple studies in a single year should model the limitation rather than assuming the full deduction lands currently.",
]),
("Worked Example: Same Loss, Three Structures", [
"An investor acquires a $980,000 short-term rental with $240,000 of cash and a $740,000 conventional bank mortgage. A cost segregation study produces a $268,000 first-year loss. The investor materially participates and the average stay is 5.1 nights.",
"Structure one, held directly or in a single-member LLC: basis is $980,000, well above the loss. Qualified nonrecourse financing means the full amount is at risk. Material participation makes the loss non-passive. The full $268,000 is deductible.",
"Structure two, held in an LLC taxed as a partnership with two members: each member's outside basis includes their share of the $740,000 of qualified nonrecourse debt under IRC Sec. 752. Both are at risk. The full loss flows through and is deductible.",
"Structure three, held in an S corporation: the shareholder's basis is the $240,000 contributed, because entity-level bank debt does not create shareholder basis. The deductible loss is capped at $240,000, with $28,000 suspended under IRC Sec. 1366(d) until basis is restored.",
"Same property, same study, same participation. The entity choice cost $28,000 of current deduction, and would cost far more on a larger loss.",
]),
("Practical Guidance", [
"Hold short-term rentals in an LLC taxed as a partnership or as a disregarded entity, not in an S corporation. The basis rules and the distribution rules both favor it.",
"Confirm that acquisition debt is qualified nonrecourse financing for at-risk purposes, particularly with seller financing or related-party loans.",
"Track basis and at-risk amounts by activity from acquisition. Reconstructing them later is expensive, and both limits carry forward indefinitely, which means the records matter for the whole hold period.",
"Model the excess business loss limitation before stacking multiple studies into one year. Spreading acquisitions or elections across two years can convert a deferred benefit into a current one.",
]),
],
"faqs": [
("What limits apply to a short-term rental loss?",
 "Four, in order: basis under IRC Sec. 704(d) or Sec. 1366(d), at risk under IRC Sec. 465, passive activity under IRC Sec. 469, and the excess business loss limitation under IRC Sec. 461(l). Clearing material participation only addresses the third one."),
("Why does an S corporation limit my STR loss?",
 "Because shareholders do not receive basis for entity-level debt they have not personally lent to the corporation. A partner in an LLC taxed as a partnership does receive basis for qualified nonrecourse financing under IRC Sec. 752, which is why partnerships and disregarded entities are preferred for real estate."),
("Is my mortgage at risk?",
 "Conventional bank and agency mortgages on real property generally qualify as qualified nonrecourse financing under IRC Sec. 465(b)(6) and are treated as at risk. Seller financing from a related party, promoter loans, and some mezzanine structures may not qualify."),
("What happens to a loss blocked by basis?",
 "It carries forward indefinitely and becomes deductible when basis is restored through additional contributions, income allocations, or, in a partnership, additional debt allocated to you. It is deferred, not lost."),
("What is the excess business loss limitation?",
 "Under IRC Sec. 461(l), a non-corporate taxpayer's net business loss against non-business income is capped at an inflation-adjusted threshold, $626,000 joint for 2025. The excess converts to a net operating loss carryforward. Non-passive STR losses count as business losses for this purpose."),
],
"related": [
("/blog/deducting-str-losses-against-w2-income/", "Deducting STR losses against W-2 income"),
("/blog/should-i-put-my-airbnb-in-an-llc-or-s-corp/", "LLC versus S corp for an Airbnb"),
("/short-term-rentals/", "Short-term rental tax strategy"),
],
"cta_head": "The Entity Decision Is Worth More Than the Study",
"cta_body": "Basis and at-risk limits are set at acquisition and are hard to fix later. Bring your structure, financing, and acquisition plan before you close.",
},

{
"slug": "str-39-year-recovery-period-nonresidential",
"title": "Why Your Short-Term Rental Is 39-Year Property, Not 27.5",
"meta_title": "STR 39-Year Recovery Period and Nonresidential Property (2026) | AE Tax Advisors",
"meta_desc": "A property with average stays of 30 days or less is generally nonresidential on a 39-year schedule. Why it usually does not matter, and when it does.",
"category": STR, "date": D,
"intro": [
"Most short-term rental owners assume their property depreciates over 27.5 years like any residential rental. For a genuine short-term rental, that is usually wrong.",
"Under IRC Sec. 168(e)(2)(A), residential rental property requires that 80% or more of gross rental income come from dwelling units, and the definition of a dwelling unit excludes units in an establishment where more than half the units are used on a transient basis. A property rented in stays of a week or less is transient.",
"That pushes the structural component to a 39-year nonresidential schedule. It matters less than it sounds, and it matters more in one specific case.",
],
"sections": [
("The Transient Use Exclusion", [
"IRC Sec. 168(e)(2)(A)(ii)(I) provides that a dwelling unit does not include a unit in a hotel, motel, or other establishment where more than half the units are used on a transient basis.",
"There is no bright line defining transient in this provision, but the widely applied standard follows the average period of customer use, and stays of 30 days or less are generally treated as transient.",
"A single-family home rented on Airbnb with an average stay of four nights is functioning as transient lodging. The structure is nonresidential real property with a 39-year recovery period under IRC Sec. 168(c).",
"A property rented on annual leases is plainly residential at 27.5 years. A mid-term rental with 60 to 90 day stays is residential as well, since those stays are not transient.",
"The awkward zone is 8 to 29 day average stays, which are too long for the passive activity seven-day exception and arguably short enough to be transient for the depreciation classification. Owners in that zone can face the worst of both: a 39-year schedule and a rental activity classification.",
]),
("Why It Usually Does Not Matter Much", [
"The difference between 27.5 and 39 years applies only to the structural component. A cost segregation study moves 20% to 30% of basis into five-year and 15-year property that is bonus eligible under IRC Sec. 168(k) regardless of the structure's recovery period.",
"On a property with $700,000 of depreciable basis and 26% reclassification, $182,000 is fully deductible in year one either way. The remaining $518,000 of structure produces $18,836 annually at 27.5 years versus $13,282 at 39 years.",
"The annual difference is $5,554, which at a 37% rate is about $2,055 per year. Real, but not decisive.",
"By comparison, the material participation determination on the same property is worth $67,000 in year one. The classification question is a rounding error next to it.",
]),
("Where It Does Matter", [
"Conversion. An owner who operates a property as a short-term rental and later converts it to long-term rental, or the reverse, has a change in the property's classification.",
"The recovery period is generally determined when the property is placed in service, and a change in use triggers the rules in Treasury Regulation Sec. 1.168(i)-4. A change from nonresidential to residential use, or the reverse, requires computing depreciation for the year of change and subsequent years as though the property had been originally placed in service with the new classification, using the adjusted basis at the beginning of the year of change.",
"Owners who flip between STR and LTR operation, which is common when occupancy or regulation changes, need to track this rather than continuing on the original schedule.",
"Qualified improvement property. QIP under IRC Sec. 168(e)(6) applies only to nonresidential real property. An STR classified as nonresidential can treat qualifying interior improvements as 15-year QIP with full bonus eligibility. A residential rental cannot.",
"This is genuinely favorable and cuts the other way from the recovery period. An owner who renovates the interior of a nonresidential short-term rental may deduct that work in year one rather than over 27.5 years.",
]),
("The Bonus Depreciation Interaction", [
"Neither 27.5-year nor 39-year property is bonus eligible. Bonus depreciation under IRC Sec. 168(k) applies only to property with a recovery period of 20 years or less.",
"So the structural classification question never affects the bonus depreciation available. What affects it is the reclassification percentage from the cost segregation study, which is driven by the property's components rather than by its recovery period.",
"Short-term rentals typically reclassify well because they are furnished. Furniture, appliances, electronics, housewares, decor, and outdoor equipment are all five-year property, and a fully furnished property carries $25,000 to $70,000 of it.",
]),
("Documenting the Classification", [
"The classification should be supported by the property's actual operating data: average length of stay pulled from the booking platform or property management system, occupancy, and booking counts.",
"That same data supports or undermines the passive activity analysis, so it is worth pulling annually and retaining regardless.",
"Where a property's operating model changes materially, document the change and the date, since it affects both the depreciation classification and the passive activity treatment from that point forward.",
]),
("Worked Example: Classification and Renovation", [
"An investor acquires a $840,000 beach property, furnishes it for $46,000, and operates it with an average stay of 5.3 nights. Land is allocated at $180,000, leaving $660,000 of depreciable building basis.",
"The property is nonresidential real property on a 39-year schedule because more than half the use is transient.",
"A cost segregation study reclassifies 27%, producing $178,200 of five-year and 15-year property, all bonus eligible. The $46,000 of furnishings is separately five-year property, fully deductible.",
"Structural basis of $481,800 depreciates at $12,354 annually rather than $17,520 under a 27.5-year schedule, a difference of $5,166 per year.",
"Two years later the owner spends $118,000 renovating the interior. Because the property is nonresidential, the qualifying portion is QIP under IRC Sec. 168(e)(6), carrying a 15-year life with full bonus eligibility. Roughly $96,000 of the renovation is deductible in the year placed in service.",
"Under a 27.5-year residential classification, QIP would have been unavailable and the same renovation would have depreciated over 27.5 years at roughly $3,490 annually.",
"The 39-year classification cost $5,166 per year on the structure and saved roughly $92,000 in the renovation year. On net, it was favorable.",
]),
],
"faqs": [
("Is my Airbnb 27.5-year or 39-year property?",
 "Generally 39-year nonresidential property if the average stay is short enough to be transient. IRC Sec. 168(e)(2)(A) excludes from dwelling units any unit in an establishment where more than half the units are used on a transient basis, and stays of 30 days or less are generally treated as transient."),
("How much does the difference cost me?",
 "Less than most owners expect. On $500,000 of structural basis, the annual difference is roughly $5,500 of depreciation, or about $2,000 of tax at a 37% rate. The material participation determination on the same property is worth far more."),
("Does the classification affect bonus depreciation?",
 "No. Bonus depreciation under IRC Sec. 168(k) applies only to property with a recovery period of 20 years or less, so neither 27.5-year nor 39-year structure is eligible either way. The reclassified five-year and 15-year components are bonus eligible regardless."),
("Is 39-year classification ever better?",
 "Yes, for renovations. Qualified improvement property under IRC Sec. 168(e)(6) applies only to nonresidential real property. An owner renovating the interior of a nonresidential STR can deduct the qualifying work in year one, which a residential rental owner cannot."),
("What happens if I convert from short-term to long-term rental?",
 "The classification changes, and Treas. Reg. Sec. 1.168(i)-4 governs. Depreciation for the year of change and later years is computed as though the property had originally been placed in service under the new classification, using adjusted basis at the beginning of the year of change."),
],
"related": [
("/blog/str-vs-ltr-tax-treatment-differences/", "STR versus LTR tax treatment"),
("/blog/landlord-guide-depreciation-27-5-vs-39-year/", "27.5 versus 39 year depreciation"),
("/blog/how-to-convert-long-term-rental-to-short-term-rental-for-taxes/", "Converting an LTR to an STR"),
],
"cta_head": "The Classification Is Not the Decision That Matters Most",
"cta_body": "Owners often fixate on 27.5 versus 39 while missing the participation question worth ten times as much. Bring your booking data and we will address both.",
},

{
"slug": "str-depreciation-recapture-selling-short-term-rental",
"title": "Depreciation Recapture When You Sell a Short-Term Rental",
"meta_title": "STR Depreciation Recapture on Sale (2026 Guide) | AE Tax Advisors",
"meta_desc": "Cost segregation creates Sec. 1245 property that recaptures at ordinary rates. How STR recapture is layered at sale and the three ways to manage it.",
"category": STR, "date": D,
"intro": [
"The cost segregation study that produced a $240,000 first-year deduction did not eliminate tax. It moved it. When you sell, the depreciation comes back, and a meaningful portion of it comes back at ordinary rates rather than capital gain rates.",
"Understanding how the layers work is what separates an investor who plans the exit from one who is surprised by it.",
],
"sections": [
("The Three Layers of Gain", [
"On sale, total gain is the amount realized less adjusted basis, where adjusted basis is original cost plus improvements less all depreciation claimed. Because the study accelerated depreciation, adjusted basis is lower and gain is larger than it otherwise would have been.",
"That gain is then allocated into three layers, each taxed differently, in a specific order.",
"Layer one is Sec. 1245 recapture. Under IRC Sec. 1245, gain on personal property is recaptured as ordinary income to the extent of depreciation claimed on it. All of the five-year property identified in the study, the appliances, furniture, carpet, decorative lighting, and specialty finishes, is Sec. 1245 property. This layer is taxed at ordinary rates up to 37%.",
"Layer two is unrecaptured Sec. 1250 gain. This is the straight-line depreciation claimed on the building structure and on 15-year land improvements. Because MACRS depreciates real property on a straight-line basis, there is generally no Sec. 1250 ordinary recapture, but this gain is taxed at a maximum 25% rate under IRC Sec. 1(h)(1)(E) rather than the lower long-term capital gain rate.",
"Layer three is the remaining gain, which is long-term capital gain taxed at 0%, 15%, or 20% depending on income, plus the 3.8% net investment income tax where applicable.",
]),
("Why the Study Increases the Ordinary Layer", [
"Without a study, essentially all depreciation on a rental is straight-line on the building, producing unrecaptured Sec. 1250 gain at 25%.",
"With a study, 20% to 30% of basis moved into Sec. 1245 property, and the depreciation on that property recaptures at ordinary rates.",
"On a property where the study identified $190,000 of five-year property fully deducted in year one, that $190,000 recaptures as ordinary income on sale.",
"At a 37% ordinary rate versus a 25% unrecaptured Sec. 1250 rate, the differential cost is 12 points on $190,000, or approximately $22,800.",
"That is the true cost of the study's acceleration, and it should be compared against the benefit rather than ignored.",
]),
("The Arithmetic Usually Still Favors the Study", [
"The comparison is not deduction versus recapture. It is the present value of a deduction taken now against the present value of tax paid at sale.",
"A $190,000 deduction at a 37% rate saves $70,300 today. The recapture on the same $190,000 at a 37% rate costs $70,300 at sale. If the sale is seven years out, the taxpayer had free use of $70,300 for seven years.",
"At an 8% opportunity cost, that use is worth roughly $50,000. The study wins clearly.",
"The arithmetic reverses in two cases. A very short hold, where the deferral period is too brief to generate meaningful value. And a taxpayer whose rate is materially higher at sale than at deduction, which can happen for someone early in a career or someone whose income spikes in the sale year.",
"For most STR investors in a high bracket planning a multi-year hold, the study is clearly correct.",
]),
("Method One: 1031 Exchange", [
"A like-kind exchange under IRC Sec. 1031 defers the entire gain, including both recapture layers. No tax is recognized, and the deferred gain carries into the replacement property through a reduced basis.",
"Since 2017, Sec. 1031 applies only to real property. The furniture, appliances, and other personal property in a furnished short-term rental is not like-kind and is boot, triggering recognition of the Sec. 1245 recapture attributable to it.",
"That is a real limitation for furnished properties. An investor exchanging a short-term rental with $58,000 of furnishings will recognize the recapture on that personal property even in an otherwise fully deferred exchange.",
"The practical answer is to structure the sale so that personal property is sold separately with non-exchange funds allocated to it, and to accept the recapture on that portion while deferring the real property gain.",
]),
("Method Two: Installment Sale", [
"An installment sale under IRC Sec. 453 spreads capital gain across the years payments are received, keeping the seller in lower brackets and reducing net investment income tax exposure.",
"But IRC Sec. 453(i) requires that Sec. 1245 recapture be recognized in full in the year of sale, regardless of how little cash is received.",
"For an STR with heavy Sec. 1245 property from a study, this means the ordinary income layer is due immediately. A seller taking a small down payment can owe more tax than they received.",
"The planning answer is to size the down payment against the recapture liability. A seller with $190,000 of Sec. 1245 recapture needs enough cash at closing to fund roughly $70,000 of tax before anything else.",
]),
("Method Three: Hold Until Death", [
"Under IRC Sec. 1014, property held until death receives a stepped-up basis equal to fair market value at the date of death. All accumulated depreciation and all appreciation disappear for income tax purposes. There is no recapture.",
"This is the cleanest outcome available and it is the actual endgame of a buy, depreciate, refinance, hold strategy.",
"An investor who runs studies, refinances to extract equity tax free, exchanges rather than sells, and holds until death never pays the deferred tax. The heirs take a stepped-up basis and can sell with little or no gain.",
"The estate tax analysis is separate and depends on the size of the estate relative to the exclusion, but for most investors the income tax result is complete elimination.",
]),
("Worked Example: STR Sale Six Years Out", [
"An investor bought a short-term rental for $920,000 with $175,000 of land, ran a study reclassifying 28%, and furnished it for $52,000. Total first-year depreciation was approximately $260,600.",
"Six years later they sell for $1,340,000. Total depreciation claimed across six years is $342,000, of which $208,600 was on Sec. 1245 property including furnishings and $133,400 was straight-line on structure and land improvements.",
"Adjusted basis is $972,000 less $342,000, or $630,000. Total gain is $710,000.",
"Layer one: $208,600 of Sec. 1245 recapture at ordinary rates. At 37%, that is $77,182.",
"Layer two: $133,400 of unrecaptured Sec. 1250 gain at 25%, or $33,350.",
"Layer three: $368,000 of long-term capital gain at 20% plus 3.8% net investment income tax, or $87,584.",
"Total federal tax is approximately $198,116.",
"Had the investor executed a 1031 exchange instead, allocating $38,000 of the price to remaining personal property sold outside the exchange, they would have recognized only the recapture attributable to that personal property and deferred approximately $180,000 of tax.",
]),
],
"faqs": [
("Does cost segregation increase my tax when I sell?",
 "It shifts part of the gain from the 25% unrecaptured Sec. 1250 rate to ordinary rates up to 37%, because the reclassified five-year property is Sec. 1245 property. On $190,000 of such property that differential is roughly $22,800, which is generally far less than the value of the deferral."),
("How is STR gain taxed on sale?",
 "In three layers: Sec. 1245 recapture on personal property at ordinary rates, unrecaptured Sec. 1250 gain on the building and land improvements at up to 25%, and remaining gain as long-term capital gain, plus the 3.8% net investment income tax where applicable."),
("Does a 1031 exchange defer the recapture?",
 "For the real property, yes, entirely. But since 2017 Sec. 1031 applies only to real property, so furniture and appliances in a furnished STR are boot and the recapture attributable to them is recognized. Allocate and sell the personal property separately."),
("Can I spread the recapture over an installment sale?",
 "No. Under IRC Sec. 453(i), Sec. 1245 recapture is recognized in full in the year of sale regardless of cash received. Size your down payment against the recapture liability, since a small down payment can leave you owing more tax than you collected."),
("Is there any way to avoid recapture entirely?",
 "Holding until death. Under IRC Sec. 1014 the basis steps up to fair market value at death, eliminating all accumulated depreciation and appreciation for income tax purposes. This is the actual endgame of a buy, depreciate, exchange, hold strategy."),
],
"related": [
("/blog/what-happens-to-depreciation-when-i-sell-after-cost-segregation/", "Depreciation when you sell after cost segregation"),
("/blog/depreciation-recapture-planning/", "Depreciation recapture planning"),
("/blog/can-i-do-a-1031-exchange-on-a-short-term-rental/", "1031 exchanges on short-term rentals"),
],
"cta_head": "Model the Exit Before You Run the Study",
"cta_body": "The study is almost always correct, but the exit changes how you should structure the sale. Bring your basis, depreciation history, and hold plan.",
},

{
"slug": "str-placed-in-service-year-end-timeline",
"title": "The STR Placed in Service Deadline: What Has to Happen Before December 31",
"meta_title": "STR Placed in Service Year-End Timeline (2026) | AE Tax Advisors",
"meta_desc": "Depreciation starts when a property is ready and available for its intended use, not at closing. What must be complete before December 31 to claim the deduction.",
"category": STR, "date": D,
"intro": [
"The single most common way a short-term rental tax strategy fails in December is not material participation. It is the placed in service date.",
"Depreciation begins when property is placed in service, which means ready and available for its specifically assigned function. Not when you closed. Not when you paid for it. When it was ready to rent.",
"An investor who closes December 12 and takes their first booking in February has no depreciation deduction for the closing year at all.",
],
"sections": [
("What Placed in Service Actually Means", [
"Treasury Regulation Sec. 1.167(a)-11(e)(1)(i) provides that property is placed in service when it is first placed in a condition or state of readiness and availability for a specifically assigned function.",
"For a rental property, that means the property is ready and available to be rented. It does not require that a tenant or guest actually occupy it.",
"This distinction matters enormously in December. A property that is fully furnished, licensed, listed, and available for booking on December 28 is placed in service on December 28, even if the first guest arrives in January.",
"A property still awaiting furniture delivery, without a certificate of occupancy, or not yet listed anywhere, is not available and is not placed in service.",
]),
("The Checklist That Establishes Readiness", [
"Ownership and access. The closing must have occurred and you must control the property.",
"Physical readiness. Renovation substantially complete, utilities on and in your name, and the property habitable. Minor punch list items generally do not prevent placement in service, but a property with no functioning kitchen or no heat does.",
"Furnishings in place. For a furnished short-term rental, the property is not available to rent without beds, linens, kitchenware, and basic supplies. Delivery and installation dates matter and should be documented.",
"Regulatory compliance. Where the jurisdiction requires a short-term rental permit, business license, or registration, the property is generally not available to rent lawfully without it. Permit issuance dates are a common December bottleneck and are entirely outside your control once submitted.",
"Listed and bookable. The listing published on at least one platform with an available calendar is the clearest evidence of availability. A screenshot of the listing with the publication date, and the platform's own record of when the listing went live, is strong documentation.",
"Insurance in force appropriate to short-term rental use.",
]),
("What Does Not Establish Placement in Service", [
"Closing on the property. Acquisition alone does not place property in service.",
"Paying for furniture that has not been delivered. The de minimis and bonus depreciation rules for the furnishings themselves also turn on when those items were placed in service, so a December order delivered in January is a January asset.",
"Intending to rent. Intent without availability is not enough.",
"A booking accepted for a future date on a property that is not yet ready. The booking shows intent to operate but does not establish that the property was in a state of readiness.",
]),
("The Furnishings Are Separately Placed in Service", [
"This point is missed constantly. The building and the personal property inside it have their own placed in service dates.",
"Furniture, appliances, electronics, and housewares delivered and installed in December are five-year property placed in service in December, fully deductible under IRC Sec. 168(k) that year.",
"Items ordered in December but delivered in January are January assets, deductible the following year.",
"For a property carrying $50,000 of furnishings, the delivery timing is worth roughly $18,500 at a 37% rate. Ordering early enough for December delivery is a free decision that many owners make too late.",
"Mid-quarter convention considerations also apply. If more than 40% of the year's depreciable property placed in service falls in the fourth quarter, the mid-quarter convention applies rather than the half-year convention for personal property, which changes the first-year calculation. Bonus depreciation at 100% makes this largely academic for property that is fully expensed, but it matters where bonus is elected out of or unavailable.",
]),
("The Realistic December Timeline", [
"Working backward from December 31, a property acquired in the fourth quarter needs roughly this sequence.",
"Permit or license application submitted by early November in jurisdictions with processing time. This is the item most likely to blow the deadline and the one you cannot accelerate.",
"Furniture ordered by mid-November for December delivery, accounting for lead times on beds and larger items.",
"Utilities transferred and renovation punch list closed by mid-December.",
"Listing published and calendar opened by the third week of December, leaving room for platform review.",
"Documentation captured contemporaneously: listing screenshot with date, permit issuance date, delivery receipts, utility activation, and insurance binder.",
"An investor who closes on December 20 with an unfurnished property and no permit is not going to place it in service that year, and pushing the paperwork to claim otherwise creates exposure disproportionate to the benefit.",
]),
("When You Miss the Deadline", [
"Missing the year is not a disaster. The deduction is available in the following year when the property is genuinely placed in service, and the cost segregation study can be run then.",
"What you lose is a year of deferral, not the deduction itself.",
"For an investor who specifically needed the deduction in the closing year, perhaps against a large one-time income event, the alternative is a look-back study on a property already owned, filed with Form 3115. That places a catch-up deduction in the current year without needing a new acquisition to be ready.",
"This is the practical answer for an investor in December who realizes the new property will not make it: run the study on something you already own instead.",
]),
("Worked Example: Two Weeks Apart", [
"Investor A closes on a $760,000 short-term rental on November 8. Furniture is ordered November 12 and delivered December 4. The city permit, applied for November 10, is issued December 18. The listing goes live December 20 with an open calendar. First booking arrives January 9.",
"The property is placed in service December 20. A cost segregation study produces $174,000 of bonus eligible components, plus $47,000 of separately placed furnishings, for approximately $221,000 of first-year deduction. Material participation is documented at 112 hours from November through year end.",
"Investor B closes on a comparable property December 14. Furniture is ordered December 16 with a January 20 delivery. The permit application is submitted December 18 and issued January 22. The listing goes live January 26.",
"The property is placed in service in January. Investor B has zero depreciation in the closing year.",
"Investor B instead runs a look-back study on a rental acquired three years earlier, filing Form 3115 to claim a $138,000 catch-up deduction in the current year. That recovers most of the intended benefit from a property they already owned.",
]),
],
"faqs": [
("When is a short-term rental placed in service?",
 "When it is first in a condition of readiness and availability for its assigned function, under Treas. Reg. Sec. 1.167(a)-11(e)(1)(i). For a rental, that means ready and available to rent. A guest does not have to occupy it, but it must genuinely be bookable."),
("Does closing on the property place it in service?",
 "No. Acquisition alone is not enough. The property must be physically ready, furnished for a furnished rental, lawfully permitted where required, insured, and listed with an open calendar before it is available to rent."),
("What if my furniture arrives in January?",
 "Those items are placed in service in January and are deductible the following year, separately from the building. For a property with $50,000 of furnishings, the delivery date is worth roughly $18,500 at a 37% rate, so order early enough for December delivery."),
("Do I need a short-term rental permit before year end?",
 "Where the jurisdiction requires one, generally yes, because the property is not lawfully available to rent without it. Permit processing time is the most common December bottleneck and the one factor entirely outside your control once submitted."),
("What if I miss the deadline?",
 "You lose a year of deferral, not the deduction. The property is placed in service the following year and the study runs then. If you needed the deduction in the current year, a look-back study with Form 3115 on a property you already own can substitute."),
],
"related": [
("/blog/year-end-tax-planning-checklist-real-estate-investors/", "Year-end tax planning checklist"),
("/blog/form-3115-cost-segregation-catch-up/", "Form 3115 catch-up depreciation"),
("/short-term-rentals/", "Short-term rental tax strategy"),
],
"cta_head": "Start the Countdown in October, Not December",
"cta_body": "Permits and furniture lead times decide whether the deduction lands this year. Bring us your closing date and we will build the timeline backward.",
},

{
"slug": "passive-activity-loss-rules-rental-property",
"title": "Passive Activity Loss Rules for Rental Property: The Complete Framework",
"meta_title": "Passive Activity Loss Rules for Rental Property (2026) | AE Tax Advisors",
"meta_desc": "IRC Sec. 469 makes rental losses passive by default. The four exits, the $25,000 allowance, and how suspended losses eventually release, explained for 2026.",
"category": RE, "date": D,
"intro": [
"IRC Sec. 469 is the reason most rental property losses do not reduce your tax bill. Enacted in 1986 to shut down tax shelters, it classifies rental activity as passive by default and limits passive losses to passive income.",
"There are four ways out. Understanding which one applies to you is the difference between a deduction and a carryforward.",
],
"sections": [
("The Default Rule", [
"Under IRC Sec. 469(c)(2), rental activity is passive regardless of how much you participate. This is a per se rule, not a facts and circumstances test.",
"Passive losses offset passive income. They do not offset wages, business income from an activity you materially participate in, interest, dividends, or capital gains.",
"Losses that cannot be used are suspended under IRC Sec. 469(b) and carry forward indefinitely. They are not lost, but they are deferred, sometimes for decades.",
"Passive income includes income from other rental properties, from limited partnership interests, and from businesses in which you do not materially participate. Portfolio income such as interest and dividends is not passive income and cannot absorb passive losses.",
]),
("Exit One: The $25,000 Special Allowance", [
"IRC Sec. 469(i) permits a taxpayer who actively participates in rental real estate to deduct up to $25,000 of passive rental loss against non-passive income.",
"Active participation is a much lower standard than material participation. It requires bona fide involvement in management decisions such as approving tenants, setting rental terms, and approving expenditures. You need not perform the work yourself.",
"The allowance phases out at 50 cents per dollar of modified adjusted gross income above $100,000, disappearing entirely at $150,000. For married filing separately who lived apart all year, the amounts are halved.",
"You must own at least 10% of the activity by value.",
"For most of the high-income investors who benefit most from cost segregation, this exit is unavailable. It is genuinely useful for early-career investors and house hackers.",
]),
("Exit Two: Real Estate Professional Status", [
"Under IRC Sec. 469(c)(7), a taxpayer who spends more than 750 hours in real property trades or businesses in which they materially participate, and more than half of all personal service time in such businesses, is not subject to the per se rental rule.",
"Both tests must be met by one spouse individually. Hours cannot be combined between spouses for qualification.",
"Qualifying alone does not deduct anything. It removes the automatic classification, after which each rental activity must independently pass material participation under Treasury Regulation Sec. 1.469-5T.",
"The aggregation election under Treasury Regulation Sec. 1.469-9(g) treats all rental real estate interests as a single activity, so material participation is tested once across the portfolio. Without it, an investor with nine properties must materially participate in each separately.",
"This is the standard structure for a household with one high-earning spouse and one spouse managing real estate full time.",
]),
("Exit Three: The Seven-Day Rule", [
"Treasury Regulation Sec. 1.469-1T(e)(3)(ii)(A) provides that an activity is not a rental activity where the average period of customer use is seven days or less.",
"This is not an exception to the passive rules. It removes the activity from the rental category entirely, which means the per se rule in IRC Sec. 469(c)(2) never applies.",
"You then need only materially participate under Treasury Regulation Sec. 1.469-5T, which for a self-managed short-term rental can be reached through the 100-hour test where no other individual participates more.",
"This is why short-term rentals dominate high-income real estate tax planning. A physician working 2,200 hours cannot qualify as a real estate professional, but can plausibly spend 130 hours on a self-managed short-term rental.",
"A second exception applies where the average period of use is 30 days or less and significant personal services are provided, though the services standard is demanding and excludes cleaning, repairs, and utilities.",
]),
("Exit Four: Passive Income", [
"The simplest exit is to generate passive income that the losses can absorb.",
"An investor with a portfolio where some properties produce income and others produce losses nets them within the passive bucket automatically.",
"Investors sometimes acquire a passive income generator deliberately for this purpose, often a stabilized property or a limited partnership interest in an income-producing deal, specifically to release suspended losses.",
"Self-rental income is a trap here. Under Treasury Regulation Sec. 1.469-2(f)(6), net rental income from property leased to a business in which you materially participate is recharacterized as non-passive, so it cannot absorb passive losses. A net loss from the same property generally remains passive. The rule is deliberately asymmetric.",
]),
("How Suspended Losses Eventually Release", [
"Under IRC Sec. 469(g)(1), disposing of your entire interest in a passive activity in a fully taxable transaction to an unrelated party releases the suspended losses, which become non-passive and offset any income.",
"All three conditions must be met. A partial sale does not release losses from a grouped activity unless you can establish the allocable amount with reasonable certainty under Treasury Regulation Sec. 1.469-4(g). A 1031 exchange is not fully taxable and defers the release. A sale to a related party does not release them.",
"A gift does not release them either. Under IRC Sec. 469(j)(6), suspended losses on gifted property are added to the donee's basis and the donor loses them.",
"At death, IRC Sec. 469(g)(2) allows suspended losses on the final return only to the extent they exceed the step-up in basis. Because step-ups are usually large, most suspended losses are eliminated at death rather than deducted.",
]),
("Worked Example: Four Investors", [
"Investor A earns $118,000, owns two rentals producing a $34,000 loss, and actively participates. The $25,000 allowance phases down to $16,000 at their income level. They deduct $16,000 and suspend $18,000.",
"Investor B earns $640,000 as a surgeon with a spouse managing seven rentals full time. The spouse logs 1,240 hours, qualifies as a real estate professional, and the aggregation election is filed. Cost segregation studies produce $340,000 of loss, fully non-passive against the surgeon's income.",
"Investor C earns $520,000 as a software executive with no spouse available to qualify. They buy a short-term rental with an average stay of 4.8 nights, self-manage, and log 141 hours with no other individual exceeding that. A $196,000 study deduction is non-passive.",
"Investor D earns $410,000 and owns four long-term rentals producing $88,000 of loss with no exit available. The entire loss suspends. Three years later they sell one property in a fully taxable sale to an unrelated buyer and, having kept property-level suspended loss records, release the allocable portion against the gain.",
]),
],
"faqs": [
("Why can I not deduct my rental loss?",
 "Because IRC Sec. 469(c)(2) classifies rental activity as passive per se, regardless of your involvement. Passive losses offset only passive income and suspend otherwise. There are four exits: the $25,000 allowance, real estate professional status, the seven-day rule, and passive income."),
("What is the $25,000 rental loss allowance?",
 "Under IRC Sec. 469(i), a taxpayer who actively participates may deduct up to $25,000 of passive rental loss against other income. It phases out between $100,000 and $150,000 of modified adjusted gross income, so most high earners cannot use it."),
("How is the seven-day rule different from real estate professional status?",
 "REPS removes the per se rental classification but you must still materially participate in each activity. The seven-day rule removes the activity from the rental category entirely, so only material participation applies. The seven-day route is reachable for a full-time professional; REPS generally is not."),
("Do suspended losses expire?",
 "No. They carry forward indefinitely under IRC Sec. 469(b) and release when you dispose of your entire interest in a fully taxable transaction to an unrelated party under IRC Sec. 469(g). They are eliminated only at death to the extent of the step-up in basis, or if you gift the property."),
("Can self-rental income absorb my passive losses?",
 "No. Under Treas. Reg. Sec. 1.469-2(f)(6), net rental income from property leased to a business you materially participate in is recharacterized as non-passive, so it cannot absorb passive losses. A net loss from the same property generally stays passive. The rule is asymmetric by design."),
],
"related": [
("/blog/what-is-the-25000-rental-loss-allowance/", "The $25,000 rental loss allowance"),
("/blog/what-is-the-750-hour-rule-for-real-estate-professionals/", "The 750 hour rule"),
("/blog/what-happens-to-suspended-passive-losses-when-i-sell/", "Releasing suspended passive losses"),
],
"cta_head": "Find Your Exit Before You Buy",
"cta_body": "Which of the four exits is available to you determines what kind of property you should be buying. Bring your income, your household, and your portfolio.",
},

{
"slug": "defined-benefit-plan-high-income-business-owners",
"title": "Defined Benefit Plans for High Income Business Owners: When $250,000 of Deduction Is Available",
"meta_title": "Defined Benefit Plans for High Income Business Owners (2026) | AE Tax Advisors",
"meta_desc": "A defined benefit or cash balance plan can deduct $150,000 to $300,000 annually. Who qualifies, what staff costs, and the commitment it requires.",
"category": BO, "date": D,
"intro": [
"A defined contribution plan caps total additions at $70,000 for 2025 plus catch-up. That is the ceiling for a 401(k) with profit sharing, no matter how profitable your business is.",
"A defined benefit plan has no such cap. The contribution is whatever an actuary determines is required to fund a promised benefit, and for an owner in their fifties with strong income, that number routinely lands between $150,000 and $300,000 annually, fully deductible.",
"It is the largest deduction available to most business owners and the least understood.",
],
"sections": [
("How the Contribution Is Determined", [
"A defined benefit plan promises a specific benefit at retirement, expressed as an annual amount. The maximum annual benefit under IRC Sec. 415(b) is the lesser of a dollar limit, $280,000 for 2025, or 100% of the participant's average compensation for the three highest consecutive years.",
"An actuary then calculates what must be contributed each year to fund that promised benefit by the participant's normal retirement age, given current assets, expected returns, and the years remaining.",
"Two variables drive the contribution upward: age and compensation. An older participant has fewer years to fund the benefit, so the annual contribution is larger. Higher compensation supports a larger promised benefit.",
"A 58-year-old owner with $350,000 of compensation and ten years to normal retirement age can often support a contribution above $250,000. A 38-year-old with the same compensation and thirty years might support $80,000.",
"A cash balance plan is a defined benefit plan expressed as a hypothetical account balance with a stated pay credit and interest credit. It behaves like a defined benefit plan for funding and deduction purposes while presenting to participants like an account, which is why it has largely displaced traditional defined benefit designs for small businesses.",
]),
("Stacking With a 401(k)", [
"A defined benefit plan is layered on top of a 401(k) with profit sharing rather than replacing it.",
"Where both plans exist, the employer deduction for the defined contribution plan is limited to 6% of covered compensation under IRC Sec. 404(a)(7), unless the defined benefit plan is covered by the Pension Benefit Guaranty Corporation. Employee elective deferrals are not counted against this limit.",
"The practical result for a typical owner is roughly $23,500 of employee deferral plus catch-up, plus a 6% employer profit sharing contribution, plus the full defined benefit contribution.",
"For a 55-year-old owner, the combined deduction commonly reaches $280,000 to $350,000 annually.",
]),
("The Staff Cost Is the Deciding Factor", [
"Defined benefit plans must satisfy minimum participation, coverage, and nondiscrimination requirements. Employees generally must be covered.",
"The plan can be designed to minimize staff cost through eligibility requirements, benefit formulas that provide small benefits to staff, and cross-testing that combines the defined benefit and defined contribution plans for testing purposes.",
"Favorable demographics mean an older owner and a younger, lower-paid workforce. A 57-year-old owner with staff averaging 33 produces excellent ratios, often 8 to 1 or better in owner benefit to staff cost.",
"Unfavorable demographics mean staff close to the owner's age and compensation. A three-partner firm where all partners are 55 and two senior employees are 52 produces a much worse ratio.",
"For a business with no employees other than the owner and spouse, the staff cost is zero and the analysis is straightforward.",
"The staff cost must be quantified by an actuary before adoption, not estimated. This is the single most important number in the decision.",
]),
("The Commitment Is Real", [
"This is not a discretionary plan. Minimum required contributions under IRC Sec. 430 must be made annually, and failure triggers excise taxes under IRC Sec. 4971 and reporting obligations.",
"The plan should be established with the expectation of maintaining it for at least three to five years. Terminating a plan shortly after adoption without a valid business reason risks a determination that it was never intended to be permanent, which can disqualify it retroactively.",
"There is flexibility within the commitment. The benefit formula can be amended prospectively, contribution ranges exist between minimum required and maximum deductible amounts, and in a genuinely bad year a plan can be frozen. But an owner whose income swings from $900,000 to $150,000 unpredictably is a poor candidate.",
"Investment risk sits with the employer. If plan assets underperform the assumed rate, required contributions increase. If they outperform, contributions decrease and the deduction shrinks. Most small plans use conservative investment allocations specifically to keep the funding path predictable.",
]),
("Costs and Administration", [
"Actuarial and administration fees typically run $2,500 to $6,000 annually for a small plan, plus setup costs. Annual Form 5500 filing and an actuarial certification on Schedule SB are required.",
"PBGC coverage applies to most defined benefit plans but professional service employers with 25 or fewer participants are generally exempt. Where PBGC coverage applies, premiums are an additional annual cost, and the combined plan deduction limit under IRC Sec. 404(a)(7) does not apply, which is favorable.",
"These costs are trivial relative to a $200,000 deduction and should not drive the decision.",
]),
("Who Should Not Do This", [
"A business with volatile income that cannot reliably fund the minimum contribution.",
"A business with a workforce demographically similar to the owner, where staff cost consumes too much of the benefit.",
"An owner who is not yet maximizing a 401(k) with profit sharing. Fill the cheaper bucket first.",
"An owner within a few years of selling, where the plan will need to be terminated shortly after adoption.",
"An owner under 40 with modest income, where the actuarial contribution is not much larger than what a defined contribution plan already permits.",
]),
("Worked Example: Two Owner Firms", [
"Firm A is a 56-year-old consultant with $680,000 of net income and two employees aged 29 and 34 earning $62,000 and $71,000.",
"The 401(k) with safe harbor and cross-tested profit sharing directs $70,000 to the owner at approximately $9,800 of staff cost. A cash balance plan adds $237,000 for the owner at approximately $16,400 of additional staff cost.",
"Total owner deduction is $307,000 at $26,200 of staff cost, a ratio of nearly 12 to 1. At a combined 42% marginal rate, the tax reduction is approximately $129,000 against $26,200 of staff cost plus $5,000 of administration.",
"Firm B is a three-partner architecture firm where partners are 54, 56, and 58, with four senior staff aged 47 to 55 earning $110,000 to $145,000.",
"The same design produces $580,000 of partner contributions but requires approximately $198,000 of staff contributions, a ratio of under 3 to 1.",
"Firm B may still proceed, since the staff contributions are themselves deductible and serve a retention purpose, but the analysis is entirely different and should be run explicitly rather than assumed from Firm A's result.",
]),
],
"faqs": [
("How much can a defined benefit plan deduct?",
 "There is no fixed dollar cap. An actuary determines the required contribution to fund a promised benefit, which for an owner in their fifties with strong income commonly lands between $150,000 and $300,000 annually, fully deductible."),
("Can I have a defined benefit plan and a 401(k)?",
 "Yes, and stacking them is standard. Where both exist, the employer deduction for the defined contribution plan is limited to 6% of covered compensation under IRC Sec. 404(a)(7) unless the DB plan is PBGC covered. Employee deferrals are not counted against that limit."),
("What does a defined benefit plan cost me in staff contributions?",
 "It depends entirely on demographics. An older owner with a younger, lower-paid workforce often achieves an 8 to 1 or better ratio of owner benefit to staff cost. A firm where staff are close to the owner in age and pay may see 3 to 1 or worse. Have an actuary quantify it before adopting."),
("Am I locked in once I start?",
 "Substantially. Minimum required contributions under IRC Sec. 430 must be made annually, with excise taxes under IRC Sec. 4971 for failures. Plan for at least three to five years. There is flexibility through contribution ranges and prospective amendments, but it is not a discretionary plan."),
("Who is a poor candidate?",
 "Owners with volatile income, businesses whose staff demographics resemble the owner, anyone not already maxing a 401(k) with profit sharing, owners within a few years of selling, and younger owners whose actuarial contribution would not much exceed defined contribution limits."),
],
"related": [
("/blog/cash-balance-plans-business-owners-2026/", "Cash balance plans for business owners"),
("/blog/defined-benefit-plan-vs-401k-for-small-business-owners/", "Defined benefit plan versus 401(k)"),
("/blog/how-to-shelter-300k-per-year-with-retirement-plans/", "Sheltering $300K per year with retirement plans"),
],
"cta_head": "Get the Actuarial Numbers Before You Decide",
"cta_body": "The staff cost is the whole decision and it cannot be estimated reliably. We will get you a projection with real numbers for your census.",
},

{
"slug": "mid-year-tax-planning-checklist-business-owners",
"title": "Mid-Year Tax Planning Checklist for Business Owners",
"meta_title": "Mid-Year Tax Planning Checklist for Business Owners (2026) | AE Tax Advisors",
"meta_desc": "June and July are when tax planning actually works. Twelve items to review at mid-year while every option is still open, before December closes them.",
"category": BO, "date": D,
"intro": [
"Most tax planning happens in December, which is when the fewest options remain. Retirement plans that had to be adopted by year end, entity elections with March deadlines, and accounting method changes that take months to prepare are all decided by then.",
"Mid-year is when the work should happen. Here is what to review while the year is still changeable.",
],
"sections": [
("One: Project the Full Year Now", [
"Everything else depends on this. Take six months of actual results, project the remainder, and compute an estimated taxable income and tax for the year.",
"The projection does not need to be precise. It needs to be close enough to tell you which bracket you are landing in, whether you are above or below the qualified business income threshold, whether you will cross the net investment income tax threshold, and how far you are from any relevant cliff.",
"Without this number, every subsequent decision is a guess.",
]),
("Two: Confirm the Estimated Tax Safe Harbor", [
"Compute the safe harbor amount under IRC Sec. 6654: 100% of prior year tax, or 110% if prior year adjusted gross income exceeded $150,000.",
"Compare it to what you have actually paid through the June installment. If you are short, correct it now rather than in December.",
"Note that withholding is treated as paid ratably across the year under IRC Sec. 6654(g), so a year-end withholding increase can still cure earlier shortfalls. Estimated payments cannot.",
]),
("Three: Reassess Reasonable Compensation", [
"If your S corporation income is running well above or below prior year, the salary set in January may no longer be defensible or optimal.",
"Above the QBI income threshold, salary drives the W-2 wage limitation and cutting it can cost more in lost deduction than it saves in payroll tax. Below the threshold, the calculus reverses.",
"Adjusting salary at mid-year is straightforward. Adjusting it in December means either a large catch-up payroll or an indefensible full-year number.",
]),
("Four: Decide the Retirement Plan Before the Deadline", [
"A new 401(k) generally must be established by the end of the tax year to allow employee deferrals for that year, though the SECURE Act permits certain plans to be adopted by the return due date for employer contributions only.",
"A safe harbor 401(k) has an earlier deadline still, generally requiring adoption before October 1 for a new plan covering the current year.",
"A defined benefit or cash balance plan requires an actuarial study, plan document drafting, and often a census analysis, which takes weeks. Starting in December means starting for next year.",
"If a plan upgrade is on the table, the decision belongs in July.",
]),
("Five: Review Equipment and Fixed Asset Timing", [
"Identify what you plan to buy in the next twelve months and decide which side of December 31 each purchase belongs on.",
"Remember that the deduction follows the placed in service date, not the payment date, and that financing does not reduce the deduction. A December delivery with 10% down produces the same write-off as a cash purchase.",
"Decide between Sec. 179 and bonus depreciation deliberately. Sec. 179 gives asset-level control and cannot create a loss. Bonus applies by class and can. State conformity often decides it.",
]),
("Six: Model Any Cost Segregation Study", [
"If you acquired or improved real property in the last several years, determine whether a study is worthwhile and, critically, which year it should land in.",
"A look-back study with Form 3115 can place a catch-up deduction in any open year, which means the deduction can be timed against a high-income year rather than taken reflexively at acquisition.",
"Studies take four to eight weeks. Commissioning one in mid-July leaves room to have it in hand well before the return.",
]),
("Seven: Check the Pass-Through Entity Tax Election", [
"If you operate in a state with a PTET election, confirm whether the election has been made and whether the entity has made the required estimated payments.",
"For a cash method entity, the federal deduction lands in the year of payment. Paying by December 31 captures it a year earlier than paying with the return.",
"Some states have election deadlines well before the return due date, and missing them forfeits the benefit for the year entirely.",
]),
("Eight: Review Entity Structure Against Current Facts", [
"An S corporation election requires Form 2553 filed generally within two months and fifteen days of the beginning of the tax year for which it is effective. Late election relief exists but is not automatic.",
"If you are converting from a sole proprietorship or a partnership, the decision belongs early in the year, not at filing.",
"Similarly, if you have added a business line, a property, or a partner, review whether the current structure still fits before it becomes a multi-year problem.",
]),
("Nine: Confirm Worker Classification", [
"Review your contractor roster against your employee roster. Anyone doing substantially the same work under substantially the same conditions should be classified the same way.",
"Section 530 relief requires consistent treatment of similar workers, and inconsistency is the most common way businesses lose it.",
"Fixing a classification prospectively at mid-year is far cheaper than defending it later.",
]),
("Ten: Review Accountable Plan and Reimbursements", [
"Confirm that home office, vehicle, cell phone, and travel reimbursements are running through a documented accountable plan rather than being deducted personally, which is not available to employees including S corporation owners.",
"Reimbursements should be substantiated and paid on a regular schedule, not booked as a lump entry in December.",
]),
("Eleven: Update Basis and Suspended Loss Records", [
"Maintain basis, at-risk amounts, and suspended passive losses by activity. These records determine what you can deduct and, on a future disposition, what releases.",
"Property-level suspended loss records specifically preserve partial disposition relief under Treasury Regulation Sec. 1.469-4(g), which aggregate-only records forfeit.",
"Reconstructing years of records at the moment of a sale is expensive and often incomplete.",
]),
("Twelve: Plan Charitable Giving Deliberately", [
"If you intend to give, decide now whether to give cash, appreciated securities, or appreciated real property, and whether to bunch multiple years into one through a donor advised fund.",
"Appreciated assets held more than a year generally produce a fair market value deduction with no gain recognition, which is substantially better than selling and donating cash.",
"Contributions of property above $5,000 generally require a qualified appraisal under IRC Sec. 170(f)(11), which takes time to obtain and is a common December failure.",
]),
],
"faqs": [
("Why plan at mid-year instead of December?",
 "Because most of the meaningful options have deadlines before or at year end. Safe harbor 401(k) adoption, S corporation elections, defined benefit plan setup, PTET elections, and cost segregation studies all require lead time that December does not provide."),
("What is the single most important mid-year item?",
 "A full-year income projection. Everything else, salary optimization, plan selection, equipment timing, and study timing, depends on knowing approximately where you will land. Without it every other decision is a guess."),
("When do retirement plans need to be established?",
 "A safe harbor 401(k) generally requires adoption before October 1 for a new plan covering the current year. Defined benefit and cash balance plans require actuarial work taking weeks. Starting the conversation in December generally means starting for the following year."),
("Can I still change my S corporation salary at mid-year?",
 "Yes, and mid-year is the right time. If income is running well above or below prior year, the January number may no longer be optimal or defensible. Adjusting in December requires either a large catch-up payroll or an indefensible annual figure."),
("Is it too late to run a cost segregation study in December?",
 "Usually tight. Studies take four to eight weeks from engagement to delivery. More importantly, a look-back study with Form 3115 lets you place the deduction in the year that needs it, so the timing decision should be deliberate rather than driven by a deadline."),
],
"related": [
("/blog/year-end-tax-planning-checklist-real-estate-investors/", "Year-end tax planning checklist"),
("/blog/safe-harbor-rule-for-estimated-tax-payments/", "The estimated tax safe harbor"),
("/blog/obbba-tax-planning-checklist-business-owners-2026/", "OBBBA tax planning checklist"),
],
"cta_head": "The Best Time to Do This Was June",
"cta_body": "Bring six months of results and we will build the full-year projection, then work through every item on this list against your actual numbers.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
