"""Batch: entity structuring long-tail guides."""

from blog_gen import write_all

C = "Entity Structuring"
D = "2026-08-10"

ARTICLES = [
{
"slug": "land-trust-vs-llc-for-rental-property",
"title": "Land Trust vs LLC for Rental Property: What Each One Actually Does",
"meta_title": "Land Trust vs LLC for Rental Property (2026 Guide) | AE Tax Advisors",
"meta_desc": "A land trust provides privacy but no liability protection or tax effect. How trusts and LLCs compare, and why most investors need both or just one.",
"category": C, "date": D,
"intro": [
"Land trusts are marketed to real estate investors as an asset protection tool. They are not one. A land trust is a title-holding arrangement that provides privacy, and privacy is not protection.",
"Understanding what each structure actually accomplishes prevents the two most common mistakes: paying for a land trust expecting liability protection, and skipping an LLC because a trust is already in place.",
],
"sections": [
("What a Land Trust Does", [
"A land trust holds title to real property in the name of a trustee for the benefit of a beneficiary. The public record shows the trustee, not the beneficiary. That is the entire mechanism.",
"The benefits are real but narrow. Property records do not reveal ownership, which makes an investor harder to identify through county searches. It simplifies transfer of beneficial interests without recording a deed. In some states it can avoid triggering a due-on-sale clause, since transfers into a trust where the borrower is a beneficiary are protected under the Garn-St Germain Act.",
"Illinois, Florida, Indiana, Virginia, and several other states have specific land trust statutes. In states without them, a conventional revocable trust performs the same title-holding function.",
]),
("What a Land Trust Does Not Do", [
"It does not provide liability protection. The beneficiary of a land trust holds the beneficial interest and remains personally liable for claims arising from the property. A tenant injured on the premises sues the owner, and discovery identifies the beneficiary quickly.",
"It has no tax effect. A land trust is generally a grantor trust under IRC Sec. 671 through 679, meaning all income, deductions, and credits flow directly to the beneficiary's personal return as if the trust did not exist. There is no separate return, no separate taxpayer identification number in most cases, and no change to how the property is reported.",
"It does not create depreciation, does not change passive activity treatment, and does not affect the qualified business income deduction. The property is taxed exactly as it would be held individually.",
]),
("What an LLC Does", [
"A properly formed and maintained LLC creates a legal entity separate from its members. Claims arising from the property are generally limited to the LLC's assets, protecting the member's other property.",
"That protection depends entirely on maintaining separateness. Separate bank accounts, no personal expenses paid from the LLC, adequate capitalization, proper insurance, and observation of whatever formalities the operating agreement requires. An LLC used as a personal checking account is a veil-piercing case waiting to happen.",
"For tax purposes, a single-member LLC is a disregarded entity under Treasury Regulation Sec. 301.7701-3 unless it elects otherwise. Income and deductions flow to the member's Schedule E exactly as if held individually. A multi-member LLC defaults to partnership treatment and files Form 1065.",
"Critically for real estate, neither default changes the tax outcome meaningfully. The LLC is chosen for liability, not for tax.",
]),
("Using Both Together", [
"The common structure combines them. A land trust holds title, providing privacy in the public record, and an LLC holds the beneficial interest in the trust, providing liability protection.",
"This is the arrangement most asset protection attorneys recommend for investors who value both. The county record shows a trustee. The trust's beneficiary is an LLC. The LLC's members are shielded.",
"The cost is modest, a trust document and a trustee arrangement layered onto an LLC that would exist anyway. The complexity is real but manageable, and it does not change the tax reporting at all, since both layers are transparent for income tax purposes.",
]),
("The Financing Complication", [
"Most residential lenders will not lend to an LLC at conventional terms. Investors commonly buy in their own name, finance conventionally, then transfer to an LLC afterward.",
"That transfer technically triggers the due-on-sale clause in most notes. Lenders rarely call loans in a normal rate environment, but the exposure is real, and in a rising rate environment a lender has an economic incentive to enforce.",
"A transfer into a land trust where the borrower remains a beneficiary is expressly protected from due-on-sale enforcement under the Garn-St Germain Act for properties of fewer than five dwelling units. A subsequent transfer of the beneficial interest to an LLC is not protected by that statute, though it is not recorded and is therefore less visible.",
"This is why land trusts appear so often in investor structures. The privacy is not primarily about hiding from plaintiffs. It is about the lender not noticing.",
]),
("The Tax Considerations That Actually Matter", [
"Neither structure changes depreciation, passive loss treatment, or the qualified business income deduction. What does matter is entity choice at a higher level.",
"Do not hold appreciating real estate in an S corporation. Distributing appreciated property out of an S corporation is a taxable event under IRC Sec. 311(b), treated as if the corporation sold it at fair market value. Real estate held in a partnership or disregarded entity can generally be distributed without gain under IRC Sec. 731.",
"S corporation shareholders also do not receive basis for entity-level debt, which limits deductible losses under IRC Sec. 1366(d). Partners in a partnership do receive basis for qualified nonrecourse financing under IRC Sec. 752, which is why leveraged real estate belongs in a partnership or disregarded entity.",
"Multiple LLCs also multiply state filing fees and franchise taxes. California charges $800 minimum franchise tax per LLC annually, plus a gross receipts fee. An investor with eight California LLCs pays $6,400 before any tax on income. The protection may still be worth it, but the cost should be an input rather than a surprise.",
]),
("Worked Example: Six-Property Portfolio", [
"An investor holds six rentals across two states with $2,900,000 of combined value and $1,700,000 of debt.",
"Holding all six in one LLC is simplest and cheapest but concentrates risk. A claim on any property reaches the equity in all six.",
"Holding each in a separate LLC costs roughly $2,400 annually in filing fees and additional bookkeeping across the two states, and creates six separate sets of records to maintain.",
"A middle structure groups them by risk and equity, perhaps three LLCs holding two properties each, with a land trust holding title to each property for privacy and to reduce due-on-sale visibility. All LLCs are owned by a single holding LLC taxed as a partnership, which files one return and issues one K-1 to the investor.",
"The tax outcome is identical to individual ownership. The liability outcome, the privacy outcome, and the administrative cost all differ, and those are the actual decision variables.",
]),
],
"faqs": [
("Does a land trust protect me from lawsuits?",
 "No. A land trust provides privacy in the public record but no liability protection. The beneficiary remains personally liable for claims arising from the property. Protection requires an LLC or another entity holding the beneficial interest."),
("Does a land trust change my taxes?",
 "No. A land trust is generally a grantor trust under IRC Sec. 671 through 679, so all income and deductions flow directly to the beneficiary as if the trust did not exist. There is no separate return and no change in depreciation or passive activity treatment."),
("Should I use a land trust and an LLC together?",
 "Often yes. The land trust holds title for privacy, and an LLC holds the beneficial interest for liability protection. Neither layer changes the tax reporting, and the combined cost is modest relative to an LLC alone."),
("Will transferring my property to an LLC trigger the due-on-sale clause?",
 "Technically yes on most notes. A transfer into a land trust where you remain a beneficiary is protected by the Garn-St Germain Act for properties under five dwelling units. A subsequent transfer of the beneficial interest to an LLC is not protected by that statute, though it is not recorded."),
("Should I hold rental property in an S corporation?",
 "Generally no. Distributing appreciated property out of an S corporation is taxable under IRC Sec. 311(b), and shareholders do not receive basis for entity debt, which limits deductible losses. Partnerships and disregarded entities avoid both problems."),
],
"related": [
("/blog/should-i-hold-rental-property-in-an-llc-or-personal-name/", "LLC versus personal name for rentals"),
("/blog/do-i-need-a-separate-llc-for-each-rental-property/", "Do you need a separate LLC per property"),
("/blog/structure-llcs-asset-protection-tax-benefit/", "Structuring LLCs for protection and tax benefit"),
],
"cta_head": "Structure Costs Money Every Year. Make It Earn It.",
"cta_body": "Bring your property list with values, debt, and states. We will map a structure that fits the actual risk rather than a template.",
},

{
"slug": "family-limited-partnership-tax-and-estate-benefits",
"title": "Family Limited Partnerships: Valuation Discounts, Control, and IRS Scrutiny",
"meta_title": "Family Limited Partnership Tax and Estate Benefits (2026) | AE Tax Advisors",
"meta_desc": "FLPs transfer wealth at a discount while keeping control, but IRC Sec. 2036 defeats poorly run ones. Structure, discounts, and pitfalls for 2026.",
"category": C, "date": D,
"intro": [
"A family limited partnership lets a senior generation transfer assets to children and grandchildren at a discount to underlying value while retaining management control. Done correctly it moves substantial wealth out of a taxable estate at reduced transfer tax cost.",
"Done carelessly it produces the opposite. Under IRC Sec. 2036, the entire partnership value can be pulled back into the estate at full value, eliminating the discount and any appreciation transferred with it. The difference between the two outcomes is almost entirely about operational discipline.",
],
"sections": [
("How the Discount Works", [
"The senior generation contributes assets to a partnership in exchange for general and limited partnership interests, then gifts or sells limited interests to family members.",
"A limited partnership interest is worth less than a proportionate share of the underlying assets, because a limited partner cannot control distributions, cannot compel liquidation, cannot participate in management, and cannot easily sell the interest. Appraisers quantify these as a lack of control discount and a lack of marketability discount.",
"Combined discounts of 20% to 35% are common and defensible for a partnership holding a mix of assets with genuine restrictions. Discounts above 40% draw scrutiny and generally require unusual facts.",
"The effect is leverage on the transfer tax exclusion. Gifting a limited interest representing $1,500,000 of underlying assets at a 30% discount uses $1,050,000 of exclusion. Over a program of annual gifts, that difference compounds meaningfully.",
]),
("The Section 2036 Problem", [
"IRC Sec. 2036(a) includes in the gross estate any property transferred during life where the decedent retained possession, enjoyment, or the right to income, or the right to designate who enjoys the property.",
"The IRS has used this successfully against FLPs repeatedly. The pattern in the losing cases is consistent. The decedent transferred nearly all personal assets to the partnership, continued paying personal expenses from partnership funds, made distributions on demand rather than pro rata, kept using partnership-owned property personally, and formed the partnership shortly before death with no purpose other than tax reduction.",
"Where those facts are present, the entire partnership is included in the estate at undiscounted value and the planning accomplishes nothing beyond legal fees.",
"There is an exception for transfers that are a bona fide sale for adequate and full consideration. Courts have interpreted this to require a legitimate, significant, non-tax purpose for forming the partnership. Consolidated asset management, protection from divorcing spouses of children, facilitating family business succession, and pooling for investment scale have all been accepted where the facts supported them.",
]),
("What a Defensible FLP Looks Like", [
"Form it while healthy and well before any anticipated transfer event. Formations executed weeks before death fail.",
"Retain sufficient personal assets outside the partnership to fund your own living expenses. This is the single most important operational fact. A senior generation that must take partnership distributions to buy groceries has retained enjoyment.",
"Respect the entity. Separate accounts, formal capital accounts, partnership tax returns, documented meetings, distributions made pro rata to all partners rather than on demand to one, and no personal use of partnership property without arm's length rent.",
"Contribute assets that genuinely benefit from pooled management. Marketable securities alone are the weakest fact pattern, because there is no management benefit to pooling them. Operating real estate, a family business, or a concentrated position requiring coordinated management are all stronger.",
"Obtain a qualified appraisal from a credentialed business valuation appraiser for every transfer. Discounts asserted without an appraisal are indefensible, and an appraisal also starts the gift tax statute of limitations running when the gift is adequately disclosed on Form 709.",
]),
("Income Tax Consequences", [
"An FLP is a partnership for income tax purposes, filing Form 1065 and issuing K-1s. Income flows to partners in proportion to their interests, which is part of the point, since it shifts income to family members in lower brackets.",
"The kiddie tax under IRC Sec. 1(g) limits this for children under 19, or under 24 if a full-time student, by taxing unearned income above a threshold at the parents' rate. FLP income allocated to a young child is generally not an income-shifting win.",
"For adult children in lower brackets, the shift is real. Income allocated to a child in the 22% bracket rather than the parents' 37% bracket saves 15 points on every dollar allocated.",
"Basis matters at death. Assets inside a partnership do not automatically receive a stepped-up basis under IRC Sec. 1014 for the portions already gifted. Interests still owned at death do receive a step-up in the partnership interest, and a Sec. 754 election allows the partnership to adjust inside basis correspondingly. Making that election is important and frequently overlooked.",
]),
("The Discount Cuts Both Ways", [
"A valuation discount that reduces gift and estate tax also reduces the basis step-up at death for interests included in the estate. An interest included at a 30% discount receives a stepped-up basis at that discounted value.",
"For families whose estates fall below the exclusion amount, this is a bad trade. There is no transfer tax to save, and the discount destroys basis that would otherwise have been free. Those families should generally not use an FLP for tax reasons, though the non-tax benefits of centralized management and creditor protection may still justify it.",
"The exclusion amount is scheduled to change, and families near the threshold should model both scenarios rather than planning for one.",
]),
("Worked Example: Real Estate FLP", [
"A couple in their late sixties owns $12,000,000 of commercial real estate held across several LLCs plus $4,000,000 of other assets. They form an FLP, contribute the real estate LLC interests, and retain the $4,000,000 personally for living expenses.",
"They hold a 2% general partner interest and initially all limited interests. A qualified appraisal supports a combined 28% discount on limited interests given lack of control and marketability.",
"Over six years they gift limited interests representing $6,400,000 of underlying value to a trust for their three children. At the discount, this uses approximately $4,608,000 of combined exclusion.",
"The transferred interests appreciate at 5% annually, so roughly $2,200,000 of appreciation on the gifted portion accrues outside the estate as well.",
"They retain the general partner interest, control all management decisions, and continue receiving guaranteed payments for services. Distributions are made pro rata. Personal expenses are paid from the retained $4,000,000. The partnership files returns, holds documented meetings, and maintains capital accounts.",
"The estate tax reduction across the transferred interests and their appreciation, at a 40% rate, exceeds $3,400,000. The structure survives because the operational facts support it.",
]),
],
"faqs": [
("How large a valuation discount can an FLP support?",
 "Combined lack of control and lack of marketability discounts of 20% to 35% are common and defensible for a partnership with genuine restrictions and a real asset mix. Discounts above 40% draw scrutiny and require unusual facts. Every transfer needs a qualified appraisal."),
("What makes the IRS challenge a family limited partnership?",
 "Under IRC Sec. 2036, retained enjoyment pulls the assets back into the estate at full value. The losing cases share a pattern: transferring nearly all personal assets, paying personal expenses from partnership funds, non-pro-rata distributions on demand, personal use of partnership property, and formation shortly before death."),
("Do I need a business purpose for the partnership?",
 "Effectively yes. The bona fide sale exception to IRC Sec. 2036 requires a legitimate non-tax purpose. Consolidated management, protection from children's divorcing spouses, and business succession have all been accepted where facts supported them. Marketable securities alone are the weakest fact pattern."),
("Does an FLP reduce income taxes?",
 "It can shift income to family members in lower brackets. The kiddie tax under IRC Sec. 1(g) limits this for children under 19, or 24 if a full-time student. For adult children in lower brackets the shift is real and can be worth 15 percentage points on allocated income."),
("Is an FLP a good idea if my estate is below the exclusion?",
 "Usually not for tax reasons. The discount that saves transfer tax also reduces the basis step-up at death under IRC Sec. 1014. With no transfer tax to save, you are destroying basis for nothing. Non-tax benefits like centralized management may still justify it."),
],
"related": [
("/blog/multi-entity-structures-liability-protection/", "Multi-entity structures for liability protection"),
("/blog/operating-agreement-asset-protection-provisions/", "Operating agreement asset protection provisions"),
("/estate-trust-wealth-transfer/", "Estate, trust, and wealth transfer planning"),
],
"cta_head": "The Structure Is the Easy Part",
"cta_body": "FLPs fail on operations, not on documents. Bring your asset schedule and we will map both the structure and the discipline it requires to hold up.",
},

{
"slug": "charging-order-protection-llc-by-state",
"title": "Charging Order Protection: Why Some States Protect LLC Owners and Others Do Not",
"meta_title": "LLC Charging Order Protection by State (2026 Guide) | AE Tax Advisors",
"meta_desc": "Charging order protection stops creditors from seizing LLC interests, but single-member LLCs often lose it. State comparison and tax effects for 2026.",
"category": C, "date": D,
"intro": [
"Most investors understand that an LLC protects personal assets from business claims. Fewer understand the reverse protection, which stops a personal creditor from reaching assets inside the LLC.",
"That reverse protection is the charging order, and it varies dramatically by state. In some states it is the exclusive remedy and genuinely strong. In others, courts have ordered foreclosure and even dissolution, which defeats the purpose entirely.",
],
"sections": [
("What a Charging Order Is", [
"A charging order is a court order directing that any distributions otherwise payable to a debtor member be paid to the creditor instead. The creditor becomes an assignee of economic rights only.",
"The creditor does not become a member. It cannot vote, cannot compel a distribution, cannot force a sale of LLC assets, and cannot participate in management. It simply waits for money to come out.",
"The practical leverage this creates favors the debtor. A creditor holding a charging order against an LLC that makes no distributions receives nothing while potentially owing tax on allocated income under the assignee rules. That prospect drives settlements at a fraction of the judgment.",
]),
("Where the Protection Is Strong", [
"Wyoming, Nevada, Delaware, South Dakota, and Alaska have statutes expressly making the charging order the exclusive remedy for a judgment creditor of a member, and extending that protection to single-member LLCs.",
"Wyoming's statute is among the clearest, stating that a charging order is the sole and exclusive remedy and that a court may not order foreclosure of the interest or dissolution of the company.",
"These states also generally do not permit a creditor to obtain the LLC's records, compel management decisions, or reach the underlying assets. That combination is what makes them the standard choice for asset protection structures.",
]),
("Where It Is Weak", [
"Many states permit foreclosure of the charged interest, which converts the creditor from a passive assignee into an owner who may then be able to force liquidation.",
"Single-member LLCs are the larger vulnerability nationally. The charging order remedy was designed for partnerships, where the protection exists to prevent a creditor from disrupting innocent co-owners. With one member, there are no innocent co-owners.",
"Courts have relied on that reasoning to allow creditors to reach single-member LLC assets directly. The Florida Supreme Court's decision in Olmstead v. Federal Trade Commission is the most cited example, holding that a creditor could reach a single-member LLC interest through a levy rather than being limited to a charging order. Florida amended its statute afterward, but the amendment preserved the distinction, protecting multi-member LLCs more strongly than single-member ones.",
"Bankruptcy adds another layer. In bankruptcy, a single-member LLC interest generally becomes property of the estate and the trustee steps into the member's shoes with full management rights. Charging order protection under state law does not survive that.",
]),
("The Multi-Member Fix and Its Limits", [
"Adding a second member restores the partnership rationale and strengthens protection substantially in most states.",
"The second member must be real. A 1% interest gifted to a spouse who is also a co-defendant on the judgment accomplishes nothing. A nominal interest with no capital contribution, no economic risk, and no participation invites a court to disregard it.",
"Where a second member is genuine, holding a meaningful percentage with real capital at risk and actual rights under the operating agreement, the protection is far more durable.",
"There is a tax consequence to adding a member. A single-member LLC is a disregarded entity under Treasury Regulation Sec. 301.7701-3. Adding a member converts it to a partnership, which begins filing Form 1065 and issuing K-1s. This is generally a non-event tax-wise under Revenue Ruling 99-5, but it adds a return and creates capital account tracking that did not exist before.",
]),
("Operating Agreement Provisions That Matter", [
"The statute sets the floor. The operating agreement can strengthen the position considerably.",
"Useful provisions include express restrictions on transfer and assignment, requiring consent of non-transferring members for admission of any assignee, granting managers full discretion over distributions with no obligation to distribute, and providing that an assignee receives economic rights only with no information or inspection rights.",
"A distribution provision granting complete discretion is the operative one. If the agreement requires annual distributions of net cash flow, a charging order creditor collects on schedule. If distributions are entirely discretionary, the creditor waits indefinitely.",
"Some agreements go further with provisions addressing the tax consequences to an assignee, reinforcing the settlement leverage. These should be drafted by counsel in the governing state rather than pulled from a template.",
]),
("The Tax Side Nobody Mentions", [
"Forming an LLC in Wyoming or Nevada does not avoid tax in the state where you live or where the property sits. Income from a rental in California is California source income regardless of where the LLC was organized.",
"Worse, a Wyoming LLC doing business in California must register as a foreign LLC and pay the $800 minimum franchise tax plus the gross receipts fee. You now have two states' compliance obligations instead of one.",
"The protection may still justify the cost. But investors are frequently sold Wyoming and Nevada entities on an implied tax benefit that does not exist for operating property in another state.",
"Where the structure does work cleanly is a holding company. A Wyoming holding LLC owning membership interests in state-specific operating LLCs holds intangible personal property, not operating assets, and generally does not create a filing obligation in the operating states by itself.",
]),
("Worked Example: Layered Structure", [
"An investor in Georgia owns four rentals in Georgia and two in Tennessee, with $3,100,000 of combined equity, and has meaningful personal liability exposure from an operating business.",
"Each property sits in a state-specific LLC formed where the property is located, registered and compliant in that state. Those LLCs are owned by a Wyoming holding LLC.",
"The investor and their spouse are both members of the Wyoming holding LLC with genuine capital contributions and real economic interests, making it a multi-member LLC taxed as a partnership.",
"The operating agreement grants the manager full discretion over distributions, restricts transfers, and limits assignees to economic rights only.",
"A personal judgment creditor of the investor is limited to a charging order against the Wyoming holding LLC interest under Wyoming's exclusive remedy statute. The creditor cannot reach the underlying properties, cannot force distributions, and cannot compel dissolution.",
"Georgia and Tennessee income is reported and taxed where earned, as it would have been anyway. The Wyoming layer adds protection, not tax savings.",
]),
],
"faqs": [
("What is a charging order?",
 "A court order directing that distributions otherwise payable to a debtor member go to the creditor instead. The creditor becomes an assignee of economic rights only, with no voting, management, or right to compel a distribution or force a sale of LLC assets."),
("Which states have the strongest charging order protection?",
 "Wyoming, Nevada, Delaware, South Dakota, and Alaska have statutes making the charging order the exclusive remedy and extending that protection to single-member LLCs. Wyoming's statute expressly bars foreclosure of the interest and dissolution of the company."),
("Are single-member LLCs protected?",
 "Often not, outside the strong-statute states. The charging order remedy exists to protect innocent co-owners, and with one member there are none. Courts have permitted creditors to reach single-member LLC assets directly, and in bankruptcy the trustee generally steps in with full management rights."),
("Does adding a second member fix it?",
 "It helps substantially, provided the member is genuine with real capital at risk and actual rights. A nominal 1% interest with no contribution invites a court to disregard it. Adding a member converts the LLC to a partnership for tax purposes, generally tax free under Rev. Rul. 99-5."),
("Does a Wyoming LLC save me state income tax?",
 "No. Income is taxed where it is earned. A Wyoming LLC owning California property still owes California tax and must register as a foreign LLC, adding the $800 minimum franchise tax. The benefit is protection, not tax savings."),
],
"related": [
("/blog/operating-agreement-asset-protection-provisions/", "Operating agreement asset protection provisions"),
("/blog/should-i-form-my-business-in-wyoming-or-delaware/", "Wyoming versus Delaware formation"),
("/blog/multi-entity-structures-liability-protection/", "Multi-entity structures for liability protection"),
],
"cta_head": "Protection and Tax Are Separate Questions",
"cta_body": "Most investors are sold one and told they are getting both. Bring your property list, states, and liability exposure and we will separate them clearly.",
},

{
"slug": "management-company-structure-for-business-owners",
"title": "The Management Company Structure: When a Second Entity Actually Helps",
"meta_title": "Management Company Structure for Business Owners (2026) | AE Tax Advisors",
"meta_desc": "A management company can centralize payroll, shift income, and preserve QBI, but controlled group rules and Sec. 482 limit it. Full analysis for 2026.",
"category": C, "date": D,
"intro": [
"The management company structure appears constantly in tax planning discussions and is misunderstood roughly as often. The idea is straightforward: form a second entity that provides management services to your operating businesses and charges a fee.",
"Whether that accomplishes anything depends entirely on why you are doing it. There are three good reasons and several bad ones, and the bad ones create more exposure than the tax they save.",
],
"sections": [
("Reason One: Centralizing Employment and Benefits", [
"An owner with four operating entities has four payrolls, four workers compensation policies, four benefit plans, and four sets of employment compliance.",
"A management company employing everyone and charging each operating entity for services consolidates this. One payroll, one benefits package, one set of employment practices.",
"This is a genuine operational benefit with a real tax dimension. Retirement plan design is simpler and often more favorable when all employees sit in one entity, though the controlled group rules under IRC Sec. 414(b) and (c) and the affiliated service group rules under IRC Sec. 414(m) treat commonly owned entities as one employer for plan testing regardless. Owners who form a management company expecting to escape those rules are disappointed.",
]),
("Reason Two: Preserving the QBI Deduction", [
"This is the most valuable use and the most technically demanding.",
"Where an owner runs a specified service trade or business under IRC Sec. 199A, such as a medical or legal practice, the qualified business income deduction disappears above the phase-out. A genuinely separate business providing services that are not in an excluded field may retain the deduction.",
"The regulations impose serious limits. Under Treasury Regulation Sec. 1.199A-5(c)(2), where a business provides property or services to an SSTB and there is 50% or more common ownership, the portion of the business providing those services is itself treated as an SSTB.",
"That rule kills the naive version. A management company owned by the same doctor, providing services only to the doctor's practice, is an SSTB by attribution.",
"What survives is a management company with substantial unrelated business. A company managing five unrelated practices, of which one is the owner's, has 80% of its revenue from unrelated parties. That portion may retain QBI eligibility. This is a real business, not a structure, and it should be built as one.",
]),
("Reason Three: Separating Risk", [
"An operating business with meaningful liability exposure benefits from holding valuable assets elsewhere. Intellectual property, equipment, and accumulated cash sitting inside an operating entity are exposed to its claims.",
"A management company holding equipment and leasing it to the operating entity, or holding intellectual property and licensing it, moves those assets outside the reach of operating claims while maintaining their use.",
"The arrangement must be documented with real agreements and arm's length pricing. Equipment leased at a nominal rate to strip value from an operating entity facing claims is a fraudulent transfer question, not a tax question, and courts unwind it.",
]),
("Where It Goes Wrong: Section 482", [
"The bad version of this structure is a management fee set at whatever amount produces the desired tax result.",
"Under IRC Sec. 482, the IRS may reallocate income and deductions among commonly controlled entities to clearly reflect income. A management fee that does not reflect the value of services actually provided will be adjusted.",
"The fee should be supported by something. A cost-plus calculation based on actual expenses incurred plus a reasonable markup is the most common defensible approach. A percentage of revenue can work where it reflects market rates for comparable services. A number chosen to zero out an entity's income does not.",
"Documentation matters more than the method. A written management services agreement describing what is provided, invoices issued and paid on schedule, and a computation supporting the fee will withstand examination. An annual journal entry booked at filing will not.",
]),
("Where It Goes Wrong: No Real Substance", [
"Courts and the IRS look at whether the management company does anything. An entity with no employees, no office, no assets, and no activity other than receiving fees is not a business.",
"The consequence is usually a Sec. 482 reallocation eliminating the fee, plus accuracy-related penalties under IRC Sec. 6662. Where the arrangement is aggressive enough, the penalty exposure increases.",
"The test is practical. Does the management company have employees performing identifiable functions? Does it have a bank account, contracts, and its own expenses? Could you describe its business to a third party without referring to tax? If not, it is not a management company.",
]),
("The Payroll Tax Illusion", [
"Owners sometimes structure a management company hoping to reduce payroll tax by paying themselves through one entity and taking distributions from another.",
"This generally does not work. Reasonable compensation is evaluated across the enterprise. An owner performing substantial services for operating entities while taking a small salary from a management company and large distributions from operating entities has the same reasonable compensation problem, just spread across two returns.",
"Where the structure does help is in coordinating a single salary that supports retirement plan contributions across the enterprise, rather than fragmenting compensation across entities in a way that limits plan design. That is a legitimate benefit and a different one.",
]),
("Worked Example: Multi-Practice Owner", [
"An owner holds majority interests in three dental practices in different cities, each an S corporation, plus a minority interest in two others.",
"A management company is formed, taxed as an S corporation, employing the non-clinical staff: billing, scheduling, marketing, HR, and IT. It contracts with all five practices, including the two where the owner holds minority interests, and with three unrelated practices in the region.",
"Fees are set on a cost-plus basis at actual cost plus 12%, documented in written agreements with each practice and supported by an annual computation. Invoices are issued monthly and paid.",
"Because 38% of management company revenue comes from practices where common ownership is below 50%, that portion is analyzed independently for SSTB status. Management services are not an excluded field, so that revenue supports a qualified business income deduction.",
"The management company sponsors a single 401(k) and cash balance plan covering all administrative staff. Controlled group rules require aggregating the clinical staff of majority-owned practices for testing, which is modeled rather than ignored.",
"The structure produces a genuine QBI deduction on the unrelated revenue, real administrative efficiency, and a cleaner retirement plan. It works because it is an actual business.",
]),
],
"faqs": [
("Does a management company reduce my payroll taxes?",
 "Generally no. Reasonable compensation is evaluated across the enterprise, so paying yourself through one entity and taking distributions from another does not change the analysis. The legitimate benefit is coordinating a single salary that supports better retirement plan design."),
("Can a management company preserve my QBI deduction?",
 "Only with substantial unrelated business. Under Treas. Reg. Sec. 1.199A-5(c)(2), where a business provides services to an SSTB with 50% or more common ownership, that portion is itself treated as an SSTB. A management company serving only your own practice does not work."),
("How should the management fee be set?",
 "On a supportable basis, most commonly cost plus a reasonable markup, documented in a written services agreement with invoices issued and paid on schedule. Under IRC Sec. 482 the IRS can reallocate income where the fee does not reflect services actually provided."),
("Does a management company let me set up a separate retirement plan?",
 "Not in the way owners usually hope. Controlled group rules under IRC Sec. 414(b) and (c) and affiliated service group rules under Sec. 414(m) treat commonly owned entities as a single employer for plan testing regardless of how many entities exist."),
("What makes the IRS challenge a management company?",
 "Lack of substance and unsupported fees. An entity with no employees, no office, no assets, and no activity beyond receiving fees will face a Sec. 482 reallocation plus accuracy-related penalties under IRC Sec. 6662. Ask whether you could describe its business without referring to tax."),
],
"related": [
("/blog/how-to-structure-multiple-businesses-for-tax-efficiency/", "Structuring multiple businesses"),
("/blog/should-i-use-a-holding-company-for-my-businesses/", "Holding company structures"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
],
"cta_head": "Build a Business, Not a Structure",
"cta_body": "Management companies work when they do real work. Bring your entity list, headcount, and revenue by entity and we will tell you whether this fits.",
},

{
"slug": "tenancy-in-common-vs-llc-real-estate",
"title": "Tenancy in Common vs LLC for Real Estate: The 1031 Exchange Difference",
"meta_title": "Tenancy in Common vs LLC for Real Estate (2026 Guide) | AE Tax Advisors",
"meta_desc": "TIC interests qualify for 1031 exchanges under Rev. Proc. 2002-22. LLC interests do not. Structure comparison and drop-and-swap planning for 2026.",
"category": C, "date": D,
"intro": [
"Co-owning real estate through an LLC is simpler in almost every respect except one, and that one matters enormously at the exit. An LLC interest is a partnership interest, and partnership interests are excluded from like-kind exchange treatment under IRC Sec. 1031(a)(2).",
"A tenancy in common interest is an interest in real property. It qualifies. When co-owners want to go separate ways at sale, one structure permits each of them to exchange independently and the other does not.",
],
"sections": [
("The Core Difference", [
"A tenancy in common is direct co-ownership of real property. Each co-tenant holds an undivided fractional interest in the property itself, holds title, and may generally transfer, encumber, or exchange that interest independently.",
"An LLC is an entity. Members hold interests in the LLC, and the LLC holds the property. For tax purposes a multi-member LLC is a partnership by default, and its members hold partnership interests.",
"IRC Sec. 1031 permits exchanges of real property held for productive use or investment. Since the 2017 changes, personal property is excluded entirely, and IRC Sec. 1031(a)(2) has always excluded partnership interests.",
"The result is that a TIC co-owner can sell their fractional interest and exchange into replacement property individually, while an LLC member cannot exchange their membership interest at all. The LLC itself can exchange, but only if all members go the same direction.",
]),
("Revenue Procedure 2002-22", [
"The IRS will issue a ruling that a TIC arrangement is a co-ownership rather than a partnership if it satisfies the conditions in Revenue Procedure 2002-22. Those conditions are the working framework practitioners use even without seeking a ruling.",
"Key conditions include no more than 35 co-owners, title held directly by the co-owners as tenants in common, no business entity treatment or holding out as a partnership, unanimous approval required for sale, lease, refinancing, or hiring a manager, each co-owner having the right to transfer and encumber their interest, proceeds distributed proportionally, management agreements renewable annually, and no debt to a related party on non-arm's length terms.",
"The unanimity requirements are what make TICs operationally difficult. A single co-owner can block a sale, a refinance, or a lease. That is a real cost and it is the price of the tax treatment.",
]),
("Why Most Co-Ownership Ends Up in an LLC Anyway", [
"LLCs are simply easier. Majority or manager control replaces unanimity. Liability protection is stronger, since co-tenants can face joint liability. Lenders prefer a single borrower entity. Transfers are handled through the operating agreement rather than by recording deeds.",
"For co-owners who plan to sell the property together and take cash, or to exchange together into a single replacement property, an LLC costs nothing and is better in every operational respect.",
"The problem arises only when co-owners want different things at exit. One wants cash, one wants to exchange, one wants to buy the others out. An LLC makes each of those harder.",
]),
("The Drop and Swap", [
"The standard solution is to convert before the sale. The LLC distributes undivided TIC interests in the property to its members under IRC Sec. 731, generally without gain, and each former member then holds a direct real property interest that can be exchanged independently.",
"The risk is the holding requirement. IRC Sec. 1031 requires that property be held for productive use in a trade or business or for investment, both at the time of relinquishment and with respect to replacement property. A distribution executed days before closing invites an argument that the TIC interest was held for sale rather than for investment, and that the exchange was really a disguised partnership distribution.",
"The IRS has challenged drop and swaps, with mixed results. Courts have often sided with taxpayers where the facts were reasonable, but the risk scales with how close to closing the drop occurs.",
"The practical guidance is time. Execute the distribution as far ahead of the sale as circumstances permit, ideally in a prior tax year. Report consistently. Do not distribute after a purchase and sale agreement is signed if it can be avoided.",
"Form 1065 also asks directly whether the partnership distributed property in a like-kind exchange or contributed property to a partnership in a like-kind exchange. Answering this consistently matters.",
]),
("The Swap and Drop Variant", [
"The reverse structure, where the partnership completes the exchange and then distributes replacement property interests to members afterward, has the same holding period concern applied to replacement property.",
"It is generally viewed as somewhat safer, because the partnership itself performed the exchange and held the replacement property. But a distribution shortly after acquisition raises the same question in the other direction.",
"Where members know in advance they will separate, planning the structure years ahead avoids both problems entirely.",
]),
("Tax Reporting Differences", [
"A TIC arrangement does not file a partnership return. Each co-owner reports their proportionate share of income, deductions, and depreciation directly on Schedule E, based on their fractional interest.",
"Each co-owner has their own basis, makes their own depreciation elections, and may run a cost segregation study on their own interest. This independence is useful where co-owners have different tax situations, since one may want to accelerate depreciation while another does not.",
"An LLC files Form 1065, issues K-1s, and makes elections at the entity level. A cost segregation study benefits all members proportionally whether they want it or not, though special allocations under IRC Sec. 704(b) can create flexibility if drafted with substantial economic effect.",
]),
("Worked Example: Three Investors, Divergent Plans", [
"Three investors own a $4,600,000 retail property through an LLC, each holding a one-third interest. Adjusted basis is $2,100,000. They agree to sell.",
"Investor A wants cash to fund a business. Investor B wants to exchange into a single tenant net lease property. Investor C wants to exchange into two smaller residential properties.",
"Selling through the LLC forces one outcome. If the LLC exchanges, A cannot get cash without a taxable distribution. If the LLC sells for cash, B and C recognize their share of roughly $2,500,000 of gain.",
"Instead, fourteen months before listing, the LLC distributes undivided one-third TIC interests to each member under IRC Sec. 731. The distribution is non-taxable. Each investor holds a direct real property interest, reports on Schedule E, and files consistently for a full tax year before the sale.",
"At closing, A takes cash and recognizes roughly $833,000 of gain. B and C each engage a qualified intermediary and exchange independently into their chosen replacement property, deferring their gain entirely.",
"The fourteen-month lead time is what makes the structure defensible. The same transaction executed the week before closing would be considerably weaker.",
]),
],
"faqs": [
("Can I 1031 exchange my LLC interest?",
 "No. IRC Sec. 1031(a)(2) excludes partnership interests, and a multi-member LLC is a partnership by default. The LLC itself can exchange the property, but only if all members go the same direction. Individual members cannot exchange their interests."),
("What is a drop and swap?",
 "Converting an LLC-held property into tenancy in common interests distributed to members under IRC Sec. 731 before a sale, so each former member can exchange independently. The distribution itself is generally non-taxable. The risk is the holding requirement, which is why timing matters."),
("How long before a sale should I do the drop?",
 "As long as circumstances permit, ideally in a prior tax year. The IRS argument is that a TIC interest distributed days before closing was held for sale rather than for investment. Courts have often sided with taxpayers on reasonable facts, but risk scales with proximity to closing."),
("What are the requirements for a valid TIC arrangement?",
 "Revenue Procedure 2002-22 sets the working framework: no more than 35 co-owners, direct title as tenants in common, no holding out as a partnership, unanimous approval for sale, lease, and refinancing, transferable interests, proportional proceeds, and annually renewable management agreements."),
("Which is better for co-owning rental property?",
 "An LLC in nearly every operational respect: majority control instead of unanimity, better liability protection, and lender preference. TIC is better only where co-owners may want different exits, since it preserves each owner's independent 1031 ability."),
],
"related": [
("/blog/how-does-1031-exchange-work-for-rental-properties/", "How a 1031 exchange works"),
("/blog/delaware-statutory-trust-dst-1031-exchange/", "Delaware statutory trusts and 1031 exchanges"),
("/blog/entity-structuring-rental-property-portfolios/", "Entity structuring for rental portfolios"),
],
"cta_head": "Plan the Divorce Before the Marriage",
"cta_body": "Co-ownership structures should anticipate that partners will eventually want different things. Bring your ownership structure and timeline and we will map the exit paths.",
},

{
"slug": "qualified-small-business-stock-section-1202",
"title": "Qualified Small Business Stock: The Section 1202 Exclusion Most Owners Never Claim",
"meta_title": "Qualified Small Business Stock Section 1202 Exclusion (2026) | AE Tax Advisors",
"meta_desc": "QSBS can exclude up to $10 million or more of gain entirely. C corp requirements, five-year holding, stacking, and the 2025 law changes explained.",
"category": C, "date": D,
"intro": [
"Section 1202 allows a non-corporate shareholder to exclude up to 100% of gain on the sale of qualified small business stock, capped at the greater of $10,000,000 or ten times basis. That is a complete exclusion from federal tax, not a deferral.",
"It is one of the most valuable provisions in the code and among the least used, because it requires a C corporation, a five-year hold, and decisions made at formation that most founders make without knowing the provision exists.",
],
"sections": [
("The Core Requirements", [
"The stock must be issued by a domestic C corporation. S corporation stock never qualifies, and stock acquired while the company was an S corporation does not qualify even after a later conversion. Only stock issued after the conversion can qualify.",
"The stock must be acquired at original issuance from the corporation, in exchange for money, property other than stock, or services. Purchasing shares from an existing shareholder does not qualify, which is a common and expensive surprise for early employees buying from founders.",
"The corporation's aggregate gross assets must not have exceeded $50,000,000 at any time before and immediately after issuance. Legislation enacted in 2025 raised this threshold to $75,000,000 for stock issued after the effective date, with the per-issuer gain cap increasing correspondingly to $15,000,000. Which threshold applies depends on when the stock was issued, so the analysis is issuance-date specific.",
"At least 80% of assets by value must be used in the active conduct of a qualified trade or business throughout substantially all of the holding period.",
"The holding period is five years for the full exclusion. The 2025 legislation added a tiered exclusion for stock issued after the effective date, allowing 50% exclusion at three years and 75% at four years, with 100% at five.",
]),
("The Excluded Businesses", [
"IRC Sec. 1202(e)(3) excludes a list of businesses, and it overlaps substantially with the Sec. 199A specified service list but is not identical.",
"Excluded are businesses involving services in health, law, engineering, architecture, accounting, actuarial science, performing arts, consulting, athletics, financial services, and brokerage services, where the principal asset is the reputation or skill of employees. Also excluded are banking, insurance, financing, leasing, and investing businesses, farming, businesses involving oil, gas, or mineral extraction eligible for percentage depletion, and hotels, motels, restaurants, and similar businesses.",
"Note that engineering and architecture are excluded here while they are permitted under Sec. 199A. The lists are different and must be checked separately.",
"Technology companies, manufacturers, consumer products, software, and most product businesses qualify. Service firms generally do not.",
]),
("Stacking and Packing", [
"The per-taxpayer cap applies per issuer. Gifting stock to family members, or to non-grantor trusts for their benefit, multiplies the exclusion because each recipient has their own $10,000,000 or $15,000,000 cap.",
"Under IRC Sec. 1202(h), a recipient by gift takes the transferor's holding period and basis and is treated as having acquired the stock in the same manner. This is the mechanism that makes stacking work.",
"A founder with $60,000,000 of anticipated gain who gifts stock to four non-grantor trusts for children well before an exit can potentially exclude far more than the individual cap. The trusts must be genuinely non-grantor for this to work, since a grantor trust's income is taxed to the grantor and does not create a separate cap.",
"Packing refers to increasing basis to raise the ten-times-basis alternative cap. A shareholder contributing $4,000,000 of property to the corporation at issuance has a $40,000,000 alternative cap rather than the $10,000,000 floor. Basis for this purpose is generally the amount paid, and contributed property is valued at fair market value at contribution under IRC Sec. 1202(i).",
]),
("The Redemption Traps", [
"Two anti-abuse rules disqualify stock based on the corporation's redemption activity, and they catch ordinary transactions regularly.",
"Under IRC Sec. 1202(c)(3)(A), stock is not QSBS if the corporation purchased any of its stock from the taxpayer or a related person within a four-year window beginning two years before issuance.",
"Under IRC Sec. 1202(c)(3)(B), stock is not QSBS if the corporation made significant redemptions, exceeding 5% of aggregate stock value, within a two-year window beginning one year before issuance.",
"A company that buys back shares from a departing founder and then issues new shares to an incoming investor within a year may have inadvertently disqualified the new shares. De minimis exceptions exist under the regulations, and redemptions from terminating employees have a specific exception, but the rules are unforgiving and should be checked before any buyback.",
]),
("Section 1045 Rollover", [
"Where stock is sold before the five-year holding period is satisfied, IRC Sec. 1045 permits a rollover of gain into replacement QSBS purchased within 60 days. The holding period tacks.",
"This preserves the exclusion for a founder whose company is acquired at year three. Reinvesting the proceeds into another qualifying company continues the clock rather than resetting it.",
"The election is made on a timely filed return and requires the replacement stock to itself be QSBS, which means the acquisition target must satisfy all the same requirements.",
]),
("State Conformity Is Not Universal", [
"The exclusion is federal. States conform inconsistently. California does not conform and taxes QSBS gain in full. Pennsylvania, Mississippi, and Alabama also do not conform.",
"For a founder in California with $10,000,000 of excluded federal gain, the state tax at 13.3% is approximately $1,330,000 on gain that is entirely tax free federally.",
"This drives real planning. Establishing residency in a conforming or no-tax state well before an exit, or holding stock in a non-grantor trust sited in a favorable state, can preserve the state-level benefit. Both require lead time and genuine substance, and states with aggressive residency audit programs will examine the facts closely.",
]),
("Worked Example: Founder Exit", [
"A founder incorporates a software company as a C corporation in 2021, contributing $180,000 of cash and property at issuance for 4,000,000 shares. Company gross assets never exceed $28,000,000.",
"In 2023 the founder gifts 800,000 shares to each of two non-grantor trusts for their children, sited in a no-income-tax state with an independent trustee.",
"In 2027 the company is acquired for $96,000,000. The founder's remaining 2,400,000 shares produce $57,600,000 of gain and each trust's 800,000 shares produce $19,200,000 of gain.",
"The five-year holding period is satisfied. The founder excludes $10,000,000. Each trust excludes $10,000,000, for $20,000,000 across the two.",
"Total excluded gain is $30,000,000, against $27,600,000 of the founder's gain and $18,400,000 across the trusts remaining taxable at long-term capital gain rates.",
"Federal tax saved through the exclusion, at 23.8% including net investment income tax, is approximately $7,140,000. The gifting decision made four years before the exit accounts for $4,760,000 of that.",
]),
],
"faqs": [
("Does S corporation stock qualify for Section 1202?",
 "No. QSBS must be issued by a domestic C corporation. Stock held while the company was an S corporation never qualifies, even after conversion. Only shares issued after the conversion to C corporation status can qualify, and the five-year clock starts then."),
("How much gain can I exclude?",
 "The greater of $10,000,000 per issuer or ten times your basis in the stock. Legislation enacted in 2025 raised the cap to $15,000,000 for stock issued after the effective date, along with raising the gross asset threshold from $50 million to $75 million."),
("Can I multiply the exclusion by gifting stock?",
 "Yes. The cap applies per taxpayer per issuer, and under IRC Sec. 1202(h) a donee takes your holding period and is treated as acquiring the stock as you did. Gifts to non-grantor trusts for family members each carry their own cap. The trusts must be genuinely non-grantor."),
("What if I sell before five years?",
 "IRC Sec. 1045 allows a rollover of gain into replacement QSBS purchased within 60 days, with the holding period tacking. For stock issued after the 2025 effective date, a tiered exclusion also applies: 50% at three years and 75% at four years."),
("Do states honor the Section 1202 exclusion?",
 "Not all of them. California does not conform and taxes the gain in full, as do Pennsylvania, Mississippi, and Alabama. For a California founder with $10 million excluded federally, state tax can still exceed $1.3 million. Residency and trust siting planning requires years of lead time."),
],
"related": [
("/blog/when-does-it-make-sense-to-form-a-c-corporation/", "When forming a C corporation makes sense"),
("/blog/stock-sale-vs-asset-sale-tax-implications/", "Stock sale versus asset sale"),
("/blog/s-corp-to-c-corp-conversion-when-it-makes-sense/", "S corp to C corp conversion"),
],
"cta_head": "The Decisions That Matter Happen at Formation",
"cta_body": "QSBS planning is worth millions and expires quietly if the entity type or issuance timing is wrong. Bring your cap table and formation history.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
