"""Batch: hub and comparison pages that existing pages already link to."""

from blog_gen import write_all

D = "2026-08-11"

ARTICLES = [
{
"slug": "real-estate-investor-tax-strategy",
"standalone": True,
"crumb_name": "Services", "crumb_path": "services",
"title": "Real Estate Investor Tax Strategy",
"meta_title": "Real Estate Investor Tax Strategy (2026) | AE Tax Advisors",
"meta_desc": "Cost segregation, material participation, entity structuring, and exit planning for real estate investors. How AE Tax Advisors builds a full-portfolio plan.",
"category": "Real Estate Tax Planning", "date": D,
"intro": [
"Most real estate investors are working with a tax preparer, not a tax strategist. The return gets filed accurately and on time, and every decision that would have reduced the bill was made months earlier without anyone at the table.",
"Real estate is unusually responsive to planning because the deductions are large, the timing is controllable, and the rules governing whether you can use them are mechanical. What follows is the framework we work through with every investor.",
],
"sections": [
("Step One: Determine Which Loss Exit Is Available to You", [
"This decision comes before any property analysis, because it determines what kind of property you should be buying.",
"IRC Sec. 469 classifies rental activity as passive by default, and passive losses do not offset wages or active business income. There are four ways around it.",
"The $25,000 special allowance under IRC Sec. 469(i) is available to active participants with modified adjusted gross income below $150,000. It phases out entirely above that, so it rarely helps the investors who need it most.",
"Real estate professional status under IRC Sec. 469(c)(7) requires more than 750 hours and more than half of all personal service time in real property trades or businesses, met by one spouse individually. For a household with one spouse managing real estate full time, this is the strongest position available.",
"The seven-day rule under Treasury Regulation Sec. 1.469-1T(e)(3)(ii)(A) removes short-term rentals from the rental category entirely, requiring only material participation. This is the route available to a full-time professional who cannot possibly qualify as a real estate professional.",
"Passive income from other holdings absorbs losses directly, which is why investors with a mixed portfolio often have more flexibility than they realize.",
"An investor without any of these exits will suspend every dollar of deduction a cost segregation study produces. Determining which exit applies is the first conversation, not the last.",
]),
("Step Two: Accelerate Depreciation Where It Will Be Used", [
"A cost segregation study reclassifies components of a building from the 27.5 or 39 year schedule into five-year, seven-year, and 15-year property under IRC Sec. 168. Those shorter-lived components are eligible for bonus depreciation under IRC Sec. 168(k), which the One Big Beautiful Bill Act restored to 100% permanently for property acquired and placed in service after January 19, 2025.",
"Residential rental property typically reclassifies 20% to 28% of depreciable basis. Short-term rentals reclassify higher because of furnishings. Specialized commercial property can exceed 40%.",
"Used property qualifies. Since 2017, bonus depreciation applies to property that is new to you rather than newly built, which is why studies on acquisitions of existing buildings became so much more valuable.",
"Timing matters as much as amount. A look-back study filed with Form 3115 claims the entire cumulative missed depreciation as a Sec. 481(a) adjustment in the current year, with no amended returns. That means the deduction can be placed in the year it is worth the most rather than the year you happened to buy.",
]),
("Step Three: Get the Entity Structure Right Before You Close", [
"Entity choice affects how much loss you can actually deduct, independent of the passive rules.",
"In an LLC taxed as a partnership, your basis includes your share of qualified nonrecourse financing under IRC Sec. 752, so a leveraged property supports losses well beyond your cash contribution.",
"In an S corporation, shareholders receive no basis for entity-level debt under IRC Sec. 1366(d). The same property and the same study produce a substantially smaller deductible loss.",
"S corporations also make distributing appreciated property a taxable event under IRC Sec. 311(b), which a partnership generally avoids under IRC Sec. 731. Real estate does not belong in an S corporation.",
"Above the entity level, liability isolation, charging order protection, and state franchise tax cost all trade against one another. A structure with eight California LLCs costs $6,400 annually in minimum franchise tax alone before anyone looks at income.",
]),
("Step Four: Plan the Exit From the Beginning", [
"Every dollar of accelerated depreciation returns at sale. The reclassified five-year property is Sec. 1245 property that recaptures at ordinary rates up to 37%. The building and land improvements produce unrecaptured Sec. 1250 gain at up to 25%.",
"That is not an argument against acceleration. It is an argument for knowing which exit you are heading toward.",
"A 1031 exchange under IRC Sec. 1031 defers the entire gain including both recapture layers, though personal property in a furnished rental is boot since the 2017 changes limited exchanges to real property.",
"An installment sale under IRC Sec. 453 spreads capital gain but recognizes all Sec. 1245 recapture in the year of sale, which means the down payment has to be sized against that liability.",
"Holding until death eliminates it entirely. Under IRC Sec. 1014 the basis steps up to fair market value and all accumulated depreciation disappears for income tax purposes. Buy, depreciate, refinance tax free, exchange rather than sell, and hold. That is the actual endgame.",
]),
("Step Five: Maintain the Records the Strategy Depends On", [
"Three record sets determine whether the plan survives an examination and whether the deductions are available when you need them.",
"A contemporaneous participation log, recording date, hours, property, and a specific description of the work, corroborated by emails, invoices, and platform activity. Reconstructions prepared after a notice consistently fail.",
"Basis and at-risk schedules by activity, maintained from acquisition. Both limits carry forward indefinitely, so the records matter for the entire hold period.",
"Suspended passive loss records at the property level rather than in aggregate. Property-level records preserve partial disposition relief under Treasury Regulation Sec. 1.469-4(g), which aggregate-only records forfeit.",
]),
("What Working With Us Looks Like", [
"We start with the loss exit question and your full income picture, not with a property. That determines whether a study produces a current deduction or a carryforward, and it changes what we recommend you buy next.",
"We model federal and state results together. Many states decouple from bonus depreciation, and an investor in California, New Jersey, New York, or Massachusetts who budgets for a proportional state refund will be disappointed.",
"We run cost segregation studies with engineering support and a full component listing, because a study you cannot defend is worse than no study.",
"And we tell you when the answer is no. Below roughly $400,000 of depreciable basis on a residential property, or where the loss will suspend indefinitely with no path to using it, a study frequently does not pay for itself. We would rather say so.",
]),
],
"faqs": [
("Why are my rental losses not reducing my tax bill?",
 "Because IRC Sec. 469 classifies rental activity as passive by default, and passive losses offset only passive income. There are four exits: the $25,000 allowance, real estate professional status, the seven-day short-term rental rule, and passive income from other holdings."),
("How much does a cost segregation study produce?",
 "Residential rental property typically reclassifies 20% to 28% of depreciable basis into bonus-eligible components. Short-term rentals run higher because of furnishings, and specialized commercial property can exceed 40%. The reclassified amount is generally fully deductible in the first year."),
("Can I run a study on a property I have owned for years?",
 "Yes. A look-back study filed with Form 3115 claims the entire cumulative missed depreciation as a Sec. 481(a) adjustment in the current year, with no amended returns required. This also lets you place the deduction in the year it is worth the most."),
("Should I hold rental property in an S corporation?",
 "No. Shareholders receive no basis for entity-level debt under IRC Sec. 1366(d), which caps your deductible loss, and distributing appreciated property out is taxable under IRC Sec. 311(b). An LLC taxed as a partnership or a disregarded entity avoids both problems."),
("What happens to the depreciation when I sell?",
 "It returns in layers: Sec. 1245 recapture at ordinary rates on the reclassified personal property, unrecaptured Sec. 1250 gain at up to 25% on the building and land improvements, then long-term capital gain. A 1031 exchange defers all of it, and holding until death eliminates it under IRC Sec. 1014."),
],
"related": [
("/blog/passive-activity-loss-rules-rental-property/", "Passive activity loss rules for rental property"),
("/blog/what-is-the-750-hour-rule-for-real-estate-professionals/", "The 750 hour rule for real estate professionals"),
("/short-term-rentals/", "Short-term rental tax strategy"),
("/blog/form-3115-cost-segregation-catch-up/", "Form 3115 catch-up depreciation"),
("/blog/entity-structuring-rental-property-portfolios/", "Entity structuring for rental portfolios"),
],
"cta_head": "Start With the Exit, Not the Property",
"cta_body": "Bring your income picture, your household situation, and your current portfolio. We will tell you which loss exit is available to you before we talk about any study.",
},

{
"slug": "1031-exchange-planning",
"standalone": True,
"crumb_name": "Services", "crumb_path": "services",
"title": "1031 Exchange Planning",
"meta_title": "1031 Exchange Planning and Coordination (2026) | AE Tax Advisors",
"meta_desc": "Exchange timelines, boot avoidance, identification strategy, and coordination with cost segregation. What has to be decided before you list the property.",
"category": "Real Estate Tax Planning", "date": D,
"intro": [
"A 1031 exchange defers the entire gain on an investment property sale, including depreciation recapture. It is the single most powerful deferral available to a real estate investor and the one most often executed badly.",
"The failures are almost never about the qualified intermediary or the paperwork. They are about decisions made before the property was ever listed.",
],
"sections": [
("The Deadlines Are Absolute", [
"Under IRC Sec. 1031(a)(3), replacement property must be identified within 45 days of the transfer of the relinquished property, and the exchange must be completed within 180 days or by the due date of the return including extensions, whichever is earlier.",
"There are no extensions for a failed acquisition, a financing problem, or a seller who backs out. Limited relief exists for federally declared disasters and nothing else.",
"The 180-day rule interacts with the filing deadline in a way that catches fourth-quarter sellers. An exchange beginning in November has fewer than 180 days available unless the return is extended, and the extension must actually be filed.",
]),
("Identification Strategy", [
"Three rules govern identification. The three-property rule permits identifying up to three properties regardless of value. The 200% rule permits identifying any number so long as their combined fair market value does not exceed 200% of the relinquished property's value. The 95% rule permits identifying more than that only if you acquire at least 95% of the identified value.",
"Most investors use the three-property rule, and most identify only the property they intend to buy. That is the mistake.",
"Identifying a backup costs nothing if the primary closes. A Delaware statutory trust interest makes an excellent third identification because it closes quickly, requires no negotiation, and is available at specific leverage ratios to satisfy debt replacement.",
"An investor at day 42 with a collapsed primary target and no backup identified has a failed exchange and a fully taxable sale.",
]),
("Avoiding Boot", [
"Boot is anything received that is not like-kind property, and it triggers gain recognition to the extent received.",
"Cash boot arises from proceeds not reinvested. Mortgage boot arises when the debt on the replacement is less than the debt on the relinquished property, and it catches investors who reinvested every dollar of equity but paid down debt.",
"The rules are asymmetric in a useful way. Contributing outside cash cures debt relief. Taking on additional debt does not cure cash actually received.",
"The safe pattern is trading up in both value and debt. Trading up in value while reducing debt requires outside cash equal to the reduction.",
"Recognized boot comes out in the worst order first: Sec. 1245 recapture at ordinary rates, then unrecaptured Sec. 1250 gain at 25%, then capital gain. For an investor with a prior cost segregation study, even a small amount of boot is expensive.",
]),
("Coordinating With Cost Segregation", [
"Replacement property basis has two components. Carryover basis from the relinquished property, and excess basis where the replacement cost exceeds the relinquished basis plus boot.",
"Carryover basis is not eligible for bonus depreciation. Excess basis generally is, and a cost segregation study on that excess basis can produce a substantial first-year deduction.",
"Many preparers treat exchanged-into property as having no study opportunity at all, which is wrong whenever the replacement is more expensive than the relinquished property's basis. An investor exchanging a property with $180,000 of remaining basis into a $1,400,000 replacement has roughly $1,220,000 of excess basis available.",
"Suspended passive losses do not release in an exchange, because it is not a fully taxable disposition. They carry over to the replacement property.",
]),
("Partnership and Co-Ownership Problems", [
"IRC Sec. 1031(a)(2) excludes partnership interests. A member of an LLC taxed as a partnership cannot exchange their membership interest, and the entity can only exchange if all members go the same direction.",
"Where co-owners want different outcomes, the standard solution is a drop and swap: the LLC distributes undivided tenancy in common interests to members under IRC Sec. 731, generally without gain, and each former member exchanges independently.",
"The risk is the holding requirement. A distribution executed days before closing invites an argument that the interest was held for sale rather than for investment. Execute the drop as far ahead of the sale as circumstances allow, ideally in a prior tax year, and report consistently.",
]),
("What We Do", [
"We model the exchange before the property is listed: the debt replacement requirement, the identification strategy including backups, the boot exposure, and what the tax would be if the exchange failed.",
"We coordinate the timeline against your filing deadline, since a fourth-quarter sale can lose days off the 180-day window without an extension.",
"We evaluate whether the exchange is actually the right answer. An investor with large suspended passive losses and modest gain sometimes does better recognizing the gain, releasing the losses, and investing freely.",
"And we run the cost segregation analysis on the replacement property's excess basis, which is the part almost everyone leaves on the table.",
]),
],
"faqs": [
("What are the 1031 exchange deadlines?",
 "45 days to identify replacement property and 180 days to complete the exchange, or the due date of your return including extensions, whichever is earlier. Under IRC Sec. 1031(a)(3) these are absolute, with limited relief only for federally declared disasters."),
("What is mortgage boot?",
 "Debt relief where the replacement property carries less debt than the relinquished property. It triggers gain even if every dollar of cash proceeds was reinvested. Contributing outside cash equal to the shortfall cures it; taking on more debt does not cure cash you actually received."),
("Can I do a cost segregation study on a property I exchanged into?",
 "Yes, on the excess basis. Carryover basis from the relinquished property is not bonus eligible, but any amount by which the replacement cost exceeds the relinquished basis plus boot generally is. This is commonly overlooked on exchange acquisitions."),
("Do my suspended passive losses release in an exchange?",
 "No. An exchange is not a fully taxable disposition, so the losses stay suspended and carry over to the replacement property. Only a fully taxable disposition of the entire interest to an unrelated party releases them under IRC Sec. 469(g)."),
("Can I exchange my LLC interest?",
 "No. IRC Sec. 1031(a)(2) excludes partnership interests. Where co-owners want different exits, a drop and swap distributing tenancy in common interests under IRC Sec. 731 before the sale is the standard solution, and it should be executed well ahead of closing."),
],
"related": [
("/blog/1031-exchange-timeline-45-180-day-rules/", "1031 exchange 45 and 180 day rules"),
("/blog/what-is-boot-in-a-1031-exchange/", "What is boot in a 1031 exchange"),
("/blog/delaware-statutory-trust-dst-1031-exchange/", "Delaware statutory trusts as replacement property"),
("/blog/tenancy-in-common-vs-llc-real-estate/", "Tenancy in common versus LLC"),
],
"cta_head": "Model the Exchange Before You List",
"cta_body": "Most failed exchanges were decided before the property went on the market. Bring your basis, debt, and timeline and we will map the requirements and the backups.",
},

{
"slug": "compare/best-cpas-high-income",
"standalone": True,
"crumb_name": "Compare", "crumb_path": "compare",
"title": "Best CPAs for High Income Earners: How to Choose",
"meta_title": "Best CPAs for High Income Earners (2026 Comparison) | AE Tax Advisors",
"meta_desc": "Most CPAs file returns rather than reduce taxes. What separates a strategist from a preparer, what to ask, and what proactive planning should cost.",
"category": "Comparison", "date": D,
"intro": [
"Once household income passes roughly $400,000, the value a CPA adds shifts entirely. Accurate preparation is table stakes. What actually moves the number is decisions made during the year, and most firms are not structured to make them.",
"This is a guide to telling the difference, including the questions that separate the two in about ten minutes.",
],
"sections": [
("Preparation and Strategy Are Different Businesses", [
"A preparation practice is a compliance business. It is busy from January through April, priced per return, and measured on accuracy and timeliness. Every strategic decision that mattered was made before the documents arrived.",
"A strategy practice works year round, is priced on the engagement rather than the form, and its output is a set of decisions: entity structure, compensation levels, retirement plan design, asset timing, and elections made before deadlines that most people never hear about.",
"Both are legitimate. The mismatch happens when a high earner hires the first and expects the second.",
"The tell is simple. If the only time you hear from your firm is when they need documents and when the return is ready, you have a preparer.",
]),
("What a High Earner Should Expect", [
"A full-year income projection completed by mid-year, not an estimate produced in March.",
"An entity and compensation review that runs annually, since the optimal S corporation salary moves with income and with the qualified business income wage limitation.",
"Retirement plan design at the level your income supports. A business owner earning $700,000 with a SEP IRA is leaving $150,000 or more of annual deduction unused. A defined benefit or cash balance plan requires actuarial work that takes weeks, so it is a July conversation.",
"Proactive identification of deadlines: S corporation elections, safe harbor 401(k) adoption, pass-through entity tax elections, Sec. 475 elections for traders, and the annual safe harbor elections under the tangible property regulations.",
"Coordination with real estate holdings, including whether a loss exit under IRC Sec. 469 is available before a cost segregation study is commissioned.",
]),
("Questions That Separate the Two", [
"What is my projected taxable income for this year, and when did you last calculate it? A strategist has a number. A preparer has last year's return.",
"How did you determine my reasonable compensation, and when was it last reviewed? The answer should reference survey data and the qualified business income wage limitation, not a round number set years ago.",
"What retirement plan design did you evaluate, and what did you rule out? If nobody modeled a cash balance plan for a business earning above $500,000, nobody was looking.",
"Which elections did you make on my last return, and why? Elections such as the de minimis safe harbor, the aggregation election for real estate professionals, and grouping elections under Treasury Regulation Sec. 1.469-4 are made annually and are frequently missed.",
"What would you do differently if I gave you six months of notice on a large transaction? A strategist has a list. A preparer has a shrug.",
]),
("What It Should Cost", [
"Preparation for a complex individual return with pass-through entities and rental property generally runs $2,000 to $6,000.",
"Proactive advisory work is priced separately and typically runs $6,000 to $20,000 annually depending on complexity, entity count, and whether real estate is involved.",
"The comparison that matters is against what the planning produces. A cash balance plan alone commonly generates $150,000 to $250,000 of annual deduction. An accounting method change for an inventory-heavy business can be a seven-figure one-time deduction. A cost segregation study on a mid-size property produces six figures.",
"An engagement that costs $12,000 and finds $180,000 of deduction is not expensive. A $900 return preparation that finds nothing is not cheap.",
]),
("Warning Signs", [
"A firm that has never asked about your real estate, your equity compensation, or your spouse's activities. The plan cannot be built without the full household picture.",
"Aggressive positions without documentation. Anyone promising to make your income disappear, recommending structures with no business purpose, or citing strategies without authority is creating exposure, not saving tax.",
"No written analysis. Reasonable compensation, entity choice, and plan design should be documented. Verbal advice is not defensible.",
"Deadlines communicated after they pass. If you learn about a March 15 election in April, the relationship is not working.",
]),
("Where AE Tax Advisors Fits", [
"We work with business owners and real estate investors, generally at $400,000 of household income and above, and we do both the planning and the compliance so nothing falls between them.",
"Our engagements start with a full-year projection and a written plan identifying each strategy, its dollar value, its cost, and its deadline. You see the arithmetic before you commit.",
"We handle cost segregation studies with engineering support in house, which matters because the study interacts with the passive activity analysis and the entity structure, and those conversations should not happen with three different firms.",
"We also tell clients when a strategy is not worth it in their situation. That is a shorter list of recommendations and a more useful one.",
]),
],
"faqs": [
("What is the difference between a CPA and a tax strategist?",
 "A CPA credential covers accounting and compliance. A strategist works year round on decisions made before the return: entity structure, compensation, retirement plan design, asset timing, and elections with deadlines. Many CPAs do both, but a preparation-focused practice generally does not."),
("At what income does proactive planning start paying for itself?",
 "Generally around $400,000 of household income, or lower where a business or rental real estate is involved. Below that, the available strategies are fewer and the deduction values smaller relative to the advisory cost."),
("What should proactive tax advisory cost?",
 "Typically $6,000 to $20,000 annually depending on entity count, complexity, and whether real estate is involved, separate from return preparation. Judge it against what the planning produces rather than against a preparation fee."),
("How do I know if my current CPA is doing enough?",
 "Ask what your projected taxable income is this year and when it was last calculated, how your reasonable compensation was determined, and what retirement plan designs were evaluated and ruled out. A strategist has specific answers to all three."),
("Is a more aggressive advisor better?",
 "No. Positions without documentation and structures without business purpose create exposure rather than savings. The strategies worth using are well established in the code and regulations, and a good advisor can cite the authority for each one."),
],
"related": [
("/blog/tax-strategist-vs-cpa-difference/", "Tax strategist versus CPA"),
("/blog/how-to-evaluate-tax-advisor/", "How to evaluate a tax advisor"),
("/blog/when-to-fire-your-cpa-7-red-flags/", "When to fire your CPA"),
("/compare/best-tax-advisors-business-owners/", "Best tax advisors for business owners"),
],
"cta_head": "Ask Us the Five Questions",
"cta_body": "Bring your last return and your current year numbers. We will answer every question in the list above about your specific situation on the call.",
},

{
"slug": "compare/best-tax-advisors-business-owners",
"standalone": True,
"crumb_name": "Compare", "crumb_path": "compare",
"title": "Best Tax Advisors for Business Owners: What to Look For",
"meta_title": "Best Tax Advisors for Business Owners (2026 Comparison) | AE Tax Advisors",
"meta_desc": "Entity design, retirement plan architecture, accounting methods, and exit planning. How to evaluate a tax advisor for a business earning $500K or more.",
"category": "Comparison", "date": D,
"intro": [
"A business owner's tax outcome is decided by four or five structural choices, and each one is made once and then lives for years. Entity type. Compensation level. Retirement plan design. Accounting method. Exit structure.",
"An advisor who gets those right is worth many times their fee. An advisor who never raises them is expensive at any price. Here is how to tell which one you have.",
],
"sections": [
("The Four Decisions That Actually Matter", [
"Entity structure. S corporation election timing, whether a holding company or management company earns its keep, and how multiple businesses relate to one another. These decisions have election deadlines, and Form 2553 is generally due within two months and fifteen days of the start of the tax year it applies to.",
"Compensation. Reasonable compensation is a defensible number derived from survey data, not a round figure. Above the qualified business income threshold it also drives the W-2 wage limitation under IRC Sec. 199A, so minimizing salary can cost more in lost deduction than it saves in payroll tax. The optimum moves annually.",
"Retirement plan architecture. A safe harbor 401(k) with new comparability profit sharing is the base. A cash balance plan layered on top can add $150,000 to $300,000 of annual deduction for an owner over 45. The staff cost depends entirely on demographics and must be quantified by an actuary before adoption.",
"Accounting method. For businesses under the IRC Sec. 448(c) gross receipts threshold, a change from accrual to cash produces a Sec. 481(a) adjustment equal to receivables less payables, deducted entirely in the year of change. For a receivable-heavy or inventory-heavy business this is frequently the single largest deduction available, and it is routinely never raised.",
]),
("What a Good Advisor Does Differently", [
"They work from a projection. Every recommendation is measured against a full-year income estimate produced by mid-year, not against last year's return.",
"They quantify before they recommend. Each strategy comes with a dollar value, a cost, and a deadline. You should be able to see the arithmetic.",
"They say no. A plan with four recommendations you will actually implement beats a menu of twenty. An advisor who never rules anything out is not analyzing.",
"They handle the state layer. Pass-through entity tax elections, state decoupling from bonus depreciation, and multi-state nexus all change the answer, and the federal number alone is misleading in a high-tax state.",
"They plan the exit years ahead. Purchase price allocation under IRC Sec. 1060 is negotiated in the agreement, and shifting value from a non-compete allocation to goodwill can be worth six figures. C corporation exposure and qualified small business stock eligibility are decided at formation, not at sale.",
]),
("Industry Knowledge Is Not Optional", [
"Several of the largest available deductions are industry specific and invisible to a generalist.",
"The FICA tip credit under IRC Sec. 45B for restaurants and salons, worth tens of thousands annually per location and frequently unclaimed.",
"The research credit under IRC Sec. 41 for engineering, manufacturing, and software firms, where the funded research exclusion means contract terms determine eligibility.",
"Accounting method changes for contractors, staffing agencies, and pharmacies, where receivables and inventory make the Sec. 481(a) adjustment enormous.",
"The specified service trade or business analysis under IRC Sec. 199A, where engineering and architecture are excluded from the SSTB list while accounting and consulting are not, and insurance brokerage is not while investment advisory is.",
"An advisor who does not know your industry's provisions will file an accurate return that leaves a great deal on the table.",
]),
("What It Should Cost", [
"Advisory engagements for a business owner generally run $6,000 to $20,000 annually depending on entity count, industry complexity, and whether real estate is involved, separate from preparation.",
"Compare it against the output. A cash balance plan produces $150,000 to $300,000 of annual deduction. An accounting method change can produce a seven-figure one-time deduction. Getting the purchase price allocation right on an exit can be worth several hundred thousand dollars once.",
"The fee is not the variable that matters. The list of strategies actually identified and implemented is.",
]),
("Red Flags", [
"No question about your spouse, your real estate, or your other entities. The plan cannot be built from one business in isolation.",
"Strategies presented without authority. Every legitimate strategy has a code section or regulation behind it, and a good advisor will cite it without being asked.",
"Structures with no business purpose. A management company with no employees, no office, and no activity other than receiving fees will be unwound under IRC Sec. 482, with penalties under IRC Sec. 6662.",
"Deadlines communicated after they pass. Elections under Sec. 2553, safe harbor 401(k) adoption, PTET elections, and the annual tangible property safe harbors all have hard dates.",
]),
("Where AE Tax Advisors Fits", [
"We work with business owners generally at $500,000 of revenue and above, across professional services, healthcare, trades, hospitality, and real estate.",
"Engagements begin with a full-year projection and a written plan listing each strategy with its value, cost, and deadline. You approve the list before we implement.",
"We do the compliance as well, so the plan and the return are built by the same people and nothing gets lost in a handoff.",
"We handle cost segregation studies in house with engineering support, which matters for owners who also hold their real estate, because the study, the self-rental rules, and the entity structure all interact.",
]),
],
"faqs": [
("What are the highest value decisions for a business owner?",
 "Entity structure, reasonable compensation, retirement plan architecture, and accounting method. Each is made once and lives for years, and each has a deadline. Exit structure is the fifth and should be planned three to five years ahead."),
("What is the largest single deduction most owners are missing?",
 "For inventory-heavy or receivable-heavy businesses, a change from accrual to cash accounting under IRC Sec. 448(c). The Sec. 481(a) adjustment equals receivables and inventory less payables, deducted entirely in the year of change, and it is frequently seven figures."),
("How much should business owner tax advisory cost?",
 "Generally $6,000 to $20,000 annually depending on entity count, industry, and whether real estate is involved, separate from preparation. Judge it against the strategies actually identified rather than against a preparation fee."),
("Does industry experience matter?",
 "Substantially. The FICA tip credit, the research credit, industry-specific accounting method opportunities, and the specified service trade or business analysis under IRC Sec. 199A all turn on facts a generalist may not know to ask about."),
("When should I start planning my exit?",
 "Three to five years out. Purchase price allocation under IRC Sec. 1060 is negotiated in the agreement, C corporation exposure requires a five-year built-in gains period under IRC Sec. 1374 to run, and qualified small business stock eligibility is decided at formation."),
],
"related": [
("/blog/tax-planning-business-owners-making-500k/", "Tax planning for business owners making $500K"),
("/blog/3115-change-accounting-method-playbook/", "Accounting method change playbook"),
("/blog/defined-benefit-plan-high-income-business-owners/", "Defined benefit plans for high income owners"),
("/compare/best-cpas-high-income/", "Best CPAs for high income earners"),
],
"cta_head": "See the List Before You Commit",
"cta_body": "Bring your P&L, entity documents, and current plan documents. We will produce a written strategy list with dollar values and deadlines attached.",
},

{
"slug": "compare/tax-alchemy-vs-hall-cpa",
"standalone": True,
"crumb_name": "Compare", "crumb_path": "compare",
"title": "Tax Alchemy vs Hall CPA: Comparing Two Real Estate Tax Approaches",
"meta_title": "Tax Alchemy vs Hall CPA (2026 Comparison) | AE Tax Advisors",
"meta_desc": "One is an education and coaching model, the other a CPA firm serving real estate investors. How the two differ and what each is actually suited for.",
"category": "Comparison", "date": D,
"intro": [
"Investors researching real estate tax help frequently end up comparing these two, and the comparison is harder than it looks because they are not the same kind of business.",
"Understanding what each model actually delivers matters more than comparing price, because the models solve different problems.",
],
"sections": [
("Two Different Business Models", [
"Tax Alchemy operates primarily as an education and coaching offering, teaching real estate tax strategies through courses, community, and coaching rather than acting as your accountant of record.",
"Hall CPA is a licensed CPA firm serving real estate investors, providing preparation, advisory, and related services, along with a substantial content and community presence through their podcast and materials.",
"The distinction matters because an education product cannot sign your return, cannot represent you before the IRS, and cannot be held to a professional standard for advice specific to your facts. A CPA firm can do all three.",
"Conversely, an education model is typically less expensive and can be genuinely valuable for an investor who wants to understand the mechanics before hiring anyone.",
]),
("What Each Model Is Good At", [
"Education and coaching works well when you are early, want to learn the framework yourself, and are not yet at a complexity level where a mistake is expensive. Understanding the seven-day rule, material participation, and how cost segregation works is genuinely useful knowledge for any investor.",
"A CPA firm works well when the decisions have real dollars attached and the facts are specific. Whether your particular manager arrangement kills your 100-hour test, whether your entity structure caps your loss under IRC Sec. 1366(d), and whether your state decouples from bonus depreciation are all fact-specific questions that a course cannot answer.",
"The failure mode of the education model is an investor who learned a strategy, implemented it without the facts being right, and finds out at examination. The failure mode of the firm model is paying for advisory work you did not need.",
]),
("Questions to Ask Either One", [
"Who signs my return, and are they licensed to represent me before the IRS?",
"If I implement a strategy you taught or recommended and it is examined, what is your involvement?",
"How is my specific material participation situation analyzed, given my manager arrangement and hours?",
"What does my state do with bonus depreciation, and how does that change the projection?",
"What is the actual dollar value of this strategy in my situation, and what does it cost to implement?",
"An answer that applies equally to every investor is not an answer to your question.",
]),
("The Strategies Themselves Are Not Proprietary", [
"This is worth stating plainly. The seven-day rule, real estate professional status, cost segregation, the aggregation election, Form 3115 look-back studies, and the Augusta rule are all in the Internal Revenue Code and Treasury Regulations. Nobody owns them.",
"What differs between providers is not access to secret strategies. It is the quality of the fact analysis, the documentation produced, and whether someone stands behind the position.",
"Any provider marketing proprietary strategies unavailable elsewhere is describing marketing, not tax law.",
]),
("Where AE Tax Advisors Fits", [
"We are a licensed firm providing both advisory and compliance, which means the plan and the return are built by the same people.",
"We run cost segregation studies in house with engineering support, so the study, the passive activity analysis, and the entity structure are handled together rather than by three separate providers.",
"Our engagements produce a written plan listing each strategy with its dollar value, its cost, and its deadline, so you can see the arithmetic before committing.",
"And we model federal and state together, which matters a great deal for investors in California, New York, New Jersey, and Massachusetts where the state result diverges sharply from the federal number.",
]),
("Choosing Between Approaches", [
"If you own one or two properties, want to understand the framework, and are comfortable executing with a competent preparer, education plus a good preparer is a reasonable and inexpensive path.",
"If you have a portfolio, a high-income spouse whose situation drives the whole analysis, entity complexity, or a transaction on the horizon, you want a firm that will analyze your specific facts and sign the return.",
"If you are already implementing strategies you learned from a course and have never had someone review whether the facts actually support them, that review is worth doing before an examination makes it urgent.",
]),
],
"faqs": [
("What is the main difference between these two providers?",
 "Business model. One operates primarily as education and coaching; the other is a licensed CPA firm providing preparation and advisory. An education product cannot sign your return, represent you before the IRS, or be held to a professional standard on facts specific to you."),
("Are real estate tax strategies proprietary to any provider?",
 "No. The seven-day rule, real estate professional status, cost segregation, aggregation elections, and Form 3115 look-back studies are all in the code and regulations. What differs is the quality of fact analysis, documentation, and whether someone stands behind the position."),
("Is a course enough to implement these strategies?",
 "It depends on complexity. Understanding the framework is valuable. But whether your specific manager arrangement defeats the 100-hour test, or whether your entity caps your loss under IRC Sec. 1366(d), are fact-specific questions a course cannot answer for you."),
("What should I ask any real estate tax provider?",
 "Who signs the return, what their involvement is if a position is examined, how your specific material participation facts are analyzed, what your state does with bonus depreciation, and the dollar value of each strategy in your situation."),
("I already implemented strategies from a course. What now?",
 "Have someone review whether your facts actually support the positions taken, particularly your participation documentation, entity basis, and state treatment. That review is far cheaper before an examination than during one."),
],
"related": [
("/compare/tax-alchemy-vs-ae-tax/", "Tax Alchemy vs AE Tax Advisors"),
("/compare/hall-cpa-vs-ae-tax/", "Hall CPA vs AE Tax Advisors"),
("/blog/how-to-evaluate-tax-advisor/", "How to evaluate a tax advisor"),
("/blog/what-to-look-for-real-estate-tax-advisor/", "What to look for in a real estate tax advisor"),
],
"cta_head": "Have Your Positions Reviewed Before They Are Examined",
"cta_body": "If you implemented strategies from a course or program, bring us your returns and documentation. We will tell you whether the facts support the positions taken.",
},

{
"slug": "compare/anderson-advisors-vs-mark-kohler",
"standalone": True,
"crumb_name": "Compare", "crumb_path": "compare",
"title": "Anderson Advisors vs Mark Kohler: Comparing Entity and Asset Protection Approaches",
"meta_title": "Anderson Advisors vs Mark Kohler (2026 Comparison) | AE Tax Advisors",
"meta_desc": "Both emphasize entity structuring and asset protection for investors. How the approaches differ, what multi-entity structures actually cost, and what to ask.",
"category": "Comparison", "date": D,
"intro": [
"Both of these providers are known for entity structuring and asset protection, and investors researching them are usually deciding how many entities they actually need.",
"That is the right question, and it deserves a more careful answer than either the maximalist or minimalist position gives.",
],
"sections": [
("Both Emphasize Structure, With Different Emphases", [
"Anderson Business Advisors is known for multi-entity asset protection structures for real estate investors, combining land trusts, LLCs, and holding entities, typically paired with ongoing platinum-style membership services.",
"Mark Kohler is a CPA and attorney known for education, books, and content on entity structuring, the trifecta framework, and small business tax strategy, alongside a firm providing legal and tax services.",
"Both are legitimate and both have substantial followings. The practical question for an investor is not which is better in the abstract but how much structure your situation actually warrants.",
]),
("What Entities Actually Do", [
"An LLC provides liability isolation, protecting your other assets from claims arising from a property, provided you maintain separateness with distinct accounts, adequate capitalization, and no personal expenses run through the entity.",
"Charging order protection works in the other direction, limiting a personal creditor to a charging order rather than reaching entity assets. This is strong in Wyoming, Nevada, Delaware, South Dakota, and Alaska, and weaker elsewhere, particularly for single-member LLCs.",
"A land trust provides privacy in the public record. It provides no liability protection and no tax effect, since it is generally a grantor trust with everything flowing to the beneficiary.",
"None of these change your income tax. A single-member LLC is disregarded, a multi-member LLC is a partnership, and the property is taxed the same either way. Structure is bought for protection, not for tax savings.",
]),
("The Cost Side Nobody Emphasizes", [
"Every entity carries annual cost: state filing fees, registered agent fees, bookkeeping, and often a separate tax return.",
"California charges $800 minimum franchise tax per LLC annually plus a gross receipts fee, and an out-of-state LLC owning California property owes the same. An investor with eight California LLCs pays $6,400 before any tax on income, on properties that may be losing money.",
"Multi-member LLCs file Form 1065 and issue K-1s, adding preparation cost and capital account tracking that did not exist before.",
"A structure that costs $9,000 annually to maintain on a portfolio generating $60,000 of cash flow is a real decision, not an administrative detail. It may still be correct, but the cost belongs in the analysis.",
]),
("What Actually Determines How Much Structure You Need", [
"Equity at risk. Structure protects equity. A portfolio with $200,000 of total equity across four leveraged properties does not warrant the same architecture as one with $4,000,000 of equity.",
"Liability profile. Short-term rentals with guests on site, properties with pools, and multifamily with common areas carry different exposure than a single-family rental on a long lease.",
"Insurance. Adequate primary coverage plus an umbrella policy is the first line and is far cheaper than entity architecture. Structure is what handles claims exceeding coverage, not what replaces it.",
"Your other assets. An investor whose only meaningful asset is the real estate has less to protect than a surgeon with a practice, retirement accounts, and personal net worth.",
"Financing constraints. Most residential lenders will not lend to an LLC at conventional terms, which is why land trusts appear so often, and transfers after closing carry due-on-sale exposure.",
]),
("Questions to Ask Any Structuring Provider", [
"What is the total annual cost of this structure, including filing fees, registered agent fees, bookkeeping, and additional tax returns?",
"What specific claim does this structure protect against that adequate insurance would not?",
"Does this change my income tax at all, and if so how? The honest answer for most real estate structures is that it does not.",
"Which state's law governs my charging order protection, and does that state protect single-member LLCs?",
"What happens to my existing financing when I transfer these properties?",
"A provider who cannot answer the cost question specifically is selling a product rather than analyzing your situation.",
]),
("Where AE Tax Advisors Fits", [
"We are a tax firm, not an asset protection firm, and we say so plainly. For genuine asset protection architecture we work alongside qualified counsel in the relevant state.",
"What we do is make sure the structure does not damage the tax result, which happens more often than people expect. Real estate in an S corporation caps your deductible loss under IRC Sec. 1366(d) and makes distributions taxable under IRC Sec. 311(b). A self-rental arrangement without a grouping election can suspend a large depreciation deduction. Multiple entities can complicate the aggregation election under Treasury Regulation Sec. 1.469-9(g).",
"We also price the structure. Before you adopt an eight-entity architecture, you should see the annual carrying cost next to the protection it provides.",
]),
],
"faqs": [
("Do multiple LLCs reduce my taxes?",
 "No. A single-member LLC is disregarded and a multi-member LLC is a partnership, so the property is taxed the same either way. Entity structure is purchased for liability protection and privacy, not for income tax savings."),
("How many entities do I actually need?",
 "It depends on equity at risk, liability profile, your other assets, and financing constraints. A portfolio with $200,000 of equity does not warrant the same architecture as one with $4,000,000. Adequate insurance plus an umbrella policy is the first line, not entity count."),
("Does a land trust protect me from lawsuits?",
 "No. A land trust provides privacy in the public record only. It gives no liability protection and no tax effect, since it is generally a grantor trust with all income and deductions flowing to the beneficiary. Protection requires an entity holding the beneficial interest."),
("What does a multi-entity structure cost annually?",
 "Filing fees, registered agent fees, bookkeeping, and often separate returns per entity. California alone charges $800 minimum franchise tax per LLC plus a gross receipts fee. Ask any provider for the total annual carrying cost before adopting the structure."),
("Can entity structure hurt my tax result?",
 "Yes. Real estate in an S corporation caps your deductible loss under IRC Sec. 1366(d) and makes distributions of appreciated property taxable under IRC Sec. 311(b). Self-rental arrangements without a grouping election can suspend large depreciation deductions."),
],
"related": [
("/compare/anderson-advisors-vs-ae-tax/", "Anderson Advisors vs AE Tax Advisors"),
("/compare/mark-kohler-vs-ae-tax/", "Mark Kohler vs AE Tax Advisors"),
("/blog/charging-order-protection-llc-by-state/", "Charging order protection by state"),
("/blog/land-trust-vs-llc-for-rental-property/", "Land trust versus LLC"),
],
"cta_head": "Price the Structure Before You Build It",
"cta_body": "Bring the structure you have been quoted. We will tell you what it costs annually, what it does for your taxes, and where it might work against you.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
