"""Batch: final profession tax strategy guides."""

from blog_gen import write_all

C = "Tax Strategy"
D = "2026-08-11"

ARTICLES = [
{
"slug": "tax-strategy-for-home-health-agency-owners",
"title": "Tax Strategy for Home Health Agency Owners: Receivables, Caregivers, and Growth",
"meta_title": "Tax Strategy for Home Health Agency Owners (2026) | AE Tax Advisors",
"meta_desc": "Home health agencies carry heavy payer receivables and caregiver payroll. Accounting method, worker classification, and entity strategy explained for 2026.",
"category": C, "date": D,
"intro": [
"A home health or home care agency has the balance sheet of a staffing company and the regulatory profile of a healthcare provider. Caregivers are paid weekly while Medicare, Medicaid, managed care, and private pay collect over 30 to 90 days.",
"That receivable gap creates the largest tax opportunity most agency owners have never been offered, and the payroll structure creates the largest risk.",
],
"sections": [
("The Accounting Method Opportunity", [
"Under IRC Sec. 448(c), a business with average annual gross receipts below the inflation-adjusted threshold, $31 million for 2025, may generally use the cash method.",
"Most agencies fall well below the threshold and many are nonetheless on the accrual method because a prior accountant configured it that way or because a lender wanted accrual statements. You can present accrual statements to a lender and file on the cash method. Those are separate questions.",
"For a receivable-heavy business, the change is dramatic. An agency with $1,600,000 of payer receivables and $420,000 of accrued payroll and payables carries a $1,180,000 spread. Changing to the cash method via Form 3115 produces a Sec. 481(a) adjustment of that amount, deductible entirely in the year of change.",
"Note that gross receipts means total billings, not net collections after contractual adjustments. Growing agencies cross the threshold sooner than expected, and the opportunity closes when they do. Evaluate it before that happens.",
]),
("Worker Classification Is the Largest Risk", [
"Some agencies engage caregivers as independent contractors. Where the agency sets schedules, assigns clients, sets rates, provides training, and supervises care, that classification is difficult to sustain.",
"Home care is also subject to the Fair Labor Standards Act companionship services rules, which for most agency-employed home care workers require minimum wage and overtime, including for live-in and travel time between clients in many cases.",
"The exposure is not only payroll tax. Misclassification affects overtime liability, workers compensation, state unemployment, retirement plan coverage testing, and licensure. In an acquisition it becomes a diligence finding that reduces price or funds an escrow.",
"Section 530 of the Revenue Act of 1978 provides relief where the agency had a reasonable basis for the treatment, treated all similar workers consistently, and filed all required Forms 1099. Agencies commonly fail the consistency requirement because some caregivers are employees and some are contractors doing identical work.",
"This is one of the few tax issues where the correct answer is frequently to change behavior rather than reporting.",
]),
("Entity Structure and QBI", [
"Home health services are health services and therefore a specified service trade or business under IRC Sec. 199A, so the qualified business income deduction phases out above the income threshold.",
"That simplifies the S corporation salary analysis, since there is no wage limitation to preserve above the phase-out. It is a payroll tax question against reasonable compensation risk.",
"Non-medical home care presents a closer question. Companionship, homemaker, and personal care services performed without a clinical component are arguably not health services within the meaning of the regulations. Agencies operating both lines should track the revenue separately, because the analysis can differ by line.",
"Reasonable compensation for an owner should reflect the actual role. An owner who is also the clinical director or administrator has a compensation profile with two components and the analysis is stronger when it accounts for both.",
]),
("Retirement Plans With a Large Hourly Workforce", [
"Agencies carry many employees relative to owner profit, which makes aggressive plan design harder than in a small professional practice.",
"Using the maximum permissible eligibility requirement of one year and 1,000 hours excludes a meaningful share of a part-time, high-turnover caregiver workforce. That is legitimate plan design and it is what makes an owner-favorable structure feasible.",
"Where the design works, a safe harbor 401(k) with new comparability profit sharing can still direct $70,000 to the owner at manageable staff cost, and a cash balance plan may be viable where the workforce skews younger than the owner.",
"Multi-location agencies should account for controlled group rules under IRC Sec. 414(b) and (c), which treat commonly owned entities as one employer for plan testing regardless of how many LLCs exist.",
]),
("Growth and Acquisition Structure", [
"Home care consolidates through acquisition, and most transactions are asset sales. Under IRC Sec. 1060 the price is allocated across classes, with goodwill and customer relationships producing capital gain and non-compete or consulting allocations producing ordinary income to the seller.",
"On a $4,000,000 sale, moving $700,000 from goodwill to a consulting agreement costs the seller roughly $190,000. Allocation is negotiated in the purchase agreement and is far easier to influence before price is agreed.",
"An acquiring agency buying another agency's book amortizes amounts allocated to goodwill, customer relationships, and non-competes over 15 years under IRC Sec. 197. A $1,800,000 acquisition produces $120,000 of annual deduction for 15 years, and financing does not change it.",
"An agency that changed to the cash method has a specific exit consideration: receivables already deducted produce ordinary income when collected or purchased. This should be modeled during transaction planning and factored into the working capital negotiation.",
]),
("Worked Example: $7.4M Agency", [
"An owner runs a home care agency with $7,400,000 of billings and $690,000 of profit before owner compensation, with 140 caregivers and 9 office staff, structured as an S corporation with a $180,000 salary. The agency is on the accrual method.",
"Receivables are $1,340,000 and accrued payroll and payables are $380,000. Changing to the cash method on Form 3115 produces a $960,000 Sec. 481(a) deduction in the year of change.",
"A worker classification review moves 22 contractors to employee status prospectively, adding roughly $61,000 of annual payroll tax and eliminating an exposure the buyer would have priced at several hundred thousand dollars.",
"A safe harbor 401(k) with new comparability, designed with one-year and 1,000-hour eligibility, directs $70,000 to the owner at approximately $38,000 of staff cost across the eligible population.",
"Taxable income in the transition year falls by more than $1,000,000, and the classification cleanup materially improves the agency's position in an eventual sale.",
]),
],
"faqs": [
("Can a home health agency use the cash method?",
 "Generally yes if average annual gross receipts are under the threshold, $31 million for 2025. Gross receipts means total billings, not net collections, so growing agencies cross the threshold sooner than expected and should evaluate the change before that happens."),
("How large is the accounting method change deduction?",
 "It equals receivables less payables and accrued expenses at the change date, claimed as a Sec. 481(a) adjustment in the year of change. For an agency with heavy payer receivables and weekly caregiver payroll, this is frequently seven figures."),
("Can caregivers be independent contractors?",
 "Rarely, where the agency sets schedules, assigns clients, sets rates, and supervises care. The exposure extends beyond payroll tax to overtime under the FLSA companionship rules, workers compensation, and acquisition diligence. Section 530 relief requires consistent treatment of similar workers, which agencies commonly fail."),
("Does home care qualify for the QBI deduction?",
 "Clinical home health services are health services and therefore a specified service trade or business under IRC Sec. 199A, phasing out above the income threshold. Non-medical companionship and homemaker services present a closer question, so track the lines separately."),
("How is buying another agency's book deducted?",
 "Amounts allocated to goodwill, customer relationships, and non-compete agreements are Sec. 197 intangibles amortized over 15 years. A $1,800,000 acquisition produces $120,000 of annual deduction, and financing does not change the amortization."),
],
"related": [
("/blog/3115-change-accounting-method-playbook/", "Accounting method change playbook"),
("/blog/tax-strategy-for-staffing-agency-owners/", "Tax strategy for staffing agency owners"),
("/blog/purchase-price-allocation-optimization-business-sale/", "Purchase price allocation in a sale"),
],
"cta_head": "The Method Change Window Closes as You Grow",
"cta_body": "Once billings cross the threshold, the opportunity is gone. Send us your balance sheet and trailing billings and we will size it while it is still available.",
},

{
"slug": "tax-strategy-for-trucking-owner-operators",
"title": "Tax Strategy for Trucking Owner Operators: Per Diem, Equipment, and Entity Choice",
"meta_title": "Tax Strategy for Trucking Owner Operators (2026) | AE Tax Advisors",
"meta_desc": "Owner operators get an 80 percent meal deduction, full equipment write-offs, and real S corp savings. Per diem substantiation and entity timing for 2026.",
"category": C, "date": D,
"intro": [
"An owner operator running one truck under their own authority is a business with $200,000 to $400,000 of revenue, six-figure equipment, and a deduction most other taxpayers cannot claim.",
"The three items that move the number most are per diem, equipment timing, and whether the entity structure fits the revenue. Most owner operators get one of the three right.",
],
"sections": [
("The Per Diem Deduction Is Larger Than for Anyone Else", [
"Meals are generally 50% deductible under IRC Sec. 274(n). For individuals subject to Department of Transportation hours of service limitations, IRC Sec. 274(n)(3) raises that to 80%.",
"Owner operators may use the special transportation industry rate for meals and incidental expenses rather than tracking actual costs or location-specific rates, which removes the need to keep meal receipts entirely.",
"The deduction is claimed for each day away from the tax home requiring sleep or rest, with partial days at a prorated rate. For a driver out 280 days a year, this is a substantial and entirely legitimate deduction.",
"What is required is a log establishing which days were spent away from home and where. Electronic logging device records already capture this, which makes substantiation straightforward for anyone who retains them.",
"Company drivers receiving W-2 wages cannot deduct the shortfall between per diem received and the federal rate, because unreimbursed employee expenses are not currently deductible. This provision is only useful to owner operators and to drivers paid as contractors.",
]),
("Equipment Timing Is the Biggest Lever", [
"Tractors and trailers are three-year and five-year property respectively under the MACRS asset classes for over-the-road transportation, and both are fully deductible in the placed-in-service year under IRC Sec. 168(k) or IRC Sec. 179.",
"Because gross vehicle weight rating far exceeds 6,000 pounds, the luxury auto limits in IRC Sec. 280F do not apply.",
"Financing does not reduce the deduction. A $165,000 tractor placed in service in December with 10% down is fully deductible that year. This decouples the purchase decision from cash availability and makes timing a genuine planning variable.",
"The choice between Sec. 179 and bonus matters for an owner operator with variable income. Sec. 179 cannot create a loss and is elected asset by asset, letting you land taxable income on a specific number. Bonus applies by class and can create a net operating loss.",
"Sleeper cab equipment, APUs, inverters, refrigerators, and electronics are separately depreciable five-year property.",
]),
("Entity Structure and When S Corporation Pays", [
"A single-truck owner operator netting $95,000 on a Schedule C pays roughly $13,400 of self-employment tax.",
"Electing S corporation treatment with a $60,000 salary saves approximately $5,000 annually, against perhaps $2,500 of added payroll and compliance cost. The margin is real but not overwhelming at that income level.",
"At $160,000 of net profit, an S corporation with a $85,000 salary saves roughly $11,000 annually, and the case is clear.",
"Reasonable compensation should reflect what a comparable company driver would earn for the same driving, adjusted for the management component. Setting salary at $30,000 on a $160,000 profit invites reclassification.",
"An owner operator running multiple trucks with hired drivers has a stronger case for a lower owner salary percentage, because the profit reflects a return on the business rather than solely on personal driving services.",
"Note that an S corporation election forfeits the ability to deduct self-employed health insurance against self-employment income in the same way, though the above-the-line deduction remains available with proper W-2 reporting.",
]),
("Deductions Owner Operators Commonly Miss", [
"Cell phone and data used for dispatch, navigation, and load boards, allocated to business use.",
"Load board subscriptions, ELD service, dispatch service fees, and factoring fees.",
"Occupational accident insurance, physical damage, and bobtail coverage.",
"Trailer rental, escrow deductions from settlements, and lease purchase payments, which require care because a lease purchase is frequently a financed purchase in substance rather than a lease.",
"Tolls, scales, parking, and lumper fees, which accumulate into real money and are frequently paid in cash without documentation.",
"Home office where a portion of the residence is used regularly and exclusively for dispatch, bookkeeping, and administration. For an owner operator with no other fixed base, this also establishes the tax home for per diem purposes.",
"Health insurance premiums as an above-the-line deduction, and a health savings account if covered by a qualifying high deductible plan.",
]),
("Retirement Plans and Variable Income", [
"Freight rates swing, which makes plan flexibility important.",
"A solo 401(k) is generally the right structure. The employee deferral can be funded during the year and the employer profit sharing portion, up to a $70,000 total in 2025 plus catch-up, is discretionary and decided at filing. Fund heavily in a strong year and lightly in a weak one.",
"For an S corporation, the contribution is based on W-2 wages, which is another reason the salary decision should account for retirement plan capacity rather than being minimized in isolation.",
"An owner operator with a spouse who does the books can put the spouse on payroll, expanding household retirement capacity, though the spouse must perform real work at reasonable compensation.",
]),
("Worked Example: Single Truck Owner Operator", [
"A driver runs one truck under their own authority with $268,000 of gross revenue and $148,000 of net profit before owner compensation, out 274 days a year.",
"Per diem at the special transportation rate for 274 days, at 80% deductibility, produces a deduction of roughly $17,000 that requires only their existing ELD records to substantiate.",
"They elect S corporation treatment with an $82,000 salary, saving approximately $10,300 of self-employment tax annually.",
"A replacement tractor at $172,000 is placed in service in November with 12% down and fully deducted under Sec. 179, sized to land taxable income at the level they wanted.",
"A solo 401(k) funded with a $23,500 deferral plus a $20,500 employer contribution based on the W-2 wage adds $44,000 of deduction.",
"Combined, the plan reduces the tax bill by roughly $73,000 in the year, against a business that had been filing a Schedule C with no structure at all.",
]),
],
"faqs": [
("How much of my meals can I deduct as a driver?",
 "80% rather than the usual 50%, under IRC Sec. 274(n)(3), because you are subject to Department of Transportation hours of service limitations. You may use the special transportation industry per diem rate rather than tracking actual meal costs."),
("Do I need meal receipts?",
 "Not if you use the special transportation industry per diem rate. You need a record of which days you were away from your tax home overnight and where, which your electronic logging device records already establish."),
("Can I deduct a truck I financed?",
 "Yes, in full. Depreciation follows the placed-in-service date, not cash paid. A $165,000 tractor placed in service in December with 10% down is fully deductible that year under IRC Sec. 168(k) or Sec. 179, and the luxury auto limits do not apply given the weight rating."),
("When should an owner operator elect S corporation status?",
 "Generally once net profit consistently exceeds roughly $90,000 to $100,000. At $160,000 of profit the savings are around $11,000 annually against modest added cost. Reasonable compensation should reflect what a comparable company driver earns plus a management component."),
("What retirement plan works with variable freight income?",
 "A solo 401(k). The employee deferral funds during the year and the employer contribution is discretionary and decided at filing, so you can contribute heavily in strong years and lightly in weak ones. For an S corporation the contribution is based on W-2 wages."),
],
"related": [
("/blog/trucking-company-equipment-depreciation-fleet/", "Trucking equipment depreciation and fleets"),
("/blog/how-to-finance-equipment-10-percent-down-full-tax-deduction/", "Financing equipment with 10 percent down"),
("/blog/should-i-elect-s-corp-status-for-my-llc/", "Electing S corp status for your LLC"),
],
"cta_head": "Three Items, Most of the Money",
"cta_body": "Per diem, equipment timing, and entity structure account for most of what is available. Bring your settlement statements and equipment plans.",
},

{
"slug": "tax-strategy-for-it-consultants-and-software-developers",
"title": "Tax Strategy for IT Consultants and Independent Software Developers",
"meta_title": "Tax Strategy for IT Consultants and Developers (2026) | AE Tax Advisors",
"meta_desc": "Consulting is a specified service business but software development often is not. Entity, QBI, R&D credit, and multi-state nexus strategy for 2026.",
"category": C, "date": D,
"intro": [
"An independent developer or IT consultant billing $250,000 to $600,000 has a specific and resolvable set of questions: entity structure, whether the qualified business income deduction is available, whether the research credit applies, and where the income is sourced.",
"The QBI question in particular has a better answer than most consultants assume, and it turns on what you actually do rather than on your job title.",
],
"sections": [
("Consulting Is an SSTB. Software Development Often Is Not.", [
"Treasury Regulation Sec. 1.199A-5(b)(2)(vii) defines consulting as providing professional advice and counsel to clients to assist in achieving goals and solving problems. That is a specified service trade or business, and the qualified business income deduction phases out above the income threshold.",
"The regulations also state that consulting does not include performance of services other than advice and counsel, and specifically excludes services ancillary to the sale of goods where no separate fee is charged.",
"A developer who writes code, builds systems, and delivers working software is not primarily providing advice and counsel. They are producing a work product. That is a meaningfully different position from an advisory consultant who assesses, recommends, and reports.",
"The regulations also exclude from SSTB status businesses whose principal asset is not the reputation or skill of one or more employees or owners in the enumerated fields. Software development, systems integration, and managed services generally fall outside the enumerated fields entirely.",
"For a business with $400,000 of qualified business income, this is an $80,000 deduction. It is worth documenting the nature of the services contemporaneously through engagement letters, statements of work, and deliverable descriptions that reflect what is actually being produced.",
"Where a practice does both, the de minimis rules in Treasury Regulation Sec. 1.199A-5(c) matter. A business under $25,000,000 of gross receipts is not an SSTB if less than 10% of gross receipts come from services in an excluded field. Above that threshold the test is 5%.",
]),
("Entity Structure and Salary", [
"An S corporation is standard once net profit exceeds roughly $90,000. On $320,000 of profit with a $150,000 salary, self-employment tax savings run approximately $15,000 annually.",
"Where the business is not an SSTB and income exceeds the threshold, the W-2 wage limitation under IRC Sec. 199A becomes binding, and cutting salary can cost more in lost QBI deduction than it saves in payroll tax. The optimum is calculated, not assumed, and it moves annually.",
"For a solo developer where the owner is the entire payroll, the wage limitation binds frequently and the optimal salary is higher than payroll tax minimization alone would suggest.",
"Reasonable compensation should reflect market rates for the technical work performed. Salary survey data for the relevant role and market is the support, and it is readily available for technical positions.",
]),
("The Research Credit Applies More Often Than Expected", [
"Software development frequently satisfies the four-part test under IRC Sec. 41(d): a permitted purpose of developing or improving functionality or performance, technological in nature relying on computer science, elimination of uncertainty about capability or method, and a process of experimentation evaluating alternatives.",
"Routine development, maintenance, bug fixes, and adapting existing software to a customer's requirements generally do not qualify. Genuine architectural work, performance optimization under uncertainty, and novel integration problems often do.",
"Internal use software faces a higher standard under IRC Sec. 41(d)(4)(E), requiring innovation, significant economic risk, and unavailability of a commercial alternative. Software developed for sale, lease, or license to third parties is not subject to that higher standard.",
"The funded research exclusion is decisive for consultants. Under Treasury Regulation Sec. 1.41-4A(d), research funded by a client is excluded where payment is not contingent on success and the taxpayer does not retain substantial rights. A fixed-price contract where you bear overrun risk and retain the right to reuse the code or knowledge generally supports the credit. A time-and-materials contract with full IP assignment generally does not.",
"This means two developers doing identical work can get opposite results based on contract terms alone, which is a strong argument for reviewing your standard agreement.",
]),
("Multi-State and International Sourcing", [
"An independent consultant serving clients in a dozen states needs to know where the income is sourced.",
"Most states source service income to where the service is performed, though a growing number use market-based sourcing tied to where the customer receives the benefit. Those two rules produce different answers for remote work, and a consultant working from home in one state for clients in another may have obligations in both.",
"Economic nexus thresholds for income tax and for sales tax differ, and several states impose sales tax on certain software, SaaS, and information services. A developer selling a software product should confirm the sales tax treatment in each state where they have customers, because it varies significantly.",
"Consultants working abroad may qualify for the foreign earned income exclusion under IRC Sec. 911, which requires either the bona fide residence test or the physical presence test of 330 full days in a 12-month period. The exclusion applies to earned income, so an S corporation salary can qualify while distributions cannot.",
]),
("Home Office, Equipment, and Section 174", [
"Home office through an S corporation should run as an accountable plan reimbursement rather than a personal deduction, since unreimbursed employee expenses are not currently deductible.",
"Computers, monitors, servers, networking equipment, and software are five-year property fully deductible in the placed-in-service year, or expensed under the de minimis safe harbor at $2,500 per invoice with a written policy in place before the year begins.",
"Software development costs are also governed by IRC Sec. 174. The 2017 law required capitalization and five-year amortization for domestic research expenditures beginning in 2022, which hit software businesses hard. Legislation enacted in 2025 restored current deductibility for domestic amounts with transition rules for balances capitalized in 2022 through 2024. Confirm how the transition applies to your unamortized balance rather than assuming prior treatment continues.",
]),
("Worked Example: $380,000 Developer", [
"An independent developer nets $380,000 building custom software under fixed-price contracts, retaining the right to reuse components and libraries developed.",
"The engagements are documented as development and delivery of working software rather than advisory services, supporting a non-SSTB position. Qualified business income of approximately $215,000 after salary supports a deduction of $43,000.",
"S corporation salary is set at $165,000, modeled against the W-2 wage limitation rather than minimized, which preserves the full QBI deduction while saving approximately $8,900 of self-employment tax relative to a Schedule C.",
"A research credit study covering three fixed-price projects with genuine architectural uncertainty identifies $186,000 of qualified research expenses, producing a credit of approximately $13,000.",
"A solo 401(k) funded with a $23,500 deferral plus a $41,250 employer contribution adds $64,750 of deduction.",
"Combined annual tax reduction is approximately $58,000, with the QBI position and credit recurring.",
]),
],
"faqs": [
("Are software developers excluded from the QBI deduction?",
 "Often not. Consulting is a specified service business under Treas. Reg. Sec. 1.199A-5(b)(2)(vii), but a developer producing working software is delivering a work product rather than advice and counsel. Software development generally falls outside the enumerated fields entirely."),
("How do I document a non-SSTB position?",
 "Contemporaneously, through engagement letters, statements of work, and deliverable descriptions that reflect what you actually produce. If part of your revenue is advisory, the de minimis rules in Treas. Reg. Sec. 1.199A-5(c) allow up to 10% below $25 million of gross receipts."),
("Can an independent developer claim the R&D credit?",
 "Frequently, on genuine architectural work, performance optimization under uncertainty, and novel integration problems. The funded research exclusion is decisive: a fixed-price contract where you bear risk and retain reuse rights generally supports the credit, while time-and-materials with full IP assignment generally does not."),
("Where is my consulting income taxed?",
 "It depends on the state. Most source service income to where the service is performed, but a growing number use market-based sourcing tied to where the customer receives the benefit. A remote consultant may have obligations in both their home state and client states."),
("Do I still have to capitalize software development costs?",
 "Legislation enacted in 2025 restored current deductibility for domestic research expenditures under IRC Sec. 174, with transition rules for amounts capitalized in 2022 through 2024. Confirm how the transition applies to your unamortized balance rather than assuming."),
],
"related": [
("/blog/rd-tax-credit-section-41-guide/", "The R&D tax credit under Section 41"),
("/blog/tax-strategy-for-saas-founders/", "Tax strategy for SaaS founders"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
],
"cta_head": "Your Contract Language Decides Two Positions",
"cta_body": "The same work qualifies or fails for both QBI and the research credit depending on how the engagement is documented. Send us a sample agreement.",
},

{
"slug": "tax-strategy-for-professional-athletes",
"title": "Tax Strategy for Professional Athletes: Jock Taxes, Signing Bonuses, and a Short Career",
"meta_title": "Tax Strategy for Professional Athletes (2026 Guide) | AE Tax Advisors",
"meta_desc": "Duty day allocation creates filings in a dozen states. Signing bonus sourcing, residency planning, and retirement structures for a compressed earning window.",
"category": C, "date": D,
"intro": [
"A professional athlete has an income profile almost nobody else has: very high earnings compressed into a short window, taxed by every state the team travels to, followed by decades of retirement funded from that window.",
"Three things move the number more than anything else: where you establish residency, how your signing bonus is structured, and how much of the earning window goes into deferred and protected vehicles.",
],
"sections": [
("Duty Day Allocation and the Jock Tax", [
"States tax nonresident athletes on income allocated to services performed in the state, generally using a duty day formula: total compensation multiplied by duty days in the state divided by total duty days.",
"Duty days typically include games, practices, team meetings, travel days, and preseason and postseason activity, though the definition varies by state. Some states include training camp days and some do not, which changes the denominator and therefore every state's allocation.",
"An athlete on a team playing in 20 states files roughly 20 nonresident returns plus a resident return, with credits claimed in the resident state for taxes paid elsewhere. Several cities impose their own taxes on top.",
"The resident state credit generally prevents true double taxation, but it does not eliminate the cost. Where a nonresident state's rate exceeds the resident state's rate, the excess is not recovered by the credit. And a resident of a no-tax state receives no credit benefit at all, since there is no resident tax to offset, which means every nonresident state's tax is a real cost rather than a wash.",
"Accurate duty day tracking is the foundation. Errors compound across every return, and states audit these allocations.",
]),
("Residency Is the Largest Single Decision", [
"For an athlete on a team in a no-tax state, or one who can establish residency in Florida, Texas, Nevada, Tennessee, or Washington, the savings on home games, off-season income, endorsement income, and investment income are substantial.",
"Endorsement and licensing income sourcing is more complex than salary. Income for personal appearances is generally sourced where the appearance occurred. Royalty income for the use of name, image, and likeness is often sourced to the residence state, which makes residency planning worth considerably more for an athlete with large endorsement revenue.",
"High-tax states audit departures aggressively. Domicile turns on where you actually live: family location, home ownership, vehicle and voter registration, physical presence, and where personal and professional connections sit. Day counting is verifiable through travel records and team schedules.",
"An athlete relocating should document the move thoroughly from the beginning and understand that the departure state will examine it.",
]),
("Signing Bonus Structure", [
"A properly structured signing bonus can be sourced entirely to the athlete's state of residence rather than allocated across duty days.",
"The generally accepted requirements are that the bonus is paid separately from salary, is not conditioned on the athlete performing subsequent services, and is nonrefundable.",
"Where those conditions are satisfied, the bonus is compensation for signing rather than for services performed in any state, and it is generally sourced to residence.",
"For an athlete residing in a no-tax state, that can mean a multi-million dollar bonus entirely free of state tax rather than allocated across a dozen taxing jurisdictions.",
"This is a contract drafting matter that must be handled at signing. It cannot be fixed afterward, and it is worth involving tax counsel alongside the agent before the deal is executed.",
]),
("The Compressed Earning Window", [
"An athlete earning $4,000,000 annually for six years must fund a lifetime from that window, and the tax planning should reflect the compression.",
"Deferred compensation arrangements under IRC Sec. 409A, where the league and collective bargaining agreement permit, can shift income into lower-rate years after the playing career ends. The deferral must comply strictly with Sec. 409A election timing and distribution rules, and violations trigger immediate inclusion plus a 20% additional tax.",
"A business entity for endorsement and appearance income, separate from team salary, creates earned income that supports a retirement plan. Team salary generally cannot fund an individual plan, but endorsement income through an S corporation or LLC can support a solo 401(k) and, for an athlete with substantial and sustained endorsement revenue, a cash balance plan.",
"Real estate is common and the mechanics matter. An athlete cannot qualify as a real estate professional under IRC Sec. 469(c)(7) during a playing career. Short-term rentals under the seven-day rule are the accessible route, since only material participation applies and an athlete has concentrated off-season availability.",
]),
("Agent Fees, Training, and Deductions", [
"Agent commissions, union dues, training and conditioning costs, and equipment are business expenses for an athlete treated as self-employed, but employee athletes cannot currently deduct unreimbursed expenses.",
"That distinction matters. Where an athlete is a team employee receiving a W-2, agent fees and training costs are not deductible under current law. Where endorsement and appearance income is earned through a business entity, expenses attributable to that activity are deductible against it.",
"This is another reason to separate endorsement income into an entity rather than reporting it alongside team compensation.",
]),
("Worked Example: Mid-Career Contract", [
"An athlete signs a four-year contract with $3,600,000 of annual salary and a $6,000,000 signing bonus, plus $900,000 of annual endorsement income. The team plays in a high-tax state.",
"The athlete establishes residency in Florida, documented through home purchase, family relocation, vehicle and voter registration, and day counting supported by team travel records.",
"The signing bonus is drafted as separate from salary, nonrefundable, and not conditioned on subsequent services, sourcing it to Florida. State tax avoided on the bonus alone approaches $500,000 relative to duty day allocation across taxing states.",
"Salary is allocated by duty day across the states played in, with nonresident returns filed in each. Because Florida imposes no tax, no resident credit offsets those amounts, making accurate duty day tracking directly valuable.",
"Endorsement income flows through an S corporation with a $300,000 salary, funding a solo 401(k) at $70,000 and allowing deduction of agent commissions and training costs attributable to that activity.",
"A short-term rental acquired in the off-season, self-managed with documented material participation, produces a cost segregation deduction that offsets endorsement income.",
]),
],
"faqs": [
("What is the jock tax?",
 "State taxation of nonresident athletes on income allocated to services performed in the state, generally using a duty day formula. An athlete on a team playing in 20 states files roughly 20 nonresident returns plus a resident return, with several cities imposing their own taxes."),
("Can a signing bonus avoid state allocation?",
 "Often yes, where it is paid separately from salary, is nonrefundable, and is not conditioned on performing subsequent services. It is then compensation for signing rather than for services in any state, and is generally sourced to residence. This must be drafted at signing."),
("Does moving to a no-tax state help?",
 "Substantially, for home games, off-season income, endorsement royalties, and investment income. But it also means no resident credit offsets nonresident state taxes, so duty day accuracy becomes more important, not less. Departure states audit these moves aggressively."),
("Can an athlete deduct agent fees?",
 "Not against W-2 team compensation, since unreimbursed employee expenses are not currently deductible. Where endorsement and appearance income is earned through a business entity, expenses attributable to that activity are deductible against it, which is a reason to separate the income."),
("How can an athlete fund a retirement plan?",
 "Team salary generally cannot fund an individual plan. Endorsement and appearance income earned through an S corporation or LLC creates the earned income needed to fund a solo 401(k), and with sustained revenue, a cash balance plan."),
],
"related": [
("/blog/str-loophole-7-day-rule-explained/", "The short-term rental seven-day rule"),
("/multi-state-global-tax/", "Multi-state and global tax planning"),
("/blog/tax-strategies-for-high-income-w2-earners-over-200k/", "Tax strategies for high income W-2 earners"),
],
"cta_head": "The Contract Is the Planning Document",
"cta_body": "Signing bonus structure and residency have to be settled before the deal is executed. Bring us the term sheet while it is still a term sheet.",
},

{
"slug": "tax-strategy-for-roofing-and-landscaping-contractors",
"title": "Tax Strategy for Roofing and Landscaping Contractors: Seasonality, Fleet, and Method",
"meta_title": "Tax Strategy for Roofing and Landscaping Contractors (2026) | AE Tax Advisors",
"meta_desc": "Seasonal trades face income swings, heavy equipment, and receivable cycles. Accounting method, fleet timing, and entity strategy explained for 2026.",
"category": C, "date": D,
"intro": [
"Roofing and landscaping share a profile that distinguishes them from other trades: sharp seasonality, equipment-heavy operations, and in roofing, receivables tied to insurance claims that collect slowly.",
"Those three facts point to the same three levers, and the accounting method is usually the largest.",
],
"sections": [
("The Accounting Method Change", [
"Under IRC Sec. 448(c), a contractor with average annual gross receipts under the threshold, $31 million for 2025, may generally use the cash method, is exempt from the uniform capitalization rules of IRC Sec. 263A, and may use the completed contract method for long-term contracts.",
"Many contractors are on the accrual method because a bonding company or lender asked for accrual statements. You can present accrual financials to a surety while filing on the cash method. They are separate questions and conflating them is expensive.",
"For a roofer with $1,100,000 of receivables, much of it in insurance claims awaiting adjuster approval and supplement payments, against $340,000 of payables, the change produces a $760,000 Sec. 481(a) deduction in the year of change, filed on Form 3115.",
"Landscaping contractors with maintenance contracts billed in arrears have a similar though usually smaller spread.",
"For a growing contractor this is frequently the single largest deduction available and it is routinely never raised.",
]),
("Fleet and Equipment Timing", [
"Trucks and trailers with gross vehicle weight ratings over 6,000 pounds are outside the luxury auto limits under IRC Sec. 280F and are fully deductible in the placed-in-service year.",
"For landscaping, mowers, skid steers, mini excavators, chippers, aerators, and irrigation equipment are five-year and seven-year property, fully deductible under IRC Sec. 168(k) or IRC Sec. 179.",
"For roofing, conveyors, lifts, compressors, safety systems, and shop equipment follow the same treatment.",
"Upfits count as part of basis or as separate equipment: racks, boxes, liftgates, spray systems, and dump inserts are all deductible.",
"Financing does not reduce the deduction. A $340,000 equipment package placed in service in November with 10% down is fully deductible that year, which decouples the purchase decision from cash availability and makes timing a real planning variable in a seasonal business.",
"The Sec. 179 versus bonus choice matters here. Sec. 179 cannot create a loss and is elected asset by asset, letting a contractor land taxable income at a target. Bonus applies by class and can create a net operating loss. For a business with a bad-weather year, Sec. 179 offers precision.",
]),
("Seasonality and Income Timing", [
"A landscaping contractor earning most of its profit between April and October, and a roofing contractor whose year depends on storm activity, both face year-to-year income swings that ordinary planning does not accommodate.",
"On the cash method, income timing responds to collection and payment decisions. Deferring December collections into January, or accelerating January material purchases into December, shifts income across the year end within the constraints of constructive receipt under Treasury Regulation Sec. 1.451-2.",
"Equipment timing is the larger lever. In a strong year, placing planned equipment in service before December 31 absorbs income. In a weak year, deferring to January preserves the deduction for a year when it is worth more.",
"Retirement plan design should reflect the volatility. A solo or safe harbor 401(k) with discretionary profit sharing lets you fund heavily in a strong year and lightly in a weak one. A cash balance plan requires reasonably consistent funding and is a poor fit for a storm-dependent roofer, however attractive the deduction looks in a single good year.",
]),
("Worker Classification and Crews", [
"Both trades use subcontracted crews extensively, and classification is a recurring exposure.",
"Where the contractor sets schedules, supplies materials and equipment, directs the work, and the crew works exclusively for them, the classification is difficult to sustain regardless of what the agreement says.",
"Section 530 relief requires a reasonable basis, consistent treatment of similar workers, and filed Forms 1099. The consistency requirement is where contractors typically fail, because they often have some crews as employees and some as subcontractors doing identical work.",
"Beyond payroll tax, misclassification affects workers compensation premiums, state unemployment, and licensing. In many states, an uninsured subcontractor's injury becomes the general contractor's workers compensation claim.",
"Requiring certificates of insurance from every subcontractor and retaining them is both a risk practice and evidence supporting the classification.",
]),
("Entity Structure and QBI", [
"Contracting is not a specified service trade or business under IRC Sec. 199A, so the qualified business income deduction is available at any income level, subject to the W-2 wage and qualified property limitations.",
"For a contractor with substantial payroll, the wage limitation is rarely binding, and the deduction is worth 20% of qualified business income. On $600,000 that is $120,000.",
"The qualified property component helps equipment-heavy contractors specifically. The limitation is the greater of 50% of W-2 wages or 25% of wages plus 2.5% of the unadjusted basis of qualified property, and a contractor with $2,400,000 of equipment basis carries meaningful additional capacity under the second prong.",
"S corporation salary should be modeled against the wage limitation rather than minimized, since cutting it can cost more in lost QBI deduction than it saves in payroll tax.",
]),
("Worked Example: Roofing Contractor", [
"An owner runs a roofing company with $8,200,000 of revenue and $980,000 of profit before owner compensation, 34 employees, and an S corporation structure with a $240,000 salary. The company is on the accrual method with $1,240,000 of receivables and $390,000 of payables and accruals.",
"Changing to the cash method on Form 3115 produces an $850,000 Sec. 481(a) deduction in the year of change.",
"A fleet addition of four trucks with upfits and a conveyor package totaling $412,000 is placed in service in the current year and fully deducted.",
"The qualified business income deduction of approximately $148,000 remains available, with the wage limitation not binding given the payroll base.",
"A safe harbor 401(k) with new comparability directs $70,000 to the owner at approximately $44,000 of staff cost across 34 employees.",
"Taxable income in the transition year falls by more than $1,300,000, with the fleet and plan deductions recurring and the method change a one-time item.",
]),
],
"faqs": [
("Can a roofing or landscaping contractor use the cash method?",
 "Generally yes if average annual gross receipts are under the threshold, $31 million for 2025. Many contractors are on accrual only because a bonding company wanted accrual statements, and you can present accrual financials to a surety while filing on the cash method."),
("How large is the method change deduction?",
 "It equals receivables less payables and accrued expenses at the change date, claimed as a Sec. 481(a) adjustment in the year of change. For a roofer with insurance claim receivables, this is frequently high six or seven figures."),
("Are trucks and equipment fully deductible?",
 "Yes. Vehicles over 6,000 pounds gross vehicle weight rating are outside the IRC Sec. 280F limits, and equipment is five-year or seven-year property. All of it is fully deductible in the placed-in-service year, and financing does not reduce the deduction."),
("Do contractors qualify for the QBI deduction?",
 "Yes. Contracting is not a specified service trade or business under IRC Sec. 199A, so the deduction is available at any income level. Equipment-heavy contractors also benefit from the qualified property prong of the wage limitation."),
("Should a seasonal contractor use a cash balance plan?",
 "Usually not. Cash balance plans require reasonably consistent annual funding, and a storm-dependent roofer or weather-dependent landscaper with wide income swings is a poor fit. A 401(k) with discretionary profit sharing accommodates the volatility better."),
],
"related": [
("/blog/tax-strategy-for-hvac-plumbing-contractors/", "Tax strategy for HVAC and plumbing contractors"),
("/blog/construction-company-heavy-equipment-write-off/", "Heavy equipment write-offs for contractors"),
("/blog/3115-change-accounting-method-playbook/", "Accounting method change playbook"),
],
"cta_head": "The Method Change Is Usually the Largest Item",
"cta_body": "For a receivable-heavy trade, one accounting method change frequently outweighs everything else combined. Send us your balance sheet and trailing revenue.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
