"""Batch: Google People Also Ask question targets."""

from blog_gen import write_all

RE = "Real Estate Tax"
CS = "Cost Segregation"
D = "2026-08-10"

ARTICLES = [
{
"slug": "what-is-the-750-hour-rule-for-real-estate-professionals",
"title": "What Is the 750 Hour Rule for Real Estate Professionals?",
"meta_title": "What Is the 750 Hour Rule for Real Estate Professionals? (2026) | AE Tax Advisors",
"meta_desc": "The 750 hour rule is only half of real estate professional status. Both tests, what hours count, and why REPS alone does not unlock losses in 2026.",
"category": RE, "date": D,
"intro": [
"The 750 hour rule comes from IRC Sec. 469(c)(7)(B)(ii), and it is one of two tests you must satisfy to be a real estate professional. Most people who quote it have never seen the other one, which is harder.",
"There is also a third step that catches nearly everyone who clears both tests and expects their rental losses to become deductible.",
],
"sections": [
("The Two Tests", [
"To qualify as a real estate professional for a tax year, you must satisfy both of these.",
"First, more than half of the personal services you perform in all trades or businesses during the year must be performed in real property trades or businesses in which you materially participate.",
"Second, you must perform more than 750 hours of service during the year in real property trades or businesses in which you materially participate.",
"The 750 hours is the easier test. A person spending 15 hours a week on real estate clears it. The more-than-half test is what disqualifies most people, because it compares real estate hours against all working hours.",
"A physician working 2,100 hours in a practice would need more than 2,100 hours in real property trades or businesses to qualify. That is a second full-time job, and the IRS treats claims of that nature with appropriate skepticism.",
]),
("What Counts as a Real Property Trade or Business", [
"IRC Sec. 469(c)(7)(C) lists them: real property development, redevelopment, construction, reconstruction, acquisition, conversion, rental, operation, management, leasing, or brokerage.",
"Brokerage counts, which is why licensed full-time agents qualify readily. Property management counts. Construction counts.",
"What does not count is investing. Time spent researching markets, reviewing listings, studying, attending seminars, or managing a portfolio in an investor capacity is not a real property trade or business. Under Treasury Regulation Sec. 1.469-9(b)(4), an investor's time generally does not count unless they are involved in day-to-day management or operations.",
"Travel time is also contested. The IRS has taken the position that commuting to properties is not qualifying time, and courts have generally been unsympathetic to taxpayers claiming large travel hours.",
]),
("Married Couples Cannot Combine Hours", [
"This is the most commonly misunderstood point. Under IRC Sec. 469(c)(7)(B), the tests must be satisfied by one spouse individually. Hours cannot be combined even on a joint return.",
"So a couple where one spouse works 2,000 hours in a W-2 job and the other spends 900 hours on rentals qualifies through the second spouse, provided that spouse's 900 hours exceed half of their own total working hours. The first spouse's job is irrelevant to the test.",
"But a couple where each spouse spends 500 hours on rentals does not qualify. Neither individually reached 750.",
"Once one spouse qualifies, material participation in the rental activities may be determined by considering the participation of both spouses under IRC Sec. 469(h)(5). That is a separate rule at a separate step, and it is where the combination is permitted.",
]),
("Qualifying Is Not the Same as Deducting", [
"This is where nearly everyone stops too early. Real estate professional status does not make rental losses deductible. It removes rental activities from the automatic passive classification in IRC Sec. 469(c)(2).",
"After that, each rental activity must independently pass one of the material participation tests in Treasury Regulation Sec. 1.469-5T. An investor with nine rentals must materially participate in each one separately, which is nearly impossible.",
"The solution is the aggregation election under Treasury Regulation Sec. 1.469-9(g), which treats all rental real estate interests as a single activity. With that election, you test material participation once across the combined portfolio.",
"The election is made by attaching a statement to an original return. It is binding for future years unless there is a material change in facts, and a late election requires relief procedures. Investors who qualify as real estate professionals but never make the aggregation election frequently find their losses suspended anyway.",
]),
("Documentation Decides Audit Outcomes", [
"Treasury Regulation Sec. 1.469-5T(f)(4) permits proof of participation by any reasonable means and does not require contemporaneous daily reports. In practice, cases are won and lost on records.",
"Taxpayers who bring contemporaneous logs tied to verifiable events, invoices, emails, tenant communications, permit records, and calendar entries, generally prevail. Taxpayers who reconstruct a calendar after receiving an audit notice generally do not, and courts have described such reconstructions in unflattering terms.",
"The log should record date, hours, activity, and property. Round numbers repeated across many days, totals that conveniently land just above 750, and hours claimed during periods when the taxpayer was demonstrably elsewhere are all patterns examiners look for.",
]),
("Worked Example: Who Actually Qualifies", [
"A married couple files jointly. The husband is an anesthesiologist working roughly 1,900 hours annually. The wife left her career two years ago and manages their eleven rental properties full time.",
"The wife logs 1,340 hours across leasing, tenant management, contractor coordination, renovations, and acquisitions. She has no other trade or business, so her real estate hours are 100% of her personal service time, satisfying the more-than-half test, and 1,340 exceeds 750.",
"She qualifies as a real estate professional. The husband does not, and does not need to.",
"They make the aggregation election under Treasury Regulation Sec. 1.469-9(g), treating all eleven rentals as one activity. With combined spousal participation counted under IRC Sec. 469(h)(5), material participation across the aggregated activity is satisfied comfortably.",
"Cost segregation studies on four of the properties produce $412,000 of first-year deductions. Because the activity is non-passive, the loss offsets the husband's practice income directly, saving roughly $165,000.",
"Had they skipped the aggregation election, they would have needed material participation in each of the eleven properties separately, and most of the loss would have suspended.",
]),
],
"faqs": [
("Is 750 hours all I need for real estate professional status?",
 "No. You must also perform more than half of all your personal services in real property trades or businesses in which you materially participate. That second test is what disqualifies most people, since it compares real estate hours against all working hours."),
("Can my spouse and I combine our hours to reach 750?",
 "No. Under IRC Sec. 469(c)(7)(B) the tests must be met by one spouse individually, even on a joint return. Once one spouse qualifies, both spouses' participation may be counted for material participation under IRC Sec. 469(h)(5), which is a separate step."),
("Does time researching properties count?",
 "Generally not. Under Treas. Reg. Sec. 1.469-9(b)(4), time in an investor capacity does not count unless you are involved in day-to-day management or operations. Market research, reviewing listings, studying, and attending seminars are investor activities."),
("Do I still need to do anything after qualifying?",
 "Yes. Qualifying only removes the automatic passive classification. Each rental must still pass material participation individually unless you make the aggregation election under Treas. Reg. Sec. 1.469-9(g), which treats all rentals as one activity. Many people miss this step."),
("What records do I need to prove my hours?",
 "A contemporaneous log recording date, hours, activity, and property, corroborated by invoices, emails, tenant communications, permits, and calendar entries. Reconstructions prepared after an audit notice consistently fail. The regulation permits reasonable means of proof, but examiners test the corroboration."),
],
"related": [
("/blog/real-estate-professional-status-qualification-guide/", "Real estate professional status qualification guide"),
("/blog/material-participation-hours-tracking-template/", "Material participation hours tracking template"),
("/blog/grouping-elections-real-estate-irc-469/", "Grouping and aggregation elections"),
],
"cta_head": "Qualifying Is Step One of Three",
"cta_body": "Most investors who claim REPS have not made the aggregation election and do not have a defensible log. Bring your hours, your properties, and your prior returns.",
},

{
"slug": "can-my-spouse-qualify-for-real-estate-professional-status",
"title": "Can My Spouse Qualify for Real Estate Professional Status?",
"meta_title": "Can My Spouse Qualify for Real Estate Professional Status? (2026) | AE Tax Advisors",
"meta_desc": "One spouse can qualify for REPS and unlock losses against the other's income. How the tests apply per spouse and what documentation survives an audit.",
"category": RE, "date": D,
"intro": [
"Yes, and this is the single most powerful application of real estate professional status for high-income households. One spouse qualifies, and the resulting non-passive losses offset the other spouse's W-2 or business income on a joint return.",
"It is also among the most examined positions on individual returns, because the tax savings are large and the substantiation is often thin.",
],
"sections": [
("Why the Rule Works This Way", [
"IRC Sec. 469(c)(7)(B) requires that the qualifying tests be met by one spouse individually. Hours are not combined for this purpose.",
"That sounds restrictive but is actually the mechanism that makes the strategy work. The high-earning spouse's 2,200 hours in medicine or law do not have to be beaten. They are simply irrelevant to whether the other spouse qualifies.",
"The non-earning or lower-earning spouse only needs to satisfy the tests against their own personal service time. A spouse who does not work outside real estate has 100% of their personal service hours in real estate, satisfying the more-than-half test automatically, and needs only to exceed 750 hours.",
"Because the return is joint, the resulting non-passive loss reduces combined taxable income regardless of which spouse generated it.",
]),
("Where Combining Is Permitted", [
"Once one spouse has qualified as a real estate professional, the material participation analysis for the rental activities is a separate step, and there the rules differ.",
"IRC Sec. 469(h)(5) provides that participation by a spouse is counted in determining whether a taxpayer materially participates. So both spouses' hours count toward the material participation tests in Treasury Regulation Sec. 1.469-5T.",
"This creates a useful two-stage structure. One spouse must independently clear the REPS tests. Then both spouses' hours combine to establish material participation in the rental activities.",
"An anesthesiologist spending 120 hours a year on property decisions adds those hours to their spouse's 1,100 hours for material participation purposes, even though those 120 hours could never help the anesthesiologist qualify as a real estate professional.",
]),
("The Aggregation Election Is Not Optional", [
"Qualifying does not deduct anything. After the REPS determination, each rental activity must independently satisfy material participation, which is unmanageable across a portfolio.",
"The election under Treasury Regulation Sec. 1.469-9(g) treats all rental real estate interests as a single activity, so material participation is tested once across the whole portfolio.",
"The election is made by attaching a statement to a timely filed original return. It binds future years absent a material change in facts. Investors who qualified but never filed the statement often discover the problem during an examination, when relief options are limited and expensive.",
"Revenue Procedure 2011-34 provides late election relief in certain circumstances, requiring that the taxpayer filed consistently as though the election were in effect and had reasonable cause. It is available but not something to rely on.",
]),
("What the IRS Looks For", [
"This position is audited. The examiner's playbook is consistent and worth knowing.",
"They ask for the time log first. If it was created after the notice, that is usually the end of the discussion. They compare claimed hours against the properties owned, since 1,400 hours across two single family rentals is not credible.",
"They check whether a third-party property manager was engaged. Hours claimed for management functions performed by a paid manager are challenged directly, and a management agreement is powerful evidence against the taxpayer.",
"They compare the log against other evidence: travel records, the other spouse's schedule, the qualifying spouse's other activities, social media, and the timing of claimed work against documented events.",
"They test whether the activities were investor activities rather than operations. Reviewing statements, meeting with the CPA, and researching markets do not count.",
]),
("Practical Documentation That Holds Up", [
"Keep the log in real time. A shared calendar or a simple spreadsheet updated weekly is sufficient. The format does not matter. The timing does.",
"Record date, hours, property, and a specific description. Not property management, but showed unit 4 to two applicants, ran screening, drafted lease.",
"Retain corroboration as a matter of course. Emails with tenants and contractors, invoices, permit applications, listing records, bank records showing payments to vendors you coordinated, and photos with metadata.",
"Do not use a full-service property manager if you intend to claim material participation on management activity. If you do use one, your qualifying hours need to come from acquisitions, renovations, and decisions the manager does not make.",
"Avoid round numbers and identical daily entries. Real work does not produce 4.0 hours every weekday.",
]),
("Worked Example: The Standard Fact Pattern", [
"A surgeon earns $840,000. The spouse left a marketing career three years ago and now manages the household's rental portfolio of seven properties, including two under renovation.",
"The spouse logs 1,190 hours across acquisitions, contractor management, leasing, tenant relations, and bookkeeping, documented contemporaneously in a shared calendar with corroborating emails and invoices. No third-party property manager is engaged.",
"The spouse has no other trade or business, so 100% of personal service time is in real property trades or businesses, and 1,190 exceeds 750. The spouse qualifies as a real estate professional.",
"They make the aggregation election under Treasury Regulation Sec. 1.469-9(g) on a timely filed return.",
"Material participation across the aggregated activity is established using both spouses' hours under IRC Sec. 469(h)(5), totaling roughly 1,340.",
"Cost segregation studies on three properties produce $386,000 of first-year deductions. The loss is non-passive and offsets the surgeon's income, saving approximately $158,000 in federal and state tax.",
"The position survives examination because the log exists, the hours are credible for seven properties including two renovations, no property manager was engaged, and the aggregation election was filed on time.",
]),
],
"faqs": [
("Can one spouse qualify while the other works full time?",
 "Yes, and that is the point of the strategy. The tests are applied to each spouse individually under IRC Sec. 469(c)(7)(B), so the working spouse's hours are irrelevant. Because the return is joint, the resulting non-passive loss reduces combined taxable income."),
("Can we combine our hours at any stage?",
 "Yes, but only for material participation. IRC Sec. 469(h)(5) counts a spouse's participation for the material participation tests. It does not apply to the REPS qualification tests themselves, which one spouse must meet alone."),
("Does hiring a property manager disqualify us?",
 "Not automatically, but it makes management hours much harder to claim. Examiners treat a management agreement as strong evidence against the taxpayer for those functions. Qualifying hours then need to come from acquisitions, renovations, and decisions the manager does not make."),
("What if we qualified but never filed the aggregation election?",
 "Each rental must then pass material participation individually, which usually suspends most of the loss. Rev. Proc. 2011-34 offers late election relief where you filed consistently as though the election were in effect and have reasonable cause, but it is not something to plan around."),
("How likely is an audit on this position?",
 "Higher than average. The savings are large, the substantiation is often weak, and the IRS has trained examiners specifically on it. A contemporaneous log with independent corroboration is the difference between winning and losing."),
],
"related": [
("/blog/what-is-the-750-hour-rule-for-real-estate-professionals/", "The 750 hour rule explained"),
("/blog/real-estate-professional-status-2026/", "Real estate professional status in 2026"),
("/blog/how-to-track-material-participation-hours-for-str/", "Tracking material participation hours"),
],
"cta_head": "Build the File Before You Take the Position",
"cta_body": "We help households structure the hours, the election, and the documentation before the return is filed rather than after a notice arrives.",
},

{
"slug": "what-happens-if-i-never-took-depreciation-on-my-rental",
"title": "What Happens If I Never Took Depreciation on My Rental Property?",
"meta_title": "What If I Never Took Depreciation on My Rental? (2026) | AE Tax Advisors",
"meta_desc": "The IRS recaptures depreciation allowed or allowable, so skipping it costs you twice. How Form 3115 recovers missed deductions without amending returns.",
"category": RE, "date": D,
"intro": [
"This is the worst position in rental real estate, and it is more common than you would expect. An owner who never claimed depreciation still owes recapture tax at sale, because the code measures recapture by depreciation allowed or allowable.",
"You pay tax on a deduction you never received. The good news is that the fix does not require amending anything and can produce a very large deduction in the current year.",
],
"sections": [
("Allowed or Allowable Is the Governing Phrase", [
"IRC Sec. 1016(a)(2) reduces basis by depreciation allowed, or allowable if greater. IRC Sec. 1250 then measures recapture against that reduced basis.",
"The practical result is that basis goes down whether or not you claimed the deduction. An owner who held a rental for twelve years and never depreciated it has the same adjusted basis as an owner who depreciated it correctly, and faces the same unrecaptured Sec. 1250 gain at up to 25% on sale.",
"There is no election to skip depreciation. It is not optional, and declining to claim it produces no benefit of any kind.",
]),
("Why Amending Does Not Fix It", [
"Amended returns are limited by the statute of limitations under IRC Sec. 6511, generally three years from filing or two years from payment.",
"An owner who missed depreciation for twelve years can amend at most the last three. The other nine years are closed and the deductions are permanently lost through that route.",
"There is also a technical problem. Failing to claim depreciation for two or more consecutive years establishes an impermissible method of accounting. Once a method is established, it is corrected through a method change under IRC Sec. 446(e), not through amended returns. The IRS position on this is longstanding and consistent.",
]),
("Form 3115 Recovers Everything", [
"A change from an impermissible depreciation method to a permissible one is an automatic change in method of accounting. It is filed on Form 3115 with the current year return, and the cumulative effect is claimed as a Sec. 481(a) adjustment.",
"A negative Sec. 481(a) adjustment, meaning one that decreases income, is taken entirely in the year of change. All twelve years of missed depreciation land in one current-year deduction.",
"No amended returns are required. No prior years are reopened. The automatic change procedures under the applicable revenue procedure govern, and the change is made without a user fee.",
"There is a duplicate copy requirement, filing one copy with the return and one with the IRS national office, and the copy must be filed by the return's filing date including extensions.",
]),
("What This Is Worth", [
"An owner with a $410,000 rental placed in service in 2013 with $340,000 allocated to the building has been entitled to $12,364 of annual depreciation. Over thirteen years that is $160,732.",
"Filing Form 3115 in the current year produces a $160,732 deduction. At a 32% marginal rate that is $51,434 of tax reduction in one year.",
"If the owner also runs a cost segregation study as part of the same method change, the catch-up includes both the missed straight-line depreciation and the accelerated portion the study identifies. That combination frequently doubles the adjustment.",
"The deduction is subject to the passive activity rules under IRC Sec. 469. An owner without real estate professional status or passive income will suspend the loss, which is still better than losing it, but the timing should be planned.",
]),
("The Partial Depreciation Case", [
"A related and equally common situation is depreciating the building but not the land improvements, or using the wrong recovery period, or never adjusting after a major renovation was capitalized incorrectly.",
"All of these are method issues correctable through the same mechanism. A property depreciated over 39 years that should have been on 27.5 years, or a residential rental where $60,000 of site work was folded into the building rather than depreciated over 15 years, both produce a favorable Sec. 481(a) adjustment.",
"Where the error is in the opposite direction, meaning too much depreciation was claimed, the adjustment is positive and increases income. That is spread over four years under the automatic change procedures, which softens it considerably.",
]),
("Do This Before You Sell", [
"The catch-up is only useful while you still own the property. Once the property is sold, the method change is unavailable and the recapture applies to depreciation you never claimed.",
"Owners considering a sale should run the correction first, take the catch-up deduction against current income, and then sell. The recapture on sale is unchanged, since it was going to apply either way, but at least the deduction was received.",
"For an owner planning a 1031 exchange, the timing is similar. Correct the method, claim the adjustment, then exchange.",
]),
("Worked Example: Thirteen Years of Missed Depreciation", [
"An investor bought a duplex in 2013 for $395,000 with $75,000 allocated to land. They reported rental income and expenses each year but never claimed depreciation, because their preparer never asked and they did not know to.",
"Correct annual depreciation on the $320,000 building is $11,636. Over thirteen years, $151,268 was allowable but never claimed.",
"A cost segregation study on the property identifies $76,800 of five-year and 15-year property that should have been separately depreciated, adding further catch-up.",
"Form 3115 is filed with the current year return. The combined Sec. 481(a) adjustment is approximately $209,000, deductible in full in the current year.",
"The investor qualifies for real estate professional status through their spouse and has made the aggregation election, so the loss is non-passive. At a combined 38% marginal rate, the correction produces roughly $79,400 of tax reduction.",
"Without the correction, the same investor would have paid unrecaptured Sec. 1250 gain at up to 25% on $151,268 at sale, roughly $37,800, on deductions never received.",
]),
],
"faqs": [
("Do I owe recapture on depreciation I never claimed?",
 "Yes. IRC Sec. 1016(a)(2) reduces basis by depreciation allowed or allowable, whichever is greater. Skipping depreciation gives you no benefit and no protection. You owe the same recapture as an owner who claimed it correctly."),
("Can I just amend my old returns?",
 "Only three years back under IRC Sec. 6511, and even that is technically the wrong mechanism. Failing to claim depreciation for two or more consecutive years establishes an impermissible accounting method, which is corrected by a method change under IRC Sec. 446(e), not by amending."),
("How does Form 3115 recover the missed depreciation?",
 "It is an automatic change from an impermissible to a permissible method. The cumulative missed depreciation is claimed as a Sec. 481(a) adjustment entirely in the year of change. No prior returns are amended and no years are reopened."),
("Is there a limit on how many years I can recover?",
 "No. The Sec. 481(a) adjustment captures the entire cumulative difference regardless of how many years are involved. An owner who missed twenty years of depreciation recovers all twenty in the current year."),
("Can I still do this if I am selling the property?",
 "Only before the sale closes. Once the property is disposed of, the method change is unavailable and you will pay recapture on depreciation you never received. Run the correction first, claim the adjustment, then sell or exchange."),
],
"related": [
("/blog/form-3115-cost-segregation-catch-up/", "Form 3115 catch-up depreciation"),
("/blog/lookback-depreciation-recovering-missed-deductions/", "Recovering missed depreciation deductions"),
("/blog/depreciation-recapture-planning/", "Depreciation recapture planning"),
],
"cta_head": "Every Year You Wait Is Another Year of Recapture Without the Deduction",
"cta_body": "Send us the closing statement and the years you have owned the property. We will size the Form 3115 adjustment before you file.",
},

{
"slug": "can-i-take-bonus-depreciation-on-a-used-property",
"title": "Can I Take Bonus Depreciation on a Used Property?",
"meta_title": "Can I Take Bonus Depreciation on a Used Property? (2026) | AE Tax Advisors",
"meta_desc": "Yes. Used property has qualified for bonus depreciation since 2017 if it is new to you. The acquisition rules, related party traps, and 2026 rates.",
"category": CS, "date": D,
"intro": [
"Yes. This is one of the most consequential changes in recent depreciation law and one of the most persistently misunderstood. Before 2017, bonus depreciation applied only to original use property. Since then, used property qualifies as long as it is new to the taxpayer.",
"That single change is why cost segregation studies on existing buildings became so much more valuable than they used to be.",
],
"sections": [
("The Requirement Is First Use by You", [
"Under IRC Sec. 168(k)(2)(E)(ii), used property qualifies if the taxpayer did not previously use the property and it was not acquired from a related party or in certain carryover basis transactions.",
"The property does not have to be new. A 1974 apartment building purchased in 2026 contains five-year and 15-year components that are new to you, and those components qualify for bonus depreciation in full.",
"This is the mechanism behind essentially every cost segregation study on an acquisition. The study identifies the personal property and land improvement components within the purchase price, and those components are bonus eligible because you are the first owner to place them in service in your hands.",
]),
("The Related Party Rules", [
"Property acquired from a related party does not qualify. Related parties are determined under IRC Sec. 267 and IRC Sec. 707(b), which reach family members, controlled entities, and partnerships or corporations with common ownership above the relevant thresholds.",
"Buying a rental from your father, or transferring a property from one entity you control to another, does not produce bonus eligible components. The prior owner's use is attributed to you.",
"This catches investors restructuring their holdings. Moving a property from an individual name into an LLC the individual owns is a non-event with no new basis and no bonus depreciation. Selling a property between two LLCs both owned by the same person is a related party transaction.",
"Property acquired in a transaction with carryover basis, including gifts under IRC Sec. 1015 and most tax-free reorganizations, also fails the test because basis carries over rather than being newly determined.",
]),
("The 1031 Exchange Complication", [
"In a like-kind exchange, replacement property basis has two components. Carryover basis from the relinquished property, and excess basis to the extent the replacement property cost exceeds the relinquished property's basis plus boot.",
"Carryover basis is not bonus eligible, because it is not newly acquired basis. Excess basis generally is, and a cost segregation study can identify bonus eligible components within it.",
"An investor exchanging a property with $180,000 of remaining basis into a $1,400,000 replacement has roughly $1,220,000 of excess basis. A study on that excess basis at a 25% reclassification rate produces $305,000 of bonus eligible property.",
"This is meaningful and routinely missed. Many preparers treat exchanged-into property as having no cost segregation opportunity at all, which is wrong whenever the replacement is more expensive than the relinquished property's basis.",
]),
("The Current Rate", [
"Bonus depreciation was scheduled to phase down after 2022, dropping to 80% in 2023, 60% in 2024, and 40% in 2025.",
"The One Big Beautiful Bill Act enacted in 2025 restored 100% bonus depreciation permanently for qualifying property acquired and placed in service after January 19, 2025.",
"That means a study run today on qualifying components produces a full first-year deduction rather than a phased one. It also means the urgency that drove year-end decisions during the phase-down has eased, which changes the timing calculus for owners who were rushing to beat a declining rate.",
"Property acquired under a binding contract before the effective date may still fall under the prior phase-down schedule, so acquisition dates matter and should be checked rather than assumed.",
]),
("What Components Actually Qualify", [
"Bonus depreciation applies to property with a recovery period of 20 years or less. In a building, that means five-year personal property, seven-year property, and 15-year land improvements.",
"It does not apply to the 27.5-year or 39-year building structure. That portion depreciates on its normal schedule regardless.",
"Qualified improvement property under IRC Sec. 168(e)(6) carries a 15-year life and is bonus eligible, which is why interior renovations of nonresidential buildings recover so quickly.",
"A typical study on a residential rental reclassifies 20% to 28% into these categories. A study on a specialized commercial property can reach 40% or more.",
]),
("Worked Example: Used Fourplex", [
"An investor buys a 1978 fourplex in 2026 for $1,180,000. Land is allocated at $195,000, leaving $985,000 depreciable.",
"The building is nearly fifty years old and every component in it has been used continuously since construction. None of that matters. The investor did not previously use the property and did not acquire it from a related party.",
"A cost segregation study identifies five-year property of $167,450 and 15-year land improvements of $88,650, together 26% of depreciable basis.",
"All $256,100 is bonus eligible at 100% and deductible in the first year. The remaining $728,900 of structure depreciates over 27.5 years, adding roughly $26,505.",
"First-year depreciation is approximately $282,605 against $35,818 on a straight-line schedule. At a 35% marginal rate, that is roughly $86,400 of additional tax deferral in year one on a fifty-year-old building.",
]),
],
"faqs": [
("Does bonus depreciation apply to used property?",
 "Yes. Since the 2017 law change, used property qualifies under IRC Sec. 168(k)(2)(E)(ii) as long as you did not previously use it and did not acquire it from a related party. This is why cost segregation on existing buildings became so much more valuable."),
("Can I take bonus depreciation on a property I bought from a family member?",
 "No. Property acquired from a related party under IRC Sec. 267 or Sec. 707(b) is excluded, and the prior owner's use is attributed to you. This also blocks transfers between entities you control and property received by gift with carryover basis."),
("What is the bonus depreciation rate right now?",
 "100%, restored permanently by the One Big Beautiful Bill Act for qualifying property acquired and placed in service after January 19, 2025. Property under a binding contract before that date may still fall under the prior phase-down schedule, so acquisition dates matter."),
("Can I use bonus depreciation on property I acquired in a 1031 exchange?",
 "On the excess basis, yes. Carryover basis from the relinquished property is not bonus eligible, but any excess basis where the replacement cost exceeds the relinquished basis plus boot generally is. This is commonly overlooked on exchange acquisitions."),
("Which parts of a building qualify?",
 "Only components with a recovery period of 20 years or less: five-year personal property, seven-year property, and 15-year land improvements, plus qualified improvement property. The 27.5-year or 39-year structure itself is never bonus eligible."),
],
"related": [
("/blog/bonus-depreciation-obbba-permanent-100-percent/", "Permanent 100% bonus depreciation under OBBBA"),
("/blog/can-i-do-a-cost-segregation-study-on-a-property-i-already-own/", "Cost segregation on property you already own"),
("/blog/cost-segregation-new-construction-vs-existing/", "New construction versus existing property studies"),
],
"cta_head": "Age of the Building Is Irrelevant",
"cta_body": "If you bought it and you did not previously use it, the components are bonus eligible. Send us the closing statement and we will size the study.",
},

{
"slug": "section-179-vs-bonus-depreciation-difference",
"title": "Section 179 vs Bonus Depreciation: Which One Should You Use?",
"meta_title": "Section 179 vs Bonus Depreciation Difference (2026) | AE Tax Advisors",
"meta_desc": "Both give a full first-year deduction, but Sec. 179 cannot create a loss and gives asset-level control. Full comparison and when to use each in 2026.",
"category": CS, "date": D,
"intro": [
"Both provisions deduct the full cost of qualifying property in the year it is placed in service. With 100% bonus depreciation restored permanently, many owners assume the choice no longer matters.",
"It matters more than ever, because the differences are now entirely about control rather than about rate. Four distinctions decide which one you want.",
],
"sections": [
("Difference One: Section 179 Cannot Create a Loss", [
"IRC Sec. 179(b)(3) limits the deduction to the taxpayer's aggregate taxable income from the active conduct of any trade or business. Any excess carries forward.",
"Bonus depreciation under IRC Sec. 168(k) has no such limit. It can drive taxable income negative, creating a net operating loss.",
"For a profitable business, this rarely binds. For a startup, a business having a down year, or a real estate investor with limited active business income, it binds constantly.",
"The carryforward is not lost, but it is deferred, and the taxpayer who wanted a current deduction does not get one.",
]),
("Difference Two: Section 179 Is Elected Asset by Asset", [
"You choose which specific assets receive Sec. 179 treatment and how much of each asset's cost to expense. You can take $40,000 on a $95,000 machine and depreciate the rest normally.",
"Bonus depreciation applies automatically to all qualifying property in a class unless you elect out, and the election out applies to the entire class for that year. You cannot bonus one five-year asset and not another.",
"This makes Sec. 179 the precision instrument. A business owner who wants taxable income to land at a specific number, perhaps to stay under a qualified business income threshold, to preserve a credit, or to manage a state tax result, uses Sec. 179 to hit the target.",
]),
("Difference Three: The Dollar Caps", [
"Sec. 179 has a dollar limit and a phase-out. For 2025 the deduction limit is $2,500,000, reduced dollar for dollar once qualifying property placed in service exceeds $4,000,000. These amounts are indexed annually.",
"Bonus depreciation has no dollar cap at all. A taxpayer placing $18,000,000 of qualifying property in service deducts all of it.",
"For most owners the Sec. 179 cap is irrelevant. For a large contractor, a manufacturer, or a real estate investor running multiple cost segregation studies in a year, bonus is the only provision that can absorb the volume.",
]),
("Difference Four: What Property Qualifies", [
"Sec. 179 reaches some property bonus depreciation does not. Under IRC Sec. 179(f), qualified real property includes roofs, HVAC, fire protection and alarm systems, and security systems installed on nonresidential real property after the building was placed in service.",
"That is meaningful. A $180,000 roof replacement on a commercial building is 39-year property, not bonus eligible, but can be expensed under Sec. 179.",
"Sec. 179 also applies to certain property used in furnishing lodging, which was formerly excluded.",
"Bonus depreciation reaches property Sec. 179 does not in one important respect. Sec. 179 requires property used in the active conduct of a trade or business. Property used in a passive rental activity generally does not qualify. Bonus depreciation has no such requirement, which is why cost segregation studies on rental real estate rely on bonus rather than Sec. 179.",
]),
("State Conformity Is the Quiet Factor", [
"Many states decouple from federal bonus depreciation while conforming to Sec. 179, often at a lower cap.",
"Pennsylvania, New Jersey, California, and several others require add-backs of federal bonus depreciation, recomputing state depreciation on a different schedule. That creates a permanent difference in timing and ongoing compliance complexity.",
"Where a state conforms to Sec. 179 but not bonus, electing Sec. 179 can produce a matching state deduction that bonus depreciation would not. For a business operating primarily in one such state, this can flip the analysis entirely.",
"The state analysis should be run alongside the federal one rather than after.",
]),
("The Ordering Rule", [
"Where both apply, Sec. 179 is taken first, then bonus depreciation on the remaining basis, then regular MACRS depreciation on whatever remains.",
"This ordering is useful. A taxpayer can elect Sec. 179 on a specific asset to capture a state benefit, then let bonus handle the rest of the class federally.",
]),
("Worked Example: Two Owners, Different Answers", [
"A contractor has $840,000 of business income and buys $620,000 of equipment. Either provision fully deducts it. The contractor operates in Pennsylvania, which disallows bonus depreciation but conforms to Sec. 179 at the federal limit. Electing Sec. 179 produces a matching state deduction worth roughly $19,000 that bonus would not. Sec. 179 wins.",
"A real estate investor buys a $2,400,000 apartment building and runs a cost segregation study identifying $610,000 of five-year and 15-year property. Sec. 179 is largely unavailable, because rental real estate is generally not an active trade or business for this purpose. Bonus depreciation is the only route, and it produces the full $610,000 deduction.",
"A startup manufacturer has $180,000 of business income and places $740,000 of equipment in service. Sec. 179 is capped at $180,000 by the taxable income limit, with the rest carrying forward. Bonus depreciation deducts the entire $740,000, creating a net operating loss the owner can carry forward under IRC Sec. 172. Bonus wins.",
"A medical practice owner with $960,000 of income wants taxable income to land at $394,000 to manage a specific threshold. Sec. 179 lets them elect exactly $566,000 across selected assets. Bonus would take everything in the class. Sec. 179 wins.",
]),
],
"faqs": [
("Which is better, Section 179 or bonus depreciation?",
 "Neither is universally better. Bonus depreciation has no dollar cap and can create a loss, making it right for large purchases and for rental real estate. Sec. 179 gives asset-by-asset control and often produces a state deduction where bonus does not."),
("Can Section 179 create a net operating loss?",
 "No. IRC Sec. 179(b)(3) limits the deduction to aggregate taxable income from the active conduct of a trade or business, with the excess carrying forward. Bonus depreciation has no such limit and can drive taxable income negative."),
("Can I use Section 179 on rental property?",
 "Generally not for the personal property components identified in a cost segregation study, because Sec. 179 requires active conduct of a trade or business and most rental activity does not qualify. This is why cost segregation studies rely on bonus depreciation."),
("Can I expense a new commercial roof?",
 "Under Sec. 179, yes. Qualified real property under IRC Sec. 179(f) includes roofs, HVAC, fire protection, alarm, and security systems installed on nonresidential real property after it was placed in service. Bonus depreciation does not reach these, since they are 39-year property."),
("Do states treat them the same way?",
 "Often not. Many states disallow federal bonus depreciation and require an add-back while conforming to Sec. 179, sometimes at a lower cap. Pennsylvania, New Jersey, and California are common examples. Run the state analysis alongside the federal one."),
],
"related": [
("/blog/section-179-deduction-2026-complete-guide/", "Section 179 complete guide"),
("/blog/bonus-depreciation-obbba-permanent-100-percent/", "Permanent 100% bonus depreciation"),
("/blog/how-to-time-equipment-purchases-maximum-tax-benefit/", "Timing equipment purchases"),
],
"cta_head": "The Choice Is About Control, Not Rate",
"cta_body": "With bonus at 100%, the deciding factors are your state, your income level, and where you want taxable income to land. Bring your purchase list and P&L.",
},

{
"slug": "does-cost-segregation-work-on-inherited-property",
"title": "Does Cost Segregation Work on Inherited Property?",
"meta_title": "Does Cost Segregation Work on Inherited Property? (2026) | AE Tax Advisors",
"meta_desc": "Inherited property gets a stepped-up basis and a fresh depreciation schedule. Why cost segregation on inherited real estate is often unusually valuable.",
"category": CS, "date": D,
"intro": [
"Yes, and inherited property is frequently a better candidate than a purchase, for a reason most heirs never hear. The stepped-up basis under IRC Sec. 1014 resets the property's basis to fair market value at the date of death, and depreciation starts over from that new number.",
"An heir inheriting a property their parent had nearly fully depreciated gets a fresh, much larger depreciable basis. A cost segregation study on that basis produces a large deduction on a property that had stopped generating any.",
],
"sections": [
("The Step-Up Resets Everything", [
"Under IRC Sec. 1014(a), the basis of property acquired from a decedent is its fair market value on the date of death, or on the alternate valuation date if elected.",
"Prior depreciation disappears. The decedent's accumulated depreciation does not carry over, and there is no recapture at death. This is the single most powerful provision in the code for real estate held long term.",
"A property purchased for $260,000 in 1994, depreciated to a $40,000 adjusted basis, and worth $920,000 at the owner's death passes to the heir with a $920,000 basis. The $880,000 of appreciation and the $220,000 of accumulated depreciation both vanish for income tax purposes.",
"The heir then allocates the new basis between land and building and begins a new depreciation schedule.",
]),
("The New Depreciation Schedule", [
"Depreciation restarts under IRC Sec. 168 as though the heir placed the property in service on the date of death, using the full recovery period. Residential rental restarts at 27.5 years. Nonresidential restarts at 39.",
"This is worth emphasizing. The heir does not inherit the decedent's remaining recovery period. A property with three years left on a 27.5-year schedule in the decedent's hands starts a fresh 27.5 years in the heir's hands.",
"On the example above, with $920,000 stepped-up basis and $170,000 allocated to land, the heir has $750,000 of depreciable basis producing $27,273 of annual depreciation on a property that was generating almost none.",
]),
("Why the Study Is Especially Valuable Here", [
"The stepped-up basis is generally much higher than the decedent's original cost, which means the reclassified components are proportionally larger.",
"A study reclassifying 24% of a $750,000 depreciable basis produces $180,000 of bonus eligible property. The same property studied by the decedent decades ago at a $220,000 depreciable basis would have produced $52,800.",
"The components must be valued as of the date of death, not as of the original construction. This is a valuation exercise and requires an engineering-based study rather than a rule of thumb, since the appraisal establishing date-of-death value typically does not break out components.",
"Where a formal appraisal was obtained for estate purposes, it becomes a useful starting point and helps establish the total, but the component allocation still requires the study.",
]),
("The Bonus Depreciation Question", [
"Property acquired from a decedent has a basis determined under IRC Sec. 1014, which is not a carryover basis. The heir did not previously use the property.",
"Where the heir was not previously an owner or user, the components generally qualify as used property eligible for bonus depreciation under IRC Sec. 168(k)(2)(E)(ii).",
"Where the heir already owned an interest in the property, for example as a co-owner with the decedent, prior use may be attributed and the analysis becomes more nuanced. Only the stepped-up portion attributable to the decedent's interest would be newly acquired.",
"Community property adds a favorable wrinkle. Under IRC Sec. 1014(b)(6), both halves of community property receive a step-up when one spouse dies, not just the decedent's half. A surviving spouse in a community property state gets a full step-up on the entire property, which is substantially better than the half step-up available in a common law state.",
]),
("Timing and the Estate Return", [
"The date-of-death value is established through the estate. Where a federal estate tax return is filed, IRC Sec. 1014(f) requires consistency between the basis claimed by the heir and the value reported on the estate return.",
"Where no estate return is required, which is the case for most estates given the current exclusion, the heir should still obtain a qualified appraisal as of the date of death. Reconstructing that value years later is difficult and invites challenge.",
"This is the single most important action item for an heir. Get the appraisal at the time. It costs a few thousand dollars and establishes the number every future deduction depends on.",
]),
("Passive Loss Considerations", [
"The deduction from a study on inherited property is subject to the same passive activity rules under IRC Sec. 469 as any rental. An heir with a W-2 job and no real estate professional status will suspend the loss.",
"There is a separate rule worth knowing. Under IRC Sec. 469(g)(2), suspended passive losses of the decedent are allowed on the decedent's final return, but only to the extent they exceed the step-up in basis. Because the step-up is usually large, most of the decedent's suspended losses are eliminated rather than deductible.",
"That is a planning point for the decedent, not the heir. An owner with large suspended passive losses and advanced age should consider whether triggering those losses through a disposition during life produces a better result than losing them at death.",
]),
("Worked Example: Inherited Rental Portfolio", [
"An heir inherits three rentals from a parent who bought them between 1996 and 2004. The parent's combined adjusted basis was $186,000 after decades of depreciation. Date-of-death appraised value is $2,340,000.",
"The heir obtains qualified appraisals establishing the $2,340,000 value and the land allocation of $445,000, leaving $1,895,000 of depreciable basis across the three properties.",
"Straight-line depreciation alone on the new basis is $68,909 annually, against roughly $4,000 the parent had been claiming.",
"Cost segregation studies performed as of the date of death identify $492,700 of five-year and 15-year components, 26% of depreciable basis. All of it is bonus eligible under IRC Sec. 168(k).",
"First-year depreciation is approximately $528,000. The heir's spouse qualifies as a real estate professional and the aggregation election is made, so the loss is non-passive.",
"At a combined 37% marginal rate, the first-year benefit is roughly $195,000, on properties that had been generating almost no deduction in the parent's hands.",
]),
],
"faqs": [
("Can I do a cost segregation study on property I inherited?",
 "Yes, and it is often unusually valuable. The stepped-up basis under IRC Sec. 1014 resets depreciable basis to date-of-death fair market value, which is typically far higher than the decedent's remaining basis, so the reclassified components are proportionally larger."),
("Does the depreciation schedule start over when I inherit?",
 "Yes. Depreciation restarts under IRC Sec. 168 as though you placed the property in service on the date of death, using the full recovery period. You do not inherit the decedent's remaining schedule or accumulated depreciation."),
("Is inherited property eligible for bonus depreciation?",
 "Generally yes. Basis determined under IRC Sec. 1014 is not carryover basis, and if you did not previously use the property, the components qualify as used property under IRC Sec. 168(k)(2)(E)(ii). Prior co-ownership complicates this and should be reviewed."),
("What if no estate tax return was filed?",
 "You still need a qualified appraisal as of the date of death. Most estates are below the filing threshold, but the date-of-death value is the foundation of every future deduction. Obtaining it at the time costs a few thousand dollars. Reconstructing it later is difficult and invites challenge."),
("What happens to the decedent's suspended passive losses?",
 "Under IRC Sec. 469(g)(2) they are allowed on the final return only to the extent they exceed the step-up in basis. Because the step-up is usually large, most suspended losses are eliminated. This is a reason for an aging owner with large suspended losses to plan during life."),
],
"related": [
("/blog/lookback-cost-segregation-existing-property/", "Look-back cost segregation on existing property"),
("/blog/can-i-do-a-cost-segregation-study-on-a-property-i-already-own/", "Cost segregation on property you already own"),
("/estate-trust-wealth-transfer/", "Estate, trust, and wealth transfer planning"),
],
"cta_head": "Get the Date of Death Appraisal Now",
"cta_body": "The valuation is the foundation for every deduction that follows, and it gets harder to establish every year. Send us the property details and the date of death.",
},

{
"slug": "what-happens-to-suspended-passive-losses-when-i-sell",
"title": "What Happens to Suspended Passive Losses When I Sell?",
"meta_title": "What Happens to Suspended Passive Losses When I Sell? (2026) | AE Tax Advisors",
"meta_desc": "A fully taxable disposition releases suspended passive losses under IRC Sec. 469(g). What qualifies, what does not, and what happens at death.",
"category": RE, "date": D,
"intro": [
"Suspended passive losses are not lost. They accumulate under IRC Sec. 469(b) and carry forward indefinitely, waiting for either passive income to absorb them or a disposition to release them.",
"The release happens under IRC Sec. 469(g), and the conditions are specific. Getting them wrong means the losses stay suspended through a transaction you expected would free them.",
],
"sections": [
("The Release Rule", [
"IRC Sec. 469(g)(1) provides that when a taxpayer disposes of their entire interest in a passive activity in a fully taxable transaction to an unrelated party, any suspended loss from that activity is treated as not from a passive activity.",
"That last phrase is the whole point. The released loss becomes non-passive, which means it offsets any income, including wages, business income, interest, and dividends.",
"Three conditions must all be satisfied. The disposition must be of the entire interest in the activity. It must be fully taxable. It must be to an unrelated party.",
]),
("Entire Interest Is Strict", [
"Selling three of your five rentals does not release the losses from those three if all five were grouped as a single activity through an aggregation election.",
"This is the trap the aggregation election creates. Grouping all rentals into one activity under Treasury Regulation Sec. 1.469-9(g) is enormously useful for material participation, but it means partial dispositions do not release losses. Only disposing of the entire grouped activity does.",
"There is a specific rule that helps. Under Treasury Regulation Sec. 1.469-4(g), where a taxpayer disposes of substantially all of an activity, the taxpayer may treat that as a disposition of a separate activity if the amount of suspended loss allocable to the disposed portion can be established with reasonable certainty.",
"That relief requires records showing loss by property, which most taxpayers with an aggregation election do not maintain. Keeping a property-level suspended loss schedule costs nothing and preserves the option.",
]),
("Fully Taxable Excludes Several Common Exits", [
"A 1031 exchange is not a fully taxable disposition. Gain is deferred, and suspended losses stay suspended, carrying over to the replacement property. This surprises investors who expected the exchange to clear their accumulated losses.",
"An installment sale is a taxable disposition, but the losses are released proportionally as gain is recognized rather than all at once under IRC Sec. 469(g)(3).",
"A gift is not a taxable disposition. Under IRC Sec. 469(j)(6), suspended losses attributable to gifted property are added to the donee's basis rather than deducted by the donor. The donor loses them permanently.",
"A conversion to personal use is not a disposition at all. Suspended losses remain suspended, waiting for a future qualifying event.",
"A foreclosure or deed in lieu generally is a fully taxable disposition and does release the losses, which is one of the few favorable aspects of that outcome.",
]),
("Unrelated Party Matters", [
"Selling to a related party under IRC Sec. 267(b) or IRC Sec. 707(b) does not release the losses. They remain suspended until the property is disposed of to an unrelated party.",
"Selling a rental to your child, or between two entities you control, defers the release rather than triggering it. The losses survive and become available when the related party ultimately sells outside the group.",
"Investors restructuring their holdings should be aware that the reorganization does not clear the suspended balance.",
]),
("What Happens at Death", [
"Under IRC Sec. 469(g)(2), suspended losses of a decedent are allowed on the final return, but only to the extent they exceed the step-up in basis under IRC Sec. 1014.",
"In practice this eliminates most suspended losses. A property with $340,000 of suspended losses and a $600,000 step-up produces no deduction, because the step-up exceeds the losses.",
"This is a significant planning point for aging investors with large suspended loss balances. The losses are more valuable used during life than surrendered at death.",
"Options include disposing of one property in a fully taxable sale to release its losses, generating passive income to absorb them, or converting a rental to a short-term rental with material participation so that the activity's income becomes non-passive and can absorb suspended losses from the same activity.",
]),
("Worked Example: Portfolio Exit", [
"An investor owns six rentals with $780,000 of accumulated suspended passive losses. They made the aggregation election eight years ago and have maintained a property-level suspended loss schedule.",
"They sell two properties in a fully taxable sale to unrelated buyers, generating $410,000 of gain.",
"Because the aggregation election groups all six as one activity, this is not a disposition of the entire interest. However, the investor establishes with reasonable certainty that $268,000 of the suspended losses are allocable to the two properties sold, relying on their property-level records.",
"Under Treasury Regulation Sec. 1.469-4(g), the disposition of substantially all of that portion is treated as a disposition of a separate activity. The $268,000 is released and becomes non-passive.",
"That $268,000 offsets the $410,000 of gain and any other income. The remaining $512,000 of suspended losses stays with the four retained properties.",
"Had the investor not maintained property-level records, the entire $780,000 would have remained suspended until the last of the six properties was sold.",
]),
("Practical Guidance", [
"Maintain a suspended loss schedule by property, not just in aggregate. This costs nothing and preserves partial disposition relief.",
"Before executing a 1031 exchange, model whether recognizing gain and releasing suspended losses produces a better result than deferring. For an investor with large suspended losses and modest gain, a taxable sale can be nearly tax neutral while clearing the balance sheet.",
"Do not gift property with large suspended losses. The losses are added to the donee's basis and effectively lost as deductions.",
"For aging investors, model the death scenario explicitly. Losses that will be eliminated by a step-up are worth using during life.",
]),
],
"faqs": [
("Do I lose suspended passive losses if I never use them?",
 "They carry forward indefinitely under IRC Sec. 469(b) and are released when you dispose of your entire interest in the activity in a fully taxable transaction to an unrelated party. They are only truly lost at death to the extent the step-up in basis exceeds them, or if you gift the property."),
("Does a 1031 exchange release my suspended losses?",
 "No. An exchange is not a fully taxable disposition. Gain is deferred and the suspended losses carry over to the replacement property. Investors frequently expect an exchange to clear accumulated losses and it does not."),
("Can I release losses by selling just one property?",
 "Only if that property is its own activity, or if you can establish the allocable suspended loss with reasonable certainty under Treas. Reg. Sec. 1.469-4(g). If you made an aggregation election and keep only aggregate records, partial sales generally release nothing."),
("What happens to suspended losses if I gift the property?",
 "You lose them. Under IRC Sec. 469(j)(6), suspended losses attributable to gifted property are added to the donee's basis rather than deducted by you. This makes gifting loss-heavy property a poor choice relative to alternatives."),
("What happens to suspended losses at death?",
 "Under IRC Sec. 469(g)(2) they are allowed on the final return only to the extent they exceed the step-up in basis. Since step-ups are usually large, most suspended losses are eliminated. Aging investors with large balances should plan to use them during life."),
],
"related": [
("/blog/passive-activity-loss-rules-for-real-estate-investors/", "Passive activity loss rules"),
("/blog/grouping-elections-real-estate-irc-469/", "Grouping elections under IRC Sec. 469"),
("/blog/how-to-avoid-capital-gains-tax-when-selling-rental-property/", "Avoiding capital gains on a rental sale"),
],
"cta_head": "Know Your Suspended Balance by Property",
"cta_body": "Most investors know their total and nothing more, which forecloses partial disposition relief. Send us your prior returns and we will rebuild the schedule.",
},

{
"slug": "what-is-the-de-minimis-safe-harbor-election",
"title": "What Is the De Minimis Safe Harbor Election and Should You Make It?",
"meta_title": "De Minimis Safe Harbor Election Explained (2026) | AE Tax Advisors",
"meta_desc": "The de minimis safe harbor lets you expense items up to $2,500 per invoice instead of capitalizing. Requirements, the written policy, and common errors.",
"category": RE, "date": D,
"intro": [
"The de minimis safe harbor under Treasury Regulation Sec. 1.263(a)-1(f) lets a taxpayer expense tangible property costing up to $2,500 per invoice or per item rather than capitalizing and depreciating it.",
"It is one of the simplest and most reliably useful elections available to a rental owner or small business, and it is missed constantly. It also has a requirement that most taxpayers who claim it have never satisfied.",
],
"sections": [
("What the Election Does", [
"Absent the election, an appliance, a piece of furniture, a computer, or a tool with a useful life beyond one year must generally be capitalized and depreciated. Even where bonus depreciation eliminates the timing difference, the property must be tracked on a depreciation schedule for its recovery period.",
"With the election, amounts within the threshold are simply deducted as an ordinary expense in the year paid. No asset record, no depreciation schedule, no recapture tracking, and no partial disposition analysis later.",
"The threshold is $2,500 per invoice or per item as substantiated on the invoice, for taxpayers without an applicable financial statement. Taxpayers with an audited financial statement may use $5,000.",
"Most individual investors and small businesses do not have an applicable financial statement, which requires an audited financial statement or one filed with a federal agency. The $2,500 threshold is the relevant one.",
]),
("The Written Policy Requirement", [
"This is what most taxpayers miss. To use the safe harbor at the $2,500 level, you must have accounting procedures in place at the beginning of the tax year treating amounts below a specified threshold as expenses for non-tax purposes.",
"For a taxpayer without an applicable financial statement, the policy need not be written under the regulation, but the IRS has stated that having it in writing is strongly advisable, and a written policy dated before the start of the tax year is the practical standard for defending the position.",
"The policy is one paragraph. It states that the taxpayer will expense amounts paid for tangible property below a stated dollar threshold and items with an economic useful life of twelve months or less.",
"It must exist at the beginning of the year, not be created in March when the return is prepared. A policy dated the day before the year begins costs nothing and eliminates the issue permanently.",
]),
("How the Election Is Made", [
"The election is made annually by attaching a statement to a timely filed original return, including extensions. It is not made once and carried forward.",
"The statement identifies the taxpayer, states that the taxpayer is making the de minimis safe harbor election under Treasury Regulation Sec. 1.263(a)-1(f), and includes the taxpayer identification number.",
"An election missed for a year cannot be made late on an amended return. This is a real deadline with no relief mechanism, which is why the statement should be part of a standard filing checklist rather than a judgment call each year.",
]),
("What Counts Toward the Threshold", [
"The limit applies per invoice, or per item if the invoice substantiates per-item amounts. An invoice for eight $310 chairs totaling $2,480 qualifies at either level. An invoice for a single $3,100 refrigerator does not, and the entire amount must be capitalized. You cannot expense $2,500 of it.",
"Additional costs such as delivery and installation are included in the amount if they are on the same invoice. Splitting an invoice to get under the threshold is not permitted and is treated as one transaction.",
"The safe harbor does not apply to inventory, land, or amounts paid for property that must be capitalized under other rules such as UNICAP for producers.",
]),
("Interaction With the Other Safe Harbors", [
"Three safe harbors work together and are frequently confused.",
"The de minimis safe harbor covers amounts under the threshold per invoice, regardless of what the item is.",
"The routine maintenance safe harbor under Treasury Regulation Sec. 1.263(a)-3(i) covers recurring activities expected to be performed more than once during a ten-year period for buildings, or more than once during the property's class life for other property. Amount is irrelevant. A $19,000 HVAC servicing program that recurs qualifies.",
"The small taxpayer safe harbor under Treasury Regulation Sec. 1.263(a)-3(h) allows taxpayers with average annual gross receipts of $10,000,000 or less to expense improvements to a building with unadjusted basis of $1,000,000 or less, if total amounts for the year do not exceed the lesser of $10,000 or 2% of unadjusted basis. This is per building and is elected annually.",
"A rental owner should generally use all three. They cover different situations and none of them is exclusive of the others.",
]),
("Worked Example: Rental Turnover", [
"An investor turns over four units in a year, spending $34,600 across appliances, flooring, blinds, light fixtures, small tools, and furniture.",
"Reviewing the invoices, $19,400 consists of items or invoices under $2,500 each: individual appliances at $780 to $1,900, blinds packages at $410 per unit, light fixtures, and a tool purchase at $1,240.",
"With a written capitalization policy in place before the year began and the election statement attached to the return, that $19,400 is expensed currently. No depreciation schedule entries, no asset tracking, no future disposition analysis.",
"The remaining $15,200 consists of flooring replacements at $3,800 per unit. These exceed the threshold and are analyzed under the improvement rules. As restorations of a building system they are capitalized, though as five-year property in a cost segregation context they may be bonus eligible.",
"The election saved no tax relative to bonus depreciation in this case, since both produce a current deduction. What it saved is the bookkeeping: 47 asset records that never had to be created, tracked, or disposed of.",
]),
],
"faqs": [
("What is the de minimis safe harbor threshold?",
 "$2,500 per invoice or per item for taxpayers without an applicable financial statement, and $5,000 for those with an audited financial statement. Most individual investors and small businesses use the $2,500 threshold."),
("Do I need a written capitalization policy?",
 "For taxpayers without an applicable financial statement the regulation does not strictly require it in writing, but a written policy dated before the start of the tax year is the practical standard for defending the position. It is one paragraph and costs nothing."),
("How do I make the election?",
 "Attach a statement to a timely filed original return, including extensions, identifying yourself and stating that you are electing the de minimis safe harbor under Treas. Reg. Sec. 1.263(a)-1(f). It must be made annually and cannot be made late on an amended return."),
("Can I expense part of an item that exceeds the threshold?",
 "No. If a single item costs $3,100, the entire amount is capitalized. The safe harbor is all or nothing per invoice or item, and splitting an invoice to get under the threshold is not permitted."),
("Is this the same as the routine maintenance safe harbor?",
 "No, they are separate. The de minimis safe harbor is based on dollar amount per invoice. The routine maintenance safe harbor under Treas. Reg. Sec. 1.263(a)-3(i) is based on whether the activity recurs, with no dollar limit. Most rental owners should use both."),
],
"related": [
("/blog/what-repairs-vs-improvements-can-i-deduct-on-rental-property/", "Repairs versus improvements"),
("/blog/partial-asset-disposition-overlooked-tax-strategy/", "Partial asset dispositions"),
("/blog/what-deductions-are-most-commonly-missed-on-tax-returns/", "Commonly missed deductions"),
],
"cta_head": "Three Safe Harbors, All Elected Annually",
"cta_body": "Most rental returns we review are missing at least one of them. Send us your prior year return and we will tell you which elections you have been leaving on the table.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
