"""Batch: energy incentives, credits, and remaining property types."""

from blog_gen import write_all

CS = "Cost Segregation"
BO = "Business Owner Tax"
RE = "Real Estate Tax"
D = "2026-08-11"

ARTICLES = [
{
"slug": "section-179d-energy-efficient-commercial-building-deduction",
"title": "The Section 179D Deduction: Energy Efficiency Money Most Building Owners Never Claim",
"meta_title": "Section 179D Energy Efficient Building Deduction (2026) | AE Tax Advisors",
"meta_desc": "179D deducts up to $5 per square foot for efficient commercial buildings. Qualification, the prevailing wage bonus, and the designer allocation explained.",
"category": BO, "date": D,
"intro": [
"IRC Sec. 179D allows a deduction for energy efficient commercial building property, and the amounts are large enough to change the economics of a renovation. The Inflation Reduction Act expanded it substantially and made it permanent.",
"The base deduction is modest. The bonus rate, available when prevailing wage and apprenticeship requirements are met, reaches $5.00 per square foot indexed for inflation. On a 180,000 square foot building, that is up to $900,000.",
],
"sections": [
("What Qualifies", [
"The deduction applies to energy efficient commercial building property installed in a building located in the United States, within the scope of the applicable ASHRAE reference standard.",
"Qualifying systems are interior lighting, heating, cooling, ventilation and hot water, and the building envelope.",
"The property must be certified as part of a plan to reduce total annual energy and power costs with respect to those systems by at least 25% compared to a reference building meeting the applicable standard.",
"The deduction scales with the improvement. At a 25% reduction you receive the floor amount, and it increases on a sliding scale up to a 50% reduction where the maximum applies.",
"Commercial buildings and multifamily buildings of four or more stories both qualify. Residential rental property of three stories or fewer generally does not, which is where IRC Sec. 45L becomes the relevant provision instead.",
]),
("The Prevailing Wage and Apprenticeship Bonus", [
"This is the difference between a modest deduction and a large one. Without meeting the labor requirements, the deduction is roughly one fifth of the bonus amount.",
"To claim the bonus rate, laborers and mechanics employed by the taxpayer, contractors, and subcontractors on the installation must be paid prevailing wages as determined by the Department of Labor for the locality, and apprenticeship hour, ratio, and participation requirements must be satisfied.",
"The requirements apply during construction and, for prevailing wage, for the applicable alteration or repair period.",
"This has to be addressed in the construction contract before the work begins. Retroactively establishing prevailing wage compliance after a project is complete is difficult, and there are correction procedures with penalties that are far more expensive than compliance would have been.",
"For any renovation where 179D is contemplated, the labor requirements belong in the bid documents.",
]),
("Certification Requirements", [
"The energy savings must be certified by a qualified individual who is a licensed engineer or contractor in the jurisdiction where the building is located, and who is not related to the taxpayer.",
"Certification uses qualified computer software approved by the Department of Energy to model the building against the reference standard.",
"A site visit is required to verify that the property has been placed in service and meets the modeled specifications.",
"This is a specialist engagement. The certification is the substantiation, and a deduction claimed without it is not supportable.",
]),
("The Designer Allocation for Government and Tax Exempt Buildings", [
"This is the provision most people have heard of and the one most misunderstood.",
"Where a building is owned by a government entity, the owner cannot use a deduction because it pays no tax. IRC Sec. 179D(d)(3) permits the deduction to be allocated to the person primarily responsible for designing the property, typically the architect, engineer, or design-build contractor.",
"The Inflation Reduction Act extended this allocation to buildings owned by other tax exempt entities, including nonprofits, tribal governments, and certain religious and educational organizations, which substantially expanded the pool.",
"For an architecture or engineering firm doing public sector work, this is a recurring deduction stream with no capital outlay. A firm designing four school buildings totaling 300,000 square feet may be allocated a seven-figure deduction across those projects.",
"The allocation requires a written letter from an authorized representative of the owner. Firms should request the allocation letter as part of project closeout, because obtaining it years later from a school district or municipality is considerably harder.",
]),
("Interaction With Cost Segregation", [
"The 179D deduction reduces the basis of the qualifying property. It does not stack on top of depreciation; it accelerates it.",
"That means a building owner running both a cost segregation study and a 179D claim must coordinate them so the same basis is not deducted twice. The study should be prepared with knowledge of the 179D amount and the affected systems.",
"The two are complementary rather than duplicative. 179D reaches building envelope and HVAC components that a cost segregation study leaves in the 39-year structure, while the study accelerates the personal property and land improvements that 179D does not address.",
"Running them together on a renovation is frequently the strongest available combination, and running them separately without coordination creates a basis error.",
]),
("Claiming It on a Prior Year", [
"179D is a deduction, not a credit, and a missed deduction is generally a method issue rather than an amended return issue where the property has been depreciated for two or more years.",
"A change to claim a previously unclaimed 179D deduction can often be made through a change in accounting method on Form 3115, capturing the amount as a Sec. 481(a) adjustment in the current year.",
"For designers claiming allocated deductions, the analysis differs because there is no depreciable basis, and amended returns within the statute of limitations under IRC Sec. 6511 are typically the route.",
]),
("Worked Example: Office Renovation", [
"An owner renovates a 145,000 square foot office building, replacing HVAC, lighting, and portions of the envelope for $9,400,000. The construction contract includes prevailing wage and apprenticeship requirements from the outset.",
"Energy modeling by a licensed engineer certifies a 41% reduction in total annual energy and power costs against the reference standard, placing the deduction on the sliding scale above the floor.",
"At approximately $4.10 per square foot at that savings level, the 179D deduction is roughly $594,500.",
"Separately, a cost segregation study on the renovation identifies qualified improvement property under IRC Sec. 168(e)(6) and five-year personal property, coordinated so that basis claimed under 179D is excluded from the accelerated categories.",
"The combined first-year deduction substantially exceeds what either provision would have produced alone, and the prevailing wage decision made at the bid stage accounts for roughly $475,000 of it.",
]),
],
"faqs": [
("How much is the Section 179D deduction worth?",
 "Up to $5.00 per square foot indexed for inflation when prevailing wage and apprenticeship requirements are met, on a sliding scale beginning at a 25% energy cost reduction and reaching the maximum at 50%. Without meeting the labor requirements it is roughly one fifth of that."),
("What buildings qualify?",
 "Commercial buildings and multifamily buildings of four or more stories, located in the United States and within the scope of the applicable ASHRAE reference standard. Residential rental of three stories or fewer generally looks to IRC Sec. 45L instead."),
("Can an architect claim 179D on a government building?",
 "Yes. Under IRC Sec. 179D(d)(3), where the owner is a government entity or, after the Inflation Reduction Act, another tax exempt entity, the deduction may be allocated to the designer. It requires a written allocation letter from an authorized representative of the owner."),
("Does 179D stack with cost segregation?",
 "They are complementary but must be coordinated. The 179D deduction reduces the basis of the qualifying property, so the same basis cannot also be accelerated in a study. 179D reaches envelope and HVAC that a study leaves in the structure."),
("Can I claim 179D for a prior year?",
 "Often yes. Where the property has been depreciated for two or more years, a change to claim a previously unclaimed deduction can generally be made on Form 3115 as a Sec. 481(a) adjustment in the current year, without amending prior returns."),
],
"related": [
("/blog/cost-segregation-office-buildings/", "Cost segregation for office buildings"),
("/blog/section-45l-new-energy-efficient-home-credit/", "The Section 45L credit for residential builders"),
("/blog/form-3115-cost-segregation-catch-up/", "Form 3115 catch-up deductions"),
],
"cta_head": "The Labor Decision Happens at the Bid Stage",
"cta_body": "Prevailing wage compliance is worth roughly five times the deduction and cannot be added later. Bring us your renovation plans before the contract is signed.",
},

{
"slug": "section-45l-new-energy-efficient-home-credit",
"title": "The Section 45L Credit: $2,500 to $5,000 Per Unit for Residential Builders",
"meta_title": "Section 45L New Energy Efficient Home Credit (2026) | AE Tax Advisors",
"meta_desc": "45L pays up to $5,000 per dwelling unit for qualifying homes and low-rise multifamily. Certification, prevailing wage, and basis reduction rules for 2026.",
"category": BO, "date": D,
"intro": [
"IRC Sec. 45L provides a credit for each qualifying new energy efficient dwelling unit acquired from an eligible contractor. The Inflation Reduction Act restructured it around ENERGY STAR and Zero Energy Ready Home certification and raised the amounts substantially.",
"For a multifamily developer completing a 220-unit community, the credit can exceed $1,000,000. It is a credit rather than a deduction, so it reduces tax dollar for dollar.",
],
"sections": [
("The Credit Amounts", [
"For single family homes, the credit is $2,500 for a unit certified to the applicable ENERGY STAR program requirements, and $5,000 for a unit certified as a Zero Energy Ready Home under the Department of Energy program.",
"For multifamily dwelling units, the base credit is $500 for ENERGY STAR certification and $1,000 for Zero Energy Ready Home certification.",
"Multifamily units that also satisfy prevailing wage requirements receive $2,500 and $5,000 respectively, matching the single family amounts.",
"That prevailing wage multiplier is a five times increase and is the single most consequential decision on a multifamily project contemplating this credit.",
"Manufactured homes have their own applicable ENERGY STAR requirements and qualify at the corresponding amounts.",
]),
("Who Can Claim It", [
"The credit goes to the eligible contractor, defined as the person who constructed the qualified new energy efficient home, or in the case of a manufactured home, the manufacturer.",
"For a developer who builds and sells, that is the developer. For a developer who builds and holds as rental property, the developer is still the eligible contractor and claims the credit, because the statute requires acquisition by a person for use as a residence, and the regulations and guidance treat a rental unit leased to a tenant as satisfying that.",
"A person who merely finances construction is not an eligible contractor. Ownership of the property during construction is the operative fact.",
"The unit must be acquired by a person for use as a residence during the taxable year. For rental property, that means the unit must be leased.",
]),
("Prevailing Wage on Multifamily", [
"The multiplier requires that laborers and mechanics employed by the taxpayer, contractors, and subcontractors in the construction of the qualified home be paid prevailing wages as determined by the Department of Labor for the locality and type of construction.",
"Unlike Sec. 179D, the 45L multiplier requires prevailing wage but not the apprenticeship requirements.",
"This has to be in the contract from the beginning. On a 220-unit project, the difference between $1,000 and $5,000 per unit is $880,000, which typically far exceeds the incremental labor cost.",
"Documentation requirements are substantial: certified payroll records, wage determinations, and evidence of compliance across all contractors and subcontractors. This is a compliance program, not a checkbox, and it should be administered by someone who has done it before.",
]),
("Certification", [
"Certification must be obtained from an eligible certifier who is not related to the eligible contractor, using approved procedures under the applicable ENERGY STAR or Zero Energy Ready Home program.",
"The certifier must be accredited under the applicable program. For ENERGY STAR that generally means a certified HERS rater working within an accredited rating provider network.",
"Certification is per unit and requires inspection and testing during construction, including blower door and duct leakage testing. It cannot be performed retroactively on a completed and occupied unit in most cases.",
"That timing constraint is why 45L must be planned before construction rather than discovered afterward. A developer who completes a project without engaging a rater has generally lost the credit.",
]),
("Basis Reduction and Interaction With Depreciation", [
"Under IRC Sec. 45L(e), the basis of the property is reduced by the amount of the credit allowed.",
"For a developer holding the units as rental property, that reduces depreciable basis and therefore reduces future depreciation, including the amounts identified in a cost segregation study.",
"The credit is still substantially better than the depreciation forgone, since a credit reduces tax dollar for dollar while a deduction reduces it at the marginal rate. A $5,000 credit is worth $5,000, while $5,000 of additional basis is worth roughly $1,850 at a 37% rate spread across 27.5 years.",
"For a developer who builds and sells, the basis reduction affects gain on sale rather than depreciation.",
"The credit is a general business credit under IRC Sec. 38, subject to the general business credit limitations, with carryback and carryforward available for unused amounts.",
]),
("Prior Year Claims", [
"Unlike a deduction, a missed credit is not corrected through a change in accounting method. It requires an amended return within the statute of limitations under IRC Sec. 6511, generally three years from filing.",
"Developers who completed qualifying projects in recent years and never claimed the credit should evaluate amended returns promptly, because the window closes on a rolling basis.",
"The practical obstacle is certification. Where units were never certified during construction, the credit is generally unavailable regardless of how efficient the building actually is.",
]),
("Worked Example: 220-Unit Community", [
"A developer builds a 220-unit garden style apartment community and engages a HERS rater at the design stage. All units are certified to the applicable ENERGY STAR multifamily requirements.",
"The construction contracts include prevailing wage requirements with certified payroll administration across all trades.",
"With prevailing wage satisfied, the credit is $2,500 per unit, for a total of $550,000. Without it, the credit would have been $500 per unit, or $110,000.",
"Fifty units are additionally certified as Zero Energy Ready Homes at $5,000 each, replacing the $2,500 amount for those units and adding $125,000.",
"Total credit is $675,000, reducing tax dollar for dollar.",
"Basis is reduced by $675,000, which reduces the cost segregation study result correspondingly. On a $46,000,000 project the depreciation forgone is worth roughly $250,000 spread over the schedule, against a $675,000 immediate credit. The credit wins decisively.",
]),
],
"faqs": [
("How much is the 45L credit per unit?",
 "For single family, $2,500 for ENERGY STAR certification and $5,000 for Zero Energy Ready Home. For multifamily, $500 and $1,000 respectively, rising to $2,500 and $5,000 when prevailing wage requirements are met."),
("Can I claim 45L on rental units I keep?",
 "Yes. The eligible contractor is the person who constructed the home, and a developer who builds and holds still qualifies. The unit must be acquired by a person for use as a residence during the year, which for rental property means it must be leased."),
("Does 45L require apprenticeship compliance?",
 "No. Unlike Sec. 179D, the 45L multiplier for multifamily requires prevailing wage but not the apprenticeship hour, ratio, and participation requirements. Certified payroll documentation across all contractors and subcontractors is still substantial."),
("Can I certify units after construction is finished?",
 "Generally no. Certification requires inspection and testing during construction, including blower door and duct leakage testing. A developer who completes a project without engaging an accredited rater has usually lost the credit regardless of actual efficiency."),
("Does the credit reduce my depreciation?",
 "Yes. Under IRC Sec. 45L(e), basis is reduced by the credit allowed, which reduces future depreciation including cost segregation results. The credit is still far better, since it reduces tax dollar for dollar while the forgone deduction is worth only the marginal rate."),
],
"related": [
("/blog/section-179d-energy-efficient-commercial-building-deduction/", "The Section 179D deduction"),
("/blog/cost-segregation-large-multifamily-100-plus-units/", "Cost segregation for large multifamily"),
("/blog/cost-segregation-new-construction-vs-existing/", "New construction versus existing property studies"),
],
"cta_head": "Engage the Rater Before You Break Ground",
"cta_body": "Certification cannot be done retroactively and prevailing wage is a five times multiplier. Bring us the project before the contracts are signed.",
},

{
"slug": "rd-tax-credit-section-41-guide",
"title": "The R&D Tax Credit Under Section 41: Who Actually Qualifies",
"meta_title": "R&D Tax Credit Section 41 Guide (2026) | AE Tax Advisors",
"meta_desc": "The research credit reaches far beyond laboratories. The four-part test, the funded research exclusion, payroll offset, and documentation requirements.",
"category": BO, "date": D,
"intro": [
"The credit for increasing research activities under IRC Sec. 41 is claimed by a fraction of the businesses eligible for it, largely because owners assume research means laboratories and white coats.",
"The statutory test is technological uncertainty resolved through experimentation. Engineering firms, manufacturers, software developers, food producers, and construction firms doing genuine design work all routinely qualify.",
],
"sections": [
("The Four-Part Test", [
"Qualified research must satisfy four requirements under IRC Sec. 41(d).",
"Permitted purpose. The activity must be intended to develop or improve the functionality, performance, reliability, or quality of a business component, meaning a product, process, technique, formula, invention, or software. Improving an existing process counts. Improving aesthetics or style does not.",
"Technological in nature. The activity must fundamentally rely on principles of physical or biological science, engineering, or computer science. Social sciences, economics, and market research are excluded.",
"Elimination of uncertainty. At the outset, there must be uncertainty about the capability or method of developing the component, or the appropriate design. If the outcome was known, there was no research.",
"Process of experimentation. Substantially all of the activities must constitute a process of evaluating alternatives through modeling, simulation, systematic trial and error, or other methods. This is the requirement most often failed on documentation rather than on substance.",
]),
("What Costs Count", [
"Qualified research expenses fall into three categories.",
"Wages for employees performing qualified services: those directly engaged in research, and those directly supervising or directly supporting it. For an employee whose time is substantially all qualified research, the entire wage may be included.",
"Supplies used and consumed in the conduct of qualified research. This excludes land, improvements to land, and property subject to depreciation. Prototype materials generally qualify.",
"Contract research, at 65% of amounts paid to a third party for qualified research performed on the taxpayer's behalf, rising to 75% for payments to qualified research consortia.",
"Rent, overhead, general administrative costs, and capital equipment do not qualify.",
]),
("The Funded Research Exclusion Is the Main Obstacle", [
"Under IRC Sec. 41(d)(4)(H), research is excluded to the extent it is funded by a grant, contract, or otherwise by another person.",
"Regulations under Treasury Regulation Sec. 1.41-4A(d) provide the two-part analysis. Research is funded if payment is not contingent on the success of the research, meaning the taxpayer bears no economic risk. Research is also funded if the taxpayer does not retain substantial rights in the results.",
"For a firm doing client work, this makes contract terms decisive. A fixed-price contract where the firm absorbs cost overruns bears economic risk and generally supports the credit. A cost-plus or time-and-materials contract where the client pays regardless of outcome generally does not.",
"Rights language matters equally. A contract assigning all intellectual property to the client with no retained right to use the knowledge developed weakens the substantial rights position. Retaining a non-exclusive right to use the technology, even without exclusivity, generally suffices.",
"Firms doing genuine development work should review their standard agreements with this in mind, because two contracts for identical work can produce entirely different credit outcomes.",
]),
("The Payroll Tax Offset for Small Businesses", [
"A qualified small business may elect to apply a portion of the research credit against the employer portion of social security tax, rather than against income tax.",
"This matters enormously for startups with no income tax liability. A company with $2,000,000 of qualified research expenses and no taxable income can still monetize the credit against payroll tax.",
"A qualified small business generally means a business with gross receipts under $5,000,000 for the taxable year and no gross receipts for any year before the five-year period ending with the current year. The Inflation Reduction Act increased the maximum electable amount.",
"The election is made on a timely filed return including extensions, and cannot be made on an amended return. This is a hard deadline that startups miss regularly.",
]),
("Section 174 Interaction", [
"Research expenditures are also governed by IRC Sec. 174, which the 2017 law required to be capitalized and amortized over five years for domestic activity beginning in 2022.",
"Legislation enacted in 2025 restored current deductibility for domestic research expenditures, with transition rules addressing amounts previously capitalized in 2022 through 2024. Foreign research remains subject to longer amortization.",
"IRC Sec. 280C requires a reduction in the Sec. 174 amount by the credit claimed, unless the taxpayer elects a reduced credit. The reduced credit election is often preferable and should be modeled rather than defaulted.",
"The definitions differ between the two sections. Sec. 174 is broader than Sec. 41, so expenses can be Sec. 174 expenditures without being qualified research expenses for the credit.",
]),
("Documentation Decides the Outcome", [
"The IRS requires specific information for research credit refund claims, including identification of business components, the research activities performed, the individuals who performed them, and the information each sought to discover.",
"Contemporaneous documentation is far more valuable than reconstruction. Project records, design iterations, test results, failure analyses, engineering change orders, and time tracking by project all support the claim.",
"The most common failure is time allocation. A firm that can identify qualified projects but cannot substantiate which employees spent how much time on them will see the wage component reduced substantially.",
"Implementing project-level time tracking prospectively costs little and roughly doubles the defensible credit for most firms.",
]),
("Worked Example: Manufacturing Firm", [
"A manufacturer with $18,000,000 of revenue develops custom tooling and production processes for client applications, working primarily under fixed-price contracts where it bears overrun risk and retains the right to use the process knowledge developed.",
"A credit study identifies qualified research expenses of $2,340,000: $1,820,000 of engineering and technical wages, $310,000 of prototype supplies, and $210,000 of contract research at the 65% inclusion rate.",
"Under the alternative simplified credit method, the credit is approximately $164,000 for the year.",
"The firm elects the reduced credit under IRC Sec. 280C to avoid reducing its Sec. 174 amount, which nets to a better result given its marginal rate.",
"Three prior open years are also claimed on amended returns, adding approximately $410,000.",
"The firm implements project-level time tracking going forward, which the study estimates will increase the substantiated wage base by roughly 30% in subsequent years.",
]),
],
"faqs": [
("Do I need a laboratory to claim the R&D credit?",
 "No. The test under IRC Sec. 41(d) is technological uncertainty resolved through a process of experimentation. Engineering firms, manufacturers, software developers, food producers, and construction firms doing genuine design work routinely qualify."),
("Why does my client contract affect the credit?",
 "Under the funded research exclusion in IRC Sec. 41(d)(4)(H), research funded by another person is excluded. A fixed-price contract where you bear overrun risk generally supports the credit; a cost-plus contract generally does not. Retained rights to the results matter equally."),
("Can a startup with no taxable income use the credit?",
 "Yes, through the payroll tax offset election, which applies the credit against the employer portion of social security tax. It requires qualifying as a small business and must be elected on a timely filed return including extensions. It cannot be made on an amended return."),
("What costs qualify?",
 "Wages for employees directly engaged in, supervising, or supporting qualified research; supplies used and consumed in the research; and 65% of contract research payments. Rent, overhead, general administrative costs, and capital equipment do not qualify."),
("What documentation do I need?",
 "Identification of business components, the activities performed, who performed them, and what each sought to discover, supported by project records, design iterations, test results, and time tracking by project. Time allocation is the most common weak point."),
],
"related": [
("/blog/tax-strategy-for-engineering-and-architecture-firms/", "Tax strategy for engineering and architecture firms"),
("/blog/tax-strategy-for-saas-founders/", "Tax strategy for SaaS founders"),
("/blog/qualified-small-business-stock-section-1202/", "Qualified small business stock"),
],
"cta_head": "Start With Your Contracts",
"cta_body": "Two firms doing identical work can get opposite credit results based on contract terms alone. Bring us a sample agreement and a project list.",
},

{
"slug": "cost-segregation-cannabis-cultivation-facilities",
"title": "Cost Segregation for Cannabis Facilities: Why 280E Changes the Whole Analysis",
"meta_title": "Cost Segregation for Cannabis Cultivation Facilities (2026) | AE Tax Advisors",
"meta_desc": "IRC Sec. 280E disallows most deductions for cannabis operators, but cost of goods sold survives. How depreciation is captured through COGS under Sec. 471.",
"category": CS, "date": D,
"intro": [
"Cannabis facilities are equipment dense and reclassify heavily, commonly 45% to 60% of depreciable basis. Lighting, HVAC and dehumidification, fertigation, extraction, and environmental controls dominate the build.",
"But for a plant-touching operator, the ordinary cost segregation analysis does not apply, because IRC Sec. 280E disallows deductions and credits for a trade or business trafficking in controlled substances. Depreciation is a deduction. The question is whether it can reach the return another way.",
],
"sections": [
("What 280E Actually Disallows", [
"IRC Sec. 280E denies any deduction or credit for amounts paid or incurred in carrying on a trade or business consisting of trafficking in controlled substances within Schedule I or II of the Controlled Substances Act.",
"Marijuana remains a Schedule I substance under federal law regardless of state legalization, and courts have consistently applied 280E to state-licensed operators.",
"What 280E does not reach is cost of goods sold. Gross income for a business selling goods is receipts less cost of goods sold, and 280E operates on deductions from gross income rather than on the computation of gross income itself. Reducing gross income by COGS is constitutionally required and is not a deduction.",
"That distinction is the entire tax planning universe for a plant-touching cannabis business.",
]),
("Depreciation Through Cost of Goods Sold", [
"For a producer, depreciation on assets used directly in production can be included in inventoriable costs under the rules of IRC Sec. 471 and the associated regulations, flowing into cost of goods sold as inventory is sold.",
"That means depreciation on cultivation equipment, grow room build-out, environmental systems, and the production portion of the facility may reach the return through COGS even though it could not be claimed as a deduction.",
"Depreciation on non-production assets, retail dispensary build-out, office space, and administrative equipment, is a deduction disallowed by 280E and does not reach the return at all.",
"The allocation between production and non-production is therefore the central issue, and it is exactly what a component-level cost segregation study produces.",
"The Tax Court's decision in Patients Mutual Assistance Collective Corp. v. Commissioner constrains how far a reseller can push inventoriable costs, and the analysis differs meaningfully between a producer and a retailer. Producers have substantially more room.",
]),
("Why Acceleration Still Matters", [
"Under an inventory approach, depreciation included in inventoriable costs is recovered as inventory is sold rather than in the year incurred. For a cultivator with high turnover, that lag is short.",
"Accelerating depreciation through a cost segregation study increases the amount flowing into inventoriable costs in the early years, which increases COGS and reduces taxable income sooner.",
"Whether bonus depreciation under IRC Sec. 168(k) is included in inventoriable costs requires care. The interaction between accelerated tax depreciation and the inventory capitalization rules is not intuitive, and the position taken should be documented and consistent.",
"For a plant-touching operator, this is the difference between a study that reduces tax and a study that produces a number with nowhere to go.",
]),
("What Reclassifies in a Cultivation Facility", [
"Lighting systems including fixtures, ballasts, controls, and light movers are five-year property. On a large cultivation facility this alone is substantial.",
"HVAC and dehumidification serving grow rooms is process equipment rather than building comfort systems. Under the functional analysis reflected in Treasury Regulation Sec. 1.48-1(e)(2), systems serving the production environment classify with that function. The dedicated electrical service, switchgear, and distribution feeding them follow.",
"Fertigation and irrigation systems, reservoirs, dosing equipment, reverse osmosis and water treatment, and the distribution piping serving grow rooms are equipment.",
"Environmental controls, CO2 supplementation, sensors, and automation systems are five-year property.",
"Benching, racking, vertical grow systems, and rolling tables are equipment.",
"Extraction equipment, its dedicated ventilation, and the C1D1 rated enclosures housing it are equipment.",
"Security systems, required at a level far exceeding ordinary commercial buildings by state regulation, are five-year property along with their cabling.",
"Sealed room construction, vapor barriers, and specialty wall and ceiling systems in grow rooms are a closer question and should be analyzed rather than assumed either way.",
]),
("Real Estate Ownership Is a Common Structure", [
"Many cannabis operators separate the real estate into a non-plant-touching entity that leases to the licensed operator.",
"The property entity is not trafficking in controlled substances, so 280E does not apply to it. It deducts depreciation, interest, and operating costs normally, and a cost segregation study on the building produces an ordinary deduction.",
"The rent it receives is income, and the operator's rent expense is subject to 280E unless it can be included in inventoriable costs, which for production space it often can be.",
"This structure is common and is not itself aggressive, but it must be genuine: separate ownership, arm's length rent supported by market data, and real substance. Rent set to strip income from the operating entity invites adjustment under IRC Sec. 482.",
"Self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) also apply where ownership overlaps, and the passive activity treatment of the property entity's loss should be resolved before the study.",
]),
("Worked Example: Cultivation Facility", [
"An operator builds a 42,000 square foot indoor cultivation facility for $14,600,000 including land. Land is $1,400,000, leaving $13,200,000 depreciable.",
"A study identifies five-year property of $6,732,000 (51%), covering lighting, grow room HVAC and dehumidification with dedicated electrical, fertigation, environmental controls, benching, extraction, and security. Fifteen-year land improvements are $792,000 (6%). Structure is $5,676,000 (43%).",
"The study further allocates each component between production and non-production space, identifying 87% of the reclassified basis as directly attributable to production.",
"That production portion is included in inventoriable costs under IRC Sec. 471 and reaches the return through cost of goods sold as inventory is sold. The 13% attributable to office and administrative space is a deduction disallowed under 280E.",
"Without the component-level allocation, the operator would have had no defensible basis for including any specific amount in inventoriable costs, and the entire deduction would have been at risk.",
]),
],
"faqs": [
("Can a cannabis business claim depreciation?",
 "Not as a deduction. IRC Sec. 280E disallows deductions for a business trafficking in controlled substances. But depreciation on assets used directly in production can be included in inventoriable costs under IRC Sec. 471 and reach the return through cost of goods sold, which 280E does not reach."),
("Is cost segregation worthwhile for a cannabis operator?",
 "Yes, but for a different reason than for other businesses. The component-level allocation between production and non-production assets is what makes the inventoriable cost position defensible. Without it, there is no supportable basis for the amounts included in COGS."),
("What percentage does a cultivation facility reclassify?",
 "Commonly 45% to 60% of depreciable basis. Lighting, grow room HVAC and dehumidification with dedicated electrical, fertigation, environmental controls, benching, extraction, and regulatory-driven security systems all qualify as equipment."),
("Does 280E apply to a separate real estate entity?",
 "Generally no, because the property entity is not trafficking in controlled substances. It deducts depreciation and expenses normally. The structure must be genuine, with arm's length rent supported by market data, or it invites adjustment under IRC Sec. 482."),
("Do dispensaries get the same treatment as cultivators?",
 "No. The room to include costs in inventory is substantially narrower for a reseller than for a producer, as the Tax Court addressed in Patients Mutual. Retail build-out depreciation is generally a disallowed deduction rather than an inventoriable cost."),
],
"related": [
("/blog/cost-segregation-manufacturing-facilities/", "Cost segregation for manufacturing facilities"),
("/blog/self-rental-rules-business-rents-from-you/", "Self-rental rules explained"),
("/blog/cost-segregation-warehouse-industrial-buildings/", "Cost segregation for industrial buildings"),
],
"cta_head": "The Allocation Is the Deliverable",
"cta_body": "For a plant-touching operator the study's value is the production versus non-production split, not the headline percentage. Send us your facility plans and license structure.",
},

{
"slug": "cost-segregation-golf-courses-country-clubs",
"title": "Cost Segregation for Golf Courses and Country Clubs: Land Improvements Everywhere",
"meta_title": "Cost Segregation for Golf Courses and Country Clubs (2026) | AE Tax Advisors",
"meta_desc": "Golf properties reclassify 40 to 60 percent because nearly everything outside the clubhouse is a land improvement. Greens, irrigation, and cart paths explained.",
"category": CS, "date": D,
"intro": [
"Golf properties reclassify at the top of the range, commonly 40% to 60% of depreciable basis, because the asset is almost entirely site work. The clubhouse is a small fraction of the capital.",
"The complication is that some of what looks like site work is inseparable from land and is not depreciable at all. Getting that line right is the whole exercise.",
],
"sections": [
("What Is and Is Not Depreciable", [
"Land is never depreciable. General grading, clearing, and earthmoving that permanently changes the contour of the land is generally treated as inseparable from the land and added to non-depreciable land basis.",
"The distinction courts and the IRS have drawn turns on whether the improvement has a determinable useful life and would be replaced or would deteriorate. General land shaping does not. Constructed features with finite lives do.",
"Modern greens are the clearest example. A USGA specification green is a constructed drainage and rootzone system with gravel layers, drain tile, and engineered sand profiles, built to be rebuilt on a cycle. Those constructed components have been treated as depreciable land improvements.",
"Tees and bunkers follow similar analysis where they are constructed with drainage and engineered materials rather than merely shaped.",
"Fairway rough grading generally is not depreciable. Fairway drainage systems installed within it generally are.",
]),
("The Large Depreciable Categories", [
"Irrigation is usually the single largest item. Mainlines, laterals, heads, valves, controllers, satellite boxes, and the pump station and its wet well and controls are 15-year land improvements or five-year equipment depending on the component. Pump station equipment is generally five-year property.",
"Cart paths, curbing, and bridges are 15-year land improvements.",
"Drainage systems throughout the course, including catch basins, tile, and outfalls, are 15-year property.",
"Ponds and water features that are constructed with liners, structures, and pumping are depreciable to the extent of the constructed components. Natural water bodies are not.",
"Site lighting, fencing, netting and its supports, retaining walls, and signage foundations are 15-year property.",
"Landscaping and ornamental plantings adjacent to depreciable structures, where they would be destroyed if the structure were replaced, are depreciable land improvements. General course plantings are typically not.",
]),
("Equipment and Clubhouse", [
"Maintenance equipment, mowers, sprayers, utility vehicles, and the golf cart fleet are five-year property, though carts are frequently leased rather than owned.",
"Course furnishings, ball washers, tee markers, benches, and signage are five-year property.",
"The clubhouse reclassifies like any hospitality property. Kitchen equipment, walk-ins, bar equipment, point of sale, audiovisual and sound systems, decorative and accent lighting, millwork and casework, carpet and resilient flooring, window treatments, locker room fixtures, and pro shop display fixtures are five-year property.",
"Pool complexes, tennis and pickleball courts, and practice facilities are 15-year land improvements along with their fencing and lighting, while the pumps, filtration, and heating equipment are five-year property.",
]),
("Worked Example: 18-Hole Private Club", [
"An investor acquires an 18-hole private club with clubhouse, pool, and tennis facilities for $16,800,000. An engineering-based land allocation values the raw acreage at $3,200,000, leaving $13,600,000 depreciable.",
"The study identifies five-year property of $2,584,000 (19%), covering pump station equipment, maintenance and course equipment, clubhouse kitchen and bar, audiovisual, finishes, and pool mechanical. Seven-year property is $272,000 (2%). Fifteen-year land improvements are $5,984,000 (44%), covering irrigation distribution, cart paths, drainage, constructed greens and tee components, bunker drainage, courts, pool deck, fencing, and site lighting. Structure is $4,760,000 (35%), primarily the clubhouse and maintenance buildings.",
"Reclassified basis of $8,840,000 is deductible in year one under IRC Sec. 168(k), plus $122,051 of structural depreciation, for approximately $8,962,051 against $460,000 on a blended straight-line approach.",
]),
("The Land Allocation Is the Highest Leverage Decision", [
"Because land is not depreciable and nearly everything else is 15-year property, the land versus improvement split drives the result more than on almost any other asset class.",
"The correct approach values the land as if unimproved, based on comparable raw acreage in the market and its highest and best use absent the course, and treats the remainder as improvements.",
"A lender appraisal that assigns 40% of value to land because the property sits on 180 acres is not an allocation grounded in raw land comparables. In a market where developable raw ground trades at $18,000 per acre, 180 acres is $3,240,000, not $6,700,000.",
"This is a valuation exercise requiring support, and it belongs in the study workpapers with the comparables documented.",
]),
("Operating Business Versus Rental", [
"An owner-operated club is a trade or business, so the analysis under IRC Sec. 469 turns solely on material participation under Treasury Regulation Sec. 1.469-5T. An owner-operator clears the 500-hour test readily, making the deduction non-passive and available against other active income.",
"Where the course is leased to a management company or operator, the owner is a landlord and the ordinary passive rules apply.",
"Member-owned clubs organized as tax exempt social clubs under IRC Sec. 501(c)(7) present an entirely different analysis, since depreciation has limited value against exempt function income and the unrelated business income rules govern non-member revenue. A study on a member-owned club should be evaluated against the actual tax profile rather than assumed to be valuable.",
]),
],
"faqs": [
("Are golf greens depreciable?",
 "Constructed greens generally are. A USGA specification green is a built drainage and rootzone system with gravel layers, drain tile, and engineered sand, designed to be rebuilt on a cycle, which supports treatment as a land improvement with a determinable life. General land shaping is not depreciable."),
("What is the largest depreciable component on a golf course?",
 "Usually irrigation. Mainlines, laterals, heads, valves, controllers, and the pump station together are substantial, with the distribution as 15-year land improvements and the pump station equipment as five-year property."),
("Why does the land allocation matter so much?",
 "Because land is not depreciable and nearly everything else on a golf property is 15-year property. Valuing the land as raw unimproved acreage against local comparables, rather than accepting a lender appraisal split, is the highest leverage decision in the study."),
("Is landscaping depreciable?",
 "Ornamental plantings immediately adjacent to depreciable structures, which would be destroyed if the structure were replaced, are depreciable land improvements. General course plantings and turf are typically treated as inseparable from the land."),
("Does a study help a member-owned club?",
 "Often not much. A club exempt under IRC Sec. 501(c)(7) has limited use for depreciation against exempt function income, and the analysis turns on unrelated business income from non-member revenue. Evaluate against the actual tax profile before commissioning a study."),
],
"related": [
("/blog/cost-segregation-rv-parks-campgrounds/", "Cost segregation for RV parks and campgrounds"),
("/blog/cost-segregation-hotels-hospitality-properties/", "Cost segregation for hotels"),
("/blog/cost-segregation-mobile-home-parks/", "Cost segregation for mobile home parks"),
],
"cta_head": "The Land Line Decides the Result",
"cta_body": "On a golf property, the raw land valuation moves the answer more than anything else in the study. Send us the acreage, the appraisal, and the closing detail.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
