"""Batch: additional question-target and business owner guides."""

from blog_gen import write_all

BO = "Business Owner Tax"
CS = "Cost Segregation"
RE = "Real Estate Tax"
D = "2026-08-11"

ARTICLES = [
{
"slug": "pass-through-entity-tax-election-salt-cap-workaround",
"title": "The Pass-Through Entity Tax Election: A Real Workaround to the SALT Cap",
"meta_title": "Pass-Through Entity Tax Election and the SALT Cap (2026) | AE Tax Advisors",
"meta_desc": "The PTET election moves state tax to the entity level, bypassing the SALT cap. How it works, which states offer it, and when it backfires in 2026.",
"category": BO, "date": D,
"intro": [
"The state and local tax deduction cap under IRC Sec. 164(b)(6) limits an individual's deduction for state income and property taxes. For a business owner paying $90,000 of state income tax, most of that deduction is lost.",
"The pass-through entity tax election is the workaround, and unlike most workarounds it has explicit IRS blessing. Notice 2020-75 confirmed that state income taxes paid by a partnership or S corporation are deductible by the entity in computing non-separately stated income, and are not subject to the individual cap.",
"More than thirty states have enacted some version of it. The savings are real, and so are the traps.",
],
"sections": [
("How It Works", [
"The state enacts an elective entity-level income tax on pass-through entities. The entity pays state tax on its income, deducts that payment as a business expense, and passes through reduced income to owners.",
"Owners then receive either a credit against their state tax liability or an exclusion of the income from their state return, depending on the state's design.",
"The result is that the state tax is paid with pre-federal-tax dollars. A partner allocated $900,000 of income in a state with a 6% rate sees the entity pay $54,000 of state tax, reducing the federal K-1 income to $846,000. That $54,000 is fully deductible federally rather than being capped.",
"At a 37% federal rate, the federal benefit is approximately $20,000 on that one owner. Across a four-partner firm, it can approach $80,000 annually.",
]),
("Which Entities Qualify", [
"The election is available to partnerships and S corporations. Sole proprietorships and single-member LLCs treated as disregarded entities generally do not qualify, because there is no entity separate from the individual for this purpose.",
"That is a meaningful planning point. A single-member LLC owner in a PTET state may benefit from adding a second member, converting the entity to a partnership, or electing S corporation status, purely to access the election.",
"The second member must be genuine. A nominal interest with no capital and no economic participation invites challenge on multiple fronts.",
"C corporations do not need the workaround, since they deduct state taxes at the entity level already.",
]),
("Where It Backfires", [
"The election is not universally beneficial, and several fact patterns produce a worse outcome.",
"Owners who do not itemize. If an owner takes the standard deduction, the SALT cap was not costing them anything, and the entity-level tax simply shifts timing without benefit. Some state designs can leave them worse off.",
"Nonresident owners. An owner living in a state that does not allow a credit for another state's PTET can end up double taxed. Several states have addressed this and several have not. For a partnership with owners in multiple states, this must be modeled owner by owner.",
"Owners with state credits or attributes. An owner already using state credits that offset their liability may find the entity-level payment redundant.",
"Owners in a loss year. The entity-level tax is generally computed on entity income, and an owner with offsetting losses elsewhere may prepay tax they would not have owed.",
"Cash flow timing. The entity must actually pay the tax to deduct it, and most states require estimated payments during the year. An entity that distributes all cash to owners may need to change its distribution policy.",
]),
("Election Mechanics Vary Widely", [
"There is no uniform design. Some states require an annual election, some make it binding for multiple years, and some require it to be made by a specific date well before the return is filed.",
"Some states require unanimous owner consent. Some allow a majority. Some let individual owners opt in or out.",
"Rates differ. Some states apply the top individual rate, some apply a flat rate, and some apply a rate that differs from what the owner would have paid individually. Where the entity rate exceeds the owner's effective rate, the credit may not fully compensate.",
"Credit mechanics differ. A refundable credit is generally better than a non-refundable one, and an income exclusion approach behaves differently from a credit approach when the owner has other income in the state.",
"Because of this variation, the analysis is state specific and must be run against the actual statute rather than a general description.",
]),
("The Federal Deduction Timing", [
"Notice 2020-75 confirms the deduction is allowed in computing the entity's non-separately stated income. For a cash method entity, that means the deduction lands in the year the tax is actually paid.",
"An entity that pays its full state liability by December 31 deducts it that year. An entity that pays in April with the return deducts it the following year.",
"This creates an actionable year-end item. Making the PTET payment before year end accelerates the federal deduction by a full year, which for a first-year election means capturing the benefit immediately rather than a year later.",
]),
("Interaction With the QBI Deduction", [
"The PTET payment reduces qualified business income, because it reduces the entity's non-separately stated income.",
"For an owner claiming the 20% qualified business income deduction under IRC Sec. 199A, that means the PTET reduces the QBI deduction by 20% of the payment.",
"On a $54,000 PTET payment, the QBI deduction falls by roughly $10,800, reducing the net federal benefit. The election is usually still worthwhile, but the benefit is smaller than the headline number for owners with a full QBI deduction.",
"For owners in a specified service trade or business above the phase-out, where no QBI deduction is available, there is no offset and the full benefit is retained.",
]),
("Worked Example: Three-Partner Firm", [
"A firm operates in a PTET state with a 6.5% rate and allocates income equally among three partners, each receiving $780,000. All three are residents of the state and itemize.",
"Without the election, each partner pays approximately $50,700 of state income tax personally, of which almost none is deductible federally given the SALT cap and their property taxes.",
"With the election, the entity pays $152,100 of state tax and deducts it. Each partner's K-1 income falls to $729,300, and each receives a state credit for their share of the entity tax.",
"The federal deduction of $50,700 per partner at a 37% rate is worth $18,759 each, or $56,277 across the firm.",
"The firm is a specified service trade or business above the phase-out, so no QBI deduction is lost. The full benefit is retained.",
"The election is made by the state's deadline, unanimous consent is documented, and the full payment is made by December 31 to secure the deduction in the current year rather than the next.",
]),
],
"faqs": [
("Is the pass-through entity tax election legitimate?",
 "Yes. IRS Notice 2020-75 confirmed that state income taxes paid by a partnership or S corporation are deductible in computing the entity's non-separately stated income and are not subject to the individual SALT cap under IRC Sec. 164(b)(6)."),
("Can a single-member LLC make the election?",
 "Generally no, because a disregarded entity is not separate from the individual for this purpose. Owners in PTET states sometimes add a genuine second member or elect S corporation status specifically to access the election."),
("Does the election reduce my QBI deduction?",
 "Yes. The PTET payment reduces qualified business income, so an owner claiming the full 20% deduction under IRC Sec. 199A loses 20% of the payment in QBI deduction. Owners in a specified service business above the phase-out have no offset and keep the full benefit."),
("When should the entity pay the tax?",
 "By December 31 for a cash method entity. The federal deduction lands in the year of payment, so paying before year end captures the benefit a full year earlier than paying with the return in April."),
("Can the election make me worse off?",
 "Yes, in several cases: owners who take the standard deduction, nonresident owners in states that do not credit another state's PTET, owners already using state credits, and owners in a loss year. The analysis should be run owner by owner, not just at the entity level."),
],
"related": [
("/blog/how-to-structure-multiple-businesses-for-tax-efficiency/", "Structuring multiple businesses"),
("/blog/qbi-deduction-optimization-irc-199a/", "QBI deduction optimization"),
("/blog/estimated-tax-payment-strategies-business-owners/", "Estimated tax payment strategies"),
],
"cta_head": "Model It Owner by Owner Before December",
"cta_body": "The election helps most owners and hurts a few, and the payment deadline decides which year the deduction lands in. Bring your K-1 allocations and owner residency.",
},

{
"slug": "can-i-deduct-the-cost-of-a-cost-segregation-study",
"title": "Can I Deduct the Cost of a Cost Segregation Study?",
"meta_title": "Can I Deduct the Cost of a Cost Segregation Study? (2026) | AE Tax Advisors",
"meta_desc": "Study fees are generally deductible as an ordinary business expense, not capitalized into basis. Where the fee is deducted and how to evaluate ROI in 2026.",
"category": CS, "date": D,
"intro": [
"Yes, in nearly all cases. The fee for a cost segregation study is an ordinary and necessary expense of determining your tax liability, deductible under IRC Sec. 212 for an investment activity or IRC Sec. 162 for a trade or business.",
"It is not capitalized into the basis of the property, and it is not amortized. Understanding why matters, because the same logic distinguishes a study fee from costs that must be capitalized.",
],
"sections": [
("Why It Is a Current Deduction", [
"A cost segregation study does not acquire, improve, or produce property. It analyzes property you already own and determines the correct classification of components for depreciation purposes.",
"That makes it a cost of tax compliance and tax determination rather than a capital expenditure. Under Treasury Regulation Sec. 1.263(a)-2, amounts paid to acquire or produce tangible property are capitalized. A study neither acquires nor produces anything.",
"For a rental property owner, the fee is deducted on Schedule E as a professional fee against the rental activity. For an operating business owner, it is deducted on the business return.",
"The deduction is subject to the same passive activity rules as the rest of the activity's expenses. A passive rental owner adds the fee to the activity's loss, which suspends along with everything else if it cannot be used currently.",
]),
("The Timing Question", [
"Cash method taxpayers deduct the fee when paid. Accrual method taxpayers deduct when the liability is fixed and determinable and economic performance has occurred.",
"For a study commissioned in November and delivered in February, a cash method taxpayer who pays in December deducts in the earlier year, and one who pays in February deducts in the later year.",
"This rarely drives the decision given the size of the underlying deduction, but for a taxpayer at a bracket threshold it is a free lever.",
]),
("What Is Not Deductible", [
"Fees paid in connection with acquiring the property are a different matter. A purchase price allocation performed as part of due diligence before closing, or an appraisal obtained to support a loan, is generally a cost of acquiring the property and is capitalized.",
"The distinction is purpose and timing. A study performed after acquisition to determine depreciation on property you own is a tax determination cost. An allocation performed as part of negotiating or closing the acquisition is an acquisition cost.",
"Fees for filing Form 3115 as part of a look-back study follow the same treatment as the study itself: current deduction as a professional fee.",
]),
("Evaluating Whether a Study Is Worth It", [
"Study fees for residential rental property typically run $3,000 to $9,000 depending on size and complexity. Commercial property studies run $6,000 to $25,000, and large or specialized properties more.",
"The relevant comparison is the present value of the accelerated deduction against the fee, not the nominal deduction against the fee.",
"On a property with $700,000 of depreciable basis and a 25% reclassification, the study accelerates roughly $175,000 of deduction from a 27.5-year schedule into year one. At a 35% marginal rate that is approximately $61,000 of tax deferred.",
"The deferral is not permanent. You are borrowing depreciation from future years at zero interest. The value is the time value of that money plus any rate arbitrage between your current bracket and your future bracket.",
"For a taxpayer at 37% now who expects to be at 24% in retirement, the rate arbitrage alone is substantial. For a taxpayer whose rate will be higher later, the analysis is different and should be run.",
]),
("When the Study Is Not Worth It", [
"There are genuine cases where the answer is no, and a firm that never says so is not being straight with you.",
"Properties with low depreciable basis. Below roughly $400,000 of depreciable basis, the fee often consumes too much of the benefit for residential property.",
"Owners who cannot use the loss. If the deduction will suspend under IRC Sec. 469 with no passive income and no path to real estate professional status, the benefit is deferred indefinitely. The study may still be worth running later.",
"Short expected hold periods. A property being sold within two or three years generates recapture that largely reverses the benefit, and the Sec. 1245 recapture is at ordinary rates.",
"Properties in states that decouple sharply, where the state benefit is much smaller than the federal number implies, though this generally reduces rather than eliminates the case.",
]),
("Worked Example: Fee Against Benefit", [
"An investor owns a $1,300,000 fourplex with $1,080,000 of depreciable basis, acquired three years ago and never studied.",
"A look-back study costs $7,400 and identifies 26% reclassification. Combined with the Form 3115 catch-up for the three prior years, the current-year deduction is approximately $316,000.",
"The investor's spouse qualifies as a real estate professional and the aggregation election is in place, so the loss is non-passive. At a combined 38% marginal rate, the current-year tax reduction is approximately $120,000.",
"The $7,400 fee is deducted currently as a professional fee on Schedule E, reducing tax by another $2,800.",
"Net first-year benefit is roughly $115,400 against a $7,400 cost. The deduction is a deferral, not a permanent savings, so the true economic value is the time value plus any bracket differential at the eventual disposition, which the investor plans to defer indefinitely through a 1031 exchange.",
]),
],
"faqs": [
("Is a cost segregation study fee deductible?",
 "Yes, generally as an ordinary and necessary expense under IRC Sec. 212 or Sec. 162. It is a tax determination cost, not a capital expenditure, because the study does not acquire, produce, or improve property. It is not added to basis or amortized."),
("Where do I deduct the fee?",
 "On Schedule E as a professional fee for a rental activity, or on the business return for an operating business. It is subject to the same passive activity rules as the rest of the activity's expenses."),
("Is a purchase price allocation done before closing deductible?",
 "Generally no. An allocation or appraisal performed as part of acquiring the property is an acquisition cost and is capitalized. The distinction is whether the work determines depreciation on property you already own or supports the acquisition itself."),
("How much does a study cost?",
 "Residential rental studies typically run $3,000 to $9,000. Commercial studies run $6,000 to $25,000, with large or specialized properties higher. The comparison that matters is the present value of the accelerated deduction against the fee."),
("When is a study not worth it?",
 "When depreciable basis is below roughly $400,000 for residential property, when the loss will suspend indefinitely under IRC Sec. 469 with no path to using it, or when the property will be sold within a few years and recapture reverses most of the benefit."),
],
"related": [
("/blog/how-much-does-a-cost-segregation-study-cost/", "How much does a cost segregation study cost"),
("/blog/how-to-evaluate-cost-segregation-study/", "How to evaluate a cost segregation study"),
("/blog/depreciation-recapture-planning/", "Depreciation recapture planning"),
],
"cta_head": "We Will Tell You When the Answer Is No",
"cta_body": "Send us the basis, your hold plan, and your income picture. If the study does not pay for itself in your situation, we will say so.",
},

{
"slug": "do-i-need-an-engineering-based-cost-segregation-study",
"title": "Do I Need an Engineering Based Cost Segregation Study?",
"meta_title": "Do I Need an Engineering Based Cost Segregation Study? (2026) | AE Tax Advisors",
"meta_desc": "The IRS Audit Techniques Guide favors the detailed engineering approach. Study methodologies compared and what separates a defensible report in 2026.",
"category": CS, "date": D,
"intro": [
"The IRS does not require any specific methodology for a cost segregation study. What it does is describe several approaches in its Cost Segregation Audit Techniques Guide and identify which ones produce the most reliable results.",
"The guide is clear that the detailed engineering approach based on actual cost records is the most accurate and generally produces the most reliable allocation. Everything else is a compromise, and how much of a compromise depends on the property.",
],
"sections": [
("The Methodologies the IRS Describes", [
"The detailed engineering approach from actual cost records applies where the taxpayer has the construction documents, contractor invoices, and change orders. Costs are traced directly to components. This is the most accurate approach and the benchmark against which others are measured.",
"The detailed engineering cost estimate approach applies where the property was purchased rather than constructed and actual cost records are unavailable. An engineer takes off quantities from drawings or a site inspection and applies published cost data to estimate component costs, then reconciles to the actual purchase price.",
"The survey or letter approach relies on information provided by contractors and subcontractors after the fact.",
"The residual estimation approach values short-lived assets and treats the remainder as building. It is faster and less rigorous.",
"The sampling or modeling approach uses a study of representative properties applied across a larger portfolio of similar assets. This has legitimate applications for chain retail or restaurant portfolios with standardized builds.",
"The rule of thumb approach applies a percentage based on experience with similar properties. The guide is explicit that this approach lacks documentation and is not a reliable basis for a study.",
]),
("What Separates a Defensible Report", [
"The guide identifies elements of a quality study, and they are worth knowing because they are also a useful buyer's checklist.",
"A preparer with expertise in both construction and tax law. Cost estimating alone is not enough, because the classification questions are legal ones. Tax knowledge alone is not enough, because the quantities and costs require engineering judgment.",
"A detailed description of the methodology used, with an explanation of why it was appropriate for the property.",
"A complete asset listing with descriptions, cost allocations, and the recovery period assigned to each, along with the authority supporting each classification.",
"A reconciliation to the total depreciable basis, demonstrating that all costs were accounted for and none were double counted or omitted.",
"Photographs, drawings, and documentation of the physical inspection.",
"Citations to relevant authority for the classifications taken, particularly for items where the treatment is not obvious.",
]),
("Why the Cheap Study Is Expensive", [
"Studies advertised at a few hundred dollars, produced from a questionnaire and a purchase price with no inspection and no engineering work, are rule of thumb studies with a professional-looking cover.",
"On examination, they cannot substantiate the allocations because there is no underlying work product. The examiner asks how the $186,000 of electrical was determined and there is no answer beyond a percentage.",
"The outcome is not usually total disallowance. It is a negotiated reduction, plus accuracy-related penalty exposure under IRC Sec. 6662 where the understatement is substantial, plus the professional fees to defend it.",
"The economics are straightforward. A study producing a $300,000 deduction that is reduced by 40% on examination has cost the taxpayer $120,000 of deduction plus defense costs to save perhaps $5,000 on the study fee.",
]),
("When a Lighter Approach Is Defensible", [
"Not every property needs the full detailed engineering treatment.",
"Small residential rentals with straightforward components can be handled with a properly documented estimate approach at lower cost, provided a site inspection or thorough documentation review occurs and the report identifies specific components rather than applying a percentage.",
"Portfolios of standardized properties are the clearest case for a sampling approach. A chain with 40 identical builds can study a representative sample and apply the results, which the guide contemplates.",
"What is never defensible is applying a percentage with no component identification and no documentation, regardless of property size.",
]),
("The Preparer Question", [
"There is no license or credential required to perform a cost segregation study, which means the market includes both engineering firms with decades of experience and operations that produce reports from a spreadsheet.",
"Useful questions to ask: Who performs the site inspection and what are their qualifications? Will I receive a complete asset listing with authority cited for each classification? What is included if the return is examined? Can I see a sample report for a property like mine?",
"The audit support answer matters. A firm that stands behind its work and will support the report at no additional cost has different incentives than one that hands you a PDF and moves on.",
]),
("Worked Example: Two Studies, Same Property", [
"An investor acquires a $2,600,000 medical office building with $2,150,000 of depreciable basis.",
"Study A costs $1,200, is produced from a questionnaire with no site visit, and reports 24% reclassification with a two-page summary and no asset listing.",
"Study B costs $11,500, includes a site inspection, a review of available construction documentation, quantity takeoffs, published cost data applied to each component, a 90-page report with a complete asset listing, authority cited for each classification, photographs, and a reconciliation to total basis. It reports 27% reclassification.",
"Study B produces $64,500 more deduction on its face, roughly $23,900 of additional tax benefit at a 37% rate, which already exceeds the fee difference.",
"More importantly, Study B is defensible. Study A's $516,000 reclassification is a number with nothing behind it, and on examination the taxpayer has no basis for defending any specific component.",
]),
],
"faqs": [
("Does the IRS require an engineering based study?",
 "No methodology is required, but the IRS Cost Segregation Audit Techniques Guide identifies the detailed engineering approach from actual cost records as the most accurate and reliable. The guide is explicit that rule of thumb approaches lack documentation and are not reliable."),
("What makes a study defensible?",
 "A preparer with both construction and tax expertise, a documented methodology, a complete asset listing with recovery periods and cited authority for each item, a reconciliation to total depreciable basis, a physical inspection, and supporting photographs and drawings."),
("Are cheap studies a problem?",
 "Usually. A study produced from a questionnaire with no inspection and no component identification cannot substantiate its allocations on examination. The typical outcome is a negotiated reduction plus accuracy-related penalty exposure under IRC Sec. 6662, which far exceeds the fee saved."),
("Can I use a sampling approach for a portfolio?",
 "Yes, for standardized properties. The Audit Techniques Guide contemplates a sampling or modeling approach where a representative study is applied across a portfolio of similar assets, which fits chain retail, restaurant, and standardized build portfolios well."),
("What should I ask a study provider?",
 "Who performs the site inspection and what are their qualifications, whether you receive a complete asset listing with authority cited per item, what audit support is included and at what cost, and whether you can see a sample report for a comparable property."),
],
"related": [
("/blog/how-to-evaluate-cost-segregation-study/", "How to evaluate a cost segregation study"),
("/blog/does-cost-segregation-increase-audit-risk/", "Does cost segregation increase audit risk"),
("/blog/can-i-deduct-the-cost-of-a-cost-segregation-study/", "Deducting the cost of a study"),
],
"cta_head": "Ask for the Asset Listing Before You Pay",
"cta_body": "A study you cannot defend is worse than no study. We will walk you through what a defensible report contains and what your property actually needs.",
},

{
"slug": "what-is-boot-in-a-1031-exchange",
"title": "What Is Boot in a 1031 Exchange and How Do You Avoid It?",
"meta_title": "What Is Boot in a 1031 Exchange? (2026 Guide) | AE Tax Advisors",
"meta_desc": "Boot is anything received that is not like-kind property, and it triggers gain. Cash boot, mortgage boot, and the two rules that prevent both in 2026.",
"category": RE, "date": D,
"intro": [
"Boot is the term for anything you receive in a 1031 exchange that is not like-kind property. Receiving boot does not disqualify the exchange, but it triggers recognition of gain up to the amount of boot received.",
"There are two kinds, and investors routinely avoid one while walking directly into the other.",
],
"sections": [
("Cash Boot", [
"Cash boot is the straightforward version. Any exchange proceeds you actually or constructively receive, rather than reinvesting into replacement property, is boot.",
"Under IRC Sec. 1031(b), gain is recognized to the extent of money and other property received, limited to the realized gain.",
"An investor who sells for $1,400,000 and buys replacement property for $1,250,000 has $150,000 of cash boot and recognizes $150,000 of gain, assuming realized gain is at least that much.",
"Constructive receipt counts. Proceeds held by an agent you control, or funds you could have accessed, are received even if you did not touch them. This is why a qualified intermediary is essential and why the exchange agreement restricts your access.",
"Cash used to pay non-transactional expenses at closing is also boot. Prorated rents, security deposits transferred, and repairs credited to the buyer are generally not exchange expenses, and paying them from exchange proceeds creates boot. Transactional expenses like broker commissions, title fees, and recording fees generally do not.",
]),
("Mortgage Boot Is the One That Surprises People", [
"Mortgage boot, also called debt relief, arises when the debt on the relinquished property exceeds the debt on the replacement property. Under Treasury Regulation Sec. 1.1031(d)-2, relief from a liability is treated as money received.",
"An investor who sells a property with $800,000 of debt and buys one with $600,000 of debt has $200,000 of mortgage boot, even if every dollar of cash proceeds was reinvested.",
"This catches investors who focus entirely on the equity and ignore the debt. Reinvesting all the cash is necessary but not sufficient.",
"Mortgage boot can be offset by adding cash to the replacement purchase. An investor with $200,000 of debt relief who contributes $200,000 of outside cash to the replacement acquisition eliminates the boot.",
"Cash boot cannot be offset by taking on additional debt. The rules are asymmetric: additional cash cures debt relief, but additional debt does not cure cash received. This asymmetry is the single most useful thing to understand about boot.",
]),
("The Two Rules That Prevent Boot", [
"Rule one: the replacement property must cost at least as much as the relinquished property's net selling price.",
"Rule two: all net equity from the sale must be reinvested, and the debt on the replacement must be equal to or greater than the debt on the relinquished property, or the shortfall made up with outside cash.",
"Investors who satisfy both rules have a fully deferred exchange. Investors who satisfy the first but not the second frequently have mortgage boot they did not anticipate.",
"Trading up in value and up in debt is the safe pattern. Trading up in value while paying down debt requires outside cash equal to the debt reduction.",
]),
("Personal Property and Non-Like-Kind Components", [
"Since 2017, IRC Sec. 1031 applies only to real property. Personal property received in an exchange is boot.",
"This matters for property types with substantial personal property. Acquiring a furnished short-term rental, a hotel, or a senior living community means part of the purchase price is furniture, fixtures, and equipment, which is not like-kind to the real property relinquished.",
"The practical answer is to allocate and structure deliberately. Purchase the personal property separately with non-exchange funds, or accept the boot and plan for the tax. Where the personal property is substantial, a cost segregation study on the replacement can generate offsetting depreciation.",
"Note the interaction: personal property acquired outside the exchange has a full cost basis and is bonus eligible under IRC Sec. 168(k), while the real property carries over basis from the relinquished property.",
]),
("How Boot Is Taxed", [
"Recognized gain retains its character. Boot does not create a special category.",
"Gain recognized is allocated first to depreciation recapture. Sec. 1245 recapture from a prior cost segregation study is ordinary income and comes out first. Unrecaptured Sec. 1250 gain at up to 25% comes next. Long-term capital gain at preferential rates comes last.",
"That ordering means a small amount of boot can produce a disproportionately expensive result for an investor with heavy Sec. 1245 property. An investor with $340,000 of Sec. 1245 recapture who takes $60,000 of boot recognizes that $60,000 entirely as ordinary income at up to 37%, not at capital gain rates.",
"This is a strong argument for eliminating boot entirely rather than accepting a small amount as immaterial.",
]),
("Worked Example: Debt Relief Caught in Time", [
"An investor sells an apartment building for $2,400,000 with $1,350,000 of debt and $980,000 of adjusted basis, producing $1,420,000 of realized gain including $215,000 of Sec. 1245 recapture from a prior study.",
"Selling costs are $144,000, so net proceeds after paying off debt are $906,000.",
"The intended replacement is a $2,450,000 property with $1,100,000 of debt. Equity required is $1,350,000, but only $906,000 of exchange proceeds are available, so the investor plans to add $444,000 of outside cash.",
"The value test passes: $2,450,000 exceeds the $2,256,000 net selling price. All equity is reinvested.",
"But debt drops from $1,350,000 to $1,100,000, creating $250,000 of mortgage boot. The $444,000 of outside cash contributed to the acquisition offsets it entirely, because cash added cures debt relief.",
"Had the investor instead financed $1,350,000 on the replacement and contributed only $194,000 of cash, the outcome would also have been fully deferred. Either path works. Contributing $194,000 of cash while financing only $1,100,000 would have produced $250,000 of boot, of which $215,000 would have been taxed as ordinary recapture.",
]),
],
"faqs": [
("What is boot in a 1031 exchange?",
 "Anything you receive that is not like-kind property. Cash boot is exchange proceeds you receive rather than reinvest. Mortgage boot is debt relief where the replacement property carries less debt than the relinquished property. Both trigger gain recognition under IRC Sec. 1031(b)."),
("Can I offset mortgage boot with new debt?",
 "You can avoid it by taking on at least as much debt on the replacement, or by contributing outside cash equal to the shortfall. The asymmetry matters: cash cures debt relief, but taking on more debt does not cure cash you actually received."),
("Are closing costs boot?",
 "Transactional expenses like broker commissions, title fees, and recording fees generally are not. Non-transactional items paid from exchange proceeds, such as prorated rents, security deposits, and repair credits to the buyer, generally are boot."),
("Is furniture in a replacement property boot?",
 "Yes. Since 2017, IRC Sec. 1031 applies only to real property, so personal property received is boot. For furnished short-term rentals, hotels, or senior living, allocate and purchase the personal property separately with non-exchange funds where possible."),
("How is boot taxed?",
 "Recognized gain comes out in order: Sec. 1245 recapture as ordinary income first, then unrecaptured Sec. 1250 gain at up to 25%, then long-term capital gain. An investor with heavy Sec. 1245 property from a prior study pays ordinary rates on even a small amount of boot."),
],
"related": [
("/blog/how-does-1031-exchange-work-for-rental-properties/", "How a 1031 exchange works"),
("/blog/1031-exchange-timeline-45-180-day-rules/", "The 45 and 180 day rules"),
("/blog/common-1031-exchange-mistakes/", "Common 1031 exchange mistakes"),
],
"cta_head": "Run the Debt Math Before You Sign the Replacement Contract",
"cta_body": "Mortgage boot is the failure most investors do not see coming. Send us the relinquished and replacement terms and we will confirm the exchange is fully deferred.",
},

{
"slug": "hsa-strategy-for-business-owners",
"title": "The HSA Is the Only Triple Tax Advantaged Account, and Business Owners Underuse It",
"meta_title": "HSA Strategy for Business Owners (2026 Guide) | AE Tax Advisors",
"meta_desc": "HSAs are deductible going in, tax free growing, and tax free coming out for medical costs. Contribution limits, the receipt strategy, and S corp rules.",
"category": BO, "date": D,
"intro": [
"A health savings account is the only account in the code with three tax advantages at once. Contributions are deductible, growth is untaxed, and qualified medical distributions are untaxed.",
"A 401(k) gives you two of the three. A Roth gives you two. The HSA gives you all three, and most business owners treat it as a spending account rather than an investment account.",
],
"sections": [
("The Eligibility Requirement", [
"To contribute, you must be covered by a high deductible health plan and have no other disqualifying coverage.",
"The plan must meet minimum deductible and maximum out-of-pocket requirements that adjust annually. For 2025, the minimum deductible is $1,650 for self-only coverage and $3,300 for family coverage.",
"Disqualifying coverage includes a general purpose health flexible spending account, including a spouse's FSA, which is a common and overlooked disqualifier. Enrollment in Medicare also ends eligibility.",
"Contribution limits for 2025 are $4,300 for self-only and $8,550 for family coverage, with an additional $1,000 catch-up for those 55 and older. Both spouses 55 or older can each make a catch-up contribution, but the catch-up must go to each spouse's own account.",
]),
("The Strategy Most People Miss", [
"The default behavior is to contribute and then spend the balance on current medical expenses. That captures the deduction but wastes the growth advantage entirely.",
"The better approach is to contribute the maximum, invest the balance, pay current medical expenses from other funds, and let the account compound untouched.",
"There is no deadline for reimbursing yourself. As long as the expense was incurred after the account was established and you were eligible at the time, you can reimburse yourself years or decades later, tax free.",
"That means an owner who saves receipts for twenty years builds a documented reserve of qualified expenses that can be withdrawn tax free at any point. A $60,000 file of receipts is a $60,000 tax-free withdrawal available on demand, while the account itself compounded untouched.",
"The practical requirement is documentation. Keep the receipts and an explanation of benefits, organized by year, in a form you will still have in twenty years. A scanned folder is sufficient.",
]),
("After 65 It Becomes a Retirement Account", [
"After age 65, non-qualified distributions are subject to income tax but not the 20% penalty. That makes the HSA function like a traditional IRA for non-medical spending, while remaining entirely tax free for medical spending.",
"Medical spending in retirement is substantial. Medicare premiums for Part B and Part D, and Medicare Advantage premiums, are qualified expenses payable from an HSA. Medigap premiums are not.",
"Long-term care insurance premiums are qualified up to age-based limits.",
"For a couple retiring at 65, projected lifetime medical costs commonly exceed $300,000. An HSA funded for twenty years and invested can cover a meaningful share of that with money that was never taxed at any point.",
]),
("The S Corporation Complication", [
"For a more than 2% shareholder of an S corporation, HSA contributions made by the corporation are treated as wages, included in Box 1 of the W-2, and are not excludable from income.",
"The shareholder then takes an above-the-line deduction for the contribution on their personal return under IRC Sec. 223.",
"The net income tax result is the same, but the contribution is not exempt from income inclusion the way it is for a regular employee. It is, however, generally excluded from social security and Medicare wages, which preserves a payroll tax benefit.",
"Partners in a partnership face similar treatment, with contributions treated as guaranteed payments and deducted personally.",
"Sole proprietors simply take the above-the-line deduction. There is no entity-level contribution.",
"The practical guidance is to handle the W-2 reporting correctly, because this is one of the most commonly botched items on S corporation returns for owner-employees.",
]),
("Estate Treatment Is the Weak Point", [
"An HSA inherited by a spouse becomes the spouse's own HSA and continues its tax treatment.",
"An HSA inherited by anyone else is different. The account ceases to be an HSA on the date of death, and the fair market value is included in the beneficiary's gross income for that year. There is no stretch and no deferral.",
"That makes an HSA a poor asset to leave to children relative to a Roth IRA, which they can hold and withdraw tax free over ten years.",
"For an owner with a large HSA and non-spouse heirs, spending the HSA during retirement, or naming a charity as beneficiary, is generally better than leaving it to children.",
]),
("Worked Example: Twenty Year Accumulation", [
"A 45-year-old business owner with family coverage contributes the maximum annually and invests the balance rather than spending it, paying current medical costs from cash flow and saving every receipt.",
"Over twenty years at an average contribution near $9,000 and 7% growth, the account reaches roughly $395,000.",
"The contributions were deductible at a 37% marginal rate, worth approximately $66,000 of tax reduction over the period.",
"The growth of roughly $215,000 was never taxed.",
"The owner has accumulated $84,000 of documented unreimbursed medical expenses over twenty years, available for tax-free withdrawal at any time.",
"In retirement, Medicare Part B and Part D premiums plus out-of-pocket costs are paid from the account tax free.",
"The same $180,000 of contributions placed in a taxable brokerage account would have produced no deduction, taxable growth, and taxable withdrawals. The difference across the three advantages exceeds $150,000.",
]),
],
"faqs": [
("Why is an HSA better than a 401(k) or Roth?",
 "It is the only account with three tax advantages simultaneously: deductible contributions, untaxed growth, and untaxed qualified medical distributions. A traditional 401(k) taxes withdrawals. A Roth taxes contributions. The HSA taxes neither."),
("Do I have to spend HSA money on current medical expenses?",
 "No, and you generally should not. There is no deadline for reimbursing yourself, so you can pay current costs from other funds, invest the HSA balance, save the receipts, and reimburse yourself tax free years or decades later."),
("How are HSA contributions handled for an S corp owner?",
 "For a more than 2% shareholder, corporate contributions are included in W-2 Box 1 wages, and the shareholder takes an above-the-line deduction under IRC Sec. 223. They are generally excluded from social security and Medicare wages, preserving a payroll tax benefit."),
("Can I still contribute after enrolling in Medicare?",
 "No. Medicare enrollment ends HSA eligibility. You can still spend the existing balance tax free on qualified expenses, including Medicare Part B, Part D, and Medicare Advantage premiums, though Medigap premiums do not qualify."),
("What happens to my HSA when I die?",
 "A spouse beneficiary takes it over as their own HSA. Any other beneficiary must include the full fair market value in gross income in the year of death, with no stretch or deferral. That makes an HSA a poor asset to leave to children compared to a Roth IRA."),
],
"related": [
("/blog/merp-medical-expense-reimbursement-plan-s-corp/", "MERP for S corporation owners"),
("/blog/can-my-s-corp-pay-for-my-health-insurance/", "S corp health insurance deductions"),
("/blog/what-retirement-plan-gives-the-largest-tax-deduction/", "Which retirement plan gives the largest deduction"),
],
"cta_head": "Stop Treating It Like a Spending Account",
"cta_body": "The receipt strategy turns an HSA into the most tax-efficient account you own. We will set up the documentation system and confirm your S corp reporting is right.",
},

{
"slug": "safe-harbor-rule-for-estimated-tax-payments",
"title": "The Safe Harbor Rule for Estimated Taxes: How to Never Owe a Penalty",
"meta_title": "Safe Harbor Rule for Estimated Tax Payments (2026) | AE Tax Advisors",
"meta_desc": "Pay 100 or 110 percent of last year's tax and the underpayment penalty cannot apply, no matter how much you earn. Withholding timing and annualization rules.",
"category": BO, "date": D,
"intro": [
"The estimated tax underpayment penalty is one of the easiest taxes to avoid entirely, and business owners pay it constantly because they are trying to estimate the wrong number.",
"You do not have to accurately predict this year's tax. Under IRC Sec. 6654, paying a specified percentage of last year's tax eliminates the penalty regardless of what this year turns out to be.",
],
"sections": [
("The Two Safe Harbors", [
"For individuals, the penalty does not apply if withholding and timely estimated payments equal at least 90% of the current year tax, or 100% of the prior year tax.",
"For taxpayers whose prior year adjusted gross income exceeded $150,000, or $75,000 for married filing separately, the prior year threshold rises to 110%.",
"The prior year safe harbor is the useful one, because it is a known number. You have already filed the return. There is no estimation involved.",
"An owner whose prior year tax was $214,000 and whose AGI exceeded $150,000 pays $235,400 across four timely installments and cannot be penalized, even if the current year tax turns out to be $600,000.",
"The prior year must have been a full twelve-month year with a filed return for the safe harbor to apply.",
]),
("The Payment Schedule Matters", [
"Payments must be timely, not merely sufficient in total. The installment due dates are generally April 15, June 15, September 15, and January 15 of the following year.",
"Each installment must cover one quarter of the required annual payment. Paying the full amount in December does not cure earlier underpayments, because the penalty is computed per period.",
"An owner who pays nothing for three quarters and then pays the full annual amount in January still owes penalty on the first three installments.",
]),
("Withholding Is Treated as Paid Evenly", [
"This is the most useful mechanic in the rules and it is widely unknown. Under IRC Sec. 6654(g), amounts withheld are treated as paid ratably throughout the year regardless of when they were actually withheld.",
"That means an owner who reaches December and realizes they are underpaid can eliminate the entire penalty by increasing withholding on a December paycheck or on a retirement distribution.",
"A $90,000 withholding in December is treated as $22,500 paid in each quarter, curing all four periods retroactively.",
"For an S corporation owner, this means running a large withholding through a year-end bonus payroll. For a taxpayer with an IRA, a distribution with substantial withholding can accomplish the same thing, though the distribution itself is taxable.",
"There is no equivalent for estimated payments. A fourth-quarter estimated payment is credited to the fourth quarter only.",
]),
("The Annualized Income Method", [
"Where income is heavily back-loaded, the annualized income installment method under IRC Sec. 6654(d)(2) can reduce required earlier installments.",
"This applies to a business owner whose income arrives in the fourth quarter, an investor with a large year-end capital gain, or anyone whose prior year safe harbor is unavailable or unattractive.",
"The method computes each installment based on income actually earned through that point in the year, annualized. It is reported on Form 2210 Schedule AI.",
"The tradeoff is complexity and documentation. It requires computing taxable income at four points during the year, with deductions allocated appropriately. For most taxpayers the prior year safe harbor is simpler and equally effective.",
]),
("When the Prior Year Safe Harbor Is a Bad Choice", [
"The safe harbor guarantees no penalty. It does not guarantee no balance due.",
"An owner whose prior year tax was $180,000 and whose current year tax is $520,000 pays $198,000 in estimates under the safe harbor and owes $322,000 in April. That is not a penalty, but it is a cash flow event that has to be planned for.",
"Owners in a rapidly growing business should generally pay more than the safe harbor requires, not to avoid penalty but to avoid a large April obligation.",
"Conversely, an owner whose income is declining sharply should consider the 90% of current year method, since paying 110% of a much larger prior year unnecessarily ties up cash.",
]),
("State Rules Differ", [
"State safe harbor rules do not always match the federal ones. Some states use different percentages, different thresholds, or different installment schedules.",
"Some states do not recognize the ratable withholding treatment, which means the December withholding fix that works federally may not work at the state level.",
"For a taxpayer with meaningful state liability, the state calculation should be run separately rather than assumed to follow the federal result.",
]),
("Worked Example: The December Fix", [
"A business owner had $268,000 of prior year tax and AGI above $150,000, so the safe harbor requires $294,800, or $73,700 per quarter.",
"They paid $40,000 in each of the first three quarters, totaling $120,000, leaving them $101,100 short across three installments.",
"In early December they realize the shortfall. Rather than making a large fourth quarter estimated payment, which would only be credited to the fourth quarter, they run a year-end payroll through their S corporation with $175,000 of federal withholding.",
"Under IRC Sec. 6654(g), that withholding is treated as $43,750 paid in each quarter. Combined with the $40,000 quarterly estimates, each of the first three installments is now covered at $83,750 against the $73,700 required.",
"The penalty is eliminated entirely. The same amount paid as a December estimated payment would have left three quarters underpaid and a penalty running from April.",
]),
],
"faqs": [
("What is the estimated tax safe harbor?",
 "Under IRC Sec. 6654, no underpayment penalty applies if timely payments equal at least 90% of current year tax or 100% of prior year tax. That prior year threshold rises to 110% if prior year adjusted gross income exceeded $150,000."),
("Can I just pay everything in the fourth quarter?",
 "Not with estimated payments. The penalty is computed per period, so a December estimated payment does not cure earlier underpayments. Withholding is different: under IRC Sec. 6654(g) it is treated as paid ratably across the year regardless of when withheld."),
("How does the December withholding trick work?",
 "Increase withholding late in the year through a year-end payroll or a retirement distribution. Because withholding is deemed paid evenly across all four quarters, a large December withholding retroactively cures underpayments in every earlier period."),
("Does the safe harbor mean I will not owe anything in April?",
 "No. It only prevents the penalty. An owner whose income grew sharply can pay the safe harbor amount and still owe a very large balance in April. Growing businesses should generally pay above the safe harbor for cash flow reasons."),
("Do states follow the same rules?",
 "Not always. State safe harbor percentages, thresholds, and installment schedules vary, and some states do not treat withholding as paid ratably. Run the state calculation separately rather than assuming it follows the federal result."),
],
"related": [
("/blog/estimated-tax-payment-strategies-business-owners/", "Estimated tax payment strategies"),
("/blog/real-estate-investor-estimated-tax-payments/", "Estimated taxes for real estate investors"),
("/blog/year-end-tax-planning-checklist-real-estate-investors/", "Year-end tax planning checklist"),
],
"cta_head": "The Fix Is Available Through December 31",
"cta_body": "If you are underpaid this year, withholding still cures it retroactively. Bring your prior year return and year-to-date payments and we will size the correction.",
},

{
"slug": "can-i-pay-my-spouse-through-my-business",
"title": "Can I Pay My Spouse Through My Business?",
"meta_title": "Can I Pay My Spouse Through My Business? (2026 Guide) | AE Tax Advisors",
"meta_desc": "Paying a spouse can unlock benefits and retirement capacity, but often adds payroll tax with no gain. When it works and when it costs you money in 2026.",
"category": BO, "date": D,
"intro": [
"Yes, if the spouse actually works in the business and the compensation is reasonable for the work performed. The harder question is whether you should, because for many owners it costs money rather than saving it.",
"The answer depends almost entirely on entity type and on what you are trying to accomplish, and the good reasons have nothing to do with income splitting.",
],
"sections": [
("Why It Usually Does Not Save Income Tax", [
"On a joint return, income is taxed the same regardless of which spouse earned it. Moving $60,000 from your Schedule C to your spouse's W-2 does not change taxable income.",
"What it does change is payroll tax. Wages paid to a spouse are subject to social security and Medicare tax, and the business owes the employer share.",
"For a sole proprietor already above the social security wage base, paying a spouse $60,000 adds social security tax that would not otherwise have been owed on those dollars, because the owner's self-employment income above the base is only subject to Medicare.",
"That is a straightforward cost of roughly $7,440 in additional social security tax with no offsetting income tax benefit. Owners who do this expecting savings are usually worse off.",
]),
("The Reasons That Actually Work", [
"Retirement plan capacity is the strongest one. A spouse on payroll can defer into a 401(k) and receive employer contributions, expanding household retirement capacity beyond what the owner alone can contribute.",
"In a solo 401(k) covering an owner and spouse, each can defer the employee limit and each can receive employer contributions, potentially doubling household contributions to $140,000 or more in 2025 before catch-ups.",
"Health benefits are the second. In a sole proprietorship, employing a spouse allows a medical expense reimbursement arrangement covering the employee-spouse and their family, which includes the owner. This converts out-of-pocket medical costs into a business deduction that also reduces self-employment income.",
"Social security credits are the third. A spouse with limited earnings history may benefit from building their own credits, though the spousal benefit already provides 50% of the higher earner's benefit, so this only helps where the spouse's own record would exceed that.",
]),
("The Sole Proprietorship MERP Structure", [
"This is the strategy that genuinely produces meaningful savings, and it works specifically for sole proprietorships and single-member LLCs.",
"The owner employs the spouse. The business establishes a medical expense reimbursement arrangement that reimburses the employee-spouse for family medical expenses, including the owner as a family member.",
"Reimbursements are a deductible business expense, excludable from the spouse's income, and reduce net self-employment income, saving both income tax and self-employment tax.",
"For a household with $22,000 of annual medical costs, the self-employment tax savings alone approach $3,100, on top of the income tax benefit of converting personal medical costs into a business deduction.",
"This requires a properly drafted plan document and compliance with applicable group health plan rules, which have become more restrictive. It is not a do-it-yourself arrangement, and arrangements set up without proper documentation face significant excise tax exposure.",
"It does not work for an S corporation, because a spouse of a more than 2% shareholder is attributed the shareholder's ownership under IRC Sec. 318 and is not treated as a regular employee for this purpose.",
]),
("Documentation Requirements", [
"Whatever the structure, the spouse must actually perform services and the compensation must be reasonable for those services.",
"That means a job description, time records or a defensible account of duties, wages paid on a regular schedule through actual payroll, a Form W-2, and treatment consistent with other employees.",
"Paying a spouse $85,000 for bookkeeping that takes four hours a week is not reasonable compensation and will be adjusted. Paying $28,000 for genuine part-time administrative work is defensible.",
"Payments must actually be made. An accrual on the books with no cash movement is not compensation.",
]),
("The S Corporation Case", [
"For an S corporation, adding a spouse to payroll is more often a cost than a benefit.",
"The owner is already an employee with a salary. Payroll tax applies to that salary. Adding a spouse's salary adds payroll tax on those wages as well, and unlike a sole proprietorship, the MERP structure is unavailable due to attribution.",
"The remaining benefit is retirement plan capacity, which is real. A spouse earning $70,000 can defer the employee limit and receive employer contributions, expanding household retirement savings.",
"Whether that justifies the payroll tax cost depends on the numbers. For a household already maximizing the owner's plan contributions, adding a spouse can be worth it. For a household not yet maxing the owner's own capacity, it usually is not.",
]),
("Worked Example: Sole Proprietor With MERP", [
"A consultant operates as a sole proprietor with $340,000 of net profit. Their spouse handles scheduling, invoicing, and client communication roughly fifteen hours a week.",
"The spouse is placed on payroll at $34,000 annually, which is defensible for the hours and duties. Payroll tax cost is approximately $5,200 including both shares.",
"A properly documented medical expense reimbursement arrangement covers the employee-spouse and family, reimbursing $24,000 of annual medical and dental costs. This is a business deduction that reduces net self-employment income.",
"Self-employment tax savings on the $24,000 reduction are approximately $696, since the owner is above the social security wage base, plus income tax savings of roughly $8,880 at a 37% rate on medical costs that were previously non-deductible given the AGI floor.",
"The spouse defers $23,500 into a solo 401(k) and receives an employer contribution, expanding household retirement capacity by roughly $32,000.",
"Net benefit is positive but modest on the medical side and substantial on the retirement side. An owner who ran the same structure through an S corporation would have captured the retirement benefit and none of the medical benefit.",
]),
],
"faqs": [
("Does paying my spouse reduce our taxes?",
 "Usually not by itself. On a joint return, income is taxed the same regardless of which spouse earned it, and wages paid to a spouse add payroll tax. The benefits come from retirement plan capacity and, for sole proprietors, medical expense reimbursement."),
("What is the best reason to employ a spouse?",
 "Retirement plan capacity. In a solo 401(k) covering both spouses, each can defer the employee limit and receive employer contributions, potentially doubling household contributions. For sole proprietors, a medical expense reimbursement arrangement is the second strong reason."),
("Can I set up a medical reimbursement plan for my spouse?",
 "For a sole proprietorship or single-member LLC, yes, and it converts family medical costs into a business deduction that also reduces self-employment income. It requires a properly drafted plan document and compliance with group health plan rules, so it is not a self-service arrangement."),
("Does the medical reimbursement structure work for an S corporation?",
 "No. A spouse of a more than 2% shareholder is attributed the shareholder's ownership under IRC Sec. 318 and is not treated as a regular employee for this purpose. The retirement plan benefit remains available."),
("What documentation do I need?",
 "A job description, a defensible record of duties and hours, wages paid on a regular schedule through actual payroll, a Form W-2, and compensation that is reasonable for the work performed. Book accruals with no cash movement are not compensation."),
],
"related": [
("/blog/merp-medical-expense-reimbursement-plan-s-corp/", "Medical expense reimbursement plans"),
("/blog/can-i-hire-my-kids-through-my-business-for-tax-savings/", "Hiring your children through your business"),
("/blog/how-much-can-i-contribute-to-a-solo-401k/", "Solo 401(k) contribution limits"),
],
"cta_head": "The Entity Type Decides the Answer",
"cta_body": "The same arrangement helps a sole proprietor and costs an S corporation owner money. Bring your entity structure, profit, and household medical spend.",
},

{
"slug": "can-i-write-off-a-boat-or-airplane-for-business",
"title": "Can I Write Off a Boat or Airplane for My Business?",
"meta_title": "Can I Write Off a Boat or Airplane for Business? (2026) | AE Tax Advisors",
"meta_desc": "Aircraft can be deductible with real business use and strict substantiation. Boats face the entertainment facility rule. What survives an audit in 2026.",
"category": BO, "date": D,
"intro": [
"Aircraft and boats are among the most heavily examined deductions on a business return, and they fail for different reasons. Aircraft fail on substantiation and passive loss rules. Boats fail on a specific statutory provision that makes most boat deductions impossible regardless of business use.",
"Both can work. Neither works the way promoters describe.",
],
"sections": [
("Boats Face the Entertainment Facility Rule", [
"IRC Sec. 274(a)(1)(B) disallows any deduction for a facility used in connection with entertainment, amusement, or recreation. A boat is the textbook example, and the disallowance applies even if the use was primarily for business.",
"That means a boat used to entertain clients is not deductible. Not partially, not with substantiation. The facility rule is a flat disallowance.",
"Boats can be deductible where they are not entertainment facilities. A boat used as genuine transportation between business locations, a boat that is inventory in a dealership, a boat chartered out as a trade or business, or a working vessel used in a commercial operation are all outside the entertainment facility rule.",
"A charter operation is the structure most often attempted. It requires the boat to be genuinely held for the production of income, actively marketed, and operated as a business rather than as personal use with occasional charters.",
"Where a charter operation is real, the passive activity rules under IRC Sec. 469 then apply, and the hobby loss rules under IRC Sec. 183 apply if the activity lacks a profit motive. Charter operations that lose money every year while the owner uses the boat personally are the fact pattern the IRS looks for.",
]),
("Aircraft Are Deductible With Real Business Use", [
"Aircraft are not entertainment facilities when used for transportation. Business travel by private aircraft is deductible in the same way any business transportation is.",
"The obstacles are three: substantiation, personal use allocation, and the passive activity rules.",
"IRC Sec. 274(d) requires strict substantiation for listed property, and aircraft are listed property under IRC Sec. 280F(d)(4). Records must establish the amount, time, place, and business purpose of each flight. A flight log with passenger names, destinations, and business purpose is the minimum.",
"Personal use is not deductible and must be allocated out. Where an employee or owner uses the aircraft for personal travel, the value is generally income to them under the SIFL rules or must be reimbursed.",
"Under IRC Sec. 274(e)(2), deductions for entertainment flights provided to specified individuals are limited to the amount included in that person's income, which for a heavily used aircraft can disallow a substantial portion of the cost.",
]),
("The Bonus Depreciation Question", [
"Aircraft used more than 50% for qualified business use are eligible for bonus depreciation under IRC Sec. 168(k) and generally use a five or seven year recovery period depending on use.",
"This is the source of the promotion. A $4,000,000 aircraft placed in service with qualifying business use can produce a $4,000,000 first-year deduction.",
"The 50% qualified business use test under IRC Sec. 280F is where most fail. Qualified business use excludes leasing to a 5% owner or related party, and certain use by employees is treated carefully. Falling below 50% requires the taxpayer to switch to the alternative depreciation system and recapture prior accelerated depreciation.",
"That recapture is the expensive failure mode. An owner who took $4,000,000 in year one and drops below 50% business use in year three recaptures the excess depreciation as ordinary income.",
]),
("The Passive Activity Trap", [
"Many aircraft are held in a separate entity that leases the aircraft to the owner's operating business or to a management company.",
"Leasing is a rental activity under IRC Sec. 469. Under Treasury Regulation Sec. 1.469-1T(e)(3)(ii), the average period of customer use test matters: where the average use period is seven days or less, or thirty days or less with significant services, the activity is not a rental.",
"Where the aircraft entity is a rental activity and the owner does not materially participate, the loss is passive and suspends. A $4,000,000 bonus depreciation deduction sitting suspended is worth nothing currently.",
"The self-rental rules under Treasury Regulation Sec. 1.469-2(f)(6) compound this, since net rental income from property leased to a business you materially participate in is recharacterized as non-passive while a net loss generally is not.",
"A grouping election under Treasury Regulation Sec. 1.469-4 is frequently the answer, but it must be evaluated and made properly. This is the single most common failure in aircraft structures, and it is entirely avoidable with planning before acquisition.",
]),
("What Actually Survives Examination", [
"A flight log maintained contemporaneously, recording date, aircraft, departure and destination, passengers, and specific business purpose for each leg.",
"A defensible allocation between business and personal use, with personal use either reimbursed at appropriate rates or included in income.",
"An entity structure that addresses the passive activity rules deliberately, with any grouping election made on a timely filed return.",
"Genuine business use that a reasonable person would recognize. An aircraft flown 90 hours a year, mostly to vacation destinations, with a business purpose noted for each flight, is not going to hold up regardless of the log quality.",
"Federal Aviation Administration compliance is a separate but related issue. Certain leasing structures raise operational control questions under Part 91 that can create regulatory exposure independent of the tax result, and the structure should be reviewed by aviation counsel as well as tax counsel.",
]),
("Worked Example: Aircraft Done Correctly", [
"A business owner with operations in four states acquires a $3,200,000 aircraft. Prior year travel included 92 commercial trips to those locations.",
"The aircraft is held in an LLC that leases it to the operating company under a written agreement at market rates. The owner makes a grouping election under Treasury Regulation Sec. 1.469-4 treating the aircraft leasing activity and the operating business as a single activity, filed with a timely return.",
"Flight logs record 118 hours in year one, of which 104 hours are documented business trips with passenger names and specific business purposes. The 14 personal hours are valued under SIFL and included in the owner's income.",
"Qualified business use is 88%, well above the 50% threshold under IRC Sec. 280F, so bonus depreciation applies.",
"The $3,200,000 deduction offsets operating business income because the grouping election makes the loss non-passive.",
"The structure works because the business use is real, the documentation is contemporaneous, the personal use is handled, and the passive activity question was addressed before acquisition rather than after.",
]),
],
"faqs": [
("Can I deduct a boat used to entertain clients?",
 "No. IRC Sec. 274(a)(1)(B) disallows any deduction for a facility used in connection with entertainment, amusement, or recreation, and a boat is the textbook example. The disallowance applies regardless of how much business was conducted aboard."),
("Is there any way to deduct a boat?",
 "Only where it is not an entertainment facility: genuine transportation between business locations, dealer inventory, a real charter operation, or a working commercial vessel. A charter operation must be actively marketed and operated as a business, and it faces the hobby loss rules under IRC Sec. 183."),
("Can I take bonus depreciation on an aircraft?",
 "Yes, if qualified business use exceeds 50% under IRC Sec. 280F. Falling below 50% in a later year requires switching to the alternative depreciation system and recapturing prior accelerated depreciation as ordinary income, which is the expensive failure mode."),
("Why is my aircraft deduction suspended?",
 "Most likely the passive activity rules. Aircraft held in a separate leasing entity are often a rental activity under IRC Sec. 469, and without material participation the loss suspends. A grouping election under Treas. Reg. Sec. 1.469-4 is usually the answer and must be made on a timely return."),
("What documentation do I need for aircraft?",
 "Contemporaneous flight logs recording date, aircraft, departure and destination, passengers, and specific business purpose for each leg, as required for listed property under IRC Sec. 274(d). Personal use must be allocated out and either reimbursed or included in income."),
],
"related": [
("/blog/how-to-write-off-a-vehicle-through-your-business/", "Writing off a vehicle through your business"),
("/blog/personal-expenses-through-business-irs-risk/", "Personal expenses through a business"),
("/blog/grouping-elections-real-estate-irc-469/", "Grouping elections under IRC Sec. 469"),
],
"cta_head": "The Structure Has to Be Right Before You Buy",
"cta_body": "Most aircraft deductions fail on the passive activity question, which is fixable in advance and difficult afterward. Bring your travel history and acquisition plan.",
},
]

if __name__ == "__main__":
    write_all(ARTICLES)
