import json,sys,re,html
from pathlib import Path
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R));import site_template as T
D='2026-10-08';S=T.SITE
# Each record has a verified profile and an original evaluation scenario, not a claimed client result.
rows=[
('gamburg-cpa','Gamburg CPA','https://www.gamburgcpa.com/','Advertises individual and business tax services, international accounting and tax planning.','An owner with a U.S. company and foreign interests needs a clear boundary between domestic planning and cross-border compliance.','Confirm which foreign reporting, treaty analysis and state returns are included and which require a specialist.','Foreign entity ownership, country-by-country income and prior information returns.','International reporting support'),
('brook-bay-consulting','Brook Bay Consulting','https://brookbayconsulting.com/','Pittsburgh practice describing bookkeeping, business tax planning, preparation and plan implementation.','A Pittsburgh owner wants planning recommendations translated into updated books and actual tax filings.','Ask whether the proposal covers bookkeeping corrections, the implementation calendar and coordination of business and owner returns.','Current ledger, prior returns and a list of transactions awaiting classification.','Local bookkeeping and planning coordination'),
('tys-advisors','TYS Advisors','https://tysllp.com/','Describes tax preparation, planning, transaction structuring and accounting services, with construction industry coverage.','A construction owner has uneven project cash flow and wants forecasts that reflect the project pipeline.','Ask how job information reaches the tax forecast and who reviews major contracts before execution.','Job schedules, receivables, work in progress and equipment acquisition plans.','Construction business forecasting'),
('kathy-l-hess-associates','Kathy L. Hess & Associates','https://www.klhesscpa.com/','Pittsburgh South Hills practice advertising tax strategy, compliance, audit support, accounting and bookkeeping.','An established Pittsburgh family business wants tax planning connected to the owner’s personal financial goals.','Request a proposal separating business planning, estate-related coordination, bookkeeping and annual preparation.','Business and household income, ownership records and existing estate adviser contacts.','Pittsburgh business and personal coordination'),
('duane-morris-tax-accounting-group','Duane Morris Tax Accounting Group','https://www.duanemorris.com/site/taxaccounting.html','Law-firm-affiliated group providing tax compliance, planning, accounting, management advisory and litigation consulting.','An owner needs both tax analysis and help with a transaction or dispute involving legal counsel.','Confirm the engagement’s tax, legal and litigation components, billing responsibilities and professional relationships.','Transaction documents, counsel’s issue list, financial statements and filing history.','Tax work involving legal or litigation support'),
('apex-cpas-consultants','Apex CPAs & Consultants','https://apexcpas.com/2026/03/tax-planning-for-business-owners/','Describes business tax planning involving financial review, entity structure, compensation, investment and succession.','A growing company wants a tax model for expansion rather than a forecast based only on last year’s profit.','Ask for modeled growth scenarios, decision deadlines and the assumptions used to compare owner compensation choices.','Hiring budget, financing terms, current payroll and expansion projections.','Growth and succession planning'),
('pnc-cpa-advisors','PNC CPA and Advisors','https://pncpafirm.com/services/proactive-tax-planning/','Describes proactive tax planning, complex returns, IRS representation and part-time CFO services.','An owner wants to address historical filing issues while evaluating equipment purchases and retirement planning.','Identify which work resolves past compliance and which work plans future decisions; request separate responsibilities and fees.','Notices, filed returns, payment records and expected major purchases.','Compliance cleanup and prospective planning'),
('hacker-johnson-smith','Hacker, Johnson & Smith','https://hackerjohnson.com/','Florida firm advertising independent audit and tax services, including banking, insurance, manufacturing and nonprofit work.','A manufacturing company needs both tax planning and financial reporting acceptable to a lender.','Separate tax advice from audit or attest work and confirm the required independence and reporting standards.','Lender requirements, financial statements, inventory records and existing audit reports.','Financial reporting and industry tax support'),
('pasquesi-partners','Pasquesi Partners','https://pasquesipartners.com/','Chicago practice offering business and individual tax services, planning, bookkeeping, payroll and fractional CFO support.','A professional services firm wants tax advice tied to project profitability and partner compensation.','Ask whether the ongoing accounting service includes tax forecasts, partner-level analysis and a written action plan.','Partner agreements, compensation records, project margins and current monthly reporting.','Professional services accounting and planning'),
('carpenter-evert-associates','Carpenter, Evert & Associates','https://www.carpenterevert.com/','Bloomington practice describing tax preparation, strategic planning, audit, accounting and business advisory services.','A small business needs better monthly information before evaluating a tax strategy or financing decision.','Ask how the proposal connects bookkeeping, financial analysis, tax planning and any lender reporting.','Reconciled accounts, loan covenants, current budget and prior financial statements.','Accounting foundations and business advisory'),
('warren-averett','Warren Averett','https://warrenaverett.com/insights/the-principles-of-proactive-tax-planning-five-considerations-for-business-owners/','Publishes business owner guidance emphasizing proactive tax planning and ongoing business decisions.','An owner considering a larger advisory firm wants one accountable team across multiple business needs.','Confirm the assigned tax team, specialty handoffs, communication schedule and engagement covering each business.','Entity chart, states of operation, adviser roster and upcoming transactions.','Coordinating a broader advisory team'),
('compound-wealth-tax','Compound Wealth & Tax','https://www.compoundwealthtax.com/','Wisconsin firm describing integrated tax and wealth planning for owners, high-net-worth families and real estate investors.','An owner approaching a liquidity event wants tax analysis coordinated with existing investment advice.','Ask which entity provides each service, how tax fees differ from investment fees and whether retaining your investment adviser is possible.','Ownership basis records, expected sale terms and current investment adviser arrangements.','Integrated tax and wealth decisions'),
('aligned-cpa','Aligned CPA','https://alignedcpa.com/blog/tax-planning-for-business-owners/','Publishes business owner tax planning guidance that connects tax strategy with longer-term business goals.','An owner wants to avoid choosing a short-term deduction that works against cash reserves and long-term growth.','Ask for an after-fee, after-tax projection showing the effect on cash and future years, not just current deductions.','Cash reserves, growth budget, debt commitments and annual income projections.','Long-term business tax planning'),
('oak-city-accounting','Oak City Accounting','https://oakcityaccounting.com/tax-planning','Raleigh practice advertising planning packages, projections, entity reviews and preparation for small businesses and individuals.','A medical practice owner compares a recurring planning package with a defined advisory project.','Specify the number of projections, meetings, business returns and personal returns, plus renewal and complexity charges.','Practice profit forecasts, owner payroll, state filings and existing retirement plan details.','Recurring planning package evaluation'),
('dkk-accounting','DKK Accounting','https://www.dkkaccounting.com/services','Offers bookkeeping, consulting, tax preparation and tax projections updated with financials, plus educational products.','An owner uses online tax tools but needs someone to reconcile the numbers and implement a recommendation.','Distinguish courses and stand-alone reports from a professional engagement covering personalized planning and filings.','Bookkeeping exports, owner salary records, reports already purchased and prior returns.','Bookkeeping-driven tax projections'),
('david-m-florijan-cpa','David M. Florijan CPA','https://www.davidmflorijancpa.com/','Glenshaw practice describing small business tax services, planning, payroll and Pittsburgh North Hills coverage.','A North Hills owner wants to keep personal attention while adding structured planning for a growing business.','Ask who reviews your file, how current-year changes are handled and whether planning meetings have defined deliverables.','Business returns, payroll totals, household income changes and questions for the next meeting.','North Hills business owner service'),
('davis-davis-associates','Davis, Davis & Associates','https://www.ddacpas.com/','Pittsburgh practice offering business accounting, tax preparation and planning, with healthcare, real estate and restaurant coverage.','A restaurant owner needs tax planning grounded in reliable payroll, sales and operating cost records.','Confirm whether the proposal covers industry bookkeeping, year-end planning and owner returns together.','Sales reconciliations, payroll summaries, equipment records and entity ownership.','Pittsburgh industry-specific accounting'),
('ltax-consulting','LTax Consulting','https://ltaxconsulting.com/','Describes a boutique consulting approach to tax preparation and planning, personalized communication and actionable recommendations.','An owner with business and investment income wants a documented plan rather than disconnected filing advice.','Request the exact written recommendations, review dates, implementation responsibilities and scope of investment coordination.','Business profit projections, investment tax statements and expected changes in household income.','Personalized tax preparation and planning'),
('revonary','Revonary','https://www.revonary.com/','Provides tax planning, accounting and consulting under an alternative practice structure, serving businesses, individuals and family offices.','A business owner with trust or family office needs wants clarity about which professional entity is responsible for each service.','Identify the contracting entity for tax, consulting and any attest work and confirm how information moves between teams.','Trust documents, entity chart, reporting requirements and existing professional engagements.','Family and business reporting coordination'),
('vital-wealth','Vital Wealth','https://www.vitalwealth.com/our-services/tax-strategy/','Describes tax strategy for entrepreneurs earning $1 million or more, including entity, investment, income and exit coordination.','A seven-figure entrepreneur wants to model a future sale while retaining existing CPA and legal advisers.','Ask who prepares returns, who gives investment advice and how the proposed strategy reaches your CPA and attorney.','Sale timeline, capital structure, adviser contacts and income forecasts.','Entrepreneur exit and investment coordination'),
('warner-tax-group','Warner Tax Group','https://www.warnercpa.com/taxservices.html','Ohio practice listing business and personal returns, bookkeeping, payroll, consulting and tax planning.','An Ohio business wants tax planning alongside payroll and state or city compliance.','Confirm which local filings and payroll services are included and whether planning is an ongoing service or a separate project.','Payroll records, city filing history, state returns and current accounting software details.','Ohio business compliance and planning'),
('sweeney-conrad','Sweeney Conrad','https://www.sweeneyconrad.com/what-we-do/tax-services','Describes closely held business and high-net-worth tax services, real estate planning, multistate and international work under an alternative practice structure.','A closely held company has real estate, owner equity compensation and multiple state obligations.','Request a lead adviser and a single plan coordinating business, owner, property and state work; identify each contracting entity.','Equity compensation details, property schedules, state activity and ownership records.','Closely held company complexity'),
('nelson-cpa','Nelson CPA','https://nelson.cpa/','Serves small business owners, professionals and real estate investors using S corporations and LLCs, including multistate and international activity.','An S corporation owner wants return preparation plus access to targeted consultations for new decisions.','Compare return preparation and hourly consultation scope with a separate written advisory project and confirm seasonal availability.','Recent entity and owner returns, payroll history and a prioritized consultation agenda.','S corporation and LLC return-led advice'),
('phillips-business-group','Phillips Business Group','https://phillipsbusinessgroup.com/','Markets strategic tax planning for entrepreneurs, with particular attention to women business owners and quarterly strategy sessions.','A seven-figure entrepreneur wants accessible strategy sessions backed by a documented implementation process.','Ask for individualized assumptions, substantiation requirements, deliverables and execution fees for each proposed strategy.','Business and personal returns, income forecasts, ownership and desired planning priorities.','Entrepreneur-focused strategy sessions'),
('bryan-sweeney-cpa','Bryan Sweeney, CPA','https://www.sweeneytax.com/taxplanning.php','Dallas practice describing proactive tax planning for businesses and individuals throughout the year.','A Dallas owner wants to turn periodic tax advice into a specific plan for business and household cash flow.','Ask which meetings, projections, return reviews and implementation tasks are included in the proposal.','Prior returns, projected business profit, household cash needs and planned transactions.','Dallas business and individual planning')]
assert len(rows)==25
fields=['slug','name','source','summary','scenario','question','documents','focus']
data=[dict(zip(fields,r)) for r in rows]
for f in data:
 pass
 f['fees']='A numeric fee for a comparable planning engagement was not verified in the sources reviewed for this guide. Request a current written quote directly. This does not mean the firm has no published pricing.'
 if f['slug']=='oak-city-accounting':f['fees']='The reviewed planning page lists a Professional Package starting at $6,000, expressed as $1,500 per quarter, with projections, two hours of personalized planning and tax preparation. Confirm the billing period, covered returns and complexity charges directly; this starting package is not equivalent to every advisory engagement.'
 if f['slug']=='nelson-cpa':f['price_source']='https://nelson.cpa/become-a-client/';f['fees']='The client intake page lists consultations generally at $275 to $350 per hour and describes providing a firm return-preparation price after reviewing prior returns. Those hourly consultation rates are not a quote for a complete multi-entity planning engagement. Confirm availability and current rates.'
 if f['slug']=='dkk-accounting':f['fees']='The service page offers educational products and stand-alone reports, including a reasonable compensation report listed at $397. Product prices are not a quote for a full professional tax planning engagement. Request separate pricing for bookkeeping, individualized planning and return preparation.'
E=html.escape
def p(x):return '<p>'+E(x)+'</p>'
def ul(xs):return '<ul>'+''.join('<li>'+E(x)+'</li>' for x in xs)+'</ul>'
def section(h,b):return T.section(h,b)
AE='AE publishes standard advisory pricing of $7,800, payable in two $3,900 installments 30 days apart. Returns, amendments, cost segregation and additional services are separately scoped and priced. The standard engagement has no required annual planning renewal; it does not include unlimited future planning. Confirm current terms in the signed proposal.'
paths=[]
def save(path,title,desc,body,f=None,extra=[]):
 sources=[f['source']] if f else [];sources+=([f['price_source']] if f and f.get('price_source') else []);sources+=[S+'/pricing/']
 schemas=[T.article_schema(title=title,description=desc,url=S+path,published=D,modified=D,section='Tax Advisor Comparison',citations=sources),T.breadcrumb_schema([('Home','/'),('Compare','/compare/'),(title,path)])]
 body=T.page_header(h1=E(title),subtitle=E(desc),trail=[('Home','/'),('Compare','/compare/'),(E(title),path)])+body
 T.write_page(path,T.build_page(title=title,description=desc,path=path,body=body,schemas=schemas,published=D,modified=D,active_nav='/compare/'))
 paths.append(path)
def related(f):
 base='/compare/'+f['slug'];return '<ul>'+''.join('<li><a href="'+base+s+'/">'+E(f['name']+label)+'</a></li>' for s,label in [('-vs-ae-tax',' vs AE'),('-pricing',' pricing'),('-alternatives',' alternatives')])+'<li><a href="/compare/business-tax-advisor-shortlist/">Business tax advisor shortlist</a></li><li><a href="/blog/six-figure-tax-bill-second-opinion/">Six-figure tax bill second opinions</a></li></ul>'
def tail(f):
 src='<p>Official materials reviewed October 8, 2026: <a rel="external noopener" href="'+E(f['source'],quote=True)+'">'+E(f['name'])+' official source</a>'
 if f.get('price_source'):src+='; <a href="'+E(f['price_source'])+'">official consultation pricing</a>'
 src+='; <a href="/pricing/">AE pricing</a>.</p>'
 return section('Related guides',related(f))+section('Sources and editorial disclosure',src+p('Published by AE Tax Advisors, a competing provider. This guide is not an independent ranking or customer review and is not affiliated with or endorsed by the named firm. Service summaries reflect the linked marketing materials; unconfirmed details are questions to resolve, not evidence of missing services. The scenarios are illustrative evaluation examples, not client results.'))+section('See whether AE fits your business',p('Tell our team your entities, tax years, states, properties and desired outcome. Ask for the responsible professionals, a defined scope and the complete project price. Savings and refunds depend on individual facts and are not guaranteed.')+'<p><a class="btn-cta btn-lg" href="/discovery/">Book a discovery call</a></p>')
def table(rows,headers):
 return '<div style="overflow-x:auto"><table><thead><tr>'+''.join('<th scope="col">'+E(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr><th scope="row">'+E(r[0])+'</th>'+''.join('<td>'+E(c)+'</td>' for c in r[1:])+'</tr>' for r in rows)+'</tbody></table></div>'
for f in data:
 n=f['name'];slug=f['slug'];base='/compare/'+slug
 body=section('Which engagement fits your business?',p('Comparing '+n+' with AE Tax Advisors starts with the work your business needs completed. '+f['scenario'])+p('A profitable business can have a large tax bill without having overpaid. Evaluate the quality of the review, the written recommendations and the cost of acting on them before choosing a provider.'))
 body+=section(n+': public service overview',p(f['summary'])+p('Your first conversation should establish fit for '+f['focus'].lower()+'. '+f['question']))
 body+=section('Side-by-side scope comparison',table([('Public focus',f['focus'],'Business owner and real estate tax planning; confirm fit for your project.'),('Planning deliverable',f['question'],'Confirm written findings, modeled alternatives and covered implementation tasks.'),('Preparation and execution','Request the exact business, owner and state filings included.','Returns, amendments and studies separately scoped.'),('Price evidence','See the linked pricing guide for reviewed fee evidence and request a current proposal.','Standard advisory $7,800; confirm additional work and current terms.'),('Accountability','Confirm assigned professionals and handoffs.','Confirm the professional and deadline for each action in the engagement.')],['Decision',n,'AE Tax Advisors']))
 body+=section('An illustrative decision to put in both proposals',p(f['scenario'])+p('Ask both firms to show a baseline forecast and the effect of the proposed action using the same income, entity and timing assumptions. Separate current tax savings, refunds and timing benefits. Include professional and implementation fees. A recommendation should remain useful when the tax effect is smaller than initially hoped.')+p('Documents to organize: '+f['documents']))
 body+=section('When AE deserves consideration',p('Consider AE if you want a defined advisory engagement evaluating your business and owner-level tax position, with any preparation, amendments or property studies identified separately. '+f['question'])+p('The other firm may fit better when its relevant specialty, local access or ongoing accounting arrangement matches the work you need. Confirm specialty services directly with either provider; this comparison does not imply identical capabilities.')+p(AE))+tail(f)
 save(base+'-vs-ae-tax/',n+' vs AE Tax Advisors: Scope, Fees and Fit','Compare '+n+' with AE on '+f['focus'].lower()+', written deliverables, fees and implementation responsibilities.',body,f)
 body=section('What does '+n+' cost?',p(f['fees'])+p('The useful number is the total price for the same work on the same facts. A free consultation, hourly session, preparation fee or educational product is not interchangeable with a complete planning and implementation engagement.'))
 body+=section('What to include in your quote request',p('For '+f['focus'].lower()+', start with this issue: '+f['question'])+p('Illustrative buyer situation: '+f['scenario'])+p('Prepare: '+f['documents'])+ul(['Specify each legal entity, owner return, tax year and filing jurisdiction.','Define whether you need findings, a written plan, projected tax calculations or execution.','List bookkeeping corrections and information needed before the plan can be finalized.','Ask whether meetings, communication and revisions are included or billed separately.','Confirm the price for additional entities, amended returns and out-of-scope work.']))
 body+=section('Separate first-year and future costs',table([('Assessment','Is there a fee, and what does the assessment deliver?'),('Advisory','Is it a project, hourly consultation or recurring arrangement?'),('Implementation','Who performs each task, and what outside costs are expected?'),('Preparation','Which federal, state and owner filings are included?'),('Future years','What renews automatically, what is optional and how can it be cancelled?')],['Cost category','Question for the written proposal']))
 body+=section('Compare with AE published advisory fees',p(AE)+p('For a business with multiple entities, obtain a combined first-year proposal and an ongoing annual estimate from each firm. Do not compare one provider’s preparation-inclusive package to AE advisory alone. Do not assume a higher fee guarantees greater savings or that the smallest quoted fee provides the most useful scope.'))
 body+=section('Evaluate value without treating deductions as cash savings',p('Request an explanation of each recommendation’s assumptions, tax effect and practical requirements. A deduction reduces taxable income; it is not the same amount as tax saved. A timing benefit can reverse later. Include implementation spending and professional fees before assessing the expected net benefit.')+p('For this project, the deciding scope question is: '+f['question']))+tail(f)
 save(base+'-pricing/',n+' Pricing: Fees, Scope and Quote Questions','Evaluate '+n+' pricing for '+f['focus'].lower()+' with verified fee evidence and a written quote checklist.',body,f)
 body=section('Choose an alternative around the work you need',p('If you are considering alternatives to '+n+', first define the outcome. '+f['scenario'])+p('A second opinion, ongoing accounting arrangement and specialist transaction engagement solve different problems. Change providers only after establishing who will complete the work and how existing records will transfer.'))
 body+=section('What the current option publicly offers',p(f['summary'])+p('This makes '+f['focus'].lower()+' a relevant issue to investigate. The firm may remain a suitable option if its proposal answers your questions and its team meets your requirements.'))
 body+=section('Three practical alternatives',table([('AE Tax Advisors','Evaluate a defined business owner advisory project and separately scoped implementation.','Ask how business and owner-level planning will be coordinated and what execution costs are extra.'),('Your existing CPA plus planning','Useful when the preparer already knows your books and you need a more explicit planning process.','Request written forecasts, a decision calendar and responsibility for every action.'),('A relevant specialist','Useful for a defined need such as cross-border reporting, attest work, legal coordination or investment advice.','Verify qualifications, engagement boundaries and how the specialist coordinates with the return preparer.')],['Route','When to investigate','Scope question']))
 body+=section('An issue-specific shortlist test',p(f['question'])+p('Put that question at the top of the request you send to each shortlisted provider. Then compare the proposed professional, documents required, deliverable and completion date. A provider that identifies a limitation and arranges the right handoff may be a better fit than a broad promise without an accountable person.')+p('Bring the same evidence to every conversation: '+f['documents']))
 body+=section('If you decide to switch',ul(['Confirm who files any pending returns and handles existing notices.','Collect complete prior returns, workpapers available to you and depreciation schedules.','Authorize secure record transfer and confirm access to your accounting system.','Define the new firm’s review scope and the start date of its responsibility.','Check contract cancellation and renewal terms before ending the prior relationship.'])+p('Keep the engagement roles clear during transition. A new advisory firm does not automatically take responsibility for unfinished returns or representation matters.'))
 body+=section('AE as one option on your shortlist',p(AE)+p('Use AE’s discovery call to explain '+f['focus'].lower()+' and confirm whether our team is suited to the actual issue. The decision should follow the written scope and verified experience, rather than a ranking unsupported by your facts.'))+tail(f)
 save(base+'-alternatives/',n+' Alternatives: Business Owner Shortlist','Explore alternatives to '+n+' for '+f['focus'].lower()+': AE, your current CPA and issue-specific specialists.',body,f)
# One useful hub with all 25, linked from existing discovery surfaces.
hub='/compare/business-tax-advisor-shortlist/'
body=section('A shortlist organized around your business needs',p('These 25 firms provide relevant publicly described tax or accounting services. This is an AE-published shopping guide, not an independent ranking. Use the linked comparisons to assess scope, use pricing guides to request matching quotes, and use alternatives guides to decide whether you need a new adviser or a specialist.')+p('Official materials reviewed October 8, 2026. Availability and contract terms must be confirmed directly.'))
for f in data:body+=section(f['name'],p(f['summary'])+p('Evaluation focus: '+f['focus']+'. '+f['question'])+related(f))
body+=section('Start with an AE discovery call','<p><a class="btn-cta" href="/discovery/">Discuss your business</a></p>')
save(hub,'Business Tax Advisor Shortlist: 25 Firms to Compare','Compare 25 business tax providers by planning needs, pricing scope and implementation. Find firm-specific comparisons and alternatives.',body)
for file in ['compare/index.html','compare/tax-planning-firms/index.html','pricing/index.html']:
 q=R/file;x=q.read_text();tag='<section class="content-section" id="expanded-firm-shortlist"><div class="container narrow"><h2>More business tax advisors to compare</h2><p>Explore 25 additional providers with firm-specific service comparisons, pricing questions and alternatives.</p><p><a href="'+hub+'">Browse the business tax advisor shortlist</a></p></div></section>'
 
 if 'expanded-firm-shortlist' not in x:x=x.replace('</main>',tag+'</main>');q.write_text(x)
xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join('<url><loc>'+S+u+'</loc><lastmod>'+D+'</lastmod></url>\n' for u in paths)+'</urlset>\n'
(R/'sitemap-competitors-expanded.xml').write_text(xml)
for file in ['sitemap-index.xml','sitemap_index.xml']:
 q=R/file;x=q.read_text();x=re.sub(r'<sitemap><loc>https://www.aetaxadvisors.com/sitemap-competitors-expanded.xml</loc>.*?</sitemap>\s*','',x);x=x.replace('</sitemapindex>','<sitemap><loc>'+S+'/sitemap-competitors-expanded.xml</loc><lastmod>'+D+'</lastmod></sitemap>\n</sitemapindex>');q.write_text(x)
(R/'_gen/competitors-expanded-20261008.json').write_text(json.dumps({'date':D,'firms':data,'paths':paths},indent=2))
print(json.dumps({'competitors':len(data),'new_pages':len(paths),'paths':paths},indent=2))
