"""Public, anonymized editorial summaries; private source mapping stays outside Git."""
STORIES = [
 dict(slug='restaurant-owner-entity-retirement-roadmap', title='A Restaurant Owner Connects Entity Planning, Payroll and Retirement', cat='Business Owners', kind='Tax plan',
 context='A restaurant owner was planning business expansion while several family shareholders received income through the same operating structure. The planning question was how to coordinate compensation, expenses and retirement contributions as the business grew.',
 work='AE prepared a proposed roadmap covering location-level entities, compensation documentation, business-expense reimbursements, retirement planning and the treatment of new equipment. The plan connected the business structure with the owners’ personal tax returns rather than treating each return as a separate project.',
 moves=['Review the ownership and operating structure before adding another location.', 'Document compensation by each working shareholder’s role.', 'Coordinate reimbursable business expenses and retirement-plan design with payroll.'],
 status='The source documents a proposed tax plan. It does not establish that the restructuring was completed or that projected savings were realized.',
 next='Before selecting a retirement plan, obtain an employee census and model staff coverage, related-business rules and annual funding needs. The useful comparison is the total cost of the plan alongside the owners’ contribution capacity.',
 proof='Employee ages, compensation, ownership relationships, existing plan documents and a realistic annual funding budget.',
 value='A coordinated plan helps an expanding business choose an order of operations: structure, payroll, benefits and then capital spending.', ref='retirement'),
 dict(slug='business-owner-retirement-cash-flow-planning', title='A Business Owner Aligns Retirement Planning With Cash Flow', cat='Business Owners', kind='Tax plan',
 context='An S corporation owner had significant operating income and wanted to evaluate several planning channels together. Retirement contributions, family employment and an additional entity were all part of the discussion.',
 work='AE prepared a forward-looking plan considering compensation, retirement-plan options, expense reimbursements and equipment purchases. The work identified decisions that needed to be modeled together, including the cash left available to run the business.',
 moves=['Compare retirement contributions with the business’s available cash.', 'Review compensation and any family employment against actual duties.', 'Evaluate equipment purchases and proposed entity changes as separate investment decisions.'],
 status='These are documented planning recommendations. The records reviewed do not verify adopted plans, funded contributions or achieved tax savings.',
 next='Run a lower-profit-year stress test before adding a defined benefit or cash balance plan. Include any new employees and all related businesses in the coverage analysis, then ask an actuary to confirm feasible contributions.',
 proof='Employee census, ownership chart, current payroll, multiyear profit forecast and actuarial contribution estimates.',
 value='The strongest retirement strategy should support both long-term wealth building and the cash demands of the operating company.', ref='retirement'),
 dict(slug='professional-practice-entity-amendment-review', title='A Professional Practice Builds a Roadmap for Structure and Prior Returns', cat='Business Owners', kind='Tax plan',
 context='A growing professional practice needed to revisit its tax structure and review earlier business returns. The owner’s personal returns alone did not provide the full picture of compensation, depreciation and entity reporting.',
 work='AE prepared a plan addressing reimbursements, compensation and retirement design alongside a proposed additional corporation. It also identified the business returns and supporting schedules needed before any prior-year recovery could be quantified.',
 moves=['Request the filed entity returns, K-1s and depreciation schedules.', 'Review owner compensation and personally paid business expenses.', 'Model an additional corporation alongside the existing operating structure.'],
 status='The source plan identifies prior-year review as pending. No completed restructuring or refund is claimed in this story.',
 next='Model the entire life cycle of any additional corporation: services performed, fee support, state taxes, administration and the cost of eventually distributing earnings. A lower entity-level rate alone does not establish a lower total tax cost.',
 proof='Written service scope, support for intercompany charges, ownership details, state footprint and expected distributions.',
 value='The plan creates a practical sequence for gathering missing records before committing to a more complex structure.', ref='compensation'),
 dict(slug='dental-practice-business-rental-tax-roadmap', title='A Dental Practice Owner Coordinates Business and Rental Planning', cat='Business Owners', kind='Tax plan',
 context='A dental practice owner had both practice income and rental investments. The business and property decisions needed to be considered together, with attention to compensation, state elections and whether rental deductions could be used.',
 work='AE prepared a proposed roadmap covering an entity-level state tax election, business reimbursements, compensation and rental-property planning. The value of the review was the connection between the operating practice, rental holdings and the household return.',
 moves=['Evaluate available state tax elections using the entity’s actual facts.', 'Review compensation and properly documented business reimbursements.', 'Assess rental depreciation together with loss limitations.'],
 status='The available document is a tax plan with projections. This summary does not report completed elections or verified savings.',
 next='Build a property-by-property loss-usage model before ordering more depreciation studies. Confirm ownership, basis, at-risk amounts, participation and applicable state treatment so projected deductions are tied to the return where they can actually be used.',
 proof='Property depreciation schedules, ownership records, participation records and current-year federal and state projections.',
 value='Coordinating the practice and rentals helps prioritize the next decision by usable benefit rather than deduction size.', ref='passive'),
 dict(slug='new-s-corp-owner-implementation-roadmap', title='A New S Corporation Owner Turns an Election Into an Implementation Plan', cat='Business Owners', kind='Tax plan',
 context='A self-employed professional was transitioning into an S corporation. The election created a need to align payroll, books, business expenses and personal reporting.',
 work='AE’s plan addressed compensation, business reimbursements, retirement planning and possible prior-year deductions. It also requested formation and election records, bookkeeping access and insurance documentation before finalizing the related work.',
 moves=['Confirm the entity documents and IRS election acceptance.', 'Align compensation, payroll and bookkeeping.', 'Review prior-year insurance and expense records before recommending amendments.'],
 status='The plan documents the transition and recommended implementation steps. The review does not establish a completed refund or a final annual savings amount.',
 next='Create a recurring payroll and reimbursement calendar. Review shareholder health-insurance reporting with the preparer and reconcile distributions against wages before the next filing period.',
 proof='Election acceptance, payroll reports, premium statements, expense substantiation and a reconciled shareholder ledger.',
 value='An election works best when it becomes an operating process rather than a form filed once and forgotten.', ref='compensation'),
 dict(slug='rental-investor-loss-classification-review', title='A Rental Investor Reviews Loss Classification Before Accelerating Depreciation', cat='Real Estate Investors', kind='Tax plan',
 context='A household with substantial non-rental income also owned a short-term rental showing suspended losses. Accelerating depreciation would only be useful if the return could properly use the additional deduction.',
 work='AE prepared a proposed plan connecting rental participation documentation, cost segregation and the household’s broader tax position. The plan also considered records needed to support a separate business activity.',
 moves=['Review the rental activity’s classification and participation evidence.', 'Evaluate depreciation after identifying the loss limitations.', 'Keep business activity records separate from personal expenses.'],
 status='The source describes proposed strategies. It does not verify that suspended losses were released, a study was completed or a refund was received.',
 next='Reconcile the rental’s stay-length records and actual work performed before changing its tax treatment. Test the basis, at-risk and passive-activity limits and model both a usable-deduction outcome and a carryforward outcome.',
 proof='Booking records, participation logs, contractor involvement, basis records and existing loss carryforwards.',
 value='The key planning question is where a deduction can be used, not simply how large a depreciation report can be.', ref='passive'),
 dict(slug='w2-household-tax-planning-before-new-investments', title='A W-2 Household Reviews Tax Planning Before Adding New Investments', cat='Business Owners', kind='Tax plan',
 context='A household whose reviewed tax profile was primarily wage income wanted a forward-looking tax plan. The starting point was the actual return history, rather than assuming a business or rental strategy was already available.',
 work='AE prepared a preliminary wage-income planning review and identified areas for additional documentation. The written profile distinguished the household’s current situation from opportunities that would depend on future facts.',
 moves=['Start with the income and deductions supported by filed returns.', 'Separate current opportunities from proposed future investments.', 'Confirm eligibility and documentation before committing capital.'],
 status='This story reflects a preliminary planning document. It does not claim an investment was purchased or a tax strategy was implemented.',
 next='Update withholding and estimated-payment projections using current pay statements, bonuses and investment income. Compare any proposed investment on its after-tax economics and liquidity, including the possibility that deductions will be carried forward.',
 proof='Current pay statements, withholding, investment income estimates and the proposed investment’s actual costs and operating assumptions.',
 value='A clear starting profile makes it easier to choose an appropriate next step and avoid paying for a structure the household does not need.', ref='payments'),
 dict(slug='trade-business-owner-rental-retirement-coordination', title='A Trade Business Owner Coordinates Payroll, Retirement and Rental Planning', cat='Business Owners', kind='Tax plan',
 context='A household combined wage income, an ownership interest in a trade business and a rental investment. Each activity had a different documentation and reporting path.',
 work='AE prepared a coordinated plan considering expense reimbursements, compensation, retirement contributions and rental depreciation. Prior-year work was described separately from the proposed current-year steps.',
 moves=['Review compensation for owners who perform services.', 'Match business reimbursements with documented expenses.', 'Connect rental depreciation with participation and loss-usage analysis.'],
 status='The plan describes recommendations and work in progress. The review does not verify final filings, completed benefit plans or realized savings.',
 next='Build one household projection that includes wages, pass-through income, retirement contributions and rental limitations. Use it to adjust tax payments as implementation decisions change during the year.',
 proof='Year-to-date payroll, business profit estimates, owner roles, plan documents and rental activity records.',
 value='One coordinated projection can prevent individually sensible decisions from producing an unexpected household tax bill.', ref='compensation'),
 dict(slug='multi-business-owner-property-planning-roadmap', title='A Multi-Business Owner Connects Property Studies With Entity Review', cat='Business Owners', kind='Tax plan',
 context='A household operated multiple businesses and held commercial property through a separate rental activity. The planning work needed to distinguish each entity’s income, expenses and ownership.',
 work='AE prepared a preliminary roadmap that included property cost segregation, entity review, compensation documentation and prior-return analysis. The plan requested source records before confirming the full effect of those recommendations.',
 moves=['Gather the returns and entity documents for each activity.', 'Scope property studies using purchase and improvement records.', 'Review compensation and reimbursement documentation separately for the relevant entities.'],
 status='The source explicitly treats the figures as preliminary and prior-year review as pending. This summary claims no completed recovery or quantified result.',
 next='Reconcile related-party rent, intercompany balances and expense allocation before applying depreciation changes. Each deduction should belong to the correct entity and activity, with a clear trail from the books to the return.',
 proof='Entity ownership chart, leases, intercompany ledgers, closing documents and reconciled financial statements.',
 value='A combined review helps the owner see which records are needed and which planning decision should come first.', ref='passive'),
 dict(slug='rental-owner-new-business-planning', title='A Rental Owner Plans a New Business Alongside Existing Property', cat='Real Estate Investors', kind='Tax plan',
 context='A rental owner was preparing to launch a separate active business. Property planning and the new venture needed distinct books, ownership decisions and tax projections.',
 work='AE prepared a preliminary plan considering entity structure, rental cost segregation, expense tracking, retirement options and earlier return review. The plan noted that complete tax documents were still needed to refine the recommendations.',
 moves=['Separate the new venture’s operating records from the rental activity.', 'Evaluate property depreciation using the actual purchase documents.', 'Review earlier returns before quantifying any recovery opportunity.'],
 status='The source is a preliminary strategy overview. No entity formation, study completion or realized savings are established by the records reviewed.',
 next='Prepare a start-up budget and distinguish pre-opening expenditures from ongoing operating costs. Model entity choice using expected profit, payroll and the rental’s separate tax treatment rather than assigning one structure to every activity.',
 proof='Ownership agreements, start-up receipts, operating forecasts, property records and prior returns.',
 value='Planning before launch gives the owner a chance to set up useful records before the first filing deadline arrives.', ref='payments'),
 dict(slug='investor-passive-loss-carryforward-review', title='An Investor Receives a Clearer View of Passive Loss Carryforwards', cat='Real Estate Investors', kind='Completed document review',
 context='An investor asked whether earlier returns had failed to use suspended investment losses. Multiple K-1s and several years of carryforwards made a year-by-year reconciliation important.',
 work='The documented review traced allowed losses and carryforwards across the available return copies. It found that those copies did not establish the alleged failure to offset passive income. It also distinguished an unfiled draft return from earlier filed-return years.',
 moves=['Trace carryforwards through each year’s passive-activity schedules.', 'Separate basis-limited, at-risk and passive losses.', 'Confirm whether a return is filed before treating it as an amendment candidate.'],
 status='A document review is recorded. It did not establish a specific amendment or refund from the available records, and it requested original supporting documents before further action.',
 next='Obtain the original K-1s and supporting basis, at-risk and activity worksheets. Recompute an earlier year only if a specific omitted deductible loss is substantiated, then roll any correction through subsequent years.',
 proof='Original K-1s, loss worksheets, disposition details, prior carryforward records and filing acceptance evidence.',
 value='A careful review can be useful even when it rules out an assumed refund. It gives the investor a clearer record of what remains to be checked.', ref='passive'),
 dict(slug='rental-partnership-return-coordination', title='A Rental Partnership Connects Entity Reporting With Owner K-1s', cat='Real Estate Investors', kind='Engagement scope',
 context='A rental partnership engaged AE for partnership reporting and owner K-1 preparation. The entity return and the owners’ individual returns needed a consistent set of property and ownership records.',
 work='The engagement record documents federal and state partnership-return preparation and member K-1s. That scope provides a clear reporting assignment without implying that a separate advisory or depreciation project has already been performed.',
 moves=['Prepare the partnership return from reconciled property records.', 'Coordinate K-1 delivery with the owners’ filing needs.', 'Keep the federal and state reporting responsibilities explicit.'],
 status='The available source confirms the engagement scope. It does not establish completed filing acceptance or a tax-savings result.',
 next='Reconcile partner contributions, distributions and debt allocations before finalizing the K-1 package. Provide the owners with the records needed for their separate basis and loss-limit reviews.',
 proof='Partnership agreement, ownership changes, contribution and distribution ledgers, debt schedules and prior K-1s.',
 value='A clear entity-to-owner handoff helps partnership preparation support the personal return rather than end at the K-1.', ref='passive'),
 dict(slug='rental-conversion-study-and-return-planning', title='A Property Owner Coordinates Rental Conversion, Cost Segregation and Filing', cat='Real Estate Investors', kind='Engagement scope',
 context='A property owner’s engagement combined a cost segregation study, individual-return preparation and rental-conversion analysis. The planning decision required more than the property’s purchase price.',
 work='The documented scope brings property analysis and tax-return preparation into the same engagement. It also distinguishes a possible K-1 add-on from the core work, giving the owner a clearer picture of the reporting assignment.',
 moves=['Review the property’s conversion and placed-in-service facts.', 'Coordinate the study inputs with the individual return.', 'Confirm whether any entity K-1 creates additional reporting work.'],
 status='The source confirms contracted work, not a completed depreciation study or filed tax benefit.',
 next='Document the conversion date, personal-use history and records needed to establish depreciable basis. Review the activity classification and loss limitations before projecting the benefit of accelerated depreciation.',
 proof='Purchase and conversion records, supporting valuation where required, booking history, personal-use days and depreciation schedules.',
 value='Reviewing conversion facts early helps keep the study and the return aligned on the same starting assumptions.', ref='passive'),
 dict(slug='rental-owner-entity-and-participation-review', title='A Rental Owner Evaluates Entity Changes Alongside Participation Rules', cat='Real Estate Investors', kind='Engagement scope',
 context='A rental owner engaged AE for entity restructuring, real estate professional analysis and earlier-return review. Those decisions needed to be evaluated separately before being combined into one plan.',
 work='The engagement record identifies proposed entity changes, qualification analysis and amendment analysis. It gives each workstream a place in the project rather than assuming that forming an entity settles how rental losses will be treated.',
 moves=['Map property ownership and the proposed entity structure.', 'Evaluate real estate professional and participation facts.', 'Review earlier returns before choosing a correction method.'],
 status='The records confirm the advisory scope. They do not establish that the proposed restructuring or any amended returns were completed.',
 next='Compare the proposed structure with the existing ownership on a full federal and state basis. Review financing, transfer costs, distributions and exit plans with the legal and tax advisors before moving property.',
 proof='Ownership and loan documents, participation records, prior returns, state filings and the intended holding period.',
 value='Separating ownership, participation and amendment decisions helps the owner understand what each part of the engagement can accomplish.', ref='passive'),
 dict(slug='equipment-leasing-entity-return-roadmap', title='An Equipment Leasing Owner Connects Entity Setup With Return Preparation', cat='Business Owners', kind='Engagement scope',
 context='An owner engaged AE for an equipment leasing entity and future business and personal returns. Entity setup and asset reporting needed to stay connected from the beginning.',
 work='The tracker documents an equipment leasing entity-formation scope and related return preparation, with onboarding marked complete. That establishes the assigned work without claiming that the equipment was purchased or a depreciation deduction was allowed.',
 moves=['Align the entity setup with the business and personal reporting scope.', 'Collect equipment and financing records before depreciation is prepared.', 'Keep lease activity records distinct from personal expenses.'],
 status='Onboarding is recorded as complete. The source does not verify entity formation, equipment delivery, return filing or tax savings.',
 next='Prepare an asset and lease register showing ownership, financing, business use and placed-in-service evidence. Model cash flow, depreciation and the effect of a later sale before buying equipment primarily for a deduction.',
 proof='Invoices, executed leases, delivery records, financing documents, usage records and an operating forecast.',
 value='Connecting setup and filing responsibilities helps an owner build the records needed for a coherent first-year return.', ref='depreciation'),
 dict(slug='mixed-use-rental-property-study-coordination', title='A Property Owner Separates Rental and Personal Use Before Study Work', cat='Real Estate Investors', kind='Engagement scope',
 context='A property owner’s engagement included rental properties and a rented portion of a primary residence. The scope combined property studies with earlier-year and current-year return work.',
 work='The engagement record identifies cost segregation work across the properties, amendment work and return preparation. The rented portion of the residence requires its own allocation rather than treating the entire home as rental property.',
 moves=['Separate personal and rental portions in the property records.', 'Coordinate study inputs with the applicable return years.', 'Review prior depreciation before determining what needs correction.'],
 status='The reviewed source documents contracted scope. It does not establish completed studies, filed amendments or realized refunds.',
 next='Create a consistent allocation schedule for basis, improvements, expenses and use. Review personal-use days and existing depreciation so the return preparer and study team use the same rental portion.',
 proof='Floor plans or allocation support, improvement invoices, rental records, personal-use history and prior depreciation schedules.',
 value='A shared allocation record can make multiple property projects easier to coordinate without overstating the rental deduction.', ref='depreciation'),
]
