"""Add 147 disclosed educational examples without inventing client outcomes."""
import sys, re, json, html
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
import site_template as T
ROOT=T.ROOT
DATE='2026-10-06'
# Persona, operating facts, concrete records and the central business constraint.
PROFILES=[
('HVAC Company Owner',650000,'service technicians, installation crews and seasonal equipment purchases','job-cost reports, truck logs and installation invoices','Keep enough working capital for the next cooling season.'),
('Plumbing Company Owner',450000,'emergency service calls, contractor payments and a growing dispatch team','dispatch records, subcontractor agreements and materials ledgers','Separate owner labor from the margin produced by the field team.'),
('Electrical Contractor',800000,'commercial projects, milestone billing and retainage','project schedules, retainage aging and equipment purchase records','Taxable profit and collected cash may move at different speeds.'),
('Roofing Company Owner',1100000,'storm-driven demand, deposits and subcontracted installation','contract files, deposit reconciliations and subcontractor payment histories','Avoid committing reserves needed to finish contracted jobs.'),
('General Contractor',1400000,'multiple projects, progress payments and owner guarantees','job-level profit reports, loan guarantees and work-in-progress schedules','A profitable contract does not guarantee that cash is available today.'),
('Landscaping Company Owner',350000,'recurring maintenance contracts and seasonal labor','customer contracts, seasonal payroll and mower asset schedules','Match year-end spending to the equipment actually needed next season.'),
('Dental Practice Owner',900000,'clinical production, associate compensation and practice equipment','provider production reports, associate agreements and equipment invoices','The owner needs both clinical staffing capacity and reliable personal cash flow.'),
('Veterinary Practice Owner',550000,'patient care, inventory and diagnostic equipment','inventory counts, staff census and diagnostic equipment invoices','Keep inventory and employee commitments visible before selecting deductions.'),
('Medical Practice Owner',1200000,'provider compensation, insurance reimbursements and a support team','payer aging, provider contracts and employee benefit documents','Collections may lag services, making a cash forecast essential.'),
('Marketing Agency Owner',500000,'retainers, campaign delivery and contractor support','client retainers, campaign cost reports and contractor invoices','Separate client pass-through spending from agency earnings.'),
('IT Services Company Owner',750000,'managed service contracts, technicians and recurring software costs','service agreements, software contracts and technician payroll','Recurring revenue should fund reserves before discretionary planning commitments.'),
('Ecommerce Business Owner',1000000,'inventory, marketplace settlements and fulfillment costs','inventory reconciliations, marketplace statements and freight records','Cash tied up in inventory is unavailable for tax payments or retirement funding.'),
('Manufacturing Company Owner',1600000,'production machinery, skilled labor and customer receivables','fixed-asset registers, production records and receivables aging','Equipment decisions must support production capacity as well as tax planning.'),
('Trucking Company Owner',700000,'fleet financing, driver payroll and maintenance spending','vehicle titles, finance schedules and maintenance logs','A depreciation deduction does not eliminate fleet loan payments.'),
('Multi-Location Salon Owner',400000,'stylist payroll, product sales and leased locations','location profit reports, stylist payroll and tenant improvement invoices','Location-level performance matters more than a consolidated revenue headline.'),
('Real Estate Brokerage Owner',1100000,'agent commissions, lead generation and broker supervision','commission statements, agent agreements and brokerage payroll','Gross commissions must be reconciled to the brokerage share before planning.'),
('Property Management Company Owner',600000,'management fees, staff operations and client trust accounts','management contracts, trust-account reconciliations and employee timesheets','Client funds are distinct from the company cash available for planning.'),
('Real Estate Agent With Rentals',350000,'commission income and separately held rental properties','commission statements, property ledgers and participation calendars','A professional license alone does not establish the tax treatment of rental losses.'),
('Real Estate Developer',1500000,'development inventory, construction financing and retained rentals','parcel schedules, construction draws and property-purpose records','Property held for sale must be distinguished from property held for investment.'),
('Short-Term Rental Operator',500000,'guest turnover, vendor coordination and an operating team','reservation exports, owner task logs and vendor work schedules','Short stays alone do not establish deductible nonpassive losses.'),
('Rental Portfolio Owner With a Service Business',850000,'a profitable operating business and separately tracked rental assets','entity returns, property depreciation schedules and ownership records','Business earnings and rental deductions must be tested together without ignoring activity limits.'),
]
TOPICS=[
('compensation','Owner Pay and Entity Review','Compare the present tax classification with a payroll-supported alternative.','An S corporation must pay reasonable compensation for shareholder services before treating remaining payments as distributions. The analysis depends on duties, time and comparable work, rather than a preset wage percentage. A rental holding entity should not be changed merely because the operating business uses an S election.','Write a role description, establish a supported compensation range, then compare total tax and administrative cost.','An artificially low salary can create employment-tax exposure; an entity change can also introduce filing duties and ownership constraints.','https://www.irs.gov/businesses/small-businesses-self-employed/s-corporation-compensation-and-medical-insurance-issues','/s-corporation-tax-planning/'),
('retirement','Retirement Funding and Working Capital','Decide how much recurring cash can be committed to retirement funding.','Plan design must consider eligible employees, ownership relationships and compensation. A larger owner contribution is not automatically the best plan if employee funding or ongoing obligations strain operations. Defined benefit designs require specialist actuarial work; contribution capacity is not a fixed number attached to a profit level.','Obtain a complete employee census and compare a practical baseline plan with a more demanding design over several years.','A strong profit year does not establish sustainable funding. Related employers and employee eligibility can change the design substantially.','https://www.irs.gov/publications/p560','/retirement-tax-planning/'),
('assets','Equipment and Depreciation Decisions','Separate necessary asset investment from spending motivated only by a tax deduction.','An asset schedule should distinguish business use, acquisition date, service date and the applicable recovery rules. Land is not depreciable. Buying an asset and placing it in service are different events. Accelerated depreciation is a timing choice whose value depends on eligibility, available income, loss limitations and future disposition.','Reconcile existing assets before deciding whether to acquire additional equipment or commission a property classification study.','Debt service continues after a deduction. Personal use, asset sales, state differences and later recapture may change the economics.','https://www.irs.gov/publications/p946','/cost-segregation/'),
('reimbursements','Expense Reimbursement and Recordkeeping','Identify owner-paid business expenses that have not been consistently substantiated.','A corporate reimbursement arrangement needs a business connection, adequate substantiation and return of excess advances to qualify as an accountable plan. It does not turn personal spending into business spending. Mileage, travel and mixed-use expenses need their own records. The owner should not claim the same cost personally after the company reimburses it.','Create a monthly expense submission and approval process that ties receipts and business purposes to the company books.','Unsupported allowances, duplicated deductions and unrepaid advances can defeat the intended treatment. Expenses must relate to the relevant business.','https://www.irs.gov/publications/p463','/accountable-plan/'),
('rentals','Rental Losses and Participation Evidence','Evaluate an existing or proposed rental before assuming it will offset operating income.','Rental losses are generally subject to passive activity limitations. Real estate professional qualification and material participation are separate questions. A qualifying short-stay activity can fall outside the rental definition, but its participation facts still matter. Basis, at-risk and other applicable limits must be considered before calculating a current deduction.','Build an activity-by-activity evidence file and test participation before modeling the benefit of depreciation.','A management company, spouse participation, competing work hours and personal use can change the answer. A purchase alone does not establish loss deductibility.','https://www.irs.gov/publications/p925','/real-estate-professional-status/'),
('sale','Sale Preparation and Depreciation History','Prepare the tax file before selling a business asset or an investment property.','A sale analysis starts with the actual asset, ownership and adjusted basis. Depreciation can affect gain character and recapture. Investment real estate and business equipment do not share every deferral option. A headline sale price is not the amount the owner keeps after debt, transaction costs and taxes.','Create a basis reconciliation and ask the transaction advisers to review the proposed terms before signing a binding agreement.','A buyer allocation, related-party transaction, prior depreciation error or property held for sale may change the result. Tax planning should not override commercial terms.','https://www.irs.gov/publications/p544','/business-exit-tax-planning/'),
('review','Prior-Year Depreciation and Return Review','Determine whether an apparent missed deduction is a real filing correction opportunity.','The review must establish what was filed, what records support a different position and which correction procedure applies. A missed expense and an established depreciation method do not necessarily follow the same route. An amended return is not the automatic answer to every depreciation issue. The relevant tax year, refund deadline and activity limitations must be checked.','Compare filed returns with the original source documents, reconcile carryforwards and prepare a written correction recommendation.','A refund is not guaranteed. An adjustment can move other items, require entity-level coordination or be limited by the applicable filing window.','https://www.irs.gov/publications/p946','/amended-tax-returns/'),
]

def para(s): return '<p>'+html.escape(s)+'</p>'
def slug(s): return re.sub('[^a-z0-9]+','-',s.lower()).strip('-')
def main():
    indexpath=ROOT/'case-studies/index.html'; hub=indexpath.read_text()
    hub=re.sub(r'<!-- owner-expansion:start -->.*?<!-- owner-expansion:end -->','',hub,flags=re.S)
    cards=[]; entries=[]
    for persona,profit,facts,records,constraint in PROFILES:
      real=any(x in persona for x in ['Real Estate','Property Management','Rental'])
      cat='Real Estate Investors' if real else 'Business Owners'
      band='1mplus' if profit>=1000000 else '500to1m' if profit>=500000 else '250to500'
      for key,name,question,rule,action,risk,source,related in TOPICS:
        ident='planning-'+slug(persona)+'-'+key
        path='/case-studies/'+ident+'/'
        title=persona+': '+name
        desc='Tax planning case study for a '+persona.lower()+': '+question
        estate='yes' if real or key in ['rentals','sale'] else 'no'
        body=T.page_header(h1=title,subtitle=desc,trail=[('Home','/'),('Case Studies','/case-studies/'),('Case Study',path)],cta='Discuss My Business and Property Plan')
        sections=[
        ('The owner and the operating facts',para(f'The example concerns a {persona.lower()} with assumed annual operating profit of ${profit:,} before new planning actions. The business involves {facts}. This figure is not revenue, taxable household income or a guarantee of cash available for distribution.')+para(constraint+' The owner wants a coordinated review that connects the entity return, household return and any property activity. The first task is to establish a reliable baseline, rather than choosing a deduction from a list.')),
        ('The decision to resolve',para(question+' The starting file includes '+records+'. Those records should be reconciled to bank activity, filed returns and ownership documents. If the records disagree, the planning model should show the unresolved difference instead of treating it as an available deduction.')),
        ('The tax rule that controls the example',para(rule)+para('Federal treatment should be reviewed alongside the applicable state rules and the tax year being modeled. Dates, elections and the actual ownership arrangement can change the analysis. A planning illustration cannot establish eligibility for a taxpayer whose facts have not been reviewed.')),
        ('A practical review sequence',para(action)+para(f'For this {persona.lower()}, the adviser would first reconcile {records}. Next, the owner would identify the cash needed for current operations, tax payments and committed projects. Only then would the team compare the existing approach with a proposed change, using the same assumptions in both columns.')+para('The comparison should show the proposed deduction or income change, its current availability, implementation cost, cash commitment and any effect in later years. A strategy that lowers this year\'s tax while creating an unaffordable obligation should be revised or rejected.')),
        ('What could change the answer',para(risk)+para(constraint+' The owner should also identify missing returns, differences between book and tax balances, and work performed by outside advisers. Those issues can change the order of implementation even when a strategy appears suitable in isolation.')),
        ('Documents to bring to an advisory review',para('Bring the last filed business and personal returns, current profit and loss statement, balance sheet, ownership schedule and relevant payroll or property records. Include '+records+'. Where a proposed action involves another specialist, bring their written recommendation and the assumptions used to produce it.')+para('Identify who controls each decision, who keeps the supporting records and who will prepare the final filing. This prevents a discussion with one adviser from being mistaken for implementation by another.')),
        ('The proposed deliverable',para('The output of this example is a review plan, not a claimed refund. A useful advisory deliverable would document the eligibility decision, compare the cash and tax consequences, identify missing evidence, assign the next action and specify the relevant filing or implementation deadline.')+para('If the facts do not support the proposed treatment, the written plan should say so and show the baseline approach. If the strategy is supported, the owner still needs completed documentation and consistent reporting before claiming the intended treatment.')),
        ('Who this example is for',para(f'This example is intended for a {persona.lower()} with meaningful operating profit, records available for review and a decision involving both tax and business cash flow. It is particularly useful when separate preparers, payroll providers, bookkeepers or property advisers have not yet connected their work into one plan.')+para('Use the discovery call to explain your ownership, income sources, existing properties and the decision you need to make. AE can then clarify which advisory, preparation or property-study services fit the situation and what additional professional input is required.')),
        ]
        for heading,content in sections: body+=T.section(heading,content)
        body+=T.section('Sources and related reading',f'<p><a href="{source}" target="_blank" rel="noopener">IRS guidance supporting this planning topic</a>. Reviewed October 6, 2026. Apply the guidance for the relevant filing year.</p><p><a href="/case-studies/">Find more owner and real estate examples</a> · <a href="/discovery/">Discuss your planning needs</a></p>')
        siblings=[('/case-studies/planning-'+slug(persona)+'-'+t[0]+'/',persona+': '+t[1]) for t in TOPICS if t[0]!=key][:3]
        body+=T.related_section(siblings,'Other decisions for this owner profile')
        body+='<div class="container narrow"><p style="font-size:.85rem;color:var(--medium)">Educational case study. Facts and figures are illustrative and do not document a specific client’s results. Outcomes depend on individual circumstances.</p></div>'
        schema=[T.article_schema(title=title,description=desc,url=T.SITE+path,published=DATE,modified=DATE,section='Tax Planning Case Study')]
        page=T.build_page(title=title+' | AE Tax Advisors',description=desc,path=path,body=body,schemas=schema,published=DATE,modified=DATE,active_nav='/case-studies/')
        T.write_page(path,page)
        cards.append(f'<article class="cs-card" data-cat="{cat}" data-income="{band}" data-ownership="owner" data-estate="{estate}" data-text="{T.esc((title+" "+question).lower())}"><span class="cs-tag">{cat}</span><h3><a href="{path}">{T.esc(title)}</a></h3><div class="cs-profile-tags"><span>Assumed profit ${profit:,}</span><span>Business owner</span><span>{"Real estate decision" if estate=="yes" else "Operating business"}</span></div><p>{T.esc(question)}</p><a class="btn-secondary" href="{path}">Read the case study</a></article>')
        entries.append(dict(title=title,path=path,category=cat))
    assert len(entries)==147
    hub=hub.replace('<div class="cs-grid" id="cs-grid">','<div class="cs-grid" id="cs-grid">\n<!-- owner-expansion:start -->'+''.join(cards)+'<!-- owner-expansion:end -->',1)
    hub=hub.replace('All (103)','All (250)').replace('Real Estate Investors (45)','Real Estate Investors (87)').replace('Business Owners (54)','Business Owners (159)').replace('103 case studies','250 case studies and planning examples')
    hub=hub.replace('Illustrative planning scenarios are kept separate from this library\n            and are not presented as client outcomes.','New educational examples are individually labeled as illustrative, use hypothetical facts, and do not claim client outcomes.')
    hub=hub.replace('<strong>New: 28 anonymized planning stories.</strong>','<strong>250 case studies and planning examples, including 147 new owner-focused illustrations.</strong>')
    hub=hub.replace('Income means the published income or net profit figure, not business revenue or property value.','Income means the published income or net profit figure, not business revenue or property value. On illustrative examples, the card explicitly identifies assumed profit.')
    def upd(m):
      d=json.loads(m[1])
      if d.get('@type')=='CollectionPage':
        d['description']='250 tax planning case studies, anonymized planning stories and explicitly hypothetical examples for business owners and real estate professionals.';d['dateModified']=DATE
        items=d['mainEntity']['itemListElement'];items=[i for i in items if '/planning-' not in i.get('url','')]
        for e in entries: items.append({'@type':'ListItem','position':len(items)+1,'name':e['title'],'url':T.SITE+e['path']})
        d['mainEntity']['numberOfItems']=len(items);d['mainEntity']['itemListElement']=items
      return '<script type="application/ld+json">'+json.dumps(d)+'</script>'
    hub=re.sub(r'<script type="application/ld\+json">(.*?)</script>',upd,hub,flags=re.S)
    hub=re.sub(r'<title>.*?</title>','<title>250 Tax Planning Cases and Examples for Owners | AE Tax Advisors</title>',hub,count=1)
    indexpath.write_text(hub)
    sitemap=ROOT/'sitemap-case-studies.xml';xml=sitemap.read_text()
    for e in entries:
      if T.SITE+e['path'] not in xml: xml=xml.replace('</urlset>',f'<url><loc>{T.SITE+e["path"]}</loc><lastmod>{DATE}</lastmod></url>\n</urlset>')
    sitemap.write_text(xml)
    print('Added 147 illustrative pages; hub contains',hub.count('class="cs-card"'),'entries.')
if __name__=='__main__':main()
