"""Maintain the October 1 service-search release without creating duplicate URLs.

Run from the repository root. These overrides follow legacy page generators.
Fees come from /pricing/; do not invent outcome statistics or reviewer credentials.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from site_template import SITE, build_page, page_header, section, related_section, faq_section, faq_schema, breadcrumb_schema, article_schema

DATE = '2026-10-01'
P925 = 'https://www.irs.gov/publications/p925'
P527 = 'https://www.irs.gov/publications/p527'
P946 = 'https://www.irs.gov/publications/p946'
SALARY = 'https://www.irs.gov/businesses/small-businesses-self-employed/s-corporation-compensation-and-medical-insurance-issues'
RETIRE = 'https://www.irs.gov/retirement-plans/retirement-plans-for-self-employed-people'
ESTIMATES = 'https://www.irs.gov/businesses/small-businesses-self-employed/estimated-taxes'
F3115 = 'https://www.irs.gov/instructions/i3115'

def link(path, label):
    return f'<a href="{path}">{label}</a>'

def bullets(items):
    return '<ul>' + ''.join('<li>'+item+'</li>' for item in items) + '</ul>'

def table(headers, rows):
    return '<div style="overflow-x:auto"><table class="blog-table"><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'

def fee(scope='advisory'):
    if scope == 'study':
        return '<p>Published standard cost segregation pricing is <strong>$1 per square foot, with a $2,000 minimum per study</strong>. Complex work may be quoted separately. Advisory, Form 3115 preparation and tax returns require their own confirmed scope. '+link('/cost-segregation-study-cost-pricing/','Compare study pricing and deliverables')+'.</p>'
    return '<p>AE publishes <strong>$7,800 for Strategic Tax Advisory</strong> and <strong>$9,800 for Complex Tax Advisory</strong>. Strategic is one engagement paid in two installments of $3,900, 30 days apart, with no required recurring annual planning fee. Tax returns, amendments, cost segregation and additional work are separately scoped. Confirm the engagement, payment terms, properties, entities and filings before work begins. '+link('/pricing/','View published service fees')+'.</p>'

PAGES = {
'short-term-rental-tax-strategy': dict(
 title='Short-Term Rental Tax Planning & Advisory | AE Tax Advisors',
 h1='Short-Term Rental Tax Planning for Airbnb and VRBO Owners',
 desc='STR tax planning for Airbnb and VRBO owners. Coordinate participation records, depreciation, cost segregation and tax return scope with AE Tax Advisors.',
 intro='Connect the way you operate your short-term rental to a practical tax plan. Review guest stays, participation, property records and filing responsibilities before relying on a projected deduction.',
 sections=[
 ('Tax planning and preparation for short-term rental owners','<p>AE Tax Advisors helps property owners coordinate STR strategy with their wider business and real estate tax position. If you are searching for a short-term rental CPA or Airbnb tax accountant, compare who will analyze the activity, prepare the return and implement depreciation work. Those responsibilities should be explicit in the proposal.</p><p>This review is useful before buying or opening a property, changing management arrangements, completing a renovation, or filing a return that includes a new study. An existing owner may also need to reconcile prior depreciation or suspended losses.</p>'),
 ('Start with the rental operations', '<p>A platform listing does not determine federal tax treatment. Review actual booking history, guest services, owner stays and the work performed by the owner, spouse and other people. '+link(P527,'IRS Publication 527')+' explains rental reporting and personal-use considerations.</p>'+table(['Situation','Question to resolve'],[
 ('New Airbnb or VRBO purchase','When was the property ready and available for its intended use, and what costs belong in the asset schedule?'),
 ('Property managed by someone else','Who performs the work, and what evidence supports the owner’s participation?'),
 ('Owner uses the rental personally','How do personal-use days affect the rental analysis?'),
 ('Existing property with a new study','Does implementation require a method change, and who prepares the filing?')
 ])),
 ('Separate the seven-day rule from material participation','<p>For passive-activity purposes, average customer use of seven days or less is one exception to rental-activity treatment. It does not, by itself, establish material participation or make a loss deductible against other income. Evaluate the relevant participation test and other applicable limitations separately. See '+link(P925,'IRS Publication 925')+'.</p><p>Use '+link('/short-term-rental-tax-loophole-2026/','the STR seven-day rule guide')+' for the tax-rule discussion. For an engagement, prepare booking exports and a record of actual work rather than selecting a desired tax result first.</p>'),
 ('Coordinate cost segregation with the tax return','<p>A depreciation study belongs in the same file as the purchase documents, land allocation, furnishings and improvement history. Confirm which components are eligible, which tax-year rules apply, and whether additional deductions are currently usable. The study cannot answer the participation question.</p>'+fee('study')+'<p>Review '+link('/cost-segregation-airbnb/','Airbnb cost segregation')+', '+link('/cost-segregation-documents-checklist/','the property document checklist')+' and '+link('/form-3115-cost-segregation/','lookback implementation')+' before setting the scope.</p>'),
 ('What to confirm in an STR engagement','<p>Ask for a proposal that assigns the operational review, depreciation work, owner-level loss analysis, federal and state return preparation, and follow-up support. Identify each property and ownership entity. If another CPA files your return, establish how the analysis and asset schedule will reach that preparer.</p>'+fee()+'<p>See '+link('/bios/','the advisor team')+' and '+link('/compare/best-tax-advisors-short-term-rental-owners/','our disclosed STR advisor comparison')+' when evaluating service fit.</p>'),
 ('Prepare for the first call',bullets(['Property type, ownership entity, acquisition date and opening date.','Number of properties, states and upcoming purchases or sales.','Current tax preparer and whether a cost segregation report already exists.','Availability of booking exports, participation records and prior asset schedules.'])+'<p>The discovery call establishes fit and next steps. Detailed tax records should be exchanged through the agreed secure collection process after scope is established.</p>')],
 faqs=[('Do you help owners who use a property manager?','Yes, the planning discussion can include managed properties. Management arrangements affect the participation analysis; hiring a manager does not establish a particular tax outcome.'),('Is cost segregation included in advisory?','No. AE publishes cost segregation separately from tax advisory. Confirm report scope, implementation and return fees in writing.'),('Can short-term rental losses offset W-2 income?','That depends on the activity, participation and applicable loss limits. A short stay or depreciation study alone does not establish eligibility.'),('Can I keep my current CPA?','Confirm a coordination arrangement that names who performs each analysis, updates the asset schedule and files the return.'),('What should I bring to the discovery call?','Bring a summary of your properties, ownership, timing and current tax support. Use the agreed secure process for detailed tax documents.')],
 links=[('/cost-segregation-airbnb/','Cost segregation for Airbnb and STR properties'),('/real-estate-investor-cpa/','Tax support for a real estate portfolio'),('/pricing/','Advisory and preparation pricing')], sources=[(P527,'Residential rental property'),(P925,'Passive activity and at-risk rules')]),
'physician-tax-planning': dict(
 title='Tax Planning for Physicians & Medical Practices | AE Tax',
 h1='Tax Planning for Physicians and Medical Practice Owners',
 desc='Physician tax planning for practice owners and doctors with 1099 income. Coordinate entity choices, owner pay, retirement planning and real estate with AE Tax.',
 intro='Build a tax plan around how you earn your income: medical practice profits, independent contractor work, employment, or a combination of these and investment property.',
 sections=[
 ('Medical practice owners and 1099 physicians','<p>AE Tax Advisors serves physicians who own practices or have business income that needs coordinated advisory and compliance work. A doctor running a practice has different decisions from an employed physician with only W-2 income. Start by mapping income sources, ownership, payroll, retirement arrangements and major transactions.</p><p>This service can be relevant when starting independent contractor work, buying into a practice, changing an entity, hiring staff, buying a practice building or preparing for a sale. The objective is a plan with defined actions and responsibilities, rather than an advertised savings amount.</p>'),
 ('Match the planning review to your income',table(['Physician situation','Planning questions'],[
 ('Practice owner','How do owner pay, staff costs, retirement funding and distributions fit the practice’s cash flow?'),('1099 or locum tenens work','Which expenses, entity choices, estimated payments and retirement options need review?'),('W-2 employment plus a business','Which income and benefits belong to the employer, and which belong to the separate business?'),('Practice owner with rentals','Who owns each asset, and how do rental activity and owner-level limits affect the combined return?')])+'<p>W-2 wages do not become business receipts simply because a physician forms an LLC. Separate the employment relationship from any actual independent business.</p>'),
 ('Entity choices and S-corporation owner pay','<p>Before an entity election, compare projected compensation, payroll administration, state treatment, benefits, distributions and longer-term ownership plans. The IRS requires reasonable compensation for services by S-corporation shareholder-employees before non-wage distributions. See '+link(SALARY,'IRS guidance on S-corporation compensation')+'.</p><p>Use '+link('/reasonable-compensation/','the S-corp owner salary guide')+' to assemble the role and pay evidence. A target tax saving does not establish the appropriate salary.</p>'),
 ('Retirement planning without ignoring the practice budget','<p>Compare available plan designs with employee eligibility, expected contributions, administration and cash commitments. A larger deduction can require a larger funded commitment. Coordinate the practice’s plan with other arrangements and the responsible plan administrator. See '+link(RETIRE,'IRS retirement plans for self-employed people')+'.</p><p>Discuss '+link('/retirement-exit-ma-tax-strategy/','retirement and exit planning')+' before adopting a plan or making a transaction commitment. Tax modeling should state the year and assumptions used.</p>'),
 ('Practice buildings and investment property','<p>Keep the practice operating business, property ownership and rental activity distinct in the records. A building purchase may call for basis reconciliation and a separately scoped depreciation study. Rental losses require their own analysis; professional status as a physician says nothing about real estate participation.</p><p>Review '+link('/cost-segregation-for-medical-office/','medical-office cost segregation')+' or '+link('/cost-segregation-airbnb/','residential STR cost segregation')+' for the property involved. AE’s core study audience is residential investment property; confirm whether a medical-office project fits the current scope.</p>'),
 ('Engagement scope, fees and first steps',fee()+'<p>Confirm the physician, practice entities, states, payroll review, tax returns and property work covered by the proposal. Name the professional responsible for each filing and the records needed from your bookkeeper or current CPA. '+link('/bios/','Meet the advisor team')+'.</p>'+bullets(['Summarize W-2, 1099, practice and investment income.','List entity ownership, staff and current retirement plans.','Identify purchases, buy-ins, equipment changes or a planned exit.','Explain what your current preparer handles and where you need additional help.']))],
 faqs=[('Is this service for employed doctors?','The focus is practice owners and physicians with business or investment complexity. A W-2-only situation may need a different scope; discuss fit on the first call.'),('Do all 1099 physicians need an S corporation?','No. Evaluate the facts, compensation, benefits, state rules and administration before choosing an entity.'),('Can you coordinate practice income and rental properties?','That can be part of a scoped advisory engagement. Property study and return-preparation fees are separate and should be confirmed.'),('Do you guarantee six-figure savings?','No. Results depend on income, records, eligibility, implementation and timing. A written model should distinguish deductions, current savings and deferrals.'),('Can I retain my current accountant?','Discuss the coordination arrangement and make sure the engagement assigns implementation and filing responsibilities.')],
 links=[('/physician-tax-planning-save-six-figures/','How to evaluate a physician tax savings projection'),('/business-owner-tax-planning/','Advisory for business and practice owners'),('/pricing/','Published fees')],sources=[(SALARY,'S-corporation compensation'),(RETIRE,'Self-employed retirement plans')]),
'physician-tax-planning-save-six-figures': dict(
 title='Physician Tax Savings: Evaluate a Planning Proposal | AE Tax',
 h1='How Physicians Can Evaluate a Tax Savings Projection',
 desc='Evaluate physician tax planning proposals by separating deductions, permanent savings, deferrals and implementation costs. Use a practical comparison checklist.',
 intro='Before accepting a six-figure savings projection, ask what produces the result, when it can be used, what it costs and which assumptions remain unconfirmed.',
 article=True,
 sections=[
 ('Start with a baseline return','<p>A useful planning comparison starts with the same income, filing status, states and business facts for both scenarios. Identify the tax year and the income already earned. For practice owners, include owner compensation, staff costs, retirement commitments and cash distributions. For employed doctors, separate wages from any independent business.</p><p>Ask whether the proposed model includes all relevant taxes and costs. A comparison that changes revenue, ignores payroll costs or assumes unlimited deduction use cannot isolate the effect of the proposed strategy.</p>'),
 ('Separate four numbers that sound like savings',table(['Number in the proposal','What to ask'],[('Deduction','How much can be used this year after applicable limits?'),('Current tax reduction','Which federal and state liabilities change, and relative to what baseline?'),('Tax deferral','When could tax become payable, including on a later distribution or asset sale?'),('Net financial benefit','What remains after study fees, filing fees, administration and required cash commitments?')])+'<p>These amounts should not be added as if they measure the same thing. A cost segregation deduction, a retirement contribution and an entity change have different financial consequences.</p>'),
 ('Illustrative deduction versus tax reduction','<p><strong>Hypothetical arithmetic, not a client result:</strong> if an additional $100,000 deduction is fully usable at an assumed 30% marginal federal rate, the simplified federal tax reduction is $30,000 before fees and other effects. If only $20,000 is currently usable, the same simplified calculation is $6,000. Neither calculation establishes eligibility or total lifetime savings.</p><p>Ask the advisor to show the usable amount, the tax-rate assumption and the later-year consequences. The purpose is to compare the proposed work with its cost, rather than to treat the largest deduction as the best plan.</p>'),
 ('Questions for the person presenting the model',bullets(['Which actions remain legally and practically available for the year being modeled?','What evidence supports owner pay, property basis and the use of rental losses?','Which amounts are permanent savings and which are timing changes?','How do federal and state results differ?','Which advisor, payroll provider, plan administrator or preparer must implement each action?','What happens if income changes, the property is sold or the plan is not funded?'])+'<p>For retirement proposals, ask the responsible plan professional to explain staff coverage, administration and funding requirements. '+link(RETIRE,'The IRS retirement overview')+' describes the main types of plans.</p>'),
 ('Compare the engagement with the projection','<p>Request a written scope that identifies the analysis, deliverables, separate fees and implementation responsibilities. Retain the assumptions so the result can be revisited when the facts change. Do not rely on a headline figure as proof that the service pays for itself.</p>'+fee()+'<p>For the service discussion, start with '+link('/physician-tax-planning/','physician and medical-practice tax planning')+'. This guide explains how to assess a proposal; the service page explains fit and next steps.</p>')],
 faqs=[('Can a physician save six figures through planning?','Some facts may support a large benefit, but a headline amount is not evidence for your situation. Ask for a documented model with a consistent baseline, eligibility analysis and implementation costs.'),('Is a $100,000 deduction a $100,000 tax saving?','No. The effect depends on how much is usable, the applicable tax rates and other consequences.'),('Should I compare only the advisory fee?','Compare the entire proposed work, including separately priced studies and returns, administration and any required funding.'),('Where do I begin if I own a practice?','Begin with income sources, ownership, payroll, current benefits and upcoming transactions, then scope an advisory review.')],
 links=[('/physician-tax-planning/','Physician tax planning services'),('/cost-segregation-calculator/','Illustrative property depreciation scenario'),('/pricing/','Published engagement fees')],sources=[(RETIRE,'Retirement plan options')]),
'reasonable-compensation': dict(
 title='S-Corp Reasonable Compensation & Owner Salary | AE Tax',
 h1='S-Corp Reasonable Compensation: Document Your Owner Salary',
 desc='Set an S-corp owner salary using duties, time and comparable pay evidence. Coordinate reasonable compensation with payroll, distributions and your tax plan.',
 intro='A defensible owner salary starts with the services you perform and the evidence supporting comparable pay. Document the decision before treating distributions as a substitute for wages.',
 article=True,
 sections=[
 ('What reasonable compensation means for an S-corp owner','<p>The IRS requires S corporations to pay reasonable compensation to shareholder-employees for their services before non-wage distributions. The analysis depends on the work performed and the source of gross receipts. The IRS can reclassify payments as wages. See '+link(SALARY,'the IRS compensation guidance')+'.</p><p>A universal salary percentage cannot capture different owner roles, hours, staffing and businesses. A tax-saving target or an online benchmark alone is not a compensation analysis.</p>'),
 ('Build an owner role inventory',bullets(['List the professional, production, management, sales and administrative work you actually perform.','Estimate time by role and identify changes during the year.','Record qualifications, relevant experience and responsibilities.','Describe what employees, contractors and other owners do.','Identify revenue supported by your services versus staff or other business resources.'])+'<p>For multiple businesses, keep the work and compensation records for each entity consistent. Use '+link('/s-corp-owner-pay-across-related-companies/','the related-company owner-pay guide')+' when responsibilities cross entity boundaries.</p>'),
 ('Compare pay evidence with the actual job','<p>Use comparable roles and document the source, date, geography, hours and responsibilities behind the comparison. Explain adjustments when the comparison differs from the owner’s work. Preserve the analysis rather than only recording the final number.</p>'+table(['Evidence','What to document'],[('Role and time record','The services provided, hours and responsibilities during the year.'),('Pay comparison','Why the selected jobs and geographic market are comparable.'),('Business operations','How other workers and business assets contribute to receipts.'),('Implementation record','Approved compensation, payroll reporting and any later changes.')])+'<p>Revisit the file when hours, staff, duties or business operations materially change.</p>'),
 ('Coordinate salary, distributions and benefits','<p>The planning model should show payroll administration, distributions, benefits and the owner’s broader return. A lower salary is not automatically the best overall result. Before changing payroll, identify who approves the change and who handles reporting.</p><p>Discuss '+link('/business-owner-tax-planning/','business-owner tax advisory')+' if salary decisions need to be coordinated with entity structure, retirement plans or rental holdings. Review '+link('/s-corp-health-insurance-missing-w2-after-filing/','owner health-insurance reporting')+' when the W-2 and benefit records need reconciliation.</p>'),
 ('What to request from an advisor','<p>Request a written record of the owner’s work, comparison evidence, assumptions, recommended compensation and implementation responsibilities. Confirm whether payroll changes and return preparation are part of the engagement or handled by other professionals.</p>'+fee()+'<p>For the first call, summarize your business, ownership, owner duties, existing payroll and distributions. Exchange payroll and return records through the agreed secure process after the work is scoped.</p>')],
 faqs=[('Is the 60/40 salary rule an IRS safe harbor?','No universal salary-to-distribution ratio establishes reasonable compensation. Evaluate the services and supporting evidence.'),('Can the salary be based only on profit?','Profit alone does not establish the value of the owner’s work. Consider duties, time, responsibilities and comparable pay evidence.'),('Does a compensation analysis prevent an audit?','No. It documents the reasoning and evidence; it cannot guarantee an audit outcome.'),('Should I revisit salary every year?','Review whether duties, time, staffing, compensation evidence or business operations changed and update the file when needed.'),('Can AE help coordinate the review?','Discuss the owner-pay issue as part of the advisory scope, and confirm who handles payroll implementation and filing.')],
    links=[('/services/reasonable-compensation/','Reasonable compensation analysis service'),('/business-owner-tax-planning/','Business-owner tax advisory'),('/s-corp-owner-pay-across-related-companies/','Owner pay across related companies'),('/pricing/','Advisory and payroll service pricing')], sources=[(SALARY,'S-corporation compensation and benefits')]),
'form-3115-cost-segregation': dict(
 title='Form 3115 Preparation & Cost Segregation Lookback | AE Tax',
 h1='Form 3115 for Cost Segregation and Missed Depreciation',
 desc='Review Form 3115 preparation for cost segregation lookback studies. Reconcile prior depreciation, determine the correction procedure and confirm filing scope.',
 intro='An existing property needs more than a new depreciation report. Establish the correct correction procedure, reconcile the asset history and assign responsibility for the filing.',
 sections=[
 ('When a cost segregation lookback needs a filing review','<p>A lookback study revisits depreciation for an existing property. Form 3115 requests a change in accounting method or the treatment of an item, but it is not the correct procedure for every error. Begin with the filed returns, acquisition and service dates, ownership, elections and depreciation actually claimed. See '+link(F3115,'IRS Form 3115 instructions')+'.</p><p>AE Tax Advisors can discuss the study, reconciliation and filing work needed for the particular property. The proposal should identify who determines the correction procedure and who prepares the return and any method-change application.</p>'),
 ('Form 3115, amendment or current schedule?',table(['What the file shows','Review before choosing a procedure'],[('A treatment carried through prior returns','Whether an accounting method was adopted and a change procedure applies.'),('A first-year error or isolated mistake','Whether an amendment or another correction is appropriate.'),('Property sold or ownership changed','Whether eligibility and disposition facts affect the available procedure.'),('Report completed after a filing deadline','Which year and filing route remain available; do not assume a late report cures a missed requirement.')])+'<p>Use '+link('/amended-return-vs-form-3115/','the amended-return versus Form 3115 guide')+' for the comparison and '+link('/cost-segregation-after-extension-deadline/','the after-deadline guide')+' for late-report questions.</p>'),
 ('Reconstruct the depreciation history','<p>The review file should reconcile the purchase documents, supported land allocation, building basis, separately purchased assets, improvements and every prior depreciation schedule. Resolve duplicates and missing records before applying a new classification.</p>'+bullets(['Original acquisition and placed-in-service dates.','Ownership entity and relevant changes in ownership.','Depreciation schedules and filed returns for prior years.','Improvement invoices, earlier studies and asset dispositions.','Any elections or prior correction work affecting the assets.'])+'<p>See '+link('/cost-segregation-documents-checklist/','the study document checklist')+' and '+link('/blog/cost-segregation-report-basis-reconciliation/','report-to-basis reconciliation')+'.</p>'),
 ('Understand the Section 481(a) reconciliation','<p>Where the method-change procedure applies, the workpaper compares the relevant prior treatment with the proposed treatment to prevent omission or duplication. The calculation and timing depend on the change and applicable procedure. It is not simply a percentage of the purchase price.</p><p>The preparer should use the rules applicable to the assets and tax years involved. Ordering a study today does not replace historical depreciation rules with today’s bonus percentage. '+link(P946,'IRS Publication 946')+' provides depreciation guidance.</p>'),
 ('Agree on the preparation and filing deliverables','<p>Ask the preparer to identify the governing procedure, eligibility conditions, applicable change number, required form sections, statements and adjustment workpaper. Confirm the taxpayer, year of change, return deadline and any duplicate-copy requirement using current IRS guidance.</p><p>A completed study is not evidence that the application was prepared or filed. Request a final signed packet, the return attachment and records of the required submissions. See '+link(F3115,'current Form 3115 instructions and updates')+'.</p>'),
 ('Study pricing and implementation scope',fee('study')+'<p>Confirm separately whether the engagement includes prior-schedule reconstruction, method-change analysis, Form 3115 preparation, state adjustments and tax-return filing. A catch-up calculation in the study scope does not automatically include every implementation task.</p><p>If your existing CPA files the return, establish '+link('/cost-segregation-cpa-coordination/','the preparer handoff')+' before ordering the study. Discuss suspended losses and future disposition consequences as part of the owner-level review.</p>'),
 ('Bring a property summary to the first call','<p>Summarize when you acquired and first used the property, how it is owned, which returns have been filed, whether a study exists and whether a sale is planned. Identify the preparer who maintains the depreciation schedule. The next step is to define the records and work required, not to promise a refund before reviewing the file.</p>')],
 faqs=[('Can Form 3115 recover missed depreciation?','It may be the appropriate method-change procedure for the facts. The preparer must establish eligibility, calculate the adjustment and evaluate deduction usability.'),('Does a new study always require Form 3115?','No. The correction route depends on the prior treatment, returns, assets and applicable procedures.'),('Is the catch-up amount an immediate refund?','No. An adjustment or deduction must be evaluated with the owner’s return and applicable limits.'),('Is preparation included in the study fee?','Do not assume it is. Confirm the distinction between a catch-up calculation, Form 3115 preparation and return filing in the written scope.'),('What if I am selling the property?','Disclose the sale timing before the review. Eligibility, correction procedures and disposition consequences need coordinated analysis.')],
 links=[('/cost-segregation-study/','Cost segregation study services'),('/form-3115-year-of-sale-rental-property/','Sale-year missed-depreciation review'),('/cost-segregation-cpa-coordination/','Study and return-preparer coordination')],sources=[(F3115,'Form 3115 instructions and subsequent developments'),(P946,'Depreciation methods and records')]),
'real-estate-investor-cpa': dict(
 title='CPA & Tax Advisory for Real Estate Investors | AE Tax',
 h1='Tax Advisory and CPA Support for Real Estate Investors',
 desc='Tax advisory for landlords and real estate investors. Coordinate rental reporting, depreciation, cost segregation, entities and separately scoped tax returns.',
 intro='Choose tax support that connects property records, entity returns and the owner’s tax position. AE Tax Advisors works with rental owners and business owners with real estate nationwide.',
 sections=[
 ('What to look for in a real estate investor CPA','<p>When comparing a CPA or tax advisor for real estate investing, ask how the firm handles the full path from records to the filed return. The proposal should identify the advisor and preparer, properties and entities, states, depreciation work and follow-up support. '+link('/bios/','Review AE’s current advisor profiles')+' and confirm the professional assigned to your engagement.</p><p>A single-family rental, a managed STR and a partnership portfolio require different records and analysis. Start with the actual operations and upcoming transactions, rather than choosing a package solely by the number of doors.</p>'),
 ('Match the service to your portfolio',table(['Investor situation','Work to coordinate'],[('Long-term rental owner','Rental reporting, asset schedules, improvements and loss carryforwards.'),('Airbnb or other STR owner','Booking history, participation, personal use and depreciation.'),('Rental partnership','Entity returns, K-1s, owner basis and debt information.'),('Business owner with property','Operating-business planning and property ownership records.'),('Acquisition or planned sale','Transaction timing, basis, disposition consequences and preparer responsibilities.')])+'<p>See '+link('/real-estate-tax-planning/','real estate tax advisory')+' for the broader portfolio planning service.</p>'),
 ('Keep depreciation connected to the books','<p>The depreciation file should tie to closing documents, supported land allocation, furnishing purchases and improvement invoices. A new study needs to be reconciled to existing assets so the return does not claim the same cost twice.</p><p>Review '+link('/cost-segregation-study/','cost segregation study services')+' for study fit and '+link('/form-3115-cost-segregation/','lookback preparation')+' for existing property. A report alone does not establish whether the owner can currently use the deduction.</p>'),
 ('Separate property activity from the owner’s loss analysis','<p>Identify how each activity is operated, which owner-level records are needed and which limitations must be checked. For STRs, bookings and work performed matter. For partnerships, keep entity and owner records consistent.</p><p>'+link(P925,'IRS Publication 925')+' describes passive-activity and at-risk rules; '+link(P527,'Publication 527')+' covers residential rental reporting. Use the relevant tax-year rules and verify the facts before relying on a loss projection.</p>'),
 ('Advisory, returns and studies have separate scope',fee()+'<p>Published business-return pricing starts at $1,500 and owner/investor personal-return pricing starts at $1,000, subject to the published conditions and complexity. Schedule E is listed at $250 per rental property per year. Do not assume these line items combine into a complete quote; confirm the signed proposal.</p>'+fee('study')),
 ('How to coordinate with an existing CPA','<p>You may need advisory work while another preparer files the returns. Confirm that the scope names the person who reviews the report, updates the asset schedule, prepares any method change and communicates owner-level assumptions. Agree on delivery dates before a filing deadline approaches.</p><p>Use '+link('/cost-segregation-cpa-coordination/','the study-to-CPA handoff guide')+' and '+link('/compare/best-tax-advisors-short-term-rental-owners/','our STR advisor comparison')+' to prepare questions for the engagement.</p>'),
 ('Prepare a portfolio summary','<p>For a first call, list property types, ownership entities, states, purchase dates and planned transactions. Explain your current tax support and whether records or asset schedules need cleanup. Detailed returns and financial documents should follow through the agreed secure collection process after the work is scoped.</p>')],
 faqs=[('Do you work with owners who have only one rental?','Discuss the property, income, upcoming decisions and service scope. The number of properties alone does not determine engagement fit.'),('Can you handle STR and long-term rental planning together?','A scoped portfolio review can coordinate both. Their operating facts and tax treatment need separate analysis.'),('Is return preparation included in advisory?','Returns are separately scoped and priced. Confirm every entity, owner return and state in the proposal.'),('Can I keep my current CPA?','Discuss an explicit handoff arrangement and assign responsibility for analysis, asset schedules and filing.'),('Will cost segregation reduce my tax bill immediately?','That depends on the property, eligibility, deduction usability and the owner’s return. A study cannot promise an immediate refund.')],
 links=[('/rental-property-tax-planning/','Long-term rental planning'),('/short-term-rental-tax-strategy/','STR planning and preparation scope'),('/pricing/','Published real estate and return fees')], sources=[(P925,'Passive activity and loss limitations'),(P527,'Rental reporting')]),
'locations/billings': dict(
 title='Tax Advisor in Billings, MT for Business Owners | AE Tax',
 h1='Tax Advisors in Billings, Montana',
 desc='AE Tax Advisors is headquartered in Billings, MT. Explore business-owner tax planning, real estate advisory, cost segregation and separately scoped returns.',
 intro='Tax advisory for business owners, practice owners and real estate investors, headquartered in Billings and serving clients nationwide.',
 local=True,
 sections=[
 ('AE Tax Advisors Billings headquarters','<p><strong>935 Lake Elmo Dr, Suite B<br>Billings, MT 59105</strong></p><p>Phone: <a href="tel:+16316145762">(631) 614-5762</a><br>Email: <a href="mailto:team@aetaxadvisors.com">team@aetaxadvisors.com</a></p><p>Book a discovery call to discuss your situation and confirm the appropriate next step. Contact the team before planning an office visit. '+link('/bios/','Meet the advisor team')+'.</p>'),
 ('Business tax planning in Billings','<p>Business owners often need to connect entity structure, owner pay, retirement funding, major purchases and estimated payments. A planning engagement should turn those questions into an action list with named responsibilities and timing, while identifying the returns and implementation work priced separately.</p><p>Explore '+link('/business-owner-tax-planning/','business-owner tax advisory')+', '+link('/reasonable-compensation/','S-corp owner salary documentation')+' and '+link('/physician-tax-planning/','medical-practice owner planning')+' for the relevant situation.</p>'),
 ('Real estate advisory for Montana property owners','<p>A local owner can have rentals, partnership interests or a business building in several states. Begin with a consistent property list, ownership records and asset schedules. Location alone does not establish deduction eligibility or eliminate the need to review state treatment.</p><p>See '+link('/real-estate-tax-planning/','real estate tax planning')+' and '+link('/short-term-rental-tax-strategy/','Airbnb and STR tax planning')+'. If you want a specialist CPA for a rental portfolio, use '+link('/real-estate-investor-cpa/','the investor tax-support page')+' to compare responsibilities and scope.</p>'),
 ('Cost segregation studies and implementation','<p>AE’s core study audience includes residential investment properties, short-term rentals, long-term rentals and small to mid-sized multifamily. Compare study fees with the usable benefit and the implementation work required for the return.</p>'+fee('study')+'<p>Use '+link('/cost-segregation-study/','the study service page')+' to review fit and '+link('/form-3115-cost-segregation/','the lookback review page')+' when prior depreciation needs attention.</p>'),
 ('Advisory and return fees',fee()+'<p>Confirm the Montana and other state filings, owner returns, business entities and additional work in the engagement. A published starting price does not determine the complete fee for a particular business or portfolio.</p>'),
 ('What to prepare before calling',bullets(['Your business type, income sources and current tax support.','Ownership entities and states where the business or properties operate.','Upcoming purchases, sales, hiring, retirement changes or filing deadlines.','The question you need resolved and whether the relevant records are available.'])+'<p>The first call establishes fit and a collection plan. Send detailed tax and financial records through the agreed secure process after scope is confirmed.</p><p>For general federal planning background, see '+link(ESTIMATES,'IRS estimated-tax guidance')+'. State-specific conclusions require review of the applicable rules and facts.</p>')],
 faqs=[('Where is AE Tax Advisors located?','AE’s published headquarters address is 935 Lake Elmo Dr, Suite B, Billings, MT 59105. Contact the team before planning an office visit.'),('Do you serve clients outside Billings?','Yes. AE publishes nationwide advisory services. Confirm the relevant states and filings in your engagement.'),('Do you provide business tax planning in Billings?','Business-owner tax advisory is a published AE service. Discuss your business, timing and current support on a discovery call.'),('Is cost segregation included in advisory?','No. The study service is separately priced; confirm the study and implementation deliverables.'),('Can I book online?','Use Book a Call to open AE’s discovery appointment page.')],
 links=[('/business-owner-tax-planning/','Business owner advisory'),('/real-estate-investor-cpa/','Real estate investor tax support'),('/pricing/','Published fees')],sources=[(ESTIMATES,'Federal estimated taxes')])
}

PAGES['services/reasonable-compensation'] = dict(
 title='S-Corp Reasonable Compensation Analysis Service | AE Tax',
 h1='Reasonable Compensation Analysis for S-Corp Owners',
 desc='Discuss an S-corp reasonable compensation analysis with AE Tax Advisors. Define owner duties, comparable pay evidence, payroll coordination and engagement scope.',
 intro='Connect a documented owner-pay analysis to the payroll and tax work that implements it. Start by defining the owner’s responsibilities and the professionals involved.',
 sections=[
 ('When to discuss an owner-pay analysis','<p>An owner-pay review can be relevant when you start an S corporation, change your role, add employees, take distributions, or discover that payroll no longer reflects your actual work. Owners working across related companies also need records that consistently assign duties and compensation.</p><p>AE Tax Advisors can discuss the review as part of business-owner advisory. Confirm the analysis, written deliverables, payroll coordination and separate preparation fees before assuming they are covered by an engagement.</p>'),
 ('Define the evidence and deliverables',bullets(['An inventory of the owner’s duties, time, qualifications and responsibilities.','Comparison evidence with sources, dates, geography and relevant job descriptions.','A written explanation of assumptions and adjustments used in the recommendation.','An implementation record assigning responsibility for payroll, distributions and reporting.','A plan to revisit the file when duties or business operations change.'])+'<p>This is a scope checklist to agree with the advisor, not a promise that every item is included in every engagement. For the educational explanation, read '+link('/reasonable-compensation/','the S-corp owner salary guide')+'.</p>'),
 ('Coordinate the review with your payroll provider','<p>Before changing compensation, identify who authorizes the payroll adjustment and who reconciles reporting to the business return. Explain any earlier salary or distribution decisions that may need attention. A recommendation should not leave the bookkeeper or payroll provider guessing about timing or responsibilities.</p><p>Use '+link('/s-corp-owner-pay-across-related-companies/','the related-company pay guide')+' if more than one entity is involved, and '+link('/business-owner-tax-planning/','business-owner tax planning')+' when compensation interacts with a broader entity or retirement review.</p>'),
 ('Agree on fees and the review boundary','<p>Request a written quote for the compensation work and identify whether it belongs in a wider advisory engagement. Confirm any separate payroll setup, correction, tax-return or follow-up work. AE’s '+link('/pricing/','published pricing')+' provides the starting point for the service discussion; it does not establish a complete compensation-analysis quote for your facts.</p><p>For a discovery call, summarize the entity, owner duties, existing payroll and distributions. The detailed payroll file and returns should follow through the agreed secure collection process after scope is established.</p>')],
 faqs=[('Is there a standard percentage that establishes my salary?','No universal salary percentage resolves the analysis. The services performed and supporting comparison evidence matter.'),('Does this guarantee an IRS audit outcome?','No. A documented analysis explains the recommendation and evidence; it cannot guarantee an examination result.'),('Can the review work with my existing payroll provider?','Discuss the coordination arrangement and name the person who handles payroll implementation and reporting.'),('How much does the analysis cost?','Confirm the compensation work in a written proposal, including whether it is part of advisory and which additional services are separately priced.')],
 links=[('/reasonable-compensation/','Owner salary guide and evidence checklist'),('/business-owner-tax-planning/','Business-owner advisory'),('/pricing/','Published service fees')],sources=[(SALARY,'IRS S-corporation compensation guidance')])

def render(slug, data):
    file = ROOT/slug/'index.html'
    original = file.read_text()
    published = re.search(r'property="article:published_time" content="(\d{4}-\d{2}-\d{2})',original)
    published = published.group(1) if published else '2026-09-12'
    path = '/'+slug+'/'
    trail = [('Home','/'),('Services','/services/'),(data['h1'],path)]
    faqs = [(q,'<p>'+html.escape(a)+'</p>') for q,a in data['faqs']]
    body = page_header(h1=data['h1'],subtitle=data['intro'],trail=trail)
    body += '\n'.join(section(h,b) for h,b in data['sections'])
    body += faq_section(faqs)+related_section(data['links'])
    body += section('Sources and content updates', '<p>By AE Tax Advisors Team. Content updated October 1, 2026. '+link('/editorial-policy/','Read our editorial policy')+'.</p>'+bullets([link(url,label) for url,label in data['sources']])+'<p>General information; planning and filing decisions depend on your facts and the applicable tax-year rules. Examples are illustrative, not guaranteed outcomes.</p>')
    # Keep established contextual commercial paths so maintenance tests remain valid.
    for block in re.findall(r'<!-- commercial-owner-path -->.*?<!-- /commercial-owner-path -->',original,re.S):
        body += block
    schemas = [breadcrumb_schema(trail),faq_schema(faqs)]
    if data.get('article'):
        schemas += [article_schema(title=data['h1'],description=data['desc'],url=SITE+path,published=published,modified=DATE,citations=[u for u,l in data['sources']])]
    else:
        schemas += [{'@context':'https://schema.org','@type':'Service','@id':SITE+path+'#service','name':data['h1'],'url':SITE+path,'description':data['desc'],'provider':{'@type':'Organization','name':'AE Tax Advisors','url':SITE+'/'},'areaServed':{'@type':'Country','name':'United States'}}]
    if data.get('local'):
        schemas += [{'@context':'https://schema.org','@type':'AccountingService','@id':SITE+'/#billings-office','name':'AE Tax Advisors','url':SITE+path,'telephone':'+1-631-614-5762','email':'team@aetaxadvisors.com','address':{'@type':'PostalAddress','streetAddress':'935 Lake Elmo Dr, Suite B','addressLocality':'Billings','addressRegion':'MT','postalCode':'59105','addressCountry':'US'}}]
    file.write_text(build_page(title=data['title'],description=data['desc'],path=path,body=body,schemas=schemas,published=published,modified=DATE,og_type='article' if data.get('article') else 'website'))

EXPANSIONS = {
'cost-segregation-study': ('Compare a cost segregation company by the complete scope','<p>When searching for a cost segregation company, compare the full path from property documents to the filed return. Ask who performs and reviews the analysis, what records support the classifications, and who reconciles the report with your existing asset schedule. A provider’s headline deduction is not a substitute for a property-specific review.</p>'+table(['Before you engage','Confirm in writing'],[('Study scope','Property, billing square footage, records, methodology and deliverables.'),('Tax implementation','Who updates depreciation and prepares any required method change.'),('Owner-level review','Who evaluates usable deductions and state differences.'),('After delivery','Preparer questions, corrections and any examination support covered by the fee.')])+'<p>Start with '+link('/cost-segregation-study-cost-pricing/','published fees and scope')+', then use '+link('/cost-segregation-documents-checklist/','the document checklist')+'. For Airbnb and VRBO property, coordinate '+link('/short-term-rental-tax-strategy/','STR tax planning')+' with '+link('/cost-segregation-airbnb/','the property study')+'. For long-term rentals and small multifamily, connect the study to '+link('/real-estate-investor-cpa/','portfolio tax support')+'.</p>'),
'business-owner-tax-planning': ('Choose a proactive tax advisor by implementation','<p>If you are looking for a tax strategist for your business, compare what happens after the recommendations are presented. A useful plan names the decision, supporting assumptions, responsible professional, required records and timing. Confirm who coordinates payroll, retirement-plan work, bookkeeping changes and the tax return.</p>'+table(['Planning question','Practical deliverable to request'],[('S-corp owner pay','A role and compensation record linked to payroll implementation.'),('Entity change','A comparison of alternatives, costs and ownership consequences.'),('Retirement funding','A plan-professional review of eligibility, administration and funding commitments.'),('Business and rental income','A combined review that keeps entity and property records distinct.'),('Major purchase or exit','A documented review before committing to the transaction.')])+'<p>Start with '+link('/reasonable-compensation/','owner salary documentation')+', '+link('/physician-tax-planning/','medical practice planning')+' or '+link('/real-estate-investor-cpa/','business-owner rental holdings')+' for the relevant decision. Billings-area owners can also review '+link('/locations/billings/','our headquarters and local service information')+'.</p><p>Bring a summary of income, entities, employees and upcoming transactions to the discovery call. Ask which deliverables belong in advisory and which returns or studies are separately priced. '+link('/pricing/','Review AE’s published fees')+' before comparing proposals.</p>')
}

def add_expansion(slug, heading, content):
    file=ROOT/slug/'index.html';source=file.read_text()
    block='<!-- service-search-expansion -->'+section(heading,content)+'<!-- /service-search-expansion -->'
    source=re.sub(r'<!-- service-search-expansion -->.*?<!-- /service-search-expansion -->','',source,flags=re.S)
    marker=source.find('<h2>Frequently Asked Questions</h2>')
    insertion=source.rfind('<section',0,marker) if marker>=0 else source.find('</main>')
    source=source[:insertion]+block+'\n'+source[insertion:]
    source=re.sub(r'(property="article:modified_time" content=")[^"]+',r'\g<1>'+DATE+'T00:00:00-06:00',source)
    source=re.sub(r'("dateModified"\s*:\s*")[^"]+',r'\g<1>'+DATE,source)
    file.write_text(source)

def contextual_paths():
    groups=[
      ('/short-term-rental-tax-strategy/','Plan the tax work for your short-term rental',['airbnb-tax-deductions','short-term-rental-tax-planning-basics','short-term-rental-tax-loophole-2026','cost-segregation-airbnb']),
      ('/physician-tax-planning/','Coordinate tax planning for your medical practice',['physician-cost-segregation','physician-retirement-planning','physician-exit-strategy','cost-segregation-for-medical-office']),
      ('/business-owner-tax-planning/','Build a tax plan for your business',['s-corp-vs-llc-tax-savings','s-corp-tax-strategy','year-end-tax-planning-checklist','accountable-plan']),
      ('/form-3115-cost-segregation/','Confirm the filing work for a depreciation lookback',['blog/form-3115-missed-depreciation','cost-segregation-cpa-coordination','amended-return-vs-form-3115'])
    ]
    count=0
    for target,heading,slugs in groups:
        for slug in slugs:
            file=ROOT/slug/'index.html'
            if not file.exists(): continue
            source=file.read_text()
            block='<!-- service-search-context -->'+section(heading,'<p>'+link(target,'Review the service, records and implementation scope')+' before committing to a strategy. Confirm what your advisor and return preparer each handle, then '+link('/discovery/','book a call')+' to discuss fit and next steps.</p>')+'<!-- /service-search-context -->'
            source=re.sub(r'<!-- service-search-context -->.*?<!-- /service-search-context -->','',source,flags=re.S)
            if '</main>' not in source:continue
            file.write_text(source.replace('</main>',block+'\n</main>',1));count+=1
    print('Contextual service links:',count)

def home_paths():
    file=ROOT/'index.html';source=file.read_text()
    block='<!-- service-search-home -->'+section('Find tax planning for your situation','<p>Start with the service that matches the next decision for your business or property.</p>'+bullets([
      link('/cost-segregation-study/','Rental property cost segregation')+' — study scope, fees and return coordination.',
      link('/short-term-rental-tax-strategy/','Airbnb and VRBO tax planning')+' — operational records, participation and depreciation.',
      link('/business-owner-tax-planning/','Business owner tax advisory')+' — entity choices, owner pay and implementation.',
      link('/physician-tax-planning/','Physician and medical practice planning')+' — business income, staff and property decisions.',
      link('/form-3115-cost-segregation/','Missed depreciation and lookback preparation')+' — correction procedure and filing scope.',
      link('/locations/billings/','Tax advisory in Billings, Montana')+' — headquarters, contact details and service fit.'
    ]))+'<!-- /service-search-home -->'
    source=re.sub(r'<!-- service-search-home -->.*?<!-- /service-search-home -->','',source,flags=re.S)
    file.write_text(source.replace('</main>',block+'\n</main>',1))

def main():
    for slug,data in PAGES.items():render(slug,data)
    for slug,(heading,content) in EXPANSIONS.items():add_expansion(slug,heading,content)
    contextual_paths();home_paths()
    for slug,description in {
        'cost-segregation-study': 'Nationwide cost segregation for rental properties, Airbnb, STRs and small multifamily. Compare study fees, scope, implementation and usable tax benefit.',
        'business-owner-tax-planning': 'Tax planning for business and practice owners. Coordinate entities, owner pay, retirement plans and major transactions with AE Tax Advisors.'
    }.items():
        file=ROOT/slug/'index.html';source=file.read_text()
        old=re.search(r'<meta name="description" content="([^"]+)"',source).group(1)
        source=source.replace(old,html.escape(description,quote=True))
        source=source.replace(html.unescape(old),description)
        file.write_text(source)
    print('Rebuilt',len(PAGES),'destinations; expanded',len(EXPANSIONS),'existing service pages; added homepage discovery paths.')

if __name__=='__main__':main()
