"""Extend existing AE resources with distinct tools, source links and buyer guidance.

Run after legacy generators. Never invent reviewer signoff or client outcomes.
"""
import csv, io, json, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from site_template import SITE, build_page, page_header, section, related_section, breadcrumb_schema, article_schema, write_page
DATE = '2026-10-01'
P925 = 'https://www.irs.gov/publications/p925'
P946 = 'https://www.irs.gov/publications/p946'
P544 = 'https://www.irs.gov/publications/p544'
P527 = 'https://www.irs.gov/publications/p527'
def link(url, label, download=False, resource=None):
    attr = ' download' if download else ''
    if resource: attr += ' data-ae-resource="'+resource+'"'
    return '<a href="'+url+'"'+attr+'>'+label+'</a>'
def ul(items): return '<ul>'+''.join('<li>'+v+'</li>' for v in items)+'</ul>'
def table(headers, rows):
    return '<div class="ae-table-scroll"><table class="blog-table"><thead><tr>'+''.join('<th scope="col">'+v+'</th>' for v in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+v+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def csv_file(name, rows):
    out=io.StringIO(newline='');csv.writer(out).writerows(rows)
    dest=ROOT/'downloads'/name;dest.parent.mkdir(exist_ok=True);dest.write_text(out.getvalue())
def stamp(s):
    s=re.sub(r'(property="article:modified_time" content=")[^"]+',r'\g<1>'+DATE+'T00:00:00-06:00',s)
    return re.sub(r'("dateModified"\s*:\s*")[^"]+',r'\g<1>'+DATE,s)
def enhance(slug, name, block):
    f=ROOT/slug/'index.html';s=f.read_text()
    marker='<!-- '+name+' -->';end='<!-- /'+name+' -->'
    s=re.sub(re.escape(marker)+'.*?'+re.escape(end),'',s,flags=re.S)
    s=s.replace('</main>',marker+block+end+'\n</main>',1)
    if '/assets/decision-tool-events.js' not in s:s=s.replace('</head>','<script src="/assets/decision-tool-events.js" defer></script>\n</head>',1)
    if '/assets/decision-tools.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/decision-tools.css">\n</head>',1)
    f.write_text("\n".join(line.rstrip() for line in stamp(s).splitlines())+"\n")
def create(slug,title,h1,desc,intro,sections,sources):
    path='/'+slug+'/';trail=[('Home','/'),('Resources','/resources/'),(h1,path)]
    body=page_header(h1=h1,subtitle=intro,trail=trail)+''.join(section(h,b) for h,b in sections)
    body+=section('Sources and publication information','<p>By AE Tax Advisors Team. Updated October 1, 2026. '+link('/bios/','Meet the advisory team')+' | '+link('/editorial-policy/','Editorial standards')+'.</p>'+ul([link(u,l) for u,l in sources])+'<p>This resource organizes a decision and its supporting records. It does not establish eligibility, determine a tax-return position or promise an outcome.</p>')
    schemas=[breadcrumb_schema(trail),article_schema(title=h1,description=desc,url=SITE+path,published=DATE,modified=DATE,citations=[u for u,l in sources])]
    write_page(path,build_page(title=title,description=desc,path=path,body=body,schemas=schemas,published=DATE,modified=DATE,extra_head='<link rel="stylesheet" href="/assets/decision-tools.css"><script src="/assets/site-ux.js" defer></script><script src="/assets/decision-tool-events.js" defer></script>'))

def main():
    questions=[
      ('Initial strategy','Written plan, alternatives, assumptions and delivery date'),
      ('Implementation','Who performs each action and who confirms completion'),
      ('Entity returns','Entity count, states, preparer and separate fees'),
      ('Personal return','Owner return, K-1 coordination, states and separate fees'),
      ('Prior-year review','Years, correction procedure, amendments and separate fees'),
      ('Cost segregation','Study methodology, report reviewer and property-specific fee'),
      ('Study implementation','Depreciation reconciliation, Form 3115 responsibility and fee'),
      ('Bookkeeping and payroll','Who changes the books or payroll and what is excluded'),
      ('Ongoing access','Advisor contact, meeting cadence and response expectations'),
      ('Future work','Required renewal, optional scope and separate annual returns'),
      ('Examination support','Exactly which questions, notices or examinations are covered'),
      ('Full price','First-year total, future-year total, installments and cancellation terms')]
    csv_file('tax-advisor-engagement-scorecard.csv', [['Service or decision','Question to confirm','Firm A response','Firm A included or separate fee','Firm A source and date','Firm B response','Firm B included or separate fee','Firm B source and date','Firm C response','Firm C included or separate fee','Firm C source and date']]+[[a,b]+['']*9 for a,b in questions])
    create('tools/tax-advisor-engagement-scorecard','Tax Advisor Engagement Comparison Scorecard | AE Tax','Compare Tax Advisor Engagements by Scope and Total Cost','Download a tax advisor comparison scorecard. Compare written plans, implementation, tax returns, study fees, renewal terms and responsible professionals.',
      'Send every shortlisted firm the same brief, then compare what it commits to deliver. A fee or marketing claim alone does not establish the scope of an engagement.',[
      ('Download the comparison worksheet','<p>'+link('/downloads/tax-advisor-engagement-scorecard.csv','Download the blank engagement scorecard (CSV)',True,'advisor_scorecard')+'. Open it in a spreadsheet, add each provider’s written responses, and keep the source and date beside every material statement. Blank fields mean unresolved questions, not missing services.</p>'),
      ('Use the same buyer brief',ul(['Describe the business, ownership entities, properties, states and upcoming transaction.','List the services you need and the professional who currently prepares each return.','State the deadline and the records available. Send sensitive records only through the agreed secure process.','Request an itemized first-year quote and a separate schedule for future work.'])),
      ('Compare the deliverables',table(['Service or decision','Question to confirm'],questions)),
      ('Choose the provider that fits the work','<p>A study specialist can fit when your existing CPA handles the owner-level analysis and filing. A coordinated advisory engagement can fit when you need someone to connect business decisions, rental records and implementation. A larger firm may fit when the project needs a wider specialist team. Confirm the relevant capabilities directly rather than treating an unconfirmed item as unavailable.</p><p>AE publishes advisory, return preparation and cost segregation as separately scoped services. '+link('/pricing/','Check AE’s current service pricing')+' and '+link('/compare/tax-advisor-comparison-methodology/','the comparison methodology')+' before comparing quotes. AE publishes this worksheet and is a provider you may compare.</p>'),
      ('What to do with unanswered questions','<p>Ask the provider to identify the responsible professional, deliverable, due date and fee. Record any exclusions and required future commitments. Do not assign a numeric quality score from incomplete information. Keep written proposals so a later decision can be traced to the scope offered.</p><p>'+link('/discovery/','Book a Call',resource='advisor_scorecard')+' to discuss AE’s fit.</p>')],[(SITE+'/pricing/','AE service pricing'),(SITE+'/compare/tax-advisor-comparison-methodology/','AE comparison methodology')])

    participation=['Date','Person','Role (owner/spouse/co-host/vendor)','Property or activity','Start time','End time','Minutes','Task performed','Evidence reference','Treatment to review','Reviewer notes']
    csv_file('str-participation-log-blank.csv',[participation]+[['']*len(participation)])
    csv_file('str-participation-log-example.csv',[participation,
      ['2026-09-01','Owner A','owner','Hypothetical Cabin A','09:00','09:30','30','Responded to guest arrival questions','Platform messages EXAMPLE-01','Operating work: confirm facts','Illustration only'],
      ['2026-09-01','Spouse A','spouse','Hypothetical Cabin A','14:00','14:45','45','Restocked supplies and checked equipment','Receipt and calendar EXAMPLE-02','Operating work: confirm facts','Record separate actual work; do not duplicate shared time'],
      ['2026-09-02','Co-host A','co-host','Hypothetical Cabin A','10:00','11:00','60','Coordinated cleaning and guest issue','Manager report EXAMPLE-03','Outside-person comparison','Not owner participation'],
      ['2026-09-03','Owner A','owner','Hypothetical Cabin A','16:00','16:20','20','Reviewed investment performance only','Spreadsheet EXAMPLE-04','Investor-only work: separate for review','Do not automatically count toward participation']])
    csv_file('str-guest-stay-and-use-log.csv',[['Booking reference','Property','Arrival date','Departure date','Actual customer-use days','Rental or personal use','Services provided','Source reference','Notes']]+[['']*9])
    csv_file('str-quarterly-review-checklist.csv',[['Review item','Evidence to retain','Status','Responsible person','Review date']]+[[a,b,'','',''] for a,b in [
      ('Guest stays','Booking exports and actual rental periods'),('Personal use','Owner and family calendar with use classification'),('Owner and spouse work','Separate person/task entries and corroboration'),('Outside individuals','Manager, cleaner and vendor task reports'),('Activity definition','Property ownership and any professional grouping analysis'),('Asset records','Closing file, land support, furnishings and improvement invoices'),('Prior depreciation','Asset schedule, return history and elections'),('Tax limitations','Professional basis, at-risk and loss-usability review'),('Implementation handoff','Named preparer, report reconciliation and due date')]])
    create('guides/str-documentation-kit','STR Documentation Kit: Logs and Review Checklist | AE Tax','Short-Term Rental Documentation Kit','Download STR participation and guest-use logs, an annotated example and a quarterly review checklist. Keep owner, spouse and manager records distinct.',
      'Keep the operational facts, the source records and the tax review together. These worksheets help organize evidence; filling them out does not establish a deduction.',[
      ('Download the kit',ul([link('/downloads/str-participation-log-blank.csv','Blank participation log (CSV)',True,'str_log'),link('/downloads/str-participation-log-example.csv','Hypothetical annotated participation example (CSV)',True,'str_example'),link('/downloads/str-guest-stay-and-use-log.csv','Guest-stay and personal-use log (CSV)',True,'str_guest_log'),link('/downloads/str-quarterly-review-checklist.csv','Quarterly review checklist (CSV)',True,'str_review_checklist')])),
      ('Record people and tasks separately','<p>Record the date, actual time, task, property or activity and a reference to the supporting message, invoice or calendar record. Preserve the records themselves. A spouse’s participation can count with the taxpayer’s participation under the material-participation rules. An unrelated co-host’s work is not simply added to the owner’s time. REPS qualification is a separate analysis.</p><p>'+link('/blog/str-spouse-cohost-material-participation-hours/','Read the spouse and co-host guide')+' for the comparison. Avoid duplicating the same work when two people participate together; document each person’s actual contribution.</p>'),
      ('How to interpret the annotated example',table(['Entry','Reason it is separated'],[('Owner guest communication','Operational task with a platform message reference.'),('Spouse restocking','Separate actual task, person and evidence.'),('Co-host coordination','Outside-person hours that may matter to a comparative test.'),('Investment performance review','Investor-only work is flagged for review rather than automatically counted.')] )+'<p>All names, dates, properties and evidence references in the example are fictional. No row is a professional determination that time qualifies.</p>'),
      ('Review guest use before participation','<p>Use actual customer-use periods to evaluate the relevant rental-activity exception. A listing’s minimum-night setting is not the actual average. Keep personal-use days and services provided distinct. The worksheets do not decide the correct activity grouping or automate qualification.</p><p>Short guest stays do not alone establish material participation, building recovery period or current loss usability. '+link(P925,'IRS Publication 925')+' and '+link(P527,'Publication 527')+' explain separate parts of this review.</p>'),
      ('Make the quarterly handoff useful',ul(['Reconcile the time log with task records and identify unsupported entries.','Request property-level reports from each outside person where available.','Keep ownership, acquisition basis, improvements and depreciation records in the same review file.','Have the tax professional identify the intended participation test, other loss limitations and filing responsibilities.'])+'<p>'+link('/short-term-rental-tax-strategy/','Review AE’s STR planning service')+' or '+link('/discovery/','Book a Call',resource='str_kit')+'. Do not send completed logs through a public contact form; use the agreed secure collection process.</p>')],[(P925,'IRS: participation, spouse rules and passive activities'),(P527,'IRS: rental and personal-use reporting')])

    combined=[
      ('Start with one forecast and separate records','<p>Tax planning for a business owner buying rental property starts with the business forecast, owner income and property decision together. Keep the legal entities and activity records distinct: a combined planning discussion does not combine activities for tax purposes.</p>'+table(['Owner situation','Decision to resolve before committing'],[('Physician or practice owner','Protect operating cash, coordinate owner pay and retirement commitments, and review property use.'),('Owner of several entities','Map ownership, intercompany payments, debt and the person who reconciles each K-1.'),('Owner buying an STR','Evaluate operating arrangements, guest use, participation evidence and projected cash flow.'),('Owner buying a long-term rental','Review passive income, suspended losses and holding-period economics before assuming an immediate offset.')])),
      ('Separate deduction generation from deduction usability','<p>A cost segregation study classifies property costs. It does not establish that a rental loss offsets business or employment income. Activity classification, participation, basis, at-risk rules and other loss limits must be evaluated separately. Real estate professional status removes automatic rental treatment for qualifying taxpayers but does not itself establish material participation in every activity.</p><p>For property leased to your own business, review the self-rental and permitted grouping rules rather than assuming rent and business losses have identical treatment. A grouping requires the applicable facts and rules; common ownership alone is not the answer. '+link(P925,'Read IRS Publication 925')+'.</p>'),
      ('Compare the acquisition and the exit','<p>Use supported land and asset allocations, actual service dates and the rules for the acquisition year. A percentage estimate does not establish eligible component costs. Compare incremental deductions with the no-study depreciation schedule, then evaluate when the deductions are usable.</p><p>Accelerating depreciation changes future deductions and can change tax at sale. Real property and reclassified personal property can have different disposition treatment. A Section 1031 exchange is not a blanket deferral mechanism for every asset. Use '+link('/cost-segregation-calculator/','the calculator and holding-period comparison')+' as a discussion aid after professional input, and '+link(P544,'IRS Publication 544')+' for disposition background.</p>'),
      ('Three illustrative owner decisions',table(['Hypothetical situation','Review that changes the decision'],[('Practice owner needs cash for staffing and a rental purchase','Model operating reserves, debt service, retirement obligations and after-tax cash before sizing the purchase.'),('Contractor considers a property near year-end','Confirm readiness for intended use, documentation and filing workload; purchase or deposit alone does not resolve service timing.'),('Multi-entity owner has suspended rental losses','Reconcile activity-level carryovers and income before commissioning another study. Do not presume all passive income or dispositions free all losses.')] )+'<p>These are hypothetical planning situations, not client results or recommendations to buy property.</p>'),
      ('Agree on the implementation handoff',ul(['Written alternatives and unresolved assumptions before purchase.','Named responsibility for the study, owner-level review, bookkeeping and each return.','A schedule reconciling asset basis, depreciation and any correction method.','Separate quotes for advisory, study, returns and additional implementation work.','A follow-up after closing or operational changes to update the forecast.'])+'<p>'+link('/tools/tax-advisor-engagement-scorecard/','Download the engagement comparison scorecard')+' and '+link('/compare/best-tax-advisors-business-owners-buying-rental-property/','compare firms for this buyer situation')+'.</p>'),
      ('Prepare a useful first conversation','<p>Bring a summary of income sources, entities, states, properties, the intended transaction and current professional support. Agree on the secure collection process for returns and detailed records after scope is established.</p><p>'+link('/business-owner-tax-planning/','Business-owner advisory')+' | '+link('/real-estate-investor-cpa/','Investor tax support')+' | '+link('/pricing/','Published fees')+' | '+link('/discovery/','Book a Call',resource='business_rental_guide')+'</p>')]
    slug='real-estate-tax-strategy-business-owners';f=ROOT/slug/'index.html';old=f.read_text()
    published=re.search(r'property="article:published_time" content="(\d{4}-\d{2}-\d{2})',old).group(1)
    h1='Tax Planning for Business Owners Buying Rental Property';desc='Coordinate business income, rental acquisitions, deduction usability and implementation. Review practical owner scenarios and compare tax advisory scope.'
    trail=[('Home','/'),('Business Owner Tax Planning','/business-owner-tax-planning/'),(h1,'/'+slug+'/')]
    body=page_header(h1=h1,subtitle='Connect the business forecast and property decision before closing, then assign the study, tax review and filing work.',trail=trail)+''.join(section(h,b) for h,b in combined)
    body+=section('Sources and content updates','<p>By AE Tax Advisors Team. Updated October 1, 2026. '+link('/bios/','Advisory team')+' | '+link('/editorial-policy/','Editorial standards')+'.</p>'+ul([link(P925,'Passive activity and at-risk rules'),link(P946,'Depreciation rules and asset classifications'),link(P544,'Sales and dispositions')])+'<p>General information. Individualized conclusions require the applicable tax-year rules and your actual records.</p>')
    for block in re.findall(r'<!-- commercial-owner-path -->.*?<!-- /commercial-owner-path -->',old,re.S):body+=block
    f.write_text(build_page(title='Business Owner & Rental Property Tax Planning | AE Tax',description=desc,path='/'+slug+'/',body=body,schemas=[breadcrumb_schema(trail),article_schema(title=h1,description=desc,url=SITE+'/'+slug+'/',published=published,modified=DATE,citations=[P925,P946,P544])],published=published,modified=DATE,extra_head='<link rel="stylesheet" href="/assets/decision-tools.css"><script src="/assets/site-ux.js" defer></script><script src="/assets/decision-tool-events.js" defer></script>'))

    holding='''<p>A large first-year deduction can still have limited holding-period value. Enter the incremental tax cash flows from a reviewed study-versus-no-study projection. This tool performs cash-flow arithmetic; it does not calculate depreciation, recapture, eligibility or taxes. Do not copy the first-year result into every year.</p>
<form id="holding-period-form"><div class="scenario-grid">
<label>Holding period (whole years)<input name="years" type="number" min="1" max="40" step="1" required></label>
<label>Total up-front study and implementation fee ($)<input name="fee" type="number" min="0" max="1000000000000" step="any" required></label>
<label>Additional tax at sale versus no study ($)<input name="exitTax" type="number" min="0" max="1000000000000" step="any" required></label>
<label>Annual discount rate (%)<input name="discount" type="number" min="0" max="100" step="any" required></label></div>
<label for="holding-benefits">Year-by-year tax cash-flow differences ($), one number per year</label>
<textarea id="holding-benefits" name="benefits" rows="5" required aria-describedby="holding-input-help" style="width:100%;padding:12px;font:inherit"></textarea>
<p id="holding-input-help">Use positive amounts for tax reductions and negative amounts for extra tax from lower later deductions. Enter one signed number for each holding year, separated by commas or newlines. Exclude fees and sale tax from these amounts because they are entered separately. Include actual usability, state effects and fee tax treatment in the professionally reviewed projection.</p>
<button class="btn-cta" type="submit">Compare holding-period cash flows</button></form>
<div id="holding-period-result" role="status" aria-live="polite">No assumptions have been filled in. Enter reviewed cash-flow differences to compare.</div>
<h3>Worked cash-flow example</h3><p>For a hypothetical three-year hold with annual differences of $20,000, -$2,000 and -$2,000, an up-front fee of $3,000, additional sale tax of $10,000 and a 5% discount rate, the undiscounted difference is $3,000 and net present value is approximately $3,868. The example illustrates arithmetic, not a typical property result.</p>
<p>Fees are paid at time zero. Annual tax differences and sale tax are assumed to occur at each year-end; sale tax occurs in the final year. Net present value equals the sum of each annual difference less that year’s sale tax, discounted by (1 + rate) raised to the year number, minus the up-front fee. Compare different holding periods by changing both the period and its reviewed cash-flow schedule.</p>
<p>A full forecast can include loss releases, differing asset classes, future depreciation, state taxes, sale structure and more. This worksheet cannot determine those amounts. No inputs are stored or transmitted. '''+link(P544,'IRS disposition guidance')+' | '+link('/discovery/','Book a Call',resource='holding_period')+'</p>'
    enhance('cost-segregation-calculator','holding-period-comparison',section('Compare holding-period cash flows',holding))
    f=ROOT/'cost-segregation-calculator/index.html';s=f.read_text()
    if '/assets/holding-period-cashflow.js' not in s:s=s.replace('</head>','<script src="/assets/holding-period-cashflow.js" defer></script>\n</head>',1)
    f.write_text(s)

    # Scope tools link from existing comparison destinations without new thin comparisons.
    for slug in ['compare','compare/best-tax-advisors-business-owners-buying-rental-property','compare/peter-holtz-cpa-vs-ae-tax','compare/prime-path-advisory-vs-ae-tax','compare/neil-jesani-advisors-vs-ae-tax','compare/rainwater-cpa-vs-ae-tax','compare/wcg-cpas-vs-ae-tax','compare/the-real-estate-cpa-vs-ae-tax','compare/proactive-tax-advisor-pricing-guide']:
        if (ROOT/slug/'index.html').exists():enhance(slug,'engagement-scorecard',section('Compare written proposals on the same facts','<p>'+link('/tools/tax-advisor-engagement-scorecard/','Use the engagement comparison scorecard')+' to confirm the written plan, implementation owner, filings, excluded work, first-year price and future commitments. '+link('/downloads/tax-advisor-engagement-scorecard.csv','Download the blank worksheet',True,'advisor_scorecard')+'. A blank response means a question to resolve directly with the firm, not evidence that a service is unavailable.</p>'))
    for slug in ['short-term-rental-tax-strategy','material-participation','blog/str-spouse-cohost-material-participation-hours','resources','guides']:
        enhance(slug,'str-kit-discovery',section('Prepare the records behind an STR decision','<p>'+link('/guides/str-documentation-kit/','Get the STR documentation kit')+' for blank participation and guest-use logs, a hypothetical annotated example, and a quarterly review checklist. Keep operational facts separate from the professional tax conclusion.</p>'))
    for slug in ['business-owner-tax-planning','real-estate-investor-cpa','compare/best-tax-advisors-business-owners-buying-rental-property']:
        enhance(slug,'business-rental-decision',section('Own a business and plan to buy rental property?','<p>'+link('/real-estate-tax-strategy-business-owners/','Connect the business forecast, property decision and filing handoff')+' before closing. The guide covers practice owners, owners of multiple entities, STR buyers and long-term rental buyers.</p>'))
    # Existing service and blog pricing destinations retain distinct reader purposes.
    enhance('cost-segregation-study-cost-pricing','pricing-service-intent',section('Pricing for an engagement versus budgeting for a study','<p>This page describes AE’s published study pricing and the scope to confirm in a proposal. For the factors that change a study budget and questions to ask any provider, read '+link('/blog/cost-segregation-study-cost/','the study-cost budgeting guide')+'. '+link('/cost-segregation-calculator/','Compare cash-flow assumptions')+' before ordering.</p>'))
    enhance('blog/cost-segregation-study-cost','pricing-budget-intent',section('Get a scope-based AE quote','<p>Use this guide to compare cost drivers and proposal questions. AE’s '+link('/cost-segregation-study-cost-pricing/','published study pricing and service scope')+' is the destination for its current fees. The '+link('/tools/tax-advisor-engagement-scorecard/','engagement scorecard')+' separates study delivery from filing and owner-level advisory.</p>'))
    f=ROOT/'blog/cost-segregation-study-cost/index.html';s=f.read_text();s=re.sub(r'<title>.*?</title>','<title>Cost Segregation Study Budget: Fees and Scope | AE Tax</title>',s,count=1,flags=re.S)
    s=re.sub(r'(<meta (?:name|property)="(?:og:title|twitter:title)" content=")[^"]+',r'\g<1>Cost Segregation Study Budget: Fees and Scope | AE Tax',s);f.write_text(s)

    # Remove stale language remaining after a previous release removed numeric estimates.
    for f in (ROOT/'compare').glob('*/index.html'):
        s=f.read_text();original=s
        s=re.sub(r'Pricing shown for the competitor is an estimated starting level based on market information available to AE Tax Advisors, not a published quote or guaranteed fee\.', 'A competitor fee is shown only when the page identifies a verified published source; otherwise request a current quote.',s)
        s=s.replace('Public service models and estimated starting prices reviewed September 20, 2026. Confirm current scope and fees directly.','Public service models reviewed September 20, 2026. Unverified competitor prices are not presented as quotes; confirm current scope and fees directly.')
        s=re.sub(r'AE Tax Advisors estimates that ([^<.]+) engagements start around <strong>Current fee not publicly verified; request a quote</strong>\. This is market information rather than a published quote or guaranteed fee\.',r'A current numeric fee for \1 was not verified in the cited official sources. Request a written quote.',s)
        s=s.replace('This is market information, not a published quote, and actual pricing can vary by scope.','Actual pricing can vary by scope; unverified historical estimates are not used as current fees.')
        if s!=original:f.write_text("\n".join(line.rstrip() for line in stamp(s).splitlines())+"\n")
    f=ROOT/'compare/tax-advisor-comparison-methodology/index.html';s=f.read_text()
    s=s.replace('Competitor price figures are labeled as estimates unless the competitor publishes the amount. An estimate is not a quote, guarantee, or claim that every client pays the same fee.','Competitor numeric prices are included only when supported by an identified, dated official published source. If a current fee is not verified, the comparison asks the reader to request a quote. Unverified historical market estimates are not treated as current prices.')
    s=s.replace('No, unless a page expressly identifies a published price. The competitor figures in this comparison cluster are market estimates available to AE Tax Advisors and must be confirmed directly with each firm.','Only a price linked to a dated official published source is presented as a published fee. Otherwise, request a current written quote; historical market estimates are not used as current prices.')
    s=s.replace('Comparison pages display a reviewed date.','A content update date does not establish professional review signoff. Comparison pages should distinguish a source-check date from any documented professional review date.')
    f.write_text("\n".join(line.rstrip() for line in stamp(s).splitlines())+"\n")
    enhance('editorial-policy','review-evidence-policy',section('Professional review and outcome evidence','<p>A named reviewer credit belongs on a page only after that professional has actually reviewed the material and authorized the credit. A content update date, team byline or link to the advisory team does not establish professional signoff.</p><p>A client-outcome case study should distinguish the original issue, selected strategy, implementation, filed-return change and realized outcome. Keep supporting records and publication approval in the internal file; do not expose client returns or identifying information. A publisher-reported outcome without that evidence must not be described as independently verified. Hypothetical examples should be labeled prominently.</p>'))
    for slug in ['case-studies/medical-practice-c-corp-retirement-stacking','case-studies/multi-entity-real-estate-operating']:
        enhance(slug,'case-evidence-boundary',section('Read the outcome with its evidence boundary','<p>This is a publisher-reported, anonymized case. The source returns and realized savings have not been independently verified for this website update. The published amount is not a forecast for another owner.</p>'+table(['Before applying a similar approach','Evidence to reconcile'],[('Original issue','Prior returns, entity ownership and the business or property facts.'),('Chosen strategy','Alternatives, assumptions and the reason this strategy fit those facts.'),('Implementation','Actions completed, dates, responsible professionals and separate fees.'),('What changed on the return','Relevant schedules and a reconciliation between the earlier and filed positions.'),('Realized outcome','Separate a deduction, tax deferral, tax reduction and actual refund; identify the period.')] )+'<p>'+link('/editorial-policy/','Read the evidence standard')+' or '+link('/discovery/','Book a Call',resource='case_evidence')+' to review your own facts.</p>'))
    enhance('resources','decision-resources',section('Compare the next decision',ul([link('/real-estate-tax-strategy-business-owners/','Business owners buying rental property'),link('/tools/tax-advisor-engagement-scorecard/','Tax advisor engagement scorecard'),link('/cost-segregation-calculator/#holding-period-form','Holding-period cash-flow comparison')])))
    print('Decision tools and existing-page improvements generated.')

if __name__=='__main__': main()
